swagger-api/swagger-codegen

src/main/scala/com/wordnik/swagger/codegen/Codegen.scala, src/test/scala/CodegenTest.scala
I found that I needed two extra variables in the generator/mustache templates. I thought other people might find these useful as well.
"first" - the first query param, this could also be aded for the other types of params
"hasRequiredParams" - a flag to indicate the presence of required params
=> Adding first and hasRequiredParams parameters to Codegen

src/main/java/com/wordnik/swagger/codegen/CodegenOperation.java, src/main/java/com/wordnik/swagger/codegen/languages/JaxRSServerCodegen.java, src/main/resources/JavaJaxRS/api.mustache
Fix JaxRS codegen to only generate @PATH annotation on a given resource function when that function is a "sub resource" (e.g. @PATH("/{id}") or @PATH("/{id}/operation").
*Swagger YAML:*
```
paths:
/charges:
post:
description: Create a charge
operationId: createCharge
parameters:
-
name: body
in: body
description: Charge to create
required: true
schema:
$ref: '#/definitions/Charge'
responses:
200:
description: Success - Duplicate transaction detected and previous charge returned
schema:
$ref: '#/definitions/Charge'
```
*Would generate the following:*
```
@Path("/charges")
@Api(value = "/charges", description = "the charges API")
@Produces({"application/json"})
public class ChargesApi {
@POST
@Path("")
@ApiOperation(value = "", notes = "Create a charge", response = Charge.class) …
```
=> JAXRS Codegen should omit @PATH variable when it is not necessary

src/main/resources/php/api.mustache
=> Rework generated PHP function comments.

src/main/java/com/wordnik/swagger/codegen/DefaultGenerator.java
This is a fix for resolving the standard templates for a run of Codegen under windows. 
For me it did not work for language java and this is because the config appends  `File.separator` to the template path (either passed by parameter or standard path). When searching this in the classpath however it has to be slashes in every environment.
I've added a method to DefaultGenerator that returns the path with slashes. It is used only when searching the template in the classpath.
Please consider merging this.
Best regards
Fleque
=> Fix for template resolving from classpath on windows

src/main/java/com/wordnik/swagger/codegen/DefaultCodegen.java
Hi.
This fixes the selection of methodResponse for code generation. Before the change only responses with statusCode 200 were considered. If none present (fore example for a post-request to create a new resource responding with 201) this was not used and the "default" if present was used instead.
This fixes the selection in the way that it will use the response definition with the smalles 2xx value present as method result.
Best regards
Fleque
=> Fix for the selection of the methodResponse during code-generation

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/languages/ScalaClientCodegen.java, modules/swagger-codegen/src/main/resources/scala/apiInvoker.mustache, modules/swagger-codegen/src/main/resources/scala/pom.mustache
When generating Scala client, the ApiInvoker is a class with
overridable options, avoiding the need of public vars to be
manually modified.
Additionally it is possible to plug the AsyncHttp protocol
for Jersey in order to achieve Netty support and maximum scalability.
NOTE: Support for Scala 2.10.0-3 removed as largely obsolete
=> Support for HTTP Async client transport for Jersey on Scala

build.sbt, sbt, src/main/resources/scala/apiInvoker.mustache, src/main/resources/scala/pom.mustache, src/main/scala/com/wordnik/swagger/codegen/BasicScalaGenerator.scala
When generating Scala client, the ApiInvoker is a class with
overridable options, avoiding the need of public vars to be
manually modified.
Additionally it is possible to plug the AsyncHttp protocol
for Jersey in order to achieve Netty support and maximum scalability.
=> Support for HTTP Async client transport for Jersey on Scala (legacy master)

modules/swagger-codegen/src/main/resources/scala/api.mustache
Gets rid of the smelly vars inside Scala api.mustache allowing the
override of default basePath and ApiInvoker on the constructor.
Previously the code for overriding was:
val myApi = new MyApi()
myApi.basePath = "http://myapi.endpoint.com"
myApi.apiInvoker = new ApiInvoker(authScheme = "SPNEGO")
after the change everything can be simply declared in the constructor:
val myApi = new MyApi("http://myapi.endpoint.com",
new ApiInvoker(authScheme = "SPNEGO"))
=> Scala api.mustache: allow easy basePath and ApiInvoker override

bin/html.sh
I fixed/updated the swagger.json example URL in the html.sh script so that it would be able to generate a sample again.
Previously it was breaking:
=> Fixed The html.sh Sample Generation Script

modules/swagger-codegen/src/main/resources/scala/apiInvoker.mustache
Default authentication scheme is a String and must be later
on decoded as Realm enum
=> SPNEGO auth fix: Authentication scheme should be set as String

modules/swagger-codegen/src/main/resources/scala/api.mustache
When default values have been provided with the api.mustache
constructor, backward compatibility was broken because of the public
instance variables becoming immutable vals whilst they were vars before.
We can now use the constructor arguments as default values for the internal
vars and establish backward compatibility with existing code.
=> Scala api.mustache: make new constructor backward compatible

modules/swagger-codegen/src/main/resources/php/Swagger.mustache
When working with empty arrays in the php library, I was getting an error message "Undefined variable: values".
=> Minor fix to cater for empty array in php

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/languages/PythonClientCodegen.java
Running ./bin/java-petstore.sh on Windows fails with StringIndexOutOfBoundsException
```
Exception in thread "main" java.util.ServiceConfigurationError: com.wordnik.swagger.codegen.CodegenConfig: Provider com.wordnik.
swagger.codegen.languages.PythonClientCodegen could not be instantiated
at java.util.ServiceLoader.fail(ServiceLoader.java:224)
at java.util.ServiceLoader.access$100(ServiceLoader.java:181)
at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:377)
at java.util.ServiceLoader$1.next(ServiceLoader.java:445)
at com.wordnik.swagger.codegen.Codegen.getExtensions(Codegen.java:111)
at com.wordnik.swagger.codegen.Codegen.<clinit>(Codegen.java:19)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 1
at java.lang.String.charAt(String.java:658) …
```
=> Fix StringIndexOutOfBoundsException on Windows

src/main/resources/python3/swagger.mustache
I generate clients for APIs that deliver datetimes in other ISO8601 formats, for example YYYY-MM-DDTHH:mm:ssZ.
Requested for develop_2.0 branch in https://github.com/swagger-api/swagger-codegen/pull/377
=> python3: support more iso8601 datetime formats

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/Codegen.java
The --auth parameter was setup to ignore values. It is still optional but now will accept a value.
=> The --auth parameter was setup to ignore values.

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/test/scala/Java/JavaModelTest.scala
Getter and Setter with 2nd chars being uppercase are not generated following the Sun specification : http://download.oracle.com/otn-pub/jcp/7224-javabeans-1.01-fr-spec-oth-JSpec/beans.101.pdf?AuthParam=1424762391_ef17a82335203d9fbf095a2f819eb317
Chapter 8.8.
When you generate a getter and setter, you should get : 
fooBah --> getFooBah
mAttr --> getmAttr
That was not the cas, we got previously, which is wrong.
fooBah --> getFooBah
mAttr --> getMAttr
I have made a new function called getterAndSetterCapitalize which takes a String and return the proper capitalized name for getter and setter.
=> Defect (Issue #445) : change the call of initialCaps for getter and setter proper generation

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/CodegenResponse.java, modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/test/resources/2_0/responseSelectionTest.json, modules/swagger-codegen/src/test/scala/CodegenTest.scala
Hi,
In my clients, I want to be able to handle every response, not only the 200 (or default) one.
If order to achieve this, some more informations are required in CodegenResponse, ie dataType of each of them.
This pull request add the kind of type information (dataType, isPrimitive, map/list, ...) you find on an operation inside CodegenResponse.
In the same time, the fromOperation method has been refactored, in order to:
- add the default response to the CodegenOperation.responses list
- remove unnecessary loops and Map.get operations
- reduce code size and factorization of return type discovery
Tests have been added in CodegenTest, using new json files, in order to test default return type selection.
=> Implements CodegenResponse, and return default response in Operaiton.Responses (#293)

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/CodegenConfig.java, modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/CodegenModelType.java, modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/CodegenOperation.java, modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/CodegenSecurity.java, modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/DefaultGenerator.java
A template can now refer to the type ( oath2.0, apiKey, basic )
as well as the name of the security schemes it rquires.
Usage :
{{#operations}}
{{#authMethods}}
{{type}}  {{name}}
{{/authMethods}}
{{/operations}}
=> Expose Security schemes of operations.

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/DefaultGenerator.java
Make {{basePath}} value in support files be the
same as in operation files, aka host/path, instead of /path.
=> Fix {{basePath}} value in support files.

modules/swagger-codegen/src/main/resources/php/api.mustache
use baseName for parameters (query, header, form) in PHP api method/function (other clients like Java also use baseName instead of paramName for query, header and form parameters in api method/function )
=> use baseName for parameter name in PHP api

modules/swagger-codegen/src/main/resources/php/Swagger.mustache
Adding a new exception so that the curl response and response info will be accessible to the main process in case additional information about the error is passed either through the response or response headers.
=> PHP Bindings: exposing response and response info in Exceptions

modules/swagger-codegen/src/main/resources/php/Swagger.mustache, samples/client/petstore/php/Swagger.php
1) syntax error `PHP Parse error:  syntax error, unexpected '[' in Swagger.php on line 223` due to the following:
`$subClass = explode(',', $inner, 2)[1];`
not sure if it's due to me not using the latest version of php, I workaround the issue by moving the [1] to the next line with a temporary variable so that php5.3 can compile it without syntax error
2) updated array comparison to case insensitive so that it works for both array of primitive type and array of model
3) updated PHP sample
=> Bug fixes for Swagger.php deserialize function

modules/swagger-codegen/src/main/resources/php/Swagger.mustache
This new exception had a typo in it for the construct class declaration.
=> Fixing bug in new APIClientException

modules/swagger-codegen/src/main/resources/php/Swagger.mustache, samples/client/petstore/php/Swagger.php
Allow developers to customize the user agent in PHP API client. If not set, default to "PHP-Swagger".
=> update User-agent in PHP API client

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/CodegenSecurity.java, modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/DefaultCodegen.java
Hi,
This PR allows one to access definitions of security schemes.
The following members are available : 
```
- isBasic
- isApiKey
- isOAuth
```
In case of ApiKey scheme, the following members can be used : 
```
- apiKeyParamName
- isKeyInQuery
- isKeyInParam
```
=> Adding defintion of security schemes in CodegenSecurity

modules/swagger-codegen/src/main/resources/Java/api.mustache
to make it clear and also allow a query parameter to be set with string value: "null" (4 characters string)
=> update null comparison for query params in Java

modules/swagger-codegen/src/main/resources/php/model.mustache
Adding in the ability to access and generate models as/from arrays.  This makes it easier to generate response and requests models for testing binding usage as well as creating request models in subsequent code.
=> PHP Generated Models

README.md
Update codegen usage in README.md with Ruby:
```
-l,--lang <arg>           client language to generate.
Available languages include:
[android, async-scala, java, jaxrs, nodejs,
objc, scalatra, scala, dynamic-html, html,
swagger, tizen, php, ruby, python]
```
=> update README with ruby on the codegen usage

modules/swagger-codegen/src/main/resources/ruby/api.mustache, modules/swagger-codegen/src/main/resources/ruby/model.mustache, samples/client/petstore/ruby/lib/PetApi.rb, samples/client/petstore/ruby/lib/StoreApi.rb, samples/client/petstore/ruby/lib/UserApi.rb, samples/client/petstore/ruby/models/Category.rb, samples/client/petstore/ruby/models/Order.rb, samples/client/petstore/ruby/models/Pet.rb, samples/client/petstore/ruby/models/Tag.rb, samples/client/petstore/ruby/models/User.rb
- Bug fix for Ruby header parameter: the current code will only set the *last* header parameter if there're more than one header parameter
```
{{#headerParams}}headers = {
{{{paramName}}}: {{{paramName}}},
}
{{/headerParams}}
{{^headerParams}}headers = nil
{{/headerParams}}
```
- remove extra line break in api.mustache and model.mustache so that the code format looks better
- put single quote in parameter name to avoid special character from causing failure in compiling the auto-generated Ruby code
=> Bug fix for ruby header parameter and better code format

README.md, modules/swagger-codegen/src/main/resources/Java/apiInvoker.mustache, modules/swagger-codegen/src/main/resources/python/swagger.mustache
Attribute classes weren't being respected and now they are.
=> Python: fixing an issue in swagger python code generation

modules/swagger-codegen/src/main/resources/php/Swagger.mustache, modules/swagger-codegen/src/main/resources/php/model.mustache, samples/client/petstore/php/Swagger.php, samples/client/petstore/php/models/Category.php, samples/client/petstore/php/models/Order.php, samples/client/petstore/php/models/Pet.php, samples/client/petstore/php/models/Tag.php, samples/client/petstore/php/models/User.php
Add attribute mapping to PHP model to handle property key with special characters (e.g. -).
Ruby API client already has an attribute map and the PHP's attribute map is implemented with referenced to the Ruby implementation.
=> Add Attribute Mapping to PHP model

modules/swagger-codegen/src/main/resources/ruby/swagger/configuration.mustache, modules/swagger-codegen/src/main/resources/ruby/swagger/request.mustache, samples/client/petstore/ruby/lib/PetApi.rb, samples/client/petstore/ruby/lib/StoreApi.rb, samples/client/petstore/ruby/lib/UserApi.rb, samples/client/petstore/ruby/lib/swagger/configuration.rb, samples/client/petstore/ruby/lib/swagger/request.rb
currently, the user-agent is not set in Ruby API client. this PR will
- add user_agent to attr_accessor (so that developers can customize it)
- add user-agent to the default_headers
- update user-agent to "ruby-swagger-#{Swagger::VERSION}"
=> Fix User-Agent in Ruby API cleint

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/languages/PhpClientCodegen.java, modules/swagger-codegen/src/test/scala/php/PhpModelTest.scala, samples/client/petstore/php/PetApi.php, samples/client/petstore/php/StoreApi.php, samples/client/petstore/php/models/Pet.php, samples/client/petstore/php/models/User.php, samples/client/petstore/php/models/category.php, samples/client/petstore/php/models/order.php, samples/client/petstore/php/models/pet.php, samples/client/petstore/php/models/tag.php, samples/client/petstore/php/models/user.php
Update PHP codegen as follows:
- model property in underscore format (createAt => create_at)
- method argument in underscore format (additionalMeta => additiona_meta)
- model name (class name) in camelized format (mobile_phone => MobilePhone)
- escape invalid  name (e.g. reserved word, 123testing) with _ at the beginning (e.g. 123number => _123number, return => _return)
- update reserved word list
- update test case for php and php petstore sample
- add string utility function (camelize, underscore) to default codegen (ref: https://github.com/twitter/elephant-bird/blob/master/core/src/main/java/com/twitter/elephantbird/util/Strings.java)
=> PHP better naming convention

modules/swagger-codegen/src/main/resources/python/swagger.mustache
Use date.util lib to parse string to datetime in python.
The string can be iso8601 datetime format.
`ISO8601`(http://www.w3.org/TR/NOTE-datetime)
=> Support iso8601 datetime format in Python client

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/languages/AndroidClientCodegen.java, modules/swagger-codegen/src/main/resources/android-java/model.mustache, samples/client/petstore/android-java/src/main/java/io/swagger/client/api/PetApi.java
This PR is very similar to #535 (Better variable and model property naming for Java): update android-java codegen with better naming convention:
- in model template, use {{baseName}} instead of {{name}} for @JsonProperty (since we need the original name as the JSON key)
- camelized model name (e.g. phone_number => PhoneNumber)
- for property and variable name, camelize with lower first character (e.g. phone_number => phoneNumber)
- for reserved words or word starting with number, append _ (e.g. return => _return, 123number => _123number)
- update test case and Petstore sample for android-java
=> better naming convention for android-java codegen

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/DefaultCodegen.java
when tag is not provided a StringIndexOutOfBoundsException is generated 
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
at java.lang.String.charAt(String.java:646)
at com.wordnik.swagger.codegen.DefaultCodegen.initialCaps(DefaultCodegen.java:379)
at com.wordnik.swagger.codegen.DefaultCodegen.toApiFilename(DefaultCodegen.java:142)
at com.wordnik.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:144)
at com.wordnik.swagger.codegen.Codegen.main(Codegen.java:99)
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
at java.lang.String.charAt(String.java:646)
at com.wordnik.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:144)
at com.wordnik.swagger.codegen.Codegen.main(Codegen.java:99) …
=> fix StringIndexOutOfBoundsException when tag is not provided

modules/swagger-codegen-distribution/pom.xml, modules/swagger-codegen-distribution/src/main/java/com/wordnik/swagger/codegen/SwaggerCodegen.java, modules/swagger-codegen-distribution/src/main/java/com/wordnik/swagger/codegen/cmd/Generate.java, modules/swagger-codegen-distribution/src/main/java/com/wordnik/swagger/codegen/cmd/Langs.java, modules/swagger-codegen-distribution/src/main/java/com/wordnik/swagger/codegen/cmd/Meta.java
can replace Codegen and MetaGenerator classes. Provides a bit different cli interface
based on refactored pom from #541,
affects #349
```
usage: swagger <command> [<args>]
The most commonly used swagger commands are:
generate   Generate code with chosen lang
help       Display help information
langs      Shows available langs
meta       MetaGenerator. Generator for creating a new template set and configuration for Codegen.  The output will be based on the language you specify, and includes default templates to include.
```
**generate** and **meta** commands have same as current cli options
I can remove change of default main class so that it can be merged without brake backward compatibility
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on …
=> add - new command line interface in distribution module

modules/swagger-codegen/src/main/resources/META-INF/services/com.wordnik.swagger.codegen.CodegenConfig
Since Threepane and Swift were not listed as languages
=> small fix on CodegenConfig to bring back Threepane and Swift

modules/swagger-codegen/src/main/resources/php/api.mustache, samples/client/petstore/php/PetApi.php, samples/client/petstore/php/StoreApi.php, samples/client/petstore/php/UserApi.php
This PR updates code comment with better documentation on method name as follows:
```
/**
* updatePetWithForm
*
* Updates a pet in the store with form data
*
* @param string $pet_id ID of pet that needs to be updated (required)
* @param string $name Updated name of the pet (required)
* @param string $status Updated status of the pet (required)
* @return void
*/
public function updatePetWithForm($pet_id, $name, $status) {
```
This PR also replaces tab with 2 spaces in PHP API template
=> Update PHP documentation for method

modules/swagger-codegen/src/main/resources/Java/apiInvoker.mustache, modules/swagger-codegen/src/main/resources/android-java/apiInvoker.mustache, samples/client/petstore/android-java/src/main/java/io/swagger/client/ApiInvoker.java, samples/client/petstore/java/src/main/java/io/swagger/client/ApiInvoker.java
* Java client uses e.g. `Java/1.7.0_51` as User-Agent, changing it to `Java-Swagger` by default.
* Android client uses e.g. `Apache-HttpClient/4.3.6 (java 1.5)`, changing it to `Android-Java-Swagger`.
* Provide the `ApiInvoker.setUserAgent` method to allow customizing User-Agent easily.
=> Set default User-Agent for Java and Android clients

modules/swagger-codegen/src/main/resources/Java/apiInvoker.mustache, modules/swagger-codegen/src/main/resources/android-java/apiInvoker.mustache, samples/client/petstore/android-java/src/main/java/io/swagger/client/ApiInvoker.java, samples/client/petstore/java/src/main/java/io/swagger/client/ApiInvoker.java
According to Android's docs (https://developer.android.com/reference/java/text/SimpleDateFormat.html)
the `SimpleDateFormat` class in Android does not accept `XXX` as the timezone, it uses `Z` instead.
Also updated the date time format of Android and Java clients to include milliseconds and to be consistent.
=> Fix date time format for Android client

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/DefaultCodegen.java
Issue link [577](https://github.com/swagger-api/swagger-codegen/issues/577) 
Fixed the compile time error in the generated code caused due to unescaped new line characters.
Since the description text is not being escaped, if there is a new line character, it will cause a new line to be added to the source code. This can cause compile time error if the new line character is part of a string (e.g. java string) and there is no '+' sign explicitly added to the code. Note: The code was doing escapeText for properties but not for models. This patch fixes that.
=> Fixed the compile time error in the generated code caused due to unescaped new line characters.

modules/swagger-codegen/src/main/resources/ruby/api.mustache, samples/client/petstore/ruby/lib/pet_api.rb, samples/client/petstore/ruby/lib/store_api.rb, samples/client/petstore/ruby/lib/user_api.rb
- set "Accept" only if it's defined in the Swagger spec
- set Content-Type to the first value in "Consumes" or use "application/json" as default
- updated petstore ruby samples (files compiled without issue using ruby -c)
=> Fixed Ruby header: "Accept", "Content-Type"

modules/swagger-codegen/src/main/resources/python/swagger.mustache, samples/client/petstore/python/client/PetApi.py, samples/client/petstore/python/client/swagger.py
* Changed default User-Agent to `Python-Swagger` in python client.
* Added the `user_agent` property to allow customizing User-Agent easily.
* Updated Python Petstore client and tested without issue.
=> Fixed user agent in python client

modules/swagger-codegen/src/main/resources/csharp/api.mustache, samples/client/petstore/csharp/src/main/csharp/io/swagger/Api/PetApi.cs, samples/client/petstore/csharp/src/main/csharp/io/swagger/Api/StoreApi.cs, samples/client/petstore/csharp/src/main/csharp/io/swagger/Api/UserApi.cs
Currently, IDE shows the following warnings:
```
Warning CS0219: The variable `response' is assigned but its value is never used (CS0219)
```
This is due to the variable response is defined even the return type is "void".
This PR updates the code to use {{#returnType}} and {{^returnType}} to correctly declare the variable response if needed (number of warnings down from 33 to 22)
This PR also updates code format of api.mustache: remove 2 leading spaces and replace tab with spaces
=> Eliminated warning related to response in CSharp API files

modules/swagger-codegen/src/main/resources/android-java/apiInvoker.mustache
Switched `SingleClientConnManager` with `ThreadSafeClientConnManager`.
The `SingleClientConnManager` cannot be used safely in multi-threaded environments (see [this](https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/conn/SingleClientConnManager.html)),  and therefor should not be used.
This fix should be considered temporary since with the Apache HttpClient version bump in b5a4d5be040d9115063145a5923d7aafa17b3242, many of the classes in `ApiInvoker` have been deprecated
=> Switched SingleClientConnManager with ThreadSafeClientConnManager.

modules/swagger-codegen/src/main/resources/objc/SWGApiClient.m, modules/swagger-codegen/src/main/resources/objc/api-body.mustache
* Fixed issue that it will throw exceptions when post form parameters without file.
In the methods `dictionary` and `stringWithCompletionBlock`:
```objective-c
NSMutableURLRequest * request = nil;
if (body != nil && [body isKindOfClass:[NSArray class]]){
SWGFile * file;
NSMutableDictionary * params = [[NSMutableDictionary alloc] init];
for(id obj in body) {
if([obj isKindOfClass:[SWGFile class]]) {
file = (SWGFile*) obj;
requestContentType = @"multipart/form-data";
}
else if([obj isKindOfClass:[NSDictionary class]]) {
for(NSString * key in obj) {
params[key] = obj[key];
}
}
}
NSString * urlString = [[NSURL URLWithString:path relativeToURL:self.baseURL] absoluteString];
// request with multipart form
if(file != nil) {
request = [self.requestSerializer multipartFormRequestWithMethod: …
```
=> Fixed issue about form parameters in Objc client

samples/client/petstore/php/SwaggerPetstore-php/README.md, samples/client/petstore/php/SwaggerPetstore-php/tests/PetApiTest.php
Added a unit test for PHP petstore client - getPetById, using PHPUnit_Framework_TestCase
Added a readme with instruction on how to perform testing.
Here is the test result
```
./vendor/bin/phpunit tests
PHPUnit 4.6.2 by Sebastian Bergmann and contributors.
.
Time: 2.45 seconds, Memory: 2.75Mb
OK (1 test, 1 assertion)
```
This PR is a starting point for PHP client unit testing. More tests will be added with reference to how other Petstore client (e.g. ruby, java) is tested.
=> Added unit testing for PHP Petstore client

modules/swagger-codegen/src/main/resources/python/api.mustache, modules/swagger-codegen/src/main/resources/python/model.mustache, modules/swagger-codegen/src/main/resources/python/swagger.mustache
Fixed issue that it will throw some errors if unicode string in the python client.
=> Support unicode string in python client.

modules/swagger-codegen/src/main/resources/objc/SWGApiClient.m
* When call `uploadFile` method without file in objc client, the request content-type is `application/x-www-form-urlencoded` which is incorrect.
* After fixing, the request content-type is `multipart/form-data` and the tcpdump information is below:
```sh
POST /v2/pet/1/uploadImage HTTP/1.1
Host: petstore.swagger.io
Content-Type: multipart/form-data; boundary=Boundary+2262D22AF872FACC
Connection: keep-alive
Accept: */*
User-Agent: PetstoreClient/1.0 (iPhone Simulator; iOS 8.2; Scale/2.00)
Accept-Language: en;q=1, fr;q=0.9, de;q=0.8, zh-Hans;q=0.7, zh-Hant;q=0.6, ja;q=0.5
Content-Length: 130
Accept-Encoding: gzip, deflate
--Boundary+2262D22AF872FACC
Content-Disposition: form-data; name="additionalMetadata"
special
--Boundary+2262D22AF872FACC--
```
=> Fixed request content-type in objc client

modules/swagger-codegen/src/main/resources/php/APIClient.mustache, samples/client/petstore/php/SwaggerPetstore-php/lib/APIClient.php
Currently, the PHP API client only looks for the following primitive types:
```
} elseif (in_array($class, array('string', 'int', 'float', 'bool'))) {
```
This PR updates the check to include "double":
```
} elseif (in_array($class, array('string', 'int', 'float', 'double', 'bool'))) {
```
=> Fixed "double" response type in PHP client

modules/swagger-codegen/src/main/resources/python/api.mustache, modules/swagger-codegen/src/main/resources/python/swagger.mustache, samples/client/petstore/python/SwaggerPetstore-python/SwaggerPetstore/pet_api.py, samples/client/petstore/python/SwaggerPetstore-python/SwaggerPetstore/store_api.py, samples/client/petstore/python/SwaggerPetstore-python/SwaggerPetstore/swagger.py, samples/client/petstore/python/SwaggerPetstore-python/SwaggerPetstore/user_api.py
In `api.mustache`, the content-type key in the headerParams is `Content-Type`, `headerParams['Content-Type']`.
But in `swagger.mustache`, the content-type key in the headers hash is `Content-type`,
`headers['Content-type']`.
This will result the `content-type` in request headers always be `application/json`.
https://github.com/swagger-api/swagger-codegen/pull/625/files#diff-7356954fd07cc52ba5ac73153eb27cd8R85
=> Fixed request content-type in python client

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/languages/PhpClientCodegen.java, modules/swagger-codegen/src/main/resources/php/APIClient.mustache, modules/swagger-codegen/src/main/resources/php/api.mustache
This fixes issue https://github.com/swagger-api/swagger-codegen/issues/628, which causes name collision.
=> Making default PHP namespace generic and fix issues 628 and 635

modules/swagger-codegen/src/main/resources/objc/api-body.mustache
Adding defaultHeaders dictionary to generated API classes. defaultHeaders will be merged with headerParams before sending the request.
fix for https://github.com/swagger-api/swagger-codegen/issues/638
=> Adding defaultHeaders dictionary to generated API classes.

modules/swagger-codegen/src/main/resources/php/APIClient.mustache
We found and fixed a bug in the PHP template which was causing PHP arrays to never serialize down to JSON.
=> [PHP Templates] Fixing a bug which was preventing payloads to serialize into JSON

modules/swagger-codegen/src/main/resources/objc/model-body.mustache, modules/swagger-codegen/src/main/resources/objc/model-header.mustache, samples/client/petstore/objc/client/SWGApiClient.m, samples/client/petstore/objc/client/SWGCategory.h, samples/client/petstore/objc/client/SWGCategory.m, samples/client/petstore/objc/client/SWGOrder.h, samples/client/petstore/objc/client/SWGOrder.m, samples/client/petstore/objc/client/SWGPet.h, samples/client/petstore/objc/client/SWGPet.m, samples/client/petstore/objc/client/SWGTag.h, samples/client/petstore/objc/client/SWGTag.m, samples/client/petstore/objc/client/SWGUser.h, samples/client/petstore/objc/client/SWGUser.m
Use `propertyIsOptional`(https://github.com/icanzilb/JSONModel#make-all-model-properties-optional-avoid-if-possible) to implement optional property instead of using `Optional` protocol in objc client.
If use `Optional` protocol to implement optional property, the generated code will be`BOOL<Optional>` when the data type is `BOOL`.
But the BOOL does not support protocol, so we use `propertyIsOptional` method instead of `Optiona` protocol.
=> Update model optional property in objc client

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/DefaultGenerator.java, modules/swagger-codegen/src/main/resources/ruby/swagger.mustache, modules/swagger-codegen/src/main/resources/ruby/swagger/configuration.mustache
* Fix hard-coded values in Ruby client: scheme, host and base_path, i.e. fill them with default values
* Initialize a default configuration object so that the client can be used without being configured explicitly
=> Fix hard-coded values in Ruby client: scheme, host and base_path

modules/swagger-codegen/src/main/resources/ruby/api.mustache, samples/client/petstore/ruby/lib/pet_api.rb, samples/client/petstore/ruby/lib/store_api.rb, samples/client/petstore/ruby/lib/swagger.rb, samples/client/petstore/ruby/lib/user_api.rb, samples/client/petstore/ruby/spec/pet_spec.rb, samples/client/petstore/ruby/spec/spec_helper.rb
Assuming `name` and `status` are optional parameters (`required` is `false`), instead of having to pass those two parameters like this:
``` ruby
PetApi.updatePetWithForm(1, "pet name", "pet status")
```
this PR allows passing any parameters that is needed, e.g. only update the status:
``` ruby
PetApi.updatePetWithForm(1, :status => "pet status")
```
Complete changes:
* Pass optional parameters via the `opts` Hash
* Handle query parameters in a way similar to header/form parameters to
support parameter name normalization, e.g. the "additional_metadata"
key is used for "additionalMetadata"
* Rename variables to be consistent: `query_params`, `header_params` and
`form_params`
* Remove unnecessary blank lines
* Rename local variable `body` to `_body_param` to avoid potential naming comflict
=> Add support of optional parameters to Ruby codegen

modules/swagger-codegen/src/main/resources/python/swagger.mustache, samples/client/petstore/python/SwaggerPetstore-python/SwaggerPetstore/swagger.py
If the request content type is `application/json`, 
it will execute `data = urllib.urlencode(postData)` in the else part which is incorrect.
=> Fixed encoding issue for request json body in python client.

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/languages/AndroidClientCodegen.java, modules/swagger-codegen/src/main/resources/android-java/build.mustache, modules/swagger-codegen/src/main/resources/android-java/manifest.mustache, samples/client/petstore/android-java/build.gradle, samples/client/petstore/android-java/src/main/AndroidManifest.xml
https://github.com/swagger-api/swagger-codegen/pull/699 breaks the automated build for android client jar version, this pull request fixes it. In addition, it set ups build.gradle to be used as library module in android project structure.
=> Jar and aar support for Android

README.md
The README is linking to a tag which no longer exists, updated the link to reflect what I assume is the proper version.
=> Linked to the 2.0.18 tag instead of the no longer existing 2.0.17.

README.md
My last pull request changed to use 2.0.18 but after further research I found that the 2.0.17 tag still exists but the URL is not correct. This reverts my change and links to the 2.0.17 tag.
Sorry about the confusion.
=> Found the 2.0.17 tag under 2.0.17 instead of v2.0.17.

modules/swagger-codegen/src/main/resources/Java/JsonUtil.mustache
Generated Java sample for the Pet Store is broken after the PR #726:
```
$ ./bin/java-petstore.sh ; cd samples/client/petstore/java; mvn clean package
...
[INFO] 9 errors 
[INFO] -------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] Total time: 1.936s
[INFO] Finished at: Fri May 08 12:32:56 UTC 2015
[INFO] Final Memory: 13M/303M
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project swagger-java-client: Compilation failure: Compilation failure:
[ERROR] …
```
=> Reverted JsonUtil.mustache for JavaClientCodegen after PR #726.

pom.xml, samples/client/petstore/scala/src/test/scala/PetApiTest.scala, samples/client/petstore/scala/src/test/scala/StoreApiTest.scala
Test results before the fixes:
```
Results :
Tests in error:
PetApi should fetch a pet(PetApiTest): didn't find pet 1
StoreApi should fetch an order(StoreApiTest): didn't find order
StoreApi should place an order(StoreApiTest): false was not true
StoreApi should delete an order(StoreApiTest): false was not true
Tests run: 15, Failures: 0, Errors: 4, Skipped: 0
```
Test results after the fixes:
```
Results :
Tests run: 13, Failures: 0, Errors: 0, Skipped: 0
```
=> Fix tests for Scala petstore sample

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/languages/PhpClientCodegen.java, modules/swagger-codegen/src/test/scala/php/PhpModelTest.scala, samples/client/petstore/php/SwaggerClient-php/lib/PetApi.php
- fixed Swagger type for PHP codegen
- tested with model name `Pet.Test` and response correctly casts to `PetTest`
- commented out import test as import is not used in PHP templates
=> Fix PHP swagger type

modules/swagger-codegen/src/main/resources/htmlDocs/index.mustache, samples/html/index.html
Remove dead include of site.css
Includes latest build, not sure if I should have left the build alone ?
fixes #666
=> html: build and remove dead css include

modules/swagger-codegen/src/main/resources/swagger-static/assets/css/style.css, modules/swagger-codegen/src/main/resources/swagger-static/operation.mustache, samples/dynamic-html/docs/assets/css/style.css, samples/dynamic-html/docs/operations/PetApi.html, samples/dynamic-html/docs/operations/StoreApi.html, samples/dynamic-html/docs/operations/UserApi.html
Based on PR: https://github.com/swagger-api/swagger-codegen/pull/716
fixes #334 
Re-factored the way parameters are viewed.
=> Fix dynamic-html positioning of parameters

modules/swagger-codegen/src/main/resources/ruby/api.mustache, modules/swagger-codegen/src/main/resources/ruby/swagger/request.mustache, samples/client/petstore/ruby/lib/pet_api.rb, samples/client/petstore/ruby/lib/store_api.rb, samples/client/petstore/ruby/lib/swagger/request.rb, samples/client/petstore/ruby/lib/user_api.rb
For #745, this PR will update Ruby API client so that Accept and Content-Type header will use "application/json" if it's provided in the Swagger spec.
Integration test result:
```
[INFO] --- exec-maven-plugin:1.2.1:exec (bundle-test) @ RubyPetstoreClientTests ---
.............................................
Finished in 28.56 seconds (files took 0.30172 seconds to load)
45 examples, 0 failures
[INFO] Total time: 32.382 s
[INFO] Finished at: 2015-05-15T20:53:29+08:00
```
Also performed testing by …
=> Minor improvement to Ruby API Client 'accept' and 'content-type' header

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/languages/RubyClientCodegen.java, modules/swagger-codegen/src/main/resources/ruby/api.mustache, modules/swagger-codegen/src/main/resources/ruby/base_object.mustache, modules/swagger-codegen/src/main/resources/ruby/model.mustache, modules/swagger-codegen/src/main/resources/ruby/swagger.mustache, modules/swagger-codegen/src/main/resources/ruby/swagger/request.mustache, modules/swagger-codegen/src/main/resources/ruby/swagger/response.mustache, samples/client/petstore/ruby/lib/model/base_object.rb, samples/client/petstore/ruby/lib/pet_api.rb, samples/client/petstore/ruby/lib/store_api.rb, samples/client/petstore/ruby/lib/swagger.rb, samples/client/petstore/ruby/lib/swagger/request.rb, samples/client/petstore/ruby/lib/swagger/response.rb, samples/client/petstore/ruby/lib/user_api.rb, samples/client/petstore/ruby/models/base_object.rb, samples/client/petstore/ruby/models/category.rb, samples/client/petstore/ruby/models/order.rb, samples/client/petstore/ruby/models/pet.rb, samples/client/petstore/ruby/models/tag.rb, samples/client/petstore/ruby/models/user.rb, samples/client/petstore/ruby/spec/pet_spec.rb, samples/client/petstore/ruby/spec/response_spec.rb, samples/client/petstore/ruby/spec/spec_helper.rb
- all models now inherit base_model.rb, which provides common methods like `to_hash`, `build_from_hash`
- fixed bug with posting objects with sub-models #752 
- added rspec test cases for posting objects with sub-models
- refactored post model into a function `object_to_http_body` in Swagger::Request
Ruby integration test result:
```
[INFO] --- exec-maven-plugin:1.2.1:exec (bundle-test) @ RubyPetstoreClientTests ---
..............................................
Finished in 28.08 seconds (files took 0.52256 seconds to load)
46 examples, 0 failures
[INFO] Total time: 35.214s
[INFO] Finished at: Mon May 18 …
```
=> [Ruby] bug fixes for posting with sub-models and enhancements (refactoring)

modules/swagger-codegen/src/main/resources/perl/APIClient.mustache, modules/swagger-codegen/src/main/resources/perl/api.mustache, samples/client/petstore/perl/lib/WWW/SwaggerClient/APIClient.pm, samples/client/petstore/perl/lib/WWW/SwaggerClient/PetApi.pm, samples/client/petstore/perl/lib/WWW/SwaggerClient/StoreApi.pm, samples/client/petstore/perl/lib/WWW/SwaggerClient/UserApi.pm, samples/client/petstore/perl/t/01_pet_api.t
For accept and content-type, use `application/json` if it's in the consumes/produces list. This is to avoid `application/xml` being used as the API client cannot handle XML response at the moment
Added test case for new functions for performing the above.
=> [Perl] better logic for accept and content-type, added test cases

README.md
Looks like I'm the one of users, who have missed "Requires Java 1.7". I suggest to add a section how to ensure, that you are running proper Java version. ... at least for OS X users (like me).
There are some issues, created because of this:
- https://github.com/swagger-api/swagger-codegen/issues/605
- https://github.com/swagger-api/swagger-codegen/issues/381
=> Improve README for OS X Users with random Java versions

modules/swagger-codegen/pom.xml, modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/CodegenResponse.java, modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/examples/ExampleGenerator.java, modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/languages/NodeJSServerCodegen.java, modules/swagger-codegen/src/main/resources/htmlDocs/index.mustache, modules/swagger-codegen/src/test/resources/2_0/petstore.json, modules/swagger-generator/pom.xml, pom.xml
Fixes #646: Example field handling has been fixed.
The swagger-api/swagger-core/pull/1002 has to be accepted first.
I would suggest to remove escaping of '\n' (i.e. example = example.replaceAll("\n", "\\\\n") in [ExampleGenerator](https://github.com/swagger-api/swagger-codegen/pull/676/files#diff-08b7ea6b5aaa485f71bcf31aec901b5dL40) and jsonExample = jsonExample.replaceAll("\\\\n", "\n") in [NodeJSServerCodegen](https://github.com/swagger-api/swagger-codegen/pull/676/files#diff-7a12f5f8b19af3ab6e9ee4867476611bL181)) and leave this on behalf of particular descendants of the DefaultCodegen class.
As for now only `html` and `nodejs` generators use examples, while the first outputs examples as is and has the issue reported [here](https://github.com/swagger-api/swagger-codegen/pull/654#issuecom …
=> Fixes #646: Example field handling has been fixed.

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/languages/CSharpClientCodegen.java, modules/swagger-codegen/src/main/resources/csharp/api.mustache, modules/swagger-codegen/src/main/resources/csharp/apiException.mustache, modules/swagger-codegen/src/main/resources/csharp/apiInvoker.mustache, modules/swagger-codegen/src/main/resources/csharp/model.mustache, samples/client/petstore/csharp/compile.bat, samples/client/petstore/csharp/src/main/csharp/io/swagger/Api/PetApi.cs, samples/client/petstore/csharp/src/main/csharp/io/swagger/Api/StoreApi.cs, samples/client/petstore/csharp/src/main/csharp/io/swagger/Api/UserApi.cs, samples/client/petstore/csharp/src/main/csharp/io/swagger/Model/Category.cs, samples/client/petstore/csharp/src/main/csharp/io/swagger/Model/Order.cs, samples/client/petstore/csharp/src/main/csharp/io/swagger/Model/Pet.cs, samples/client/petstore/csharp/src/main/csharp/io/swagger/Model/Tag.cs, samples/client/petstore/csharp/src/main/csharp/io/swagger/Model/User.cs, samples/client/petstore/csharp/src/main/csharp/io/swagger/client/ApiException.cs, samples/client/petstore/csharp/src/main/csharp/io/swagger/client/ApiInvoker.cs
Use RestSharp to make HTTP calls. Tested with the following:
- GetPetById
- UpdatePetWithForm (confirmed by inspecting the HTTP request using tcpdump)
- AddPet
Add `DataContract` to CSharp models (similar to @jsonproperty in Java) to properly map attributes with special characters. Deserialisation of responses from server works fine (tested with Pet, a model with sub-models)
=> Use RestSharp for CSharp API client

modules/swagger-codegen/src/main/resources/php/APIClient.mustache, modules/swagger-codegen/src/main/resources/php/api.mustache, samples/client/petstore/php/SwaggerClient-php/lib/APIClient.php, samples/client/petstore/php/SwaggerClient-php/lib/PetApi.php, samples/client/petstore/php/SwaggerClient-php/lib/StoreApi.php, samples/client/petstore/php/SwaggerClient-php/lib/UserApi.php, samples/client/petstore/php/SwaggerClient-php/tests/PetApiTest.php, samples/client/petstore/php/test.php
- updated API client to support default header with test cases
- better accept and content-type (use application/json if available)
- added back test cases for updatePetWithForm
- better exception using InvalidArgumentException
```
$ ./vendor/bin/phpunit tests
PHPUnit 4.6.6 by Sebastian Bergmann and contributors.
.......
Time: 5.73 seconds, Memory: 5.50Mb
OK (7 tests, 345 assertions)
```
=> [PHP] update API client to support default header, better accept and content-type

modules/swagger-codegen/src/main/resources/objc/api-body.mustache, samples/client/petstore/objc/client/SWGPetApi.m, samples/client/petstore/objc/client/SWGStoreApi.m, samples/client/petstore/objc/client/SWGUserApi.m
* Added required parameter check for objc client.
Currently, required parameter validation is missing/broken. 
This PR aims to improve the method/function by ensuring that the required parameter is set. 
Otherwise, an exception will be thrown.
* Tested without issue.
```sh
Test Case '-[PetApiTest testUploadFile]' passed (0.411 seconds).
Test Suite 'PetApiTest' passed at 2015-05-19 09:04:38 +0000.
Executed 6 tests, with 0 failures (0 unexpected) in 6.423 (6.426) seconds
Test Suite 'PetstoreClientTests.xctest' passed at 2015-05-19 09:04:38 +0000.
Executed 6 tests, with 0 failures (0 unexpected) in 6.423 (6.427) seconds
Test Suite 'All tests' passed at 2015-05-19 09:04:38 +0000.
Executed 6 tests, with 0 failures (0 unexpected) in 6.423 (6.429) seconds
[INFO] …
```
=> Fix required parameter validation for Objc

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/DefaultGenerator.java, modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/languages/PhpClientCodegen.java, modules/swagger-codegen/src/main/resources/php/APIClient.mustache, modules/swagger-codegen/src/main/resources/php/api.mustache, modules/swagger-codegen/src/main/resources/php/configuration.mustache, modules/swagger-codegen/src/test/resources/2_0/petstore.json, samples/client/petstore/php/SwaggerClient-php/lib/APIClient.php, samples/client/petstore/php/SwaggerClient-php/lib/Configuration.php, samples/client/petstore/php/SwaggerClient-php/lib/PetApi.php, samples/client/petstore/php/SwaggerClient-php/lib/StoreApi.php, samples/client/petstore/php/SwaggerClient-php/lib/UserApi.php, samples/client/petstore/php/SwaggerClient-php/tests/PetApiTest.php
- Support API key, HTTP basic
- Add a Configuration class for authentication-related setting
- Tested with 2 API key and HTTP basic auth
- Added test case for API key authentication using getPetById
```
./vendor/bin/phpunit tests                        
PHPUnit 4.6.6 by Sebastian Bergmann and contributors.
.......
Time: 5.67 seconds, Memory: 4.50Mb
OK (7 tests, 157 assertions)
```
=> [PHP] Add authentication support (API key, HTTP basic)

modules/swagger-codegen/src/main/resources/python/model.mustache, samples/client/petstore/python/SwaggerPetstore-python/SwaggerPetstore/models/category.py, samples/client/petstore/python/SwaggerPetstore-python/SwaggerPetstore/models/order.py, samples/client/petstore/python/SwaggerPetstore-python/SwaggerPetstore/models/pet.py, samples/client/petstore/python/SwaggerPetstore-python/SwaggerPetstore/models/tag.py, samples/client/petstore/python/SwaggerPetstore-python/SwaggerPetstore/models/user.py
Normally, python will output the memory address when print object.
```sh
<__console__.A instance at 0x1047ba998>
```
Overwrite the instance method `__repr__`,  the `pprint` method will output the properties infos of the models.
```sh
>>> pprint(pet)
<SwaggerPetstore.models.pet category=<SwaggerPetstore.models.category id=1 name='dog'> status='sold' nam
e='hello kity' tags=[<SwaggerPetstore.models.tag id=1 name='green'>] photo_urls=['foobar'] id=1>
```
=> Pretty print for models of python client

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/languages/CSharpClientCodegen.java, modules/swagger-codegen/src/main/resources/csharp/apiInvoker.mustache, samples/client/petstore/csharp/src/main/csharp/io/swagger/client/ApiInvoker.cs
To address #730 
Tested with type set to `object` with and without $ref
=> [C#] Fix "object' type for response

modules/swagger-codegen/src/main/resources/ruby/api.mustache, samples/client/petstore/ruby/lib/swagger_client/api/pet_api.rb, samples/client/petstore/ruby/lib/swagger_client/api/store_api.rb, samples/client/petstore/ruby/lib/swagger_client/api/user_api.rb, samples/client/petstore/ruby/spec/pet_spec.rb
Currently a `Swagger::Response` object is returned for operations that have no response type defined (since the `Swagger::Request.new(...).make` is the last statement), which might be confusing.
This PR changes it to return `nil` explicitly.
=> Return nil in Ruby clients for operations that have no response type defined

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/CodegenParameter.java, modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/DefaultCodegen.java
This is required in some languages like Obj-C where there is no automatic value boxing and
handling of primitive types require extra work compared to non-primitive types.
Case in point: `BOOL` type. To assign `BOOL` into a dictionary, one needs to box it into an
`NSValue *` instance, so to build a dictionary for sending form data, for example, you
cannot do this in the template:
dict["{{paramName}}"] = {{paramName}};
Because if the parameter ends up being of type `BOOL`, an error about boxing values will be
generated:
BOOL boolValue = NO;
dict["boolValue"] = boolValue;
^---------------- Cannot do the assignment here.
The fix is to wrap it in `@()` like so:
BOOL boolValue = NO;
dict["boolValue"] = @(boolValue);
So a flag is needed in `CodegenParameter` so we can selectively emit the right …
=> Adds isPrimitiveType flag to CodegenParameter.

modules/swagger-codegen/src/main/resources/php/APIClient.mustache, samples/client/petstore/php/SwaggerClient-php/lib/APIClient.php, samples/client/petstore/php/SwaggerClient-php/tests/PetApiTest.php
Currently, test cases failed with PHP5.3 but not PHP5.5 
This PR will address the issue to allow test cases run without issue using PHP5.3
The change has been tested with both PHP5.3 and PHP5.5:
```
SwaggerClient-php|php53_fix_warning ⇒ php -v                                             
PHP 5.5.20 (cli) (built: Feb 25 2015 23:30:53) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
SwaggerClient-php|php53_fix_warning ⇒  ./vendor/bin/phpunit tests                        
PHPUnit 4.6.6 by Sebastian Bergmann and contributors.
.......
Time: 6.65 seconds, Memory: 4.50Mb
OK (7 tests, 157 assertions)
```
```
➜  SwaggerClient-php git:(php53_fix_warning) ✗ php -v
PHP 5.3.10-1ubuntu3.14 with Suhosin-Patch (cli) (built: Sep  4 2014 07:08:49) …
```
=> [PHP] Fix warning/error related to PHP5.3

modules/swagger-codegen/src/main/resources/php/APIClient.mustache, modules/swagger-codegen/src/main/resources/php/api.mustache, modules/swagger-codegen/src/main/resources/php/configuration.mustache, samples/client/petstore/php/SwaggerClient-php/lib/APIClient.php, samples/client/petstore/php/SwaggerClient-php/lib/Configuration.php, samples/client/petstore/php/SwaggerClient-php/lib/PetApi.php, samples/client/petstore/php/SwaggerClient-php/lib/StoreApi.php, samples/client/petstore/php/SwaggerClient-php/lib/UserApi.php, samples/client/petstore/php/SwaggerClient-php/tests/PetApiTest.php, samples/client/petstore/php/test.php
This PR will allow developers to easily customize APIClient and use it to initialize the API class (e.g. PetApi)
It also allows developers to skip the initialization of a new APIClient as the API class (e.g. PetApi) will automatically construct a new default API client if no client has been initialized). For example, the following line becomes optional:
```
$api_client = new SwaggerClient\APIClient('http://petstore.swagger.io/v2');
```
=> [PHP] Make API client more pluggable

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/test/scala/Java/JavaInheritanceTest.scala, modules/swagger-codegen/src/test/scala/Objc/ObjcModelTest.scala, modules/swagger-codegen/src/test/scala/scala/ScalaModelTest.scala
Fixes #429: Handling of composed models has been added.
=> Fixes #429: Handling of composed models has been added.

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/languages/PythonClientCodegen.java, modules/swagger-codegen/src/main/resources/python/api.mustache, modules/swagger-codegen/src/main/resources/python/config.mustache, modules/swagger-codegen/src/main/resources/python/swagger.mustache, samples/client/petstore/python/SwaggerPetstore-python/SwaggerPetstore/apis/pet_api.py, samples/client/petstore/python/SwaggerPetstore-python/SwaggerPetstore/apis/store_api.py, samples/client/petstore/python/SwaggerPetstore-python/SwaggerPetstore/apis/user_api.py, samples/client/petstore/python/SwaggerPetstore-python/SwaggerPetstore/config.py, samples/client/petstore/python/SwaggerPetstore-python/SwaggerPetstore/swagger.py, samples/client/petstore/python/SwaggerPetstore-python/tests/test_api_client.py, samples/client/petstore/python/SwaggerPetstore-python/tests/test_pet_api.py
* Allows developers to easily customize APIClient and use it to initialize the API class (e.g. PetApi)
* Allows developers to skip the initialization of a new APIClient as the API class (e.g. PetApi) will automatically construct a new default API client if no client has been initialized). For example, the following line becomes optional:
```python
api_client = SwaggerPetstore.APIClient('http://petstore.swagger.io/v2')
```
* Tested without issue
```sh
[INFO] Total time: 26.713 s
[INFO] Finished at: 2015-05-25T14:45:45+08:00
[INFO] …
```
=> [Python] Make API client more pluggable

modules/swagger-codegen/src/main/resources/objc/SWGApiClient.m, modules/swagger-codegen/src/main/resources/objc/api-body.mustache, modules/swagger-codegen/src/main/resources/objc/api-header.mustache, modules/swagger-codegen/src/main/resources/objc/apiBodyResponseWithContainer.mustache, modules/swagger-codegen/src/main/resources/objc/apiNonPrimitiveResponse.mustache, modules/swagger-codegen/src/main/resources/objc/apiPrimitiveResponse.mustache, modules/swagger-codegen/src/main/resources/objc/voidResponse.mustache, samples/client/petstore/objc/PetstoreClient/PetstoreClientTests/PetApiTest.m, samples/client/petstore/objc/client/SWGApiClient.m, samples/client/petstore/objc/client/SWGPetApi.h, samples/client/petstore/objc/client/SWGPetApi.m, samples/client/petstore/objc/client/SWGStoreApi.h, samples/client/petstore/objc/client/SWGStoreApi.m, samples/client/petstore/objc/client/SWGUserApi.h, samples/client/petstore/objc/client/SWGUserApi.m
Allows developers to easily customize APIClient and use it to initialize the API class (e.g. PetApi)
If the user passes the `apiClient` when initialize the `PetApi`:
```objc
SWGPetApi *api = [[SWGPetApi alloc] initWithApiClient: apiClient];
```
will set the `apiClient` to be the customized ApiClient `apiClient`.
If the use doesn't pass `apiClient` when initialize `PetApi`:
```objc
SWGPetApi *api = [[SWGPetApi alloc] init];
```
will get the `apiClient` instance from the pool.
Tested without issue:
```sh
[INFO] Total time: 48.675 s
[INFO] Finished at: 2015-05-26T17:58:01+08:00
[INFO] …
```
=> Make objc client more pluggable

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/languages/ObjcClientCodegen.java
Minor fix to output path using `File.separator` #800
=> [ObjC] Minor fix to output path

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/languages/CSharpClientCodegen.java, modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache, modules/swagger-codegen/src/main/resources/csharp/Configuration.mustache, modules/swagger-codegen/src/main/resources/csharp/api.mustache, modules/swagger-codegen/src/main/resources/csharp/apiException.mustache, modules/swagger-codegen/src/main/resources/csharp/apiInvoker.mustache, modules/swagger-codegen/src/main/resources/csharp/model.mustache, samples/client/petstore/csharp/src/main/csharp/io/swagger/Api/PetApi.cs, samples/client/petstore/csharp/src/main/csharp/io/swagger/Api/StoreApi.cs, samples/client/petstore/csharp/src/main/csharp/io/swagger/Api/UserApi.cs, samples/client/petstore/csharp/src/main/csharp/io/swagger/Model/Category.cs, samples/client/petstore/csharp/src/main/csharp/io/swagger/Model/Order.cs, samples/client/petstore/csharp/src/main/csharp/io/swagger/Model/Pet.cs, samples/client/petstore/csharp/src/main/csharp/io/swagger/Model/Tag.cs, samples/client/petstore/csharp/src/main/csharp/io/swagger/Model/User.cs, samples/client/petstore/csharp/src/main/csharp/io/swagger/client/ApiClient.cs, samples/client/petstore/csharp/src/main/csharp/io/swagger/client/ApiException.cs, samples/client/petstore/csharp/src/main/csharp/io/swagger/client/ApiInvoker.cs, samples/client/petstore/csharp/src/main/csharp/io/swagger/client/Configuration.cs
- Added pluggable ApiClient
- Added configuration for authentication and API client
- Added authentication for api key and http basic auth
Tested with `AddPet, UpdatePetWithForm, GetPetById, UploadFile` and no issues found.
=> [C#] Added ApiClient (Pluggable) and authentication (API key and HTTP basic auth)

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/languages/PhpClientCodegen.java, modules/swagger-codegen/src/main/resources/php/APIClient.mustache, samples/client/petstore/php/SwaggerClient-php/lib/APIClient.php, samples/client/petstore/php/test.php
- Added support for Object (currently, response set to object would result in error)
- Removed null elements in the serialised JSON string
- Fixed default header in API client
=> [PHP] Added support for object, removed null in serialized JSON string

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/languages/AndroidClientCodegen.java, modules/swagger-codegen/src/main/resources/android-java/build.mustache, modules/swagger-codegen/src/main/resources/android-java/jsonUtil.mustache
Now that https://github.com/swagger-api/swagger-codegen/pull/805 (thanks @hyeghiazaryan !) has been merged to develop_2.0 (thanks @olensmar !), I've updated the android-java generator to use the new config file functionality.
Here's the output of the android-java config-help : 
```
$ swagger-codegen config-help -l android
CONFIG OPTIONS
modelPackage
package for generated models
apiPackage
package for generated api classes
invokerPackage
root package to use for the generated code
groupId
groupId for use in the generated build.gradle and pom.xml
artifactId
artifactId for use in the generated build.gradle and pom.xml
artifactVersion
artifact version for use in the generated build.gradle and pom.xml
sourceFolder
source folder for generated code
useAndroidMavenGradlePlugin
A flag to toggle …
```
=> [Android] Enabling cli config options for android generator

samples/client/petstore/objc/PetstoreClient/PetstoreClientTests/PetApiTest.m
* Updated test case `testCreateAndGetPet` of objc client.
Tested nested models `category` of `pet` and `tags` of `pet`.
```sh
[INFO] Total time: 41.904 s
[INFO] Finished at: 2015-06-04T16:48:43+08:00
```
=> [Objc] Update test case

README.md
Replaced the following
```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jarr config-help -l java
```
with 
```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar config-help -l java
```
(remove trailing r from jarr)
=> Fixed a minor typo with the command example

modules/swagger-codegen/src/main/java/io/swagger/codegen/AbstractGenerator.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java
Template files (*.mustache) uses `getCPResourcePath` to get the correct path in all platforms.
This PR also leverages `getCPResourcePath` for non-template files to address the file not found issue in Windows as Path inside JAR should use backslash.
The fix has been tested in Windows and Mac.
=> [Bug fix] Fix path inside JAR for non-template files

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ScalaClientCodegen.java, modules/swagger-codegen/src/main/resources/scala/apiInvoker.mustache, modules/swagger-codegen/src/main/resources/scala/pom.mustache, samples/client/petstore/scala/pom.xml, samples/client/petstore/scala/src/main/scala/io/swagger/client/ApiInvoker.scala, samples/client/petstore/scala/src/main/scala/io/swagger/client/model/Pet.scala
* Upgrade jersey to latest version (from 1.7 to 1.19)
* Replace getClientResponseStatus() with getStatusInfo()
* Fix the following maven-build warnings and model-import warnings
```
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:build-helper-maven-plugin is missing. @ line 72, column 15
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[WARNING]  Expected all dependencies to require Scala version: 2.10.4
[WARNING]  com.fasterxml.jackson.module:jackson-module-scala_2.10:2.4.2 requires scala version: 2.10.4
[WARNING]  org.scala-lang:scala-reflect:2.10.4 requires scala version: 2.10.4
[WARNING]  io.swagger:swagger-scala-client:1.0.0 requires scala version: 2.10.4
[WARNING]  org.scalatest:scalatest_2.10:2.1.3 …
```
=> [Scala] Fix warnings and upgrade jersey for Scala client

modules/swagger-codegen/src/main/resources/Java/api.mustache, modules/swagger-codegen/src/main/resources/android-java/api.mustache, samples/client/petstore/android-java/src/main/java/io/swagger/client/model/Pet.java, samples/client/petstore/java/src/main/java/io/swagger/client/api/PetApi.java
Currently, the path variable name in underscore case won't work in Java and Android client.
This PR fixed the issue by using `baseName`.
Tested with manually changing petId to pet_id and the result is good.
=> [Java, Android] Fix path variable name

modules/swagger-codegen/src/main/resources/php/api.mustache
I changed it to `required` and now it works for me. Why was `optional` used and where did it come from?
=> Optional is used in PHP template although not available

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java
I am developing a servlet container lib in Scala, and at the same time a Swagger plug in for it.
I find it helpful to have this key in `postProcessOperations`.
=> Add a `pathPrefix` key to the `operations` key

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConfig.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java
This PR copies model properties of the parent models that are defined with the `allOf` key (with value of either `$ref` or `properties`), i.e. for composed models.
It also fixes #936.
=> Copy properties from parent models defined with allOf

modules/swagger-codegen/src/main/resources/swift/APIs.mustache, modules/swagger-codegen/src/main/resources/swift/Extensions.mustache, modules/swagger-codegen/src/main/resources/swift/Models.mustache, modules/swagger-codegen/src/main/resources/swift/api.mustache, modules/swagger-codegen/src/main/resources/swift/model.mustache
As discussed in #901 I added explicit access control to classes, methods and members to support the use in a Framework, e.g. when using it in a CocoaPod.
cc: @tkQubo
=> [Swift] Support use in Framework

pom.xml
Updated pom.xml to use a newer version of swagger-parser: 1.0.9-SNAPSHOT, which contains updated function for `SwaggerParser().read`
=> Fix compilation error with a newer swagger parser

README.md
Perhaps something was out of date?
=> Fix path in instructions for making your own codegen modules

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AkkaScalaClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AndroidClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AsyncScalaClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ObjcClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PerlClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Python3ClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RetrofitClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RubyClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ScalaClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SinatraServerCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TizenClientCodegen.java, samples/client/petstore/java/src/main/java/io/swagger/client/model/Pet.java
Throw a runtime exception with better error message when operationId is empty
```
[INFO] Total time: 22.696 s
[INFO] Finished at: 2015-07-27T11:20:51+08:00
[INFO] Final Memory: 20M/248M
```
=> [All] Better exception handling for empty operationId (method name)

modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache
If you look at the source of NewtonSoft.Json, you'll see that DeserializeObject never throws an IOException. All exceptions should be caught in this method, just like Serialize.
=> Catch all exceptions on Deserialize

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ObjcClientCodegen.java, modules/swagger-codegen/src/main/resources/objc/ApiClient-body.mustache, modules/swagger-codegen/src/test/scala/Objc/ObjcModelTest.scala, samples/client/petstore/objc/SwaggerClient/SWGApiClient.m, samples/client/petstore/objc/SwaggerClient/SWGPet.h, samples/client/petstore/objc/SwaggerClient/SWGPetApi.h, samples/client/petstore/objc/SwaggerClient/SWGPetApi.m, samples/client/petstore/objc/SwaggerClientTests/Tests/DeserializationTest.m
Fixed the issue that deserialize nested map data.
When parse nested data type like `"NSDictionary* /* NSString, NSDictionary* /* NSString, NSNumber */ */`, the pattern `NSString *dictPat = @"NSDictionary\\* /\\* (.+), (.+) \\*/";` will match key `NSString, NSDictionary* /* NSString,` and value `NSNumber`.
But the correct match key should be `NSString` and the correct match value should be `NSDictionary* /* NSString, NSNumber */ `. The issue will be fixed by replace the pattern `NSString *dictPat = @"NSDictionary\\* /\\* (.+), (.+) \\*/";` with `NSString *dictPat = @"NSDictionary\\* /\\* (.+?), (.+) \\*/";`.
By the way, integration test looks fine:
```sh
Test Suite 'All tests' passed at 2015-07-28 02:57:42 +0000.
Executed 21 tests, with 0 failures (0 unexpected) in 12.322 (12.338) seconds …
```
=> [Objc] Fix deserialize nested map error

modules/swagger-codegen/src/main/resources/objc/Configuration-body.mustache, samples/client/petstore/objc/SwaggerClient/SWGConfiguration.m
The authentication setting were overridden before and this PR will restore the code to determine authentication setting
```sh
Test Suite 'All tests' passed at 2015-08-07 10:27:59 +0000.
Executed 23 tests, with 0 failures (0 unexpected) in 10.887 (10.905) seconds
[INFO] Total time: 01:02 min
[INFO] Finished at: 2015-08-07T18:27:59+08:00
[INFO] Final Memory: 9M/160M
```
=> [Objc] Fix issue about authentication

modules/swagger-codegen/src/main/resources/python/api_client.mustache
Just using `startswith` instead of `in` allows for nested arrays/maps defined in swagger to be translated to the right list/dict combination on python.
Also added unicode to the list of types `sanitize_for_serialization` just returns.
=> Support for nested lists/maps for the python client

modules/swagger-codegen/src/main/resources/objc/ApiClient-body.mustache, samples/client/petstore/objc/SwaggerClient/SWGApiClient.m, samples/client/petstore/objc/SwaggerClientTests/Tests/DeserializationTest.m
Deserializing bool value always returns nil before the fix.
```sh
Test Suite 'All tests' passed at 2015-08-08 07:02:59 +0000.
Executed 24 tests, with 0 failures (0 unexpected) in 10.486 (10.504) seconds
[INFO] Total time: 49.885 s
[INFO] Finished at: 2015-08-08T15:02:59+08:00
```
=> [Objc] Fix deserialize bool value issue

modules/swagger-codegen/src/main/resources/python/configuration.mustache, modules/swagger-codegen/src/main/resources/python/rest.mustache, samples/client/petstore/python/swagger_client/api_client.py, samples/client/petstore/python/swagger_client/configuration.py, samples/client/petstore/python/swagger_client/models/order.py, samples/client/petstore/python/swagger_client/models/pet.py, samples/client/petstore/python/swagger_client/models/user.py, samples/client/petstore/python/swagger_client/rest.py
* Fixed the comatibility of `httplib` lib in python2 and python3.
* Fixed issue that missing newline char in the message of ApiException.
* Tested result:
=> [Python] Fix issues in python client

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JaxRSServerCodegen.java
Currently the codegen ignores Path level params. For example, the following Path and Operation would get converted into a Codegen operation with no parameters, even though there is a path level header parameter.
```yaml
swager: 2.0
paths:
/people :
parameters:
name: "Authorization"
in: "header"
description: "authorization ticket"
required: true
type: "string"
get:
description: Get all the people entities
response:
200:
schema:
$ref: #/definitions/People
```
Additionally, included a fix for #996 while I was at it.
As always feedback on my code is appreciated.
=> Codegen should honor path level parameters

pom.xml
update swagger-parser-version to 1.0.10 (removed snapshot) to resolve CI build error
=> update swagger-parser-version to 1.0.10 (removed snapshot)

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PerlClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SilexServerCodegen.java
- fixed variable names starting with number by appending an underscore at the beginning
- made LOGGER protected (from private) so that code generator can use it for logging
- tested with manually updating a variable name in petstore to start with "00"
```
PHPUnit 4.8.4 by Sebastian Bergmann and contributors.
............
Time: 14.76 seconds, Memory: 6.25Mb
OK (12 tests, 381 assertions)
```
=> [PHP, Perl, Silex] fixed variable names starting with number, made LOGGER protected

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenProperty.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java, modules/swagger-codegen/src/test/scala/Java/JavaModelEnumTest.scala, pom.xml
This fixes https://github.com/swagger-api/swagger-codegen/issues/1050 .
The bug repros if your models use inheritance and enums together. In this event, swagger-codegen output is invalid Java code and will not compile.  This is due to a type conflict with the properties copied from the parent class. The solution proposed in this PR is to remove any enums from child classes that already exist in the parent class.
=> [Java] Fixing subClassed types so that they can use enums

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenOperation.java, modules/swagger-codegen/src/main/resources/htmlDocs/index.mustache, modules/swagger-codegen/src/main/resources/htmlDocs/style.css.mustache, pom.xml
Update static html template to improve navigation, with Up links and jumps between
methods and modules. Added guards around different parameters, to eliminate
empty sections.
See https://gist.github.com/DavidBiesack/a9048b151cd7935c8d76 for sample output from the Uber example shipped with swagger-editor
I also updated the swagger-core dependency to build with most recent as of 2015-08-13
=> improve static html; add template guards for collections. 

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java, modules/swagger-codegen/src/main/resources/python/api_client.mustache, modules/swagger-codegen/src/main/resources/python/configuration.mustache, modules/swagger-codegen/src/main/resources/python/model.mustache, samples/client/petstore/python/swagger_client/api_client.py, samples/client/petstore/python/swagger_client/configuration.py, samples/client/petstore/python/swagger_client/models/category.py, samples/client/petstore/python/swagger_client/models/order.py, samples/client/petstore/python/swagger_client/models/pet.py, samples/client/petstore/python/swagger_client/models/tag.py, samples/client/petstore/python/swagger_client/models/user.py
If the variable name is reserved word or number, then append underscore `_`.
`return` will be `_return`.
`123Number` will be `_123_number`.
Test without issue in both python2 and python3:
```sh
```
=> [Python] Change reserved word handling in python client.

modules/swagger-codegen/src/main/resources/objc/ApiClient-body.mustache, modules/swagger-codegen/src/main/resources/objc/ApiClient-header.mustache, modules/swagger-codegen/src/main/resources/objc/api-body.mustache, samples/client/petstore/objc/SwaggerClient/SWGApiClient.h, samples/client/petstore/objc/SwaggerClient/SWGApiClient.m, samples/client/petstore/objc/SwaggerClient/SWGPet.h, samples/client/petstore/objc/SwaggerClient/SWGPetApi.m, samples/client/petstore/objc/SwaggerClient/SWGStoreApi.m, samples/client/petstore/objc/SwaggerClient/SWGUserApi.m
Add `sanitizeForSerialization` method to sanitize request parameters.
If the parameter is model, return properties hash.
If the parameter is date/datetime, return iso8601 string.
Otherwise return the parameter directly.
Fix issue that it will throw error if not pass optional form parameter.
```sh
Test Suite 'All tests' passed at 2015-08-21 01:55:55 +0000.
Executed 24 tests, with 0 failures (0 unexpected) in 11.356 (11.371) seconds
[INFO] Total time: 39.814 s
[INFO] Finished at: 2015-08-21T09:55:56+08:00 …
```
=> [Objc] Sanitize request parameters in objc client

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java, modules/swagger-codegen/src/main/resources/Java/model.mustache
I found today that models are not cacheable because they do not implement `java.io.Serializable`.  I have added this as an option.
=> [Java] Adding an option so java models can implement Serializable

modules/swagger-codegen/src/main/resources/python/api_client.mustache, modules/swagger-codegen/src/main/resources/python/rest.mustache, samples/client/petstore/python/swagger_client/__init__.py, samples/client/petstore/python/swagger_client/api_client.py, samples/client/petstore/python/swagger_client/apis/__init__.py, samples/client/petstore/python/swagger_client/apis/pet_api.py, samples/client/petstore/python/swagger_client/rest.py
When the http method is `post`, the request will miss query parameters.
```
--------------------------------------------------------------
TOTAL                             1250    472    62%
Ran 27 tests in 41.420s
OK
```
=> [Python] Fix issue that missing query parameters in python client.

modules/swagger-codegen/src/main/resources/php/ObjectSerializer.mustache, samples/client/petstore/php/SwaggerClient-php/lib/ObjectSerializer.php, samples/client/petstore/php/SwaggerClient-php/tests/OrderApiTest.php
- Fixed deserialization for datetime object
- Added a test case to cover deserialization of order (which has a datetime attribute)
```
PHPUnit 4.8.5 by Sebastian Bergmann and contributors.
.............
Time: 9.08 seconds, Memory: 7.50Mb
OK (13 tests, 573 assertions)
```
=> [PHP] Fixed deserialization for datetime object

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenProperty.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/resources/Java/model.mustache
Added support to array of enums in the DefaultCodegen (it used to generate an array of strings instead) and updated the java template to use it.
Tested only in Java and it is working fine. I don't think there will be issues with the other languages (they won't use my changes and will just ignore it).
=> Support to array of enums

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CodeGenStatus.java, pom.xml
Change to DefaultGenerator:
When the generate() method throw an exception, the exception is caught and a stack trace is printed. Due to the way this exception is caught, it is difficult to detect if code generation has failed when we aren't generating code through the command line. 
For this reason, I added enum CodeGenStatus, so a status can be set for each instance of the DefaultGenerator.
This change is inspired by our needs at Wikia, where we are using Swagger to generate code progammatically and would like to easily detect when generation fails.
Please let us know if we've missed anything or didn't take any factors into account with this change.
=> Default Generator Status

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/ApiClient.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/ApiException.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/Configuration.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/JSON.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/Pair.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/StringUtil.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/TypeRef.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/api/PetApi.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/api/StoreApi.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/api/UserApi.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/ApiKeyAuth.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/Authentication.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/HttpBasicAuth.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/OAuth.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Category.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Order.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Pet.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Tag.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/model/User.java
Fix serializableModel in config.json for Java
Tested with no serializableModel in config, serializableModel set to false and serializableModel set to true. Only serializableModel set to true outputs "implements Serializable" (and the corresponding import)
=> [Java] fix serializableModel (boolean)

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenParameter.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenResponse.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java, modules/swagger-codegen/src/main/resources/Java/ApiClient.mustache, modules/swagger-codegen/src/main/resources/Java/api.mustache, modules/swagger-codegen/src/test/resources/2_0/binaryDataTest.json, modules/swagger-codegen/src/test/scala/CodegenTest.scala, modules/swagger-codegen/src/test/scala/Java/JavaModelTest.scala
This is my implementation of Java code generation, including the generic (not language specific) support needed, for binary data in the request body and in the response.
This implementation is based on the agreed spec, as discussed in swagger-api/swagger-spec#50 and depends on my pull request to swagger-core which was merged on Aug-6 (swagger-api/swagger-core#1335)
This PR replaces #1065
=> support binary input and output

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java
Add an CLI option (-c) to config variable naming convention using camelCase (default is snake_case). here is an example of config.json
```
{
"variableNamingConvention": "camelCase"
}
```
Test cases passed:
```
PHPUnit 4.8.6 by Sebastian Bergmann and contributors.
.............
Time: 8.61 seconds, Memory: 10.25Mb
OK (13 tests, 1189 assertions)
```
=> [PHP] add camelCase support for variable naming

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java, modules/swagger-codegen/src/main/resources/Java/JSON.mustache, modules/swagger-codegen/src/main/resources/Java/enumClass.mustache, modules/swagger-codegen/src/main/resources/Java/model.mustache, samples/client/petstore/java/default/src/main/java/io/swagger/client/JSON.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Order.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Pet.java, samples/client/petstore/java/default/src/test/java/io/swagger/petstore/test/PetApiTest.java, samples/client/petstore/java/default/src/test/java/io/swagger/petstore/test/StoreApiTest.java, samples/client/petstore/java/jersey2/hello.txt, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/JSON.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/model/Order.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/model/Pet.java, samples/client/petstore/java/jersey2/src/test/java/io/swagger/petstore/test/PetApiTest.java, samples/client/petstore/java/jersey2/src/test/java/io/swagger/petstore/test/StoreApiTest.java
Fix #1102: "Need to avoid language keywords in enums"
* Use upper case for enum names to comply with [convention](https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html)
* Prepend enum name with underscore if it starts with number
Example code:
```java
public enum StatusEnum {
AVAILABLE("available"), PENDING("pending"), SOLD("sold"), SWITCH("switch"), _1M("1m");
private String value;
StatusEnum(String value) {
this.value = value;
}
@Override
public String toString() {
return value;
}
}
```
=> [Java] Support special characters in enum values

samples/client/petstore/objc/SwaggerClientTests/Tests/SWGApiClientTest.m
Add test cases for `sanitizeForSerialization` method.
Integration test looks fine:
```
Test Suite 'All tests' passed at 2015-08-25 01:40:25 +0000.
Executed 25 tests, with 0 failures (0 unexpected) in 10.826 (10.848) seconds
[INFO] Total time: 01:39 min
[INFO] Finished at: 2015-08-25T09:40:25+08:00
```
=> [Objc] Add test cases for sanitizeForSerialization method in objc client

modules/swagger-codegen/src/main/resources/Java/ApiClient.mustache, modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache
Per #990 
I would like to add the ability to return the status code and response headers from the previous API call from java and csharp. The python client already provides this ability via the last_response variable. This is necessary for our API, as we need the value of the Location header after a POST request.
Approach: Before returning the response body, set the non-body parts of the response on ApiClient.
=> Add status code and response headers of the last request to java and c#

modules/swagger-codegen/src/main/resources/csharp/compile.mustache, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/compile.bat
invokerPackage is no longer used and it's replaced by packageName instead.
=> [C#] fix invokerPackage with packageName in compile.mustache

modules/swagger-codegen/src/main/java/io/swagger/codegen/examples/XmlExampleGenerator.java
As requested in #1098 re-submitting this PR with the master branch.
Issue which is solved: getWrapped() returns a Boolean which can be null
With https://zeef.io/api/swagger.json the problem is there. Since the merge from develop_2.0 to master it does not display the NPE anymore while generating the (in my case Swift) library, but it generates an incomplete one.
=> Fix possible NullPointerException

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/NodeJSServerCodegen.java, modules/swagger-codegen/src/main/resources/nodejs/swagger.mustache
This fixes a bug introduced in #1037 where the `swagger.json` file would have extra trailing commas after the `paths` property, as well as missing paths, for some input swagger definitions.
=> [Node.js] fix invalid JSON being generated in swagger.json

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ObjcClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RubyClientCodegen.java, modules/swagger-codegen/src/test/scala/Java/JavaModelTest.scala, samples/client/petstore/python/swagger_client/__init__.py, samples/client/petstore/python/swagger_client/apis/__init__.py, samples/client/petstore/python/swagger_client/apis/pet_api.py
- Added function to sanitize name (parameter, property).
- Added test case in Java to cover parentheses (e.g. query[password])
- Updated C#, Java, Objc, Ruby, Python and PHP to use sanitizeName
Will file another PR to cover remaining languages if no one has concern with the current approach.
=> Add function to sanitize name (1)

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
This builds on #1139, calling the new sanitizeName() method before camelizing it when generating model names.
This is still only a partial solution to #1142 → dashes in paths with spring-mvc still lead to class names with dashes. I'll try to solve this in a separate pull request.
--------
I guess there should be some test for this ... it looks like currently all the existing tests are written in Scala. As I don't know Scala at all, I won't try to spend time trying to add a test for this. Should I add a Java test instead, or can we find some other contributor for writing the test?
Here is a file which produces a broken model class (Example-parent) before the change and a "good" one (ExampleParent) after the change:
```
swagger: '2.0'
info:
title: Swagger Codegen bug trigger
description: | …
```
=> Issue #1142: sanitize the class name for Java model classes.

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JaxRSServerCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SpringMVCServerCodegen.java
This builds on #1139 in order to solve another part of #1142:
When the first component of a path contained a dash, the generated class name contained this dash too (for the "language" spring-mvc).
The same problem for model names is solved by #1163.
=> Issue #1142: sanitize api name before camelizing.

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
Related to Issue #1146, this removes leading and trailing whitespace before escaping strings. This gets rid of annoying `\n` in some string literals (e.g. in annotations used in jaxrs).
Before (extract):
```
/**
* This is an object with a ...\n\n... multiline description.\n
**/
@ApiModel(description = "This is an object with a ...\n\n... multiline description.\n")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JaxRSServerCodegen", date = "2015-08-28T20:04:46.661+02:00")
public class Example  {
private String foo = null;
/**
* even foo has a\nmulti-line description.\n
**/
@ApiModelProperty(value = "even foo has a\nmulti-line description.\n")
@JsonProperty("foo")
public String getFoo() {
return foo;
}
public void setFoo(String foo) {
this.foo = foo;
}
```
After:
``` …
```
=> trim strings before escaping

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
* fix issue #1143: add another null check.
The problem was trying to iterate over a null list.
----
I guess there should be some test for this ... it looks like currently all the existing tests are written in Scala. As I don't know Scala at all, I won't try to spend time trying to add a test for this. Should I add a Java test instead, or can we find some other contributor for writing the test?
Here is an example yaml file which breaks before the fix, and runs after the fix (though I did not check if the generated classes are fully sensible).
```
swagger: '2.0'
info:
title: Swagger Codegen bug trigger
description: |
This demonstrates a bug in swagger-codegen.
version: 0.0.1
basePath: /api
definitions:
manual_discount:
type: object
properties:
percent_value:
type: number
minimum: 0.0 …
```
=> Add null check to fix issue #1143

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ObjcClientCodegen.java, modules/swagger-codegen/src/main/resources/objc/podspec.mustache
- For a podspec file to lint, a few extra parameters were required. Specifically:
- `authorName`: defaults to "Swagger"
- `authorEmail`: deaults to "apiteam@swagger.io"
- `license`: defaults to "MIT"
- `gitRepoURL`: Used for both the homepage and source keys in the podspec file; defaults to "https://github.com/swagger-api/swagger-codegen"
- While additional fields can be added to support all of the possible podspec fields (s.authors instead of s.author, etc), these represent the minimum requirements for the pod to lint without errors (there may still be warnings, but these can be ignored with the --allow-warnings flag).
=> [Obj-C][Cocoapods] Added extra CLI options to generate a valid podspec file.

modules/swagger-codegen/src/main/resources/objc/ApiClient-body.mustache, modules/swagger-codegen/src/main/resources/objc/ApiClient-header.mustache, modules/swagger-codegen/src/main/resources/objc/api-body.mustache, modules/swagger-codegen/src/main/resources/objc/api-header.mustache, samples/client/petstore/objc/README.md, samples/client/petstore/objc/SwaggerClient/SWGApiClient.h, samples/client/petstore/objc/SwaggerClient/SWGApiClient.m, samples/client/petstore/objc/SwaggerClient/SWGPetApi.h, samples/client/petstore/objc/SwaggerClient/SWGPetApi.m, samples/client/petstore/objc/SwaggerClient/SWGStoreApi.h, samples/client/petstore/objc/SwaggerClient/SWGStoreApi.m, samples/client/petstore/objc/SwaggerClient/SWGUserApi.h, samples/client/petstore/objc/SwaggerClient/SWGUserApi.m
- Added a property on the ApiClient class that is set before any operation's completionBlock. This allows access to the HTTP response headers by calling `.apiClient.HTTPResponseHeaders` in any of the API-bodies' completion blocks. 
- Note: It is recommended to only have one ApiClient per thread to ensure that there is no concurrency issues with the HTTPResponseHeaders property across multiple threads.
- Also added a `+sharedAPI` class method on the API-Body classes that allows quick initialization of a singleton API instance. I added this because calling `+apiWithHeader:key:` would not actually add the header and key values unless the singleton was previously nil, and it was the only way to retrieve an existing singleton instance (i.e. if I wanted to access the singleton multiple times, I …
=> [Obj-C] Added ability to access HTTP Response headers 

modules/swagger-codegen/src/main/resources/TypeScript-Angular/api.mustache, modules/swagger-codegen/src/main/resources/TypeScript-node/api.mustache, samples/client/petstore/swift/PetstoreClient.podspec, samples/client/petstore/typescript-angular/API/Client/PetApi.ts, samples/client/petstore/typescript-angular/API/Client/StoreApi.ts, samples/client/petstore/typescript-angular/API/Client/UserApi.ts, samples/client/petstore/typescript-node/api.ts
Fixed https://github.com/swagger-api/swagger-codegen/issues/1181 by replacing {{contextPath}} with {{basePath}}
=> [TypeScript] Fix base path

modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/build.gradle.mustache, modules/swagger-codegen/src/main/resources/android-java/build.mustache, samples/client/petstore/android-java/build.gradle, samples/client/petstore/java/okhttp-gson/build.gradle
In the okhttp-gson library template, set source and target compatibility to 1.7 in build.gradle to make it work with Android
=> [Java okhttp-gson, Android] Set source and target compatibility to 1.7 in build.gradle

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenModel.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenProperty.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/resources/JavaJaxRS/model.mustache
Previously, the description strings for models and properties were escaped (replacing newlines with a literal `\n`).
This resulted in files like this (see below for an example swagger yaml file):
```
/**
* This is an object with a ...\n... multiline description.
**/
@ApiModel(description = "This is an object with a ...\n... multiline description.")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JaxRSServerCodegen", date = "2015-08-28T18:54:37.200+02:00")
public class Example  {
private String foo = null;
/**
* even foo has a\nmulti-line description.\n
**/
@ApiModelProperty(value = "even foo has a\nmulti-line description.\n")
@JsonProperty("foo")
public String getFoo() {
return foo;
}
public void setFoo(String foo) {
this.foo = foo;
}
```
These `\n` in the Javadocs …
=> jaxrs (and other Java generators): do not escape newlines in generated javadocs.

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/resources/JavaJaxRS/api.mustache
This is the fix for #1146: line breaks in response descriptions are now escaped, so they don't create invalid Java string literals anymore.
In addition, fix the indentation in the generated API operation method.
**I did only test this with with the jaxrs generator (and did run the tests which are included in the build). Please check whether this breaks anything for other languages.**
-----------
I guess there should be some test for this ... it looks like currently all the existing tests are written in Scala. As I don't know Scala at all, I won't try to spend time trying to add a Scala test for this. Should I add a Java test instead, or can we find some other contributor for writing the test?
Here is an example yaml file which generates a non-compilable class before the fix and compilable …
=> jaxrs: escape line breaks in response description

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SinatraServerCodegen.java
It should return CodegenType.SERVER instead of CodegenType.CLIENT similar to other server-side code generator.
=> [Sinatra] fix sinatra type (tag)

modules/swagger-codegen/src/main/resources/php/ApiClient.mustache
The generated PHP client didn't support the HEAD and OPTIONS methods.
Followup on #1156 and #1201.
=> Add HEAD and OPTIONS support in PHP client.

modules/swagger-codegen/src/main/resources/csharp/api.mustache
The parameter in the BasePath getter is not needed.
=> [C#] Api.mustache - Remove the parameter in the BasePath getter

modules/swagger-codegen/src/main/resources/objc/api-body.mustache
The method `-dataUsingEncoding` cannot be called on NSNumber objects so we need to convert them into NSStrings before adding them to the formParams, pathParams, and bodyParams arrays.
=> [Obj-C] Fixed an issue where NSNumber parameters would cause a crash in multipart/form-data upload endpoints

modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache, samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/ApiClient.java
* For endpoints with [file response](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#response-object), save file from response body and return it
* Allow customizing the folder for file downloading via `ApiClient#setTempFolderPath`
Integration test result of the Petstore sample:
```
-------------------------------------------------------
T E S T S
-------------------------------------------------------
Concurrency config is parallel='methods', perCoreThreadCount=true, threadCount=2, useUnlimitedThreads=false
Running io.swagger.client.ApiClientTest
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.379 sec
Concurrency config is parallel='methods', perCoreThreadCount=true, threadCount=2, useUnlimitedThreads=false
Running …
```
=> [Java okhttp-gson] Add support of file downloading

modules/swagger-codegen/src/main/resources/ruby/api_client.mustache, samples/client/petstore/ruby/lib/petstore/api_client.rb
It should use the one from the Configuration object.
Integration test looks fine:
```
Finished in 45.89 seconds (files took 0.36945 seconds to load)
21 examples, 0 failures
[INFO] Total time: 49.643 s
[INFO] Finished at: 2015-09-15T15:10:11+08:00
```
=> Fix issue that using temp_folder_path from ApiClient in ruby client

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RetrofitClientCodegen.java, modules/swagger-codegen/src/main/resources/retrofit/api.mustache, modules/swagger-codegen/src/main/resources/retrofit/auth/apikey.mustache, modules/swagger-codegen/src/main/resources/retrofit/auth/basic.mustache, modules/swagger-codegen/src/main/resources/retrofit/auth/oauth.mustache, modules/swagger-codegen/src/main/resources/retrofit/auth/oauthflow.mustache, modules/swagger-codegen/src/main/resources/retrofit/auth/oauthokclient.mustache, modules/swagger-codegen/src/main/resources/retrofit/pom.mustache, modules/swagger-codegen/src/main/resources/retrofit/service.mustache, samples/client/petstore/retrofit/pom.xml, samples/client/petstore/retrofit/src/main/java/io/swagger/client/ServiceGenerator.java, samples/client/petstore/retrofit/src/main/java/io/swagger/client/api/PetApi.java, samples/client/petstore/retrofit/src/main/java/io/swagger/client/api/StoreApi.java, samples/client/petstore/retrofit/src/main/java/io/swagger/client/api/UserApi.java, samples/client/petstore/retrofit/src/main/java/io/swagger/client/auth/ApiKeyAuthorization.java, samples/client/petstore/retrofit/src/main/java/io/swagger/client/auth/BasicAuthorization.java, samples/client/petstore/retrofit/src/main/java/io/swagger/client/auth/OauthAuthorization.java, samples/client/petstore/retrofit/src/main/java/io/swagger/client/auth/OauthFlow.java, samples/client/petstore/retrofit/src/main/java/io/swagger/client/auth/OauthOkHttpClient.java, samples/client/petstore/retrofit/src/main/java/io/swagger/client/model/ApiResponse.java, samples/client/petstore/retrofit/src/main/java/io/swagger/client/model/Pet.java, samples/client/petstore/retrofit/src/test/java/io/swagger/petstore/test/PetApiTest.java, samples/client/petstore/retrofit/src/test/java/io/swagger/petstore/test/StoreApiTest.java, samples/client/petstore/retrofit/src/test/java/io/swagger/petstore/test/UserApiTest.java
Added basic auth, api key and oauth support to the service generator using okhttp interceptors.
For oauth2, the apache oltu lib is used.
Fix #962
=> [Retrofit] add authorizations to retrofit client

modules/swagger-codegen/src/main/resources/JavaInflector/model.mustache, modules/swagger-codegen/src/main/resources/JavaJaxRS/model.mustache, modules/swagger-codegen/src/main/resources/JavaSpringMVC/model.mustache
This changes `@JsonProperty({{name}})` to `@JsonProperty({{baseName}})` in model.mustache for JavaInflector, JavaJaxRS and JavaSpringMVC.
In pull request #535 this was already done for the plain Java files (which get used on client side).
This replaces the sanitized names in the generated code by the original property names from the swagger document.
=> Use the swagger property names in all Java models.

modules/swagger-codegen/src/main/resources/TypeScript-Angular/api.mustache
Changes the generated API classes to use the baseName instead of the parameter name: for a url specified as /resource/{resource_id}, the following incorrect typescript was generated:
```typescript
var path = this.basePath + '/resource/{resource_id}';
path = path.replace('{' + 'resourceId' + '}', String(resourceId));
```
which obviously fails to replace the parameter.
Query parameters have a similar problem.
=> Use the baseName when referring to path and query parameters.

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
A model that inherits from another model and does not add its own properties
causes JavaClientCodegen to crash silently with an NPE.
Fixes #1141
=> Fix NPE in JavaClientCodegen when model has no properties of its own

modules/swagger-codegen/src/main/resources/TypeScript-node/api.mustache, samples/client/petstore/typescript-node/api.ts
Similar to #1246, this PR fixes parameter name for typescript-node using {{baseName}} instead of {{paramName}}
=> [TypeScript] fix parameter name for typescript-node using baseName

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenProperty.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
Swagger codegen doesn't read the readOnly attribute on model properties from the swagger json, now the codegen engine will read the property and expose it to the templates as "isReadOnly" in model.mustache. 
This only exposes the attribute to the template but doesnt actually do anything with it.
=> Expose readOnly attribute on model properties to templates

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConstants.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, samples/client/petstore/php/SwaggerClient-php/lib/Api/UserApi.php, samples/client/petstore/php/SwaggerClient-php/lib/ApiClient.php
Provide CLI option `sortParamsByRequiredFlag ` to optionally sort method arguments based on required/optional.
Tested with true, false and option not provided.
=> Add CLI option to sort method arguments

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java, modules/swagger-codegen/src/main/resources/Java/enumClass.mustache, samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Order.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Pet.java
* [Nicer normalization on enum var name](https://github.com/swagger-api/swagger-codegen/issues/1229#issuecomment-141129940). For example:  
`http://example.com/status/OK` => `HTTP_EXAMPLE_COM_STATUS_OK`  
(was using `HTTPEXAMPLE_COMSTATUSOK` before)
* [Place each enum var in a separate line](https://github.com/swagger-api/swagger-codegen/issues/1229#issuecomment-141134764)
* [Truncate enum name by removing common prefix when present](https://github.com/swagger-api/swagger-codegen/issues/1229#issuecomment-141925993)
The integration test of the Petstore sample is fine:
```
Results :
Tests run: 33, Failures: 0, Errors: 0, Skipped: 0
```
=> [Java] Improvements on enum var name in Java client

modules/swagger-codegen/src/main/resources/Java/ApiClient.mustache, modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/ApiClient.mustache, modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache, samples/client/petstore/java/default/src/main/java/io/swagger/client/ApiClient.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/ApiClient.java, samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/ApiClient.java
Return raw response body as string for API endpoints with string response, i.e. `{"type": "string"}`.
The integration tests are fine:
(default)
> Tests run: 33, Failures: 0, Errors: 0, Skipped: 0
library: jersey2
> Tests run: 33, Failures: 0, Errors: 0, Skipped: 0
library: okhttp-gson
> Tests run: 34, Failures: 0, Errors: 0, Skipped: 0
=> [Java] Support primitive string response in Java clients

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenOperation.java, modules/swagger-codegen/src/main/resources/TypeScript-Angular/api.mustache, samples/client/petstore/typescript-angular/API/Client/PetApi.ts, samples/client/petstore/typescript-angular/API/Client/StoreApi.ts, samples/client/petstore/typescript-angular/API/Client/UserApi.ts, samples/client/petstore/typescript-angular/API/Client/api.d.ts, samples/client/petstore/typescript-node/api.ts
Follow up on #1246.
I ended up extending the CodegenOperation as formParams.length does not work as expected.
Note that this changes the constructor signature of API classes.
=> implement form parameter support using Angular $httpParamSerializer

modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/ApiClient.mustache, samples/client/petstore/java/default/src/main/java/io/swagger/client/ApiClient.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/ApiClient.java
Fix ApiClient.setDateFormat in Java jersey2 client, the same with the fix to the default Java client in PR #1284.
=> [Java jersey2]: Fix ApiClient.setDateFormat in Java jersey2 client

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RubyClientCodegen.java, samples/client/petstore/python/swagger_client/apis/user_api.py
* Fixed issue that model name not camelized in python client and ruby client.
`ruby`
```
Finished in 26.47 seconds (files took 0.18982 seconds to load)
21 examples, 0 failures
[INFO] Total time: 29.888 s
[INFO] Finished at: 2015-09-24T16:09:34+08:00
```
`python`
```
-----------------------------------------------------------------
TOTAL                                1245    471    62%
Ran 28 tests in 29.579s …
```
=> [Python, Ruby] Fix issues in python and ruby clients

samples/client/petstore/objc/SwaggerClientTests/SwaggerClient/SwaggerClient-Info.plist, samples/client/petstore/objc/SwaggerClientTests/Tests/PetApiTest.m
* Added test case for upload only file.
```
Test Suite 'All tests' passed at 2015-09-25 16:43:42.907.
Executed 26 tests, with 0 failures (0 unexpected) in 36.410 (36.435) seconds
[INFO] Total time: 01:17 min
[INFO] Finished at: 2015-09-25T16:43:43+08:00
```
=> [Objc] Add test case in objc client

modules/swagger-codegen/src/main/resources/python/configuration.mustache, modules/swagger-codegen/src/main/resources/python/rest.mustache, samples/client/petstore/python/swagger_client/configuration.py, samples/client/petstore/python/swagger_client/rest.py
* Added configuration options `cert_file` and `key_file`.
```
-----------------------------------------------------------------
TOTAL                                1257    467    63%
Ran 28 tests in 37.456s
OK
```
=> [Python] Support client certificate file and client key file in TLS/SSL

modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache, modules/swagger-codegen/src/main/resources/csharp/ApiException.mustache, modules/swagger-codegen/src/main/resources/csharp/api.mustache
this fixes the build warnings for xmldoc comments for c#. Generic return types are removed from the documentation so that the docs can at least be generated.
=> Csharp comments

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache, samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/ApiClient.java
* Add the `verifyingSsl` option to allow skipping verifying SSL
certificate and host name (default to verify)
* Add the `sslCaCert` option to allow customizing the CA certificates
Tested those two options against
https://certs.cac.washington.edu/CAtest/
and the CA certificate downloaded from
https://www.washington.edu/itconnect/security/ca/load-der.crt
in both desktop JVM and Android phone.
And the integration test is good:
```
Results :
Tests run: 34, Failures: 0, Errors: 0, Skipped: 0
```
=> Add some SSL options to Java okhttp-gson client

modules/swagger-generator/pom.xml, modules/swagger-generator/src/main/java/io/swagger/generator/Bootstrap.java, modules/swagger-generator/src/main/resources/version.prop
The version is set in the "version" field of the swagger.json
Fix #1314
=> Add version to swagger.json from pom's version

modules/swagger-codegen/src/main/resources/php/api.mustache, samples/client/petstore/php/SwaggerClient-php/lib/Api/PetApi.php, samples/client/petstore/php/SwaggerClient-php/lib/Api/StoreApi.php, samples/client/petstore/php/SwaggerClient-php/lib/Api/UserApi.php, samples/client/petstore/php/SwaggerClient-php/lib/ObjectSerializer.php
The `$httpHeader` variable was not set when catching exceptions.
See also #1354.
Regenerated php-petstore sample.
=> Use HTTP headers from ApiException in PHP client.

pom.xml
Add `<argLine>-XX:+StartAttachListener</argLine>` to solve the TestNG execution on OSX
=> Add StartAttachListener that fixes #1330

modules/swagger-codegen/src/main/resources/objc/ApiClient-body.mustache
Because the `data` that we're deserializing is of type `id` (essentially untyped), it's possible to have method resolution clashes without explicitly casting here once we've sufficiently parsed a type. I had this issue with a pagination container model, for instance, which has a field named `count` that conflicts with the property of the same name on `NSArray` or `NSDictionary`, preventing the code from compiling until I made this change.
=> [objc] Add casts that avoid method resolution errors for `count`

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
Add `_` in front of enum names that start with number, e.g.
```java
public enum PeriodEnum {
_30M("30m"),
// ...
}
```
=> [Java] Handle enum names starting with number in Java client

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaInflectorServerCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JaxRSServerCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SpringMVCServerCodegen.java
=> Remove duplicate fields from sub-classes of the Java codegen

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CsharpDotNet2ClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
Rebased version of PR #1379 (Closed by mistake...)
----
Hello,
here is a two bug fix proposal in the client code generation:
compilation problem with the Long instance initialization in Java code generator (before: "Long id =1;" now: "Long id=1l;")
generation problem with the creation of the paths in both C# implementation (the creation of the package path has a side-effect on the full path, even the existing local path containing a dot character)
Hope this help
Gwen
=> REST client code generation bug fix proposal

modules/swagger-codegen/src/main/resources/Java/libraries/retrofit/ApiClient.mustache
When no authentication methods are defined, the generated code does not compile due to where the authMethods closing tag is located. Moved the closing tag further down and opening tag further up so that the generated code is correct both when authentication are and aren't present.
=> Fix syntax issue when no auth methods defined

modules/swagger-codegen/src/main/resources/swift/model.mustache
Current Swift model classes cannot be simply instantiated from user's code. I added default parameterless initializer to create objects to use in POST requests, for example.
=> Add default initializer to Swift model classes.

modules/swagger-codegen/src/main/resources/php/ApiClient.mustache, modules/swagger-codegen/src/main/resources/php/ApiException.mustache
Currently it's not possible to use custom models in the ApiException because the body gets not deserialized to Json and therefore the object deserializer cannot deserialize it to a custom model. This pull request uses the same mechanism as used to deserialize the response body in case of a 2xx status code.
It removes also a lot of unnecessary whitespace at the end of the lines.
=> Deserialize the response body in case of an ApiException

modules/swagger-codegen/src/main/resources/php/ApiClient.mustache
This is a fix for #1394. I had not merged the data correctly after the rebase
=> ApiException doesn't use deserialized data

modules/swagger-codegen/src/main/resources/perl/BaseObject.mustache, samples/client/petstore/perl/lib/WWW/SwaggerClient/Object/BaseObject.pm
Seems to be required when using perl v5.10.1 and the perl generated api client.
=> [Perl] Ensure parameters to "each" is a hash in TO_JSON and from_hash

modules/swagger-codegen-maven-plugin/src/main/java/io/swagger/codegen/plugin/CodeGenMojo.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java
You can now generate code for a specific model by passing `-Dmodels=User,Pet,Category` to the generator.  When specifying a set of models only, operations and supporting files are *not* generated.
=> made selective generation of models

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
Include exception message showing `Empty method/operation name (operationId) not allowed`:
```
reading from https://raw.githubusercontent.com/kinlane/api-stack/gh-pages/data/google/google-spreadsheets-swagger.json
Exception in thread "main" java.lang.RuntimeException: Could not process operation:
Tag: 
Operation: 
Resource: get /accounts
Definitions: {}
Exception: Empty method/operation name (operationId) not allowed
at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:536)
at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:423)
at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:189)
at io.swagger.codegen.cmd.Generate.run(Generate.java:188)
at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: …
```
=> Better error message for empty operationId

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
Fixes #1429 
Using the spec from the issue, Child now looks like:
```json
{
"model" : {
"parent" : "Parent",
"name" : "Child",
"classname" : "Child",
"classVarName" : "child",
"modelJson" : "{\n  \"allOf\" : [ {\n    \"$ref\" : \"#/definitions/Parent\"\n  }, {\n    \"properties\" : {\n      \"childProp\" : {\n        \"type\" : \"string\"\n      }\n    }\n  } ]\n}",
"vars" : [ {
"baseName" : "id",
"getter" : "getId",
"setter" : "setId",
"datatype" : "String",
"datatypeWithEnum" : "String",
"name" : "id",
"defaultValue" : "null",
"baseType" : "String",
"jsonSchema" : "{\n  \"type\" : \"string\"\n}",
"hasMore" : true,
"isPrimitiveType" : true,
"isNotContainer" : true,
"isEnum" : false
}, {
"baseName" : "childProp",
"getter" : "getChildProp",
"setter" : "setChildProp",
"datatype" : "String", …
```
=> Ensure hasMore is updated when reconciling enum properties from parent

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwiftCodegen.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/languages/SwiftCodegenTest.java
Here is a solution for #1420 that I have reported. I introduced unit test for SwiftCodegen which documents the behavior by the way.
=> Swift enum names capitalization follows Swift convention.

modules/swagger-codegen/src/main/resources/swift/AlamofireImplementations.mustache, modules/swagger-codegen/src/main/resources/swift/Cartfile.mustache, modules/swagger-codegen/src/main/resources/swift/Podspec.mustache
Upgrades the AlamofireImplementation to [Alamofire](https://github.com/Alamofire/Alamofire) 3.0. This PR should not cause changes in the generated API. I will later create a PR where new features of Alamofire will be used, but this will cause breaking changes to the generated code.
=> Swift Alamofire 3.0

modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache, modules/swagger-codegen/src/main/resources/csharp/api.mustache
Changing Stream deserialization to use raw bytes from response, rather than UTF-8 decoded text.
Specifically, when an endpoint returns a PDF as a byte stream in the response, decoding as UTF-8 (as in RestResponse.Contents) will cause the results to be mangled.
=> Raw Binary for File Output

modules/swagger-codegen/src/main/resources/csharp/api.mustache
The word "path" is extremely common in option names for swagger APIs.
I encountered issues when generating API code in C# for the popular [kubernetes](https://github.com/kubernetes/kubernetes) project. Here is the output:
```cs
/// <summary>
/// connect HEAD requests to proxy of Pod 
/// </summary>
/// <param name="_namespace">object name and auth scope, such as for teams and projects</param> 
/// <param name="name">name of the Pod</param> 
/// <param name="path">Path is the URL path to use for the current proxy request to pod.</param> 
/// <returns>string</returns>            
public string ConnectHeadNamespacedPodProxy (string _namespace, string name, string path)
{
// verify the required parameter '_namespace' is set
if (_namespace == null) throw new ApiException(400, "Missing required …
```
=> Change usage of "path" in C# code generation

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConstants.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AndroidClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CsharpDotNet2ClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/DartClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FlashClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RubyClientCodegen.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/android/AndroidClientOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/csharp/CSharpClientOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/csharpdotnettwo/CsharpDotNet2ClientOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/dart/DartClientOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/flash/FlashClienOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/nodejs/NodeJSServerOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/php/PhpClientOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/python/PythonClientOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/ruby/RubyClientOptionsTest.java
processOptions tests have been added for Android, Ruby, nodeJS, php, python, csharp, CsharpDotNet2, dart, flash.
Options Help for CsharpDotNet2ClientCodegen (clientPackage option was missed),  DartClientCodegen (pubDescription option was missed) have been fixed.
=> processOptions tests have been added for Android, Ruby, nodeJS, php, python, csharp, CsharpDotNet2, dart, flash

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaInflectorServerCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JaxRSServerCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SpringMVCServerCodegen.java
Assign default value (if present)  for primitive properties in Java-related client and server codegen. See  #1448
For example:
```java
Integer pageSize = 100;
Long max = 10000l;
Float myFloat = 1.2f;
Double myDouble = 3.4d;
String message = "Hello";
Boolean published = false;
StatusEnum status = StatunEnum.AVAILABLE;
```
=> [Java] Assign default value for primitive properties

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConstants.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ObjcClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PerlClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SpringMVCServerCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwiftCodegen.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/akkascala/AkkaScalaClientOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/asyncscala/AsyncScalaClientOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/inflector/JavaInflectorServerOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/objc/ObjcClientOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/perl/PerlClientOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/qtfivecpp/Qt5CPPOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/scala/ScalaClientOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/scalatra/ScalatraServerOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/silex/SilexServerOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/sinatra/SinatraServerOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/springmvc/SpringMVCServerOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/staticDocs/StaticDocOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/statichtml/StaticHtmlOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/swagger/SwaggerOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/swaggeryaml/SwaggerYamlOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/swift/SwiftOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/tizen/TizenClientOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/typescriptangular/TypeScriptAngularClientOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/typescriptnode/TypeScriptNodeClientOptionsTest.java
processOptions tests have been added for Objc, perl, spring-mvc, swift, scala, async-scala, qt5cpp, html, dynamic-html, swagger, swagger-yaml, tizen, typescript-angular, typescript-node, akka-scala, inflector, scalatra, silex and sinatra
=> processOptions tests have been added for the rest of languages

modules/swagger-codegen/src/main/resources/Java/libraries/retrofit/ApiClient.mustache, modules/swagger-codegen/src/main/resources/Java/libraries/retrofit/auth/OAuth.mustache, samples/client/petstore/java/retrofit/src/main/java/io/swagger/client/ApiClient.java, samples/client/petstore/java/retrofit/src/main/java/io/swagger/client/auth/OAuth.java
* Add a listener on new token reception that can then be stored or logged for debug
* Add an helper method to add authorizations (otherwise if the swagger def is not complete or correct, it is hard to configure from the main app)
=> [Retrofit]Add a listener on new token reception

modules/swagger-codegen/src/main/resources/swift/APIs.mustache
Adds much desired ability to add custom HTTP headers as reported in #1345.
Base URL is now modifyable for clients running on different environments (e.g. testing/production)
=> Custom headers in Swift; base URL is now modifyable

modules/swagger-codegen/src/main/resources/Java/ApiClient.mustache, modules/swagger-codegen/src/main/resources/Java/auth/OAuth.mustache, modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/ApiClient.mustache, modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache, samples/client/petstore/java/default/src/main/java/io/swagger/client/ApiClient.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/OAuth.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/ApiClient.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/auth/OAuth.java, samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/ApiClient.java, samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/auth/OAuth.java
ref: #1441
credit: @mach-kernel
see also #1446, #1485
The integration test is good for Java clients (default, jersey2 and okhttp-json):
```
Tests run: 33, Failures: 0, Errors: 0, Skipped: 0
```
=> Add oauth support for Java client

modules/swagger-codegen/src/main/resources/ruby/base_object.mustache, samples/client/petstore/ruby/lib/petstore/models/base_object.rb, samples/client/petstore/ruby/spec/base_object_spec.rb
For example, the "scoreMap" and "cateMap" properties below:
```json
"definitions": {
"User": {
"properties": {
"scoreMap": {
"type": "object",
"additionalProperties": {
"type": "integer",
"format": "int32",
}
},
"cateMap": {
"type": "object",
"additionalProperties": {
"$ref": "#/definitions/Category"
}
}
}
}
}
```
The integration test is good:
```
.........................
Finished in 37.14 seconds (files took 0.41683 seconds to load)
25 examples, 0 failures
```
=> Ruby: support map/hash in model deserialization with additionalProperties

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JaxRSServerCodegen.java
Replace File.separator with '/' to fix Windows path generation and avoid regular expression issues - see #1391 for details of the issue.
Root cause was inconsistent use of File.separator vs hard-coded '/' characters in the code, compounded by File.separator not playing nice in regular expressions on Windows (where it becomes an un-escaped backslash).
All tests are still passing but someone with much better knowledge of the project than me will need to review and assess any wider impacts of the change.
=> Fix for #1391

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConstants.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RubyClientCodegen.java, modules/swagger-codegen/src/main/resources/Java/api.mustache, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/AkkaScalaClientOptionsProvider.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/AndroidClientOptionsProvider.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/AsyncScalaClientOptionsProvider.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/DartClientOptionsProvider.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/JavaOptionsProvider.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/NodeJSServerOptionsProvider.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/PhpClientOptionsProvider.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/Qt5CPPOptionsProvider.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/RubyClientOptionsProvider.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/ScalaClientOptionsProvider.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/ScalatraServerOptionsProvider.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/SilexServerOptionsProvider.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/StaticDocOptionsProvider.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/StaticHtmlOptionsProvider.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/SwaggerOptionsProvider.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/SwaggerYamlOptionsProvider.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/SwiftOptionsProvider.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/TizenClientOptionsProvider.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/TypeScriptAngularClientOptionsProvider.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/TypeScriptNodeClientOptionsProvider.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/api/PetApi.java
Make parameters unique in generated code through a config option, "ensureUniqueParams", which is true by default and can be set to false to turn it off.
See #1422
=> Make parameters unique in generated code

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/resources/ruby/api.mustache, modules/swagger-codegen/src/main/resources/ruby/api_client.mustache, samples/client/petstore/ruby/lib/petstore.rb, samples/client/petstore/ruby/lib/petstore/api/pet_api.rb, samples/client/petstore/ruby/lib/petstore/api_client.rb, samples/client/petstore/ruby/spec/api_client_spec.rb
Support collectionFormat for header, query and form parameters in Ruby client.
Unit testing looks good:
```
.................................
Finished in 38.4 seconds (files took 0.38255 seconds to load)
33 examples, 0 failures
```
=> [Ruby] Support collectionFormat for header, query and form parameters

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JaxRSServerCodegen.java, modules/swagger-codegen/src/main/resources/JavaJaxRS/api.mustache, samples/server/petstore/jaxrs/src/gen/java/io/swagger/api/ApiException.java, samples/server/petstore/jaxrs/src/gen/java/io/swagger/api/ApiOriginFilter.java, samples/server/petstore/jaxrs/src/gen/java/io/swagger/api/ApiResponseMessage.java, samples/server/petstore/jaxrs/src/gen/java/io/swagger/api/NotFoundException.java, samples/server/petstore/jaxrs/src/gen/java/io/swagger/api/PetApi.java, samples/server/petstore/jaxrs/src/gen/java/io/swagger/api/PetApiService.java, samples/server/petstore/jaxrs/src/gen/java/io/swagger/api/StoreApi.java, samples/server/petstore/jaxrs/src/gen/java/io/swagger/api/StoreApiService.java, samples/server/petstore/jaxrs/src/gen/java/io/swagger/api/UserApi.java, samples/server/petstore/jaxrs/src/gen/java/io/swagger/api/UserApiService.java, samples/server/petstore/jaxrs/src/gen/java/io/swagger/model/Category.java, samples/server/petstore/jaxrs/src/gen/java/io/swagger/model/Order.java, samples/server/petstore/jaxrs/src/gen/java/io/swagger/model/Pet.java, samples/server/petstore/jaxrs/src/gen/java/io/swagger/model/Tag.java, samples/server/petstore/jaxrs/src/gen/java/io/swagger/model/User.java, samples/server/petstore/jaxrs/src/main/java/io/swagger/api/factories/PetApiServiceFactory.java, samples/server/petstore/jaxrs/src/main/java/io/swagger/api/factories/StoreApiServiceFactory.java, samples/server/petstore/jaxrs/src/main/java/io/swagger/api/factories/UserApiServiceFactory.java, samples/server/petstore/jaxrs/src/main/java/io/swagger/api/impl/PetApiServiceImpl.java, samples/server/petstore/jaxrs/src/main/java/io/swagger/api/impl/StoreApiServiceImpl.java, samples/server/petstore/jaxrs/src/main/java/io/swagger/api/impl/UserApiServiceImpl.java
fixes #1518
This moves the tags and puts them in extensions.  Only the first tag is used for naming the file:
```json
{
"x-tags" : [ {
"hasMore" : "true",
"tag" : "fun"
}, {
"tag" : "stuff"
} ]
}
```
=> remove duplicate tags, replace with extensions in templates

modules/swagger-codegen/src/main/resources/TypeScript-Angular/model.mustache, samples/client/petstore/typescript-angular/API/Client/Category.ts, samples/client/petstore/typescript-angular/API/Client/Order.ts, samples/client/petstore/typescript-angular/API/Client/Pet.ts, samples/client/petstore/typescript-angular/API/Client/Tag.ts, samples/client/petstore/typescript-angular/API/Client/User.ts
The optional properties in the model should have a `?`. This PR fixes just that.
=> [TypeScript] mark optional model properties

modules/swagger-codegen/src/main/resources/swift/Models.mustache, samples/client/petstore/swift/Cartfile, samples/client/petstore/swift/PetstoreClient.podspec, samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/APIs.swift, samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift, samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift, samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift, samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/AlamofireImplementations.swift, samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/Models.swift, samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/Models/Category.swift, samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/Models/Order.swift, samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/Models/Pet.swift, samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/Models/Tag.swift, samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/Models/User.swift
I'm not really familiar with swift, but was using swagger to specify the API I'm working on and found it useful to generate client code based on the API specification. It seems to me that the current state of the generated swift code can't handle an array of objects at the root of the response. This patch fixes the issue, feel free to improve it.
=> The swift code generator can't handle endpoints that return an array of objects

modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/pom.mustache, samples/client/petstore/java/jersey2/pom.xml, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/ApiClient.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/ApiException.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/Configuration.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/JSON.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/Pair.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/StringUtil.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/TypeRef.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/api/PetApi.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/api/StoreApi.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/api/UserApi.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/auth/ApiKeyAuth.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/auth/Authentication.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/auth/HttpBasicAuth.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/auth/OAuth.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/model/Category.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/model/Order.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/model/Pet.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/model/Tag.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/model/User.java
Addresses temp file creation cleanup in jersey-media-multipart (fixed in Jersey 2.12) for generated Swagger clients https://github.com/swagger-api/swagger-codegen/issues/1576
=> [Java jersey2] Update Jersey to 2.12 for generated clients

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ClojureClientCodegen.java, modules/swagger-codegen/src/main/resources/clojure/api.mustache, modules/swagger-codegen/src/main/resources/clojure/project.mustache, pom.xml, samples/client/petstore/clojure/.gitignore, samples/client/petstore/clojure/pom.xml
Improvements to Clojure client codegen (see #1585):
* Include the petstore clojure client into integration tests
* Add support of config options to Clojure client
Below is all config options supported in Clojure client for now:
```
$ java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar config-help -l clojure
CONFIG OPTIONS
sortParamsByRequiredFlag
Sort method arguments to place required parameters before optional parameters. (Default: true)
ensureUniqueParams
Whether to ensure parameter names are unique in an operation (rename parameters that are not). Default: true
projectName
name of the project (Default: generated from info.title or "swagger-clj-client")
projectDescription
description of the project (Default: using info.description or "Client library of <projectNname>") …
```
=> [Clojure] Integration tests and config options

modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache, samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/ApiClient.java
Detect the current environment (Android SDK version and Java version) and determine a default datetime format accordingly.
See #1573
The integration test of the petstore sample is passing:
```
Results :
Tests run: 38, Failures: 0, Errors: 0, Skipped: 0
```
=> [Java okhttp-gson] Fix datetime format for Android

modules/swagger-codegen/src/main/resources/php/configuration.mustache, samples/client/petstore/php/SwaggerClient-php/lib/Configuration.php, samples/client/petstore/php/SwaggerClient-php/tests/PetApiTest.php
- Fixed minor bug in PHP access token (for oauth) setter.
- Added a test case to cover the bug moving forward.
```
.............
Time: 26.3 seconds, Memory: 7.00Mb
OK (13 tests, 533 assertions)
```
=> [PHP] fix access token setter

modules/swagger-codegen/src/main/java/io/swagger/codegen/InlineModelResolver.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/CodegenTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/InlineModelResolverTest.java
This PR fixes the issue of treating non-model body parameter as inline model, for example:
```json
{
"name": "InputBinaryData",
"in": "body",
"required": true,
"schema": {
"type": "string",
"format": "binary"
}
}
```
=> Do not resolve non-model body parameter as inline model

samples/client/petstore/objc/SwaggerClientTests/SwaggerClient.xcodeproj/project.pbxproj, samples/client/petstore/objc/SwaggerClientTests/Tests/PetApiTest.m
Error message below for tracking:
```
Test Case '-[PetApiTest testDeletePet]' started.
Test Case '-[PetApiTest testDeletePet]' passed (1.049 seconds).
Test Case '-[PetApiTest testGetPetByStatus]' started.
2015-11-30 11:21:39.705 xctest[20705:631010] [JSONModel.m:253] Incoming data was invalid [SWGPet initWithDictionary:]. Keys missing: {(
name
)}
2015-11-30 11:21:39.707 xctest[20705:631010] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'
*** First throw call stack:
(
0   CoreFoundation                      0x000000010f34bc65 __exceptionPreprocess + 165
1   libobjc.A.dylib                     0x000000010efe4bb7 objc_exception_throw + 45
2   CoreFoundation …
```
=> [ObjC] skip findPetByStatus test case for objc due to invalid data

modules/swagger-codegen/src/main/resources/clojure/api.mustache, modules/swagger-codegen/src/main/resources/clojure/core.mustache, samples/client/petstore/clojure/src/swagger_petstore/api/pet.clj, samples/client/petstore/clojure/src/swagger_petstore/api/store.clj, samples/client/petstore/clojure/src/swagger_petstore/api/user.clj, samples/client/petstore/clojure/src/swagger_petstore/core.clj, samples/client/petstore/clojure/test/swagger_petstore/api/pet_test.clj
Sample code:
```clojure
(let [resp (get-pet-by-id-with-http-info 1)]
(println "Status code:" (:status resp))
(println "Content-Type header:" (get-in resp [:headers :content-type]))
(println "Data: " (:data resp)))
;; The original method (without the `-with-http-info` suffix) works as before
;; which returns the data directly without HTTP response info
(println (get-pet-by-id 1))
```
Closes #1656
=> Support accessing response status code and headers in Clojure client

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java, modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache, modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/ApiResponse.mustache, modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/api.mustache, samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/ApiClient.java, samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/ApiException.java, samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/ApiResponse.java, samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/Configuration.java, samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/Pair.java, samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/StringUtil.java, samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/api/PetApi.java, samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/api/StoreApi.java, samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/api/UserApi.java, samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/auth/ApiKeyAuth.java, samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/auth/Authentication.java, samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/auth/OAuth.java, samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/model/Pet.java, samples/client/petstore/java/okhttp-gson/src/test/java/io/swagger/petstore/test/PetApiTest.java
Added WithHttpInfo API methods to Java okhttp-gson client to allow accessing response status code and headers, and removed the methods of recording last response info from ApiClient.
Sample code:
```java
PetApi api = new PetApi();
ApiResponse<Pet> resp = api.getPetByIdWithHttpInfo(1L);
System.out.println(resp.getStatusCode()); // 200
System.out.println(resp.getHeaders().get("Content-Type").get(0)); // "application/json"
Pet pet = resp.getData();
```
=> Add WithHttpInfo API methods to Java okhttp-gson client

modules/swagger-codegen/src/main/resources/clojure/core.mustache, samples/client/petstore/clojure/src/swagger_petstore/core.clj
Small stylistic improvements detected with `lein check` and `lein eastwood`.
* fix some reflection warnings by specifying the return type of `make-date-format`
* put docstrings/argument lists in the right order for a couple helper functions in core.mustache
=> Clojure client: docstrings tweaks

modules/swagger-codegen/src/main/resources/qt5cpp/helpers-body.mustache, samples/client/petstore/qt5cpp/client/SWGHelpers.cpp, samples/client/petstore/qt5cpp/client/SWGPet.h
The SWGHelpers.cpp file uses non-standard #import statements. This
causes the following error when built using Visual Studio 2013:
SWGHelpers.cpp(4): fatal error C1083: Cannot open type library file:
'c:\qt\qt5.5.1\5.5\msvc2013_64\include\qtcore\qdebug': Error loading
type library/DLL.
=> Replace #import with #include in the Qt5 generator

modules/swagger-codegen/src/main/resources/ruby/api.mustache, modules/swagger-codegen/src/main/resources/ruby/api_client.mustache, samples/client/petstore/ruby/lib/petstore/api/pet_api.rb, samples/client/petstore/ruby/lib/petstore/api/store_api.rb, samples/client/petstore/ruby/lib/petstore/api/user_api.rb, samples/client/petstore/ruby/lib/petstore/api_client.rb, samples/client/petstore/ruby/spec/pet_spec.rb
Added with-http-info API methods to Ruby client to allow accessing response status code and headers, and removed the methods of recording last response info from ApiClient.
Sample code:
```ruby
pet, status_code, headers = @pet_api.get_pet_by_id_with_http_info(1)
puts headers['Content-Type']
```
=> Added with-http-info API methods to Ruby client

samples/client/petstore/qt5cpp/PetStore/PetApiTests.cpp, samples/client/petstore/qt5cpp/PetStore/PetApiTests.h, samples/client/petstore/qt5cpp/PetStore/PetStore.pro.user
- removed getPetbyId test as the endpoint is tested in `createAndGetPetTest()`
- changed internal timeout value from 1000 to 4000 to avoid timing out
Test result looks good:
```
QDEBUG : PetApiTests::updatePetTest() got a request body
QDEBUG : PetApiTests::updatePetTest() got a request body
PASS   : PetApiTests::updatePetTest()
QDEBUG : PetApiTests::updatePetWithFormTest() got a request body
PASS   : PetApiTests::updatePetWithFormTest()
PASS   : PetApiTests::cleanupTestCase()
Totals: 6 passed, 0 failed, 0 skipped, 0 blacklisted
********* Finished testing of PetApiTests *********
```
=> [Qt5] improve Qt5 test cases

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java, modules/swagger-codegen/src/main/resources/php/model.mustache, modules/swagger-codegen/src/test/java/io/swagger/codegen/php/PhpModelTest.java
Add default value to PHP model's properties.
Tested with Petstore (manually added default value to Order's properties).
```
[INFO] --- exec-maven-plugin:1.2.1:exec (bundle-test) @ PhpPetstoreClientTests ---
.............
Time: 7.44 seconds, Memory: 18.00Mb
OK (13 tests, 3113 assertions)
[INFO] Total time: 9.746 s
[INFO] Finished at: 2015-12-08T16:01:10+08:00
```
=> [PHP] add default value to PHP model

modules/swagger-codegen/src/main/resources/Javascript/api.mustache, samples/client/petstore/javascript/src/scripts/rest/api/PetApi.js, samples/client/petstore/javascript/src/scripts/rest/api/StoreApi.js, samples/client/petstore/javascript/src/scripts/rest/api/UserApi.js, samples/client/petstore/javascript/src/scripts/rest/model/Pet.js
When generating Client JS for an operation without parameters, an unnecessary comma is added before the callback parameter:
```
self.logoutUser = function(, callback) {
```
You can see the error directly on the generating UserApi.js:
https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/javascript/src/scripts/rest/api/UserApi.js#L233
My PR add a hasParams check before adding the comma and the PetStore example generating with the fix.
=> [Javascript] Fix syntax issue when generating Javascript client operation without parameters

modules/swagger-codegen/src/main/resources/Java/ApiClient.mustache, modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/ApiClient.mustache, modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache, samples/client/petstore/java/default/src/main/java/io/swagger/client/ApiClient.java, samples/client/petstore/java/default/src/test/java/io/swagger/client/ApiClientTest.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/ApiClient.java, samples/client/petstore/java/jersey2/src/test/java/io/swagger/client/ApiClientTest.java, samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/ApiClient.java, samples/client/petstore/java/okhttp-gson/src/test/java/io/swagger/client/ApiClientTest.java
Improve the checking of JSON MIME in Java clients to support suffix like charset in `application/json; charset=UTF8`.
The Petstore sample is updated and [the integration test is OK](https://travis-ci.org/xhh/swagger-codegen/builds/95753065).
=> [Java] Improve the checking of JSON MIME

modules/swagger-codegen/src/main/resources/ruby/api.mustache, modules/swagger-codegen/src/main/resources/ruby/api_client.mustache, modules/swagger-codegen/src/main/resources/ruby/configuration.mustache, modules/swagger-codegen/src/main/resources/ruby/gem.mustache, samples/client/petstore/ruby/lib/petstore.rb, samples/client/petstore/ruby/lib/petstore/api/pet_api.rb, samples/client/petstore/ruby/lib/petstore/api/store_api.rb, samples/client/petstore/ruby/lib/petstore/api/user_api.rb, samples/client/petstore/ruby/lib/petstore/api_client.rb, samples/client/petstore/ruby/lib/petstore/configuration.rb, samples/client/petstore/ruby/spec/api_client_spec.rb, samples/client/petstore/ruby/spec/configuration_spec.rb, samples/client/petstore/ruby/spec/spec_helper.rb
Removed the singleton design from the Configuration class.
Added a `config` field to ApiClient to hold the settings the ApiClient uses.
=> Ruby client: allow setting Configuration in ApiClient

modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache
If the list is empty you get the ```ArgumentOutOfRangeException``` when calling ```flattenString.Remove(flattenString.Length - 1)``` because it tries to remove a separator from the empty string.
Also using a ```StringBuilder``` is the prefered way to concatenate strings in a loop.
=> [C#] Fixed ArgumentOutOfRangeException. Optimized string concatenation.

modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache, modules/swagger-codegen/src/test/resources/2_0/petstore.json, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Api/PetApi.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Api/StoreApi.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Api/UserApi.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Client/ApiClient.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Client/Configuration.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/Category.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/Order.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/Pet.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/Tag.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/User.cs
Having a service which returns a FileStream:
@ApiOperation(value = "file", response = java.io.File.class)
the generated ApiClient.cs includes handling FileStreams:
var regex = new Regex(@"Content-Disposition:.*filename=['""]?([^'""\s]+)['""]?$");
but should be Content-Diosposition=...
Additionally the regex is applied onto: headers.ToString()
which has the value: "System.Collections.Generic.List`1[RestSharp.Parameter]"
Therefor, a filename will never be correctly parsed.
=> [C#] fix filename and Content-Disposition parsing on FileStream

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/ApiClient.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/ApiException.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/Configuration.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/Pair.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/StringUtil.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/api/PetApi.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/api/StoreApi.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/api/UserApi.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/ApiKeyAuth.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/Authentication.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/HttpBasicAuth.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/OAuth.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Category.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Order.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Pet.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Tag.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/model/User.java
The default `needToImport` was accidentally updated with `type.indexOf(".") < 0` in the following commit:
https://github.com/swagger-api/swagger-codegen/commit/edf2642e739f75debcc40bf454c8ee9513215f80
The correct approach is to override `needToImport` in language specified generator.
=> Fix default needToImport

.gitignore
`*/.settings` applies to just the directory below the current one, where there is no such file.
`.settings` applies to all files/directories named such in the whole project.
=> Fix #1743 by removing `*/` from the .settings ignore line.

modules/swagger-codegen/src/main/resources/swift/Extensions.mustache, modules/swagger-codegen/src/main/resources/swift/Podspec.mustache, modules/swagger-codegen/src/test/resources/2_0/petstore.json, samples/client/petstore/swift/PetstoreClient.podspec, samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift, samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift, samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift, samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/Extensions.swift
To fix https://github.com/swagger-api/swagger-codegen/issues/1638, https://github.com/swagger-api/swagger-codegen/issues/1636
This PR also removes the `downloadImage` endpoint from petstore.json (that endpoint does not exist)
=> [Swift] update promisekit and alamofire to the latest version

modules/swagger-codegen/src/main/resources/php/api.mustache, samples/client/petstore/php/SwaggerClient-php/lib/Api/PetApi.php, samples/client/petstore/php/SwaggerClient-php/lib/ObjectSerializer.php
Wildcard response codes was handled like all other response codes resulting in a misleading construction like this:
```php
switch ($e->getCode()) {
case 0:
$data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Error', $e->getResponseHeaders());
$e->setResponseObject($data);
break;
}
```
This commit fixes it to use the default fallback of the PHP switch statement:
```php
switch ($e->getCode()) {
default:
$data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Error', $e->getResponseHeaders());
$e->setResponseObject($data);
break;
}
```
The Petstore sample has been regenerated as well although this change doesn't change it (there some other changes that hadn't been regenerated).
The test cases runs …
=> Handle wildcard response codes correct in PHP

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenModel.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenProperty.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
@fehguy added support for this in parameters; This adds vendorExtensions support for models and properties (per request from @ovidiom)
Swagger YAML
```yaml
User:
properties:
accountName:
type: "string"
example: "JohnDoe"
description: "User's account name."
x-authored-json-sample: Wow we have vendor extension on a model!
```
Template (in swagger-codegen)
```mustache
Value for x-authored-json-sample: {{vendorExtensions.x-authored-json-sample}}
```
Result
```
Value for x-authored-json-sample: Wow we have vendor extension on a model!
```
=> Outstanding fix for #1173: Added support for vendor extensions on model and property

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
Per issue recommendation, fix is to DefaultCodegen#fromSecurity, which
now returns an empty list rather than null if no securityDefinitions
property is present in the swagger spec
=> [Akka-Scala] Fix #1781 re specs w/o security defs

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConfig.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConstants.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java, modules/swagger-codegen/src/main/resources/Java/enumClass.mustache, modules/swagger-codegen/src/main/resources/Java/pojo.mustache, modules/swagger-codegen/src/test/java/io/swagger/codegen/inflector/JavaInflectorServerOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/JavaOptionsProvider.java
This commit adds an option to java clients to serialize BigDecimal values as strings.  It also gives the option to post-process models, for injecting other vendor extensions, imports, etc.
=> added BigDecimal java serialization options

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenModel.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java, modules/swagger-codegen/src/main/resources/Java/model.mustache, modules/swagger-codegen/src/test/java/io/swagger/codegen/java/JavaModelEnumTest.java
Using the new `postProcessModelProperty` operation, imports can be added intelligently.  This PR updates the java client with better imports and mappings.
Fixes #1764
=> made imports more intelligent

modules/swagger-generator/src/main/java/io/swagger/generator/Bootstrap.java, modules/swagger-generator/src/main/java/io/swagger/generator/exception/ApiException.java, modules/swagger-generator/src/main/java/io/swagger/generator/exception/BadRequestException.java, modules/swagger-generator/src/main/java/io/swagger/generator/exception/NotFoundException.java, modules/swagger-generator/src/main/java/io/swagger/generator/util/ValidationException.java
This pull request is focused on resolving occurrences of sonar issue squid:S2057 - Serializable classes should have a version id
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S2057
Please let me know if you have any questions.
Kirill Vlasov
=> Fixing squid:S2057 - Serializable classes should have a version id

modules/swagger-codegen/src/main/java/io/swagger/codegen/config/CodegenConfigurator.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/examples/ExampleGenerator.java, samples/client/wordnik/android-java/src/main/java/io/swagger/client/ApiInvoker.java, samples/client/wordnik/java/src/main/java/io/swagger/client/ApiInvoker.java, samples/server/petstore/spring-mvc/src/main/java/io/swagger/configuration/SwaggerConfig.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1488 - Local Variables should not be declared and then immediately returned or thrown
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1488 - Local Variables should not be declared and then immediately returned or thrown
Please let me know if you have any questions.
Kirill Vlasov
=> Local Variables should not be declared and then immediately returned or thrown

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java, modules/swagger-codegen/src/main/resources/csharp/AssemblyInfo.mustache
Changes for issue #1797 
* New mustache template created for AssemblyInfo.cs
* Properties added to the C# codegen file to specify the assembly property values and adding AssemblyInfo.mustache to list of supporting files
=> Issue 1797 - Adding assembly info

modules/swagger-codegen/src/main/resources/python/api_client.mustache
in Python, a method used as the default value of a formal parameter defines the value when the function is defined (normally at `import` time), not when the method is invoked
So if someone tried 
````
Configuration().host = mySpecialHost
api = MySpecialApi()
````
it would not work because the Configuration().host in api_client was invoked when the module was loaded, not when the constructor is run.
Note: I tested this by editing the generated python code, not the .mustache file
=> Fixed configuration of host in api_client so that it gets done at run-time not load-time

modules/swagger-codegen/src/main/resources/php/ObjectSerializer.mustache, modules/swagger-codegen/src/main/resources/php/api.mustache, samples/client/petstore/php/SwaggerClient-php/lib/Api/PetApi.php, samples/client/petstore/php/SwaggerClient-php/lib/Api/StoreApi.php, samples/client/petstore/php/SwaggerClient-php/lib/Api/UserApi.php, samples/client/petstore/php/SwaggerClient-php/lib/Configuration.php, samples/client/petstore/php/SwaggerClient-php/lib/ObjectSerializer.php
This patch makes it possible to use arrays as arguments for parameters defined as arrays of strings -- and respects the `collectionFormat`.
Until now you had to implode the string to an array yourself before calling the API.
I've been thinking about also adding type hints to array for those parameters in method argument list. But since that would break backwards compatibility it should probably be hidden behind a command line option or something.
NB: This needs swagger-parser 1.0.12.
=> Accept arrays as arguments to collection parameters in PHP client.

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenModel.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/java/JavaModelEnumTest.java, modules/swagger-generator/Dockerfile
Fixes #1819, #1820 (java only)
=> adds a parentSchema name, escapes reserved words in java client

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/DefaultGeneratorTest.java, modules/swagger-codegen/src/test/resources/2_0/duplicateOperationIds.yaml
If an operation ID is generated or specified, AND it is duplicated in the same operation group, there could be a build error.  The codegen will now suffix the operation_id with _%d to ensure it's unique
Fixes #1822
=> Added duplicate operation ID generation

.travis.yml, README.md, modules/swagger-codegen/src/main/resources/perl/README.mustache, modules/swagger-codegen/src/main/resources/perl/Role.mustache
According to #205 it should be fine to build swagger-codegen with Java 8.
The documentation still mentions Java 7 as the only working Java version (http://swagger.io/swagger-codegen/ also mentions Java 7).
=> Document Java 8 as requirement.

modules/swagger-codegen/src/main/resources/ruby/gemspec.mustache, samples/client/petstore/ruby/Gemfile.lock, samples/client/petstore/ruby/petstore.gemspec
This PR addresses running the Ruby integration tests on El Capitan
One of the development dependencies of the generated Ruby client is [autotest-fsevent](https://github.com/svoop/autotest-fsevent/). It's used to detect file system changes and re-run the tests automatically. Building the clients works fine, but when attempting to run the integration tests for Ruby with the latest OS X (El Capitan) it errors out with this message:
```
Installing autotest-fsevent 0.2.10 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
current directory: /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/autotest-fsevent-0.2.10/ext/fsevent
/usr/local/var/rbenv/versions/2.3.0/bin/ruby -r ./siteconf20160107-72766-a9grd3.rb extconf.rb
extconf.rb:24:in `<main>': …
```
=> Minimal update for Ruby testing on El Capitan

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConstants.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/csharp/CSharpClientOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/CSharpClientOptionsProvider.java, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/Properties/AssemblyInfo.cs, samples/client/petstore/csharp/SwaggerClientTest/SwaggerClientTest.userprefs
When including the entire folder into a C# project, AssemblyInfo.cs conflicts with the existing one in the project so making it optional as it's only required when building the dll. Default is to generate AssemblyInfo.cs.
=> [C#] add cli option to optionally generate Assemblyinfo.cs

modules/swagger-codegen/src/main/resources/Java/pojo.mustache
This fixes equals/hashCode for derived classes.
Example of the generated equals/hashCode on a POJO that extends another class:
```java
@Override
public boolean equals(java.lang.Object o) {
if (this == o) {
return true;
}
if (o == null || getClass() != o.getClass()) {
return false;
}
Account account = (Account) o;
return true && Objects.equals(website, account.website) &&
Objects.equals(createdOn, account.createdOn) &&
Objects.equals(links, account.links) &&
Objects.equals(displayName, account.displayName) &&
Objects.equals(uuid, account.uuid) &&
Objects.equals(username, account.username)
&& super.equals(o);
}
@Override
public int hashCode() {
return Objects.hash(website, createdOn, links, displayName, uuid, username, super.hashCode());
}
```
And one that does not have a parent:
```java …
```
=> #1858: The Java equals/hashcode methods ignores state from superclasses

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConstants.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java, modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache, modules/swagger-codegen/src/test/java/io/swagger/codegen/csharp/CSharpClientOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/CSharpClientOptionsProvider.java, samples/client/petstore/csharp/SwaggerClientTest/TestApiClient.cs
CSharp: Add support for csharp client to use DateTimeOffset instead of DateTime in models to preserve timezone information. Also adds support for sourceFolder configuration parameter.
=> CSharp client: Add support for DateTimeOffset and sourceFolder configuration.

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java, modules/swagger-codegen/src/main/resources/CsharpDotNet2/ApiClient.mustache, modules/swagger-codegen/src/main/resources/CsharpDotNet2/ApiException.mustache, modules/swagger-codegen/src/main/resources/CsharpDotNet2/api.mustache, modules/swagger-codegen/src/main/resources/CsharpDotNet2/compile-mono.sh.mustache, modules/swagger-codegen/src/main/resources/csharp/ApiResponse.mustache, modules/swagger-codegen/src/main/resources/csharp/Configuration.mustache, modules/swagger-codegen/src/main/resources/csharp/compile-mono.sh.mustache, modules/swagger-codegen/src/main/resources/csharp/model.mustache, modules/swagger-codegen/src/main/resources/csharp/packages.config.mustache, samples/client/petstore/csharp-dotnet2/SwaggerClientTest/Lib/SwaggerClient/compile-mono.sh, samples/client/petstore/csharp-dotnet2/SwaggerClientTest/Lib/SwaggerClient/src/main/CsharpDotNet2/IO/Swagger/Api/PetApi.cs, samples/client/petstore/csharp-dotnet2/SwaggerClientTest/Lib/SwaggerClient/src/main/CsharpDotNet2/IO/Swagger/Api/StoreApi.cs, samples/client/petstore/csharp-dotnet2/SwaggerClientTest/Lib/SwaggerClient/src/main/CsharpDotNet2/IO/Swagger/Api/UserApi.cs, samples/client/petstore/csharp-dotnet2/SwaggerClientTest/Lib/SwaggerClient/src/main/CsharpDotNet2/IO/Swagger/Client/ApiClient.cs, samples/client/petstore/csharp-dotnet2/SwaggerClientTest/Lib/SwaggerClient/src/main/CsharpDotNet2/IO/Swagger/Client/ApiException.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Client/ApiClient.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Client/ApiResponse.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Client/Configuration.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/Category.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/Order.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/Pet.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/Tag.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/User.cs
- fixed comments to avoid warning when building dll (C#, C# .net 2.0)
- added compile-mono.sh (copied from C# .net 2.0)
=> [C#] Fix comments and add compile-mono.sh

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/NodeJSServerCodegen.java
This last change was producing a wrong swagger spec
@see https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md
"The value MUST start with a leading slash (/)"
=> Fixed bug: basePath should not be empty

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/NodeJSServerCodegen.java
Inspired by ClojureClientCodegen.java, it is interesting to use projectName from info.title swagger spec to fill up package.json name attribute
=> projectName support to fill package.json template

modules/swagger-codegen/src/main/resources/Java/pojo.mustache
A swagger file that contains a definition named "object" compiles into a
class named Object. This is technically not a problem as it lives in a
different package than java.lang.Object, but this requires the templates to
refer to Java's Object using its fully qualified name.
=> Java Class Name Clashes with java.lang.*

modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache, modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/pom.mustache, samples/client/petstore/java/okhttp-gson/pom.xml, samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/ApiClient.java, samples/client/petstore/java/okhttp-gson/src/test/java/io/swagger/client/ApiClientTest.java
Support `debugging` for ApiClient by utilizing the `HttpLoggingInterceptor` class introduced in [OkHttp 2.6.0](https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-260), and upgrade OkHttp to the latest version in the meantime.
=> [Java okhttp-gson] Implement the "debugging" option of ApiClient

modules/swagger-codegen/src/main/resources/Java/libraries/feign/api.mustache
Query params get generated as
```java
@RequestLine("GET /myendpoint?myId={myId}")
```
instead of
```java
@RequestLine("GET /myendpoint?my_id={myId}")
```
when the query param name is "my_id"
=> [Feign]Fix wrong query param key name in feign client

README.md
Currently points to `#validating-your-swagger-spec` which leads the reader nowhere...
=> README.md: Validating your OpenAPI Spec should point to #validating-your-openapi-spec

modules/swagger-codegen/src/main/resources/TypeScript-Angular/model.mustache, modules/swagger-codegen/src/main/resources/TypeScript-node/api.mustache, samples/client/petstore/typescript-angular/API/Client/Order.ts, samples/client/petstore/typescript-angular/API/Client/Pet.ts, samples/client/petstore/typescript-node/api.ts
This change skips the trailing comma for enums in angular TypeScript models.
=> skip trailing comma for enums in TypeScript angular

modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache, modules/swagger-codegen/src/main/resources/ruby/api_client.mustache, samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/ApiClient.java, samples/client/petstore/java/okhttp-gson/src/test/java/io/swagger/client/ApiClientTest.java, samples/client/petstore/ruby/lib/petstore/api_client.rb, samples/client/petstore/ruby/petstore.gemspec, samples/client/petstore/ruby/spec/api_client_spec.rb
- Java okhttp-gson: sanitize the filename got from response header by removing path delimiters from downloading filename
- Ruby: IO improvements on file downloading
- Use `File.basename` to sanitize the filename got from response header
- Write to the `Tempfile` directly and return it to use less IO
- Set file encoding according to the response body's encoding
See #1848
=> File downloading improvements for Ruby and Java

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenParameter.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java, modules/swagger-codegen/src/main/resources/php/ApiClient.mustache, modules/swagger-codegen/src/main/resources/php/ObjectSerializer.mustache, modules/swagger-codegen/src/main/resources/php/api.mustache, samples/client/petstore/csharp/SwaggerClientTest/SwaggerClientTest.userprefs, samples/client/petstore/csharp/SwaggerClientTest/obj/Debug/SwaggerClientTest.csproj.FilesWrittenAbsolute.txt, samples/client/petstore/php/SwaggerClient-php/lib/Api/PetApi.php, samples/client/petstore/php/SwaggerClient-php/lib/ApiClient.php, samples/client/petstore/php/SwaggerClient-php/lib/ObjectSerializer.php, samples/client/petstore/php/SwaggerClient-php/tests/PetApiTest.php
- similar to https://github.com/swagger-api/swagger-codegen/pull/1864
- added test cases
....................
Time: 14.33 seconds, Memory: 18.00Mb
OK (20 tests, 3074 assertions)
=> [PHP] addd binary support to response and body parameter

modules/swagger-codegen/src/main/resources/php/ApiClient.mustache, modules/swagger-codegen/src/main/resources/php/ObjectSerializer.mustache, modules/swagger-codegen/src/main/resources/php/api.mustache, modules/swagger-codegen/src/main/resources/php/model.mustache, samples/client/petstore/php/SwaggerClient-php/lib/Api/PetApi.php, samples/client/petstore/php/SwaggerClient-php/lib/Api/StoreApi.php, samples/client/petstore/php/SwaggerClient-php/lib/Api/UserApi.php, samples/client/petstore/php/SwaggerClient-php/lib/ApiClient.php, samples/client/petstore/php/SwaggerClient-php/lib/Model/Category.php, samples/client/petstore/php/SwaggerClient-php/lib/Model/Order.php, samples/client/petstore/php/SwaggerClient-php/lib/Model/Pet.php, samples/client/petstore/php/SwaggerClient-php/lib/Model/Tag.php, samples/client/petstore/php/SwaggerClient-php/lib/Model/User.php, samples/client/petstore/php/SwaggerClient-php/lib/ObjectSerializer.php, samples/client/petstore/php/SwaggerClient-php/tests/OrderApiTest.php, samples/client/petstore/php/SwaggerClient-php/tests/PetApiTest.php
To fix #1914 
```
{
"id": 10005,
"category": {
"id": 10005,
"name": "test php category"
},
"name": "PHP Unit Test",
"tags": [
{
"id": 10005,
"name": "test php tag"
}
]
}
```
=> [PHP] fix __toString for nested models

modules/swagger-codegen/src/main/resources/android/libraries/volley/api.mustache, modules/swagger-codegen/src/main/resources/android/libraries/volley/apiInvoker.mustache, modules/swagger-codegen/src/main/resources/android/libraries/volley/auth/apikeyauth.mustache, modules/swagger-codegen/src/main/resources/android/libraries/volley/auth/oauth.mustache, modules/swagger-codegen/src/main/resources/android/libraries/volley/build.mustache, samples/client/petstore/android/volley/src/test/java/io/swagger/petstore/test/PetApiTest.java
Hi! I have added some enhancements to android-volley-library generator. I want to add tests requested  in #1839 but I have some questions so I am gonna make a to do list:
I will explain one by one:
The most common usage of Volley is making asynchronous requests with callbacks as there were already in the volley generator, something like:
```java
api.getPetById(pet.getId(), 
new Response.Listener<Pet>() {
@Override
public void onResponse(Pet response) {
fetched[0] = response;
waiter.resume();
}
}, new Response.ErrorListener() {
@Override
public void onErrorResponse(VolleyError error) {
}
});
```
But there are cases, like in services for instance, where you want to call that request synchronously. I've added this functionality so one can call both the way above or like android-default was: …
=> Android volley library enhancement and tests

README.md
Fixes #1955 
Whitespace changes are just "remove trailing whitespace" (my VIM does it automatically, I think it's good practice..)
=> #1955 fix command in README: flaskConnexion -> python-flask

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
A property defined as "type: string & format: uuid" is now generated in
Java using "java.util.UUID" class instead of a classical String. In the
Java, the UUID class do not provide a constructor. You may use the
method UUID.fromString(<uuid_string>) to construct your UUID object.
=> Support java code generation for UUIDProperty

modules/swagger-codegen/src/main/resources/TypeScript-Angular/model.mustache, modules/swagger-codegen/src/main/resources/TypeScript-node/api.mustache, samples/client/petstore/typescript-angular/API/Client/Category.ts, samples/client/petstore/typescript-angular/API/Client/Order.ts, samples/client/petstore/typescript-angular/API/Client/Pet.ts, samples/client/petstore/typescript-angular/API/Client/PetApi.ts, samples/client/petstore/typescript-angular/API/Client/Tag.ts, samples/client/petstore/typescript-angular/API/Client/User.ts, samples/client/petstore/typescript-angular/README.md, samples/client/petstore/typescript-node/README.md, samples/client/petstore/typescript-node/api.ts
As mentioned in http://typescript.codeplex.com/workitem/1073, model property with dash or other special characters should be double-quoted.
Updated TS (angular & node) petstore sample and test result looks good.
=> [TypeScript] double quote model property name

modules/swagger-codegen/src/main/resources/Javascript/package.mustache, samples/client/petstore/javascript/package.json, samples/client/petstore/javascript/test/run_tests.html
Lock version of superagent t 1.7.1 to avoid an unexpected behavior on request.header in 1.7.2: Node version's request.header uses lower-case keys while browser version's request.header keeps current case.
See also visionmedia/superagent#873
=> [JavaScript] Lock version of superagent to fix testing issues

modules/swagger-codegen/src/main/resources/ruby/api_client.mustache, samples/client/petstore/ruby/lib/petstore/api_client.rb
In order to allow openssl to figure out the location of CA certificates
on its own, don't apply the `ssl_ca_cert` configuration parameter if it
is not explicitly set.
=> Don't force explicit configuration of CA cert location

.gitignore, modules/swagger-codegen/src/main/resources/Groovy/build.gradle.mustache, modules/swagger-codegen/src/main/resources/Java/build.gradle.mustache, modules/swagger-codegen/src/main/resources/Java/libraries/feign/build.gradle.mustache, modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/build.gradle.mustache, modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/build.gradle.mustache, modules/swagger-codegen/src/main/resources/Java/libraries/retrofit/build.gradle.mustache, modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/build.gradle.mustache
I added gradle IDE plugins in `build.gradle.mustache`.
I don't commit the sample changes. I think we should add sample directory in `.gitignore`. 
Let users try codegen and generate samples.
=> [Java Client] Add Eclipse and IntelliJ IDEA support in build.gradle.mustache

modules/swagger-codegen/src/main/resources/qt5cpp/api-body.mustache, samples/client/petstore/qt5cpp/client/SWGPet.h, samples/client/petstore/qt5cpp/client/SWGPetApi.cpp, samples/client/petstore/qt5cpp/client/SWGPetApi.h, samples/client/petstore/qt5cpp/client/SWGUserApi.cpp
For #1936 
credit: @realhawker
=> [Qt5 C++] Fix file support in form parameter

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java, modules/swagger-codegen/src/main/resources/csharp/README.md, modules/swagger-codegen/src/main/resources/csharp/api_test.mustache, modules/swagger-codegen/src/main/resources/csharp/model_test.mustache, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient.Test/CategoryTests.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient.Test/OrderTests.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient.Test/PetApiTests.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient.Test/PetTests.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient.Test/StoreApiTests.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient.Test/TagTests.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient.Test/UserApiTests.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient.Test/UserTests.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/README.md, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/Category.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/Order.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/Pet.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/Tag.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/User.cs
Similar to https://github.com/swagger-api/swagger-codegen/pull/1921.
Also update README with more info on building the DLL.
TODO: ideally there should be a cs project file including the test files and is ready to run.
=> [C#] Add unit tests for C# APIs and models

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/HaskellServantCodegen.java, samples/server/petstore/haskell-servant/client/Main.hs, samples/server/petstore/haskell-servant/haskell-servant-codegen.cabal, samples/server/petstore/haskell-servant/lib/Api/PetApi.hs, samples/server/petstore/haskell-servant/lib/Apis.hs
Tested and no longer have issue running `./bin/haskell-servant-petstore.sh`
=> [Haskell] minor fix to template location for haskell-servant

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java, modules/swagger-codegen/src/main/resources/Javascript/ApiClient.mustache, modules/swagger-codegen/src/main/resources/Javascript/api.mustache, modules/swagger-codegen/src/main/resources/Javascript/enumClass.mustache, modules/swagger-codegen/src/main/resources/Javascript/model.mustache, samples/client/petstore/javascript/src/ApiClient.js, samples/client/petstore/javascript/src/api/PetApi.js, samples/client/petstore/javascript/src/api/StoreApi.js, samples/client/petstore/javascript/src/api/UserApi.js, samples/client/petstore/javascript/src/model/Category.js, samples/client/petstore/javascript/src/model/Order.js, samples/client/petstore/javascript/src/model/Pet.js, samples/client/petstore/javascript/src/model/Tag.js, samples/client/petstore/javascript/src/model/User.js, samples/client/petstore/javascript/test/run_tests.html
Improvements and enhancements to the JavaScript client codegen:
* Use brackets to access model properties to support nonstandard characters in property names, e.g. "user-status".
* Ensure a default project/module name when it is an empty string (same for "projectVersion") (#2022)
* Fix `ApiClient.isFileParam` in browserify runtime (#2028)
* Handle response deserialization to support array of models and Date property in model (#1951)
=> [JavaScript]  some improvements and enhancements to JavaScript client

modules/swagger-codegen/src/main/resources/Javascript/ApiClient.mustache, modules/swagger-codegen/src/main/resources/Javascript/api.mustache, samples/client/petstore/javascript/src/ApiClient.js, samples/client/petstore/javascript/src/api/PetApi.js, samples/client/petstore/javascript/test/ApiClientTest.js
=> [JavaScript] Support collectionFormat for parameters in JavaScript client

README.md
Apparently, I missed this command in the readme even after the comment in the original pull request in #2024. Looks like I updated the generated output directory and forgot the command itself.
=> [aspnet] Updated -l aspnet5 in example command

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/NodeJSServerCodegen.java, modules/swagger-codegen/src/main/resources/nodejs/service.mustache
=> added x-swagger-router-controller, operationId for node.js versions

samples/client/petstore/java/default/src/test/java/io/swagger/PetstoreProfiling.java
Test failed locally (java1.7) but works fine in CI.
Resolved local issue using fully qualified name.
=> [Java] fix local Java test issue using fully qualified name

modules/swagger-codegen/src/main/resources/python/model.mustache, samples/client/petstore/python/swagger_client/models/category.py, samples/client/petstore/python/swagger_client/models/order.py, samples/client/petstore/python/swagger_client/models/pet.py, samples/client/petstore/python/swagger_client/models/tag.py, samples/client/petstore/python/swagger_client/models/user.py
Fix #2037 by adding dictionary handling in a model's `to_dict()` method
=> Add model's "additionalProperties" handling in python client

modules/swagger-codegen/src/main/resources/python/model.mustache, samples/client/petstore/python/swagger_client/models/category.py, samples/client/petstore/python/swagger_client/models/order.py, samples/client/petstore/python/swagger_client/models/pet.py, samples/client/petstore/python/swagger_client/models/tag.py, samples/client/petstore/python/swagger_client/models/user.py
This PR is additional work on #2037, and is a fixed version of addition made in #2058.
1. After creating #2058 to comply with python 3.4 found a bug when using on python 2.7, the current method should comply with both.
2. Performance optimization by switching the order of the `elif`, since I guess `additionalProperties` is probably less used and should be checked last
3. Style optimization by warping lines and staying below 79 chars
=> Conitnue fixing of #2037

modules/swagger-codegen/src/main/java/io/swagger/codegen/InlineModelResolver.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java, pom.xml
=> Update parser, inline resolver

modules/swagger-codegen/src/main/resources/ruby/base_object.mustache, samples/client/petstore/ruby/lib/petstore/models/category.rb, samples/client/petstore/ruby/lib/petstore/models/order.rb, samples/client/petstore/ruby/lib/petstore/models/pet.rb, samples/client/petstore/ruby/lib/petstore/models/tag.rb, samples/client/petstore/ruby/lib/petstore/models/user.rb, samples/client/petstore/ruby/spec/base_object_spec.rb
Current code will converts boolean true of json to false
because ruby's boolean is not matched with any regex.
Here is single line patch to convert string explicitly before regex check.
```
sugi@tempest:~% irb
irb(main):001:0> true =~ /true/
nil
irb(main):002:0> "true" =~ /true/
0
irb(main):003:0> 
sugi@tempest:~% ruby1.8 -e 'p true =~ /true/'
false
sugi@tempest:~% ruby1.9.1 -e 'p true =~ /true/' 
nil
sugi@tempest:~% ruby1.9.3 -e 'p true =~ /true/'
nil
sugi@tempest:~% ruby2.0 -e 'p true =~ /true/'
nil
sugi@tempest:~% ruby2.1 -e 'p true =~ /true/' 
nil
sugi@tempest:~% ruby2.2 -e 'p true =~ /true/' 
nil
```
=> ruby: Fix boolean convertion on json to model attribute.

bin/javascript-petstore.sh
The template folder for javascript starts wit a capital letter. Shell script will fail on linux because of java.io.FileNotFoundException for the module.mustache
=> Fixes typo in template folder for javascript in bin-script

bin/javascript-promise-petstore.sh
the folder name for the template starts with a capital letter.
=> Fixes typo template folder for javascript in bin-promise-script

modules/swagger-codegen/src/main/resources/swift/Models.mustache
Hey guys,
I was having some trouble with generating an API for my jersey based java project (dropbox).  All of my dates generated for my responses were in java date format.  I added support for this format as a fallback when parsing dates. if you like it, take it :)
=> adding support for java dates

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java, modules/swagger-codegen/src/main/resources/Javascript/model.mustache
Adds an option to the JS client generator, `omitModelMethods`, which causes it to not generate getters and setters for the model classes.
These methods are often not needed or desired, especially when the returned objects are to be further processed and turned into other structures anyway (e.g. [Immutable.js](https://facebook.github.io/immutable-js/) records).
=> Add option to omit getters/setters on models

modules/swagger-codegen/src/main/resources/Javascript/model.mustache, samples/client/petstore/javascript-promise/src/model/Category.js, samples/client/petstore/javascript-promise/src/model/Order.js, samples/client/petstore/javascript-promise/src/model/Pet.js, samples/client/petstore/javascript-promise/src/model/Tag.js, samples/client/petstore/javascript-promise/src/model/User.js, samples/client/petstore/javascript/src/model/Category.js, samples/client/petstore/javascript/src/model/Order.js, samples/client/petstore/javascript/src/model/Pet.js, samples/client/petstore/javascript/src/model/Tag.js, samples/client/petstore/javascript/src/model/User.js
Fixes #2103 
In the `constructFromObject` methods, we were always setting all the
parameters, including optional ones that were missing in the `data`
object. Because of the `convertToType` calls, this had the effect
of producing the *strings* `"undefined"` or `"null"` as property
values on the constructed object! This obviously leads to difficult
bugs.
This commit makes sure that we first check that the data field
exists in the data object. Note that both `null` and `undefined`
values will be skipped.
=> Fix handling of missing optional params

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwiftCodegen.java
Fixes https://github.com/swagger-api/swagger-codegen/issues/2095
`SwaggerCodegen` was not overriding `toOperationId(String operationId)` which resulted in missing sanitization for operationId.  This PR adds `toOperationId()` from `ObjcClientCodegen`, which also includes check against reserved keyword usage.
@wing328 could you please review the change?
=> [Swift] Fix #2095, missing sanitization for operationId

modules/swagger-codegen/src/main/resources/Java/ApiClient.mustache, samples/client/petstore/java/default/src/main/java/io/swagger/client/ApiClient.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/ApiException.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/Configuration.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/Pair.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/StringUtil.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/api/PetApi.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/api/StoreApi.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/api/UserApi.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/ApiKeyAuth.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/HttpBasicAuth.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/OAuth.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Category.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Order.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Pet.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Tag.java, samples/client/petstore/java/default/src/main/java/io/swagger/client/model/User.java
This "fixes" https://github.com/swagger-api/swagger-codegen/issues/1924 .
The solution was to add the `X-HTTP-Method-Override` to the `POST` call. Using this change, swagger-codegen clients will actually make PATCH requests with POST as the verb, but with a header of `X-HTTP-Method-Override` set to PATCH. It is then the responsibility of the server to recognize the header and swap out the HTTP verb accordingly in a request filtering mechanisgm such as a `com.sun.jersey.spi.container.ContainerRequestFilter`.
Currently, this workaround, and corresponding handling on the server side, is the only way to reliably perform PATCH using Jersey 1.x.
See: http://theza.ch/2009/06/17/override-the-http-request-method-in-jersey/
Note: I have a lot of changes in this diff spit out by the generator; I …
=> Adding PATCH header override the default Java client

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java, modules/swagger-codegen/src/main/resources/Javascript/ApiClient.mustache, modules/swagger-codegen/src/main/resources/Javascript/model.mustache, samples/client/petstore/javascript-promise/src/ApiClient.js, samples/client/petstore/javascript-promise/src/model/Category.js, samples/client/petstore/javascript-promise/src/model/Order.js, samples/client/petstore/javascript-promise/src/model/Pet.js, samples/client/petstore/javascript-promise/src/model/Tag.js, samples/client/petstore/javascript-promise/src/model/User.js, samples/client/petstore/javascript/src/ApiClient.js, samples/client/petstore/javascript/src/model/Category.js, samples/client/petstore/javascript/src/model/Order.js, samples/client/petstore/javascript/src/model/Pet.js, samples/client/petstore/javascript/src/model/Tag.js, samples/client/petstore/javascript/src/model/User.js
Fixes #2113 
The `constructFromObject` factory methods should be class methods
(or "static" methods), not instance methods.
With this commit, ApiClient no longer calls the model constructors
directly. Instead, it calls the new static factory method to get the
new instance. If there is no data on the top level, null is returned.
It is still possible for users to call the model constructors
directly, of course.
=> Use static model factory methods

modules/swagger-codegen/src/main/resources/Javascript/enumClass.mustache, samples/client/petstore/javascript-promise/src/model/Category.js, samples/client/petstore/javascript-promise/src/model/Order.js, samples/client/petstore/javascript-promise/src/model/Pet.js, samples/client/petstore/javascript-promise/src/model/Tag.js, samples/client/petstore/javascript-promise/src/model/User.js, samples/client/petstore/javascript/src/model/Category.js, samples/client/petstore/javascript/src/model/Order.js, samples/client/petstore/javascript/src/model/Pet.js, samples/client/petstore/javascript/src/model/Tag.js, samples/client/petstore/javascript/src/model/User.js
=> Use objects for enums, not constructor functions

modules/swagger-codegen/src/main/resources/Javascript/enumClass.mustache, modules/swagger-codegen/src/main/resources/Javascript/model.mustache, samples/client/petstore/javascript-promise/src/model/Category.js, samples/client/petstore/javascript-promise/src/model/Order.js, samples/client/petstore/javascript-promise/src/model/Pet.js, samples/client/petstore/javascript-promise/src/model/Tag.js, samples/client/petstore/javascript-promise/src/model/User.js, samples/client/petstore/javascript/src/model/Category.js, samples/client/petstore/javascript/src/model/Order.js, samples/client/petstore/javascript/src/model/Pet.js, samples/client/petstore/javascript/src/model/Tag.js, samples/client/petstore/javascript/src/model/User.js
Fixes #2102.
This attaches the enum classes to the main model class. This also ensures that the enum is exported along with the model. There is no longer a need for a separate export of the enum.
The enums now looks similar to a local class in Java, which seems appropriate, since they are indeed local to the model class being defined.
Note: This conflicts with https://github.com/swagger-api/swagger-codegen/pull/2115
Take them in any order, and I'll rebase accordingly. We need both to really fix the enums, but the two PRs address two different issues.
=> Correct exporting of enum classes

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ObjcClientCodegen.java, modules/swagger-codegen/src/main/resources/objc/ApiClient-body.mustache, modules/swagger-codegen/src/main/resources/objc/ApiClient-header.mustache, modules/swagger-codegen/src/main/resources/objc/api-body.mustache, modules/swagger-codegen/src/main/resources/objc/api-header.mustache, samples/client/petstore/objc/SwaggerClient/SWGApiClient.h, samples/client/petstore/objc/SwaggerClient/SWGApiClient.m, samples/client/petstore/objc/SwaggerClient/SWGPetApi.h, samples/client/petstore/objc/SwaggerClient/SWGPetApi.m, samples/client/petstore/objc/SwaggerClient/SWGStoreApi.h, samples/client/petstore/objc/SwaggerClient/SWGStoreApi.m, samples/client/petstore/objc/SwaggerClient/SWGUserApi.h, samples/client/petstore/objc/SwaggerClient/SWGUserApi.m, samples/client/petstore/objc/SwaggerClientTests/SwaggerClient/SWGViewController.m, samples/client/petstore/objc/SwaggerClientTests/Tests/PetApiTest.m, samples/client/petstore/objc/SwaggerClientTests/Tests/StoreApiTest.m, samples/client/petstore/objc/SwaggerClientTests/Tests/UserApiTest.m
Fixes https://github.com/swagger-api/swagger-codegen/issues/2121
Since I needed to reference both the untouched and the camelize names of the first argument in the mustache files,  `CodegenOperation.firstParamAltName` has been introduced.
Now generated method names look like the following, e.g.:
```objc
-(NSNumber*) coffeeShopUpdateAllWithWhere: (NSString*) where
data: (XXCoffeeShop*) data
completionHandler: (void (^)(XXInlineResponse2001* output, NSError* error)) handler;
```
instead of:
```objc
-(NSNumber*) coffeeShopUpdateAllWithCompletionBlock :(NSString*) where 
data:(XXCoffeeShop*) data 
completionHandler: (void (^)(XXInlineResponse2001* output, NSError* error))completionBlock;
```
Note that the argument variable name for `completionHandler` has also been updated from …
=> [ObjC] Fix #2121, generated method names don't follow coding convention

modules/swagger-codegen/src/main/resources/Java/pojo.mustache
@wing328  @fehguy Sorry for being late on this - was with family over the weekend!
This change adds `this` to field names in `equals` within `pojo.mustache` so that an incorrect `equals` method is not generated in cases where a class has an internal field that is the same as the `classVarName` of the class.
=> Fix for issue #2117

modules/swagger-codegen/src/main/resources/Javascript/ApiClient.mustache, samples/client/petstore/javascript-promise/package.json, samples/client/petstore/javascript-promise/src/ApiClient.js, samples/client/petstore/javascript-promise/src/api/PetApi.js, samples/client/petstore/javascript-promise/src/api/StoreApi.js, samples/client/petstore/javascript-promise/src/api/UserApi.js, samples/client/petstore/javascript/src/ApiClient.js
Superagent does not always produce a `body`. See
http://visionmedia.github.io/superagent/ for details. When it
doesn't, we should deserialize the raw `response.text` rather
than returning `null`. Currently, the JS client always returns
`null` when the return type is String! This commit fixes
that.
=> Handle empty response.body from superagent

modules/swagger-codegen/src/main/resources/Java/build.gradle.mustache
jackson-jaxrs-json-provider & com.brsanthu:migbase64 are missing from the build.gradle mustache template (but the pom.xml one has them)
PS: Why are there no automated tests that detect this?
=> build.gradle missing 2 libs (pom.xml has)

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java, modules/swagger-codegen/src/main/resources/Javascript/model.mustache, samples/client/petstore/javascript-promise/src/api/PetApi.js, samples/client/petstore/javascript-promise/src/index.js, samples/client/petstore/javascript-promise/src/model/Category.js, samples/client/petstore/javascript-promise/src/model/Order.js, samples/client/petstore/javascript-promise/src/model/Pet.js, samples/client/petstore/javascript-promise/src/model/Tag.js, samples/client/petstore/javascript-promise/src/model/User.js, samples/client/petstore/javascript/src/index.js, samples/client/petstore/javascript/src/model/Category.js, samples/client/petstore/javascript/src/model/Order.js, samples/client/petstore/javascript/src/model/Pet.js, samples/client/petstore/javascript/src/model/Tag.js, samples/client/petstore/javascript/src/model/User.js
Fixes #2142 
This removes the creation of empty instances
for optional parameters in the model constructors. The problem is that
when the data for these fields is not present, we are left with "empty"
instances, which is not desirable, for several reasons:
1. It means that we cannot check for the presence of a field using the
usual JS idiom `if (object.field) {...}`.
2. It wastes memory with useless fields and objects.
Note: This completely removes the creation of "default" values
in the constructors. I don't know if there is some other case
where this is a useful thing (are there other kinds of defaults
besides empty instances of model classes?).
=> Do not create empty objects in model constructors

samples/client/petstore/javascript-promise/test/ApiClientTest.js
This simply copies the new tests from javascript-petstore
into javascript-promise-petstore.
I mentioned that these had already been added in a different PR, but I was mistaken.
=> Update tests for javascript-promise-petstore

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java
The (newly enabled) default string values in the JS client were missing quotes. This puts them in.
=> Add single quotes around default string values

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/java/JavaModelTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/php/PhpModelTest.java
it is cased because the property start with underscore and
object is created on th fly
fix #2191
=> avoid inner class

modules/swagger-codegen/src/main/java/io/swagger/codegen/AbstractGenerator.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConfig.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenParameter.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenProperty.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RubyClientCodegen.java
For https://github.com/swagger-api/swagger-codegen/issues/2038
=> Add more boolean flags to CodegenProperty

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java, modules/swagger-codegen/src/main/resources/Javascript/api.mustache, modules/swagger-codegen/src/main/resources/Javascript/model.mustache, samples/client/petstore/javascript-promise/src/api/PetApi.js, samples/client/petstore/javascript-promise/src/api/StoreApi.js, samples/client/petstore/javascript-promise/src/api/UserApi.js, samples/client/petstore/javascript-promise/src/model/Pet.js, samples/client/petstore/javascript-promise/test/api/PetApiTest.js, samples/client/petstore/javascript-promise/test/run_tests.html, samples/client/petstore/javascript/src/api/PetApi.js, samples/client/petstore/javascript/src/api/StoreApi.js, samples/client/petstore/javascript/src/api/UserApi.js, samples/client/petstore/javascript/src/model/Pet.js, samples/client/petstore/javascript/test/api/PetApiTest.js
See #2027
Code sample of optional parameters:
```javascript
// specify both "name" and "status"
petApi.updatePetWithForm(1, {name: 'new name', status: 'pending'}, function (err, data, resp) { });
// specify only "status"
petApi.updatePetWithForm(1, {status: 'sold'}, function (err, data, resp) { });
```
=> [JavaScript] Support optional parameters with object syntax

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RubyClientCodegen.java, modules/swagger-codegen/src/test/resources/2_0/petstore.json, samples/client/petstore/ruby/lib/petstore/api/pet_api.rb, samples/client/petstore/ruby/spec/api/PetApi_spec.rb, samples/client/petstore/ruby/spec/pet_spec.rb
Handle empty/reserved operation id by using a normalized one instead of throwing errors.
=> [Ruby] Handle empty/reserved operation id

modules/swagger-codegen/src/main/java/io/swagger/codegen/examples/ExampleGenerator.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/examples/XmlExampleGenerator.java, samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift
Fix https://github.com/swagger-api/swagger-codegen/issues/2156
I initially thought to keep using `Date` class but its automatic timezone handling was a bit annoying and decided to use just a plain text representation.  Hope it is OK.
=> Fix 2156 - Use fixed date/time in operation.examples to avoid unnecessary diffs

modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/cmd/Generate.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConstants.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/config/CodegenConfigurator.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
This fixes most of #1255 by adding the options `--model-name-prefix` and `--model-name-suffix` to the CLI, with corresponding changes to DefaultCodegen and CodegenConfigurator.
For C# and Java generators we (@jimschubert and me) also added support code as they override `DefaultCodegen.toModelName`.
I guess this needs to be changed for quite some other languages too.
We also need some unit tests for this functionality, these are not yet included. (The existing unit tests still run without changes, as none of them uses these options.)
=> Feature/1255 suffix+prefix for model name

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenParameter.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/CodegenTest.java, modules/swagger-codegen/src/test/resources/2_0/petstore.json
@fehguy @wing328 
This is a fix to support enums in query parameters. Enum-related information was not being stored on `CodegenParameter` previously; it is now. Test cases have been added to make sure that the enum information is being properly processed from the model.
Let me know if this change is alright. Also, the SDK templates have not been updated to take this change into account. Since I'm most familiar with Java, I think I might be able to update the Java template to support enums, but I think it would be best to make that a separate pull-request (assuming this one is approved).
=> Support for enums in query parameters (issue #1347)

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwiftCodegen.java, modules/swagger-codegen/src/main/resources/swift/api.mustache, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/SwiftOptionsProvider.java, samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift, samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift, samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift, samples/client/petstore/swift/SwaggerClientTests/SwaggerClientTests/PetAPITests.swift, samples/client/petstore/swift/SwaggerClientTests/SwaggerClientTests/StoreAPITests.swift, samples/client/petstore/swift/SwaggerClientTests/SwaggerClientTests/UserAPITests.swift
Fix https://github.com/swagger-api/swagger-codegen/issues/2120, https://github.com/swagger-api/swagger-codegen/issues/2157  -- Note this is a Breaking Change.
The following illustrates the differences in the usage of generated SDK:
Before:
```swift
PetstoreClientAPI.PetAPI.getPetById(petId: 1000).execute { response, error -> Void in
let pet = response?.body
```
After:
```swift
PetAPI.getPetById(petId: 1000) { pet, error -> Void in
```
PromiseKit ready version of simplified methods are also generated:
Before:
```swift
PetstoreClientAPI.PetAPI.getPetById(petId: 1000).execute().then { response -> Void in
let pet = response.body
```
After:
```swift
PetAPI.getPetById(petId: 1000).then { pet -> Void in
```
The `{{projectName}}API` namespace for API classes (`PetstoreClientAPI` above) now became …
=> Fix #2120, #2157 - Update Swift API method generation for ease of use

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java, modules/swagger-codegen/src/main/resources/csharp/api.mustache, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient.Test/StoreApiTests.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Api/PetApi.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Api/StoreApi.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Api/UserApi.cs
Currently, the local variable names may be a bit too "common" so to avoid collusion with model name, parameter name, we renamed the local variable names with prefix "localVar"
All C# test cases passed.
=> [C#] better local variable naming for C# API client

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ObjcClientCodegen.java, modules/swagger-codegen/src/main/resources/objc/api-body.mustache, samples/client/petstore/objc/SwaggerClient/SWGPetApi.h, samples/client/petstore/objc/SwaggerClient/SWGPetApi.m, samples/client/petstore/objc/SwaggerClient/SWGStoreApi.h, samples/client/petstore/objc/SwaggerClient/SWGStoreApi.m, samples/client/petstore/objc/SwaggerClient/SWGUserApi.m
Similar to #1255
Manually tested with `--model-name-prefix=prefix --model-name-suffix=suffix`
=> [ObjC] add prefix and suffix support to ObjC models

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractTypeScriptClientCodegen.java, modules/swagger-codegen/src/main/resources/TypeScript-Angular/api.mustache, modules/swagger-codegen/src/main/resources/TypeScript-node/api.mustache, modules/swagger-codegen/src/test/java/io/swagger/codegen/typescriptangular/TypeScriptAngularModelTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/typescriptnode/TypeScriptNodeModelTest.java, samples/client/petstore/typescript-angular/API/Client/PetApi.ts, samples/client/petstore/typescript-angular/API/Client/StoreApi.ts, samples/client/petstore/typescript-angular/API/Client/UserApi.ts, samples/client/petstore/typescript-node/api.ts
Similar to #1255
Manually tested with --model-name-prefix=prefix --model-name-suffix=suffix
Also renamed local var with better name (prefix "localVar")
=> [TypeScript] add prefix, suffix to TS model

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RubyClientCodegen.java
Similar to #1255
Manually tested with --model-name-prefix=prefix --model-name-suffix=suffix
=> [Ruby] add prefix, suffix support to Ruby's model

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java, modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/ApiClient.mustache, modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/CollectionFormats.mustache, modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/build.gradle.mustache, modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/pom.mustache, samples/client/petstore/java/retrofit2/build.gradle, samples/client/petstore/java/retrofit2/pom.xml, samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/ApiClient.java, samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/CollectionFormats.java, samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/StringUtil.java, samples/client/petstore/java/retrofit2rx/build.gradle, samples/client/petstore/java/retrofit2rx/pom.xml, samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/ApiClient.java, samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/CollectionFormats.java, samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/StringUtil.java
Retrofit v2.0.0-beta4 introduces some package changes from beta3, that should be reflected in moustache templates.
=> support latest Retrofit 2 v2.0.0-beta4

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ClojureClientCodegen.java
When the API name is more than one word (e.g., `UsersAPI` in a `users-service`), then the API namespace name will become `users-service.api.users-api`.
Prior to this fix, the API filename would include a dash, as it is solvely based on the API name (i.e., it currently is `users_service/api/users-api.clj`), which breaks clojure's conventions and leads to compilation errors.
With this fix, the API filename will be correctly converted to have underscores in place of dashes (i.e., the API file will be generated as `users_service/api/users_api.clj`).
=> Fix for clojure API filenames 

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
When generating Java clients with mode name prefix/suffix given, there are invalid imports on `Date` and `File`, e.g. for the Petstore sample (with model name prefix set to "My" and suffix set to "Model"):
import io.swagger.client.model.MyfileModel;
import io.swagger.client.model.MyDateModel;
This PR fixes it to:
import java.io.File;
import java.util.Date;
=> [Java] Fix invalid imports when model name prefix/suffix is present

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConfig.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ClojureClientCodegen.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/languages/ClojureClientCodegenTest.java
For example, when an operation's tag is `users-api`, `users_api` or `UsersApi`, generate the api file named `users_api.clj` and `users-api` as the namespace (it was `usersapi.clj` and `usersapi` before).
To implement this, I have to move the `sanitizeTag` method from DefaultGenerator.java to DefaultCodegen.java so that its behaviour can be overridden in ClojureClientCodegen.java, which is needed as the default implementation would sanitize `users-api` to `usersapi` before the tag is passed to `toApiName` and `toApiFilename`.
=> [Clojure] Improve api name for the Clojure client

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/GoClientCodegen.java
See issue #2285 for more details. This fix has been verified locally against a known good swagger file, and the generated client tested against just a handful of operations, so quality is **not** assured. From my quick look around there doesn't appear to be a Go test harness, I think that's something that we many need to work on. Apologies for any violations of style etc, feel free to edit as needed.
=> Several minor fixes in the Go client code generator for Camelization of elements

modules/swagger-codegen/src/main/resources/swift/api.mustache, samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift, samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift, samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift, samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/Models.swift, samples/client/petstore/swift/SwaggerClientTests/Podfile.lock, samples/client/petstore/swift/SwaggerClientTests/Pods/Manifest.lock, samples/client/petstore/swift/SwaggerClientTests/Pods/PromiseKit/Categories/UIKit/UIViewController+AnyPromise.h, samples/client/petstore/swift/SwaggerClientTests/Pods/PromiseKit/README.markdown, samples/client/petstore/swift/SwaggerClientTests/Pods/PromiseKit/Sources/AnyPromise.h, samples/client/petstore/swift/SwaggerClientTests/Pods/PromiseKit/Sources/AnyPromise.swift, samples/client/petstore/swift/SwaggerClientTests/Pods/PromiseKit/Sources/Promise.swift, samples/client/petstore/swift/SwaggerClientTests/Pods/Target Support Files/PromiseKit/Info.plist
Resolve issue 2181, and update PetStore example.
It does seem though, that the PetStore had more changes than I expected.
=> Issue 2181

modules/swagger-codegen/src/main/resources/go/api.mustache
... though the functionality to return an error object per the swagger is not yet implemented. See #2292
=> Re #2292 : The generated API should now return an err for non-2xx status codes

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenModel.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/resources/objc/model-body.mustache, modules/swagger-codegen/src/test/java/io/swagger/codegen/objc/ObjcModelTest.java, modules/swagger-codegen/src/test/resources/2_0/discriminatorTest.json
The swagger spec includes a discriminator field for Models. This discriminator value is the name of the property on the model that contains the name of the intended subtype for a given object. See discriminator under Fixed Fields in this page
http://swagger.io/specification/#schemaObject
This pull request adds a mustache conditional template to the objective-c model-object template for when the discriminator is defined for a given swagger model. The condition adds a custom initWithDictionary method that uses the value found in the dictionary to determine the appropriate class to return. This causes the discriminator value to be automatically applied per the spec. This implementation fails gracefully when the discriminator is defined but not supplied. The implementation fails hard when the …
=> Added discriminator support to Objective-C

README.md
The parameter being used was outputting a log file instead of changing downloading the file.
=> Fix wget command in readme

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java, modules/swagger-codegen/src/main/resources/php/ApiClient.mustache, modules/swagger-codegen/src/main/resources/php/ObjectSerializer.mustache, modules/swagger-codegen/src/main/resources/php/api.mustache, samples/client/petstore/php/SwaggerClient-php/lib/Api/PetApi.php, samples/client/petstore/php/SwaggerClient-php/lib/ApiClient.php, samples/client/petstore/php/SwaggerClient-php/lib/ObjectSerializer.php, samples/client/petstore/php/SwaggerClient-php/tests/PetApiTest.php
When `{ "type": "string", format": "binary" }` is requested, it's internally represented as a `ByteArray`, which was then translated into PHP as a literal byte array. A literal byte array in PHP is `[72, 101, 108, 108, 111]` and is not a format supported by any file, echoing, or any standard library operations other than general array handling.
I propose that a "binary string" should represent just that in PHP, an unencoded string. This allows access to the full standard library of tools for dealing with strings as bytes, including file writing and echoing.
This should have some notable performance improvements for end-users as the previous fix was essentially to do the following, which ends up making 4 copies of the data as it passes through the various layers of unpacking, and …
=> [PHP] Use String instead of Byte Array

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenModel.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java, modules/swagger-codegen/src/main/resources/python/__init__model.mustache, modules/swagger-codegen/src/main/resources/python/__init__package.mustache, modules/swagger-codegen/src/test/resources/2_0/petstore.json, samples/client/petstore/python/swagger_client/__init__.py, samples/client/petstore/python/swagger_client/apis/pet_api.py, samples/client/petstore/python/swagger_client/apis/store_api.py, samples/client/petstore/python/swagger_client/models/__init__.py
=> [Python] better handling of model name

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RubyClientCodegen.java
=> [JavaScript] Add model name prefix/suffix to JavaScript client

modules/swagger-codegen/src/main/resources/php/ObjectSerializer.mustache, modules/swagger-codegen/src/test/resources/2_0/petstore.json, samples/client/petstore/php/SwaggerClient-php/lib/Model/InlineResponse200.php, samples/client/petstore/php/SwaggerClient-php/lib/ObjectSerializer.php, samples/client/petstore/php/SwaggerClient-php/tests/PetApiTest.php, samples/client/petstore/php/SwaggerClient-php/tests/StoreApiTest.php
To deserialize `type: object` properly, we need to update the deserializer: set data type to `array` (associative array in PHP)
We also add more test cases to cover `type: object`
=> [PHP] update deserializer to handle object type and add more test cases

modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Client/ApiClient.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/InlineResponse200.cs, samples/client/petstore/csharp/SwaggerClientTest/SwaggerClientTest.userprefs, samples/client/petstore/csharp/SwaggerClientTest/TestOrder.cs, samples/client/petstore/csharp/SwaggerClientTest/TestPet.cs
Update deserialisation to return `type:obejct` as `Newtonsoft.Json.Linq.JObject`
Added more test cases
=> [C#] add type object support to C# API client

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/StaticHtmlGenerator.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/DefaultGeneratorTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/statichtml/StaticHtmlTagsTest.java
here we go. I checked generated files with -Dapis= -DsupportingFiles= manually. I also checked that StaticHtmlTagsTest.java test is representative, eg. if you put  StaticDocCodegen as a mock it pass well. Note, I don't use mock library, but miss randomized test library.
Nevertheless, let me know if I can improve it. Thanks!
=> issue #1875 fixing -Dapis= work for -l html, provding test.

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java, modules/swagger-codegen/src/main/resources/csharp/compile.mustache, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/compile.bat, samples/client/petstore/csharp/SwaggerClientTest/obj/Debug/SwaggerClientTest.csproj.FilesWrittenAbsolute.txt
- used "model_" instead of "object_" for naming model (reserved word), e.g. Object => ModelObject
-  fixed compile.bat in WinXP by using `copy` instead of `cp`
```
ProcessModel: Default    DomainUsage: Single
Execution Runtime: mono-4.0
......................	.........
Tests run: 31, Errors: 0, Failures: 0, Inconclusive: 0, Time: 18.8935898 seconds
Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0
```
=> [C#] Better naming for reserved word (model name), fixed compile.bat

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractTypeScriptClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AndroidClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FlashClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/GoClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClosureAngularClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ObjcClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PerlClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RubyClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwiftCodegen.java
Use "ModelObject" so as to avoid "ObjectObject" if the model name is "object"
=> Use "Model" to handle model name with reserved keywords

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java
This PR sorts API files (tags), methods in each API file (operations) and model files (definitions) by name (tag, operationId and model key) alphabetically.
=> Sort APIs and models by name

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java, modules/swagger-codegen/src/main/resources/csharp/compile.mustache
super.postProcessModels needs to be called. Otherwise renaming of members with same name as the class does not take place. Fixed it.
=> CSharpClientCodegen: Members with same name as the class will not be renamed.

modules/swagger-codegen/src/main/resources/csharp/api.mustache, modules/swagger-codegen/src/test/resources/2_0/petstore.json, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Api/UserApi.cs
- fixed base64encode in C# API class
- added test case to cover http basic authentication moving forward
(to fix #2368)
=> [C#] fix base64encode issue in csharp

modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/cmd/Generate.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConfig.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConstants.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/config/CodegenConfigurator.java, modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache, modules/swagger-codegen/src/main/resources/csharp/Configuration.mustache, modules/swagger-codegen/src/main/resources/csharp/api.mustache, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Api/PetApi.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Api/StoreApi.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Api/UserApi.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Client/ApiClient.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Client/Configuration.cs, samples/client/petstore/csharp/SwaggerClientTest/SwaggerClientTest.userprefs
Tested on both Windows and Mac. All test cases passed.
We'll roll out the feature (configurable user-agent) to other language one by one.
The feature is broken at the moment due to RestSharp: https://github.com/restsharp/RestSharp/issues/787
(for https://github.com/swagger-api/swagger-codegen/issues/2367)
=> [C#] add httpUserAgent option, add configurable user-agent support to C#

modules/swagger-codegen/src/main/resources/php/ObjectSerializer.mustache
Some API's return an invalid, empty string as a date-time property.
DateTime::__construct() will return the current time for empty input which is probably not what is meant.
The invalid empty string is probably to be interpreted as a missing field/value.
Let's handle this graceful.
=> Handle empty date-time gracefully

modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/model.mustache, modules/swagger-codegen/src/main/resources/Java/libraries/retrofit/model.mustache, modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/model.mustache
If the API definition contains something like
```
"integer": {
"id": "integer",
"properties": {}
},
```
with no description property, the generated code for all no default libraries will add a ApiModel annotation but no import. 
pull request appears to fix the compile time issue.
=> non default java clients wont compile if description is empty in API json.

modules/swagger-codegen/src/main/resources/php/ObjectSerializer.mustache, samples/client/petstore/php/SwaggerClient-php/README.md, samples/client/petstore/php/SwaggerClient-php/docs/InlineResponse200.md, samples/client/petstore/php/SwaggerClient-php/docs/PetApi.md, samples/client/petstore/php/SwaggerClient-php/docs/StoreApi.md, samples/client/petstore/php/SwaggerClient-php/git_push.sh, samples/client/petstore/php/SwaggerClient-php/lib/Api/PetApi.php, samples/client/petstore/php/SwaggerClient-php/lib/Api/StoreApi.php, samples/client/petstore/php/SwaggerClient-php/lib/Model/InlineResponse200.php, samples/client/petstore/php/SwaggerClient-php/lib/ObjectSerializer.php
Currently we use PHP's `DateTime::ISO8601` for the date-time properties but according to http://php.net/manual/en/class.datetime.php#datetime.constants.iso8601 it is actually not compatible with ISO-8601.
Instead we should use `DateTime::ATOM`.
=> Use PHP's DateTime::ATOM for true ISO-8601 support

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java, modules/swagger-codegen/src/test/resources/2_0/petstore.json, samples/client/petstore/php/SwaggerClient-php/README.md, samples/client/petstore/php/SwaggerClient-php/docs/InlineResponse200.md, samples/client/petstore/php/SwaggerClient-php/docs/PetApi.md, samples/client/petstore/php/SwaggerClient-php/docs/StoreApi.md, samples/client/petstore/php/SwaggerClient-php/lib/Api/PetApi.php, samples/client/petstore/php/SwaggerClient-php/lib/Api/StoreApi.php, samples/client/petstore/php/SwaggerClient-php/lib/Model/Model200Response.php, samples/client/petstore/php/SwaggerClient-php/lib/ObjectSerializer.php
For #2392 
Added a test model named "200_response"
```
PHPUnit 4.8.23 by Sebastian Bergmann and contributors.
........................
Time: 12.63 seconds, Memory: 11.25Mb
OK (24 tests, 1466 assertions)
```
=> [PHP] better handling of model name starting with number

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenModel.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java, modules/swagger-codegen/src/main/resources/Javascript/ApiClient.mustache, modules/swagger-codegen/src/main/resources/Javascript/api.mustache, modules/swagger-codegen/src/main/resources/Javascript/enumClass.mustache, modules/swagger-codegen/src/main/resources/Javascript/index.mustache, modules/swagger-codegen/src/main/resources/Javascript/model.mustache, modules/swagger-codegen/src/test/java/io/swagger/codegen/javascript/JavaScriptClientOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/javascript/JavaScriptInheritanceTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/javascript/JavaScriptModelEnumTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/javascript/JavaScriptModelTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/JavaScriptOptionsProvider.java
Please review and merge the fix and tests for Issue #2258 "[JavaScript] Generator options and template improvements". Many thanks.
=> [JavaScript] Generator options and template improvements

modules/swagger-codegen/src/main/resources/swift/Models.mustache, modules/swagger-codegen/src/main/resources/swift/model.mustache, modules/swagger-codegen/src/test/resources/2_0/petstore.json, samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/Models.swift, samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/Models/ModelReturn.swift, samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/Models/Name.swift, samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/Models/SpecialModelName.swift
For https://github.com/swagger-api/swagger-codegen/issues/2315
=> [Swift] use baseName for swift model property

modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/api.mustache
Swagger files that declare "in: formData" parameters will result in API class that cannot be compiled due to the usage of "@Multipart" annotations in method signatures.
=> Missing multipart (form data) imports.

modules/swagger-codegen/src/main/resources/objc/ApiClient-body.mustache, modules/swagger-codegen/src/main/resources/objc/ApiClient-header.mustache, samples/client/petstore/objc/SwaggerClient/SWGApiClient.h, samples/client/petstore/objc/SwaggerClient/SWGApiClient.m, samples/client/petstore/objc/SwaggerClient/SWGName.h, samples/client/petstore/objc/SwaggerClient/SWGName.m
Added getter for offline state this lets the app check if and ApiClient is going to attempt the network request or just force cache.
Added setter for AFNetworkReachabilityStatus, this is useful for two reason first to set the default before it has been set by the reachability manager. 
Also as the ApiClient uses a shared instance of the reachability manager it is possible for another class to setReachabilityStatusChangeBlock stopping the ApiClient getting reachability change callbacks internally. By adding a setter it would be possible to pass the changes along.
Note: on changes to SWGName, these changes must be because the last person to edit the swagger spec did not regenerate the objc code.
=> Updates to objc api to address issue #2422

modules/swagger-codegen/src/main/resources/csharp/Configuration.mustache, modules/swagger-codegen/src/main/resources/csharp/enumClass.mustache, modules/swagger-codegen/src/main/resources/csharp/model.mustache, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient.Test/NameTests.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Client/Configuration.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/Animal.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/Cat.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/Dog.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/InlineResponse200.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/Name.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/Order.cs, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/Pet.cs, samples/client/petstore/csharp/SwaggerClientTest/SwaggerClientTest.userprefs
minor fix to docstring for userAgent and enum
=> [C#] minor fix to docstring in csharp

README.md
The first URL (from the doc) does not work (at least for me) whereas the second does .
- **Previously** wget http://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/2.1.**5**/...
- **Now** wget http://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/2.1.**6**/...
=> Fix typo in wget arg

README.md
The link for 2.1.6 currently goes to 2.1.5. This was missed in #2515.
=> fix link in README.md.

modules/swagger-codegen/src/main/resources/python/api_client.mustache, modules/swagger-codegen/src/main/resources/python/rest.mustache, samples/client/petstore/python/swagger_client/api_client.py, samples/client/petstore/python/swagger_client/rest.py
Allow HTTP body to be used in DELETE operation for Python client. A fix for Issue #2410.
=> Issue 2410: Suport HTTP body for DELETE operation

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java
Previously if you specified a property to be of type `number` and didn't
explicitly specify a format Codegen would map it into an (unknown) PHP
class `Number`.
We add a mapping from Swaggers `number` to PHPs `float`.
=> [PHP] Map number without format to float

modules/swagger-codegen/src/main/resources/TypeScript-node/api.mustache, samples/client/petstore/typescript-node/api.ts, samples/client/petstore/typescript-node/client.ts
https://github.com/swagger-api/swagger-codegen/issues/2274
Generate enum from api key auth methods. Use this to set api key of authentication. Update test client to set multiple keys.
=> Typescript Node: Support Multiple Api Key Auth Methods

modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache
Workaround for unavailable sync HTTP-request in RestSharp, waiting for async HTTP-request now.
(this issue is/was UWP-only)
=> fix sync call for uwp

modules/swagger-codegen/src/main/resources/asyncscala/model.mustache
Small fix to generate Option fields correctly in the model of the scalaasync client. 
When displaying the mustache scope with the option -DdebugModels I was not able to 
find the variable "isNotRequired" so I replaced it with the negated version of "required". Now
the model.mustache generates Option fields correctly.
=> Fix handling optional fields in asyncscala client model

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
Addresses #2561 ... populate the p.is<TYPE>Param flags before the call to `postProcessParameter`
=> Issue #2561 : set isXYZParam flags before postProcessParameter [updated]

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/GoClientCodegen.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/go/GoClientOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/go/GoModelTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/GoClientOptionsProvider.java
@wing328 i have got the test running, but there are couple errors that i cant figure it out, please advise
Link #2569
=> issue #2569: added model tests for Go

modules/swagger-codegen/src/main/resources/go/configuration.mustache, samples/client/petstore/go/swagger/Configuration.go
For #2579 @wing328 I added "UserAgent" to config struct, i tried running the CLI with `--http-user-agent` it replaced the default value as expected.
=> isssue#2579: added "UserAgent" in configuration

modules/swagger-codegen/src/main/resources/TypeScript-node/api.mustache, samples/client/petstore/typescript-node/api.ts
This came up when needing to pass a bool as a param. If the bool was false, the API would throw saying it wasn't supplied, but false is a valid value for the input.
=> [Typescript-Node] Verify required parameter is not undefined instead of falsey.

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwiftCodegen.java
This replaces something like `property:_Type` with `property:TypeEnum`, which is more idiomatic swift
=> Append reserved swift enum type with "Enum"

modules/swagger-codegen/src/main/resources/Java/pom.mustache
This fixes #2607 and brings the Java version in the generated pom to match the version in the generated build.gradle.
-
_Copy/pasted from #2607_
The `default.yaml` example spec available in the swagger editor is sufficient for reproducing this.
A minimalist spec would be any spec that has a `definitions` section:
```
swagger: '2.0'
info:
version: 0.0.0
title: Simple API
paths:
/:
get:
responses:
200:
description: OK
definitions:
Example:
type: object
properties:
uuid:
type: string
```
Every generated class under `io.swagger.client.model` has a reference to `java.util.Objects`, which was only added in JDK 1.7. The generated `build.gradle` specifies 1.7 as the target/source version, but the `pom.xml` specifies 1.6.
=> [Java] Update Java version to 1.7 in generated pom

modules/swagger-codegen/src/main/resources/swift/Models.mustache, modules/swagger-codegen/src/main/resources/swift/model.mustache
Fix #2116
When using unwrapRequired option in Swift, we can now force the required attributes to be defined when instantiating a model.
=> [Swift] Force required attrs to be defined with unwrapRequired

modules/swagger-codegen/src/main/resources/csharp/README.mustache, modules/swagger-codegen/src/main/resources/csharp/api_doc.mustache, modules/swagger-codegen/src/main/resources/objc/Configuration-body.mustache, modules/swagger-codegen/src/main/resources/objc/README.mustache, modules/swagger-codegen/src/main/resources/objc/api_doc.mustache, modules/swagger-codegen/src/main/resources/perl/README.mustache, modules/swagger-codegen/src/main/resources/perl/api_doc.mustache, modules/swagger-codegen/src/main/resources/php/README.mustache, modules/swagger-codegen/src/main/resources/php/api_doc.mustache, modules/swagger-codegen/src/main/resources/python/README.mustache, modules/swagger-codegen/src/main/resources/python/api_doc.mustache, modules/swagger-codegen/src/main/resources/ruby/README.mustache, modules/swagger-codegen/src/main/resources/ruby/api_doc.mustache, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/README.mustache, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/docs/PetApi.md, samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/docs/StoreApi.md, samples/client/petstore/objc/SwaggerClient/SWGConfiguration.m, samples/client/petstore/objc/docs/SWGPetApi.md, samples/client/petstore/objc/docs/SWGStoreApi.md, samples/client/petstore/perl/docs/PetApi.md, samples/client/petstore/perl/docs/StoreApi.md, samples/client/petstore/perl/test.pl, samples/client/petstore/php/SwaggerClient-php/docs/PetApi.md, samples/client/petstore/php/SwaggerClient-php/docs/StoreApi.md, samples/client/petstore/python/docs/PetApi.md, samples/client/petstore/python/docs/StoreApi.md, samples/client/petstore/ruby/docs/PetApi.md, samples/client/petstore/ruby/docs/StoreApi.md
The [OAuth spec](https://tools.ietf.org/html/rfc6750#section-2.1) says that the correct format is `Bearer <token>`, not `BEARER <token>`. My server using [node-oauth2-server](https://github.com/oauthjs/node-oauth2-server) was rejecting my request without this fix.
It looks like the only place `BEARER` was in actual code was `modules/swagger-codegen/src/main/resources/objc/Configuration-body.mustache`. I experienced the issue in ObjC.
This pullreq was created by running
```bash
find . -type f -exec sed -i "" "s/BEARER/Bearer/g" {} \;
```
and then ignoring all the whitespace-only changes that generates.
=> Replace 'BEARER' with 'Bearer' everywhere for RFC6750 compliance.

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptFetchClientCodegen.java, modules/swagger-codegen/src/main/resources/TypeScript-Fetch/README.md, modules/swagger-codegen/src/main/resources/TypeScript-Fetch/package.json.mustache, modules/swagger-codegen/src/main/resources/TypeScript-Fetch/tsconfig.json.mustache, modules/swagger-codegen/src/main/resources/TypeScript-Fetch/typings.json.mustache
* build `declaration` and expose it via `typings` in `package.json`
* Update `typings.json` to point to DefinitelyTyped for `isomorphic-fetch`. (Previously the definition in DefinitelyTyped had an issue with ES6 usage that was fixed by my [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9144))
* Add README.md
=> Update typings for typescript-fetch

modules/swagger-codegen/src/main/resources/php/README.mustache, modules/swagger-codegen/src/main/resources/php/api_doc.mustache
Some links are broken after #2808 
Here is an example of PHP SDK with fixed links:
https://github.com/wing328/petstore-php2/blob/master/README.md
=> [PHP] fix broken links in php doc

modules/swagger-codegen/src/main/resources/typescript-angular/api.mustache, samples/client/petstore/typescript-angular/API/Client/PetApi.ts, samples/client/petstore/typescript-angular/API/Client/StoreApi.ts, samples/client/petstore/typescript-angular/API/Client/UserApi.ts
In Angular.js, values are injected into service in one of two ways:
1) Inline (by name).
2) By a static injector variable.
The TypeScript generator uses the 2nd method. This method requires you
to explicitly enumerate all the values you would like to have injected.
If you fail to inject a value the Angular DI system will simply pass you
`undefined`. The constructor is expecting 3 values to be passed (the
final being basePath) but the injector static only defines 2 values.
This results in basePath always being undefined no matter what you
define it to be.
This change updates the injector variable to handle that properly.
=> Update the injector static variable to contain all injected values.

modules/swagger-codegen/src/main/resources/typescript-angular/api.mustache, samples/client/petstore/typescript-angular/API/Client/PetApi.ts, samples/client/petstore/typescript-angular/API/Client/StoreApi.ts, samples/client/petstore/typescript-angular/API/Client/UserApi.ts
In Angular if a value is not defined for injection it is passed as
undefined. That means that most of the time `if (value) {` is a
reasonable test. Unfortunately since `""` (empty string) is also falsey
by nature, an empty string will not trigger the if properly.
Instead you should check `if (value !== undefined) {`.
=> Update TypeScript to do a better check for empty on basePath.

modules/swagger-codegen/src/main/resources/swift/APIHelper.mustache, modules/swagger-codegen/src/main/resources/swift/api.mustache
This is a fix attempt for : [Swift] Bool value conversion #2446
It implements the usage of APIHelpers boolean to strings conversion for request parameters.
=> Update api.mustache and APIHelper.mustache so that they can handle real boolean to string conversion

README.md
The name of this generator was updated from `silex` to `silex-PHP` in @dc7c2a4b, but that change wasn't reflected in README.md.
=> Fixes instructions for generating PHP Silex code.

modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache, modules/swagger-codegen/src/main/resources/typescript-angular2/package.mustache, samples/client/petstore/typescript-angular2/default/api/PetApi.ts, samples/client/petstore/typescript-angular2/default/api/StoreApi.ts, samples/client/petstore/typescript-angular2/default/api/UserApi.ts, samples/client/petstore/typescript-angular2/npm/README.md, samples/client/petstore/typescript-angular2/npm/api/PetApi.ts, samples/client/petstore/typescript-angular2/npm/api/StoreApi.ts, samples/client/petstore/typescript-angular2/npm/api/UserApi.ts, samples/client/petstore/typescript-angular2/npm/package.json
Updated typescript-anuglar2 clients so that generated code can be used in anuglar2 rc.
- What I've done
- Update npm package name
- Refactor generated code (Constructor of angular2 injector should not have any unnecessary argument)
=> Update typescript-angular2 client to adapt to rc (#2770)

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java, modules/swagger-codegen/src/main/resources/csharp/IApiAccessor.mustache, modules/swagger-codegen/src/main/resources/csharp/api.mustache
This pull does two things: adds partial keyword to generated Api class. This allows developers to create additional methods in non-generated files.
This also adds `IApiAccessor` as a base interface for Api interfaces. This allows devs to access `Configuration` getter/setter and `GetBasePath` programmatically when the specific type name of the Api class is not known or not relevant.
see #2723
=> [csharp] Add common IApiAccessor interface

README.md, modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConstants.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java, modules/swagger-codegen/src/main/resources/csharp/Solution.mustache
> Adds support for system properties `apiTests`, `modelTests`, `modelTests`, `modelDocs`.
> All accepting a boolean value to explicitly define whether or not these
> should be generated.
> 
> These properties aren't considered "features", so specifying
> `-DmodelTests=false` for example won't cause api or supportFiles to be ignored.
> 
> Includes additionalProperty excludeTests for when apiTests and modelTests are
> both set to false.
> 
> Also includes update to csharp client generator to prevent generation of
> the Test project or inclusion of the Test project when both api and
> model tests are excluded.
Also updates the Python generator to not output the test init script when all tests are excluded.
I did a search and only found C# and Python would be affected. Please let me know if I …
=> [generator] Individual options to exclude tests and docs for apis and models

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java, modules/swagger-codegen/src/main/resources/php/README.mustache, modules/swagger-codegen/src/main/resources/php/composer.mustache, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/PhpClientOptionsProvider.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/php/PhpClientOptionsTest.java
There couple of issues with the current version:
* CliOptions `composerVendorName` and `composerProjectName` have no effect, because `gitUserId` and `gitRepoId` have default values so the inverted condition will never work.
* Further more CliOptions `gitUserId` and `gitRepoId` eventhough they would work they are not documented when running `java -jar swagger-codegen-cli.jar config-help -l php` or anywhere else.
=> [PHP] Fixing bug with composer project path in generated sdk

pom.xml
release note: https://github.com/swagger-api/swagger-core/releases/tag/v1.5.9
=> Upgrade swagger core to 1.5.9

modules/swagger-codegen/src/main/resources/swift/api.mustache
=> [Swift] Enum parameters are now handled

modules/swagger-codegen/src/test/java/io/swagger/codegen/AbstractIntegrationTest.java
Skip the integration test, which reports the following error: 
```
Failed tests: 
TypescriptAngular2AdditionalPropertiesIntegrationTest>AbstractIntegrationTest.generatesCorrectDirectoryStructure:43 Directory content of '/Users/williamcheng/Code/swagger-api/swagger-codegen/modules/swagger-codegen/target/test-classes/integrationtests/typescript/additional-properties-expected' and '/Users/williamcheng/Code/swagger-api/swagger-codegen/modules/swagger-codegen/target/test-classes/integrationtests/typescript/additional-properties-result' differ.: lists don't have the same size expected [8] but found [7]
Tests run: 477, Failures: 1, Errors: 0, Skipped: 0
```
We'll re-enable it later after we dig deeper into the integration test.
=> Skip integration test

modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache
This should fix the following problems, I ran into:
1) typescript complaining: "Cannot create property 'xxx' on string '' " (string treated as map)
2) I have a subclass of RequestOptions which will call merge, which behind the scenes calls clone which isn't implemented on string
=> typescript-angular2 query string fix

samples/client/petstore/typescript-fetch/tests/default/package.json, samples/client/petstore/typescript-fetch/tests/default/run_tests_via_webpack.html
* Update `tsify`
* Fix webpack.html file
=> update package.json and fix webpack.html

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java
Changes the default primitive for `number` with no specified format from `double` to `decimal` in C#.
Other number/integer mappings remain unchanged:
| type | format | C# type |
|-------|----------|------------|
| number | float | System.Float |
| number | double | System.Double |
| number | ------ | System.Decimal |
| integer | int64 | System.Int64 | 
| integer | int32 | System.Int32 | 
| integer | ------ | System.Int32 | 
See #2967 and #2813.
@wing328 this seems like an extremely simple fix, and I feel like I've missed something. I generated the csharp client and verified that types looked fine and tests passed.
=> [csharp] map number/no format to Decimal

README.md, modules/swagger-codegen/src/main/java/io/swagger/codegen/ignore/rules/DirectoryRule.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/ignore/rules/IgnoreLineParser.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/ignore/CodegenIgnoreProcessorTest.java
Tests are created to act on actual files to gauarantee functionality of
.swagger-codegen-ignore processing. Found two minor issues, one with
directory processing of files below the directory and another with
filename.* patterns reversing as *filename. for the pattern.
Added documentation to the README about .swagger-codegen-ignore file
support and syntax.
=> [codegen ignore] Add tests and docs, fix two minor issues

modules/swagger-codegen-maven-plugin/src/main/java/io/swagger/codegen/plugin/CodeGenMojo.java
Both CodeGenMojo and CodegenConfigurator where parsing the swagger input.
The result in CodeGenMojo was discarded. I simply removed the line in
CodeGenMojo.
=> Remove unnecessary 2nd call to SwaggerParser.

modules/swagger-codegen/.gitignore, modules/swagger-codegen/src/main/java/io/swagger/codegen/InlineModelResolver.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/InlineModelResolverTest.java
[Use "Title" as model name if provided in swagger definition](https://github.com/swagger-api/swagger-codegen/issues/2868)
this allows to use names defined by user in Response model instead of
"inline_response". Also user could use title to have specific name for
request model instead of parameter name
=> use Title attribute as model name

modules/swagger-codegen/src/main/resources/Java/libraries/feign/ApiClient.mustache, samples/client/petstore/java/feign/LICENSE, samples/client/petstore/java/feign/src/main/java/io/swagger/client/FormAwareEncoder.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/StringUtil.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/api/FakeApi.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/api/PetApi.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/api/StoreApi.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/api/UserApi.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/AdditionalPropertiesClass.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Animal.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/AnimalFarm.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/ArrayTest.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Cat.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Category.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Dog.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/EnumTest.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/FormatTest.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/MixedPropertiesAndAdditionalPropertiesClass.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Model200Response.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/ModelApiResponse.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/ModelReturn.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Name.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Order.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Pet.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/ReadOnlyFirst.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/SpecialModelName.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Tag.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/User.java
By default, the feign jackson decoder doesn't fail on unknown properties.
I think the swagger feign generated code should follow the same behaviour.
=> Feign: disable FAIL_ON_UNKNOWN_PROPERTIES by default

modules/swagger-codegen/src/main/resources/htmlDocs/index.mustache
=> use {{name}} not {{classname}} in HTML section header/anchors

modules/swagger-codegen/src/main/resources/objc/ApiClient-body.mustache, modules/swagger-codegen/src/main/resources/objc/ApiClient-header.mustache, modules/swagger-codegen/src/main/resources/objc/Sanitizer-body.mustache
Fix a bug that's been around for a while where ApiClient.timeoutInterval didn't do anything. Every time `requestWithPath:...` is called, a new `requestSerializer` is set, which is why the timeout update needs to happen in `setRequestSerializer:`. `60` is the default timeout interval for `NSURLRequest`. I couldn't find a way to get that value programmatically.
Also, when I updated my clone of `swagger-codegen`, my generated code failed to compile for a number of reasons. I had to fix these bugs to get the compile working again. All of these were introduced in the past month or so, it seems like I'm just cleaning up after someone else's mess here.
- Change `#import <AFNetworking.h>` back to `#import <AFNetworking/AFNetworking.h>`. XCode can't locate the header with a normal CocoaPod …
=> [ObjC] Fix various bugs in generated code.

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/HaskellServantCodegen.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/go/GoClientOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/go/GoModelTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/lumen/LumenServerOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/springboot/SpringBootServerOptionsTest.java
Replaced NotImplementedException with UnsupportedOperationException. See
bug #3011.
Eclipse was throwing some errors related to differences in package names
vs file path. I renamed the packages io.swagger.codegen.Go to
io.swagger.codegen.go, io.swagger.codegen.slim to package
io.swagger.codegen.lumen and io.swagger.codegen.springBoot to
io.swagger.codegen.springboot in some test files.
=> Use UnsupportedOperationException.

.gitignore
As they all support gradle now, the build folder that contains the artifacts and test reports should be added into gitignore.
=> Add build folder under java sample clients into gitignore in sample.

modules/swagger-codegen/src/test/java/io/swagger/codegen/ignore/CodegenIgnoreProcessorTest.java
There doesn't appear to be an excellent way to resolve a case sensitive
test on Windows, so conditionally skipping the test on Windows.
See #3047
=> [swagger-codegen-ignore] Skip file case test Windows

modules/swagger-codegen/src/main/resources/swift/APIHelper.mustache
This will prevent the creation of an empty body for GET requests.
=> [Swift] #3036 Make APIHelper.convertBoolToString return nil for nil input

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java, modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache, modules/swagger-codegen/src/main/resources/csharp/Configuration.mustache, modules/swagger-codegen/src/main/resources/csharp/ExceptionFactory.mustache, modules/swagger-codegen/src/main/resources/csharp/api.mustache
See #2724 
This implements a delegate `ExceptionFactory` which can be applied to an instance of `Configuration`. Defaults to previous exception handling logic.
Also converts `ApiClient` to a partial class, with partial methods to intercept requests and responses. These could be used to do any number of things that hook into the `CallApi` methods.
Users can now implement their own logic in partial classes and prevent future overwrites using .swagger-codegen-ignore. For example:
```
// in src/IO.Swagger/Client/ApiClientRequestInterceptor.cs
//…
public partial class ApiClient 
{
partial void InterceptRequest(IRestRequest request)
{
Debug.WriteLine("Request made: {0}", request.Path);
}
}
// in .swagger-codegen-ignore, prevents any possible file overwrites.
//… …
```
=> [csharp] Intercept hooks for req/res and ExceptionFactory

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Qt5CPPGenerator.java, modules/swagger-codegen/src/main/resources/qt5cpp/api-body.mustache, modules/swagger-codegen/src/main/resources/qt5cpp/helpers-body.mustache, samples/client/petstore/qt5cpp/PetStore/PetApiTests.cpp, samples/client/petstore/qt5cpp/PetStore/PetStore.pro, samples/client/petstore/qt5cpp/client/SWGHelpers.cpp, samples/client/petstore/qt5cpp/client/SWGOrder.h, samples/client/petstore/qt5cpp/client/SWGPetApi.cpp, samples/client/petstore/qt5cpp/client/SWGStoreApi.h
@wing328 as announced in my email, here is the fix for the missing data-type handlers in the template thats rendered into SWGHelpers.cpp
QDate and QDateTime handling was missing entirely. I also found QString handling to be missing in arrays.
PS: There are four overloaded `QString stringValue(..)` functions which are unused and never called as it seems. By logic, they would be missing overloaded funcs for float, double, QDate and QDateTime. I didnt add those tho as they are never called and SDK is working still fine.
=> Fixed several issues with Qt5 generator and Qt5 PetStore tests

modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/pojo.mustache, samples/server/petstore/jaxrs-cxf/gen/java/io/swagger/api/PetApi.java, samples/server/petstore/jaxrs-cxf/gen/java/io/swagger/model/Category.java, samples/server/petstore/jaxrs-cxf/gen/java/io/swagger/model/Order.java, samples/server/petstore/jaxrs-cxf/gen/java/io/swagger/model/Pet.java, samples/server/petstore/jaxrs-cxf/gen/java/io/swagger/model/Tag.java, samples/server/petstore/jaxrs-cxf/gen/java/io/swagger/model/User.java
[java-cxf] 	Fix Java CXF on parameter names containing '_' or '-'. The template uses only the parameter name which result on misnaming parameters.
=> Fix Java CXF on parameter names containing '_' or '-'

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ScalaClientCodegen.java, modules/swagger-codegen/src/main/resources/scala/build.sbt.mustache, samples/client/petstore/scala/build.sbt
See #241 and #3006
Adds build.sbt to scala client. Removed previous option-based functionality.
~~This adds a configuration option to support sbt (`-DbuildTool=sbt`) or gradle (`-DbuildTool=gradle`) to the scala client.~~
~~I've made the option value generic enough not to cause clutter. Unlike some of the java implementations like `JavaClientCodegen`, this will generate files for the selected build tool and not all files for both.~~
~~Also, unlike other sbt support which creates `build.sbt` this creates a `ProjectBuild.scala`. It's my understanding that some plugins don't work correctly when scalaVersion with binary version 2.11 is defined in `build.sbt` and a plugin requires 2.10. If this is incorrect, let me know and I'll change to build.sbt. However, both the .sbt and .scala build …
=> [scala] Add SBT buid support for scala client

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConstants.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java
[csharp] Enabling Assembly Info to be set by the following command line's additional-properties:
- packageTitle
- packageProductName
- packageDescription
- packageCompany
- packageCopyright
=> Issue-3168: [csharp] Allow additional-properties to set Assembly Info #3168

modules/swagger-codegen/src/main/resources/typescript-angular/api.mustache, modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache
The required parameter check in the api.mustache caused unexpected behaviour if the actual parameter value evaluates to false e.g "false", 0, -1, false
The code was changed to check for undefined or null instead
See issue #3096
=> Changed check for required parameter to check for null or undefined

modules/swagger-codegen/src/main/java/io/swagger/codegen/examples/ExampleGenerator.java
As stated on http://swagger.io/specification/#dataTypes the date-time format defined by RFC3339 requires a colon in the time-offset.
I think #2236 introduced that one.
The z-schema and the javascript swagger-tools validators even don't validate the date format without the colon. e.g. If you enable the output validation in the nodejs sample app, the request to http://localhost:8080/v2/store/order/1 failes with an `Error: Response validation failed: failed schema validation`
=> fix date format in example generator

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml, samples/client/petstore/java/okhttp-gson/docs/MapTest.md, samples/client/petstore/java/okhttp-gson/hello.txt, samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/model/MapTest.java
This PR also comments out "map of map of enum" test in the spec (model section) as many languages do not support that at the moment. We'll re-enable after majority of the langauges support it.
=> [Java] better default value for variable declaration (with inner enum type)

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java, modules/swagger-codegen/src/main/resources/ruby/api.mustache, modules/swagger-codegen/src/main/resources/ruby/api_client.mustache, modules/swagger-codegen/src/test/java/io/swagger/codegen/DefaultGeneratorTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/ruby/RubyClientCodegenTest.java, modules/swagger-codegen/src/test/resources/2_0/pathWithHtmlEntity.yaml
Prior to this PR, the default generator HTML-escapes the variables passed to Mustache, which breaks specification with a path that contains a HTML entity.
In my use case, the path contains an equal sign (e.g. /foo=bar), which gets escaped to &#x3D; by Mustache's Escaper (into /foo&#x3D;bar).
This obviously breaks the API client because it sends a request to /foo&#x3D;bar instead of /foo=bar .
This PR ensures that the path stays AS-IS in the generated client code.
=> Disable path HTML-escaping in Ruby api template

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenOperation.java
add getHasExamples() method to support {{hasExamples}} tag in templates #3250
=> add getHasExamples() method to support {{hasExamples}} tag in templates

modules/swagger-codegen/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml, samples/server/petstore/lumen/app/Http/controllers/FakeApi.php, samples/server/petstore/lumen/app/Http/controllers/PetApi.php, samples/server/petstore/lumen/app/Http/controllers/StoreApi.php, samples/server/petstore/lumen/app/Http/controllers/UserApi.php, samples/server/petstore/lumen/app/Http/routes.php
The security tests have been moved to petstore-security-test.yaml
=> Remove security test from petstore-with-fake-endpoints-models-for-testing

modules/swagger-codegen/src/main/resources/JavaJaxRS/api.mustache, modules/swagger-codegen/src/main/resources/JavaJaxRS/formParams.mustache, modules/swagger-codegen/src/main/resources/JavaJaxRS/serviceFormParams.mustache
Fixed issue where the JAX-RS code generator creates variables with duplicate names when more than one file is included in the API call which results in a compilation error by modifying the api.mustache file, formParams.mustache file, and serviceFormParams.mustache file.
=> Issue #3300 Modified JavaJaxrs resources to fix duplicated variable names

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SpringCodegen.java, modules/swagger-codegen/src/main/resources/JavaSpring/application.mustache
Fixed issue [Spring]Add support for the contextPath in Spring-boot gen #3193
=> Fixed issue [Spring]Add support for the contextPath in Spring-boot gen #3193

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
Update the wording:
```
IMPORTANT NOTE: retrofit1.x is no longer actively maintained so please upgrade to 'retrofit2' instead.
```
=> [Java][Retrofit] update wording for java retrofit1

modules/swagger-codegen/src/main/resources/python/api_client.mustache
Added long to primitives along with int, float, str, date and tuple. Needed for Python 2.x
=> Added long to primitive data types supported in Python codegen

modules/swagger-codegen-maven-plugin/README.md, modules/swagger-codegen-maven-plugin/src/main/java/io/swagger/codegen/plugin/CodeGenMojo.java
=> [MAVEN] #3284: Made modelNamePrefix and -Suffix available through maven

modules/swagger-codegen/src/main/resources/go/api_client.mustache
Let the fmt package help convert the obj to a string.  Previously this could panic if the obj was an int.
=> [Go] ParameterToString can panic

modules/swagger-codegen/src/main/resources/Javascript/README.mustache
=> Correct reference to ApiClient default instance

modules/swagger-codegen/src/main/resources/swift/APIs.mustache, modules/swagger-codegen/src/main/resources/swift/AlamofireImplementations.mustache, samples/client/petstore/swift/default/PetstoreClient/Classes/Swaggers/APIs.swift, samples/client/petstore/swift/default/PetstoreClient/Classes/Swaggers/AlamofireImplementations.swift, samples/client/petstore/swift/default/SwaggerClientTests/SwaggerClientTests/StoreAPITests.swift
By injecting `onProgressReady` into a `RequestBuilder` instance, you can now get a reference to the request's `NSProgress` instance.
```swift
requestBuilder.onProgressReady = { (requestProgress) in
let disposable = requestProgress
.rx_observeWeakly(CGFloat.self, "fractionCompleted")
.subscribeNext({ (fractionCompleted) in
guard let fractionCompleted = fractionCompleted else { return }
progress(Float(fractionCompleted))
})
self.disposeBag.addDisposable(disposable)
}
```
=> [Swift] Expose NSProgress to RequestBuilder

.travis.yml
Run petstore.swagger.io locally to
- improve performance
- avoid issues with 2 or more jobs sharing the same backend (http://petstore.swagger.io)
- avoid bad data in public petstore server causing test failures
=> Run petstore.swagger.io locally

bin/objc-petstore-all.sh, modules/swagger-codegen/src/main/resources/slim/index.mustache, samples/server/petstore/slim/index.php
Add missing context path (e.g. /v2/) to index.php in PHP Slim
=> [PHP][Slim] Add missing context path

samples/client/petstore/python/tests/test_pet_api.py
```
======================================================================
ERROR: test_delete_pet (tests.test_pet_api.PetApiTests)
Traceback (most recent call last):
File "/home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/python/tests/test_pet_api.py", line 203, in test_delete_pet
raise "expected an error"
TypeError: exceptions must be old-style classes or derived from BaseException, not str
```
in https://travis-ci.org/swagger-api/swagger-codegen/jobs/143133869.
The test itself seems flaky. And that's not fixed in this PR.
=> Raise Exception Instead of String in Python Test

modules/swagger-codegen/src/main/resources/scalatra/Bootstrap.mustache, modules/swagger-codegen/src/main/resources/scalatra/api.mustache, samples/server/petstore/scalatra/src/main/scala/ScalatraBootstrap.scala, samples/server/petstore/scalatra/src/main/scala/com/wordnik/client/api/PetApi.scala, samples/server/petstore/scalatra/src/main/scala/com/wordnik/client/api/StoreApi.scala, samples/server/petstore/scalatra/src/main/scala/com/wordnik/client/api/UserApi.scala
=> fix scalatra path with basepath (#1425)

modules/swagger-codegen/src/main/resources/go/api.mustache
This addresses #3459 by removing the check for required params.
=> Issue #3459 removed check for required params

modules/swagger-codegen/src/main/resources/go/api.mustache
Addresses #3462 
Query params are now sent in their original base name (e.g. `project_id`) instead of the camelized param name (`projectId`).
Note this PR builds on currently-unmerged PR #3460.
=> Issue 3462 caseified query param

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Qt5CPPGenerator.java, modules/swagger-codegen/src/main/resources/qt5cpp/helpers-body.mustache
Now you can have sth like this in your swagger and it will work with Qt5 SDK
```
ProductObject:
type: object
properties:
image:
type: string
format: byte
```
the property will be base64 encoded/decoded to/from JSON
=> Qt5: Added missing datatype handlers for QByteArray for swagger-type "byte"

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ConfluenceWikiGenerator.java, modules/swagger-codegen/src/main/resources/META-INF/services/io.swagger.codegen.CodegenConfig, modules/swagger-codegen/src/main/resources/confluenceWikiDocs/index.mustache, modules/swagger-codegen/src/main/resources/confluenceWikiDocs/param.mustache
Addition of a generator to create confluence wiki markup which can then be pasted into confluence to generate docs as per image
=> Confluence Wiki Documentation

modules/swagger-codegen/src/main/resources/JavaSpring/libraries/spring-cloud/apiClient.mustache, samples/client/petstore/spring-cloud/README.md, samples/client/petstore/spring-cloud/src/main/java/io/swagger/api/PetApiClient.java, samples/client/petstore/spring-cloud/src/main/java/io/swagger/api/StoreApiClient.java, samples/client/petstore/spring-cloud/src/main/java/io/swagger/api/UserApiClient.java, samples/client/petstore/spring-stubs/README.md
FeignClient annotations are redered incorrectly with an extra space. This causes a problem that spring properties are not loaded. E.g: the below annotation was generated
```@FeignClient(name="${ swaggerPetstoreSimple.name:swaggerPetstoreSimple}", url="${ swaggerPetstoreSimple.url:https://localhost:8080/api}", configuration = ClientConfiguration.class)```
and overwriting 
swaggerPetstoreSimple.name:swaggerPetstoreSimple
was not possible because of the extra spaces.
=> fixing bug of rendering an extra spaces into @FeignClient annotation

modules/swagger-codegen/src/main/resources/Java/pom.mustache, samples/client/petstore/java/jersey1/pom.xml
This plugin would allow the generation of Javadoc from the generated Java client using `mvn javadoc:javadoc`, making it easier to document the Java client API.
=> [Java] Add maven-javadoc-plugin in pom.xml of generated Java client.

modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/ApiClient.mustache, samples/client/petstore/java/jersey2-java8/src/main/java/io/swagger/client/ApiClient.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/ApiClient.java
=> Support byte[] downloading in Java jersey2 client

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/HaskellServantCodegen.java, modules/swagger-codegen/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml, samples/client/petstore/java/okhttp-gson/docs/EnumArrays.md, samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/model/EnumArrays.java, samples/server/petstore/haskell-servant/lib/SwaggerPetstore/Types.hs
For https://github.com/swagger-api/swagger-codegen/issues/2487
=> [Java] better enum naming for symbol

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/GoClientCodegen.java, modules/swagger-codegen/src/main/resources/go/api.mustache, samples/client/petstore/go/go-petstore/pet_api.go, samples/client/petstore/go/go-petstore/store_api.go, samples/client/petstore/go/go-petstore/user_api.go
@wing328 please review, this is solving the `pathParams ` empty issue
=> [GO] Fixing compilation issue when pathParams  is not presented

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractPhpCodegen.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/php/PhpModelTest.java
- Added test cases for PHP generator to ensure we've the enum-related values covered moving forward
=> [PHP] add enum test cases for PHP generator (java)

modules/swagger-codegen/src/main/java/io/swagger/codegen/InlineModelResolver.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/InlineModelResolverTest.java
Fixing bug as defined in [Issue-3523](https://github.com/swagger-api/swagger-codegen/issues/3523)
InlineModels defined within MapProerty and ArrayProerty were not using
"title".
Added Unit Tests
=> support Title as model name for any inline object

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/GoClientCodegen.java
This fixes that passing a template directory (`-t ./anything`) on the command line is ignored for generating Go projects.
Original bug introduced here: https://github.com/swagger-api/swagger-codegen/commit/579e356e5bab30aa8aea1b8554491ad92cf38d38#diff-e72dbab4ab666029c71bd9b1028c03faR110
=> Restore ability to configure Go

modules/swagger-codegen/src/main/resources/aspnet5/model.mustache, modules/swagger-codegen/src/main/resources/csharp/modelEnum.mustache, samples/server/petstore/aspnet5/README.md, samples/server/petstore/aspnet5/src/IO.Swagger/Dockerfile, samples/server/petstore/aspnet5/src/IO.Swagger/Models/ApiResponse.cs, samples/server/petstore/aspnet5/src/IO.Swagger/Models/Category.cs, samples/server/petstore/aspnet5/src/IO.Swagger/Models/Order.cs, samples/server/petstore/aspnet5/src/IO.Swagger/Models/Pet.cs, samples/server/petstore/aspnet5/src/IO.Swagger/Models/Tag.cs, samples/server/petstore/aspnet5/src/IO.Swagger/Models/User.cs
See #3262
This would replace #3263, which provides a correct implementation for JSON endpoints only. Although generated code for the `aspnet5` generator outputs to JSON, we still need to support all output types (i.e. from the `produces` definition of the api endpoint).
I've also fixed the formatting in the `ToString` method for models and changed the generic description on enums which was previously worded like an auto-implemented property description.
=> [aspnet] Honor casing of properties from definition

modules/swagger-codegen/src/main/resources/Java/modelEnum.mustache, modules/swagger-codegen/src/main/resources/Java/modelInnerEnum.mustache, samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/EnumClass.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/EnumTest.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/MapTest.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Order.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Pet.java, samples/client/petstore/java/jersey1/src/main/java/io/swagger/client/model/EnumArrays.java, samples/client/petstore/java/jersey1/src/main/java/io/swagger/client/model/EnumClass.java, samples/client/petstore/java/jersey1/src/main/java/io/swagger/client/model/EnumTest.java, samples/client/petstore/java/jersey1/src/main/java/io/swagger/client/model/MapTest.java, samples/client/petstore/java/jersey1/src/main/java/io/swagger/client/model/Order.java, samples/client/petstore/java/jersey1/src/main/java/io/swagger/client/model/Pet.java, samples/client/petstore/java/jersey2-java8/pom.xml, samples/client/petstore/java/jersey2-java8/src/main/java/io/swagger/client/model/EnumClass.java, samples/client/petstore/java/jersey2-java8/src/main/java/io/swagger/client/model/EnumTest.java, samples/client/petstore/java/jersey2-java8/src/main/java/io/swagger/client/model/MapTest.java, samples/client/petstore/java/jersey2-java8/src/main/java/io/swagger/client/model/Order.java, samples/client/petstore/java/jersey2-java8/src/main/java/io/swagger/client/model/Pet.java, samples/client/petstore/java/jersey2/pom.xml, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/model/EnumArrays.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/model/EnumClass.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/model/EnumTest.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/model/MapTest.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/model/Order.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/model/Pet.java, samples/client/petstore/java/retrofit/pom.xml
Changed 4-space indentation to 2-space to make it consistent with the rest of the code in the model
=> [Java] minor indentation fix for java enum models

.travis.yml
More info: https://github.com/travis-ci/travis-ci/issues/6445
Workaround (this PR): Install Go manually.
=> [Go] Fix CI tests 

modules/swagger-codegen/src/main/resources/go/api.mustache
Right now, any generated code where the http basic authentication is
required is broken, as it tries to access nonexistent field in the
generated `Configuration` struct.
The alternative is to fix `configuration.mustache` to replace the
`UserName` field with `Username` field.
=> Go: Replace `.Username` with `.UserName` in generated API methods.

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/javascript/JavaScriptModelTest.java
There are no Integer and DateTime types in Javascript.
=> [Javascript] Fix types

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConfig.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java
Extension of the CodegenConfig interface in order to use JMustache compiler native features, such as the deactivation of HTML escaping.
My custom generator implements it like this : 
```
@Override
public Compiler processCompiler(Compiler compiler) {
return compiler.escapeHTML(false);
}
```
=> Adding support for JMustache compiler customization

modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/api.mustache
The mustache templates for the other Java clients (e.g
Java/api.mustache) use 3 curly brackets around the path variable
so the path is not escaped. Make the okhttp-gson template
consistent with them.
=> Don't escape path in generated okhttp-gson client code

modules/swagger-codegen/src/main/resources/JavaSpring/application.mustache, samples/client/petstore/spring-cloud/src/main/java/io/swagger/api/PetApi.java, samples/client/petstore/spring-cloud/src/main/java/io/swagger/configuration/ClientConfiguration.java, samples/client/petstore/spring-cloud/src/main/java/io/swagger/model/Category.java, samples/client/petstore/spring-cloud/src/main/java/io/swagger/model/ModelApiResponse.java, samples/client/petstore/spring-cloud/src/main/java/io/swagger/model/Order.java, samples/client/petstore/spring-cloud/src/main/java/io/swagger/model/Pet.java, samples/client/petstore/spring-cloud/src/main/java/io/swagger/model/Tag.java, samples/client/petstore/spring-cloud/src/main/java/io/swagger/model/User.java, samples/client/petstore/spring-stubs/src/main/java/io/swagger/api/PetApi.java, samples/client/petstore/spring-stubs/src/main/java/io/swagger/model/Category.java, samples/client/petstore/spring-stubs/src/main/java/io/swagger/model/ModelApiResponse.java, samples/client/petstore/spring-stubs/src/main/java/io/swagger/model/Order.java, samples/client/petstore/spring-stubs/src/main/java/io/swagger/model/Pet.java, samples/client/petstore/spring-stubs/src/main/java/io/swagger/model/Tag.java, samples/client/petstore/spring-stubs/src/main/java/io/swagger/model/User.java, samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/api/FakeApi.java, samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/api/PetApi.java, samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/FakeApi.java, samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/FakeApiController.java, samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/PetApi.java, samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/PetApiController.java, samples/server/petstore/springboot/src/main/java/io/swagger/api/FakeApi.java, samples/server/petstore/springboot/src/main/java/io/swagger/api/FakeApiController.java, samples/server/petstore/springboot/src/main/java/io/swagger/api/PetApi.java, samples/server/petstore/springboot/src/main/java/io/swagger/api/PetApiController.java, samples/server/petstore/springboot/src/main/resources/application.properties
Title says it all. Sets the `server.port` value in `application.properties` to the port defined by the `host` field in the swagger spec file. If no port is provided `server.port` is set to 8080 by default, which matches current template behavior. 
The `serverPort` property is an existing value that is already being parsed by [SpringCodegen.java](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SpringCodegen.java#L233).
=> [Spring Boot] use port defined in spec file for server.port value

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConfig.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/config/CodegenConfigurator.java
I have two use cases where I would like my custom generator to be aware of the Swagger inputSpec path being used for generation:
- I am generating documentation for my API and I want to indicate the path of the original spec so it can also be downloaded by developers - as the spec also consists in useful documentation
- I want to parse myself the inputSpec in addition to the parsing performed by the SwaggerParser, as the SwaggerParser loses some information - such as the order of the operations in the spec, and I want to display the operations in that same exact order in the generated documentation
Currently the inputSpec path is only kept until the SwaggerParser is used to build the Swagger object, and then it is lost. Generators are not able to access that information.
=> Allowing generators to be aware of original inputSpec path

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Qt5CPPGenerator.java
Fixes #3192 
**edit:** I have barely touched Java at all, so please double check that this change makes sense. I just made the default values stop being NULL, without any understanding of how the entire codegen project goes together.
=> For Qt5 server generator, add BaseIntegerProperty to default values

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngular2ClientCodegen.java, modules/swagger-codegen/src/main/resources/typescript-angular2/README.mustache, modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache, modules/swagger-codegen/src/main/resources/typescript-angular2/index.mustache, modules/swagger-codegen/src/main/resources/typescript-angular2/variables.mustache
Enable setup of base path for apis in angular2 bootstrap by providing the value to resolve #3513 
Need verifying I haven't missed anything as first code contribution to swagger-codegen and building the project from source
=> inject base_path opaque token for typescript angular2

modules/swagger-codegen/src/main/resources/android/model.mustache
Otherwise, if {{classVarName}} is the same as a class member name, the function will not work.
=> Uses this.{{name}} to scope instance

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngular2ClientCodegen.java, modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache, modules/swagger-codegen/src/main/resources/typescript-angular2/model.mustache, modules/swagger-codegen/src/main/resources/typescript-angular2/package.mustache, modules/swagger-codegen/src/main/resources/typescript-angular2/typings.mustache
Due to changes in the latest version of Angular ([2.0.0-rc.5](https://github.com/angular/angular/releases/tag/2.0.0-rc.5)), I had to make a few changes to the existing codegen to make it work again for me.
I also believe these changes would make a good starting point for #3081.
See https://angular.io/docs/ts/latest/api/http/index/RequestOptions-class.html. A few changes here, the HTTP method can now be specified using an enum instead of a string, which I did to make the client more robust. I also set the response content type to JSON, which is the only type of content we can handle at the moment.
https://github.com/angular/angular/issues/10612
See line [95](https://github.com/swagger-api/swagger-codegen/compare/master...sebastianhaas:angular2-rc5?expand=1#diff-174bce348e2584ed556f2d1ce0714 …
=> Angular2 rc5

modules/swagger-codegen/src/main/resources/android/libraries/volley/apiInvoker.mustache, samples/client/petstore/android/volley/README.md, samples/client/petstore/android/volley/docs/PetApi.md, samples/client/petstore/android/volley/src/main/java/io/swagger/client/ApiInvoker.java, samples/client/petstore/android/volley/src/main/java/io/swagger/client/api/PetApi.java
This makes the volley request socket timeout equal to apiInvoker connection timeout.
Issue https://github.com/swagger-api/swagger-codegen/issues/3635
=> [android] volley socket timeout configurable

modules/swagger-codegen/src/main/resources/python/api.mustache, modules/swagger-codegen/src/main/resources/python/api_client.mustache, samples/client/petstore/python/petstore_api/api_client.py, samples/client/petstore/python/petstore_api/apis/fake_api.py, samples/client/petstore/python/petstore_api/apis/pet_api.py
Implements collection formatting to Python. Previously, collections were not formatted at all, but serialized as e.g. literal `['foo', 'bar']`.
This implements it for form data only for now; I don't think it can be implemented sanely without API changes for query string data. The `query_params` arg for `api_client.call_api` would have to be changed from dict to a list (like `post_params` already is). Is that considered a breaking API change that needs to go to the 2.3.0 branch?
=> Python fixes

modules/swagger-codegen/src/main/resources/python/api.mustache, modules/swagger-codegen/src/main/resources/python/api_client.mustache, samples/client/petstore/python/petstore_api/api_client.py, samples/client/petstore/python/petstore_api/apis/fake_api.py, samples/client/petstore/python/petstore_api/apis/pet_api.py, samples/client/petstore/python/petstore_api/apis/store_api.py, samples/client/petstore/python/petstore_api/apis/user_api.py
This reworks support for form data collection formatting, and adds collection formatting support for paths, headers, and query string. The rework is because the previous implementation would fail for non-string collection items, and to provide basis for the other types.
This _does_ contain breaking changes for the methods in `api_client`; however if I understand correctly, the breaking changes meant in the PR checklist would be ones that affect client code that uses the generated api classes. This one doesn't contain any of them, so I suppose it's good for `master`.
=> Python collection formatting fixes/support

modules/swagger-codegen/src/main/resources/ruby/base_object.mustache, samples/client/petstore/ruby/lib/petstore/models/additional_properties_class.rb, samples/client/petstore/ruby/lib/petstore/models/animal.rb, samples/client/petstore/ruby/lib/petstore/models/animal_farm.rb, samples/client/petstore/ruby/lib/petstore/models/api_response.rb, samples/client/petstore/ruby/lib/petstore/models/array_of_array_of_number_only.rb, samples/client/petstore/ruby/lib/petstore/models/array_of_number_only.rb, samples/client/petstore/ruby/lib/petstore/models/array_test.rb, samples/client/petstore/ruby/lib/petstore/models/cat.rb, samples/client/petstore/ruby/lib/petstore/models/category.rb, samples/client/petstore/ruby/lib/petstore/models/client.rb, samples/client/petstore/ruby/lib/petstore/models/dog.rb, samples/client/petstore/ruby/lib/petstore/models/enum_arrays.rb, samples/client/petstore/ruby/lib/petstore/models/enum_test.rb, samples/client/petstore/ruby/lib/petstore/models/format_test.rb, samples/client/petstore/ruby/lib/petstore/models/has_only_read_only.rb, samples/client/petstore/ruby/lib/petstore/models/list.rb, samples/client/petstore/ruby/lib/petstore/models/map_test.rb, samples/client/petstore/ruby/lib/petstore/models/mixed_properties_and_additional_properties_class.rb, samples/client/petstore/ruby/lib/petstore/models/model_200_response.rb, samples/client/petstore/ruby/lib/petstore/models/model_return.rb, samples/client/petstore/ruby/lib/petstore/models/name.rb, samples/client/petstore/ruby/lib/petstore/models/number_only.rb, samples/client/petstore/ruby/lib/petstore/models/order.rb, samples/client/petstore/ruby/lib/petstore/models/pet.rb, samples/client/petstore/ruby/lib/petstore/models/read_only_first.rb, samples/client/petstore/ruby/lib/petstore/models/special_model_name.rb, samples/client/petstore/ruby/lib/petstore/models/tag.rb, samples/client/petstore/ruby/lib/petstore/models/user.rb
Similar to https://github.com/swagger-api/swagger-codegen/pull/3716, replacing ^ with \A to match the beginning of a string.
=> [Ruby] update regular expression to use \A instead of ^

modules/swagger-codegen-cli/pom.xml, modules/swagger-codegen-maven-plugin/pom.xml, modules/swagger-codegen/pom.xml, modules/swagger-generator/pom.xml, pom.xml
Update the pom file to match for 2.3.0 release
=> Bump version of pom to 2.3.0-SNAPSHOT for the 2.3.x release

appveyor.yml
Fix M2_HOME, which was likely reset to something else due to a change in appveyor side.
=> Fix appveyor maven environment variable

modules/swagger-codegen/src/main/java/io/swagger/codegen/InlineModelResolver.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/InlineModelResolverTest.java
=> Make InlineModelResolver resolve vendorExtensions correctly for Schema Object

modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache
Apply same workaround as https://github.com/swagger-api/swagger-codegen/pull/1127 to typescript-angular2 template.
=> Add last response code and headers

bin/csharp-petstore.sh, modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConstants.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java, modules/swagger-codegen/src/main/resources/csharp/FodyWeavers.xml, modules/swagger-codegen/src/main/resources/csharp/Project.mustache, modules/swagger-codegen/src/main/resources/csharp/model.mustache, modules/swagger-codegen/src/main/resources/csharp/modelGeneric.mustache, modules/swagger-codegen/src/main/resources/csharp/packages.config.mustache, modules/swagger-codegen/src/test/java/io/swagger/codegen/csharp/CSharpClientOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/CSharpClientOptionsProvider.java
This adds support for additional property `generatePropertyChanged=true` which will add an `OnPropertyChanged` method and a `PropertyChanged` event to all models and use Fody code weaving to inject the raised events into property setters.
For more information on code weaving, check out [Fody](https://github.com/Fody/Fody) on github.
see feature request #3356.
@wing328 question... I moved the `$@` in `bin/csharp-petstore.sh` to support running the script with properties passed to CLI. For example:
```
./bin/csharp-petstore.sh --additional-properties=generatePropertyChanged=true
```
Was there a reason it previously went `$@ generate...` instead? Usage of those sample generator scripts doesn't seem to be documented anywhere.
=> [csharp] PropertyChanged support .NET 4.x+

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/FormatTest.java, samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/MixedPropertiesAndAdditionalPropertiesClass.java, samples/client/petstore/java/jersey1/docs/FormatTest.md, samples/client/petstore/java/jersey1/docs/MixedPropertiesAndAdditionalPropertiesClass.md, samples/client/petstore/java/jersey1/src/main/java/io/swagger/client/model/FormatTest.java, samples/client/petstore/java/jersey1/src/main/java/io/swagger/client/model/MixedPropertiesAndAdditionalPropertiesClass.java, samples/client/petstore/java/jersey2-java8/docs/FormatTest.md, samples/client/petstore/java/jersey2-java8/docs/MixedPropertiesAndAdditionalPropertiesClass.md, samples/client/petstore/java/jersey2-java8/src/main/java/io/swagger/client/model/FormatTest.java, samples/client/petstore/java/jersey2-java8/src/main/java/io/swagger/client/model/MixedPropertiesAndAdditionalPropertiesClass.java, samples/client/petstore/java/jersey2/docs/FormatTest.md, samples/client/petstore/java/jersey2/docs/MixedPropertiesAndAdditionalPropertiesClass.md, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/model/FormatTest.java, samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/model/MixedPropertiesAndAdditionalPropertiesClass.java, samples/client/petstore/java/okhttp-gson/docs/FormatTest.md, samples/client/petstore/java/okhttp-gson/docs/MixedPropertiesAndAdditionalPropertiesClass.md, samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/model/FormatTest.java, samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/model/MixedPropertiesAndAdditionalPropertiesClass.java, samples/client/petstore/java/retrofit/src/main/java/io/swagger/client/model/FormatTest.java, samples/client/petstore/java/retrofit/src/main/java/io/swagger/client/model/MixedPropertiesAndAdditionalPropertiesClass.java, samples/client/petstore/java/retrofit2/docs/FormatTest.md, samples/client/petstore/java/retrofit2/docs/MixedPropertiesAndAdditionalPropertiesClass.md, samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/model/FormatTest.java, samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/model/MixedPropertiesAndAdditionalPropertiesClass.java, samples/client/petstore/java/retrofit2rx/docs/FormatTest.md, samples/client/petstore/java/retrofit2rx/docs/MixedPropertiesAndAdditionalPropertiesClass.md, samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/model/FormatTest.java, samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/model/MixedPropertiesAndAdditionalPropertiesClass.java
It looks like there was a commit back in January that reverted a previous fix that added UUID types for java.  The commit is 7aac639.
This fixes the issue by allowing UUID to be used in generated code.
=> Java: Fix UUID mapping to a UUID instead of a string

modules/swagger-codegen/src/main/resources/typescript-angular2/package.mustache, samples/client/petstore/typescript-angular2/npm/README.md, samples/client/petstore/typescript-angular2/npm/package.json, samples/client/petstore/typescript-angular2/npm/variables.ts
Removed files property from typescript-angular2 package.json so that all files are uploaded during npm publish.
=> [typescript-angular2] npm publish missing files

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java, modules/swagger-codegen/src/main/resources/csharp/Project.mustache, modules/swagger-codegen/src/main/resources/csharp/TestProject.mustache, modules/swagger-codegen/src/main/resources/csharp/model.mustache, modules/swagger-codegen/src/main/resources/csharp/modelGeneric.mustache
Work in progress.
C# client property validation using data annotations. Based off of python client's implementation.
See #3222 and #2663 
TODO: I need to do more thorough testing on this. Currently, only C# client property validation. I plan to update `aspnet` and `nancyfx` too.
=> [wip][csharp] client property validations

modules/swagger-codegen/src/main/resources/Java/pojo.mustache
Triple mustache is required because annotations may contain chars like "=" that
would be mistakenly encoded. See #3754 for an example
=> Use triple mustache for vendorExtensions.extraAnnotation

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
Fixed a NPE, this simply provides a better error message.
=> Fix NullPointerException when the oauth flow is missing

modules/swagger-codegen/src/main/resources/typescript-angular2/model.mustache, samples/client/petstore/typescript-angular2/default/api/PetApi.ts, samples/client/petstore/typescript-angular2/default/model/Pet.ts, samples/client/petstore/typescript-angular2/npm/README.md, samples/client/petstore/typescript-angular2/npm/api/PetApi.ts, samples/client/petstore/typescript-angular2/npm/api/StoreApi.ts, samples/client/petstore/typescript-angular2/npm/api/UserApi.ts, samples/client/petstore/typescript-angular2/npm/configuration.ts, samples/client/petstore/typescript-angular2/npm/index.ts, samples/client/petstore/typescript-angular2/npm/model/Pet.ts, samples/client/petstore/typescript-angular2/npm/package.json
To fix https://github.com/swagger-api/swagger-codegen/issues/3831
=> [Typescript][Angular2] Fix required properties in the model

modules/swagger-codegen/src/main/resources/php/ApiException.mustache, samples/client/petstore/php/SwaggerClient-php/lib/ApiException.php
In the ApiClient the headers param is always given array or null so the PHPDoc is definitely wrong.
I have made the pull request to v2.3.0 since the change of ApiException constructor param from  `$responseHeaders = null` to `array $responseHeaders = null` technically speaking breaks backward compatibility by forcing array or null.
=> [PHP] Change APIException to expect headers as array

modules/swagger-codegen/src/main/resources/php/composer.mustache, samples/client/petstore/php/SwaggerClient-php/composer.json
Correct Composer license identifier to follow the standard [defined by SPDX Open Source License Registry](https://spdx.org/licenses/Apache-2.0.html) as described in [Composer doc](https://getcomposer.org/doc/04-schema.md#license)
=> [PHP] Correct Composer license identifier

modules/swagger-codegen/src/main/resources/swift/model.mustache
Previously when running with unwrapRequired=true, the init function would only list required parameters.  I added the optional ones with default values to nil.
=> add optional parameters to init when unwrapRequired is true

modules/swagger-codegen/src/main/resources/TypeScript-Fetch/api.mustache, samples/client/petstore/typescript-fetch/builds/default/api.ts, samples/client/petstore/typescript-fetch/builds/es6-target/api.ts, samples/client/petstore/typescript-fetch/builds/with-npm-version/api.ts
To fix https://github.com/swagger-api/swagger-codegen/issues/3832
=> [Typescript] fix typescript-fetch base path by removing ending slash

modules/swagger-codegen/src/main/resources/go/api.mustache, samples/client/petstore/go/go-petstore/fake_api.go, samples/client/petstore/go/go-petstore/pet_api.go, samples/client/petstore/go/go-petstore/store_api.go, samples/client/petstore/go/go-petstore/user_api.go
Fix trailing comma in go api client
=> [Go] fix trailing comma in go api client

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenModel.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/resources/htmlDocs/index.mustache, modules/swagger-codegen/src/test/resources/2_0/petstore.yaml, samples/html/index.html
The HTML output does not include the title and description of the schema. This adds them, for better documentation of the API and schema.
=> add title, description to HTML output

modules/swagger-codegen/src/main/resources/swift/api.mustache
Fix path parameter with `baseName` mustache tag (instead of `paramName`)
https://github.com/swagger-api/swagger-codegen/issues/3858
=> [Swfit] fix path parameter with baseName mustache tag

modules/swagger-codegen/src/main/resources/swift/AlamofireImplementations.mustache, samples/client/petstore/swift/default/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift, samples/client/petstore/swift/default/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift, samples/client/petstore/swift/default/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift, samples/client/petstore/swift/default/PetstoreClient/Classes/Swaggers/AlamofireImplementations.swift, samples/client/petstore/swift/promisekit/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift, samples/client/petstore/swift/promisekit/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift, samples/client/petstore/swift/promisekit/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift, samples/client/petstore/swift/promisekit/PetstoreClient/Classes/Swaggers/AlamofireImplementations.swift, samples/client/petstore/swift/rxswift/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift, samples/client/petstore/swift/rxswift/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift, samples/client/petstore/swift/rxswift/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift, samples/client/petstore/swift/rxswift/PetstoreClient/Classes/Swaggers/AlamofireImplementations.swift
- [ x ] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ x ] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run`./bin/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [ x ] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.
- Add thread-safe access to Alamofire Manager dictionary. Since we cannot assume the API client will always be invoked on the same thread.
=> [Swift] Use thread safe manager dictionary

.github/PULL_REQUEST_TEMPLATE.md
The pull request template only mentions regeneration scripts in `./bin/`. I added `./bin/security/` as well to also keeping those samples updated.
=> Mention security script in pull request template

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractPhpCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java, modules/swagger-codegen/src/main/resources/php/.travis.yml, modules/swagger-codegen/src/main/resources/php/README.mustache, modules/swagger-codegen/src/main/resources/php/phpunit.xml.mustache, samples/client/petstore/php/SwaggerClient-php/.travis.yml, samples/client/petstore/php/SwaggerClient-php/README.md, samples/client/petstore/php/SwaggerClient-php/phpunit.xml.dist, samples/client/petstore/php/SwaggerClient-php/pom.xml
This PR fixes the PHPUnit setup in PHP client. The new setup provides a basic [phpunit.xml](https://phpunit.de/manual/4.8/en/appendixes.configuration.html) file which allows for more simple invocation.
Also, `.travis` used a hardcoded path to test folder which is not necessarily valid with directory name config changes.
To verify it works, just run:
composer install
vendor/bin/phpunit
=> [PHP] fix PHPUnit invocation, add basic phpunit.xml.dist

modules/swagger-codegen/src/main/resources/ruby/base_object.mustache, samples/client/petstore/ruby/lib/petstore/models/additional_properties_class.rb, samples/client/petstore/ruby/lib/petstore/models/animal.rb, samples/client/petstore/ruby/lib/petstore/models/animal_farm.rb, samples/client/petstore/ruby/lib/petstore/models/api_response.rb, samples/client/petstore/ruby/lib/petstore/models/array_of_array_of_number_only.rb, samples/client/petstore/ruby/lib/petstore/models/array_of_number_only.rb, samples/client/petstore/ruby/lib/petstore/models/array_test.rb, samples/client/petstore/ruby/lib/petstore/models/cat.rb, samples/client/petstore/ruby/lib/petstore/models/category.rb, samples/client/petstore/ruby/lib/petstore/models/client.rb, samples/client/petstore/ruby/lib/petstore/models/dog.rb, samples/client/petstore/ruby/lib/petstore/models/enum_arrays.rb, samples/client/petstore/ruby/lib/petstore/models/enum_test.rb, samples/client/petstore/ruby/lib/petstore/models/format_test.rb, samples/client/petstore/ruby/lib/petstore/models/has_only_read_only.rb, samples/client/petstore/ruby/lib/petstore/models/list.rb, samples/client/petstore/ruby/lib/petstore/models/map_test.rb, samples/client/petstore/ruby/lib/petstore/models/mixed_properties_and_additional_properties_class.rb, samples/client/petstore/ruby/lib/petstore/models/model_200_response.rb, samples/client/petstore/ruby/lib/petstore/models/model_return.rb, samples/client/petstore/ruby/lib/petstore/models/name.rb, samples/client/petstore/ruby/lib/petstore/models/number_only.rb, samples/client/petstore/ruby/lib/petstore/models/order.rb, samples/client/petstore/ruby/lib/petstore/models/pet.rb, samples/client/petstore/ruby/lib/petstore/models/read_only_first.rb, samples/client/petstore/ruby/lib/petstore/models/special_model_name.rb, samples/client/petstore/ruby/lib/petstore/models/tag.rb, samples/client/petstore/ruby/lib/petstore/models/user.rb
This regex causes a NameError in ruby clients when parsing nested anonymous objects.
```
NameError (wrong constant name String, Hash<String)
```
See issue for more details: https://github.com/swagger-api/swagger-codegen/issues/3880
=> Cgardens nested object regex

modules/swagger-codegen/src/main/resources/aspnet5/controller.mustache, samples/server/petstore/aspnet5/src/IO.Swagger/Controllers/PetApi.cs, samples/server/petstore/aspnet5/src/IO.Swagger/Controllers/StoreApi.cs, samples/server/petstore/aspnet5/src/IO.Swagger/Controllers/UserApi.cs, samples/server/petstore/aspnet5/src/IO.Swagger/Models/ApiResponse.cs, samples/server/petstore/aspnet5/src/IO.Swagger/Models/Category.cs, samples/server/petstore/aspnet5/src/IO.Swagger/Models/Order.cs, samples/server/petstore/aspnet5/src/IO.Swagger/Models/Pet.cs, samples/server/petstore/aspnet5/src/IO.Swagger/Models/Tag.cs, samples/server/petstore/aspnet5/src/IO.Swagger/Models/User.cs
This applies `basePath` to operations in aspnet5 generator. Previously, it assumed `basePath` could be applied globally (e.g. `additionalProperties`) rather than per-operation.
This PR moves `basePath` from the class definition's `RouteAttribute` to the existing operation route definition.
=> [aspnet5] Fix basePath application to operations

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FlaskConnexionCodegen.java, samples/server/petstore/flaskConnexion/swagger/swagger.yaml
If no tag is provided, python flask generator produces incorrect controller (default_controller_controller.py), which is fixed by this PR by generating `default_controller.py` instead.
Ref: https://github.com/swagger-api/swagger-codegen/issues/3786
=> [Python][Flask] fix python flask controller issue without tag

.gitignore, modules/swagger-codegen-cli/pom.xml, modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/SwaggerCodegen.java, modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/cmd/Meta.java, modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/cmd/Version.java, modules/swagger-codegen-cli/src/main/resources/version.properties
(Second PR, after fixing issues with my account email references)
This is as per discussed in #3007. I am using maven resources filtering support to generate a resource file with the ${project.version} stamped on it.
Please note when running (from example from an IDE) from a non-maven env. this will lead to the 
version be the literal `unset` string.
=> Add a new cli command to output version information (2nd attempt) #3892

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/CodegenTest.java, modules/swagger-codegen/src/test/resources/2_0/allOfTest.yaml
Also adds a supportMixins property for languages that support mixins/multiple inheritance.
Fix #3629 #3544 #3474 #3636
=> [All] Fix some inheritance/composition issues and add allOf unit tests

modules/swagger-codegen/src/main/resources/JavaJaxRS/resteasy/api.mustache, modules/swagger-codegen/src/main/resources/JavaJaxRS/resteasy/gradle.mustache, modules/swagger-codegen/src/main/resources/JavaJaxRS/resteasy/pom.mustache, samples/server/petstore/jaxrs-resteasy/default/build.gradle, samples/server/petstore/jaxrs-resteasy/default/pom.xml, samples/server/petstore/jaxrs-resteasy/default/src/gen/java/io/swagger/api/PetApi.java, samples/server/petstore/jaxrs-resteasy/default/src/gen/java/io/swagger/api/PetApiService.java, samples/server/petstore/jaxrs-resteasy/default/src/gen/java/io/swagger/api/StoreApi.java, samples/server/petstore/jaxrs-resteasy/default/src/gen/java/io/swagger/api/UserApi.java, samples/server/petstore/jaxrs-resteasy/joda/build.gradle, samples/server/petstore/jaxrs-resteasy/joda/pom.xml, samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/io/swagger/api/PetApi.java, samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/io/swagger/api/StoreApi.java, samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/io/swagger/api/UserApi.java, samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/io/swagger/model/Category.java, samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/io/swagger/model/ModelApiResponse.java, samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/io/swagger/model/Order.java, samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/io/swagger/model/Pet.java, samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/io/swagger/model/Tag.java, samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/io/swagger/model/User.java
The annotations should now appear on generated resteasy API classes.
=> Update JavaJaxRS/resteasy/api.mustache to have swagger annotations

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AndroidClientCodegen.java, modules/swagger-codegen/src/main/resources/android/libraries/volley/model.mustache, modules/swagger-codegen/src/test/java/io/swagger/codegen/android/AndroidClientOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/AndroidClientOptionsProvider.java, samples/client/petstore/android/volley/docs/PetApi.md, samples/client/petstore/android/volley/src/main/java/io/swagger/client/api/PetApi.java, samples/client/petstore/android/volley/src/main/java/io/swagger/client/model/Category.java, samples/client/petstore/android/volley/src/main/java/io/swagger/client/model/Order.java, samples/client/petstore/android/volley/src/main/java/io/swagger/client/model/Pet.java, samples/client/petstore/android/volley/src/main/java/io/swagger/client/model/Tag.java, samples/client/petstore/android/volley/src/main/java/io/swagger/client/model/User.java
Add `serializeModel` support to Android, e.g.
```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
-i modules/swagger-codegen/src/test/resources/2_0/petstore.yaml \
-l android -DserializableModel=true \
-o /var/tmp/android/serializableModel2/ 
```
=> [Android][Volley] add serializeModel support to Android

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwiftCodegen.java
Add support for number enum value.
https://github.com/swagger-api/swagger-codegen/issues/3934
=> [Swift] support number value for enum

modules/swagger-codegen/src/main/resources/python/model.mustache, samples/client/petstore/python/petstore_api/models/enum_arrays.py, samples/client/petstore/python/petstore_api/models/format_test.py, samples/client/petstore/python/petstore_api/models/map_test.py, samples/client/petstore/python/petstore_api/rest.py, samples/client/petstore/ruby/docs/FakeApi.md, samples/client/petstore/ruby/lib/petstore/api/fake_api.rb
Swagger ignores 'required' tag in model.mustache in python.
The setter function for these properties does not allow null values, unlike ruby and other languages
Issue: https://github.com/swagger-api/swagger-codegen/issues/3922
=> required tag is used in model, allows null values

modules/swagger-codegen/src/main/resources/python/model.mustache, samples/client/petstore/python/petstore_api/models/animal.py, samples/client/petstore/python/petstore_api/models/cat.py, samples/client/petstore/python/petstore_api/models/dog.py, samples/client/petstore/python/petstore_api/models/format_test.py, samples/client/petstore/python/petstore_api/models/name.py, samples/client/petstore/python/petstore_api/models/pet.py
- fix python required property check
- fix validation for optional properties
=> [Python] fix python required property check and validation for optional properties

.gitignore, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AspNet5ServerCodegen.java, modules/swagger-codegen/src/main/resources/aspnet5/Project.xproj.mustache, modules/swagger-codegen/src/main/resources/aspnet5/Solution.mustache, samples/server/petstore/aspnet5/IO.Swagger.sln, samples/server/petstore/aspnet5/README.md, samples/server/petstore/aspnet5/src/IO.Swagger/Dockerfile, samples/server/petstore/aspnet5/src/IO.Swagger/IO.Swagger.xproj
The AspNet5 generator was originally written to support project.json.
The Project.xproj was implemented without a valid project guid or root
namespace. During the transition period from project.json to
Project.xproj, VS2015 would fallback to project.json. Newer versions of
VS2015 don't seem to do this any longer.
This commit defines the project's guid correctly, and sets the project's
root namespace.
See: #3680
=> [aspnet] Fix .sln/.xproj guids

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ObjcClientCodegen.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/objc/ObjcModelTest.java
fixes https://github.com/swagger-api/swagger-codegen/issues/2208
Fixes Objective-C generation of maps via additionalProperties, to create a string-to-object map. The JSON Mapping library used by the generated code, JSONModel, see https://github.com/jsonmodel/jsonmodel/issues/341
=> 2208 fix Objc Mapping Generation

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaJAXRSCXFCDIServerCodegen.java, modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf-cdi/apiServiceImpl.mustache, modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf-cdi/pom.mustache, samples/server/petstore/jaxrs-cxf-cdi/pom.xml, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/io/swagger/api/PetApiService.java, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/io/swagger/api/StoreApiService.java, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/io/swagger/api/UserApiService.java, samples/server/petstore/jaxrs-cxf-cdi/src/main/java/io/swagger/api/impl/PetApiServiceImpl.java, samples/server/petstore/jaxrs-cxf-cdi/src/main/java/io/swagger/api/impl/StoreApiServiceImpl.java, samples/server/petstore/jaxrs-cxf-cdi/src/main/java/io/swagger/api/impl/UserApiServiceImpl.java
For jaxrs-cxf-cdi, add `pom.xml` template, fix a bug, and update samples.
=> jaxrs-cxf-cdi POM template

modules/swagger-codegen/src/main/resources/php/ApiClient.mustache, modules/swagger-codegen/src/main/resources/php/ApiException.mustache, modules/swagger-codegen/src/main/resources/php/ObjectSerializer.mustache, modules/swagger-codegen/src/main/resources/php/api.mustache, modules/swagger-codegen/src/main/resources/php/api_test.mustache, modules/swagger-codegen/src/main/resources/php/configuration.mustache, modules/swagger-codegen/src/main/resources/php/model.mustache, modules/swagger-codegen/src/main/resources/php/model_generic.mustache
This is a fix for #3867 which tries to significantly improve PHP client's code quality using insights offered by PHPStorm's inspections (including built-in inspections, [EA Extended](https://plugins.jetbrains.com/plugin/7622?pr=idea),  [PHP Mess Detector](https://phpmd.org/), [PHP CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer), etc).
WIP
=> [WIP] Improve PHP client emitted code quality

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwiftCodegen.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/swift/SwiftCodegenTest.java
- Added support for generating appropriate enum names for values with '/' in them
=> [Swift] Add / as enum separator

modules/swagger-codegen/src/main/resources/objc/ApiClient-body.mustache, modules/swagger-codegen/src/main/resources/objc/Configuration-protocol.mustache, modules/swagger-codegen/src/main/resources/objc/DefaultConfiguration-body.mustache, samples/client/petstore/objc/default/SwaggerClient/Core/SWGApiClient.m, samples/client/petstore/objc/default/SwaggerClient/Core/SWGConfiguration.h, samples/client/petstore/objc/default/SwaggerClient/Core/SWGDefaultConfiguration.m
There are several issues with the security policy:
* The security policy is created with `AFSSLPinningModeNone` which means that even if pinned certificates are set (if config.sslCaCert is not nil), they will be ignored. Pinning will not work at all with this security policy.
* The configuration wrapper for the security policy is a bad idea.
* `verifySSL` controls both invalid certificates and domain validation. A vanilla `AFSecurityPolicy` clearly exposes both `allowInvalidCertificates` and `validatesDomainName`.
* `sslCaCert` only allows for a single pinned certificate. A vanilla `AFSecurityPolicy` clearly exposes a set of pinned certificates and makes it very convenient to load them with either `+[AFSecurityPolicy policyWithPinningMode:]` or `+[AFSecurityPolicy certificatesInBundle:]` …
=> [objc] Remove the custom security policy

modules/swagger-codegen/src/main/resources/python/api_client.mustache, samples/client/petstore/python/petstore_api/api_client.py
In Python, tuples are fixed size in nature whereas lists are dynamic. So they should be sanitized as same as lists. Failure case here is when you have a query or post parameter as Datetime.
=> Sanitize tuples properly

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ConfluenceWikiGenerator.java, modules/swagger-codegen/src/main/resources/confluenceWikiDocs/index.mustache, modules/swagger-codegen/src/main/resources/htmlDocs/index.mustache, samples/documentation/cwiki/confluence-markup.txt, samples/html/index.html
Should be `hasHeaderParams` instead of `hasHeaderParam`
=> Fix hasHeaderParams mustache tag

modules/swagger-codegen/src/main/resources/htmlDocs2/index.mustache, samples/html2/index.html
=> Updates to html2 templates to use security headers in curl examples

modules/swagger-codegen/src/main/resources/android/apiInvoker.mustache, modules/swagger-codegen/src/main/resources/android/libraries/volley/apiInvoker.mustache, samples/client/petstore/android/httpclient/src/main/java/io/swagger/client/ApiInvoker.java, samples/client/petstore/android/volley/src/main/java/io/swagger/client/ApiInvoker.java
To fix https://github.com/swagger-api/swagger-codegen/issues/3406, https://github.com/swagger-api/swagger-codegen/issues/3202
=> [Android] fix URL encoding for Android API client

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java, modules/swagger-codegen/src/main/resources/Java/pojo.mustache, modules/swagger-codegen/src/test/java/io/swagger/codegen/java/JavaClientOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/JavaClientOptionsProvider.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/JavaOptionsProvider.java
Add `supportJava6` flag to remove equals and hashCode methods in the model as these methods are not compatible with Java6.
=> [Java][jersey1] add Java6 support to Java (jersey1) API client

bin/swift3-petstore-promisekit.sh, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Swift3Codegen.java
- [ x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
Swift3 wasn't building correctly when specifying a language of "swift3" - it was still building the swift …
=> fix some swift3 references

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java, modules/swagger-codegen/src/main/resources/csharp/README.mustache, modules/swagger-codegen/src/main/resources/csharp/api.mustache, modules/swagger-codegen/src/main/resources/csharp/api_doc.mustache, modules/swagger-codegen/src/main/resources/csharp/api_test.mustache, modules/swagger-codegen/src/main/resources/csharp/model.mustache, modules/swagger-codegen/src/main/resources/csharp/model_doc.mustache, modules/swagger-codegen/src/main/resources/csharp/model_test.mustache, samples/client/petstore/csharp/SwaggerClient/IO.Swagger.sln, samples/client/petstore/csharp/SwaggerClient/build.bat, samples/client/petstore/csharp/SwaggerClient/docs/FakeApi.md, samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/Api/FakeApi.cs, samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/IO.Swagger.csproj
The apiPackage, modelPackage, and excludeTests values were not being
populated correctly from external configs (passing -c filename to
generator).
This commit allows those properties to work correctly with the Csharp
client generator. Previously the Api and Model namespaces were hard
coded after additionalProperties for these were evaluated.
The files which generate test files for models and api classes
didn't honor the excludeTests option.
see #3993, #3961
=> [csharp] Fix apiPackage,modelPackage,excludeTests

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java, modules/swagger-codegen/src/main/resources/Java/model.mustache
Improvements based on feedbacks in #3568
=> [Java][jersey1] improvements based on #3568

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SinatraServerCodegen.java
Fix reserved word handling in model file name for Sinatra
(for https://github.com/swagger-api/swagger-codegen/issues/3846)
=> [Ruby][Sinatra] Fix reserved word handling in model file name

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java
To keep consistency between `sourceFolder` and `testFolder` access
=> [java] Allow setting test folder

modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
Java6 compatibility is being added via supportJava6 option. This PR makes a small change to Jersey2 to replace usage of Java 7 class java.nio.file.Files with reference to Apache commons.io.FileUtils. 
I'm not sure exactly how to manage the additional dependency for commons io. Originally I saw it as part of swagger-codegen but of course that is only for the generation process. I doubt we want to add it as a dependency on the swagger runtime code, are you happy for it be up to users of supportJava6 to add manually?
=> Add Java6 compatibility for Jersey2

modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/build.gradle.mustache, modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/build.sbt.mustache, modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/pom.mustache, modules/swagger-codegen/src/main/resources/Java/model.mustache, modules/swagger-codegen/src/main/resources/Java/pojo.mustache, modules/swagger-codegen/src/main/resources/Java/pom.mustache
We are working with jdk6 and jersey2 at the moment and cannot use jdk7 generated classes. I have reused 'supportJava6' flag as a switch to make some changes to the templates, so, apache commons libs can be used instead. I have changed pom, gradle and sbt as well.
=> hashCode and equals support for jdk6 for jersey2

modules/swagger-codegen/src/main/resources/nancyfx/parameters.mustache, samples/server/petstore/nancyfx/IO.Swagger.sln, samples/server/petstore/nancyfx/src/IO.Swagger/IO.Swagger.csproj, samples/server/petstore/nancyfx/src/IO.Swagger/Models/ApiResponse.cs, samples/server/petstore/nancyfx/src/IO.Swagger/Models/Category.cs, samples/server/petstore/nancyfx/src/IO.Swagger/Models/Order.cs, samples/server/petstore/nancyfx/src/IO.Swagger/Models/Pet.cs, samples/server/petstore/nancyfx/src/IO.Swagger/Models/Tag.cs, samples/server/petstore/nancyfx/src/IO.Swagger/Models/User.cs, samples/server/petstore/nancyfx/src/IO.Swagger/Utils/Parameters.cs
parser needs to access the Value parameter to enable the direct cast at Util/Parameters.cs:line 102 when handling string parameters
=> fix NancyFX string parser

modules/swagger-codegen/src/main/resources/qt5cpp/HttpRequest.cpp.mustache, modules/swagger-codegen/src/main/resources/qt5cpp/api-body.mustache, modules/swagger-codegen/src/main/resources/qt5cpp/helpers-body.mustache, modules/swagger-codegen/src/main/resources/qt5cpp/model-body.mustache, modules/swagger-codegen/src/main/resources/qt5cpp/model-header.mustache, modules/swagger-codegen/src/main/resources/qt5cpp/modelFactory.mustache, modules/swagger-codegen/src/main/resources/qt5cpp/object.mustache, samples/client/petstore/qt5cpp/client/SWGApiResponse.cpp, samples/client/petstore/qt5cpp/client/SWGApiResponse.h, samples/client/petstore/qt5cpp/client/SWGCategory.cpp, samples/client/petstore/qt5cpp/client/SWGCategory.h, samples/client/petstore/qt5cpp/client/SWGHelpers.cpp, samples/client/petstore/qt5cpp/client/SWGHttpRequest.cpp, samples/client/petstore/qt5cpp/client/SWGModelFactory.h, samples/client/petstore/qt5cpp/client/SWGObject.h, samples/client/petstore/qt5cpp/client/SWGOrder.cpp, samples/client/petstore/qt5cpp/client/SWGOrder.h, samples/client/petstore/qt5cpp/client/SWGPet.cpp, samples/client/petstore/qt5cpp/client/SWGPet.h, samples/client/petstore/qt5cpp/client/SWGPetApi.cpp, samples/client/petstore/qt5cpp/client/SWGTag.cpp, samples/client/petstore/qt5cpp/client/SWGTag.h, samples/client/petstore/qt5cpp/client/SWGUser.cpp, samples/client/petstore/qt5cpp/client/SWGUser.h
Modified the mustache files to take into account arrays that are not based on complex types bur languages specific types as explained in #3410
=> [Qt5/C++] Arrays of primitive types fix

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/CodegenTest.java
**I've run bin/run-all-petstore but there are lots of unrelated changes, and in a glance I could not see any change related to this PR. I am just guessing petstore samples are out of date. Let me know if you want me to add those (huge) changes.**
I've changed the pattern sanitizeTag uses to remove invalid characters and also added underscore to tags starting with a number. Also added some test cases.
fixes #2657
=> Fix sanitizeTag to retain numbers and underscore in tag names

modules/swagger-codegen/src/main/resources/Javascript/api.mustache
I am unable to run `./bin/javascript-petstore.sh` and `./bin/security/javascript-petstore.sh` on Windows 10
Don't throw string literals but Error objects in JavaScript.
Fixes: #4054
=> Throw an Error object instead of a string

modules/swagger-codegen/src/main/resources/TypeScript-Fetch/api.mustache, samples/client/petstore/typescript-fetch/builds/default/api.ts, samples/client/petstore/typescript-fetch/builds/es6-target/api.ts, samples/client/petstore/typescript-fetch/builds/with-npm-version/api.ts
There was a typo, this is just about changing `FetchParamCreactor` to `FetchParamCreator`.
I've done it in the 2.3.0 branch as this is potentially a breaking change (people out there using the class `XFetchParamCreactor` will need to modify their code).
This was raised incorrectly in #4070.
=> [TypeScript Fetch] Fixes typo in `FetchParamCreactor`

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaJAXRSCXFCDIServerCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaMSF4JServerCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaResteasyServerCodegen.java
Fix outputFolder in Java-related server stub generators
=> [Java] Fix outputFolder in java-related server stub generators

modules/swagger-codegen/src/main/java/io/swagger/codegen/config/CodegenConfiguratorUtils.java, pom.xml
Fixes #4090 by updating to latest swagger-core (1.5.10) and parser snapshot (1.0.23-SNAPSHOT).  This should address the following issues:
#3614
#3347 
#3305
#1551
=> update parser, core versions

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/StaticHtml2Generator.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/StaticHtmlGenerator.java, samples/html/index.html, samples/html2/index.html
Newline escaping disabled for HTML and HTML2 generators. Escaping failing Markdown processors to work correctly on descriptions.
=> Newline escaping disabled for HTML and HTML2 generators

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/HaskellServantCodegen.java
- [ x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
This PR addresses an issue with the `haskell-servant` generator. The generator didn't account for the possibility of single character identifiers when applying `toUpper` and `toLower` casing rules. Calls to …
=> Fixed toUpper and toLower usage in haskell-servant gen.

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/java/JavaModelTest.java
The fix converts the first two letters of a property name to lower case if the property name started with two upper case letters.
Another way to handle the problem jackson has with uppercase properties would be to put the JsonProperty annotation to the getter methods.
=> bugfix: issue-4051

modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache, samples/client/petstore/typescript-angular2/default/api/PetApi.ts, samples/client/petstore/typescript-angular2/default/api/StoreApi.ts, samples/client/petstore/typescript-angular2/default/api/UserApi.ts, samples/client/petstore/typescript-angular2/npm/README.md, samples/client/petstore/typescript-angular2/npm/api/PetApi.ts, samples/client/petstore/typescript-angular2/npm/api/StoreApi.ts, samples/client/petstore/typescript-angular2/npm/api/UserApi.ts, samples/client/petstore/typescript-angular2/npm/package.json
Fixing #4037 : typescript-angular2\api.mustache: removed hardcoded "responseType: ResponseContentType.Json" in requestOption (not valid for HHTP 204), added copying extraHttpRequestParams to requestOption.
=> fixing issue#4037 - ts ng2 response type is always json

google_checkstyle.xml, pom.xml
Add Checkstyle to the Maven build, reporting noncompliance, but not enforcing style.
=> Add Checkstyle to POM with Google settings advice

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenOperation.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java, modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/api.mustache, modules/swagger-codegen/src/test/java/io/swagger/codegen/languages/JavaClientCodegenTest.java, modules/swagger-codegen/src/test/resources/2_0/petstore-vendor-mime.yaml, samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/api/FakeApi.java, samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/api/PetApi.java
This provides support for handling vendor-mime-types (application/vnd. ... +json) in retrofit2
With Retrofit2, it addes Headers annotation with selected Content-Type. 
Given, a swagger operation consumes definition
....
consumes:
- application/vnd.mycompany.v1+json
- application/xml
....
it generates following snippet for retrofit2 client,
@Headers({
"Content-Type:application/vnd.mycompany.v1+json" 
})
@POST("pet")
Call<Void> addPet(
@retrofit2.http.Body Pet body
);
This includes unit test and also tested with https://travis-ci.org
This fixes the issue #3918
=> Vendor Mime-type support in retrofit2

modules/swagger-codegen/src/main/resources/JavaSpring/pojo.mustache, samples/client/petstore/spring-cloud/src/main/java/io/swagger/api/PetApi.java, samples/client/petstore/spring-stubs/src/main/java/io/swagger/api/PetApi.java, samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/api/FakeApi.java, samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/api/PetApi.java, samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/model/HasOnlyReadOnly.java, samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/model/Name.java, samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/model/ReadOnlyFirst.java, samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/FakeApi.java, samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/FakeApiController.java, samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/PetApi.java, samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/PetApiController.java, samples/server/petstore/spring-mvc/src/main/java/io/swagger/model/HasOnlyReadOnly.java, samples/server/petstore/spring-mvc/src/main/java/io/swagger/model/Name.java, samples/server/petstore/spring-mvc/src/main/java/io/swagger/model/ReadOnlyFirst.java, samples/server/petstore/springboot/src/main/java/io/swagger/api/FakeApi.java, samples/server/petstore/springboot/src/main/java/io/swagger/api/FakeApiController.java, samples/server/petstore/springboot/src/main/java/io/swagger/api/PetApi.java, samples/server/petstore/springboot/src/main/java/io/swagger/api/PetApiController.java, samples/server/petstore/springboot/src/main/java/io/swagger/model/HasOnlyReadOnly.java, samples/server/petstore/springboot/src/main/java/io/swagger/model/Name.java, samples/server/petstore/springboot/src/main/java/io/swagger/model/ReadOnlyFirst.java
Add back setter to read-only attributes in Spring models
For https://github.com/swagger-api/swagger-codegen/issues/3793
=> [Spring] add back setter to read-only attributes in Spring models

modules/swagger-codegen/src/main/resources/nancyfx/api.mustache, modules/swagger-codegen/src/main/resources/nancyfx/parameters.mustache, samples/server/petstore/nancyfx/IO.Swagger.sln, samples/server/petstore/nancyfx/src/IO.Swagger/IO.Swagger.csproj, samples/server/petstore/nancyfx/src/IO.Swagger/Modules/PetModule.cs, samples/server/petstore/nancyfx/src/IO.Swagger/Utils/Parameters.cs
Resubmitting changes from #4061 cleaned up and on a separate branch
=> Nancy fx work

modules/swagger-codegen/src/main/resources/dart/api.mustache, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/DartClientOptionsProvider.java, samples/client/petstore/dart/swagger/lib/api/pet_api.dart, samples/client/petstore/dart/swagger/lib/api/store_api.dart, samples/client/petstore/dart/swagger/lib/api/user_api.dart
Removed the somewhat awkward 'justIgnoreThisFlag' flag. The generated code is shorter and more beautiful.
=> DART: Removed the 'justIgnoreThisFlag' flag

modules/swagger-codegen/src/main/resources/objc/ApiClient-header.mustache, modules/swagger-codegen/src/main/resources/objc/Configuration-header.mustache, modules/swagger-codegen/src/main/resources/objc/ResponseDeserializer-header.mustache, samples/client/petstore/objc/default/SwaggerClient/Core/SWGApiClient.h, samples/client/petstore/objc/default/SwaggerClient/Core/SWGConfiguration.h, samples/client/petstore/objc/default/SwaggerClient/Core/SWGResponseDeserializer.h
Fixes for misplaced and missed parameter names in Obj-C code. 
That is minor fix, so I decide not to open a new issue.
=> [Obj-c] Generated code documentation fixes

modules/swagger-codegen/src/main/resources/Javascript/partial_model_enum_class.mustache, samples/client/petstore/javascript-promise/src/model/EnumClass.js, samples/client/petstore/javascript/src/model/EnumClass.js
Generated code calls constructFromObject on enum types, but enum did not define the necessary function. Returns the value of the enum.
=> Add constructFromObject to Javascript enum generation.

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AspNet5ServerCodegen.java
When I opened #4011, I seem to have forgotten to point the deprecated aspnet5 generator to the renamed aspnetcore directory.
This is a one-line change to point to that renamed directory.
This can be tested by running the same code in `./bin/aspnetcore-petstore-server.sh` but changing the language to the deprecated `aspnet5`.
See #4121.
=> [aspnet5] Fix broken template directory for deprecated lang

modules/swagger-codegen-maven-plugin/src/main/java/io/swagger/codegen/plugin/CodeGenMojo.java
Fallback to "src/main/java" for added source folder instead of a NullpointerException when no source folder ist configured in the pom
=> Default sourceFolder to src/main/java

modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/enumClass.mustache, modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/pojo.mustache, samples/server/petstore/jaxrs-cxf/gen/java/io/swagger/model/Category.java, samples/server/petstore/jaxrs-cxf/gen/java/io/swagger/model/ModelApiResponse.java, samples/server/petstore/jaxrs-cxf/gen/java/io/swagger/model/Order.java, samples/server/petstore/jaxrs-cxf/gen/java/io/swagger/model/Pet.java, samples/server/petstore/jaxrs-cxf/gen/java/io/swagger/model/Tag.java, samples/server/petstore/jaxrs-cxf/gen/java/io/swagger/model/User.java
Fixes #4045
JAXRS-CXF:
- Fixed enum marshalling & fromValue() for lowercase enum values
- Added toString() to enums
=> [JAXRS-CXF] Issue 4045 - Fixed enum marshalling & fromValue()

modules/swagger-codegen/src/main/resources/objc/model-body.mustache, modules/swagger-codegen/src/main/resources/objc/podspec.mustache, samples/client/petstore/objc/default/SwaggerClient/Model/SWGCategory.m, samples/client/petstore/objc/default/SwaggerClient/Model/SWGOrder.m, samples/client/petstore/objc/default/SwaggerClient/Model/SWGPet.m, samples/client/petstore/objc/default/SwaggerClient/Model/SWGTag.m, samples/client/petstore/objc/default/SwaggerClient/Model/SWGUser.m
Replaced deprecated call `-[JSONKeyMapper initWithDictionary:]` with `-[JSONKeyMapper initWithModelToJSONDictionary:]`, inverting keys and values of dictionary as required.
=> [ObjC] Fix deprecated JSONModel API usage

modules/swagger-codegen/src/main/resources/python/api_client.mustache, samples/client/petstore/python/petstore_api/api_client.py
select_header_content_type in generated python client's api_client prefers application/json if it is in the list of content types. But the list may content */* that means server accepts any content-type. In that case we should still prefer application/json content type.
=> Select application/json content-type in python generated client, if */* is in the list of content-types

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java, modules/swagger-codegen/src/main/resources/dart/apilib.mustache
Fixes #4117. I'm not sure if this is a proper fix. I tested it for dart only.
=> DART: multi-word class names work properly now, fixes #4117

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/resources/ruby/api_client.mustache, modules/swagger-codegen/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml, samples/client/petstore/ruby/docs/FakeApi.md, samples/client/petstore/ruby/lib/petstore/api/fake_api.rb, samples/client/petstore/ruby/lib/petstore/api_client.rb
Better handling of */* (to avoid code injection update)
To fix https://github.com/swagger-api/swagger-codegen/issues/4151
=> Better handling of */*

modules/swagger-codegen/src/main/resources/dart/api_client.mustache, modules/swagger-codegen/src/main/resources/dart/api_helper.mustache, modules/swagger-codegen/src/main/resources/dart/apilib.mustache, modules/swagger-codegen/src/main/resources/dart/pubspec.mustache, samples/client/petstore/dart/swagger/lib/api.dart, samples/client/petstore/dart/swagger/lib/api_client.dart, samples/client/petstore/dart/swagger/lib/api_helper.dart, samples/client/petstore/dart/swagger/pubspec.yaml
Dates for parameters were sent by using DateTime#toString. This would give us a date of the format "2016-11-08 14:33:37.270". Now I changed it to use DateTime#toIso8601String to give us a value like "2016-11-08T14:34:29.520". There were functions to format the date correctly, but those were not used anymore, which is why I assume that ISO8601 should have been used in the first place.
In other news, I decided not to use the provided code which relied on the intl package to format a ISO 8601, but a function from the DateTime class in core, thereby eliminating the necessity for using the external "intl" library.
=> fix[dart]: send ISO8601 dates

modules/swagger-codegen/src/main/resources/python/api.mustache, modules/swagger-codegen/src/main/resources/python/api_client.mustache, modules/swagger-codegen/src/main/resources/python/rest.mustache, samples/client/petstore/python/docs/FakeApi.md, samples/client/petstore/python/petstore_api/api_client.py, samples/client/petstore/python/petstore_api/apis/fake_api.py, samples/client/petstore/python/petstore_api/apis/pet_api.py, samples/client/petstore/python/petstore_api/apis/store_api.py, samples/client/petstore/python/petstore_api/apis/user_api.py, samples/client/petstore/python/petstore_api/rest.py
In order to support streaming responses, we need the API Client not to read response content and return a Response object. urllib3 has a flag called preload_content that if set to False, it will return a urllib3.HTTPResponse. This PR add support for this flag in rest client and api client and generated api classes. The flag is optional and defaulted to True to keep current behavior.
=> Support _preload_content flag in python client

samples/client/petstore/python/tests/test_pet_api.py
=> testcase for _preload_content flag

modules/swagger-codegen/src/main/resources/ruby/api_error.mustache, samples/client/petstore/ruby/lib/petstore/api_error.rb, samples/client/petstore/ruby/spec/api_error_spec.rb
Rewrite the logic in ruby client's `ApiError` class to always call `super` so that some information is guaranteed to be included.
https://github.com/swagger-api/swagger-codegen/issues/4167
=> [ruby] Make sure super is always called for ApiError class.

modules/swagger-codegen/src/main/resources/python/api.mustache, modules/swagger-codegen/src/main/resources/python/api_client.mustache, modules/swagger-codegen/src/main/resources/python/rest.mustache, samples/client/petstore/python/petstore_api/api_client.py, samples/client/petstore/python/petstore_api/apis/fake_api.py, samples/client/petstore/python/petstore_api/apis/pet_api.py, samples/client/petstore/python/petstore_api/apis/store_api.py, samples/client/petstore/python/petstore_api/apis/user_api.py, samples/client/petstore/python/petstore_api/rest.py, samples/client/petstore/python/tests/test_pet_api.py
Similar to #4166 adding support for a timeout flag called _request_timeout.
fixes #4169
=> [Python] Add support for request timeout

modules/swagger-codegen/src/main/resources/objc/ApiClient-body.mustache, modules/swagger-codegen/src/main/resources/objc/podspec.mustache, samples/client/petstore/objc/default/SwaggerClient.podspec, samples/client/petstore/objc/default/SwaggerClient/Core/SWGApiClient.m
Current version of generated code produces a warning: `Incompatible pointer types sending 'NSArray *' to parameter of type 'NSSet<NSData *> * _Nullable'`
This PR updates AFNetworking API usage according to this commit: https://github.com/AFNetworking/AFNetworking/commit/352f8515498c748c260561cbd3a990a00b0b05ab
=> [ObjC] AFNetworking pinnedCertificates API usage fix

modules/swagger-codegen-maven-plugin/src/main/java/io/swagger/codegen/plugin/CodeGenMojo.java
Simply pass through gitUseID and gitRepoID to the generator.
=> Add gitUseID and gitRepoID flags to maven plugin

modules/swagger-codegen/src/main/resources/htmlDocs2/index.mustache, modules/swagger-codegen/src/main/resources/htmlDocs2/js_jsonschemaview.mustache, samples/html2/index.html
`enum` values were not being displayed in the **Parameters** section. Enums are now displayed next to the **Enums:** label, as a comma separated list.
I also cleaned up the HTML formatting if the index.mustache page, to make it easier to read and debug.
Lastly, I hid the **Schema** block below the response code, if no schema was defined. For example, when a 401 error is defined, if there's no `schema` specified, the empty schema tab and panel body below that header are no longer rendered. It was taking up a lot of vertical space having a bunch of empty schema blocks for each endpoint.
=> [html2] Add missing enums to parameters

modules/swagger-codegen/src/main/resources/python/rest.mustache, samples/client/petstore/python/petstore_api/rest.py
If you tried to do two parallel calls to the same API object in the Python client you would get an error from urllib3 connection pool:
> Connection pool is full, discarding connection: ***
Because the [default maxsize=1](https://github.com/shazow/urllib3/blob/f9409436f83aeb79fbaf090181cd81b784f1b8ce/urllib3/connectionpool.py#L162)
By defaulting to a higher maxsize we mitigate for the common use case where a user is running a couple of requests in parallel.
Ideally, in the future, this should be a configuration parameter together with the pool size.
=> Allow multiple requests in parallel in Python client

bin/jaxrs-cxf-cdi-petstore-server.sh, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaJAXRSCXFCDIServerCodegen.java, modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf-cdi/RestApplication.mustache, modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf-cdi/beans.mustache, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/io/swagger/api/PetApi.java, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/io/swagger/api/PetApiService.java, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/io/swagger/api/StoreApi.java, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/io/swagger/api/StoreApiService.java, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/io/swagger/api/UserApi.java, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/io/swagger/api/UserApiService.java, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/io/swagger/model/Category.java, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/io/swagger/model/ModelApiResponse.java, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/io/swagger/model/Order.java, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/io/swagger/model/Pet.java, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/io/swagger/model/Tag.java, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/io/swagger/model/User.java, samples/server/petstore/jaxrs-cxf-cdi/src/main/java/io/swagger/api/RestApplication.java, samples/server/petstore/jaxrs-cxf-cdi/src/main/java/io/swagger/api/impl/PetApiServiceImpl.java, samples/server/petstore/jaxrs-cxf-cdi/src/main/java/io/swagger/api/impl/StoreApiServiceImpl.java, samples/server/petstore/jaxrs-cxf-cdi/src/main/java/io/swagger/api/impl/UserApiServiceImpl.java, samples/server/petstore/jaxrs-cxf-cdi/src/main/webapp/WEB-INF/beans.xml, samples/server/petstore/jaxrs-cxf-cdi/swagger.json
Add a JAX-RS application, and beans.xml, so that this works on typical JavaEE 7.0 servers.  For example, code generated by this generator will now work directly upon deployment to IBM WAS Liberty, and IBM Bluemix.
=> jaxrs-cxf-cdi :: Add a basic JAX-RS Application and CDI fixes

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Swift3Codegen.java, samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/FakeAPI.swift, samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift, samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift, samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift, samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs/FakeAPI.swift, samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift, samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift, samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift, samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs/FakeAPI.swift, samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift, samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift, samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift
fix(swift3): rename reserved enum values
Example:
```diff
- case public = "public"
+ case _public = "public"
```
=> fix(swift3): rename reserved enum values

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SpringCodegen.java, samples/client/petstore/spring-cloud/src/main/java/io/swagger/api/PetApi.java, samples/client/petstore/spring-cloud/src/main/java/io/swagger/api/StoreApi.java, samples/client/petstore/spring-cloud/src/main/java/io/swagger/api/UserApi.java, samples/client/petstore/spring-stubs/src/main/java/io/swagger/api/PetApi.java, samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/api/FakeApi.java, samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/api/PetApi.java, samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/FakeApi.java, samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/FakeApiController.java, samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/PetApi.java, samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/PetApiController.java, samples/server/petstore/springboot/src/main/java/io/swagger/api/FakeApi.java, samples/server/petstore/springboot/src/main/java/io/swagger/api/FakeApiController.java, samples/server/petstore/springboot/src/main/java/io/swagger/api/PetApi.java, samples/server/petstore/springboot/src/main/java/io/swagger/api/PetApiController.java
Instead of basepath based grouping that is used by Spring boot/MVC
=> [Spring] Use tag operation grouping for spring-cloud

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenParameter.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenProperty.java
In the method copy of the class CodegenParameter, we make a copy of vendorExtensions map instead of copying the reference to prevent unwanted instance modification of a copied instance.
=> #3908 make a copy of vendorExtensions map instead of copying the reference

modules/swagger-codegen/src/main/resources/typescript-node/api.mustache, samples/client/petstore/typescript-node/default/api.ts, samples/client/petstore/typescript-node/npm/api.ts
Newer versions of typescript allow compiler flags to mark these are errors, so the generated code should not cause app code to break.
=> address unused parameters and possible-nullity warnings

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractTypeScriptClientCodegen.java
This fixes a part of #2456.  I made this change from the github editor, but can do the rest of the checklist steps tonight at my home.
=> [Typescript] Add Error to the list of reserved words that must be escaped 

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Swift3Codegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwiftCodegen.java
For https://github.com/swagger-api/swagger-codegen/issues/4208
=> [Swift] add ErrorResponse as reserved word in Swift generators

modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache, samples/client/petstore/typescript-angular2/default/api/PetApi.ts, samples/client/petstore/typescript-angular2/default/api/StoreApi.ts, samples/client/petstore/typescript-angular2/default/api/UserApi.ts, samples/client/petstore/typescript-angular2/npm/README.md, samples/client/petstore/typescript-angular2/npm/api/PetApi.ts, samples/client/petstore/typescript-angular2/npm/api/StoreApi.ts, samples/client/petstore/typescript-angular2/npm/api/UserApi.ts, samples/client/petstore/typescript-angular2/npm/package.json
- [ x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
This change allows consumers of the Angular2 TypeScript client to use the stricter `noImplicitAny: true` setting. 
This change will not have any affect on users with `noImplicityAny` turned off.
(details of the …
=> Allow TypeScript noImplicitAny: true

eclipse-formatter.xml, modules/swagger-codegen-cli/pom.xml, modules/swagger-codegen-maven-plugin/pom.xml, modules/swagger-codegen/pom.xml, modules/swagger-generator/pom.xml, pom.xml
More work towards our code style standards aim #3972.
Uses Eclipse formatting tools with a configuration matching Google's style guide (plus our customisations).
This brings in an appropriately configured Java formatter maven plugin, but doesn't *run* it as part of the build.  To manually run it:
`mvn formatter:format`
Having done this once, we fix ~2200 code style warnings.
```sh
➜  ~/Documents/Personal/swagger-codegen$ mvn clean compile | wc -l
3809
➜  ~/Documents/Personal/swagger-codegen$ mvn formatter:format | wc -l
80
➜  ~/Documents/Personal/swagger-codegen$ mvn clean compile | wc -l
1660
```
I haven't included the results of a run in this PR, as it would generate lots of merge conflicts... I'd suggest whoever merges this PR does a once-off formatter run.
=> Allow Java source formatting mvn formatter:format

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FlaskConnexionCodegen.java, samples/server/petstore/flaskConnexion-python2/controllers/pet_controller.py, samples/server/petstore/flaskConnexion-python2/test/test_pet_controller.py, samples/server/petstore/flaskConnexion/controllers/pet_controller.py, samples/server/petstore/flaskConnexion/test/test_pet_controller.py
Flask-connexion maps directly the param name in the swagger spec to the param name in the controller method so it must not be changed in the method during generation.
If santitization is needed then a warning log will be emitted.
=> [Flask] fix parameter naming

appveyor.yml
Disable Appveyor cache (which seems broken at the moment)
We'll re-enable it after the issue is fixed.
(without caching, the job probably needs more time to run)
=> Disable Appveyor cache (which seems broken)

.travis.objc_swift_test.yml
Add travis configuration file (.travis.objc_swift_test.yml) to test Objc/Swift clients
=> [ObjC][Swift] add travis configuration file to test Objc/Swift clients

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Swift3Codegen.java, samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/FakeAPI.swift, samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift, samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift, samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift
Supports multi-level inheritance to avoid having the variables from the parents of level > 2
This commit also fixes the comparison of the variables when skipping the variables in the children classes by only comparing their names (in some cases some parent variables were present in children classes)
=> fix(swift3): multi-level inheritance support

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Swift3Codegen.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/swift3/Swift3CodegenTest.java
- [x ] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.
We were checking to see if an enum name was reserved before actually performing the camelization that was going to be returned from the function which made it possible to still return a reserved word.
Added new tests …
=> [Swift3] make sure to camelize properly before checking for reserved words

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java
Default Generator's common variables needs to be initialized earlier during the generation process. 
This PR fixes issue https://github.com/swagger-api/swagger-codegen/issues/4297 by initializing common variables during configuration of generator properties.
=> Fix basePath set to null when generating API files.

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AndroidClientCodegen.java
Add "Object" as reserved keyword in Android generator (for https://github.com/swagger-api/swagger-codegen/issues/4279)
=> [Android] add Object as reserved keyword in Android generator

modules/swagger-codegen/src/test/java/io/swagger/codegen/javascript/JavaScriptModelEnumTest.java
While examining for usages of JavaClientCodegen, I saw it was used in a JavaScript test. I assume this was a typo.
NOTE: I ran ./bin/javascript-petstore.sh, and it did generate some extra bits. However, this PR doesn't actually touch any of that code, since it's just a test fix, so I did not include the results of this output.
=> Use JavaScript codegen in JavaScript test (instead of Java)

modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache, samples/client/petstore/typescript-angular2/default/api/PetApi.ts, samples/client/petstore/typescript-angular2/npm/README.md, samples/client/petstore/typescript-angular2/npm/api/PetApi.ts, samples/client/petstore/typescript-angular2/npm/package.json
=> Fix for missing headers

modules/swagger-codegen/src/main/resources/typescript-angular2/api.service.mustache, samples/client/petstore/typescript-angular2/default/api/pet.service.ts, samples/client/petstore/typescript-angular2/default/api/store.service.ts, samples/client/petstore/typescript-angular2/default/api/user.service.ts, samples/client/petstore/typescript-angular2/default/index.ts, samples/client/petstore/typescript-angular2/npm/README.md, samples/client/petstore/typescript-angular2/npm/api/pet.service.ts, samples/client/petstore/typescript-angular2/npm/api/store.service.ts, samples/client/petstore/typescript-angular2/npm/api/user.service.ts, samples/client/petstore/typescript-angular2/npm/configuration.ts, samples/client/petstore/typescript-angular2/npm/index.ts, samples/client/petstore/typescript-angular2/npm/package.json, samples/client/petstore/typescript-angular2/npm/tsconfig.json
Provides a fix for #4322 in `2.3.0`.
=> Fix for missing headers (2.3.0)

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java
When explicitly passing `--additional-properties=generatePropertyChanged=false` to the C# generator, Fody's PropertyChanged stuff was still randomly referenced or generated because `additionalProperties` still held a false value for the property used in templates (which is truthy in mustache)
Samples aren't regenerated because this option is more of an edge case and doesn't affect the C# client (`generatePropertyChanged` is not provided`) or the property-changed sample (`generatePropertyChanged` is set to true).
For more information, see #4206
=> [csharp] Remove generatePropertyChanged when explicitly false

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenParameter.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenProperty.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FlaskConnexionCodegen.java, samples/client/petstore/ruby/lib/petstore/api/fake_api.rb, samples/client/petstore/ruby/lib/petstore/api/store_api.rb, samples/client/petstore/ruby/lib/petstore/models/format_test.rb
Fix maximum, minimum for `Integer` by removing the trailing ".0" (which becomes double/decimal) and storing the value as string instead of Double/Number in Java.
=> Fix maximum, minimum for `Integer`

modules/swagger-codegen/src/main/resources/csharp/compile.mustache
Note: I'm not sure what all this is doing because I'm not that familiar with swagger-codegen, but it builds the build.bat fine. These .sh files did not run for me.
Fixed the build.bat file generation. I don't have the proper build tool chain setup for the build.sh file fix.
=> Fix for #4344 - update compile.mustache with new dependencies

modules/swagger-codegen/src/main/resources/TypeScript-Fetch/api.mustache, samples/client/petstore/typescript-fetch/builds/default/api.ts, samples/client/petstore/typescript-fetch/builds/default/pom.xml, samples/client/petstore/typescript-fetch/builds/es6-target/api.ts, samples/client/petstore/typescript-fetch/builds/es6-target/pom.xml, samples/client/petstore/typescript-fetch/builds/with-npm-version/api.ts, samples/client/petstore/typescript-fetch/builds/with-npm-version/pom.xml
- remove trailing space in TS Fetch template and update the sample so that `npm test` passes
- add `npm test` to pom.xml so that Travis will run it as part of the CI
=> [Typscript][Fetch] remove trailing space in TS Fetch template, add npm test to pom.xml

modules/swagger-codegen/src/main/resources/Java/pojo.mustache
The Java equals method does not call super.equals but directly returns true if the class has no own vars
=> Still respect super.equals even for models without own vars

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenModel.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenOperation.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenProperty.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FlaskConnexionCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/NodeJSServerCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Swift3Codegen.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/csharp/CSharpModelTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/go/GoModelTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/java/JavaModelTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/javascript/JavaScriptModelEnumTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/javascript/JavaScriptModelTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/objc/ObjcModelTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/php/PhpModelTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/python/PythonTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/scala/ScalaModelTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/swift/SwiftModelTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/swift3/Swift3ModelTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/typescript/fetch/TypeScriptFetchModelTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/typescript/typescriptangular/TypeScriptAngularModelTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/typescript/typescriptangular2/TypeScriptAngular2ModelTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/typescript/typescriptnode/TypeScriptNodeModelTest.java
There is no good reason to use Boolean instead of boolean.
Using Boolean will lead to handling "null" state which is confusing.
This change replaces Boolean properties to boolean.
=> Refactor Boolean properties to boolean in CodegenProperty, CodegenOperation and CodegenModel classes

README.md
README-only change.
Shine Solutions uses Swagger Codegen for building Swagger AEM https://github.com/shinesolutions/swagger-aem
=> Add Shine Solutions to list of companies using Swagger Codegen

appveyor.yml
For some reasons, `git clone` failed due to existing swagger-samples folder. Update appveyor config to delete the folder and comment out "cache"
=> Minor fix to issue with Appveyor

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java
com.my.Generator.class.toString() returns "class com.my.Generator", and this value is then used in the javax.annotation.Generated annotation like that: @Generated(value = "class com.my.Generator").
Should use Generator.class.getName() instead, so we end up with @Generated(value = "com.my.Generator")
=> fix the value for @Generated java annotation

modules/swagger-codegen/src/main/resources/android/enum_outer_doc.mustache
To fix https://github.com/swagger-api/swagger-codegen/issues/4350
=> [Android] add missing enum_outer_doc.mustache for android (volley)

modules/swagger-codegen/src/main/java/io/swagger/codegen/examples/ExampleGenerator.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/examples/XmlExampleGenerator.java
Removed time section from swagger date type in example generators.
Issue #4359
=> Issue #4359: Date type should not include time

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenOperation.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenProperty.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenResponse.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptNodeClientCodegen.java, modules/swagger-codegen/src/main/resources/typescript-node/api.mustache, modules/swagger-codegen/src/test/java/io/swagger/codegen/CodegenTest.java, modules/swagger-codegen/src/test/resources/2_0/fileResponseTest.json
- Closes #4034
- Add file response support for typescript-node client generator
Sorry for late action. I did try to treat both `binary` and `file` as `Buffer in Node.js`
However I could not find a good solution for it so I just make a PR for `file`.
=> add file response support

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractTypeScriptClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngular2ClientCodegen.java, modules/swagger-codegen/src/main/resources/typescript-angular2/model.mustache, modules/swagger-codegen/src/main/resources/typescript-angular2/modelEnum.mustache, modules/swagger-codegen/src/main/resources/typescript-angular2/modelGeneric.mustache, samples/client/petstore/typescript-angular2/default/api/PetApi.ts, samples/client/petstore/typescript-angular2/default/api/StoreApi.ts, samples/client/petstore/typescript-angular2/default/api/UserApi.ts
All changes target the typescript-angular2 language:
1. Add support to generate standalone enum models. This allows to reuse the same enums in multiple definitions or operations. Before this change, the generator would output an empty interface for the enum.
2. Improve primitive type detection when determining if we prefix the "models" namespace or not. For example, a custom model starting with "Error" would not get its namespace. Fixes #4182.
=> Support for standalone enums in Typescript-Angular2 and primitive type detection improvements

modules/swagger-codegen/src/main/java/io/swagger/codegen/config/CodegenConfigurator.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractTypeScriptClientCodegen.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/config/CodegenConfiguratorTest.java
For #4228 
Running the *petstore.sh scripts has unwanted result, it changed many files where it should not.  Any suggestion? 
These are a non-breaking changes.
##Changes:
Change the value types in additionalProperties and dynamicProperties to Object instead of String.
Change methods that insert values to these maps to use Object as the type of the value instead of String.
=> boolean values from JSON are treated as strings

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
CodegenResponse's isListContainer property is always false for "array" types. Don't know where the check for "list" comes from but in CodegenOperation, there's a check for "list" and "array".
No mustache file makes use of isListContainer inside responses yet, so this change does not change any existing behavior. Just to be sure I also ran php, java-all, cpprest petstore scripts to ensure this.
=> CodegenResponse.isListContainer is false for array types.

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java
Do not NPE on an array type with no "items". Just return null.
=> ISSUE-1388 - Do not NPE when array properties items are not specified

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java
To fix https://github.com/swagger-api/swagger-codegen/issues/4337
=> [C#] add "parameter" as reserved keyword

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java
Need to call out.close() after IOUtils.copy(in, out); when writing supporting files since IOUtils does not close the stream.
I'm using Java code generation in-process and I need to delete the generated files within the same VM they were created in. Since the streams are not closed I am unable to delete gradle\wrapper\gradle-wrapper.jar. Issue seen on a Windows 7 x64 system with Java 1.8.0_102.
=> Update DefaultGenerator.java to call close()

.gitignore, modules/swagger-codegen/src/main/resources/go/api.mustache, modules/swagger-codegen/src/main/resources/go/api_doc.mustache, samples/client/petstore/go/go-petstore/README.md, samples/client/petstore/go/go-petstore/docs/FakeApi.md, samples/client/petstore/go/go-petstore/docs/PetApi.md, samples/client/petstore/go/go-petstore/docs/StoreApi.md, samples/client/petstore/go/go-petstore/docs/UserApi.md, samples/client/petstore/go/go-petstore/fake_api.go, samples/client/petstore/go/go-petstore/pet_api.go, samples/client/petstore/go/go-petstore/store_api.go, samples/client/petstore/go/go-petstore/user_api.go, samples/client/petstore/go/pet_api_test.go
Add optional parameters to go client using map[string]interface{}
Add concurrency test.
=> Add optional parameters to go client using map[string]interface{}

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java
As described in #3285 .
In case you know a better way then `typeMapping.values().contains(name)` just tell it.
Best Regards,
Christian.
=> [JAVA] #3285 ModelNamePre- and Suffixes should not be applied to Types.

modules/swagger-codegen/src/main/java/io/swagger/codegen/examples/ExampleGenerator.java
fixes issue [[NODE-SERVER] Integer stub value not generated if format not defined](https://github.com/swagger-api/swagger-codegen/issues/4360)
- [x ] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.
Fixed an issue where properties specifying Integer as the type but not …
=> Fix Integer stub value defaulting to String in nodejs-server if format not specified

modules/swagger-codegen/src/main/resources/TypeScript-Fetch/api.mustache, samples/client/petstore/typescript-fetch/builds/default/api.ts, samples/client/petstore/typescript-fetch/builds/es6-target/api.ts, samples/client/petstore/typescript-fetch/builds/with-npm-version/api.ts
=> Fix typo. Creactor -> Creator

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/ignore/CodegenIgnoreProcessorTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/ignore/rules/FileRuleTest.java
Add missing tests for simple globbed ignore pattern which is not nested and not explicitly rooted...
See comment in `Rule.java`:
```
// case 1
//: If the pattern does not contain a slash '/', Git treats it as
//: a shell glob pattern and checks for a match against the
//: pathname relative to the location of the `.gitignore` file
//: (relative to the toplevel of the work tree if not from a
//: `.gitignore` file).
```
see #4452
=> [codegen ignore] normalize path separator for Windows, add *.ext tests

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java, modules/swagger-codegen/src/main/resources/csharp/modelGeneric.mustache
See #3608
This improves the defaults on constructor parameters by using `defaults(type)` rather than `null` for all inputs.
~~There seems to have been some weird usage of nullable types, possibly on parameters that aren't defined in the target swagger definition as nullable although I'm not 100% sure and didn't spend a lot of time investigating this.~~
Edit: I looked more closely and the nullable types seem to only occur when a primitive or enum is not marked as required. I had actually [previously explained this behavior for properties](https://github.com/swagger-api/swagger-codegen/issues/2885#issuecomment-220203786), but wasn't thinking broadly enough when I made comment about constructor parameters above.
This PR changes constructor parameters in models to:
1. Default to a default if …
=> [csharp] Use default rather than null in ctor

modules/swagger-codegen/src/main/resources/nancyfx/Project.mustache, modules/swagger-codegen/src/main/resources/nancyfx/packages.config.mustache, samples/server/petstore/nancyfx/IO.Swagger.sln, samples/server/petstore/nancyfx/src/IO.Swagger/IO.Swagger.csproj, samples/server/petstore/nancyfx/src/IO.Swagger/packages.config
Updating the Nancy reference to version 1.4.3 in the project and packages config mustache files
=> Updated Nancy from 1.4.1 to 1.4.3

modules/swagger-codegen/src/main/resources/php/ApiClient.mustache, modules/swagger-codegen/src/main/resources/php/configuration.mustache
- [√] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [√] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [√] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.
This PR adds a Curl Connect Timeout setting to generated PHP API clients.  This is desirable to prevent an app attempting to use a service that is down from hanging while waiting for a connection timeout.  Fixes #4499 …
=> #4499 Adding Curl connect timeout configuration to PHP generation templates

modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/JSON.mustache, modules/swagger-codegen/src/main/resources/Java/libraries/retrofit/ApiClient.mustache, modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/ApiClient.mustache, modules/swagger-codegen/src/main/resources/akka-scala/apiInvoker.mustache, samples/client/petstore-security-test/java/okhttp-gson/src/main/java/io/swagger/client/JSON.java, samples/client/petstore/akka-scala/src/main/scala/io/swagger/client/core/ApiInvoker.scala, samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/io/swagger/client/JSON.java, samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/JSON.java, samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/ApiClient.java, samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/ApiClient.java
The `DateTimeFormatter` returned by `ISODateTimeFormat.dateTime()` only parses dates with millisecond values, and throws `IllegalArgumentException` when milliseconds are not present.  The
date-time construct from RFC 3339 Section 5.6 referenced by the Swagger/OpenAPI spec allows fractional second values to be omitted.  This results in valid date-time values being rejected by the generated code.
This PR fixes the problem by using `ISODateTimeFormat.dateTimeParser()` for parsing, which correctly handles date-time values without fractional seconds.  Note that `.dateTime()` must
still be used for printing, which is not supported by `.dateTimeParser()`.
=> Fix Gson parsing of Joda DateTime without millis

modules/swagger-codegen/src/main/resources/swift3/api.mustache, samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/FakeAPI.swift, samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift, samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift, samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift, samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs/FakeAPI.swift, samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift, samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift, samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift, samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs/FakeAPI.swift, samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift, samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift, samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift
Made POST requests allow use query parameters, besides of body. Currently generated code ignores all query parameters when body exists. 
Reported in #2557 and also in #2483 
**Note**
This is a workaround of flawed Alamofire API which is actual limitation. Next time I will post a Alamofire-less template :)
=> [swift3] allow POST with both body and query parameters

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenResponse.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
- [ x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
Swagger-Codegen's CodegenResponse class did not support vendor extensions even though OpenAPI Spec supported it.  This change enables support for vendor extensions in CodegenResponse.
Issue #4022 has more details.
=> Enable support for vendor extensions in CodegenResponse.

modules/swagger-codegen/src/main/resources/scala/api.mustache, samples/client/petstore/scala/src/main/scala/io/swagger/client/api/PetApi.scala, samples/client/petstore/scala/src/main/scala/io/swagger/client/api/StoreApi.scala, samples/client/petstore/scala/src/main/scala/io/swagger/client/api/UserApi.scala
Use previously provided apiInvoker instead of creating a new instance at deserialisation stage
See issue #4532
=> Overriden objectmapper wasn't used in deserialisation (Scala) issue #4532

modules/swagger-codegen/src/main/java/io/swagger/codegen/AbstractGenerator.java
Enforce **UTF-8** encoding when reading mustache template files, similar to how **UTF-8** is enforced when the resulting files are written to disk. Fixes #4544.
=> When reading mustache template files assume UTF-8 encoding, fixes #4544.

modules/swagger-codegen/src/main/resources/JavaInflector/pojo.mustache, modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf-cdi/pojo.mustache, modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/pojo.mustache, modules/swagger-codegen/src/main/resources/JavaJaxRS/pojo.mustache, modules/swagger-codegen/src/main/resources/JavaJaxRS/resteasy/pojo.mustache, modules/swagger-codegen/src/main/resources/JavaJaxRS/spec/pojo.mustache, modules/swagger-codegen/src/main/resources/JavaSpring/pojo.mustache, modules/swagger-codegen/src/main/resources/MSF4J/pojo.mustache, modules/swagger-codegen/src/main/resources/undertow/pojo.mustache
This covers the usages that weren't fixed in #3825
Triple mustache is required because annotations may contain chars like
"=" that would be mistakenly encoded - see #3754
**Notes**
* Updating the samples didn't change anything in the servers. There were a bunch of unrelated changes to the client samples that belong in a separate commit/PR (mostly the addition of Capitalization.java)
* I'm almost certain that the changes to Mustache documented in #3754 will have broken other generators, but I don't even know where to begin looking for them.
=> Add triple-mustache to all instances of vendorExtensions.extraAnnotation

modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache, modules/swagger-codegen/src/main/resources/typescript-angular2/apis.mustache, modules/swagger-codegen/src/main/resources/typescript-angular2/variables.mustache, samples/client/petstore/typescript-angular2/default/api/PetApi.ts, samples/client/petstore/typescript-angular2/default/api/StoreApi.ts, samples/client/petstore/typescript-angular2/default/api/UserApi.ts, samples/client/petstore/typescript-angular2/default/api/api.ts, samples/client/petstore/typescript-angular2/default/variables.ts, samples/client/petstore/typescript-angular2/npm/README.md, samples/client/petstore/typescript-angular2/npm/api/PetApi.ts, samples/client/petstore/typescript-angular2/npm/api/StoreApi.ts, samples/client/petstore/typescript-angular2/npm/api/UserApi.ts, samples/client/petstore/typescript-angular2/npm/api/api.ts, samples/client/petstore/typescript-angular2/npm/package.json, samples/client/petstore/typescript-angular2/npm/variables.ts
Arrays are now serialized according to the different collection formats.
For collections of format "multi", all items are now appended to the parameter.
For all other formats, a string is constructed using Array.join(). The delimiter for this is read from a constant map exported by variables.ts.
All api classes are also exported in a const array to make handling of large api libraries easier.
[https://github.com/swagger-api/swagger-codegen/issues/4531](url)
=> Issue 4531

modules/swagger-codegen/src/main/resources/cpprest/apiclient-header.mustache, modules/swagger-codegen/src/main/resources/cpprest/apiclient-source.mustache, samples/client/petstore/cpprest/ApiClient.cpp, samples/client/petstore/cpprest/ApiClient.h, samples/client/petstore/cpprest/api/PetApi.cpp, samples/client/petstore/cpprest/api/PetApi.h, samples/client/petstore/cpprest/api/StoreApi.h, samples/client/petstore/cpprest/model/Category.cpp, samples/client/petstore/cpprest/model/Order.cpp, samples/client/petstore/cpprest/model/Pet.cpp, samples/client/petstore/cpprest/model/Pet.h, samples/client/petstore/cpprest/model/Tag.cpp, samples/client/petstore/cpprest/model/User.cpp
Signed-off-by: Gene Chang <gene.chang@anyconnect.com>
Added an overload in apiclient-header.mustache and apiclient-source.mustache files to parameterToString for utility:datetime.  It will use datetime.to_string to convert to ISO_8601.  This was tested by generating code from our swagger and verifying the datetime object is properly converted to a URL for the GET request on the server.
=> Added support for datetime query parameters in cpprest

bin/nancyfx-petstore-server.sh, modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConstants.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/NancyFXServerCodegen.java, modules/swagger-codegen/src/main/resources/csharp/api.mustache, modules/swagger-codegen/src/main/resources/nancyfx/api.mustache, modules/swagger-codegen/src/test/java/io/swagger/codegen/csharp/CSharpClientOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/CSharpClientOptionsProvider.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/NancyFXServerOptionsProvider.java
Per #4486, this allows user to specify the use of a standard or custom
prefix for interfaces. For C# based languages, this follows Microsoft's
Framework Design Guidelines and uses an I- prefix. However, to avoid
breaking changes with existing nancyfx generated code, the default is
unset.
The option supports true, false, or a custom prefix.
To test:
**NancyFX**:
```
./bin/nancyfx-petstore-server.sh --additional-properties interfacePrefix=I
```
NOTE: true/false don't apply here because there is no default set. This assumes NancyFX community preference is no prefix.
**C# Client**
```
./bin/csharp-petstore.sh --additional-properties interfacePrefix=true
./bin/csharp-petstore.sh --additional-properties interfacePrefix=false
./bin/csharp-petstore.sh --additional-properties interfacePrefix=ZZ …
```
=> [nancyfx/csharp] Customize interface prefix

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java
After merging the fix with another C# change, noticed case sensitivity
issue for the true/false checks. Also noticed my original implementation
wasn't setting the default I- prefix as intended. This commit resolves
those three issues.
#4557 added support for customizing the interface prefix used in NancyFX Server and C# Client generators. That implementation did a case sensitive comparison in the true and false checks. It also didn't set the default I prefix unless the `interfacePrefix` option was supplied.
In addition to the checks from the original PR:
```
./bin/csharp-petstore.sh --additional-properties interfacePrefix=true
./bin/csharp-petstore.sh --additional-properties interfacePrefix=false
./bin/csharp-petstore.sh --additional-properties interfacePrefix=ZZ
```
Also evaluate:
``` …
```
=> [csharp] Fix interfacePrefix sensitivity + default

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConstants.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java, modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache, modules/swagger-codegen/src/main/resources/csharp/ApiException.mustache, modules/swagger-codegen/src/main/resources/csharp/ApiResponse.mustache, modules/swagger-codegen/src/main/resources/csharp/Configuration.mustache, modules/swagger-codegen/src/main/resources/csharp/ExceptionFactory.mustache, modules/swagger-codegen/src/main/resources/csharp/IApiAccessor.mustache, modules/swagger-codegen/src/main/resources/csharp/api.mustache, modules/swagger-codegen/src/main/resources/csharp/enumClass.mustache, modules/swagger-codegen/src/main/resources/csharp/modelEnum.mustache, modules/swagger-codegen/src/main/resources/csharp/modelGeneric.mustache, modules/swagger-codegen/src/main/resources/csharp/modelInnerEnum.mustache, modules/swagger-codegen/src/main/resources/csharp/visibility.mustache, modules/swagger-codegen/src/test/java/io/swagger/codegen/csharp/CSharpClientOptionsTest.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/CSharpClientOptionsProvider.java
Allows users to specify 'nonPublicApi' additional property (and C#
client CLI switch) to reduce visibility of classes created by the
generator. This includes API and Models as well as supporting code like
ApiClient and other infrastructure.
The requirement is to support codegen generated code to be embedded
within other applications where the generated code is not intended to be
publicly consumable or publicy exposed. An example would be an SDK which
internally consumes an API via the generated code; we wouldn't want the
internal API implementation exposed as part of that SDK.
Reducing visibility of the classes effectively makes the entire
implementation internal, regardless of the public modifier on methods or
static members. To fully make all members internal it would require
explicit …
=> [csharp] Support internal access of generated code

modules/swagger-codegen/src/main/resources/bash/client.mustache
@wing328
I've fixed this issue (#4543) by moving the bash version detection to the top 
of the generated script and improved logic to handle versions beyond 4.
I've tested it on Bash 3 and Bash 4.2:
```
➜  swagger-codegen git:(bugfix/4543-improve-bash-version-detection) ✗ /bin/bash output/bash/petstore-cli -h
Sorry - your Bash version is 3.2.57(1)-release
You need at least Bash 4.3 to run this script.
```
```
root@25c92892d1f6:/# /swagger/output/bash/petstore-cli -h
Sorry - your Bash version is 4.2.25(1)-release
You need at least Bash 4.3 to run this script.
```
Sanity to check on "4.4.0":
```
➜  swagger-codegen git:(bugfix/4543-improve-bash-version-detection) ✗ bash --version
GNU bash, version 4.4.0(1)-release (x86_64-apple-darwin16.0.0)
Copyright (C) 2016 Free Software Foundation, Inc. …
```
=> [Bash] Moved bash version detection to top and improved logic

modules/swagger-codegen/src/main/resources/typescript-angular/api.mustache, modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache, modules/swagger-codegen/src/main/resources/typescript-node/api.mustache, samples/client/petstore/typescript-angular/API/Client/PetApi.ts, samples/client/petstore/typescript-angular/API/Client/StoreApi.ts, samples/client/petstore/typescript-angular/API/Client/UserApi.ts, samples/client/petstore/typescript-angular2/default/api/PetApi.ts, samples/client/petstore/typescript-angular2/default/api/StoreApi.ts, samples/client/petstore/typescript-angular2/default/api/UserApi.ts, samples/client/petstore/typescript-angular2/npm/README.md, samples/client/petstore/typescript-angular2/npm/api/PetApi.ts, samples/client/petstore/typescript-angular2/npm/api/StoreApi.ts, samples/client/petstore/typescript-angular2/npm/api/UserApi.ts, samples/client/petstore/typescript-angular2/npm/package.json, samples/client/petstore/typescript-node/default/api.ts, samples/client/petstore/typescript-node/npm/api.ts, samples/client/petstore/typescript-node/npm/client.ts
Resolves #4407 (replacing PR #4409 with better backwards compatibility) by using `Object.assign` for object copying.
=> Extends obj using Object.assign

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenProperty.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
Earlier CodegenProperty did not have title field.
'title' information of the property was lost while converting from Property to CodegenProperty.
This change fixes it.
This PR addresses issue #4588 .  It adds title field for CodegenProperty and copies them while creating instance of CodegenProperty from Property.
=> Add title field to CodegenProperty

modules/swagger-codegen/src/main/resources/aspnetcore/enumClass.mustache, modules/swagger-codegen/src/main/resources/aspnetcore/global.json, modules/swagger-codegen/src/main/resources/aspnetcore/model.mustache, modules/swagger-codegen/src/main/resources/aspnetcore/project.json.mustache, samples/server/petstore/aspnetcore/IO.Swagger.sln, samples/server/petstore/aspnetcore/global.json, samples/server/petstore/aspnetcore/src/IO.Swagger/IO.Swagger.xproj, samples/server/petstore/aspnetcore/src/IO.Swagger/Models/ApiResponse.cs, samples/server/petstore/aspnetcore/src/IO.Swagger/Models/Category.cs, samples/server/petstore/aspnetcore/src/IO.Swagger/Models/Order.cs, samples/server/petstore/aspnetcore/src/IO.Swagger/Models/Pet.cs, samples/server/petstore/aspnetcore/src/IO.Swagger/Models/Tag.cs, samples/server/petstore/aspnetcore/src/IO.Swagger/Models/User.cs, samples/server/petstore/aspnetcore/src/IO.Swagger/project.json
This addresses a couple of issues.  As originally reported in #3608 and added to the C# client generator in #4145, this updates model constructors to use `default()` rather than attempting to initialize parameters to nulls. I didn't modify the NancyFX generator here, because it relies on object initialization and doesn't perform the same types of constructor validations or DataAnnotations/JSON validation.
The `petstore.yaml` has inner enums, so to get the sample code working against this yaml I've also added support for enums and inner enums, and regenerated the sample.
Please note if you're having issues with newer versions of `dotnet` CLI, there's a known issue (https://github.com/dotnet/corefx/issues/9171) with OS X/macOS support which requires linking openssl manually:
```
$ ln -s …
```
=> [aspnetcore] use default in model constructors, supports enums

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/BashClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CppRestClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/GoClientCodegen.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JMeterCodegen.java
For https://github.com/swagger-api/swagger-codegen/issues/4595
=> Add back embeddedTemplateDir to some generators

modules/swagger-codegen/src/main/resources/qt5cpp/model-body.mustache, samples/client/petstore/qt5cpp/client/SWGOrder.cpp, samples/client/petstore/qt5cpp/client/SWGPet.cpp, samples/client/petstore/qt5cpp/client/SWGUser.cpp
=> Fix name mangling for JSON processing with QT5

modules/swagger-codegen/src/main/resources/Javascript/partial_model_enum_class.mustache, samples/client/petstore/javascript-promise/src/model/EnumClass.js, samples/client/petstore/javascript-promise/src/model/OuterEnum.js, samples/client/petstore/javascript/src/model/EnumClass.js, samples/client/petstore/javascript/src/model/OuterEnum.js
When constructing an enum through constructFromObject the original value provided by the API response should be returned rather than extracting the value from the enum name. This resolves an issue where the constructed value is undefined when the name and value are not equivalent.
=> Enum constructFromObject should return value

modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache
[typescript-angular2] Handle date type correctly #3105
currently only works for query parameters
=> Adjust Dateformat (ISO 8601) for Query Parameters with Input Date 

modules/swagger-codegen/src/main/resources/Javascript/api_test.mustache
Removed pet variable from Javascript api_test Mustache file, which was undefined and is not necessary here. This should fix issue #4608.
=> [Javascript] Bug fix for api_test.mustache

modules/swagger-codegen/src/main/resources/php/model_generic.mustache, samples/client/petstore/php/SwaggerClient-php/lib/Model/EnumArrays.php, samples/client/petstore/php/SwaggerClient-php/lib/Model/EnumTest.php, samples/client/petstore/php/SwaggerClient-php/lib/Model/Order.php, samples/client/petstore/php/SwaggerClient-php/lib/Model/Pet.php
Changed template substitution value to be a valid mustache variable
=> fix for allowable values, #4645

bin/spring-delegate-j8.sh, bin/spring-delegate.sh
In a previous PR I forgot to change the `rm` line to reflect the file that needs to be removed before running the generator.
Related #4439
=> Fix the `rm` to remove the correct file in two spring generation bash scripts

modules/swagger-codegen/src/main/resources/htmlDocs2/param.mustache
Considering html2 as generating document instead of code, so there should be baseName in the page.
Otherwise, the parameter will be changed if the parameter doesn't follow the element rules.
e.g. parameter name as aa_bb_cc, then the document will change it as  aaBbCc, which is confused for the document users.  So highly recommend to change it to baseName.
=> change html2 moustache to fix parameter name

modules/swagger-codegen/src/main/resources/Javascript/api_test.mustache, modules/swagger-codegen/src/main/resources/Javascript/partial_model_generic.mustache
Added single quotes -- fixes bug where generated client throws an 'Uncaught Reference Error' when calling a function.
=> [Javascript] Fix for 'Uncaught Reference Error' when calling certain functions

modules/swagger-codegen/src/main/resources/JavaSpring/pojo.mustache, samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/model/HasOnlyReadOnly.java, samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/model/Name.java, samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/model/ReadOnlyFirst.java, samples/server/petstore/spring-mvc/src/main/java/io/swagger/model/HasOnlyReadOnly.java, samples/server/petstore/spring-mvc/src/main/java/io/swagger/model/Name.java, samples/server/petstore/spring-mvc/src/main/java/io/swagger/model/ReadOnlyFirst.java, samples/server/petstore/springboot-delegate-j8/src/main/java/io/swagger/model/HasOnlyReadOnly.java, samples/server/petstore/springboot-delegate-j8/src/main/java/io/swagger/model/Name.java, samples/server/petstore/springboot-delegate-j8/src/main/java/io/swagger/model/ReadOnlyFirst.java, samples/server/petstore/springboot-delegate/src/main/java/io/swagger/model/HasOnlyReadOnly.java, samples/server/petstore/springboot-delegate/src/main/java/io/swagger/model/Name.java, samples/server/petstore/springboot-delegate/src/main/java/io/swagger/model/ReadOnlyFirst.java, samples/server/petstore/springboot/src/main/java/io/swagger/model/HasOnlyReadOnly.java, samples/server/petstore/springboot/src/main/java/io/swagger/model/Name.java, samples/server/petstore/springboot/src/main/java/io/swagger/model/ReadOnlyFirst.java
Adds the generation of the `isReadOnly` value in the model for spring.
=> Add support for read-only  annotation generation on values in spring model

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/NodeJSServerCodegen.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/nodejs/NodeJSServerOptionsTest.java, samples/server/petstore/nodejs/api/swagger.yaml
=> tests, fix for #4647.  Proper escaping project name per npmjs

modules/swagger-codegen/src/main/resources/rails5/README.md
- [ x ] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
Newly generated code in Rails 5 readme wrongly says the code was generated for "Sinatra". This patch changes it to read "Ruby on Rails".
Fixes #4655
=> Minor: fix incorrect reference in Rails 5 readme from "Sinatra" to "Ruby on Rails"

modules/swagger-codegen-maven-plugin/src/main/java/io/swagger/codegen/plugin/CodeGenMojo.java
#4625 - Check if configOptions are set before trying to get the source folder, otherwise assume null/empty.
=> Fix maven plugin NullPointer exception while trying to generate Spring server (fixes #4625)

modules/swagger-codegen/src/main/resources/Javascript/ApiClient.mustache, samples/client/petstore/javascript-promise/src/ApiClient.js, samples/client/petstore/javascript/src/ApiClient.js
Fixes #4653.
/cc @khorolets @wing328 @jordanyaker
=> [JavaScript] Fixed handling of empty arrays/empty strings/booleans/single numbers as valid API responses

modules/swagger-codegen/src/main/resources/TypeScript-Fetch/api.mustache
error TS2454: Variable 'contentTypeHeader' is used before being assigned.
error TS2345: Argument of type 'FetchAPI | undefined' is not assignable to parameter of type 'FetchAPI'.
According to issue https://github.com/swagger-api/swagger-codegen/issues/4657
=> Fix Typescript errors with 'strictNullChecks' mode enabled

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ElixirClientCodegen.java
Override `escapeQuotationMark`, `escapeUnsafeCharacters` to avoid warnings.
=> [Elixir] escape unsafe characters/quotes in Elixir generator

modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/pojo.mustache, samples/server/petstore/jaxrs-cxf/src/gen/java/io/swagger/model/Category.java, samples/server/petstore/jaxrs-cxf/src/gen/java/io/swagger/model/ModelApiResponse.java, samples/server/petstore/jaxrs-cxf/src/gen/java/io/swagger/model/Order.java, samples/server/petstore/jaxrs-cxf/src/gen/java/io/swagger/model/Pet.java, samples/server/petstore/jaxrs-cxf/src/gen/java/io/swagger/model/Tag.java, samples/server/petstore/jaxrs-cxf/src/gen/java/io/swagger/model/User.java
Before this change, model classes had only a default constructor and setter methods, resulting in code like this:
``` java
myModel = MyModel();
myModel.setFirstField(firstField);
myModel.setSecondField(secondField);
return myModel;
```
this change adds builder style methods, such that the above code can be written more compactly:
``` java
return MyModel().firstField(firstField).secondField(secondField);
```
this is consistent with other JAVA generators in swagger-codegen.
=> [JAXRS-CXF] [issue #4386] add builder-style methods to model classes

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
If a type's field is an array or map, dataFormat of the innerProperty was not copied
into encapsulating property. This change fixes it.
=> Copy dataformat if property field is an array.

modules/swagger-codegen/src/main/resources/go/api.mustache
Fixed issue #4664: [go] incorrect code generated, if there are more than 1 array parameters
Took the suggestion by wing328 and reworked the fix. This patch also applied to the latest master, while the original issue was about 2.2.1 code.
=> Fixed issue #4664

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AspNetCoreServerCodegen.java
Outputs warnings about ASP.NET Core's src/ requirement, and adjusts
sourceFolder if the input doesn't start with src/.
As a consequence of this change, apiFileFolder and modelFileFolder may
possibly return different values if users are setting both sourceFolder
and packageName. This could be considered a breaking change in those
sceanrios.
see #4690 
This fix resolves the issue with `packageName` not being respected. I've also added some log messages in a new `setSourceFolder` override. However, ASP.NET Core requires a rigid source directory structure, and it appears as though changing `sourceFolder` can cause problems. We may want to override `setSourceFolder` to prevent overwriting it from "src".
=> [aspnetcore] resolve source/packageName issues

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenParameter.java, modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenProperty.java, modules/swagger-codegen/src/main/resources/htmlDocs/bodyParam.mustache, modules/swagger-codegen/src/main/resources/htmlDocs/formParam.mustache, modules/swagger-codegen/src/main/resources/htmlDocs/headerParam.mustache, modules/swagger-codegen/src/main/resources/htmlDocs/index.mustache, modules/swagger-codegen/src/main/resources/htmlDocs/pathParam.mustache, modules/swagger-codegen/src/main/resources/htmlDocs/queryParam.mustache, modules/swagger-codegen/src/main/resources/htmlDocs2/sample_android.mustache, modules/swagger-codegen/src/main/resources/htmlDocs2/sample_csharp.mustache, modules/swagger-codegen/src/main/resources/htmlDocs2/sample_java.mustache, modules/swagger-codegen/src/main/resources/htmlDocs2/sample_js.mustache, modules/swagger-codegen/src/main/resources/htmlDocs2/sample_objc.mustache, modules/swagger-codegen/src/main/resources/htmlDocs2/sample_perl.mustache, modules/swagger-codegen/src/main/resources/htmlDocs2/sample_php.mustache, modules/swagger-codegen/src/main/resources/htmlDocs2/sample_python.mustache, samples/html/index.html, samples/html2/index.html
Fix #4611 : Use `{{unescapedDescription}}` instead of `{{description}}` in `html` and `html2` language output (mustache) templates, so that Java escaping (such as replacing `"` with `\"` does not occur for API, parameter, operation description strings.
=> Fix Issue #4611 by using {{unescapedDescription}}

modules/swagger-codegen/src/main/resources/JavaJaxRS/StringUtil.mustache
…here file is generated
When generating for JaxRS, the StringUtil.java file is generated under "apiPackage", but the package name IN the file was set to "invokerPackage". This fixes the mustache file to align the two, to "apiPackage"
=> fix(jax-rs): fix package name in generated StringUtil.java to match 

modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache, samples/client/petstore/typescript-angular2/default/api/PetApi.ts, samples/client/petstore/typescript-angular2/default/api/StoreApi.ts, samples/client/petstore/typescript-angular2/default/api/UserApi.ts, samples/client/petstore/typescript-angular2/npm/README.md, samples/client/petstore/typescript-angular2/npm/api/PetApi.ts, samples/client/petstore/typescript-angular2/npm/api/StoreApi.ts, samples/client/petstore/typescript-angular2/npm/api/UserApi.ts, samples/client/petstore/typescript-angular2/npm/package.json
=> [Typescript-Angular2] Fixes #4703

modules/swagger-codegen/src/main/java/io/swagger/codegen/examples/XmlExampleGenerator.java, modules/swagger-codegen/src/test/java/io/swagger/codegen/ExampleGeneratorTest.java
fix issue #4672 (XmlExampleGenerator does not properly handle properties of several numeric types), and bring XML default example values in-line with ExampleGenerator
=> fix issue #4672 - XmlExampleGenerator does not properly handle properties of several numeric types

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java, modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/ApiClient.mustache, modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/api.mustache, modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/build.gradle.mustache, modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/build.sbt.mustache, modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/pom.mustache, modules/swagger-codegen/src/test/java/io/swagger/codegen/options/JavaClientOptionsProvider.java
https://github.com/swagger-api/swagger-codegen/issues/4698
=> rx2 support
