swagger-api/swagger-codegen

src/main/java/com/wordnik/swagger/codegen/languages/AndroidClientCodegen.java

There was an error for android-java template

Fixed apiFileFolder and modelFileFolder function results for android-java Fixes #369

---

src/main/resources/php/api.mustache

Also fixed mixed tabs and spaces in template.
See #383

Add missing formParams to PHP api.mustache. Fixes #383.

---

src/main/resources/php/Swagger.mustache

No longer will deserialize throw errors when converting a json response to a string

Fixing issue with deserialization in PHP

---

src/main/java/com/wordnik/swagger/codegen/languages/PythonClientCodegen.java
src/main/resources/META-INF/services/com.wordnik.swagger.codegen.CodegenConfig

Hi,
I need to create a python client for my current project and therefore added this implementation to based on develop_2.0 branch. The implementation is a port of what I understood of the scala generator class (from master) and produces a working Python client (as far as my tests for my API can tell that by now).
Please check the implementation and see whether there is something missing/wrong.
I would like to add tests for the code generation. It would be great if someone could tell me how this should be done in swagger-codegen.
Best regards
Fleque

[WIP] Support Python code generation

---

src/main/resources/php/Swagger.mustache
src/main/resources/php/api.mustache

for body extraction the post data needs to be a url encoded query string

Fixing curl $postData for php bindings

---

src/main/resources/Java/model.mustache
src/test/scala/Java/JavaModelTest.scala

Adds support of upper case-proprty name; https://github.com/swagger-api/swagger-codegen/issues/249

Support upper case-proprty names

---

samples/server-generator/node/output/App/apis/PetApi.js
samples/server-generator/node/output/App/apis/StoreApi.js
samples/server-generator/node/output/App/apis/UserApi.js
samples/server-generator/node/templates/api.mustache

The node server example (at swagger-codegen/samples/server-generator/node) had a breaking issue: the api template listed "params" as a property, instead of "parameters"

Fix "properties" name in node server example template

---

src/main/resources/php/Swagger.mustache
src/main/resources/php/api.mustache
src/main/resources/python/api.mustache
src/main/resources/python/swagger.mustache

Adding support for submitting a multipart/form-data request.  Including full support for file uploads by passing in the filepath as the argument to the generated method.

Python/PHP Multipart-Form request support

---

modules/swagger-codegen/src/main/resources/php/Swagger.mustache
modules/swagger-codegen/src/main/resources/php/api.mustache
modules/swagger-codegen/src/main/resources/python/api.mustache
modules/swagger-codegen/src/main/resources/python/swagger.mustache

Adding in the following enhancements:
- formParms in PHP and Python bindings
- respect the set Content-Type in python POST requests
- allowing for file uploads in PHP and Python bindings

PHP/Python Enhancements

---

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/languages/ScalaClientCodegen.java
modules/swagger-codegen/src/main/resources/scala/apiInvoker.mustache
modules/swagger-codegen/src/main/resources/scala/pom.mustache

Ability to integrate with a SPNEGO-protected REST API
with KerberosV5 ticket preemptive authentication.

Support Secure SPNEGO kerberos negotiation for Scala

---

README.md

The ````-i```` flag should be ````-l````

Update README.md - fixed incorrect flag for custom generator class

---

modules/swagger-codegen/src/main/resources/php/Swagger.mustache
modules/swagger-codegen/src/main/resources/php/api.mustache

PHP client is missing PATCH support at the moment. This PR will update Swagger.php to handle PATCH request properly

Add PATCH support to PHP API client

---

modules/swagger-codegen/src/main/resources/php/api.mustache
samples/client/petstore/php/PetApi.php
samples/client/petstore/php/StoreApi.php
samples/client/petstore/php/Swagger.php
samples/client/petstore/php/UserApi.php

single-quoted form parameter (header, query parameter already singled quoted), add more comments

form parameter(single quote), add more comments

---

modules/swagger-codegen/src/main/resources/php/Swagger.mustache
modules/swagger-codegen/src/main/resources/php/api.mustache
samples/client/petstore/php/PetApi.php
samples/client/petstore/php/Swagger.php

currently, datetime parameter is not output in ISO8601 format. this PR aims to output the datetime parameters (header, form, url, path) in ISO8601 format.

PHP parameters to suppport datetime (ISO8601)

---

modules/swagger-codegen/src/main/resources/php/Swagger.mustache
modules/swagger-generator/src/main/java/com/wordnik/swagger/generator/resource/SwaggerResource.java
samples/client/petstore/php/Swagger.php

add logic to handle all 2xx response code
bug fix for string response
bug fix for showing error message using serialize
update php petstore sample

minor bug fixes and enhancement to Swagger.php

---

modules/swagger-codegen/src/main/resources/ruby/api.mustache
modules/swagger-codegen/src/main/resources/ruby/swagger/request.mustache
samples/client/petstore/ruby/lib/PetApi.rb
samples/client/petstore/ruby/lib/StoreApi.rb
samples/client/petstore/ruby/lib/UserApi.rb
samples/client/petstore/ruby/lib/swagger/request.rb

update ruby client
- support form parameters (including file upload)
- add PATCH support for HTTP request

update ruby client to support form parameters, add PATCH support

---

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/resources/Java/api.mustache
modules/swagger-codegen/src/main/resources/Java/apiInvoker.mustache
samples/client/petstore/java/src/main/java/io/swagger/client/ApiInvoker.java
samples/client/petstore/java/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/src/main/java/io/swagger/client/api/UserApi.java

* Convert values to string for query/header/form parameters.
* For parameter of type Date, convert to ISO 8601 format.
* Also add utility methods to parse date with ISO 8601 format.

Add parameterToString to normalize parameters for Java client

---

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/DefaultGenerator.java
modules/swagger-codegen/src/main/resources/htmlDocs/index.mustache

I want to be able to display the API version my static html documentation.

Add API Version to Codegen Additional Properties

---

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/DefaultCodegen.java

Replaces PR 496.
(cherry picked from commit 01515e4ded6fa59da87d109dd8056c1b4a64e0f7)

Fix NPE with resourcePath = /, issue #495

---

modules/swagger-codegen/src/main/resources/android-java/api.mustache
modules/swagger-codegen/src/main/resources/android-java/apiInvoker.mustache
modules/swagger-codegen/src/main/resources/android-java/pom.mustache
samples/client/petstore/android-java/pom.xml
samples/client/petstore/android-java/src/main/java/io/swagger/client/ApiInvoker.java
samples/client/petstore/android-java/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/android-java/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/android-java/src/main/java/io/swagger/client/api/UserApi.java

* Handle form parameters in a way similar to Java client.
* Handle file uploading.
* Normalize query, header and form parameters with the
ApiInvoker.parameterToString method, which formats Date value to ISO 8601.

Add support of form parameter to Android client

---

modules/swagger-codegen/src/main/resources/python/swagger.mustache

* Refactor santizeForSerialization to static method.
* Sanitize header/query/form/body parameters.
* Sanitize datetime.datetime and datetime.date to iso8601 format string.
* Sanitize swagger model to dict.

Update santizeForSerialization to normalize parameters for Python client

---

modules/swagger-codegen/src/main/resources/php/Swagger.mustache

Adding in a function for applying additional headers to an ApiClient Object.

PHP Request Headers and Deserialization

---

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/DefaultGenerator.java

Use Oracle codestyle, brackets with every if+else.
Nothing else changed
Preparation of complexity refactoring and unit testing in future
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/swagger-api/swagger-codegen/540)

rft - only codestyle, remove wildcard imports and use string-utils from apache

---

README.md
bin/all-petstore.sh
modules/swagger-codegen-cli/src/main/java/com/wordnik/swagger/codegen/Readme.java
modules/swagger-codegen-cli/src/main/java/com/wordnik/swagger/codegen/SwaggerCodegen.java
modules/swagger-codegen-cli/src/main/java/com/wordnik/swagger/codegen/cmd/Generate.java
modules/swagger-codegen-cli/src/main/java/com/wordnik/swagger/codegen/cmd/Meta.java
modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/Codegen.java
modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/MetaGenerator.java

(after #547)
renew #551
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/swagger-api/swagger-codegen/571)

update docs and bash about CLI usage, deprecate old cli classes

---

modules/swagger-codegen/src/main/resources/python/api.mustache
modules/swagger-codegen/src/main/resources/python/swagger.mustache

Modifying request headers in ApiClient to act like those in Java and PHP

Python Binding Request Headers

---

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/languages/RubyClientCodegen.java
modules/swagger-codegen/src/main/resources/ruby/swagger-client.gemspec.mustache
modules/swagger-codegen/src/main/resources/ruby/swagger-client.mustache
samples/client/petstore/ruby/Gemfile.lock
samples/client/petstore/ruby/README.md
samples/client/petstore/ruby/lib/swagger-client.rb
samples/client/petstore/ruby/spec/pet_spec.rb
samples/client/petstore/ruby/spec/spec_helper.rb
samples/client/petstore/ruby/swagger-client.gemspec

This PR makes the gemspec file generated automatically with ruby generator.
Also adds README.md describing how to build the generated code into a ruby gem and  how to use the gem.

Generate Ruby gemspec

---

modules/swagger-codegen/src/main/resources/php/APIClient.mustache
modules/swagger-codegen/src/main/resources/php/api.mustache

The PHP function strpos is not being used as recommended by http://php.net/strpos.
I have fixed this.

Correct usage of strpos in PHP APIClient mustache template

---

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/languages/ObjcClientCodegen.java

fix for https://github.com/swagger-api/swagger-codegen/issues/633

Adding toParamName override to ObjcClientCodegen.java

---

modules/swagger-codegen/src/main/resources/objc/SWGQueryParamCollection.h

fix for https://github.com/swagger-api/swagger-codegen/issues/636

Adding import for Foundation.h to SWGQueryParamCollection.h

---

samples/client/petstore/ruby/spec/pet_spec.rb
samples/client/petstore/ruby/spec/response_spec.rb
samples/client/petstore/ruby/spec/spec_helper.rb
samples/client/petstore/ruby/spec/store_spec.rb

This PR aims to fix the rspec error by first creating Pet and Order object before running any tests. This can help ensure the objects are ready for the tests.
Here is the result for the integration test:
```
ruby|fix_ruby_rspec⚡ ⇒ mvn integration-test -rf :RubyPetstoreClientTests
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] Building Ruby Swagger Petstore Client 1.0-SNAPSHOT
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:copy-dependencies (default) @ RubyPetstoreClientTests ---
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (bundle-install) @ …
```

Fixed Ruby rspec

---

modules/swagger-codegen/src/main/resources/android-java/api.mustache
modules/swagger-codegen/src/main/resources/objc/api-body.mustache
modules/swagger-codegen/src/main/resources/python/api.mustache
modules/swagger-codegen/src/main/resources/python3/api.mustache
modules/swagger-codegen/src/main/resources/scala/api.mustache
samples/client/petstore/android-java/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/android-java/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/android-java/src/main/java/io/swagger/client/api/UserApi.java
samples/client/petstore/objc/client/SWGPetApi.m
samples/client/petstore/objc/client/SWGStoreApi.m
samples/client/petstore/objc/client/SWGUserApi.m
samples/client/petstore/python/SwaggerPetstore-python/SwaggerPetstore/pet_api.py
samples/client/petstore/python/SwaggerPetstore-python/SwaggerPetstore/store_api.py
samples/client/petstore/python/SwaggerPetstore-python/SwaggerPetstore/user_api.py
samples/client/petstore/python3/client/pet_api.py
samples/client/petstore/python3/client/store_api.py
samples/client/petstore/python3/client/user_api.py
samples/client/petstore/scala/src/main/scala/io/swagger/client/api/PetApi.scala
samples/client/petstore/scala/src/main/scala/io/swagger/client/api/StoreApi.scala
samples/client/petstore/scala/src/main/scala/io/swagger/client/api/UserApi.scala

- for python, use the unescape notes, summary and description (ref: http://stackoverflow.com/questions/3898572/what-is-the-standard-python-docstring-format)
- for objc, add method description (ref: http://stackoverflow.com/a/20169675/677735)
- for android and scala, add the Java-style method description

Better method documentation

---

modules/swagger-codegen/src/main/resources/Java/api.mustache
modules/swagger-codegen/src/main/resources/android-java/api.mustache
modules/swagger-codegen/src/main/resources/php/api.mustache
modules/swagger-codegen/src/main/resources/ruby/api.mustache
samples/client/petstore/android-java/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/android-java/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/android-java/src/main/java/io/swagger/client/api/UserApi.java
samples/client/petstore/java/hello.txt
samples/client/petstore/java/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/src/main/java/io/swagger/client/api/UserApi.java
samples/client/petstore/php/SwaggerClient-php/lib/PetApi.php
samples/client/petstore/php/SwaggerClient-php/lib/StoreApi.php
samples/client/petstore/php/SwaggerClient-php/lib/UserApi.php
samples/client/petstore/ruby/lib/pet_api.rb
samples/client/petstore/ruby/lib/store_api.rb
samples/client/petstore/ruby/lib/user_api.rb

Currently, required parameter validation is missing/broken. This PR aims to improve the method/function by ensuring that the required parameter is set. Otherwise, an exception will be thrown.
Reference: #701 
(Python and Objc clients have not yet been checked/fixed)

Fix required parameter validation for Java, Android, PHP and Ruby

---

samples/client/petstore/perl/pom.xml
samples/client/petstore/perl/t/01_pet_api.t

- Add unit testing to test Pet operations (GET, POST,DELETE)
- Add pom.xml for integration test
```
➜  perl git:(perl_add_unittest) ✗ mvn integration-test -rf :PerlPetstoreClientTests
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] Building Perl Swagger Petstore Client 1.0-SNAPSHOT
[INFO] 
[INFO] --- maven-dependency-plugin:2.1:copy-dependencies (default) @ PerlPetstoreClientTests ---
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (Test::More) @ PerlPetstoreClientTests ---
1..25
ok 1 - use WWW::SwaggerClient::PetApi;
ok 2 - use WWW::SwaggerClient::APIClient;
ok …
```

Add unit testing for Perl

---

README.md

Added the following:
PerlClientCodegen.java
Python3ClientCodegen.java
Qt5CPPGenerator.java

Update README.md with new generators

---

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/languages/PythonClientCodegen.java
modules/swagger-codegen/src/test/resources/2_0/v1beta3.json
modules/swagger-codegen/src/test/scala/python/PythonTest.scala

Fixed #593: Python code failure caused by Model IDs with dots has been fixed

Fixed #593: Python code failure caused by Model IDs with dots has been fixed

---

modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/examples/XmlExampleGenerator.java
modules/swagger-codegen/src/test/scala/ExampleGeneratorTest.scala

Fixed #728: Handling of recursive model definitions has been improved.

Fixed #728: Handling of recursive model definitions has been improved.

---

modules/swagger-codegen/src/test/scala/ExampleGeneratorTest.scala

Fixes #771: Unit test has been fixed after merge.

Fixes #771: Unit test has been fixed after merge.

---

modules/swagger-codegen/src/main/resources/php/APIClient.mustache
samples/client/petstore/php/SwaggerClient-php/lib/APIClient.php
samples/client/petstore/php/SwaggerClient-php/tests/PetApiTest.php

- To fix #828.
- Added test case for getInventory to catch issue with map moving forward

[PHP] bug fix for map, added test case

---

modules/swagger-generator/src/main/java/com/wordnik/swagger/generator/online/Generator.java
modules/swagger-generator/src/main/java/com/wordnik/swagger/generator/resource/SwaggerResource.java
modules/swagger-generator/src/test/scala/GeneratorInputTest.scala

Fix package name for generator/online/Generator.java

---

modules/swagger-codegen/src/main/resources/perl/ApiClient.mustache
samples/client/petstore/perl/lib/WWW/SwaggerClient/ApiClient.pm
samples/client/petstore/perl/lib/WWW/SwaggerClient/PetApi.pm
samples/client/petstore/perl/pom.xml
samples/client/petstore/perl/t/02_store_api.t
samples/client/petstore/perl/test.pl
samples/client/petstore/php/SwaggerClient/vendor/satooshi/php-coveralls/build/config/apigen.neon
samples/client/petstore/php/SwaggerClient/vendor/satooshi/php-coveralls/build/config/phpcs.xml
samples/client/petstore/php/SwaggerClient/vendor/satooshi/php-coveralls/build/config/phpmd.xml

- updated `deserialize` to support Map (hash) and List (array)
- added test case for StoreApi's `get_inventory`
- updated pom.xml with new tests

[Perl] update deserialization to support Map and List

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java
modules/swagger-codegen/src/main/resources/python/api_client.mustache
samples/client/petstore/python/SwaggerPetstore-python/SwaggerPetstore/__init__.py
samples/client/petstore/python/SwaggerPetstore-python/SwaggerPetstore/api_client.py
samples/client/petstore/python/SwaggerPetstore-python/SwaggerPetstore/apis/__init__.py
samples/client/petstore/python/SwaggerPetstore-python/SwaggerPetstore/apis/pet_api.py
samples/client/petstore/python/SwaggerPetstore-python/SwaggerPetstore/apis/store_api.py
samples/client/petstore/python/SwaggerPetstore-python/tests/test_api_client.py
samples/client/petstore/python/SwaggerPetstore-python/tests/test_store_api.py

* To fix #828.
* Added test case for getInventory to catch issue with map moving forward.
* Added support for object type response.

[Python] bug fix for map response

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java
samples/client/petstore/php/SwaggerClient-php/lib/Api/PetApi.php

The issue only impacts PHP generator (develop_2.0) in Windows and the fix tested in both Mac and Windows.

[PHP] Fix regular expression in toPackagePath

---

modules/swagger-codegen/src/main/resources/Java/ApiClient.mustache
samples/client/petstore/java/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/src/main/java/io/swagger/client/model/Pet.java

This fixes https://github.com/swagger-api/swagger-codegen/issues/890
Integration tests have been run, and are passing.

Replacing getClientResponseStatus() with getStatusInfo()

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java
modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache
modules/swagger-codegen/src/main/resources/csharp/ApiException.mustache
modules/swagger-codegen/src/main/resources/csharp/Configuration.mustache
modules/swagger-codegen/src/main/resources/csharp/api.mustache
modules/swagger-codegen/src/main/resources/csharp/model.mustache
samples/client/petstore/csharp/compile.bat
samples/client/petstore/csharp/src/main/csharp/io/swagger/Model/Category.cs
samples/client/petstore/csharp/src/main/csharp/io/swagger/Model/Order.cs
samples/client/petstore/csharp/src/main/csharp/io/swagger/Model/Pet.cs
samples/client/petstore/csharp/src/main/csharp/io/swagger/Model/Tag.cs
samples/client/petstore/csharp/src/main/csharp/io/swagger/Model/User.cs
samples/client/petstore/csharp/src/main/csharp/io/swagger/client/Configuration.cs

Add CLI option for C#
```
CONFIG OPTIONS
packageName
C# package name (convention: Camel.Case), default: IO.Swagger
packageVersion
C# package version, default: 1.0.0
```
Tested with the following config.json:
```
{
"packageName": "Com.PetStore",
"packageVersion": "9.8.1"
}
```

[C#] Add CLI option support

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JaxRSServerCodegen.java

Sanitize API class name in Jax RS server codegen

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngularClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptNodeClientCodegen.java
modules/swagger-codegen/src/main/resources/TypeScript-Angular/api.mustache
modules/swagger-codegen/src/main/resources/TypeScript-node/api.mustache
modules/swagger-codegen/src/test/scala/typescriptangular/TypeScriptAngularModelTest.scala
modules/swagger-codegen/src/test/scala/typescriptnode/TypeScriptNodeModelTest.scala

* Changed modelPackage to 'model'
* Added mapping of Map and DateTime
* Switched to use contextPath
* Changed non-required parameters to be non-required in TypeScript

Cleaned up TypeScript code generator

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenSecurity.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java

generate oauth2 fields in the data for the templates

---

modules/swagger-codegen/src/main/resources/swift/APIs.mustache

A bug indicated in https://github.com/swagger-api/swagger-codegen/pull/901#issuecomment-120954358
This pr will close https://github.com/tkQubo/swagger-codegen/issues/6

[Swift] Fix a bug

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java

see [comment here](https://github.com/swagger-api/swagger-codegen/pull/923#discussion-diff-34637565)

Fix NullPointerException for authMethods

---

modules/swagger-codegen/src/main/resources/sinatra/api.mustache
modules/swagger-codegen/src/main/resources/sinatra/my_app.mustache
samples/server/petstore/sinatra/api/pet_api.rb
samples/server/petstore/sinatra/api/store_api.rb
samples/server/petstore/sinatra/api/user_api.rb
samples/server/petstore/sinatra/my_app.rb

- Replaced {{swaggerDataType}} with {{dataType}}
- Replaced {{allowMultiple}} with {{collectionFormat}}
- Added double quote to default value
- Used {{version}} for config.api_version

[Sinatra] Fixed outdated tag in mustache template

---

modules/swagger-codegen/src/main/resources/python/__init__package.mustache
modules/swagger-codegen/src/main/resources/python/api.mustache
modules/swagger-codegen/src/main/resources/python/api_client.mustache
modules/swagger-codegen/src/main/resources/python/configuration.mustache
modules/swagger-codegen/src/main/resources/python/rest.mustache
samples/client/petstore/python/swagger_client/__init__.py
samples/client/petstore/python/swagger_client/api_client.py
samples/client/petstore/python/swagger_client/apis/pet_api.py
samples/client/petstore/python/swagger_client/apis/store_api.py
samples/client/petstore/python/swagger_client/apis/user_api.py
samples/client/petstore/python/swagger_client/configuration.py
samples/client/petstore/python/swagger_client/rest.py
samples/client/petstore/python/tests/test_deserialization.py
samples/client/petstore/python/tests/test_pet_api.py

* synchronous request:
```python
pet = api.get_pet_by_id(pet_id)
```
* Asynchronous request
```python
def callback_function(response):
pprint(response)
thread = api.get_pet_by_id(pet_id, callback=callback_function)
```
* Test without issue:
```sh
Ran 16 tests in 26.335s
OK
[INFO] Total time: 29.143 s
[INFO] Finished at: 2015-07-02T14:45:23+08:00
[INFO] Final Memory: 12M/222M
```

[Python] Support asynchronous request in python client

---

modules/swagger-codegen/src/main/resources/nodejs/swagger.mustache
samples/server/petstore/nodejs/api/swagger.json
samples/server/petstore/nodejs/controllers/Pet.js
samples/server/petstore/nodejs/controllers/PetService.js
samples/server/petstore/nodejs/controllers/Store.js
samples/server/petstore/nodejs/controllers/StoreService.js
samples/server/petstore/nodejs/controllers/User.js
samples/server/petstore/nodejs/controllers/UserService.js
samples/server/petstore/nodejs/index.js
samples/server/petstore/nodejs/package.json

[NodeJS] Add back summary and description to the endpoint definition

---

README.md
modules/swagger-codegen-cli/pom.xml
modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/cmd/Generate.java
modules/swagger-codegen-cli/src/test/java/io.swagger.codegen/GenerateTest.java
modules/swagger-codegen-cli/src/test/resources/petstore.json
modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConfig.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JaxRSServerCodegen.java

Fixed #831: skipOverwrite flag has been added

Fixed #831: skipOverwrite flag has been added

---

modules/swagger-codegen-cli/pom.xml

Fixed #798: original jar generation has been fixed.

Fixed #798: original jar generation has been fixed.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
modules/swagger-codegen/src/test/scala/Java/JavaModelTest.scala

Fixed #837: Generation of default values for complex arrays and maps has been improved.

Fixed #837: Generation of default values for complex arrays and maps has been improved.

---

modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache
samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Client/ApiClient.cs

Fixes https://github.com/swagger-api/swagger-codegen/issues/985

[C#] Fixing a mono compilation error

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java

Required for typescript generation, but seems like a general thing.

Sort model objects by inheritance

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwiftCodegen.java
modules/swagger-codegen/src/main/resources/swift/AlamofireImplementations.mustache
modules/swagger-codegen/src/main/resources/swift/Cartfile.mustache
modules/swagger-codegen/src/main/resources/swift/Podspec.mustache
modules/swagger-codegen/src/main/resources/swift/api.mustache

This update adds support for [file uploading feature] that will be added by unreleased version [1.3.0] of [Alamofire].
[file uploading feature]: https://github.com/Alamofire/Alamofire/pull/539
[1.3.0]: https://github.com/Alamofire/Alamofire/releases/tag/1.3.0
[Alamofire]: https://github.com/Alamofire/Alamofire

[Swift] Support file upload with Alamofire 1.3.0

---

modules/swagger-codegen/pom.xml
pom.xml

Thanks to Intellij IDEA that has spotted thos issues in maven configuration.

Fix issues in POM configuration

---

modules/swagger-codegen/src/main/resources/python/model.mustache
samples/client/petstore/python/swagger_client/models/category.py
samples/client/petstore/python/swagger_client/models/order.py
samples/client/petstore/python/swagger_client/models/pet.py
samples/client/petstore/python/swagger_client/models/tag.py
samples/client/petstore/python/swagger_client/models/user.py

* Fix issue https://github.com/swagger-api/swagger-codegen/issues/1038
* Integration test looks good:
```sh
--------------------------------------------------------------
TOTAL                             1247    469    62%
Ran 27 tests in 28.890s
OK
[INFO] Total time: 57.515 s
[INFO] Finished at: 2015-07-31T16:04:43+08:00
```

[Python] Fix issue in python client

---

modules/swagger-codegen/src/main/resources/Java/ApiClient.mustache

This fixes https://github.com/swagger-api/swagger-codegen/issues/1056

Fixing a bug with truncated lone string responses

---

modules/swagger-codegen/src/main/resources/android-java/apiInvoker.mustache
modules/swagger-codegen/src/main/resources/scala/apiInvoker.mustache
samples/client/petstore/android-java/src/main/java/io/swagger/client/ApiInvoker.java
samples/client/petstore/scala/src/main/scala/io/swagger/client/ApiInvoker.scala

Fix bug with truncated lone string responses for Android/Scala clients

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
modules/swagger-codegen/src/main/resources/Java/api.mustache

The only problematic spot was the api.mustache file, although if more parameterized templates were to evolve in the other mustache files we could definitely add {{localVariablePrefix}} to those too.  For now I didn't want to add any extra noise to the template files which didn't need the prefixes.

fix for #1061 java

---

pom.xml

Update swagger-core-version to 1.5.4-SNAPSHOT in pom.xml to address the CI error

Update swagger-core-version to 1.5.4-SNAPSHOT

---

modules/swagger-codegen/src/main/resources/objc/README.mustache

Added a section about recommendation for multithreaded environment.

[Objc] minor wording change for readme based on feedback from developers

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java
modules/swagger-codegen/src/main/resources/php/configuration.mustache
pom.xml
samples/client/petstore/php/SwaggerClient-php/lib/Configuration.php

- add example to config option
- replace localhost in configuration with basePath
- add version to user agent
Integration test result:
```
PHPUnit 4.8.3 by Sebastian Bergmann and contributors.
............
Time: 8.37 seconds, Memory: 5.25Mb
OK (12 tests, 167 assertions)
```

[PHP] minor improvements

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java

This fixes https://github.com/swagger-api/swagger-codegen/issues/1089

[Java] Sanitize configurable package names (fixes #1089)

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java

optional files are never written

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/test/scala/Java/JavaModelTest.scala

Shouldn't set the value if empty

added check, fix for #1103

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SpringMVCServerCodegen.java

#952 SpringMVCServer can't handle maps with $ref

fix SpringMVCServerCodegen for maps as in JavaClientCodegen

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java
modules/swagger-codegen/src/main/resources/php/ObjectSerializer.mustache
samples/client/petstore/php/SwaggerClient-php/lib/ObjectSerializer.php

This is a rebase of #838 which was done against outdated code.

update files as rebase from #838

---

samples/client/petstore/python/tests/test_api_client.py

Add test cases for `sanitize_for_serialization` method.
```
```

[Python] Add test cases for sanitize_for_serialization method in python client

---

pom.xml

To fix #1160 
Tested on Mac and Linux

Upgrade JMockit to 1.19

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java

Support dots in output folder for C# generator

---

modules/swagger-codegen/src/main/resources/nodejs/package.mustache
modules/swagger-codegen/src/main/resources/nodejs/swagger.mustache
samples/server/petstore/nodejs/api/swagger.json
samples/server/petstore/nodejs/controllers/Pet.js
samples/server/petstore/nodejs/controllers/PetService.js
samples/server/petstore/nodejs/controllers/StoreService.js
samples/server/petstore/nodejs/package.json

HTML-escaped description made the JSON files (generated by NodeJS server generator) invalid:
The fix uses the original description `{{{appDescription}}}`

[NodeJS] fixed HTML-escaped description on nodejs json files

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java

Fix HEAD path item is missing.

---

modules/swagger-codegen/pom.xml
pom.xml

To fix #1197 
- pumped slf4j version to the latest
- added dependency slf4j-simple

update pom.xml to remove warning

---

modules/swagger-codegen/src/main/resources/objc/ApiClient-body.mustache

This would actually prevent the podspec from lint-ing and prevent the project from being able to compile. Quick but important/urgent fix.

[Obj-C] Fixed an issue with incorrect references in the ApiClient when using a custom prefix.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenOperation.java

Fix #1221 
Also documented the methods.

Fix getHasXxxParam in CodegenOperation

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java

Fixed issue https://github.com/swagger-api/swagger-codegen/issues/1230
Tested without issue in both python2 and python3:
```
```

Fix issue in python client

---

modules/swagger-codegen/src/main/resources/python/api_client.mustache
modules/swagger-codegen/src/main/resources/python/rest.mustache
samples/client/petstore/python/swagger_client/__init__.py
samples/client/petstore/python/swagger_client/api_client.py
samples/client/petstore/python/swagger_client/apis/__init__.py
samples/client/petstore/python/swagger_client/apis/pet_api.py
samples/client/petstore/python/swagger_client/rest.py

Support `OPTIONS` http verb in python client.
Tested without issue in both python2 and python3:
```
______________________________________ summary ________________________________________
```

[Python] Enhancements http verbs of python client

---

modules/swagger-codegen/src/main/resources/objc/ApiClient-body.mustache
modules/swagger-codegen/src/main/resources/objc/ApiClient-header.mustache
modules/swagger-codegen/src/main/resources/objc/api-body.mustache
samples/client/petstore/objc/SwaggerClient.podspec
samples/client/petstore/objc/SwaggerClient/SWGApiClient.h
samples/client/petstore/objc/SwaggerClient/SWGApiClient.m
samples/client/petstore/objc/SwaggerClient/SWGPetApi.m
samples/client/petstore/objc/SwaggerClient/SWGStoreApi.m
samples/client/petstore/objc/SwaggerClient/SWGUserApi.h
samples/client/petstore/objc/SwaggerClient/SWGUserApi.m
samples/client/petstore/objc/SwaggerClientTests/SwaggerClient/SWGViewController.m

* Added `parameterToString` method to convert form parameters to NSString in `multipart/form` request.
```
Test Suite 'All tests' passed at 2015-09-17 07:00:00 +0000.
Executed 25 tests, with 0 failures (0 unexpected) in 13.872 (13.889) seconds
[INFO] Total time: 01:06 min
[INFO] Finished at: 2015-09-17T15:00:01+08:00
```

[Objc] Enhancements of objc client

---

modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/ApiClient.java

Support the `OPTIONS` HTTP method in Java okhttp-gson client

[Java okhttp-gson] Support the "OPTIONS"  HTTP method

---

modules/swagger-codegen/src/main/resources/python/api_client.mustache
modules/swagger-codegen/src/main/resources/python/configuration.mustache
samples/client/petstore/python/swagger_client/api_client.py
samples/client/petstore/python/swagger_client/configuration.py

Reverts swagger-api/swagger-codegen#1281

Revert "[Python] Fix issue in python client"

---

modules/swagger-codegen/src/main/resources/python/api_client.mustache
modules/swagger-codegen/src/main/resources/python/configuration.mustache
samples/client/petstore/python/swagger_client/api_client.py
samples/client/petstore/python/swagger_client/configuration.py

Tested without issue:
```
-----------------------------------------------------------------
TOTAL                                1253    467    63%
Ran 28 tests in 29.634s
OK
```

[Python] Update python log

---

modules/swagger-codegen/src/main/resources/objc/ApiClient-body.mustache
modules/swagger-codegen/src/main/resources/objc/ApiClient-header.mustache
samples/client/petstore/objc/SwaggerClient/SWGApiClient.h
samples/client/petstore/objc/SwaggerClient/SWGApiClient.m
samples/client/petstore/objc/SwaggerClientTests/SwaggerClient/SwaggerClient-Info.plist

* Added `SWGDebugLog` macro and class method `+[SWGApiClient debugLog:message:]` to log debug message.
The `SWGDebugLog` macro will log caller method name and debug message using `+[SWGApiClient debugLog:message:]` method.
```objc
SWGDebugLog(@"hello %@", @"world");    // => method_name: hello world
```
```
Test Suite 'All tests' passed at 2015-09-22 16:26:26.073.
Executed 25 tests, with 0 failures (0 unexpected) in 12.542 (12.568) seconds
[INFO] Total time: 55.070 s
[INFO] Finished at: 2015-09-22T16:26:26+08:00
[INFO] …
```

[Objc] Update objc debug logging

---

samples/client/petstore/ruby/spec/pet_spec.rb

* Added test case for upload file with form parameter.
```
Finished in 1 minute 16.11 seconds (files took 0.19379 seconds to load)
22 examples, 0 failures
[INFO] Total time: 01:19 min
[INFO] Finished at: 2015-09-25T17:35:31+08:00
```

[Ruby] Add test case in ruby client

---

modules/swagger-codegen/src/main/resources/ruby/api_client.mustache
modules/swagger-codegen/src/main/resources/ruby/configuration.mustache
samples/client/petstore/ruby/lib/petstore/api_client.rb
samples/client/petstore/ruby/lib/petstore/configuration.rb

* Added configuration options cert_file and key_file.
```
Finished in 32.28 seconds (files took 0.22611 seconds to load)
22 examples, 0 failures
[INFO] Total time: 36.025 s
[INFO] Finished at: 2015-09-28T16:20:24+08:00
```

[Ruby] Support client ceritficate in ruby client

---

modules/swagger-generator/src/main/java/io/swagger/generator/DynamicSwaggerConfig.java
modules/swagger-generator/src/main/java/io/swagger/generator/resource/SwaggerResource.java

Dynamically fill swagger enum from codegen client names

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java

Initiated the OAuth2Definition's scopes with an empty HashMap
Fix #1322

Fix NPE in empty operation oauth scopes

---

modules/swagger-generator/src/main/java/io/swagger/generator/online/Generator.java

Options supported are "apiPackage", "modelPackage", "invokerPackage", "groupId", "artifactId", "artifactVersion" and "library"
Fix #1313

Add options to online generator

---

modules/swagger-codegen/src/main/resources/htmlDocs/index.mustache

[HTML] remove site.css from html docs

---

modules/swagger-codegen/src/main/resources/php/api.mustache
samples/client/petstore/php/SwaggerClient-php/lib/Api/PetApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/StoreApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/UserApi.php
samples/client/petstore/php/SwaggerClient-php/lib/ObjectSerializer.php

See #1354.
Regenerated php-petstore sample.

Deserialize httpHeader.

---

modules/swagger-codegen/src/main/resources/nodejs/index.mustache
samples/server/petstore/nodejs/controllers/StoreService.js
samples/server/petstore/nodejs/index.js

Fix https://github.com/swagger-api/swagger-codegen/issues/1349

[NodeJS] update index.js to use the var serverPort

---

bin/all-petstore.sh
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/ApiException.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/Configuration.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/JSON.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/Pair.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/StringUtil.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/TypeRef.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/api/UserApi.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/ApiKeyAuth.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/Authentication.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/HttpBasicAuth.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/OAuth.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Category.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Order.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Pet.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Tag.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/User.java

Fix #1301, #1267 
(also remove python3-petstore.sh from all-petstore.sh)

Better exception handling

---

modules/swagger-codegen/src/main/resources/TypeScript-Angular/api.mustache
modules/swagger-codegen/src/main/resources/TypeScript-Angular/model.mustache
modules/swagger-codegen/src/main/resources/TypeScript-node/api.mustache

Update to #1383 with little fix for noImplicitAny Error

Updates to TypeScript Templates 2

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
modules/swagger-codegen/src/main/resources/Java/build.gradle.mustache
modules/swagger-codegen/src/main/resources/Java/gradle.properties.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/build.gradle.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit/build.gradle.mustache
modules/swagger-codegen/src/main/resources/Java/settings.gradle.mustache
samples/client/petstore/java/default/build.gradle
samples/client/petstore/java/default/gradle.properties
samples/client/petstore/java/default/settings.gradle
samples/client/petstore/java/jersey2/build.gradle
samples/client/petstore/java/jersey2/gradle.properties
samples/client/petstore/java/jersey2/settings.gradle
samples/client/petstore/java/okhttp-gson/build.gradle
samples/client/petstore/java/okhttp-gson/gradle.properties
samples/client/petstore/java/okhttp-gson/settings.gradle
samples/client/petstore/java/retrofit/build.gradle
samples/client/petstore/java/retrofit/gradle.properties
samples/client/petstore/java/retrofit/settings.gradle

Add gradle files with android support to java templates

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java

To make it configurable via maven task.

add library in the additional option

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/DefaultGeneratorTest.java
modules/swagger-codegen/src/test/resources/2_0/globalSecurity.json
samples/client/petstore/java/default/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/ruby/lib/petstore/api/pet_api.rb

Apply global security to operations when necessary

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenParameter.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit/CollectionFormats.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit/api.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit/queryParams.mustache
samples/client/petstore/java/retrofit/src/main/java/io/swagger/client/CollectionFormats.java
samples/client/petstore/java/retrofit/src/main/java/io/swagger/client/StringUtil.java
samples/client/petstore/java/retrofit/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/retrofit/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/retrofit/src/main/java/io/swagger/client/api/UserApi.java

Add colllectionFormat support to retrofit

---

modules/swagger-codegen/src/main/resources/Java/libraries/retrofit/api.mustache
samples/client/petstore/java/retrofit/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/retrofit/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/retrofit/src/main/java/io/swagger/client/api/UserApi.java

I accidentally added a useless import in  #1372 during rebase

Remove useless import

---

modules/swagger-codegen/src/main/resources/ruby/configuration.mustache
samples/client/petstore/ruby/lib/petstore/configuration.rb
samples/client/petstore/ruby/spec/configuration_spec.rb

Closes #1399 
The integration test is good:
```
........................
Finished in 20.42 seconds (files took 0.33238 seconds to load)
24 examples, 0 failures
```

Ruby client: remove trailing slashes from base_url

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConfig.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwiftCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/CodegenTest.java
modules/swagger-codegen/src/test/resources/2_0/globalConsumesAndProduces.json

Add support for top-level consumes and produces

---

modules/swagger-codegen/src/main/resources/Java/JSON.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/JSON.mustache
samples/client/petstore/java/default/src/main/java/io/swagger/client/JSON.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/api/UserApi.java
samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/JSON.java
samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/api/UserApi.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/JSON.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/api/UserApi.java

[Java] Ignore null fields in model serialization in Java clients

---

modules/swagger-codegen/src/main/resources/htmlDocs/index.mustache

Fixes #1251, #1212 : Form parameters has been added to the html template

Fixes #1251, #1212: Form parameters has been added to the html template

---

modules/swagger-codegen/src/main/resources/htmlDocs/index.mustache
modules/swagger-codegen/src/main/resources/htmlDocs/style.css.mustache
modules/swagger-codegen/src/main/resources/swagger-static/assets/css/style.css
modules/swagger-codegen/src/main/resources/swagger-static/model.mustache

Fixes #960: Enums have been added to result file.

Fixes #960: Enums have been added to result file

---

modules/swagger-generator/src/main/java/io/swagger/generator/online/Generator.java
modules/swagger-generator/src/test/java/io/swagger/generator/online/OnlineGeneratorOptionsTest.java
modules/swagger-generator/src/test/java/io/swagger/generator/online/OnlineJavaClientOptionsTest.java
modules/swagger-generator/src/test/java/io/swagger/generator/online/OnlineJaxRSServerOptionsTest.java
modules/swagger-generator/src/test/resources/petstore.json

Generator has been changed so that it can process all possible options.

Options processing has been fixed

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/AbstractOptionsTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/java/JavaClientOptionsTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/jaxrs/JaxRSServerOptionsTest.java
modules/swagger-generator/src/main/java/io/swagger/generator/online/Generator.java

Options tests have been added for Java and JaxRS

Options tests have been added for Java and JaxRS

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Qt5CPPGenerator.java

Add float and double to languageSpecificPrimitives

Issue #1461

---

modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/ApiClient.java

According to [the feedback](https://github.com/swagger-api/swagger-codegen/issues/1435#issuecomment-151606194) from @fabiankessler

Java jersey2: reuse a shared Client instance

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenOperation.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/resources/htmlDocs/index.mustache

ReturnType processing has been fixed

ReturnType processing has been fixed

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java
modules/swagger-codegen/src/main/resources/php/api.mustache
modules/swagger-codegen/src/main/resources/php/configuration.mustache
samples/client/petstore/php/SwaggerClient-php/lib/Api/PetApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Configuration.php

- added OAuth support
- better handle of $ in model name
ref: https://github.com/swagger-api/swagger-codegen/pull/1441
credit: @mach-kernel

[PHP] add OAuth support 

---

modules/swagger-codegen/src/main/resources/qt5cpp/helpers-body.mustache

Confirmed in my usecase that this is working. Not all paths may be tested.

Issue 1476

---

samples/client/petstore/perl/t/01_pet_api.t
samples/client/petstore/perl/t/02_store_api.t

Checking correct mapping of JSON field names to object field names.

Tests for deserialization

---

modules/swagger-codegen/src/main/resources/perl/ApiClient.mustache
modules/swagger-codegen/src/main/resources/perl/BaseObject.mustache
samples/client/petstore/perl/lib/WWW/SwaggerClient/ApiClient.pm
samples/client/petstore/perl/t/01_pet_api.t

A couple of PHP functions that don't exist in Perl were being called to process array query parameters.

Fix array query param processing

---

modules/swagger-codegen/src/main/resources/ruby/configuration.mustache
samples/client/petstore/ruby/lib/petstore/configuration.rb

ref: #1441
credit: @mach-kernel
see also #1446

Add oauth support for Ruby client

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
samples/client/petstore/java/default/pom.xml
samples/client/petstore/java/default/src/main/java/io/swagger/client/ApiException.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/Configuration.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/JSON.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/Pair.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/StringUtil.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/TypeRef.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/api/UserApi.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/ApiKeyAuth.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/Authentication.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/HttpBasicAuth.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Category.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Order.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Pet.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Tag.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/User.java
samples/dynamic-html/docs/assets/css/style.css
samples/dynamic-html/docs/models/Category.html
samples/dynamic-html/docs/models/Order.html
samples/dynamic-html/docs/models/Pet.html
samples/dynamic-html/docs/models/Tag.html
samples/dynamic-html/docs/models/User.html
samples/html/index.html

Better error handling for invalid array/map type

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngularClientCodegen.java
modules/swagger-codegen/src/main/resources/TypeScript-Angular/api.mustache
modules/swagger-codegen/src/main/resources/TypeScript-Angular/model.mustache
modules/swagger-codegen/src/main/resources/TypeScript-node/api.mustache
samples/client/petstore/typescript-angular/API/Client/Category.ts
samples/client/petstore/typescript-angular/API/Client/Order.ts
samples/client/petstore/typescript-angular/API/Client/Pet.ts
samples/client/petstore/typescript-angular/API/Client/PetApi.ts
samples/client/petstore/typescript-angular/API/Client/Tag.ts
samples/client/petstore/typescript-angular/API/Client/User.ts
samples/client/petstore/typescript-angular/tsconfig.json
samples/client/petstore/typescript-node/api.ts
samples/client/petstore/typescript-node/client.ts
samples/client/petstore/typescript-node/tsconfig.json

Makes node compile with TS 1.6+ and changes some access modifiers from private to protected

Aligns the two typescript generators

---

modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/cmd/ConfigHelp.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/CliOption.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConstants.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AndroidClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CsharpDotNet2ClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FlashClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ObjcClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PerlClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RubyClientCodegen.java
modules/swagger-generator/src/main/java/io/swagger/generator/online/Generator.java
modules/swagger-generator/src/main/java/io/swagger/generator/resource/SwaggerResource.java
modules/swagger-generator/src/test/java/io/swagger/generator/online/OnlineGeneratorOptionsTest.java
modules/swagger-generator/src/test/java/io/swagger/generator/online/OnlineJavaClientOptionsTest.java

SwaggerResource has been changed, Generator.getOptions method has been completed and test for this methos has been added

changed resource, method stub for generator options 

---

modules/swagger-codegen/src/main/resources/perl/ApiClient.mustache
modules/swagger-codegen/src/main/resources/perl/Configuration.mustache
samples/client/petstore/perl/lib/WWW/SwaggerClient/ApiClient.pm
samples/client/petstore/perl/lib/WWW/SwaggerClient/Configuration.pm
samples/client/petstore/perl/t/02_store_api.t

- Added OAuth2 support
- Commented out a test case about "pending" status
All test cases passed.

[Perl] add oauth2 support for Perl

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
modules/swagger-codegen/src/main/resources/Java/README.mustache
samples/client/petstore/java/default/README.md
samples/client/petstore/java/jersey2/README.md
samples/client/petstore/java/okhttp-gson/README.md
samples/client/petstore/java/retrofit/README.md

Add README.md to Java clients containing documentation like how to build and use the client.
See #1435

[Java] Add README.md to Java clients

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractTypeScriptClientCodegen.java
samples/client/petstore/typescript-angular/API/Client/Category.ts
samples/client/petstore/typescript-angular/API/Client/Order.ts
samples/client/petstore/typescript-angular/API/Client/Pet.ts
samples/client/petstore/typescript-angular/API/Client/PetApi.ts
samples/client/petstore/typescript-angular/API/Client/StoreApi.ts
samples/client/petstore/typescript-angular/API/Client/Tag.ts
samples/client/petstore/typescript-angular/API/Client/User.ts
samples/client/petstore/typescript-angular/API/Client/UserApi.ts
samples/client/petstore/typescript-node/api.ts

- Added better reserved word handling for OperationId (method name), e.g. delete will become _delete
- Updated reserved keyword list based on https://github.com/crissdev/is-keyword-js/blob/master/index.js suggested by @crissdev

[TypeScript] add reserved word handling for OperationId (method name)

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PerlClientCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/PerlClientOptionsProvider.java

Added `SORT_PARAMS_BY_REQUIRED_FLAG` and `ENSURE_UNIQUE_PARAMS`

[Perl] update CLI option for perl

---

modules/swagger-codegen/src/main/resources/Java/build.gradle.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/build.gradle.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/build.gradle.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit/build.gradle.mustache
samples/client/petstore/java/default/build.gradle
samples/client/petstore/java/jersey2/build.gradle
samples/client/petstore/java/okhttp-gson/build.gradle
samples/client/petstore/java/retrofit/build.gradle

The javax.annotation package is not included by default in Android.
See #1353

Provide dependency to javax.annotation.Generated for android templates

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
samples/client/petstore/java/default/src/test/java/io/swagger/petstore/test/UserApiTest.java
samples/client/petstore/java/jersey2/src/test/java/io/swagger/petstore/test/UserApiTest.java
samples/client/petstore/java/okhttp-gson/src/test/java/io/swagger/petstore/test/UserApiTest.java
samples/client/petstore/java/retrofit/src/test/java/io/swagger/petstore/test/UserApiTest.java

ref: https://github.com/swagger-api/swagger-codegen/pull/1457#issuecomment-155185530

Fix error with array of enum in Java client

---

modules/swagger-codegen/src/main/resources/TypeScript-Angular/api.mustache
modules/swagger-codegen/src/main/resources/TypeScript-node/api.mustache
samples/client/petstore/typescript-angular/API/Client/Category.ts
samples/client/petstore/typescript-angular/API/Client/Order.ts
samples/client/petstore/typescript-angular/API/Client/Pet.ts
samples/client/petstore/typescript-angular/API/Client/PetApi.ts
samples/client/petstore/typescript-angular/API/Client/StoreApi.ts
samples/client/petstore/typescript-angular/API/Client/Tag.ts
samples/client/petstore/typescript-angular/API/Client/User.ts
samples/client/petstore/typescript-angular/API/Client/UserApi.ts
samples/client/petstore/typescript-angular/API/Client/api.d.ts
samples/client/petstore/typescript-node/api.ts

Adds comments to TypeScript Generator & updates samples

---

samples/client/petstore/scala/src/test/scala/UserApiTest.scala

Better scala test to address intermittent CI failure.

[Scala] better scala test (UserApi)

---

modules/swagger-codegen/src/main/resources/Java/libraries/retrofit/auth/OAuth.mustache

This is to avoid an infinite loop if the server always sends an invalid token.

[Retrofit] Don't retry if the access token doesn't change

---

modules/swagger-codegen/src/main/resources/TypeScript-Angular/api.mustache
modules/swagger-codegen/src/main/resources/TypeScript-node/api.mustache
samples/client/petstore/typescript-angular/API/Client/Category.ts
samples/client/petstore/typescript-angular/API/Client/Order.ts
samples/client/petstore/typescript-angular/API/Client/Pet.ts
samples/client/petstore/typescript-angular/API/Client/PetApi.ts
samples/client/petstore/typescript-angular/API/Client/StoreApi.ts
samples/client/petstore/typescript-angular/API/Client/Tag.ts
samples/client/petstore/typescript-angular/API/Client/User.ts
samples/client/petstore/typescript-angular/API/Client/UserApi.ts
samples/client/petstore/typescript-angular/API/Client/api.d.ts
samples/client/petstore/typescript-node/api.ts

Removed the extra line break after parameter description in the documentation

[TypeScript] remove extra line break in documentation

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
modules/swagger-codegen/src/main/resources/Java/manifest.mustache
samples/client/petstore/java/default/src/main/AndroidManifest.xml
samples/client/petstore/java/jersey2/src/main/AndroidManifest.xml
samples/client/petstore/java/okhttp-gson/src/main/AndroidManifest.xml
samples/client/petstore/java/retrofit/src/main/AndroidManifest.xml

Add android manifest to java codegen

---

samples/client/petstore/java/retrofit2/.settings/org.eclipse.m2e.core.prefs

Removed samples/client/petstore/java/retrofit2/.settings/org.eclipse.m2e.core.prefs

Remove eclipse file

---

modules/swagger-codegen/src/main/resources/swift/APIs.mustache
modules/swagger-codegen/src/main/resources/swift/AlamofireImplementations.mustache
samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/APIs.swift
samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift
samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/AlamofireImplementations.swift

I'm not sure if this was intentional but error seems better than erorr.

Fix typo in swift error variable name.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java
samples/client/petstore/csharp/SwaggerClientTest/SwaggerClientTest.userprefs

To fix https://github.com/swagger-api/swagger-codegen/issues/955

[C#] add logic to handle model and its property having the same name

---

modules/swagger-codegen/src/main/resources/php/api.mustache
samples/client/petstore/php/SwaggerClient-php/lib/Api/PetApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/StoreApi.php
samples/client/petstore/php/SwaggerClient-php/lib/ApiClient.php
samples/client/petstore/php/SwaggerClient-php/lib/ObjectSerializer.php

Similar to #1597, #1596
Test cases passed:
```
.............
Time: 7.53 seconds, Memory: 13.25Mb
OK (13 tests, 1878 assertions)
```

[PHP] update auth for PHP API client to skip empty API key/username,password

---

modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/cmd/Meta.java
modules/swagger-codegen/src/main/resources/codegen/pom.mustache

- generate the class name correctly if the name contains hyphen
- make Meta generator take the swagger code gen version

Use the version from the codegen for meta generator

---

modules/swagger-codegen/src/main/resources/Java/enumClass.mustache
modules/swagger-codegen/src/main/resources/Java/model.mustache

Honor Enum's value

---

modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/build.gradle.mustache
samples/client/petstore/java/retrofit2/build.gradle
samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/StringUtil.java

[Java][Retrofit2] update retrofit2 gradle to use double quote

---

modules/swagger-generator/src/test/java/io/swagger/generator/online/OnlineGeneratorOptionsTest.java
samples/client/petstore/objc/SwaggerClientTests/SwaggerClient/Images.xcassets/AppIcon.appiconset/Contents.json

Add exception handling in the test case (for Windows)

---

modules/swagger-codegen/src/main/resources/JavaJaxRS/api.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/apiService.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/apiServiceImpl.mustache
samples/server/petstore/jaxrs/README.md
samples/server/petstore/jaxrs/src/gen/java/io/swagger/api/ApiException.java
samples/server/petstore/jaxrs/src/gen/java/io/swagger/api/ApiOriginFilter.java
samples/server/petstore/jaxrs/src/gen/java/io/swagger/api/ApiResponseMessage.java
samples/server/petstore/jaxrs/src/gen/java/io/swagger/api/NotFoundException.java
samples/server/petstore/jaxrs/src/gen/java/io/swagger/api/PetApi.java
samples/server/petstore/jaxrs/src/gen/java/io/swagger/api/PetApiService.java
samples/server/petstore/jaxrs/src/gen/java/io/swagger/api/StoreApi.java
samples/server/petstore/jaxrs/src/gen/java/io/swagger/api/StoreApiService.java
samples/server/petstore/jaxrs/src/gen/java/io/swagger/api/UserApi.java
samples/server/petstore/jaxrs/src/gen/java/io/swagger/api/UserApiService.java
samples/server/petstore/jaxrs/src/gen/java/io/swagger/model/Category.java
samples/server/petstore/jaxrs/src/gen/java/io/swagger/model/Order.java
samples/server/petstore/jaxrs/src/gen/java/io/swagger/model/Pet.java
samples/server/petstore/jaxrs/src/gen/java/io/swagger/model/Tag.java
samples/server/petstore/jaxrs/src/gen/java/io/swagger/model/User.java
samples/server/petstore/jaxrs/src/main/java/io/swagger/api/impl/PetApiServiceImpl.java
samples/server/petstore/jaxrs/src/main/java/io/swagger/api/impl/StoreApiServiceImpl.java
samples/server/petstore/jaxrs/src/main/java/io/swagger/api/impl/UserApiServiceImpl.java

Resubmit for #1588 
cc @nickcmaynard

[JAX-RS] Inject JAX-RS SecurityContext information into JAX-RS server implementation 

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ClojureClientCodegen.java

[Clojure] Escape characters for text in Clojure client

---

modules/swagger-generator/src/main/webapp/WEB-INF/web.xml

A simple fix to fix XML schema validation on the web.xml file

Fixed xml validation in web.xml

---

modules/swagger-codegen/src/main/resources/Java/ApiClient.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
samples/client/petstore/java/default/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/ApiClient.java

Fix file uploading issue with Java jersey2 client codegen

---

modules/swagger-codegen/src/main/resources/clojure/api.mustache
modules/swagger-codegen/src/main/resources/clojure/core.mustache
samples/client/petstore/clojure/src/swagger_petstore/api/pet.clj
samples/client/petstore/clojure/src/swagger_petstore/api/store.clj
samples/client/petstore/clojure/src/swagger_petstore/api/user.clj
samples/client/petstore/clojure/src/swagger_petstore/core.clj
samples/client/petstore/clojure/test/swagger_petstore/api/pet_test.clj
samples/client/petstore/clojure/test/swagger_petstore/api/store_test.clj
samples/client/petstore/clojure/test/swagger_petstore/api/user_test.clj
samples/client/petstore/clojure/test/swagger_petstore/core_test.clj

* Add authentications support to Clojure client (#1654)
* Support collectionFormat for array parameters in Clojure client (#1655)

Improvements on Clojure client: authentications, collectionFormat

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java

[PHP] fix issue with PHP codegen in Windows

---

modules/swagger-codegen/src/main/resources/TypeScript-node/api.mustache
samples/client/petstore/typescript-node/api.ts
samples/client/petstore/typescript-node/client.ts

- removed `url` from API and only use `basePath` moving forward (consistent with other languages)
- fixed test case
- added OAuth support

[TypeScript][Node] remove url API, fix test case

---

bin/javascript-petstore.sh
bin/windows/javascript-petstore.bat
samples/client/petstore/javascript/src/scripts/rest/api/PetApi.js
samples/client/petstore/javascript/src/scripts/rest/api/StoreApi.js
samples/client/petstore/javascript/src/scripts/rest/api/UserApi.js
samples/client/petstore/javascript/src/scripts/rest/model/Category.js
samples/client/petstore/javascript/src/scripts/rest/model/Order.js
samples/client/petstore/javascript/src/scripts/rest/model/Pet.js
samples/client/petstore/javascript/src/scripts/rest/model/Tag.js
samples/client/petstore/javascript/src/scripts/rest/model/User.js

- added bin/javascript-petstore.sh
- added bin/windows/javascript-petstore.bat
- added petstore samples for JS

[Javascript] add bin and petstore samples

---

modules/swagger-codegen/src/main/resources/php/ApiClient.mustache
modules/swagger-codegen/src/main/resources/php/ObjectSerializer.mustache
modules/swagger-codegen/src/main/resources/php/api.mustache
samples/client/petstore/php/SwaggerClient-php/lib/Api/PetApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/StoreApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/UserApi.php
samples/client/petstore/php/SwaggerClient-php/lib/ApiClient.php
samples/client/petstore/php/SwaggerClient-php/lib/ObjectSerializer.php
samples/client/petstore/php/SwaggerClient-php/tests/PetApiTest.php

- Similar to https://github.com/swagger-api/swagger-codegen/pull/1643
- Added more test cases
- Minor changes to conform the style guide
Updated test cases passed:
```
[INFO] --- exec-maven-plugin:1.2.1:exec (bundle-test) @ PhpPetstoreClientTests ---
..............
Time: 7.71 seconds, Memory: 12.00Mb
OK (14 tests, 1700 assertions)
[INFO] Total time: 10.157 s
[INFO] Finished at: 2015-12-07T00:05:06+08:00
```

[PHP] add `WithHttpInfo` method to return HTTP status code and response headers

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RubyClientCodegen.java
modules/swagger-codegen/src/main/resources/ruby/api_client.mustache
modules/swagger-codegen/src/main/resources/ruby/model.mustache
samples/client/petstore/ruby/lib/petstore/api_client.rb
samples/client/petstore/ruby/lib/petstore/models/category.rb
samples/client/petstore/ruby/lib/petstore/models/order.rb
samples/client/petstore/ruby/lib/petstore/models/pet.rb
samples/client/petstore/ruby/lib/petstore/models/tag.rb
samples/client/petstore/ruby/lib/petstore/models/user.rb
samples/client/petstore/ruby/spec/api_client_spec.rb

* Assign default values to model properties when present in Ruby client.
* Improve checking of JSON MIME to allow "charset" suffix and ignore word case.

[Ruby] Add default value to Ruby model

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConstants.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java

Code refactoring: ensureUniqueParams default value has been mooved from description to the defaaultValue field

Code refactoring: ensureUniqueParams default value has been moved from description to the defaultValue field

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ObjcClientCodegen.java
modules/swagger-codegen/src/main/resources/objc/model-body.mustache
samples/client/petstore/objc/SwaggerClient/SWGCategory.m
samples/client/petstore/objc/SwaggerClient/SWGOrder.m
samples/client/petstore/objc/SwaggerClient/SWGPet.m
samples/client/petstore/objc/SwaggerClient/SWGTag.m
samples/client/petstore/objc/SwaggerClient/SWGUser.m

Similar to #1680 #1683 
Test cases passed:
```
Test Suite 'All tests' passed at 2015-12-09 08:16:15 +0000.
Executed 25 tests, with 0 failures (0 unexpected) in 5.732 (5.750) seconds
[INFO] Total time: 24.550 s
[INFO] Finished at: 2015-12-09T16:16:16+08:00
```

[ObjC] add default value to ObjC model properties

---

modules/swagger-codegen/src/main/resources/objc/ApiClient-body.mustache

Support for extended 'application/json' HeaderAccept types

Support for extended 'application/json' HeaderAccept types

---

pom.xml
samples/client/petstore/java/feign/README.md
samples/client/petstore/java/feign/build.gradle
samples/client/petstore/java/feign/pom.xml
samples/client/petstore/java/feign/settings.gradle
samples/client/petstore/java/feign/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/FormAwareEncoder.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/StringUtil.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/api/UserApi.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Category.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Order.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Pet.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Tag.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/User.java
samples/client/petstore/java/feign/src/test/java/io/swagger/petstore/test/PetApiTest.java
samples/client/petstore/java/feign/src/test/java/io/swagger/petstore/test/StoreApiTest.java
samples/client/petstore/java/feign/src/test/java/io/swagger/petstore/test/UserApiTest.java

- update Java feign sample and test cases

[Java] Update Feign client sample and test cases

---

modules/swagger-codegen/src/main/resources/php/api.mustache
samples/client/petstore/java/feign/README.md
samples/client/petstore/java/feign/build.gradle
samples/client/petstore/java/feign/pom.xml
samples/client/petstore/java/feign/settings.gradle
samples/client/petstore/java/feign/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/FormAwareEncoder.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/StringUtil.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/api/UserApi.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Category.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Order.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Pet.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Tag.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/User.java
samples/client/petstore/java/feign/src/test/java/io/swagger/petstore/test/PetApiTest.java
samples/client/petstore/java/feign/src/test/java/io/swagger/petstore/test/StoreApiTest.java
samples/client/petstore/java/feign/src/test/java/io/swagger/petstore/test/UserApiTest.java
samples/client/petstore/php/SwaggerClient-php/lib/Api/PetApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/StoreApi.php

- for gauging performance.
- also fix empty/null string check for apikey/username,password/oauth token

[PHP] add Php profiler for petstore sample

---

modules/swagger-codegen/src/main/resources/objc/ApiClient-body.mustache
modules/swagger-codegen/src/main/resources/objc/api-body.mustache
modules/swagger-codegen/src/main/resources/objc/model-body.mustache
samples/client/petstore/objc/SwaggerClient/SWGApiClient.m
samples/client/petstore/objc/SwaggerClient/SWGCategory.m
samples/client/petstore/objc/SwaggerClient/SWGOrder.m
samples/client/petstore/objc/SwaggerClient/SWGPet.m
samples/client/petstore/objc/SwaggerClient/SWGPetApi.m
samples/client/petstore/objc/SwaggerClient/SWGTag.m
samples/client/petstore/objc/SwaggerClient/SWGUser.m
samples/client/petstore/objc/SwaggerClient/SWGUserApi.m

- minor style change
- update Petstore sample
Test cases passed:
```
[INFO] Total time: 01:30 min
[INFO] Finished at: 2015-12-10T14:51:30+08:00
```

[ObjC] minor style change for objc client

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SinatraServerCodegen.java
modules/swagger-codegen/src/main/resources/sinatra/Swaggering.rb
modules/swagger-codegen/src/main/resources/sinatra/api.mustache
modules/swagger-codegen/src/main/resources/sinatra/my_app.mustache
modules/swagger-codegen/src/main/resources/sinatra/swagger.mustache
samples/server/petstore/sinatra/api/pet_api.rb
samples/server/petstore/sinatra/api/store_api.rb
samples/server/petstore/sinatra/api/user_api.rb
samples/server/petstore/sinatra/lib/swaggering.rb
samples/server/petstore/sinatra/my_app.rb
samples/server/petstore/sinatra/swagger.yaml

For #1713
- fix bug with adding routes
- add swagger.yaml (replacing resources.json)

[Ruby][Sinatra] fix bug with adding routes and add swagger.yaml

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java

Add binary, byte array properties

---

modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/okhttp-gson/src/test/java/io/swagger/client/ApiClientTest.java

Java okhttp-gson client: get/set connect timeout

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/InlineModelResolver.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/InlineModelResolverTest.java

Fix array/map inline response/model

---

modules/swagger-codegen/src/main/resources/ruby/api_client.mustache
modules/swagger-codegen/src/main/resources/ruby/configuration.mustache
samples/client/petstore/ruby/lib/petstore/api_client.rb
samples/client/petstore/ruby/lib/petstore/configuration.rb
samples/client/petstore/ruby/spec/api_client_spec.rb

Allow customizing request timeout in Ruby client.

Ruby client: add "timeout" to configuration

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java

[C#] Escape \r in XML comments

---

modules/swagger-codegen-maven-plugin/src/main/java/io/swagger/codegen/plugin/AdditionalParams.java
modules/swagger-codegen-maven-plugin/src/main/java/io/swagger/codegen/plugin/CodeGenMojo.java

added library param

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JaxRSServerCodegen.java
modules/swagger-codegen/src/main/resources/JavaJaxRS/jersey1_18/README.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/jersey1_18/pom.mustache

added `serverPort`

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AndroidClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PerlClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java

CliOption.type has been set to "boolean" for boolean options

CliOption.type has been set to "boolean" for boolean options

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenProperty.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/InlineModelResolver.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/config/CodegenConfigurator.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AsyncScalaClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ClojureClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FlashClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RubyClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ScalaClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SinatraServerCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwiftCodegen.java

This pull request is focused on resolving occurrences of Sonar rule pmd:RedundantFieldInitializer - Redundant Field Initializer
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=pmd:RedundantFieldInitializer
Please let me know if you have any questions.
Kirill Vlasov

Redundant Field Initializer

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CliOption.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConstants.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AndroidClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PerlClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/languages/BooleanOptionsTest.java

Default values have been added to the boolean options.

Default values have been added to the boolean options

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
modules/swagger-codegen/src/main/resources/Java/model.mustache
samples/client/petstore/java/default/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/ApiException.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/Configuration.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/Pair.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/StringUtil.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/api/UserApi.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/ApiKeyAuth.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/Authentication.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/HttpBasicAuth.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/OAuth.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Category.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Order.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Pet.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Tag.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/User.java

[Java] To fix missing imports in inline models

---

.travis.yml
README.md
modules/swagger-generator/Dockerfile
modules/swagger-generator/pom.xml
modules/swagger-generator/src/main/java/io/swagger/generator/Bootstrap.java
modules/swagger-generator/src/main/resources/logback.xml
modules/swagger-generator/src/main/webapp/WEB-INF/web.xml
modules/swagger-generator/src/main/webapp/index.html

added Docker support

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/java/JavaModelEnumTest.java

updated parentModel names in inheritence situations

---

.travis.yml
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/NodeJSServerCodegen.java
modules/swagger-codegen/src/main/resources/nodejs/README.mustache

added serverPort detection from the spec

---

.travis.yml
README.md
modules/swagger-codegen/src/main/resources/perl/README.mustache
modules/swagger-codegen/src/main/resources/perl/Role.mustache

pre-testing https://github.com/swagger-api/swagger-codegen/pull/1835

Arnested java 8 doc travis

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AndroidClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AsyncScalaClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ScalaClientCodegen.java

testing https://github.com/swagger-api/swagger-codegen/pull/1830

Wing328 android reserved word travis

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AndroidClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AsyncScalaClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ScalaClientCodegen.java

Update reserved word list to include local variable names for android, scala

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RubyClientCodegen.java
modules/swagger-codegen/src/main/resources/ruby/gemspec.mustache
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/RubyClientOptionsProvider.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/ruby/RubyClientOptionsTest.java

for https://github.com/swagger-api/swagger-codegen/pull/1829

Kevin glinski master travis

---

modules/swagger-codegen/src/main/resources/php/ObjectSerializer.mustache
modules/swagger-codegen/src/main/resources/php/api.mustache
samples/client/petstore/android/default/src/test/java/io/swagger/petstore/test/PetApiTest.java
samples/client/petstore/php/SwaggerClient-php/lib/Api/PetApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/StoreApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/UserApi.php
samples/client/petstore/php/SwaggerClient-php/lib/ObjectSerializer.php
samples/client/petstore/php/SwaggerClient-php/tests/OrderApiTest.php

No issue has been reported for this. Adding more test cases just to make sure the deserialization of array of array and map of map are good.

[PHP] add more test case for php (array of array, map of map)

---

modules/swagger-codegen/src/main/resources/Java/ApiClient.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
samples/client/petstore/java/default/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/ApiClient.java

[Java] Support setting connect timeout for the default and jersey2 clients

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
modules/swagger-codegen/src/main/resources/Java/libraries/feign/ApiClient.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/feign/auth/ApiKeyAuth.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/feign/auth/HttpBasicAuth.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/feign/auth/OAuth.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/feign/pom.mustache
samples/client/petstore/java/feign/pom.xml
samples/client/petstore/java/feign/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/FormAwareEncoder.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/StringUtil.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/api/UserApi.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/auth/ApiKeyAuth.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/auth/HttpBasicAuth.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/auth/OAuth.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/auth/OAuthFlow.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Category.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Order.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Pet.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Tag.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/User.java

Based on the retrofit generator methods.
I will do OAuth later since it is more work.
Fix #1840

Add auth support to feign library

---

modules/swagger-codegen/src/main/resources/php/ObjectSerializer.mustache
samples/client/petstore/php/SwaggerClient-php/lib/ObjectSerializer.php
samples/client/petstore/php/SwaggerClient-php/tests/ObjectSerializerTest.php
samples/client/petstore/php/SwaggerClient-php/tests/PetApiTest.php

To address the security issue mentioned in https://github.com/swagger-api/swagger-codegen/issues/1848

[PHP] better filename handling in ObjectSerializer

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JaxRSServerCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/JavaOptionsProvider.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/JaxRSServerOptionsProvider.java

added date library option

---

modules/swagger-codegen/src/main/resources/csharp/README.md
samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/README.md

[C#] update README based on developer's feedback

---

samples/client/petstore/php/SwaggerClient-php/tests/PetApiTest.php
samples/client/petstore/php/test.php

- added test cases for findPetsByTags
- update test.php with correct way to set the debug flag

[PHP] add test cases for findPetsByTags

---

CONTRIBUTING.md
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java
samples/client/petstore/javascript/src/model/Pet.js
samples/client/petstore/javascript/test/api/PetApiTest.js

[JavaScript] Fix initialization issues on array and nested model fields

---

modules/swagger-codegen/src/main/resources/JavaSpringMVC/api.mustache
modules/swagger-codegen/src/main/resources/JavaSpringMVC/pom.mustache
samples/server/petstore/spring-mvc/pom.xml
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/ApiException.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/ApiOriginFilter.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/ApiResponseMessage.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/NotFoundException.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/PetApi.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/StoreApi.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/UserApi.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/configuration/SwaggerConfig.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/configuration/SwaggerUiConfiguration.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/configuration/WebApplication.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/configuration/WebMvcConfiguration.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/model/ApiResponse.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/model/Category.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/model/Order.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/model/Pet.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/model/Tag.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/model/User.java

- Changed the templates
- Removed unused dependencies
- Updated generated samples

Updated the code generation for spring mvc

---

modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/cmd/Generate.java
modules/swagger-codegen-cli/src/test/java/io/swagger/codegen/cmd/utils/OptionUtilsTest.java
modules/swagger-codegen-maven-plugin/src/main/java/io/swagger/codegen/plugin/CodeGenMojo.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/utils/OptionUtils.java
modules/swagger-codegen/src/main/resources/htmlDocs/bodyParam.mustache
modules/swagger-codegen/src/main/resources/htmlDocs/formParam.mustache
modules/swagger-codegen/src/main/resources/htmlDocs/headerParam.mustache
modules/swagger-codegen/src/main/resources/htmlDocs/pathParam.mustache
modules/swagger-codegen/src/main/resources/htmlDocs/queryParam.mustache

added args for maven plugin

---

modules/swagger-codegen/src/main/resources/htmlDocs/bodyParam.mustache
modules/swagger-codegen/src/main/resources/htmlDocs/formParam.mustache
modules/swagger-codegen/src/main/resources/htmlDocs/headerParam.mustache
modules/swagger-codegen/src/main/resources/htmlDocs/pathParam.mustache
modules/swagger-codegen/src/main/resources/htmlDocs/queryParam.mustache

switched from `paramName` to `baseName` to avoid changing format

---

modules/swagger-codegen/src/test/java/io/swagger/codegen/csharp/CSharpModelTest.java

These are unit tests to accompany #1964.
I looked into testing the generator (as bound to the mustache template) and didn't see anything language specific, so I decided against those tests.

[csharp] Model tests for List/Collection options

---

modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/cmd/Meta.java
modules/swagger-codegen/src/main/java/config/ConfigParser.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/AbstractGenerator.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/Codegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/MetaGenerator.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/auth/AuthParser.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/config/CodegenConfigurator.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FlaskConnexionCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaInflectorServerCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/NodeJSServerCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SinatraServerCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwaggerGenerator.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwaggerYamlGenerator.java
modules/swagger-generator/src/main/java/io/swagger/generator/online/Generator.java
samples/client/petstore/php/SwaggerClient-php/lib/ObjectSerializer.php

Rebase on latest master for "Using logger instead of System.out #1871"

---

modules/swagger-codegen/src/main/resources/csharp/model.mustache
samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/Category.cs
samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/Order.cs
samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/Pet.cs
samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/Tag.cs
samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/User.cs
samples/client/petstore/csharp/SwaggerClientTest/SwaggerClientTest.userprefs

For #2015 
All 26 test cases passed without issues.

[C#] add partial to C# model

---

README.md
Vagrantfile

Run docker in vagrant without sudo and won't check locale settings

---

modules/swagger-codegen/src/main/resources/Javascript/model.mustache

Use prototypes for model methods

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/resources/python/api.mustache
modules/swagger-codegen/src/main/resources/python/api_client.mustache
samples/client/petstore/python/swagger_client/__init__.py
samples/client/petstore/python/swagger_client/api_client.py
samples/client/petstore/python/swagger_client/apis/__init__.py
samples/client/petstore/python/swagger_client/apis/pet_api.py
samples/client/petstore/python/swagger_client/apis/store_api.py
samples/client/petstore/python/swagger_client/apis/user_api.py

#2046 with proper author email.

[Python] Fix for Python client upload list of files Issue #2036

---

samples/client/petstore/javascript/src/model/Category.js
samples/client/petstore/javascript/src/model/Order.js
samples/client/petstore/javascript/src/model/Pet.js
samples/client/petstore/javascript/src/model/Tag.js
samples/client/petstore/javascript/src/model/User.js

This is just the result of running ./bin/javascript-petstore.sh
after the fix for #2044.

Modify JS PetStore tests for prototypes change

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AspNet5ServerCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/aspnet5/AspNet5ServerOptionsTest.java
samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Properties/AssemblyInfo.cs

This moves a bit of logic into a base type to prevent lots of duplicates.
I've only converted csharp and aspnet5 generators, not csharp 2.0.
This base class should provide enough flexibility to support other C# based client and server generators.
Please let me know if you think I should also convert the csharp 2.0 generator. My reason for leaving it as-is was that few people are probably using C# 2.0 anymore and bugs in that generator could have a negative effect in C# 3.0 and higher. I admit my reasoning could be off.

[csharp][aspnet5] AbstractCSharpCodegen base

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaInflectorServerCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaJerseyServerCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaResteasyServerCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/NodeJSServerCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/DefaultGeneratorTest.java

added `writeOptional` method to avoid clobbering files

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaJerseyServerCodegen.java
modules/swagger-codegen/src/main/resources/Java/pojo.mustache
modules/swagger-codegen/src/main/resources/JavaInflector/pojo.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/jersey1_18/apiServiceImpl.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/jersey1_18/pojo.mustache
modules/swagger-codegen/src/test/java/io/swagger/codegen/java/JavaModelTest.java

added example value

---

modules/swagger-codegen/src/main/resources/JMeter/api.mustache

Add basePath without url to jmeter sampler path

Closes #2118

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java
samples/client/petstore/ruby/press_anykey_to_continue.sh

[C#] map `uuid` to 'Guid`in C# abstract base class

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java

[C#] fix dollar sign in parameter name

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/DefaultGeneratorTest.java
modules/swagger-codegen/src/test/resources/2_0/petstore.json
samples/client/petstore/php/SwaggerClient-php/lib/Api/PetApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/StoreApi.php

Previously, only the 1st security setting is used.
This PR is based on work by @jasonmartens (#1961)

Add support for multi-authentication setting

---

modules/swagger-codegen/src/main/resources/Javascript/api.mustache
samples/client/petstore/javascript/src/ApiClient.js
samples/client/petstore/javascript/src/api/PetApi.js
samples/client/petstore/javascript/src/api/StoreApi.js
samples/client/petstore/javascript/test/ApiClientTest.js

* Update Petstore sample and fix tests.
* Fix call to buildCollectionParam (#2166).

[JavaScript] Some bug fixes

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConfig.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java
samples/client/petstore/ruby/lib/petstore/api/pet_api.rb
samples/client/petstore/ruby/lib/petstore/api/store_api.rb
samples/client/petstore/ruby/lib/petstore/configuration.rb

For processing all models before generating the model files.

Add postProcessAllModels to default generator

---

modules/swagger-codegen/src/main/resources/Java/ApiClient.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/build.gradle.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/pom.mustache
samples/client/petstore/java/default/build.gradle
samples/client/petstore/java/default/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/jersey2/README.md
samples/client/petstore/java/jersey2/build.gradle
samples/client/petstore/java/jersey2/pom.xml

[Java] Add getter/setter methods for objectMapper and httpClient in ApiClient

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java

Map $ to value for parameter/property name

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java
modules/swagger-codegen/src/main/resources/php/.travis.yml
modules/swagger-codegen/src/main/resources/php/README.mustache
samples/client/petstore/php/SwaggerClient-php/.travis.yml
samples/client/petstore/php/SwaggerClient-php/README.md

- add readme for PHP with installation procedure
- add .travis.yml for better continuous integration with travis-ci.org

[PHP] auto generate README.md and .travis.yml (for CI)

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaJAXRSServerCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaInflectorServerCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaJerseyServerCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaResteasyServerCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/NodeJSServerCodegen.java

added folder to writeOptional

---

modules/swagger-codegen/src/main/resources/csharp/api.mustache
samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/README.md
samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Api/PetApi.cs
samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Api/StoreApi.cs
samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Api/UserApi.cs

- added <exception></exception> to method documentation
- removed the use of `apiKeyValue` as there's no need

[C#] add "exception" documentation to methods

---

modules/swagger-generator/src/main/java/io/swagger/generator/DynamicSwaggerConfig.java
modules/swagger-generator/src/main/java/io/swagger/generator/resource/SwaggerResource.java

added sort

---

modules/swagger-generator/src/main/java/io/swagger/generator/DynamicSwaggerConfig.java
modules/swagger-generator/src/main/java/io/swagger/generator/resource/SwaggerResource.java

Use case insensitive sort for list returned by the generator

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java
modules/swagger-codegen/src/main/resources/Javascript/model.mustache

[JavaScript] Fix handling of reserved words for property name

---

modules/swagger-codegen/src/main/resources/Java/api.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/api.mustache
samples/client/petstore/java/default/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/api/UserApi.java
samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/api/UserApi.java

Add ApiException to javadoc client and some indentation fixes.

[Java] Add ApiException to javadoc

---

modules/swagger-codegen/src/test/java/io/swagger/codegen/csharp/CSharpModelTest.java

Test cases based on ObjC model tests.

[C#] add more test cases for csharp model

---

CONTRIBUTING.md
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwiftCodegen.java

Better follow Swift code style for naming of parameters and variables.

Issue 2084

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RubyClientCodegen.java
modules/swagger-codegen/src/main/resources/python/api.mustache
modules/swagger-codegen/src/main/resources/ruby/api.mustache
samples/client/petstore/php/SwaggerClient-php/lib/Api/PetApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/StoreApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Tests/StoreApiTest.php
samples/client/petstore/python/swagger_client/apis/pet_api.py
samples/client/petstore/python/swagger_client/apis/store_api.py
samples/client/petstore/python/swagger_client/apis/user_api.py
samples/client/petstore/ruby/lib/petstore/api/pet_api.rb
samples/client/petstore/ruby/lib/petstore/api/store_api.rb
samples/client/petstore/ruby/lib/petstore/api/user_api.rb
samples/client/petstore/ruby/lib/petstore/configuration.rb
samples/client/petstore/ruby/spec/api/PetApi_spec.rb
samples/client/petstore/ruby/spec/api/StoreApi_spec.rb

[Ruby][Python][PHP] better local variable naming for ruby, python and php

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
modules/swagger-codegen/src/main/resources/Java/api.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/api.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/api.mustache
samples/client/petstore/java/default/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/api/UserApi.java
samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/api/UserApi.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/api/UserApi.java

[Java] better local variable naming for Java clients

---

modules/swagger-codegen/src/main/resources/Javascript/model.mustache
samples/client/petstore/javascript-promise/src/ApiClient.js
samples/client/petstore/javascript-promise/src/api/PetApi.js
samples/client/petstore/javascript-promise/src/api/StoreApi.js
samples/client/petstore/javascript-promise/src/model/Category.js
samples/client/petstore/javascript-promise/src/model/Order.js
samples/client/petstore/javascript-promise/src/model/Pet.js
samples/client/petstore/javascript-promise/src/model/Tag.js
samples/client/petstore/javascript-promise/src/model/User.js
samples/client/petstore/javascript/src/ApiClient.js
samples/client/petstore/javascript/src/api/PetApi.js
samples/client/petstore/javascript/src/api/StoreApi.js
samples/client/petstore/javascript/src/index.js
samples/client/petstore/javascript/src/model/Category.js
samples/client/petstore/javascript/src/model/Order.js
samples/client/petstore/javascript/src/model/Pet.js
samples/client/petstore/javascript/src/model/Tag.js
samples/client/petstore/javascript/src/model/User.js

Also regenerates the petstore samples.
See discussion on https://github.com/swagger-api/swagger-codegen/pull/2075 https://github.com/swagger-api/swagger-codegen/issues/2258

Remove toJson method from JS client

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwiftCodegen.java
samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift
samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift
samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift
samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/Models.swift

- better handling of reserved word as model name
- add prefix/suffix support
- better handling of model name and file name (camelize instead of initialCaps)
- fix indention in swift codegen file
All test cases passed:
```
Test Case '-[SwaggerClientTests.UserAPITests testLogin]' passed (0.568 seconds).
Test Case '-[SwaggerClientTests.UserAPITests testLogout]' started.
Test Case '-[SwaggerClientTests.UserAPITests testLogout]' passed (1.312 seconds).
Test Suite 'UserAPITests' passed at 2016-03-02 16:32:48.173.
Executed 5 tests, with 0 failures (0 unexpected) in 3.505 (3.508) seconds
Test Suite 'SwaggerClientTests.xctest' passed at 2016-03-02 16:32:48.173.
Executed 11 tests, with 0 failures (0 unexpected) in 7.532 (7.541) seconds
[INFO] …
```

[Swift] improvements to model

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java

issue-2904 mark 'findMethodResponse' method in DefaultCodegen.java as 'protected'

---

modules/swagger-codegen/src/main/resources/Javascript/ApiClient.mustache
modules/swagger-codegen/src/main/resources/Javascript/index.mustache
samples/client/petstore/javascript/src/ApiClient.js
samples/client/petstore/javascript/src/api/PetApi.js
samples/client/petstore/javascript/src/api/StoreApi.js
samples/client/petstore/javascript/src/index.js
samples/client/petstore/javascript/src/model/InlineResponse200.js
samples/client/petstore/javascript/src/model/ObjectReturn.js
samples/client/petstore/javascript/src/model/SpecialModelName.js
samples/client/petstore/javascript/test/api/PetApiTest.js
samples/client/petstore/javascript/test/api/StoreApiTest.js
samples/client/petstore/javascript/test/run_tests.html

* Fix #2165
* Update JS client of the Petstore sample
* Add test cases for getPetByIdInObject and getInventoryInObject

[JavaScript] Handle arbitrary object in JavaScript client

---

modules/swagger-codegen/src/main/resources/csharp/model.mustache
modules/swagger-codegen/src/test/resources/2_0/petstore.json
samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient.Test/PetApiTests.cs
samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient.Test/StoreApiTests.cs
samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient.Test/UserApiTests.cs
samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/compile.bat
samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Api/PetApi.cs
samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Api/StoreApi.cs
samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Api/UserApi.cs
samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/ModelReturn.cs
samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/Name.cs
samples/client/petstore/csharp/SwaggerClientTest/SwaggerClientTest.csproj
samples/client/petstore/csharp/SwaggerClientTest/SwaggerClientTest.userprefs
samples/client/petstore/csharp/SwaggerClientTest/obj/Debug/SwaggerClientTest.csproj.FilesWrittenAbsolute.txt
samples/server/petstore/jaxrs-resteasy/src/gen/java/io/swagger/model/InlineResponse200.java
samples/server/petstore/jaxrs-resteasy/src/gen/java/io/swagger/model/ModelReturn.java
samples/server/petstore/jaxrs-resteasy/src/gen/java/io/swagger/model/SpecialModelName.java

- escaped HTML special character in Model's summary and value
- added a model with both model name and property name set to `Name'

[C#] escape HTML special character in Model's summary and value

---

modules/swagger-codegen/src/main/resources/Java/pom.mustache
samples/client/petstore/java/default/src/main/java/io/swagger/client/ApiException.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/Configuration.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/Pair.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/StringUtil.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/api/UserApi.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/ApiKeyAuth.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/HttpBasicAuth.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/OAuth.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/InlineResponse200.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/ModelReturn.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Name.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Order.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Pet.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/SpecialModelName.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Tag.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/User.java

Fixes #2353 
This also updates the generated petstore, due to previous
changes (not mine).

Fix warnings in generated pom.xml file

---

README.md

Add LANDR Audio to the list of companies using Swagger Codegen

Add LANDR Audio to the list of companies

---

modules/swagger-codegen/src/test/resources/2_0/petstore_full.yml

Added petstore_full.yml (obtained from https://editor.swagger.io)

Add petstore (full) yml file

---

modules/swagger-codegen/src/main/resources/JavaJaxRS/resteasy/model.mustache
pom.xml
samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/Name.cs
samples/server/petstore/jaxrs-resteasy/src/gen/java/io/swagger/api/ApiException.java
samples/server/petstore/jaxrs-resteasy/src/gen/java/io/swagger/api/ApiOriginFilter.java
samples/server/petstore/jaxrs-resteasy/src/gen/java/io/swagger/api/ApiResponseMessage.java
samples/server/petstore/jaxrs-resteasy/src/gen/java/io/swagger/api/NotFoundException.java
samples/server/petstore/jaxrs-resteasy/src/gen/java/io/swagger/api/PetApi.java
samples/server/petstore/jaxrs-resteasy/src/gen/java/io/swagger/api/PetApiService.java
samples/server/petstore/jaxrs-resteasy/src/gen/java/io/swagger/api/PettestingByteArraytrueApi.java
samples/server/petstore/jaxrs-resteasy/src/gen/java/io/swagger/api/PettestingByteArraytrueApiService.java
samples/server/petstore/jaxrs-resteasy/src/gen/java/io/swagger/api/StoreApi.java
samples/server/petstore/jaxrs-resteasy/src/gen/java/io/swagger/api/StoreApiService.java
samples/server/petstore/jaxrs-resteasy/src/gen/java/io/swagger/api/StringUtil.java
samples/server/petstore/jaxrs-resteasy/src/gen/java/io/swagger/api/UserApi.java
samples/server/petstore/jaxrs-resteasy/src/gen/java/io/swagger/api/UserApiService.java
samples/server/petstore/jaxrs-resteasy/src/gen/java/io/swagger/model/Category.java
samples/server/petstore/jaxrs-resteasy/src/gen/java/io/swagger/model/InlineResponse200.java
samples/server/petstore/jaxrs-resteasy/src/gen/java/io/swagger/model/ModelReturn.java
samples/server/petstore/jaxrs-resteasy/src/gen/java/io/swagger/model/Order.java
samples/server/petstore/jaxrs-resteasy/src/gen/java/io/swagger/model/Pet.java
samples/server/petstore/jaxrs-resteasy/src/gen/java/io/swagger/model/SpecialModelName.java
samples/server/petstore/jaxrs-resteasy/src/gen/java/io/swagger/model/Tag.java
samples/server/petstore/jaxrs-resteasy/src/gen/java/io/swagger/model/User.java
samples/server/petstore/jaxrs-resteasy/src/main/java/io/swagger/api/impl/PetApiServiceImpl.java
samples/server/petstore/jaxrs-resteasy/src/main/java/io/swagger/api/impl/StoreApiServiceImpl.java
samples/server/petstore/jaxrs-resteasy/src/main/java/io/swagger/api/impl/UserApiServiceImpl.java

- fix RestEasy's model missing java.util.ArrayList (the fix is not ideal as java.util.ArrayList is hardcoded in the template)
- update pom.xml to cover JAX-RS RestEasy Petstore
- reformat code with proper indentation
cc @krisztiankocsis, @chameleon82

[JAX-RS] Fix RestEasy's model missing java.util.ArrayList 

---

modules/swagger-codegen/src/main/resources/android/build.mustache
modules/swagger-codegen/src/main/resources/android/libraries/volley/apiInvoker.mustache
modules/swagger-codegen/src/main/resources/android/libraries/volley/build.mustache
samples/client/petstore/android/default/build.gradle
samples/client/petstore/android/default/src/main/java/io/swagger/client/model/Name.java
samples/client/petstore/android/volley/build.gradle
samples/client/petstore/android/volley/src/main/java/io/swagger/client/ApiInvoker.java
samples/client/petstore/android/volley/src/main/java/io/swagger/client/model/Name.java

Now both compile (but some test cases failed that need a further look)
To fix #2451

[Android] update build.gradle for android (default, volley)

---

bin/sinatra-petstore-server.sh
modules/swagger-codegen/src/test/resources/2_0/petstore.json
modules/swagger-codegen/src/test/resources/2_0/petstore.yaml
samples/server/petstore/sinatra/api/pet_api.rb
samples/server/petstore/sinatra/api/store_api.rb
samples/server/petstore/sinatra/api/user_api.rb
samples/server/petstore/sinatra/lib/swaggering.rb
samples/server/petstore/sinatra/swagger.yaml

[Sinatra] fix typo, update sinatra to use origianl petstore spec (yaml)

---

modules/swagger-codegen/src/main/resources/asyncscala/api.mustache
modules/swagger-codegen/src/main/resources/asyncscala/client.mustache
modules/swagger-codegen/src/main/resources/asyncscala/model.mustache
modules/swagger-codegen/src/main/resources/asyncscala/sbt.mustache

Simple dependency fix for the scala async client.

fixed swagger-async-httpclient lib dependency

---

pom.xml

To support nice structured `mustache` syntax, mentioned [here](https://github.com/samskivert/jmustache#newline-trimming).

Update JMustache dependency to support whitespace and line breaks trimming

---

modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/build.gradle.mustache
samples/client/petstore/java/retrofit2/build.gradle

Provide dependency javax.annotation for android with Retrofit 2

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenProperty.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java
modules/swagger-codegen/src/main/resources/csharp/model.mustache
modules/swagger-codegen/src/test/resources/2_0/petstore.json
samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/FormatTest.cs
samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Model/Name.cs
samples/client/petstore/csharp/SwaggerClientTest/SwaggerClientTest.csproj
samples/client/petstore/csharp/SwaggerClientTest/SwaggerClientTest.userprefs

[C#] fix extra comma in the constructor when last property is read-only

---

samples/client/petstore/python/tests/test_api_exception.py

@wing328 please help to review.

issue2061_fix_DeprecationWarning_in_unit_tests

---

modules/swagger-codegen/src/test/resources/2_0/petstore.yaml
samples/client/petstore/go/swagger/Category.go
samples/client/petstore/go/swagger/Order.go
samples/client/petstore/go/swagger/Pet.go
samples/client/petstore/go/swagger/PetApi.go
samples/client/petstore/go/swagger/StoreApi.go
samples/client/petstore/go/swagger/Tag.go
samples/client/petstore/go/swagger/User.go
samples/client/petstore/go/swagger/UserApi.go
samples/client/petstore/go/test.go

Restored petstore.yaml from http://petstore.swagger.io/v2/swagger.json and fixed some typo (as reported in https://github.com/swagger-api/swagger-codegen/pull/2520)

[Petstore] restore petstore.yaml from http://petstore.swagger.io/v2/swagger.json

---

samples/client/petstore/go/petApi_test.go
samples/client/petstore/go/swagger/ApiResponse.go

@wing328 yes, the last PR fixed the api issue, i clean up the code a little bit. however, the tests are still failing because `GetPetById` is not returning any object, do you know what happened? i can't access the api via http call.
#1948

issue #1948, added missing apiresponse.go, renamed petapi_test.go, fixed compilation error

---

modules/swagger-codegen/src/main/resources/htmlDocs/index.mustache
samples/html/index.html

Replaced {{#isNotRequired}} with {{^required}}

[Doc] minor fix to html doc

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/GoClientCodegen.java
modules/swagger-codegen/src/main/resources/go/model.mustache
modules/swagger-codegen/src/test/resources/2_0/petstore.json
samples/client/petstore/go/swagger/ApiResponse.go
samples/client/petstore/go/swagger/Category.go
samples/client/petstore/go/swagger/ModelReturn.go
samples/client/petstore/go/swagger/Name.go
samples/client/petstore/go/swagger/Order.go
samples/client/petstore/go/swagger/Pet.go
samples/client/petstore/go/swagger/Tag.go
samples/client/petstore/go/swagger/User.go

- update type mapping (e.g. number, byte array)
- fix indention in go model (due to version change in jmustache)

[Go] update type mapping, fix indention in go model

---

modules/swagger-codegen/src/main/resources/go/model.mustache
samples/client/petstore/go/swagger/ApiResponse.go
samples/client/petstore/go/swagger/Category.go
samples/client/petstore/go/swagger/Order.go
samples/client/petstore/go/swagger/Pet.go
samples/client/petstore/go/swagger/Tag.go
samples/client/petstore/go/swagger/User.go

issue #2548, added docstring to Go model and its properties

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FlaskConnexionCodegen.java
modules/swagger-codegen/src/main/resources/flaskConnexion/controller.mustache
samples/server/petstore/flaskConnexion/app.py
samples/server/petstore/flaskConnexion/controllers/default_controller.py
samples/server/petstore/flaskConnexion/swagger/swagger.yaml

For https://github.com/swagger-api/swagger-codegen/issues/2517

[Python][Flask] add support for python2

---

modules/swagger-codegen/src/main/resources/go/api.mustache
modules/swagger-codegen/src/main/resources/go/configuration.mustache
samples/client/petstore/go/swagger/Configuration.go
samples/client/petstore/go/swagger/PetApi.go
samples/client/petstore/go/swagger/StoreApi.go
samples/client/petstore/go/swagger/UserApi.go

link #2535, i am not sure what `GetApiKeyWithPrefix` is, so i did not implement it, let me know if you still want this, and please explain how

issue #2535, added authentication header for GO

---

modules/swagger-codegen/src/main/resources/go/api.mustache
samples/client/petstore/go/swagger/PetApi.go
samples/client/petstore/go/swagger/StoreApi.go
samples/client/petstore/go/swagger/UserApi.go

remove unneeded function line

---

modules/swagger-codegen/src/main/resources/go/configuration.mustache
samples/client/petstore/go/swagger/Configuration.go

Removed local variable declaration in Go

---

modules/swagger-codegen/src/main/resources/flaskConnexion/controller.mustache
samples/server/petstore/flaskConnexion/controllers/default_controller.py

For https://github.com/swagger-api/swagger-codegen/issues/2576

[Python][Flask] add optional argument to flask controller

---

modules/swagger-codegen/src/test/java/io/swagger/codegen/go/GoModelTest.java

added import tests for Go

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/GoClientCodegen.java
modules/swagger-codegen/src/main/resources/go/api.mustache

This PR addresses issue #2564.
See previous discussion on PR https://github.com/swagger-api/swagger-codegen/pull/2568

Issue #2564 : Query structs now export their fields

---

modules/swagger-codegen/src/main/resources/swift/api.mustache
samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift
samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift
samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift
samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/Models.swift
samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/Models/FormatTest.swift
samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/Models/InlineResponse200.swift

make sure user is not forced to pass nil for optional parameters

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/GoClientCodegen.java
modules/swagger-codegen/src/main/resources/go/api.mustache
modules/swagger-codegen/src/main/resources/go/api_client.mustache
modules/swagger-codegen/src/main/resources/go/configuration.mustache
samples/client/petstore/go/swagger/api_client.go
samples/client/petstore/go/swagger/configuration.go
samples/client/petstore/go/swagger/pet_api.go
samples/client/petstore/go/swagger/store_api.go
samples/client/petstore/go/swagger/user_api.go

for #2543 , the generated Go code compiled successful, but not tested the actual code

issue#2543: added api_client to set content-type and accept for http request

---

modules/swagger-codegen/src/main/resources/Groovy/api.mustache
modules/swagger-codegen/src/main/resources/asyncscala/api.mustache
modules/swagger-codegen/src/main/resources/dart/api.mustache
modules/swagger-codegen/src/main/resources/flash/api.mustache
modules/swagger-codegen/src/main/resources/scala/api.mustache

I replaced all occurrences of {{#requiredParamCount}} {{/requriredParamCount}} with {{#allParams}} {{/allParams}} this should fix all templates but did not test it !

replaced requiredParamCount with allParams

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/GoClientCodegen.java
modules/swagger-codegen/src/main/resources/go/pom.mustache
samples/client/petstore/go/pet_api_test.go
samples/client/petstore/go/pom.xml

For #2611, @wing328, I couldn't find any better way to build the Go code except using ant run. let me know if you have a better way, i am new to maven.

issue#2611: added pom.xml for building Go

---

modules/swagger-codegen/src/main/resources/go/api.mustache
samples/client/petstore/go/swagger/pet_api.go
samples/client/petstore/go/swagger/store_api.go
samples/client/petstore/go/swagger/user_api.go

added required parameters validation for Go

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenOperation.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java

This matches the recent changes in Model, Property and Parameter https://github.com/swagger-api/swagger-codegen/pull/2629

add unescapedNotes to CodegenOperation

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/config/CodegenConfigurator.java

For https://github.com/swagger-api/swagger-codegen/issues/2604

Add exception handling for template directory that does not exist

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/NodeJSServerCodegen.java

This is a fix for [issue-2621](https://github.com/swagger-api/swagger-codegen/issues/2621)

include underscore when generating nodejs controller and service method

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Qt5CPPGenerator.java

To fix https://github.com/swagger-api/swagger-codegen/issues/2706

[Qt5][C++] fix date mapping in qt5cpp

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/ClientOpts.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenModel.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenOperation.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenParameter.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenProperty.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenResponse.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenSecurity.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/SupportingFile.java

issue #2711 adding equals, hashcode etc to model classes

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java

Better naming (easier to understand) for the function

Renmae toJSONSchemaPattern to toRegularExpression

---

modules/swagger-codegen/src/main/resources/go/api_response.mustache

issue #2717 - go code won't compile due to not respecting packageName variable

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/GoClientCodegen.java
modules/swagger-codegen/src/main/resources/go/api.mustache
samples/client/petstore/go/go-petstore/pet_api.go
samples/client/petstore/go/go-petstore/store_api.go
samples/client/petstore/go/go-petstore/user_api.go

@neilotoole can you confirm if this will fix your issue or not?
@wing328 the idea is to check the return type to see if it is primitive, if it is, add the custom import, let me know if you have a better approach.
For #2725

Issue #2725: added condition to import json based on return type

---

samples/client/petstore/go/user_api_test.go

@wing328 i created a user api test, and it discovered an issue on Go client, it seems interface conversion to array would cause issue.
we are passing an array of user objects to the postBody variable. (it seems single object works fine, the CreateUser test pass)
https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/go/go-petstore/user_api.go#L144
api_client just set the body by interface, https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/go/go-petstore/api_client.go#L92-L101
here is the error i am getting
@neilotoole have you experience this before? am i missing something obvious? or it is a bug in resty?

added user api test

---

samples/client/petstore/go/pet_api_test.go

added assert to check response status match the query

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptFetchClientCodegen.java
modules/swagger-codegen/src/main/resources/META-INF/services/io.swagger.codegen.CodegenConfig
modules/swagger-codegen/src/main/resources/TypeScript-Fetch/api.mustache
modules/swagger-codegen/src/main/resources/TypeScript-Fetch/assign.ts
modules/swagger-codegen/src/main/resources/TypeScript-Fetch/git_push.sh.mustache
modules/swagger-codegen/src/main/resources/TypeScript-Fetch/package.json
modules/swagger-codegen/src/main/resources/TypeScript-Fetch/tsconfig.json
modules/swagger-codegen/src/main/resources/TypeScript-Fetch/typings.json
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/TypeScriptFetchClientOptionsProvider.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/typescriptfetch/TypeScriptFetchClientOptionsTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/typescriptfetch/TypeScriptFetchModelTest.java

TypeScript implementation using [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API)
Other features: 
* uses ES6 modules system (backward compatible to CommonJS)
* provides barebone `package.json` so user can `npm install` the dependencies
* provides `tsconfig.json` so user can `tsc`
* provides `typings.json` so user can install TypeScript definition for dependencies via `typings` (the prevailing type management system. 
* code is isomorphic for both Node and browser (to be fully tested) 
Limitations: 
* it does not support authentication currently
* Environment/bundling (isomorphic)
* Module system compatibility

TypeScript Fetch:  implementation

---

modules/swagger-codegen/src/main/resources/nodejs/package.mustache
samples/server/petstore/nodejs/api/swagger.yaml
samples/server/petstore/nodejs/controllers/PetService.js
samples/server/petstore/nodejs/controllers/StoreService.js
samples/server/petstore/nodejs/controllers/UserService.js
samples/server/petstore/nodejs/package.json

update swagger tools to 0.10.1

[koly] update swagger tools to 0.10.1

---

modules/swagger-codegen/src/main/resources/Java/api.mustache
modules/swagger-codegen/src/main/resources/Java/model.mustache
samples/client/petstore/java/default/docs/FakeApi.md
samples/client/petstore/java/default/src/main/java/io/swagger/client/api/FakeApi.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/api/UserApi.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Animal.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/AnimalFarm.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Cat.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Category.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Dog.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/EnumClass.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/EnumTest.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/FormatTest.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Model200Response.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/ModelApiResponse.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/ModelReturn.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Name.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Order.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Pet.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/SpecialModelName.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Tag.java
samples/client/petstore/java/default/src/main/java/io/swagger/client/model/User.java

To fix https://github.com/swagger-api/swagger-codegen/issues/2805, https://github.com/swagger-api/swagger-codegen/issues/2668

[Java] fix java import issue due to enum and inner model

---

modules/swagger-codegen/src/main/resources/csharp/api.mustache
samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Api/PetApi.cs
samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Api/StoreApi.cs
samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Api/UserApi.cs

For #2756 
@kbrooks we should check for null regardless it is required or not. let me know if this is still an issue.

Issue #2756: add null checking to avoid null exception

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java
modules/swagger-codegen/src/main/resources/php/composer.mustache

This PR adds some order in docs and test, making related files have the same path but different root, as the following example:
```
lib/Api/DefaultApi.php
test/Api/DefaultApi.php
docs/Api/DefaultApi.php
```

Issue 2743

---

modules/swagger-codegen/src/main/resources/JavaSpringMVC/pom-j8-async.mustache
samples/server/petstore/spring-mvc-j8-async/pom.xml
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/api/ApiException.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/api/ApiOriginFilter.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/api/ApiResponseMessage.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/api/NotFoundException.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/api/PetApi.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/api/StoreApi.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/api/UserApi.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/configuration/SwaggerConfig.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/configuration/SwaggerUiConfiguration.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/configuration/WebApplication.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/configuration/WebMvcConfiguration.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/model/Category.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/model/ModelApiResponse.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/model/Order.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/model/Pet.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/model/Tag.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/model/User.java

I think scale-test is not used, so deleted it. Please correct if I am wrong. Thanks.

upgrade version and delete scala-test property

---

modules/swagger-codegen/src/main/resources/php/model.mustache
samples/client/petstore/php/SwaggerClient-php/lib/Model/Animal.php
samples/client/petstore/php/SwaggerClient-php/lib/Model/ApiResponse.php
samples/client/petstore/php/SwaggerClient-php/lib/Model/Cat.php
samples/client/petstore/php/SwaggerClient-php/lib/Model/Category.php
samples/client/petstore/php/SwaggerClient-php/lib/Model/Dog.php
samples/client/petstore/php/SwaggerClient-php/lib/Model/FormatTest.php
samples/client/petstore/php/SwaggerClient-php/lib/Model/Model200Response.php
samples/client/petstore/php/SwaggerClient-php/lib/Model/ModelReturn.php
samples/client/petstore/php/SwaggerClient-php/lib/Model/Name.php
samples/client/petstore/php/SwaggerClient-php/lib/Model/Order.php
samples/client/petstore/php/SwaggerClient-php/lib/Model/Pet.php
samples/client/petstore/php/SwaggerClient-php/lib/Model/SpecialModelName.php
samples/client/petstore/php/SwaggerClient-php/lib/Model/Tag.php
samples/client/petstore/php/SwaggerClient-php/lib/Model/User.php

Method should be camelCase to follow PSR-2 coding style

[PHP] method list_invalid_properties change to camelCase

---

modules/swagger-codegen/src/main/resources/Java/libraries/feign/auth/OAuth.mustache
samples/client/petstore/java/feign/src/main/java/io/swagger/client/FormAwareEncoder.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/StringUtil.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/api/FakeApi.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/api/UserApi.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/auth/OAuth.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Animal.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/AnimalFarm.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Cat.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Category.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Dog.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/EnumClass.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/EnumTest.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/FormatTest.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Model200Response.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/ModelApiResponse.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/ModelReturn.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Name.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Order.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Pet.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/SpecialModelName.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Tag.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/User.java

Fixes Oauth token not being refreshed when it expires.
Also fixes some sonar warnings.

[Feign]Fix issue with expired token refreshing

---

bin/android-petstore-httpclient.sh
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AndroidClientCodegen.java

change volley to the default http library for android

---

modules/swagger-codegen/src/main/resources/android/libraries/volley/pom.mustache
samples/client/petstore/android/volley/README.md
samples/client/petstore/android/volley/pom.xml

- update android volley dependencies to the latest version
- added source and target (both to 1.6) in pom.xml

[Android] update android volley dependencies, add source and target in pom.xml

---

modules/swagger-codegen/src/main/resources/go/api.mustache
modules/swagger-codegen/src/main/resources/go/api_client.mustache
samples/client/petstore/go/go-petstore/api_client.go
samples/client/petstore/go/go-petstore/pet_api.go
samples/client/petstore/go/go-petstore/store_api.go
samples/client/petstore/go/go-petstore/user_api.go

Updat api_client.go to use the new SetMultiValueQueryParams method

---

README.md

This is where I work, and I am using swagger-codegen for a project at work, so it counts.

Adding IMS Health to the list of companies

---

modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/auth/OAuth.mustache
samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/StringUtil.java
samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/api/FakeApi.java
samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/auth/OAuth.java
samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/model/Animal.java
samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/model/Cat.java
samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/model/Dog.java
samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/model/Name.java
samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/StringUtil.java
samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/api/FakeApi.java
samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/auth/OAuth.java
samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/model/Animal.java
samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/model/Cat.java
samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/model/Dog.java
samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/model/Name.java

[Retrofit2] Don't retry if the access token doesn't change

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java
modules/swagger-codegen/src/main/resources/htmlDocs/index.mustache

add basePathWithoutHost

---

modules/swagger-codegen/src/main/resources/Javascript/api.mustache
modules/swagger-codegen/src/main/resources/clojure/api.mustache

Unescape the mediaType value as it might contains HTML special characters.

[Javascript][Clojure] Fix mediaType 

---

modules/swagger-codegen/src/main/resources/htmlDocs/index.mustache

show security defs

---

samples/client/petstore/php/SwaggerClient-php/test/Model/EnumClassTest.php
samples/client/petstore/php/SwaggerClient-php/test/Model/EnumTestTest.php

Add tests for PHP enum class and properties.

[PHP] add enum test in PHP API client

---

modules/swagger-codegen-maven-plugin/README.md

add custom generator example to readme

---

modules/swagger-codegen/src/main/resources/objc/api-body.mustache

[Objc] fixed code generation for collection parameter

---

modules/swagger-codegen/src/main/resources/swift/model.mustache

[Swift] Remove force unwrap in model constructor

---

pom.xml

For https://github.com/swagger-api/swagger-codegen/pull/2910

[TypeScript] update pom to cover TS Fetch API clients

---

modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/pom.mustache
samples/client/petstore/java/okhttp-gson/pom.xml
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/ApiException.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/Configuration.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/Pair.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/StringUtil.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/auth/ApiKeyAuth.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/auth/OAuth.java

Fix warnings and the output now looks better:
```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] Building swagger-petstore-okhttp-gson 1.0.0
[INFO] 
[INFO] --- build-helper-maven-plugin:1.10:add-source (add_sources) @ swagger-petstore-okhttp-gson ---
[INFO] Source directory: /Users/williamcheng/Code/cherrypick/swagger-codegen/samples/client/petstore/java/okhttp-gson/src/main/java added.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ swagger-petstore-okhttp-gson ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] …
```

[Java] fix warning in pom.xml (java okhttp-gson)

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/AbstractGenerator.java

Stop Reading Custom Template Files from subdirectory

---

.github/ISSUE_TEMPLATE.md

Hopefully that will make issues easier to read.

[Github issue template] instructions about how to paste YAML or JSON code

---

README.md

We use swagger for our [Route Optimization API](https://graphhopper.com/api/1/docs/route-optimization/) and will likely expand usage to our other APIs.

Added new company using swagger

---

bin/java-petstore-feign.sh
samples/client/petstore/java/feign/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/FormAwareEncoder.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/StringUtil.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/api/FakeApi.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/api/UserApi.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/AdditionalPropertiesClass.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Animal.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/AnimalFarm.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/ArrayTest.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Cat.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Category.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Dog.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/EnumTest.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/FormatTest.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/MixedPropertiesAndAdditionalPropertiesClass.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Model200Response.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/ModelApiResponse.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/ModelReturn.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Name.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Order.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Pet.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/ReadOnlyFirst.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/SpecialModelName.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/Tag.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/model/User.java

Remove generated annotation from feign sample

---

modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/api.mustache
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/ApiException.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/Configuration.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/Pair.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/StringUtil.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/api/FakeApi.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/api/UserApi.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/auth/ApiKeyAuth.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/auth/OAuth.java

This fixes #3071 
I've tested it and it works (compiles) but never digged deep into mustache etc ... so is this enough :) ?

use explicit Response class from okhttp

---

modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/pom.mustache

[Java][okhttp-gson] fix okhttp pom to remove dependency on gradle, sbt test

---

modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/api.mustache
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/api/FakeApi.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/api/UserApi.java

[Java] client: make all okhttp classes explicit to avoid conflict

---

modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/pom.mustache
samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/ApiClient.java

Adding the ability to get and set the httpClient for jersey2

---

modules/swagger-codegen/src/main/resources/htmlDocs/index.mustache

it's the future

---

modules/swagger-codegen/src/main/resources/dart/model.mustache
samples/client/petstore/dart/LICENSE
samples/client/petstore/dart/git_push.sh
samples/client/petstore/dart/lib/api_client.dart
samples/client/petstore/dart/lib/model/api_response.dart
samples/client/petstore/dart/lib/model/category.dart
samples/client/petstore/dart/lib/model/order.dart
samples/client/petstore/dart/lib/model/pet.dart
samples/client/petstore/dart/lib/model/tag.dart
samples/client/petstore/dart/lib/model/user.dart

JSON representation of dart and java generated code is not the same.
I added the @Property annotation to the dart model.mustache 
before a property `some-name` was translated to `someName` in JSON but should be `some-name`

Dart - Java compatibility

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/java/JavaModelTest.java

https://github.com/swagger-api/swagger-codegen/issues/3140

Add Import for Inner CodegenProperties

---

bin/java-petstore-okhttp-gson.sh
modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/JSON.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/build.gradle.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/build.sbt.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/pom.mustache
samples/client/petstore/java/okhttp-gson/pom.xml
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/JSON.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/api/FakeApi.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/okhttp-gson/src/test/java/io/swagger/client/api/StoreApiTest.java

[Okhttp-gson] Add support for jsr310 dates to okhttp-gson client

---

modules/swagger-codegen/src/main/resources/nodejs/README.mustache
modules/swagger-codegen/src/main/resources/nodejs/package.mustache

Taking advantage of package.json scripts to install + launch in one command.

nodejs-server: Added npm start scripts on package.json + update README

---

README.md

W.UP is using Swagger codegen extensively for multiple projects on the server-side and mobile clients.

Added W.UP to companies using Swagger

---

bin/java-petstore-retrofit2.sh
bin/java-petstore-retrofit2rx.sh
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/ApiClient.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/build.gradle.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/build.sbt.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/pom.mustache
samples/client/petstore/java/retrofit2/.swagger-codegen-ignore
samples/client/petstore/java/retrofit2/pom.xml
samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/api/FakeApi.java
samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/retrofit2/src/test/java/io/swagger/client/api/PetApiTest.java
samples/client/petstore/java/retrofit2/src/test/java/io/swagger/client/api/StoreApiTest.java
samples/client/petstore/java/retrofit2rx/.swagger-codegen-ignore
samples/client/petstore/java/retrofit2rx/pom.xml
samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/api/FakeApi.java
samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/retrofit2rx/src/test/java/io/swagger/client/api/StoreApiTest.java

[Retrofit] Add support for jsr310 dates to retrofit2 client

---

samples/server/petstore/nodejs/README.md
samples/server/petstore/nodejs/package.json

As suggested in https://github.com/swagger-api/swagger-codegen/pull/3212

Update petstore sample for changes on PR #3212

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/LumenServerCodegen.java
samples/server/petstore/lumen/app/Http/controllers/PetApi.php
samples/server/petstore/lumen/app/Http/controllers/StoreApi.php
samples/server/petstore/lumen/app/Http/controllers/UserApi.php
samples/server/petstore/lumen/app/Http/routes.php

[PHP Lumen] sort the endpoints in ascending to avoid the route priority issure

---

modules/swagger-codegen/src/main/resources/ruby/model_test.mustache

Minor update so that rspec does not throw error related to enum attributes.

[Ruby] minor update to ruby test cases

---

appveyor.yml
pom.xml

We'll leverage [AppVeyor](https://www.appveyor.com/) to build the JAR in Windows environment.

Add CI tests for Windows environment

---

modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/ApiClient.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/api.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/pom.mustache
samples/client/petstore/java/retrofit2/.swagger-codegen-ignore
samples/client/petstore/java/retrofit2/docs/ArrayTest.md
samples/client/petstore/java/retrofit2/docs/FakeApi.md
samples/client/petstore/java/retrofit2/pom.xml
samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/api/FakeApi.java
samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/api/UserApi.java
samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/model/ArrayTest.java

Removed the warning when running `mvn javadoc:javadoc`

[Java][Retrofit2] remove javadoc, pom.xml warnings

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java

For https://github.com/swagger-api/swagger-codegen/issues/2936

[Java] update wording for fullJavaUtil option

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java

the program will exit when model definition error happen, the tip i added to this error maybe look like trick. #2499

add more tips about npe;

---

modules/swagger-codegen/src/main/resources/Java/auth/ApiKeyAuth.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/feign/auth/ApiKeyAuth.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit/auth/ApiKeyAuth.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/auth/ApiKeyAuth.mustache
modules/swagger-codegen/src/main/resources/android/libraries/volley/auth/apikeyauth.mustache
samples/client/petstore-security-test/java/okhttp-gson/src/main/java/io/swagger/client/auth/ApiKeyAuth.java
samples/client/petstore/android/volley/src/main/java/io/swagger/client/auth/ApiKeyAuth.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/auth/ApiKeyAuth.java
samples/client/petstore/java/jersey1/src/main/java/io/swagger/client/auth/ApiKeyAuth.java
samples/client/petstore/java/jersey2-java8/src/main/java/io/swagger/client/auth/ApiKeyAuth.java
samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/auth/ApiKeyAuth.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/auth/ApiKeyAuth.java
samples/client/petstore/java/retrofit/src/main/java/io/swagger/client/auth/ApiKeyAuth.java
samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/auth/ApiKeyAuth.java
samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/auth/ApiKeyAuth.java

Not compare Java String with "=="

---

modules/swagger-codegen/src/main/resources/ruby/partial_model_generic.mustache

fix[ruby]: Problem with List of Enum

---

modules/swagger-generator/src/main/java/io/swagger/generator/resource/SwaggerResource.java

added env variable override

---

.travis.yml

Cache maven directory for faster builds!

[Travis] Cache maven directory

---

modules/swagger-codegen/src/main/resources/JavaJaxRS/libraries/jersey1/pom.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/pom.mustache
samples/server/petstore/jaxrs/jersey1/pom.xml
samples/server/petstore/jaxrs/jersey2/pom.xml

Make jersey tests wait that jetty is closed before terminating

---

modules/swagger-codegen/src/main/resources/lumen/routes.mustache
samples/server/petstore/lumen/app/Http/controllers/FakeApi.php
samples/server/petstore/lumen/app/Http/routes.php

[PHP Lumen] add context path

---

modules/swagger-codegen/src/main/resources/go-server/routers.mustache
samples/server/petstore/go-api-server/LICENSE
samples/server/petstore/go-api-server/go/README.md
samples/server/petstore/go-api-server/go/routers.go

@wing328 please review, 
for issue #3418

fixed all routing to v2

---

modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache
samples/client/petstore/typescript-angular2/default/api/PetApi.ts
samples/client/petstore/typescript-angular2/default/api/StoreApi.ts
samples/client/petstore/typescript-angular2/default/api/UserApi.ts
samples/client/petstore/typescript-angular2/npm/README.md
samples/client/petstore/typescript-angular2/npm/api/PetApi.ts
samples/client/petstore/typescript-angular2/npm/api/StoreApi.ts
samples/client/petstore/typescript-angular2/npm/api/UserApi.ts
samples/client/petstore/typescript-angular2/npm/package.json

To fix https://github.com/swagger-api/swagger-codegen/issues/3427

[TypeScript][Angular2] Fix numeric query/header parameters

---

pom.xml

Updated versions on ubuntu 16.0.4 for test success.

jmockit-surefire-fix

---

modules/swagger-codegen/src/main/resources/go/api.mustache

[Go] removed unused import

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwiftCodegen.java
samples/client/petstore/swift/default/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift
samples/client/petstore/swift/default/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift
samples/client/petstore/swift/default/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift
samples/client/petstore/swift/default/SwaggerClientTests/Pods/Manifest.lock
samples/client/petstore/swift/default/SwaggerClientTests/Pods/Target Support Files/Pods-SwaggerClient/Pods-SwaggerClient-resources.sh
samples/client/petstore/swift/default/SwaggerClientTests/Pods/Target Support Files/Pods-SwaggerClientTests/Pods-SwaggerClientTests-resources.sh
samples/client/petstore/swift/default/SwaggerClientTests/SwaggerClient.xcodeproj/project.pbxproj
samples/client/petstore/swift/promisekit/PetstoreClient.podspec
samples/client/petstore/swift/promisekit/PetstoreClient/Classes/Swaggers/APIs.swift
samples/client/petstore/swift/promisekit/PetstoreClient/Classes/Swaggers/AlamofireImplementations.swift
samples/client/petstore/swift/promisekit/PetstoreClient/Classes/Swaggers/Extensions.swift
samples/client/petstore/swift/promisekit/PetstoreClient/Classes/Swaggers/Models.swift

To fix https://github.com/swagger-api/swagger-codegen/issues/2538

[Swift] To fix enum with numeric values

---

modules/swagger-codegen/src/main/resources/ruby/api_client.mustache
samples/client/petstore-security-test/ruby/lib/petstore/api_client.rb
samples/client/petstore/ruby/lib/petstore/api_client.rb

Fix spelling in ruby ApiClient: Configuraiton -> Configuration

---

modules/swagger-codegen/src/main/resources/Java/ApiClient.mustache
samples/client/petstore/java/jersey1/src/main/java/io/swagger/client/ApiClient.java

this code will fix #3389 ( change of content Type to MediaType.APPLICATION_OCTET_STREAM_TYPE)
+ possibility for multi file upload (as List)

improved Multipart/form-data file upload support

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwaggerYamlGenerator.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/SwaggerYamlOptionsProvider.java

added configuration for swagger-yaml output file

---

README.md

The jar which I download from the current url can't run the command properly.

Modify the url of the swagger-codegen-cli.jar

---

modules/swagger-codegen/src/main/resources/go/api.mustache
modules/swagger-codegen/src/main/resources/go/api_client.mustache
modules/swagger-codegen/src/main/resources/go/configuration.mustache

Fixed config to support transport, and other options

---

modules/swagger-codegen-maven-plugin/examples/java-client.xml

update to version 2.2.2

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/GoClientCodegen.java

this is only fixing the first reported issue in #3644 

[Go] fixing code gen not recognizing 'object' type issue

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ScalatraServerCodegen.java
modules/swagger-codegen/src/main/resources/scalatra/api.mustache
samples/server/petstore/scalatra/src/main/scala/ScalatraBootstrap.scala
samples/server/petstore/scalatra/src/main/scala/ServletApp.scala
samples/server/petstore/scalatra/src/main/scala/com/wordnik/client/api/PetApi.scala
samples/server/petstore/scalatra/src/main/scala/com/wordnik/client/api/StoreApi.scala
samples/server/petstore/scalatra/src/main/scala/com/wordnik/client/api/UserApi.scala
samples/server/petstore/scalatra/src/main/scala/com/wordnik/client/model/ApiResponse.scala
samples/server/petstore/scalatra/src/main/scala/com/wordnik/client/model/Category.scala
samples/server/petstore/scalatra/src/main/scala/com/wordnik/client/model/Order.scala
samples/server/petstore/scalatra/src/main/scala/com/wordnik/client/model/Pet.scala
samples/server/petstore/scalatra/src/main/scala/com/wordnik/client/model/Tag.scala
samples/server/petstore/scalatra/src/main/scala/com/wordnik/client/model/User.scala

Tp fix https://github.com/swagger-api/swagger-codegen/issues/3686 by replacing {name} with :name in the path

[Scalatra] replace {} with : in scalatra path

---

modules/swagger-codegen/src/main/resources/php/ObjectSerializer.mustache
modules/swagger-codegen/src/main/resources/php/api.mustache
modules/swagger-codegen/src/main/resources/php/configuration.mustache
samples/client/petstore/php/SwaggerClient-php/lib/Api/FakeApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/PetApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/StoreApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/UserApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Configuration.php
samples/client/petstore/php/SwaggerClient-php/lib/ObjectSerializer.php

Some PHPDoc declarations was mistyped or just missing

[PHP] Corrected PHPDoc type declarations

---

modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache
samples/client/petstore/typescript-angular2/default/api/PetApi.ts
samples/client/petstore/typescript-angular2/default/api/StoreApi.ts
samples/client/petstore/typescript-angular2/default/api/UserApi.ts
samples/client/petstore/typescript-angular2/default/index.ts
samples/client/petstore/typescript-angular2/default/model/Category.ts
samples/client/petstore/typescript-angular2/default/model/Order.ts
samples/client/petstore/typescript-angular2/default/model/Pet.ts
samples/client/petstore/typescript-angular2/default/model/Tag.ts
samples/client/petstore/typescript-angular2/default/model/User.ts
samples/client/petstore/typescript-angular2/npm/README.md
samples/client/petstore/typescript-angular2/npm/api/PetApi.ts
samples/client/petstore/typescript-angular2/npm/api/StoreApi.ts
samples/client/petstore/typescript-angular2/npm/api/UserApi.ts
samples/client/petstore/typescript-angular2/npm/index.ts
samples/client/petstore/typescript-angular2/npm/model/Category.ts
samples/client/petstore/typescript-angular2/npm/model/Order.ts
samples/client/petstore/typescript-angular2/npm/model/Pet.ts
samples/client/petstore/typescript-angular2/npm/model/Tag.ts
samples/client/petstore/typescript-angular2/npm/model/User.ts
samples/client/petstore/typescript-angular2/npm/package.json
samples/client/petstore/typescript-angular2/npm/typings.json

Fix for issue: 
https://github.com/swagger-api/swagger-codegen/issues/3695

fix map usage in api generation #3694

---

modules/swagger-codegen/src/main/resources/csharp/README.mustache

Added anchor tag in README.mustache issue #3748.

---

modules/swagger-codegen/src/main/resources/akka-scala/model.mustache
modules/swagger-codegen/src/main/resources/scala/model.mustache
modules/swagger-codegen/src/main/resources/scalatra/model.mustache
samples/client/petstore/akka-scala/src/main/scala/io/swagger/client/api/PetApi.scala
samples/client/petstore/akka-scala/src/main/scala/io/swagger/client/model/ApiResponse.scala
samples/client/petstore/akka-scala/src/main/scala/io/swagger/client/model/Category.scala
samples/client/petstore/akka-scala/src/main/scala/io/swagger/client/model/Order.scala
samples/client/petstore/akka-scala/src/main/scala/io/swagger/client/model/Pet.scala
samples/client/petstore/akka-scala/src/main/scala/io/swagger/client/model/Tag.scala
samples/client/petstore/akka-scala/src/main/scala/io/swagger/client/model/User.scala
samples/client/petstore/scala/src/main/scala/io/swagger/client/api/PetApi.scala
samples/client/petstore/scala/src/main/scala/io/swagger/client/model/ApiResponse.scala
samples/client/petstore/scala/src/main/scala/io/swagger/client/model/Category.scala
samples/client/petstore/scala/src/main/scala/io/swagger/client/model/Order.scala
samples/client/petstore/scala/src/main/scala/io/swagger/client/model/Pet.scala
samples/client/petstore/scala/src/main/scala/io/swagger/client/model/Tag.scala
samples/client/petstore/scala/src/main/scala/io/swagger/client/model/User.scala
samples/server/petstore/scalatra/src/main/scala/com/wordnik/client/api/PetApi.scala
samples/server/petstore/scalatra/src/main/scala/com/wordnik/client/model/ApiResponse.scala
samples/server/petstore/scalatra/src/main/scala/com/wordnik/client/model/Category.scala
samples/server/petstore/scalatra/src/main/scala/com/wordnik/client/model/Order.scala
samples/server/petstore/scalatra/src/main/scala/com/wordnik/client/model/Pet.scala
samples/server/petstore/scalatra/src/main/scala/com/wordnik/client/model/Tag.scala
samples/server/petstore/scalatra/src/main/scala/com/wordnik/client/model/User.scala

Better indention of model properties in Scala (scala, scalatra, akka-scala)

[Scala] better format of model properties

---

samples/client/petstore/typescript-angular2/default/api/PetApi.ts
samples/client/petstore/typescript-angular2/default/api/StoreApi.ts
samples/client/petstore/typescript-angular2/default/api/UserApi.ts
samples/client/petstore/typescript-angular2/npm/README.md
samples/client/petstore/typescript-angular2/npm/api/PetApi.ts
samples/client/petstore/typescript-angular2/npm/api/StoreApi.ts
samples/client/petstore/typescript-angular2/npm/api/UserApi.ts
samples/client/petstore/typescript-angular2/npm/package.json

Update typescript2-angular2 petstore.

[Typescript][Angular2] Update typescript-angular2 petstore sample

---

modules/swagger-codegen/src/main/resources/scala/api.mustache
samples/client/petstore/scala/src/main/scala/io/swagger/client/api/PetApi.scala
samples/client/petstore/scala/src/main/scala/io/swagger/client/api/StoreApi.scala
samples/client/petstore/scala/src/main/scala/io/swagger/client/api/UserApi.scala

- better code format
- replace String.valueOf null check with null check for string only using `isString`

[Scala] enhancement to indention and null check

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngular2ClientCodegen.java
modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache
modules/swagger-codegen/src/main/resources/typescript-angular2/configuration.mustache
modules/swagger-codegen/src/main/resources/typescript-angular2/index.mustache
samples/client/petstore/typescript-angular2/default/api/PetApi.ts
samples/client/petstore/typescript-angular2/default/api/StoreApi.ts
samples/client/petstore/typescript-angular2/default/api/UserApi.ts
samples/client/petstore/typescript-angular2/default/configuration.ts
samples/client/petstore/typescript-angular2/default/index.ts
samples/client/petstore/typescript-angular2/default/variables.ts

- [ x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x ] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run`./bin/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
Adds authentication to typescript-angular2 clients. Inspired by the csharp equivalent.

add authentication to typescript-angular2

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/InlineModelResolver.java

Possible fix for https://github.com/swagger-api/swagger-codegen/issues/3808
Change-Id: I6711e96d4b119b2cf78860d4eb43fc178edae372

Fix NullPointerException if there are no other properties

---

modules/swagger-codegen/src/main/resources/JMeter/api.mustache

[jmeter] #3800 Fixing testCases and paramName

---

modules/swagger-codegen/src/main/resources/codegen/README.mustache

Fix custom generator execution example in README template

---

modules/swagger-codegen/src/main/resources/cpprest/apiclient-source.mustache
modules/swagger-codegen/src/main/resources/cpprest/modelbase-source.mustache
samples/client/petstore/cpprest/ApiClient.cpp
samples/client/petstore/cpprest/ModelBase.cpp

Add support of Linux platform for source code generated for cpprest library. Master branch

Support cpprest on Linux

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/DartClientCodegen.java
samples/client/petstore/dart/swagger/lib/api_client.dart

To fix https://github.com/swagger-api/swagger-codegen/issues/3936

[Dart] fix number format for Dart's model

---

modules/swagger-codegen/src/main/resources/php/ApiClient.mustache
modules/swagger-codegen/src/main/resources/php/ApiException.mustache
modules/swagger-codegen/src/main/resources/php/ObjectSerializer.mustache
modules/swagger-codegen/src/main/resources/php/api.mustache
modules/swagger-codegen/src/main/resources/php/api_test.mustache
modules/swagger-codegen/src/main/resources/php/configuration.mustache
modules/swagger-codegen/src/main/resources/php/model.mustache
modules/swagger-codegen/src/main/resources/php/model_generic.mustache

Reverts swagger-api/swagger-codegen#3898

Revert "[WIP] Improve PHP client emitted code quality"

---

modules/swagger-codegen/src/main/resources/htmlDocs/index.mustache
modules/swagger-codegen/src/main/resources/htmlDocs/style.css.mustache
samples/html/index.html

- Group api index by operations.baseName 
- Change little style
Signed-off-by: weiyang <weiyang.ones@gmail.com>

[html]Group api index by operations.baseName

---

modules/swagger-codegen/src/main/resources/python/README.mustache
samples/client/petstore/python/README.md

Fix missing () in Python readme "Getting Started" section.

[Python] fix missing () in python doc

---

README.md

typo  relesae -> release

---

modules/swagger-codegen/src/main/resources/ruby/partial_model_generic.mustache
samples/client/petstore/ruby/lib/petstore/models/animal.rb
samples/client/petstore/ruby/lib/petstore/models/cat.rb
samples/client/petstore/ruby/lib/petstore/models/dog.rb
samples/client/petstore/ruby/lib/petstore/models/format_test.rb
samples/client/petstore/ruby/lib/petstore/models/name.rb
samples/client/petstore/ruby/lib/petstore/models/pet.rb

Fix required property check in Ruby models

[Ruby] fix required property check in Ruby models

---

modules/swagger-codegen/src/main/resources/TypeScript-Fetch/api.mustache
samples/client/petstore/typescript-fetch/builds/default/api.ts
samples/client/petstore/typescript-fetch/builds/es6-target/api.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/api.ts

Fix header parameter tag in TS Fetch API client (api.mustache)

[Typescript][Fetch] fix header parameters in TS Fetch API client

---

modules/swagger-codegen-maven-plugin/src/main/java/io/swagger/codegen/plugin/CodeGenMojo.java

Work originally done by @jfiala via https://github.com/swagger-api/swagger-codegen/pull/3286 but contains additional commits.
This PR only extracts changes in CodeGenMojo.java

[Maven] Correct source folder for generated files

---

README.md

Added carpolo as a project using Swagger

Added company

---

bin/spring-cloud-feign-petstore.sh
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SpringCodegen.java
modules/swagger-codegen/src/main/resources/JavaSpring/api.mustache
modules/swagger-codegen/src/main/resources/JavaSpring/libraries/spring-cloud/pom.mustache
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/SpringOptionsProvider.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/spring/SpringOptionsTest.java
samples/client/petstore/spring-cloud/pom.xml
samples/client/petstore/spring-cloud/src/main/java/io/swagger/api/PetApi.java
samples/client/petstore/spring-cloud/src/main/java/io/swagger/api/StoreApi.java
samples/client/petstore/spring-cloud/src/main/java/io/swagger/api/UserApi.java
samples/client/petstore/spring-cloud/src/test/java/io/swagger/Application.java
samples/client/petstore/spring-cloud/src/test/java/io/swagger/api/PetApiTest.java
samples/client/petstore/spring-cloud/src/test/java/io/swagger/api/StoreApiTest.java
samples/client/petstore/spring-cloud/src/test/java/io/swagger/api/UserApiTest.java
samples/client/petstore/spring-cloud/src/test/resources/application.yml

- Add an option to choose the response wrapper type
- Also generate the spring-cloud sample with a HystrixCommand wrapper

[spring] add an option to choose the response wrapper type

---

modules/swagger-codegen/src/main/resources/dart/pubspec.mustache
samples/client/petstore/dart/swagger/pubspec.yaml

Based on discussion in https://github.com/swagger-api/swagger-codegen/pull/4049
cc @ircecho

[dart] updated intl library version

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java

see issue #4077: An IndexOutOfBoundExeception is thrown during comiling yaml to spring for the element title: ""

Added String.length() > 0 check to avoid IndexOutOfBoundException

---

modules/swagger-codegen/src/main/resources/ruby/api.mustache
samples/client/petstore/ruby/lib/petstore/api/fake_api.rb

It never throws error with any values in array. Every element should be validated against the enum.

[ruby] Validate array correctly

---

README.md

Added clarification to license of generated code

---

README.md

Added QAdept to companies list

---

modules/swagger-codegen/src/main/resources/Java/pojo.mustache

Repair vendorExtensions due to broken merge.

Update pojo.mustache to repair broken merge

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java

This will ensure that the same code is always produced and reduce the git diffs.

Fix order of imports in operations

---

modules/swagger-codegen/src/main/resources/htmlDocs2/sample_php.mustache

This resolves the following issue. 
https://github.com/swagger-api/swagger-codegen/issues/4082

Remove opening PHP tag from PHP code sample

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FlaskConnexionCodegen.java
samples/server/petstore/flaskConnexion-python2/swagger/swagger.yaml
samples/server/petstore/flaskConnexion/swagger/swagger.yaml

[Flask] Use x-swagger-router-controller in for operation routing

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java

PR checklist
[* ] Read the contribution guildelines.
[ *] Filed the PR against the correct branch: master for non-breaking changes
Description of the PR
DefaultGenerator.java is very hard to read. The methods are very long and deeply nested. This makes it hard to read and maintain it.
This fix refactors DefaultGenerator by breaking it down into smaller chunks. It also adopts early return principle to avoid deeply nested code.
I ran maven tests and made sure all tests are passing.

Refactor code and Improve readability.

---

modules/swagger-codegen/src/main/resources/TypeScript-Fetch/api.mustache
samples/client/petstore/typescript-fetch/builds/default/api.ts

Add missing semicolons and remove trailing space in generated code.

Typescript-fetch - fix linting issues

---

README.md

Added VMware to list of Companies using Swagger Codegen

Added VMware to list of Companies

---

modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache
samples/client/petstore/typescript-angular2/default/api/PetApi.ts
samples/client/petstore/typescript-angular2/default/api/StoreApi.ts
samples/client/petstore/typescript-angular2/default/api/UserApi.ts
samples/client/petstore/typescript-angular2/npm/README.md
samples/client/petstore/typescript-angular2/npm/api/PetApi.ts
samples/client/petstore/typescript-angular2/npm/api/StoreApi.ts
samples/client/petstore/typescript-angular2/npm/api/UserApi.ts
samples/client/petstore/typescript-angular2/npm/package.json

Replace tab with spaces in TS Angular2 template.
(there's an issue with `basePath` that I'm looking into)

[Typscript][Angular2] Remove tab in TS Angular2 template

---

modules/swagger-codegen/src/main/resources/Java/pojo.mustache

For https://github.com/swagger-api/swagger-codegen/issues/3345#issuecomment-264191726

[Java] Add serialVersionUID to java model

---

README.md
modules/swagger-codegen-maven-plugin/examples/java-client.xml

Address issue #4298 by updating the docs to reflect the current state of the code.

Update docs for Java code generation

---

modules/swagger-codegen/src/main/resources/swift3/Models.mustache
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/Models.swift
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/Models/EnumTest.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/Models.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/Models/EnumTest.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/Models.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/Models/EnumTest.swift

- [x ] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.
Fix bug: #4318

[Swift3][bug#4318] Bug when handling java date

---

README.md

Added Saritasa to list of Companies

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CsharpDotNet2ClientCodegen.java

For https://github.com/swagger-api/swagger-codegen/issues/2099

[C#] add Guid mapping for `uuid` in C# 2.0 generator

---

modules/swagger-codegen/src/main/resources/Java/ApiClient.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
samples/client/petstore/java/feign/hello.txt
samples/client/petstore/java/jersey1/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/jersey2-java8/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/jersey2/hello.txt
samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/retrofit/hello.txt

SonarQube reported some bugs/problems on the library I created with swagger-codegen.
I fixed them in the template, built the codegen-cli and used that to regenerate the code of my project. The result works as expected.

Some code cleanings of problems reported by SonarQube.

---

README.md

added Upwork to users list

---

modules/swagger-codegen/src/main/resources/htmlDocs/bodyParam.mustache
samples/html/index.html

- [html] Add type anchor to body param block
Signed-off-by: weiyang weiyang.ones@gmail.com

[html] Add type anchor to body param block

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AndroidClientCodegen.java
modules/swagger-codegen/src/main/resources/android/libraries/volley/Pair.mustache
modules/swagger-codegen/src/main/resources/android/libraries/volley/api.mustache
modules/swagger-codegen/src/main/resources/android/libraries/volley/apiException.mustache
modules/swagger-codegen/src/main/resources/android/libraries/volley/apiInvoker.mustache
modules/swagger-codegen/src/main/resources/android/libraries/volley/auth/apikeyauth.mustache
modules/swagger-codegen/src/main/resources/android/libraries/volley/auth/httpbasicauth.mustache
modules/swagger-codegen/src/main/resources/android/libraries/volley/auth/oauth.mustache
modules/swagger-codegen/src/main/resources/android/libraries/volley/request/deleterequest.mustache
modules/swagger-codegen/src/main/resources/android/libraries/volley/request/patchrequest.mustache
modules/swagger-codegen/src/main/resources/android/libraries/volley/request/postrequest.mustache
modules/swagger-codegen/src/main/resources/android/libraries/volley/request/putrequest.mustache
samples/client/petstore/android/volley/src/main/java/io/swagger/client/ApiException.java
samples/client/petstore/android/volley/src/main/java/io/swagger/client/ApiInvoker.java
samples/client/petstore/android/volley/src/main/java/io/swagger/client/Pair.java
samples/client/petstore/android/volley/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/android/volley/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/android/volley/src/main/java/io/swagger/client/api/UserApi.java
samples/client/petstore/android/volley/src/main/java/io/swagger/client/auth/ApiKeyAuth.java
samples/client/petstore/android/volley/src/main/java/io/swagger/client/auth/HttpBasicAuth.java
samples/client/petstore/android/volley/src/main/java/io/swagger/client/request/DeleteRequest.java
samples/client/petstore/android/volley/src/main/java/io/swagger/client/request/PatchRequest.java
samples/client/petstore/android/volley/src/main/java/io/swagger/client/request/PostRequest.java
samples/client/petstore/android/volley/src/main/java/io/swagger/client/request/PutRequest.java

- Use 2-space indentation
- Add docstring

[Android] better code format for Android (volley) API client

---

modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/api.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/apiServiceImpl.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/api_test.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/returnTypes.mustache
samples/server/petstore/jaxrs-cxf/src/gen/java/io/swagger/api/PetApi.java
samples/server/petstore/jaxrs-cxf/src/gen/java/io/swagger/api/StoreApi.java
samples/server/petstore/jaxrs-cxf/src/gen/java/io/swagger/api/UserApi.java
samples/server/petstore/jaxrs-cxf/src/main/java/io/swagger/api/impl/PetApiServiceImpl.java
samples/server/petstore/jaxrs-cxf/src/main/java/io/swagger/api/impl/StoreApiServiceImpl.java
samples/server/petstore/jaxrs-cxf/src/main/java/io/swagger/api/impl/UserApiServiceImpl.java

before this commit if a method returned a container (List or Map) of
THING (i.e. List\<THING\> or Map<String, THING>) the generated return type would
drop the container and only leave THING.
this commit fixes this issue such that the container type is properly
generated.
I verified this change by generating JAXRS-CXF code using the following swagger definition:
```yaml
---
swagger: "2.0"
info:
version: "1.0.2"
host: "localhost:8080"
basePath: "/api"
schemes:
- "http"
paths:
/list:
get:
summary: "List Books"
description: ""
operationId: "listBooks"
consumes:
- "application/json"
produces:
- "application/json"
parameters: []
responses:
200:
description: "successful operation"
schema:
type: "array"
items:
$ref: "#/definitions/Book"
/book:
get:
summary: "get a book"
description: "" …
```

[JaxRS-CXF][bug #4330] support containers in return types

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java

To enhance https://github.com/swagger-api/swagger-codegen/pull/4063

[Java] show warning message for null inner type (map/array)

---

README.md

Included "AYLIEN" to the list of companies using swagger-codegen.

Add AYLIEN company to the list

---

README.md

Added Autodesk as a swagger codegen user

Added Autodesk as a swagger codegen user

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-generator/pom.xml
pom.xml

The latest swagger-core and parser bring new attributes for use inside the codegen project, and improved parsing support.
See release notes here:
[swagger-core-1.5.12](https://github.com/swagger-api/swagger-core/releases/tag/v1.5.12)
[swagger-parser-1.0.25](https://github.com/swagger-api/swagger-parser/releases/tag/v1.0.25)
Fixes #4471, #4449

Update to latest swagger-core, parser versions

---

README.md

Added reference to snapcx website, as we provide swagger 2.0 specs public APIs.
Updated README.md file to add reference to snapcx.io website. We use swagger2.0 compliant API specs.

Only updated README.md file

---

pom.xml

updated version

---

modules/swagger-codegen/src/test/java/io/swagger/codegen/bash/BashTest.java

To fix https://github.com/swagger-api/swagger-codegen/issues/4565

[Bash] To fix bash test package name

---

modules/swagger-codegen/src/main/resources/python/requirements.mustache
samples/client/petstore/python/petstore_api/api_client.py

- update python requirement.txt
- use single quote for safe characters

[Python] update python requirement.txt and use single quote for safe characters

---

README.md

Add "Simpfony" to list of companies using Swagger

Add "Simpfony" to list of companies using Swagger

---

README.md

Added my company (Fotition) to the list of companies using swagger-codegen

Added Fotition as a company using swagger-codegen

---

README.md

added QuickBlox to 'Companies/Projects using Swagger Codegen' section

added QuickBlox to 'Companies/Projects using Swagger Codegen' section

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwaggerGenerator.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwaggerYamlGenerator.java

To fix https://github.com/swagger-api/swagger-codegen/issues/3874#issuecomment-280956249

Fix warnings in swagger json/yaml generator

---

pom.xml

Updated from SNAPSHOT to 1.0.26 release

updated parser version

---

README.md
modules/swagger-codegen-cli/pom.xml
modules/swagger-codegen-maven-plugin/pom.xml
modules/swagger-codegen/pom.xml
modules/swagger-generator/pom.xml
pom.xml

update to release versions

---

modules/swagger-codegen-cli/pom.xml
modules/swagger-codegen-maven-plugin/pom.xml
modules/swagger-codegen/pom.xml
modules/swagger-generator/pom.xml
pom.xml

Update version to 2.2.3-SNAPSHOT

Update version to 2.2.3-SNAPSHOT

---

modules/swagger-codegen/src/main/resources/flaskConnexion/README.mustache
samples/server/petstore/flaskConnexion-python2/README.md
samples/server/petstore/flaskConnexion-python2/swagger_server/models/category.py
samples/server/petstore/flaskConnexion-python2/swagger_server/models/order.py
samples/server/petstore/flaskConnexion-python2/swagger_server/models/pet.py
samples/server/petstore/flaskConnexion-python2/swagger_server/models/tag.py
samples/server/petstore/flaskConnexion-python2/swagger_server/models/user.py
samples/server/petstore/flaskConnexion-python2/swagger_server/swagger/swagger.yaml
samples/server/petstore/flaskConnexion/README.md
samples/server/petstore/flaskConnexion/swagger_server/swagger/swagger.yaml

Add Python version requirement to README
Python 2.7+
or
Python 3.5.2+

[Python][Flask] Add Python version requirement to README

---

modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache
samples/client/petstore/typescript-angular2/default/api/PetApi.ts
samples/client/petstore/typescript-angular2/default/api/StoreApi.ts
samples/client/petstore/typescript-angular2/default/api/UserApi.ts
samples/client/petstore/typescript-angular2/npm/README.md
samples/client/petstore/typescript-angular2/npm/api/PetApi.ts
samples/client/petstore/typescript-angular2/npm/api/StoreApi.ts
samples/client/petstore/typescript-angular2/npm/api/UserApi.ts
samples/client/petstore/typescript-angular2/npm/package.json

To fix https://github.com/swagger-api/swagger-codegen/issues/4745

[TypeScript][Angular2] fix path variable in TS Angular2

---

modules/swagger-codegen/src/main/resources/Javascript/ApiClient.mustache
modules/swagger-codegen/src/main/resources/Javascript/api.mustache
samples/client/petstore/javascript-promise/src/ApiClient.js
samples/client/petstore/javascript-promise/src/api/FakeApi.js
samples/client/petstore/javascript-promise/src/api/PetApi.js
samples/client/petstore/javascript-promise/src/api/StoreApi.js
samples/client/petstore/javascript-promise/src/api/UserApi.js
samples/client/petstore/javascript/src/api/FakeApi.js
samples/client/petstore/javascript/src/api/PetApi.js
samples/client/petstore/javascript/src/api/StoreApi.js
samples/client/petstore/javascript/src/api/UserApi.js

This PR closes #3654 by adding *WithHttpInfo API methods, which can be used to get access to HTTP response object (e.g. headers or status code).
/cc @wing328 @amannn

[JavaScript] Added *WithHttpInfo methods in 'usePromises' mode

---

samples/server/petstore/java-msf4j/pom.xml
samples/server/petstore/java-msf4j/src/gen/java/io/swagger/api/FakeApi.java
samples/server/petstore/java-msf4j/src/gen/java/io/swagger/api/FakeApiService.java
samples/server/petstore/java-msf4j/src/gen/java/io/swagger/api/PetApi.java
samples/server/petstore/java-msf4j/src/gen/java/io/swagger/api/PetApiService.java
samples/server/petstore/java-msf4j/src/gen/java/io/swagger/api/UserApi.java
samples/server/petstore/java-msf4j/src/gen/java/io/swagger/api/UserApiService.java
samples/server/petstore/java-msf4j/src/gen/java/io/swagger/model/Animal.java
samples/server/petstore/java-msf4j/src/gen/java/io/swagger/model/Capitalization.java
samples/server/petstore/java-msf4j/src/gen/java/io/swagger/model/ClassModel.java
samples/server/petstore/java-msf4j/src/gen/java/io/swagger/model/EnumTest.java
samples/server/petstore/java-msf4j/src/gen/java/io/swagger/model/FormatTest.java
samples/server/petstore/java-msf4j/src/gen/java/io/swagger/model/MixedPropertiesAndAdditionalPropertiesClass.java
samples/server/petstore/java-msf4j/src/gen/java/io/swagger/model/OuterEnum.java
samples/server/petstore/java-msf4j/src/main/java/io/swagger/api/impl/FakeApiServiceImpl.java
samples/server/petstore/java-msf4j/src/main/java/io/swagger/api/impl/PetApiServiceImpl.java
samples/server/petstore/java-msf4j/src/main/java/io/swagger/api/impl/UserApiServiceImpl.java

→ bin/java-msf4j-petstore-server.sh
No functional changes at all, just regenerating the samples for MSF4J in preparation of a fix for #4898.

Update samples for MSF4J after 2.2.2.

---

README.md

Add hashdata(http://www.hashdata.cn/) to user list

Add hashdata to user list

---

modules/swagger-codegen/src/main/resources/swift3/AlamofireImplementations.mustache

the progress property is wrong here, since it holds download information and this case is for upload

fixes progress for file upload with alamofire / swift3

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java

https://github.com/swagger-api/swagger-codegen/issues/4906

Issue 4906

---

modules/swagger-codegen/src/main/resources/Java/README.mustache
modules/swagger-codegen/src/main/resources/android/README.mustache
modules/swagger-codegen/src/main/resources/go/README.mustache
samples/client/petstore-security-test/go/README.md
samples/client/petstore-security-test/java/okhttp-gson/README.md
samples/client/petstore/android/httpclient/README.md
samples/client/petstore/android/volley/README.md
samples/client/petstore/go/go-petstore/README.md
samples/client/petstore/java/jersey1/README.md
samples/client/petstore/java/jersey2-java6/README.md
samples/client/petstore/java/jersey2-java8/README.md
samples/client/petstore/java/jersey2/README.md
samples/client/petstore/java/okhttp-gson-parcelableModel/README.md
samples/client/petstore/java/okhttp-gson/README.md

Authorizatoin should be Authorization

Fix typo in README.mustache files

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/ignore/CodegenIgnoreProcessor.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java

To fix https://github.com/swagger-api/swagger-codegen/issues/4960.
Also revise wording related to output directory without .swagger-codegen-ignore

[JavaScript] fix issues with boolean CLI options

---

modules/swagger-codegen/src/main/resources/php/configuration.mustache
samples/client/petstore/php/SwaggerClient-php/lib/Configuration.php

Small improvements, mostly stuff pointed out by phpstorm checks regarding
https://github.com/swagger-api/swagger-codegen/issues/3867

minor improvements to Configuration php template

---

modules/swagger-generator/src/main/webapp/index.html

Fix https://github.com/swagger-api/swagger-codegen/issues/4983

JS files were replaced in the lib folder; include new

---

pom.xml
samples/server/petstore/java-msf4j/pom.xml
samples/server/petstore/jaxrs-cxf-annotated-base-path/pom.xml
samples/server/petstore/jaxrs-cxf-non-spring-app/pom.xml

Update travis.yml to cover Java-related server stubs

Update travis.yml to cover Java-related server stubs

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/BashClientCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/bash/BashTest.java
pom.xml

updated parser

---

modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
samples/client/petstore-security-test/java/okhttp-gson/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/ApiClient.java

Close https://github.com/swagger-api/swagger-codegen/issues/4671
Close https://github.com/swagger-api/swagger-codegen/pull/4772

fix handleResponse to not leak okhttp connections

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java

Add non primitive, complex types to the imports for the Api classes

Issue 4759: Import complex type for body parameters

---

pom.xml
samples/client/petstore/typescript-jquery/npm/pom.xml

Add and update pom.xml to cover TS jQuery Petstore

[TypeScript][jQuery] add integration test for TS jQuery Petstore

---

README.md

https://www.practicebird.com is happily using the typescript/Angular 2 codegen of this project

Add practicebird.com to companies/projects using swagger codegen

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AsyncScalaClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ScalaClientCodegen.java

This is a trivial change fixing a broken import. Scala client will otherwise not compile.

Fixes ListBuffer import-mapping for scala clients

---

samples/client/petstore/swift/default/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift
samples/client/petstore/swift/default/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift
samples/client/petstore/swift/default/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift
samples/client/petstore/swift/promisekit/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift
samples/client/petstore/swift/promisekit/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift
samples/client/petstore/swift/promisekit/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift
samples/client/petstore/swift/rxswift/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift
samples/client/petstore/swift/rxswift/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift
samples/client/petstore/swift/rxswift/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift

→ bin/swift-petstore-all.sh
No code changes, just regenerating the samples (so for later code changes I can see what actually changed).
The changes were likely caused by changes in the ExampleGenerator in #4797 and #5068.

Updating samples for swift.

---

modules/swagger-codegen/src/main/resources/typescript-angular2/apis.mustache
samples/client/petstore/typescript-angular2/default/api/api.ts
samples/client/petstore/typescript-angular2/npm/README.md
samples/client/petstore/typescript-angular2/npm/api/api.ts
samples/client/petstore/typescript-angular2/npm/package.json

To fix https://github.com/swagger-api/swagger-codegen/pull/4539#issuecomment-287834910

[TypeScript] fix class filename in TS Angular2 template

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java
samples/client/petstore/csharp/SwaggerClient/IO.Swagger.sln
samples/client/petstore/csharp/SwaggerClient/README.md
samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/IO.Swagger.csproj
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/IO.Swagger.sln
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/README.md
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/src/IO.Swagger.Test/IO.Swagger.Test.csproj
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/src/IO.Swagger/IO.Swagger.csproj
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/src/IO.Swagger/Model/Capitalization.cs

Update csharp generator help text about decommission of `uwp` and replacing it with v5.0

[C#] update csharp generator help text

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FlaskConnexionCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java
samples/server/petstore/flaskConnexion/swagger_server/swagger/swagger.yaml

To fix https://github.com/swagger-api/swagger-codegen/issues/4752#issuecomment-288336217

[Python][Flask] fix pattern in Python Flask generator

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaInflectorServerCodegen.java
modules/swagger-codegen/src/main/resources/JavaInflector/pom.mustache
samples/server/petstore/java-inflector/inflector.yaml
samples/server/petstore/java-inflector/pom.xml
samples/server/petstore/java-inflector/src/gen/java/io/swagger/controllers/StringUtil.java
samples/server/petstore/java-inflector/src/main/java/io/swagger/controllers/FakeClassnameTestController.java
samples/server/petstore/java-inflector/src/main/java/io/swagger/controllers/FakeController.java
samples/server/petstore/java-inflector/src/main/java/io/swagger/controllers/PetController.java
samples/server/petstore/java-inflector/src/main/java/io/swagger/controllers/StoreController.java
samples/server/petstore/java-inflector/src/main/java/io/swagger/controllers/UserController.java
samples/server/petstore/java-inflector/src/main/swagger/swagger.yaml

Fixes #5182 
** Breaking change for 2.3.0**
Renamed from `handlers` package to `controllers` for consistency

fix generated operationId

---

samples/server/petstore/flaskConnexion-python2/.dockerignore
samples/server/petstore/flaskConnexion-python2/Dockerfile
samples/server/petstore/flaskConnexion-python2/README.md
samples/server/petstore/flaskConnexion-python2/swagger_server/swagger/swagger.yaml
samples/server/petstore/flaskConnexion/swagger_server/swagger/swagger.yaml

→ bin/flaskConnexion.sh, bin/flaskConnexion-python2.sh
No code changes, just updating the samples (so later updates can see what actually changed).
The docker stuff came likely from #5133 (which just updated the samples for Python3).
Other than that, just a reordering in a .yaml.

Update samples flask connexion

---

samples/client/petstore/qt5cpp/client/SWGHelpers.cpp

→ bin/qt5-petstore.sh
No code changes, just updating the samples so later updates will show what actually changed.
There was just one added line, likely from #4834.

[C++][QT5] Update samples for QT5.

---

bin/java-msf4j-petstore-server.sh
modules/swagger-codegen/src/main/resources/MSF4J/pom.mustache
samples/server/petstore/java-msf4j/pom.xml
samples/server/petstore/java-msf4j/src/gen/java/io/swagger/api/FakeApi.java

→ bin/java-msf4j-petstore-server.sh
This fixes the indentation of the pom.xml for MSF4J, sets the artifactId as parameter in the generation script (previously it was just set manually in the generated pom, and thus overwritten after an sample update), and regenerates the samples.
I couldn't figure out where the enum related change in FakeApi.java came from.

[java][msf4j] Update msf4j samples (and fix artifact name)

---

samples/server/petstore/jaxrs-cxf-cdi/swagger.json
samples/server/petstore/jaxrs-spec/swagger.json

→ bin/jaxrs-spec-petstore-server.sh, bin/jaxrs-cxf-cdi-petstore-server.sh
No code changes, just updating the samples (so later updates show what actually changed.)
This just reorders some properties in JSON objects.

[Java][JaxRS] Updating samples for JaxRS servers: Spec + CXF-CDI.

---

samples/client/petstore/spring-stubs/pom.xml
samples/server/petstore/springboot-delegate-j8/pom.xml
samples/server/petstore/springboot-delegate/pom.xml

→ bin/spring-stubs.sh, bin/spring-delegate.sh, bin/spring-delegate-j8.sh
No code changes, just updating some samples (so later sample updates show actual changes).
The spring-fox dependency version updates are likely from #4993, I don't know where the spring-boot-starter-parent update comes from.

[java][spring] Updating samples for spring-stubs, springboot-delegate, springboot-delegate-j8

---

README.md

Add DocRaptor to Companies Using Swagger list. GitHub repo: https://github.com/docraptor

Add DocRaptor to Companies Using Swagger list

---

samples/client/petstore/csharp/SwaggerClient/IO.Swagger.sln
samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/IO.Swagger.csproj
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/IO.Swagger.sln
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/src/IO.Swagger.Test/IO.Swagger.Test.csproj
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/src/IO.Swagger/IO.Swagger.csproj

→ bin/csharp-petstore.sh, bin/csharp-property-changed-petstore.sh
No code changes, just updating the samples (so later sample updates show the actual changes).
This restores the GUID fixing of #5198, which was overwritten by the later merge of #5206.

Updating C# samples.

---

modules/swagger-codegen/src/main/resources/elixir/api.mustache
samples/client/petstore/elixir/lib/swagger_petstore/api/fake.ex
samples/client/petstore/elixir/lib/swagger_petstore/api/pet.ex
samples/client/petstore/elixir/lib/swagger_petstore/api/store.ex
samples/client/petstore/elixir/lib/swagger_petstore/api/user.ex

Add documentation for functions to elixir-client

[Elixir] Add documentation for functions

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenOperation.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AspNetCoreServerCodegen.java
modules/swagger-codegen/src/main/resources/aspnetcore/Dockerfile.mustache
modules/swagger-codegen/src/main/resources/aspnetcore/Program.mustache
modules/swagger-codegen/src/main/resources/aspnetcore/Properties/launchSettings.json
modules/swagger-codegen/src/main/resources/aspnetcore/Startup.mustache
modules/swagger-codegen/src/main/resources/aspnetcore/controller.mustache
modules/swagger-codegen/src/main/resources/aspnetcore/enumClass.mustache
modules/swagger-codegen/src/main/resources/aspnetcore/model.mustache
modules/swagger-codegen/src/main/resources/aspnetcore/project.json.mustache
modules/swagger-codegen/src/main/resources/aspnetcore/validateModel.mustache
modules/swagger-codegen/src/main/resources/aspnetcore/wwwroot/index.html
samples/server/petstore/aspnetcore/src/IO.Swagger/Attributes/ValidateModelStateAttribute.cs
samples/server/petstore/aspnetcore/src/IO.Swagger/Controllers/PetApi.cs
samples/server/petstore/aspnetcore/src/IO.Swagger/Controllers/StoreApi.cs
samples/server/petstore/aspnetcore/src/IO.Swagger/Controllers/UserApi.cs
samples/server/petstore/aspnetcore/src/IO.Swagger/Dockerfile
samples/server/petstore/aspnetcore/src/IO.Swagger/Models/ApiResponse.cs
samples/server/petstore/aspnetcore/src/IO.Swagger/Models/Category.cs
samples/server/petstore/aspnetcore/src/IO.Swagger/Models/Order.cs
samples/server/petstore/aspnetcore/src/IO.Swagger/Models/Pet.cs
samples/server/petstore/aspnetcore/src/IO.Swagger/Models/Tag.cs
samples/server/petstore/aspnetcore/src/IO.Swagger/Models/User.cs
samples/server/petstore/aspnetcore/src/IO.Swagger/Program.cs
samples/server/petstore/aspnetcore/src/IO.Swagger/Properties/launchSettings.json
samples/server/petstore/aspnetcore/src/IO.Swagger/Startup.cs
samples/server/petstore/aspnetcore/src/IO.Swagger/project.json
samples/server/petstore/aspnetcore/src/IO.Swagger/wwwroot/index.html

* Migrate from `Swashbuckle` to `Swashbuckle.AspNetCore`
* Add `[SwaggerResponse()]` for *all* responses, not just `200 OK`
* Add `[Required]` attribute for required fields in generated models
* Improve whitespace and remove some redundant code
* Fix all compiler warnings
* Add proper model state/input validation
* Regenerate AspNetCore PetStore sample
Fixes #5252, #5253, #5254, #5255 and #5256.

[C#][aspnetcore] Improve generated code

---

bin/utils/detect_tab_in_java_class.sh
modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenParameter.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenProperty.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/auth/AuthParser.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngularClientCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/InlineModelResolverTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/languages/JavaClientCodegenTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/AspNetCoreServerOptionsProvider.java

Replace tab with 4 space in Java files

---

modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/pom.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit/pom.mustache
modules/swagger-codegen/src/main/resources/Java/pom.mustache
modules/swagger-codegen/src/main/resources/akka-scala/pom.mustache
modules/swagger-codegen/src/main/resources/android/pom.mustache
modules/swagger-codegen/src/main/resources/codegen/pom.mustache
modules/swagger-codegen/src/main/resources/scala/pom.mustache
pom.xml
samples/client/petstore/akka-scala/pom.xml
samples/client/petstore/android/httpclient/pom.xml
samples/client/petstore/java/feign/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/jersey1/pom.xml
samples/client/petstore/java/jersey2-java6/pom.xml
samples/client/petstore/java/jersey2-java8/pom.xml
samples/client/petstore/java/jersey2/pom.xml
samples/client/petstore/java/retrofit/pom.xml
samples/client/petstore/scala/pom.xml

For https://github.com/swagger-api/swagger-codegen/pull/1695
Credits go to @sbroberg

Update maven compiler plugin to the latest version (3.6.1)

---

modules/swagger-codegen/src/main/resources/typescript-jquery/api.mustache
samples/client/petstore/typescript-jquery/default/api.ts
samples/client/petstore/typescript-jquery/npm/api.ts
samples/client/petstore/typescript-jquery/npm/package.json

According to TS style guide: https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#style

[TS][jQuery] replace tab with 4 space for TS jQuery templates

---

modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache
modules/swagger-codegen/src/main/resources/csharp/api.mustache
samples/client/petstore/csharp/SwaggerClient.v5/README.md
samples/client/petstore/csharp/SwaggerClient.v5/src/IO.Swagger/Api/FakeApi.cs
samples/client/petstore/csharp/SwaggerClient.v5/src/IO.Swagger/Api/PetApi.cs
samples/client/petstore/csharp/SwaggerClient.v5/src/IO.Swagger/Api/StoreApi.cs
samples/client/petstore/csharp/SwaggerClient.v5/src/IO.Swagger/Api/UserApi.cs
samples/client/petstore/csharp/SwaggerClient.v5/src/IO.Swagger/Client/ApiClient.cs
samples/client/petstore/csharp/SwaggerClient/docs/Fake_classname_tags123Api.md
samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/Api/FakeApi.cs
samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/Api/Fake_classname_tags123Api.cs
samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/Api/PetApi.cs
samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/Api/StoreApi.cs
samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/Api/UserApi.cs
samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/Client/ApiClient.cs
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/docs/Fake_classname_tags123Api.md
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/src/IO.Swagger/Api/FakeApi.cs
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/src/IO.Swagger/Api/Fake_classname_tags123Api.cs
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/src/IO.Swagger/Api/PetApi.cs
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/src/IO.Swagger/Api/StoreApi.cs
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/src/IO.Swagger/Api/UserApi.cs
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/src/IO.Swagger/Client/ApiClient.cs

Cherry-picking https://github.com/swagger-api/swagger-codegen/pull/2790 for 2.3.0 branch
Credits go to @sean11

[C#] Add support "multi" collectionFormat query string parametershttps://github.com/swagger-api/swagger-codegen/pull/2790

---

samples/client/petstore-security-test/scala/pom.xml
samples/client/petstore-security-test/scala/src/main/scala/io/swagger/client/ApiInvoker.scala
samples/client/petstore-security-test/scala/src/main/scala/io/swagger/client/api/FakeApi.scala
samples/client/petstore-security-test/scala/src/main/scala/io/swagger/client/model/ModelReturn.scala

→ bin/security/scala-petstore.sh
No code changes, just updating some samples so that later updates show what actually changed.

[Scala] Updating security samples for scala client.

---

samples/client/petstore-security-test/php/SwaggerClient-php/lib/Api/FakeApi.php
samples/client/petstore-security-test/php/SwaggerClient-php/lib/Configuration.php
samples/client/petstore-security-test/php/SwaggerClient-php/lib/ObjectSerializer.php

→ bin/security/php-petstore.sh
No code changes, just updating samples so later updates show what actually changed.

[PHP] Updating security samples for PHP client.

---

samples/client/petstore-security-test/python/petstore_api/apis/fake_api.py
samples/client/petstore-security-test/python/petstore_api/configuration.py
samples/client/petstore-security-test/python/petstore_api/rest.py

→ bin/security/python-petstore.sh
No code changes, just updating some samples so later updates show what actually changed.

[Python] Updating security samples for Python client.

---

modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/play24/Play24CallAdapterFactory.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/play24/Play24CallFactory.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/pom.mustache
samples/client/petstore/java/retrofit2-play24/pom.xml
samples/client/petstore/java/retrofit2-play24/src/main/java/io/swagger/client/Play24CallAdapterFactory.java
samples/client/petstore/java/retrofit2-play24/src/main/java/io/swagger/client/Play24CallFactory.java

Updated CallAdapter & CallAdapterFactory for retrofit 2.2.0

[Play] [Retrofit2] Updated CallAdapter & CallAdapterFactory for retrofit 2.2.0

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Swift3Codegen.java

For https://github.com/swagger-api/swagger-codegen/issues/5323

[Swift3] update reserved word list for swift3 generator

---

modules/swagger-codegen/src/main/resources/swift3/AlamofireImplementations.mustache
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/AlamofireImplementations.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/AlamofireImplementations.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/AlamofireImplementations.swift

Swift3 headers

---

README.md

Signed-off-by: weiyang <weiyang.ones@gmail.com>
- [REAMME] Add [XSky](http://www.xsky.com/) to company list

[README] Add XSky to company list

---

modules/swagger-codegen/src/main/resources/Java/build.gradle.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/feign/build.gradle.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/build.gradle.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/build.gradle.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit/build.gradle.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/build.gradle.mustache
modules/swagger-codegen/src/main/resources/android/build.mustache
modules/swagger-codegen/src/main/resources/android/libraries/volley/build.mustache

[JAVA] Update gradle and android build tools

---

modules/swagger-generator/Dockerfile
modules/swagger-generator/pom.xml
modules/swagger-generator/src/main/webapp/index.html

Fixes #5444 by using open jdk.  Also switch index.html to use latest editor

Updated to openjdk (2.3.0)

---

modules/swagger-generator/Dockerfile
modules/swagger-generator/src/main/webapp/index.html

updated to openjdk

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
modules/swagger-codegen/src/main/resources/Java/apiException.mustache
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/JavaClientOptionsProvider.java

Add an option to change Exception to RuntimeException with Java generation 
works with pet store and --additional-properties=useRuntimeException=true
https://github.com/swagger-api/swagger-codegen/issues/4376

Add RuntimeException option

---

README.md

Thank you for suggesting @wing328.

Adding Stardog Ventures to company list

---

modules/swagger-codegen/src/main/resources/go/model.mustache
modules/swagger-codegen/src/main/resources/go/model_doc.mustache
samples/client/petstore/go/go-petstore/docs/EnumTest.md
samples/client/petstore/go/go-petstore/docs/Fake_classname_tags123Api.md
samples/client/petstore/go/go-petstore/docs/Pet.md
samples/client/petstore/go/go-petstore/enum_test.go
samples/client/petstore/go/go-petstore/fake_api.go
samples/client/petstore/go/go-petstore/format_test.go
samples/client/petstore/go/go-petstore/pet.go
samples/client/petstore/go/go-petstore/pet_api.go
samples/client/petstore/go/go-petstore/store_api.go

- [go][model] Use pointers to avoid circular references

[go][model] Use pointers to avoid circular references

---

modules/swagger-codegen/src/main/resources/typescript-angular/apis.mustache
samples/client/petstore/typescript-angular/api/api.ts

For https://github.com/swagger-api/swagger-codegen/pull/5396#pullrequestreview-33013964

[TypeScript][Angular] Remove trailing comma in "APIS"

---

modules/swagger-codegen/src/main/resources/JavaSpring/beanValidation.mustache

add @Valid annotation when to model getter when type is a RefProperty or a collection containing RefProperty.

[JavaSpring] add support for cascading bean validation

---

README.md

We're using it for automated generation of client libraries in our microservices architectures. Thanks for all the work in making a great tool!

Add Yelp to list of companies using swagger-codegen

---

modules/swagger-codegen/src/main/resources/swift3/Models.mustache
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/Models.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/Models.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/Models.swift

Example Swift Petstore tests did not compile on HEAD of 2.3.0 branch

[Swift3] Fix compilation of models file

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ApexClientCodegen.java

Updated default Apex API version to v39 (Spring '17 release)

---

pom.xml

Updated parser to v1.0.29

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java
modules/swagger-codegen/src/main/resources/csharp/Configuration.mustache
modules/swagger-codegen/src/main/resources/csharp/IReadableConfiguration.mustache
modules/swagger-codegen/src/main/resources/csharp/api.mustache
samples/client/petstore/csharp/SwaggerClient/docs/PetApi.md
samples/client/petstore/csharp/SwaggerClient/docs/StoreApi.md
samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/Client/Configuration.cs
samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/Client/IReadableConfiguration.cs
samples/client/petstore/csharp/SwaggerClientNetStandard/docs/PetApi.md
samples/client/petstore/csharp/SwaggerClientNetStandard/docs/StoreApi.md
samples/client/petstore/csharp/SwaggerClientNetStandard/src/IO.Swagger/Client/Configuration.cs
samples/client/petstore/csharp/SwaggerClientNetStandard/src/IO.Swagger/Client/IReadableConfiguration.cs
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/docs/PetApi.md
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/docs/StoreApi.md
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/src/IO.Swagger/Client/Configuration.cs
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/src/IO.Swagger/Client/IReadableConfiguration.cs

- minor fix to C# (.net 3.5) client
- add XML documentation to new class

[C#] minor fix to C# (.net 3.5) client, add XML documentation to new class

---

modules/swagger-codegen/src/main/resources/Javascript-es6/README.mustache
modules/swagger-codegen/src/main/resources/Javascript/README.mustache
samples/client/petstore/javascript-es6/README.md
samples/client/petstore/javascript-promise-es6/README.md
samples/client/petstore/javascript-promise/README.md
samples/client/petstore/javascript/README.md

[javascript] Added README section for Webpack configuration

---

modules/swagger-codegen/src/main/resources/Javascript-es6/README.mustache
modules/swagger-codegen/src/main/resources/Javascript/README.mustache
samples/client/petstore/javascript-es6/README.md
samples/client/petstore/javascript-promise-es6/README.md
samples/client/petstore/javascript-promise/README.md
samples/client/petstore/javascript/README.md

Reverts swagger-api/swagger-codegen#5767

Revert "[javascript] Added README section for Webpack configuration"

---

modules/swagger-codegen/src/main/resources/JavaPlayFramework/newApiController.mustache
modules/swagger-codegen/src/main/resources/JavaPlayFramework/swaggerUtils.mustache
samples/server/petstore/java-play-framework/app/controllers/PetApiController.java
samples/server/petstore/java-play-framework/app/swagger/SwaggerUtils.java

Basic support for the collection parameters. Any suggestion is welcome!

[JavaPlayFramework] Add basic support for collection.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/StaticHtml2Generator.java
modules/swagger-codegen/src/main/resources/htmlDocs2/index.mustache

Pre-format Html for speed up the render on page loading.

StaticHtml2Gen | Speed up appDescription rendering

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CppRestClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/NancyFXServerCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/utils/ModelUtils.java
modules/swagger-codegen/src/main/resources/cpprest/api-source.mustache
modules/swagger-codegen/src/main/resources/cpprest/model-header.mustache
modules/swagger-codegen/src/main/resources/cpprest/model-source.mustache

- [x ] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.
This PR will fix the issue#5788
https://github.com/swagger-api/swagger-codegen/issues/5788

Fix for issue#5788 -CPPRest generated models are not using inheritance as specified in contract

---

README.md

Added GE in the list of companies using swagger-codegen

Added GE to list of companies using swagger-codegen

---

modules/swagger-codegen/src/main/resources/Javascript-es6/ApiClient.mustache
modules/swagger-codegen/src/main/resources/Javascript/ApiClient.mustache
samples/client/petstore/javascript-es6/src/ApiClient.js
samples/client/petstore/javascript-promise-es6/src/ApiClient.js
samples/client/petstore/javascript-promise/src/ApiClient.js
samples/client/petstore/javascript/src/ApiClient.js

Follow up to #5759 , forgot to also fix javascript-es6.

[JS] Fix JavaScript string return type

---

samples/html2/index.html

→ bin/html2-petstore.sh
No code changes, just updating of samples. Some markdown converted to HTML.

Update samples for html2.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PistacheServerCodegen.java

Use file.separator, minor code format enhancement (as mentioned in https://github.com/swagger-api/swagger-codegen/pull/5838#discussion_r121965670)

[C++][Pistache] Use File.separator, minor code format enhancement

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/examples/ExampleGenerator.java

Issue# https://github.com/swagger-api/swagger-codegen/issues/5666
Filing against 2.3.0 since Example Generator is considered as a breaking change

Example Generator to populate model for all references of a given model

---

samples/client/petstore/typescript-angular2/with-interfaces/api/PetApi.ts
samples/client/petstore/typescript-angular2/with-interfaces/api/StoreApi.ts
samples/client/petstore/typescript-angular2/with-interfaces/api/UserApi.ts

→ bin/typescript-angular2-petstore-all.sh
No code changes, just updating of samples. Just two comments moved to a different place.

Update samples for typescript-angular2.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngular2ClientCodegen.java
modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache
modules/swagger-codegen/src/main/resources/typescript-angular2/variables.mustache
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/TypeScriptAngular2ClientOptionsProvider.java
samples/client/petstore/typescript-angular2/default/variables.ts
samples/client/petstore/typescript-angular2/npm/variables.ts
samples/client/petstore/typescript-angular2/with-interfaces/variables.ts

As discussed, we'll roll back #5569 and file a new one against 2.3.0 branch only.

PR to roll back #5569

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngular2ClientCodegen.java
modules/swagger-codegen/src/main/resources/typescript-angular2/variables.mustache
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/TypeScriptAngular2ClientOptionsProvider.java
samples/client/petstore/typescript-angular2/default/variables.ts
samples/client/petstore/typescript-angular2/npm/variables.ts
samples/client/petstore/typescript-angular2/with-interfaces/variables.ts

Redo #5569 to 2.3.0 branch

---

README.md

add testimonial of Viavi Solutions Inc.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
samples/client/petstore/java/jersey2-java6/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/jersey2-java8/src/main/java/io/swagger/client/ApiClient.java

Recursively add import for parameters
Closes #5885

Recursively add import for parameters

---

README.md

Added one presentation to README.md

---

modules/swagger-codegen-maven-plugin/examples/java-client.xml
modules/swagger-codegen/src/main/resources/Java/libraries/feign/pom.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/resteasy/pom.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/pom.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/server/pom.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/libraries/jersey1/pom.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/pom.mustache
modules/swagger-codegen/src/main/resources/JavaSpring/libraries/spring-mvc/pom.mustache
modules/swagger-codegen/src/main/resources/scala/pom.mustache
modules/swagger-codegen/src/test/resources/2_0/templates/Java/libraries/jersey2/pom.mustache
pom.xml
pom.xml.circleci
samples/client/petstore-security-test/scala/pom.xml
samples/client/petstore/java/feign/pom.xml
samples/client/petstore/java/resteasy/pom.xml
samples/client/petstore/jaxrs-cxf-client/pom.xml
samples/client/petstore/jaxrs-cxf/pom.xml
samples/client/petstore/scala/pom.xml
samples/server/petstore/jaxrs-cxf/pom.xml
samples/server/petstore/jaxrs/jersey1/pom.xml
samples/server/petstore/jaxrs/jersey2/pom.xml
samples/server/petstore/spring-mvc-j8-async/pom.xml
samples/server/petstore/spring-mvc/pom.xml

I've updated the Jackson version to 2.8.9.

updated jackson-version

---

modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/server/pom.mustache

Updated Swagger-UI to latest version

updated swagger-ui dependency

---

modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/server/pom.mustache
modules/swagger-codegen/src/main/resources/JavaSpring/libraries/spring-boot/pom.mustache
modules/swagger-codegen/src/main/resources/JavaSpring/libraries/spring-cloud/pom.mustache
modules/swagger-codegen/src/main/resources/JavaSpring/libraries/spring-mvc/pom.mustache
samples/client/petstore/spring-cloud/pom.xml
samples/client/petstore/spring-stubs/pom.xml
samples/server/petstore/spring-mvc-j8-async/pom.xml
samples/server/petstore/spring-mvc/pom.xml
samples/server/petstore/springboot-beanvalidation/pom.xml
samples/server/petstore/springboot-delegate-j8/pom.xml
samples/server/petstore/springboot-delegate/pom.xml
samples/server/petstore/springboot-implicitHeaders/pom.xml
samples/server/petstore/springboot/pom.xml

#5947 contains the update to the latest versions, this PR updates master to Spring Boot 1.4.x latest (with security fixes).

updated Spring and Spring Boot dependencies

---

modules/swagger-codegen/src/main/resources/TypeScript-Fetch/api.mustache

fix(ts-fetch): preserve available headers

---

README.md

Add Sponsoo to list of companies using swagger codegen

Add Sponsoo to list of companies using swagger codegen

---

pom.xml
samples/client/petstore/typescript-angular2/default/configuration.ts
samples/client/petstore/typescript-angular2/npm/configuration.ts
samples/client/petstore/typescript-angular2/npm/package-lock.json
samples/client/petstore/typescript-angular2/npm/pom.xml
samples/client/petstore/typescript-angular2/with-interfaces/configuration.ts
samples/client/petstore/typescript-angular4/npm/package-lock.json
samples/client/petstore/typescript-angular4/npm/pom.xml

Add integration tests by running `npm install` (which also runs `npm run build` in post-install)
(typescript-node test has been commented out due to errors with Github rate limiting)

[TypeScript][Angualr2] Add integration tests

---

modules/swagger-codegen/src/main/resources/TypeScript-Fetch/api.mustache
modules/swagger-codegen/src/main/resources/typescript-angular/api.mustache
modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache
modules/swagger-codegen/src/main/resources/typescript-jquery/api.mustache
modules/swagger-codegen/src/main/resources/typescript-node/api.mustache
samples/client/petstore/typescript-angular/api/PetApi.ts
samples/client/petstore/typescript-angular/api/StoreApi.ts
samples/client/petstore/typescript-angular/api/UserApi.ts
samples/client/petstore/typescript-fetch/builds/default/api.ts
samples/client/petstore/typescript-fetch/builds/es6-target/api.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/api.ts
samples/client/petstore/typescript-jquery/default/api.ts
samples/client/petstore/typescript-jquery/npm/api.ts
samples/client/petstore/typescript-node/default/api.ts
samples/client/petstore/typescript-node/npm/api.ts

Similar to https://github.com/swagger-api/swagger-codegen/pull/6028/files, we'll make the same enhancement to node, jquery, fetch, angular

[Typescript] add @summary JSDoc tag

---

bin/java-petstore-all.sh
bin/java-petstore-resttemplate-withxml.sh
modules/swagger-codegen/src/main/resources/Java/modelInnerEnum.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf-cdi/pojo.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/enumOuterClass.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/pojo.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/enumClass.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/enumOuterClass.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/modelEnum.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/pojo.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/resteasy/eap/enumClass.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/resteasy/eap/pojo.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/resteasy/enumClass.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/resteasy/pojo.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/spec/enumOuterClass.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/spec/pojo.mustache
modules/swagger-codegen/src/main/resources/aspnetcore/model.mustache
modules/swagger-codegen/src/main/resources/csharp/enumClass.mustache
modules/swagger-codegen/src/main/resources/csharp/modelEnum.mustache
modules/swagger-codegen/src/main/resources/csharp/modelGeneric.mustache
modules/swagger-codegen/src/main/resources/csharp/modelInnerEnum.mustache
modules/swagger-codegen/src/main/resources/nancyfx/modelEnum.mustache
samples/client/petstore/java/resttemplate-withXml/build.gradle
samples/client/petstore/java/resttemplate-withXml/pom.xml
samples/client/petstore/java/resttemplate-withXml/settings.gradle
samples/client/petstore/java/resttemplate/pom.xml

Similar to https://github.com/swagger-api/swagger-codegen/pull/6040, we'll use {{description}} for C# (client, server), Java (server)

Use html-escaped description for C# (client, server), Java server

---

modules/swagger-codegen/src/main/resources/qt5cpp/api-body.mustache
modules/swagger-codegen/src/main/resources/qt5cpp/api-header.mustache

expose default headers, add headers to request

---

modules/swagger-codegen/src/main/resources/qt5cpp/api-body.mustache
modules/swagger-codegen/src/main/resources/qt5cpp/api-header.mustache

updated qt5 headers

---

modules/swagger-codegen/src/main/resources/typescript-angular2/modelEnum.mustache

Fix enum model display duplicate description #6072

[Typescript-Angular2] Fix enum model display duplicate description #6072

---

modules/swagger-codegen/src/main/resources/JavaPlayFramework/paramDefaultValue.mustache
samples/server/petstore/java-play-framework/app/controllers/PetApiController.java
samples/server/petstore/java-play-framework/public/swagger.json

Fix to the default values. It was not using the right values and didn't take care of the "default" parameter.

[Java Play Framework] Fix to the default values

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/csharp/CsharpModelEnumTest.java

Unboxing the boolean will throw java.lang.NullPointerException if the condition is false

fix npe :Unboxing of '(count < numVars) ? true : null' produce npe

---

modules/swagger-codegen/src/main/resources/swift3/Models.mustache
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/Models.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/Models.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/Models.swift
samples/client/petstore/swift3/unwraprequired/PetstoreClient/Classes/Swaggers/Models.swift

[Swift3] Fixed compilation issue on macOS

---

modules/swagger-codegen/src/main/resources/swift3/APIHelper.mustache
modules/swagger-codegen/src/main/resources/swift3/APIs.mustache
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIHelper.swift
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIHelper.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIHelper.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs.swift
samples/client/petstore/swift3/unwraprequired/PetstoreClient/Classes/Swaggers/APIHelper.swift
samples/client/petstore/swift3/unwraprequired/PetstoreClient/Classes/Swaggers/APIs.swift

**Improve generated code in APIs so to use the most of Swift SDK**: I've used the methods `reduce` and `flatMap` to iterate the dictionaries, it proved to be faster on my tests. Also the code is more readable IMHO.
Also I've used the `isEmpty` property in place of `count == 0`.
**Improve generated code in APIHelper so to remove duplicated code and reuse existing checks**: there were two ways to append items to the headers, and one of them was not checking for empty params as the other one does.

Swift3 code enhancements 

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Swift3Codegen.java

Add "Data" to Reserved Keywords

fix add "Data" to reserved Keywords (#6011)

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java
modules/swagger-codegen/src/main/resources/python/model.mustache

This pull request adds discriminator support for python. Issue #4622 is currently open for discussion of all languages lacking polymorphism support.

Add polymorphism support for python

---

README.md

Update README.md to fix broken TOC link

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java

import models fix for csharp

---

modules/swagger-codegen/src/main/resources/JavaPlayFramework/conversionBegin.mustache
modules/swagger-codegen/src/main/resources/JavaPlayFramework/conversionEnd.mustache

Fix date-time params in Java-Play codegen

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/staticDocs/StaticOperationTest.java

generate boolean getter method according to a code convention

---

modules/swagger-codegen/src/main/resources/htmlDocs2/js_jsonschemaview.mustache

fix the issue 5779

---

modules/swagger-codegen/src/main/resources/JavaPlayFramework/build.mustache
samples/server/petstore/java-play-framework/build.sbt

[Java Play-Framework] Remove unneeded deps

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AndroidClientCodegen.java

Closes https://github.com/swagger-api/swagger-codegen/issues/6183

[Android] set auth, request package based on "invokerPackage"

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java

In order to have year placed in generated text I added a that data in DefaultCodegen code

Added year to default generator

---

modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
samples/client/petstore/java/jersey2-java6/docs/FakeClassnameTags123Api.md
samples/client/petstore/java/jersey2-java6/pom.xml
samples/client/petstore/java/jersey2-java6/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/jersey2-java6/src/main/java/io/swagger/client/api/FakeClassnameTags123Api.java
samples/client/petstore/java/jersey2-java6/src/main/java/io/swagger/client/model/Cat.java
samples/client/petstore/java/jersey2-java6/src/main/java/io/swagger/client/model/Order.java
samples/client/petstore/java/jersey2/docs/FakeClassnameTags123Api.md
samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/api/FakeClassnameTags123Api.java
samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/model/Cat.java
samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/model/Order.java

Add HTTP PATCH method for jersey2

[Java][Client] Add PATCH method support for jersey2

---

README.md

Added Fitwell to using companies

---

modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache

Finishes work started in #6188 and #6175

[Java] okhttp-gson content-type fix for */*

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java
samples/client/petstore/javascript-es6/README.md
samples/client/petstore/javascript-es6/docs/Fake_classname_tags123Api.md
samples/client/petstore/javascript-es6/src/ApiClient.js
samples/client/petstore/javascript-es6/src/api/Fake_classname_tags123Api.js
samples/client/petstore/javascript-promise-es6/README.md
samples/client/petstore/javascript-promise-es6/docs/Fake_classname_tags123Api.md
samples/client/petstore/javascript-promise-es6/src/ApiClient.js
samples/client/petstore/javascript-promise-es6/src/api/Fake_classname_tags123Api.js
samples/client/petstore/javascript-promise/README.md
samples/client/petstore/javascript-promise/docs/Fake_classname_tags123Api.md
samples/client/petstore/javascript-promise/src/ApiClient.js
samples/client/petstore/javascript-promise/src/api/Fake_classname_tags123Api.js
samples/client/petstore/javascript/README.md
samples/client/petstore/javascript/docs/Fake_classname_tags123Api.md
samples/client/petstore/javascript/src/ApiClient.js
samples/client/petstore/javascript/src/api/Fake_classname_tags123Api.js
samples/client/petstore/javascript/test/ApiClientTest.js

[JS] fix template directory for ES5

---

modules/swagger-codegen/src/main/resources/Java/api.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/feign/api.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/api.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/api.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/resteasy/api.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/resttemplate/api.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit/api.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/api.mustache

Add externalDocs support

---

samples/client/petstore/lua/README.md
samples/client/petstore/lua/main.lua
samples/client/petstore/lua/petstore_client/init.lua
samples/client/petstore/lua/petstore_client/pet.lua

#WIP 
As suggested in https://github.com/swagger-api/swagger-codegen/issues/4794#issuecomment-320245838
This implementation uses [lua-http](https://github.com/daurnimator/lua-http)

samples/client/petstore/lua: Add lua sample

---

modules/swagger-codegen/src/main/resources/typescript-jquery/api.mustache
samples/client/petstore/typescript-jquery/default/api/PetApi.ts
samples/client/petstore/typescript-jquery/npm/api/PetApi.ts

Fix a problem for uploading file that I found while testing my huge project at work.

[Typescript-Jquery] Fix file upload

---

modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/ApiClient.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/build.gradle.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/build.sbt.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/pom.mustache
samples/client/petstore/java/retrofit2rx2/build.gradle
samples/client/petstore/java/retrofit2rx2/build.sbt
samples/client/petstore/java/retrofit2rx2/pom.xml
samples/client/petstore/java/retrofit2rx2/src/main/java/io/swagger/client/ApiClient.java

Updating the RxJava2 adapter for Retrofit 2 to the current version.
This complete the work from https://github.com/swagger-api/swagger-codegen/pull/6056 by @ntrp who's away.

Retrofit2 rxjava2 adapter imports

---

samples/client/petstore/R/DESCRIPTION
samples/client/petstore/R/LICENSE

Remove License File from Petstore Client R Package

---

bin/python-tornado-petstore.sh
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java
modules/swagger-codegen/src/main/resources/python/api_client.mustache
modules/swagger-codegen/src/main/resources/python/setup.mustache
modules/swagger-codegen/src/main/resources/python/tornado/rest.mustache

Similar to #6245, this adds support in Python for the [tornado](http://tornadoweb.org/) web framework.

implemented tornado-based client.

---

README.md

Fixes a small typo in README.md

Fixes a small typo in README.md

---

modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/api.mustache

Reverts swagger-api/swagger-codegen#6407

Revert "[Java][Retrofit2] Return ResponseBody if response is "file""

---

modules/swagger-codegen/src/main/resources/swift4/CodableHelper.mustache

Simple change to update to latest Swift4 syntax in the CodableHelper.mustache template.

[Swift4] Updates syntax in Codable helper template.

---

modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/api.mustache

Resubmitted https://github.com/swagger-api/swagger-codegen/pull/6407

[Java][Retrofit2] Return ResponseBody if response is "file"

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java

Fix https://github.com/swagger-api/swagger-codegen/issues/6456

[C#] fix NPE when getting swagger type

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Qt5CPPGenerator.java
modules/swagger-codegen/src/main/resources/qt5cpp/model-body.mustache

- Adjusted init function to init map correctly
- Adjusted cleanup function to cleanup maps correctly
Relates to: #6316

[QT5][CPP] Fixing issue with maps in models

---

modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/play25/Play25CallFactory.mustache
samples/client/petstore/java/retrofit2-play25/src/main/java/io/swagger/client/Play25CallFactory.java

Added ability to include filters (interceptors) for api calls (can be used to logging or other stuff)

[Java] Added Play! WS filters support for retrofit2 client 

---

README.md

Add link to Jenkins World 2017 talk which uses Swagger Codegen to generate Remote Access API and Blue Ocean API clients.

Add Jenkins World 2017 talk.

---

README.md

I am developing [Gradle Swagger Generator Plugin](https://github.com/int128/gradle-swagger-generator-plugin) and would like to introduce it in README page.

Add link to Gradle Swagger Generator Plugin

---

modules/swagger-codegen/src/main/resources/cpprest/apiclient-source.mustache

This pull request is related to 
swagger-api/swagger-codegen cpprest runtime bug with form parameters
#6522 opened 18 minutes ago by WendellDuncan

Propsed fix for the ApiClient runtime crash

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java

Typo error fix

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SpringCodegen.java

Fix class path for DeferredResult

---

modules/swagger-codegen/src/main/resources/Eiffel/api.mustache
modules/swagger-codegen/src/main/resources/Eiffel/api_client.mustache
modules/swagger-codegen/src/main/resources/Eiffel/model.mustache

Updated api client, Required parameters {{#required}} .. {{/required} are mapped to Eiffel
Void Safety Rules, optional parameters are translated to detachable TYPE.
Validation Rules are mapped to preconditions, at the moment maximun and minimun
validation has been added.
Improved API_CLIENT.parameter_to_tuple feature to accept a LIST [ANY] instead of LIST [STRING_32].
Improved model template to generate the model output.

[Eiffel] Enhancements to the Eiffel generator

---

modules/swagger-codegen-cli/pom.xml
modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/CLIHelper.java
modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/SwaggerCodegen.java
modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/cmd/ConfigHelp.java
modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/cmd/Generate.java
modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/cmd/Langs.java
modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/cmd/Meta.java
modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/cmd/Validate.java
modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/cmd/Version.java
modules/swagger-codegen-cli/src/main/resources/oas3.yaml

On this PR:
- Removed airline library and annotations
- Added argparser4j library
- Commands and option arguments are now loaded from resource file `oas3.yaml`
- Custom commands and arguments can be implemented updating the resource files (to be improved)
- Right now there are dependency issues which will be fixed on coming PR's.

Issue 6041

---

README.md

Add http://www.nttdata.com to Companies/Projects using Swagger Codegen.

Add http://www.nttdata.com

---

modules/swagger-codegen/src/main/resources/Javascript/ApiClient.mustache
modules/swagger-codegen/src/main/resources/Javascript/es6/ApiClient.mustache

Allow use to pass through instance a custom http agent, ie: 
```js
const TestApi = require('test_api_200'); // generated code
const Agent = require('agentkeepalive');
const keepaliveAgent = new Agent({
maxSockets: 100,
maxFreeSockets: 10,
timeout: 60000,
keepAliveTimeout: 30000
});
TestApi.ApiClient.instance.basePath = 'http://localhost:3131';
TestApi.ApiClient.instance.requestAgent = keepaliveAgent;
const apiInstance = new TestApi.UsersApi();
apiInstance.deleteUser(42);
```
Fixes #6736

[JavaScript] Handle custom request.agent

---

README.md

~- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.~
~- [ ] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.~
@metaswitch has just contributed the `rust-server` generator that we are currently using in production.

Add Metaswitch to list of companies

---

modules/swagger-codegen/src/main/resources/r/api.mustache
samples/client/petstore/r_test/R/ApiResponse.r
samples/client/petstore/r_test/R/Category.r
samples/client/petstore/r_test/R/Order.r
samples/client/petstore/r_test/R/Pet.r
samples/client/petstore/r_test/R/PetApi.r
samples/client/petstore/r_test/R/StoreApi.r
samples/client/petstore/r_test/R/Tag.r
samples/client/petstore/r_test/R/User.r
samples/client/petstore/r_test/R/UserApi.r

To fix https://github.com/swagger-api/swagger-codegen/issues/6520#issuecomment-338110641

[R] fix non-function error with body parameter

---

README.md

Added FINRA as a company using swagger codegen opensource

Update README.md Added FINRA as a consumer of swagger and swagger codgen

---

modules/swagger-codegen/src/main/resources/flaskConnexion/__main__.mustache
modules/swagger-codegen/src/main/resources/flaskConnexion/git_push.sh.mustache
modules/swagger-codegen/src/main/resources/flaskConnexion/setup.mustache
modules/swagger-codegen/src/main/resources/flaskConnexion/tox.mustache
samples/server/petstore/flaskConnexion-python2/git_push.sh
samples/server/petstore/flaskConnexion-python2/setup.py
samples/server/petstore/flaskConnexion-python2/swagger_server/__main__.py
samples/server/petstore/flaskConnexion-python2/swagger_server/swagger/swagger.yaml
samples/server/petstore/flaskConnexion-python2/tox.ini
samples/server/petstore/flaskConnexion/git_push.sh
samples/server/petstore/flaskConnexion/setup.py
samples/server/petstore/flaskConnexion/swagger_server/__main__.py
samples/server/petstore/flaskConnexion/swagger_server/swagger/swagger.yaml
samples/server/petstore/flaskConnexion/tox.ini

Enable the creation of the entrypoint so that the server can be started
using a named command instead of needing to always use `python -m` to
run the server.
@taxpon  @frol  @mbohlool  @cbornet

[python-flask] Create main function and entrypoint

---

modules/swagger-codegen/src/main/resources/typescript-angular/api.module.mustache
modules/swagger-codegen/src/main/resources/typescript-angular/api.service.mustache
modules/swagger-codegen/src/main/resources/typescript-angular/configuration.mustache
modules/swagger-codegen/src/main/resources/typescript-angular/package.mustache
samples/client/petstore/typescript-angular-v2/default/api.module.ts
samples/client/petstore/typescript-angular-v2/default/configuration.ts
samples/client/petstore/typescript-angular-v2/npm/api.module.ts
samples/client/petstore/typescript-angular-v2/npm/configuration.ts
samples/client/petstore/typescript-angular-v2/npm/package.json
samples/client/petstore/typescript-angular-v2/with-interfaces/api.module.ts
samples/client/petstore/typescript-angular-v2/with-interfaces/configuration.ts
samples/client/petstore/typescript-angular-v4.3/npm/api.module.ts
samples/client/petstore/typescript-angular-v4.3/npm/api/pet.service.ts
samples/client/petstore/typescript-angular-v4.3/npm/api/store.service.ts
samples/client/petstore/typescript-angular-v4.3/npm/api/user.service.ts
samples/client/petstore/typescript-angular-v4.3/npm/configuration.ts
samples/client/petstore/typescript-angular-v4/npm/api.module.ts
samples/client/petstore/typescript-angular-v4/npm/configuration.ts
samples/client/petstore/typescript-angular-v4/npm/package.json

Remove trailing spaces.
@TiFu @taxpon @sebastianhaas @Vrolijkx @mhardorf @kenisteward

[TS][Angular] minor code format enhancement

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java

fix NPE of Could not generate api file for. 
Add check type npe.

[issue-6860] fix NPE of Could not generate api file for

---

modules/swagger-codegen/src/main/resources/qt5cpp/model-body.mustache
modules/swagger-codegen/src/main/resources/qt5cpp/model-header.mustache
modules/swagger-codegen/src/main/resources/qt5cpp/model.mustache
samples/client/petstore/qt5cpp/client/SWGApiResponse.cpp
samples/client/petstore/qt5cpp/client/SWGApiResponse.h
samples/client/petstore/qt5cpp/client/SWGCategory.cpp
samples/client/petstore/qt5cpp/client/SWGCategory.h
samples/client/petstore/qt5cpp/client/SWGOrder.cpp
samples/client/petstore/qt5cpp/client/SWGOrder.h
samples/client/petstore/qt5cpp/client/SWGPet.cpp
samples/client/petstore/qt5cpp/client/SWGPet.h
samples/client/petstore/qt5cpp/client/SWGTag.cpp
samples/client/petstore/qt5cpp/client/SWGTag.h
samples/client/petstore/qt5cpp/client/SWGUser.cpp
samples/client/petstore/qt5cpp/client/SWGUser.h

Minor formatting enhancement
cc @ravinikam @stkrwork

[C++][QT5] Remove trailing spaces, empty lines

---

circle.yml

Reverts swagger-api/swagger-codegen#6837

Revert "Docker image tags"

---

README.md

Added company Thirdwatch.ai in Readme.md which is using swagger.

Added Company using Sawgger in Readme.md

---

README.md

- My tech talk at [JJUG CCC 2017 Fall](http://www.java-users.jp/ccc2017fall/)
- JJUG CCC is Japan’s largest Java community event.
- We use swagger-codegen to generate ruby client from Kotlin API server

add my slide to README.md

---

README.md

add link to d-date's presentation

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/ignore/CodegenIgnoreProcessor.java

- [n/a] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.
simple typo fix

fix swager typo

---

README.md

Add [GMO Pepabo](https://pepabo.com/en/) to Companies/Projects using Swagger Codegen.

Add GMO Pepabo

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ErlangClientCodegen.java
modules/swagger-codegen/src/main/resources/erlang-client/api.mustache
modules/swagger-codegen/src/main/resources/erlang-client/model.mustache
samples/client/petstore/erlang-client/src/swagger_api_response.erl
samples/client/petstore/erlang-client/src/swagger_category.erl
samples/client/petstore/erlang-client/src/swagger_order.erl
samples/client/petstore/erlang-client/src/swagger_pet.erl
samples/client/petstore/erlang-client/src/swagger_pet_api.erl
samples/client/petstore/erlang-client/src/swagger_store_api.erl
samples/client/petstore/erlang-client/src/swagger_tag.erl
samples/client/petstore/erlang-client/src/swagger_user.erl
samples/client/petstore/erlang-client/src/swagger_user_api.erl

This PR fixes the handling of optional parameters by adding an argument to api requests that is to contain a map of optional parameters to their values.

[Erlang] erlang client: properly handle optional parameters

---

modules/swagger-codegen/src/main/resources/swift/Podspec.mustache
modules/swagger-codegen/src/main/resources/swift3/Podspec.mustache
modules/swagger-codegen/src/main/resources/swift4/Podspec.mustache

#7026 [Swift] tvos support added

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngularClientCodegen.java
modules/swagger-codegen/src/main/resources/typescript-angular/rxjs-operators.mustache
samples/client/petstore/typescript-angular-v2/default/rxjs-operators.ts
samples/client/petstore/typescript-angular-v2/npm/rxjs-operators.ts
samples/client/petstore/typescript-angular-v2/with-interfaces/rxjs-operators.ts
samples/client/petstore/typescript-angular-v4.3/npm/rxjs-operators.ts
samples/client/petstore/typescript-angular-v4/npm/rxjs-operators.ts

fix issue 7048
[7048](https://github.com/swagger-api/swagger-codegen/issues/7048)
@TiFu  @taxpon  @sebastianhaas  @kenisteward  @Vrolijkx

fix issue 7048

---

modules/swagger-codegen/src/main/resources/php/api.mustache

[PHP] Update code style

---

pom.xml
samples/client/petstore/java/resttemplate-withXml/src/main/java/io/swagger/client/api/FakeApi.java
samples/client/petstore/java/resttemplate/src/main/java/io/swagger/client/api/FakeApi.java
samples/client/petstore/java/retrofit2rx/pom.xml
samples/client/petstore/java/retrofit2rx2/pom.xml
samples/client/petstore/python/docs/FakeApi.md

Swagger Core: 1.5.16 => 1.5.17
Swagger Parser: 1.0.32 => 1.0.33

Upgrade Swagger parser, core to the latest version

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java
pom.xml
samples/client/petstore/java/resttemplate-withXml/src/main/java/io/swagger/client/api/FakeApi.java
samples/client/petstore/java/resttemplate/src/main/java/io/swagger/client/api/FakeApi.java
samples/client/petstore/java/retrofit2rx/pom.xml
samples/client/petstore/java/retrofit2rx2/pom.xml
samples/client/petstore/python/docs/FakeApi.md

Currently, we only retrieve "Contact" email. This PR will include name and URL as well.
Ref: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#contact-object

Add "Contact" name, URL

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AspNetCoreServerCodegen.java
modules/swagger-codegen/src/main/resources/aspnetcore/Startup.mustache
modules/swagger-codegen/src/main/resources/aspnetcore/wwwroot/swagger-original.mustache
samples/server/petstore/aspnetcore/src/IO.Swagger/Startup.cs
samples/server/petstore/aspnetcore/src/IO.Swagger/wwwroot/swagger-original.json

Resolving issue #7159 
Adding the original swagger to the package.
@wing328 please review!
I followed your guidance..
Thanks.

[AspnetCore Server] Added Original swagger

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AspNetCoreServerCodegen.java
modules/swagger-codegen/src/main/resources/aspnetcore/Filters/BasePathFilter.mustache
modules/swagger-codegen/src/main/resources/aspnetcore/Filters/GeneratePathParamsValidationFilter.mustache
modules/swagger-codegen/src/main/resources/aspnetcore/Startup.mustache
modules/swagger-codegen/src/main/resources/aspnetcore/validateModel.mustache
samples/server/petstore/aspnetcore/src/IO.Swagger/Attributes/ValidateModelStateAttribute.cs
samples/server/petstore/aspnetcore/src/IO.Swagger/Filters/BasePathFilter.cs
samples/server/petstore/aspnetcore/src/IO.Swagger/Filters/GeneratePathParamsValidationFilter.cs
samples/server/petstore/aspnetcore/src/IO.Swagger/Startup.cs

@jimschubert @wing328 
As a follow-up to #7120..
Now the [Required], [Range].. attributes are not just rendered in Swagger, but actually VALIDATED as well!
Building on-top of #5257 from @mandrean.

Added actual VALIDATION of the Action parameters

---

modules/swagger-codegen/src/main/resources/JavaSpring/libraries/spring-boot/pom.mustache
samples/server/petstore/springboot-beanvalidation/pom.xml
samples/server/petstore/springboot-delegate-j8/pom.xml
samples/server/petstore/springboot-delegate/pom.xml
samples/server/petstore/springboot-implicitHeaders/pom.xml
samples/server/petstore/springboot-useoptional/pom.xml
samples/server/petstore/springboot/pom.xml

Issue 7151 2.3.0

---

modules/swagger-codegen/src/main/resources/JavaSpring/libraries/spring-boot/pom.mustache
samples/server/petstore/springboot-beanvalidation/pom.xml
samples/server/petstore/springboot-delegate-j8/pom.xml
samples/server/petstore/springboot-delegate/pom.xml
samples/server/petstore/springboot-implicitHeaders/pom.xml
samples/server/petstore/springboot-useoptional/pom.xml
samples/server/petstore/springboot/pom.xml

[Spring] Fix starting springboot server from IDE

---

README.md

Add our company to list

---

README.md

Adding Prokarma to the name of the company using swagger

added prokarma to the name of the company

---

modules/swagger-codegen/src/main/resources/go/api.mustache
pom.xml.circleci
samples/client/petstore/go/go-petstore/pet_api.go

rename local variable "file" to "localVarFile"
cc @antihax

[Go] rename local variable "file" to "localVarFile"

---

README.md

Hi @wing328 
Hope this was what you had in mind.
- [YES] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [NO] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [YES] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [YES] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the …

Video "Building an API with Swagger"

---

README.md

Peatio is an opensource project and all API client are generated using codegen.

Adding Peatio opensource as reference project

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java

Fix "removeOperationIdPrefix" in additional properties

Fix "removeOperationIdPrefix" in additional properties

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractEiffelCodegen.java

Replaced \t with spaces

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaJAXRSServerCodegen.java

[7389] Generate service with -l jaxrs-spec fails

---

modules/swagger-codegen/src/main/resources/scala/gitignore.mustache
modules/swagger-codegen/src/main/resources/scalatra/gitignore.mustache
samples/client/petstore/scala/.gitignore
samples/server/petstore/scalatra/.gitignore

.idea
*.iml
Added Intelli J ignore
Related PR
https://github.com/swagger-api/swagger-codegen/pull/7402
Please review
@clasnake  @jimschubert @shijinkui

[Scala][Scalatra]Added Intelli J ignore

---

README.md
modules/swagger-codegen-cli/pom.xml
modules/swagger-codegen-maven-plugin/pom.xml
modules/swagger-codegen/pom.xml
modules/swagger-generator/pom.xml
pom.xml
pom.xml.bash
pom.xml.circleci
pom.xml.shippable

prepare release 3.0.0-rc0

---

pom.xml.circleci
samples/server/petstore/java-play-framework-api-package-override/pom.xml
samples/server/petstore/java-play-framework-controller-only/pom.xml
samples/server/petstore/java-play-framework-fake-endpoints/pom.xml
samples/server/petstore/java-play-framework-no-bean-validation/pom.xml
samples/server/petstore/java-play-framework-no-exception-handling/pom.xml
samples/server/petstore/java-play-framework-no-interface/pom.xml
samples/server/petstore/java-play-framework-no-swagger-ui/pom.xml
samples/server/petstore/java-play-framework-no-wrap-calls/pom.xml

Add Play server samples to be covered by CircleCI (JDK8)

Add Play server samples to CircleCI

---

README.md

@viclovsky has been added to template creators

---

modules/swagger-codegen/src/main/resources/Ada/config.gpr
samples/client/petstore/ada/config.gpr

- remove trailing spaces in Ada template
cc @stcarrez

[Ada] remove trailing spaces in Ada template

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java

fixed path for template files on Windows OS.

---

modules/swagger-codegen/src/main/resources/Java/JSON.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/rest-assured/build.gradle.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/rest-assured/build.sbt.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/rest-assured/pom.mustache
samples/client/petstore/java/rest-assured/build.gradle
samples/client/petstore/java/rest-assured/build.sbt
samples/client/petstore/java/rest-assured/pom.xml
samples/client/petstore/java/rest-assured/src/main/java/io/swagger/client/JSON.java

Enhancements (https://github.com/swagger-api/swagger-codegen/pull/7473) were removed from https://github.com/swagger-api/swagger-codegen/pull/7492 so we're adding it back via this PR.

[Java] Add back byte array enhancement

---

modules/swagger-codegen/src/main/resources/lua/luarocks.mustache
samples/client/petstore/lua/petstore-1.0.0-1.rockspec

For https://github.com/swagger-api/swagger-codegen/pull/7475#pullrequestreview-93494048
cc @daurnimator

[Lua] Fix Rockpec

---

README.md

Add restunited to the list of companies

---

README.md

The eBook is hard to find as it's in the presentation section (bottom)

Add a link to eBook on top

---

README.md

Add SessionM to list of companies using swagger.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/config/CodegenConfigurator.java

Set options on parser to generate nested objects on model for codegen generation.

Issue #7523: set “resolve” and “flatten” options on parser to fix issue.

---

modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/cmd/Generate.java
modules/swagger-codegen-cli/src/main/resources/oas3.yaml
modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConfig.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConstants.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/config/CodegenConfigurator.java
modules/swagger-generator/src/main/java/io/swagger/generator/model/Options.java
modules/swagger-generator/src/main/java/io/swagger/generator/util/GeneratorUtil.java
modules/swagger-generator/src/main/resources/openapi.yaml

Issue 7634

---

README.md

Added [FormAPI](https://formapi.io) to the list

Added FormAPI to the list of companies that are using swagger-codegen

---

modules/swagger-codegen/src/main/resources/dart/auth/authentication.mustache

Remove tab

---

modules/swagger-codegen/src/main/resources/akka-scala/enumsSerializers.mustache

This PR addresses this issue https://github.com/swagger-api/swagger-codegen/issues/7328

Remove unused dep when model package is empty

---

README.md

After [several contribution](https://github.com/swagger-api/swagger-codegen/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3AMartinDelille+), I'll be happy to integrate the Qt technical commitee!
Ping @wing328 @ravinikam @stkrwork @fvarose

Candidature to integrate Qt technical commitee

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwaggerYamlGenerator.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/swaggeryaml/SwaggerYamlGeneratorTest.java
modules/swagger-codegen/src/test/resources/2_0/long_description_issue_7839.json

added config to yaml mapper to minimize long text.

---

.travis.yml.ios

Update to newer version of Ruby in Travis config file

---

modules/swagger-codegen-maven-plugin/examples/java-client.xml

updated version number of swagger codegen to current stable

Updated version number

---

README.md

Resubmitted from https://github.com/swagger-api/swagger-codegen/pull/7667 targeted at `3.0.0`

Fix help command in example

---

pom.xml
pom.xml.bash
pom.xml.circleci
pom.xml.shippable

use recently release swagger-core 2.0.0 version

Swagger core updating

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java

Issue 7721

---

modules/swagger-codegen/src/main/resources/Javascript/es6/ApiClient.mustache

[issue 7972](https://github.com/swagger-api/swagger-codegen/issues/7972)

change parseDate in es6/APIClient

---

modules/swagger-codegen/src/main/resources/kotlin-client/model.mustache

Add support for typealiases in Kotlin client.
Previously, aliases would not be correctly handled, resulting in empty data classes.
Technical committee member: @jimschubert

Add support for typealiases in Kotlin client

---

.travis.yml.bash
pom.xml

- [ x] Ran txhe shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
updated swagger parser version dependency.

updated parser to latest release version.

---

README.md
modules/swagger-codegen-cli/pom.xml
modules/swagger-codegen-maven-plugin/pom.xml
modules/swagger-codegen/pom.xml
modules/swagger-generator/pom.xml
pom.xml
pom.xml.bash
pom.xml.circleci
pom.xml.shippable

bump project version and swagger core/parser dependency versions.

---

README.md
modules/swagger-codegen-cli/pom.xml
modules/swagger-codegen-maven-plugin/pom.xml
modules/swagger-codegen/pom.xml
modules/swagger-generator/pom.xml
pom.xml
pom.xml.bash
pom.xml.circleci
pom.xml.shippable

bump to snapshot version

---

modules/swagger-codegen/src/main/resources/htmlDocs2/index.mustache

Fix issue #5780

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java

fixed path for config dir on windows OS.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConstants.java

Added constant to bearer authentication.

---

circle.yml

update circle config to fix CI build failure by declaring sbt version

setup sbt in circle config

---

modules/swagger-codegen-maven-plugin/examples/java-client.xml

refs #3261 - fixes maven plugin example jersey version

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java

support extensions x-codgen-ignore and x-import-mapping in models

Add support for x-codegen-ignore and x-import-mapping extensions

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenConstants.java

added constants for http methods.

---

modules/swagger-codegen/src/test/resources/3_0_0/petstore-with-fake-endpoints-models-for-testing.yaml
modules/swagger-codegen/src/test/resources/3_0_0/petstore.yaml

fixed test definition for codegen v3.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenConfig.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/DefaultGenerator.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/templates/HandlebarTemplateEngine.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/templates/MustacheTemplateEngine.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/templates/TemplateEngine.java

allow capability to generate templates with mustache engine.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenModel.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenObject.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenOperation.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenParameter.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenProperty.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenResponse.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenSecurity.java

added methods to match mustache templates.

---

README.md
modules/swagger-codegen-cli/pom.xml
modules/swagger-codegen-maven-plugin/pom.xml
modules/swagger-codegen/pom.xml
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenOperation.java
modules/swagger-generator/pom.xml
pom.docker.xml
pom.xml
pom.xml.bash
pom.xml.shippable

Prepare release 3.0.0

---

README.md
modules/swagger-codegen-cli/pom.xml
modules/swagger-codegen-maven-plugin/pom.xml
modules/swagger-codegen/pom.xml
modules/swagger-generator/pom.xml
pom.docker.xml
pom.xml
pom.xml.bash
pom.xml.shippable

Bump to snapshot

---

modules/swagger-codegen/src/test/java/io/swagger/codegen/ruby/RubyClientCodegenTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/swaggeryaml/SwaggerYamlGeneratorTest.java

remove system property to avoid affect others generator tests.

---

modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/v3/cli/cmd/Generate.java
modules/swagger-codegen-cli/src/main/resources/oas3.yaml
modules/swagger-codegen-cli/src/test/java/io/swagger/codegen/v3/cli/cmd/GenerateTest.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenConstants.java

added option to choose template engine.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/templates/HandlebarTemplateEngine.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/templates/MustacheTemplateEngine.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/templates/TemplateEngine.java

added capability to identify template engine names.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwaggerGenerator.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwaggerYamlGenerator.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/ruby/RubyClientCodegenTest.java

refactor changes related to #8712 in order to solve maven build fail.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/templates/HandlebarTemplateEngine.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/templates/MustacheTemplateEngine.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/templates/TemplateEngine.java

fixed typo.

---

modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/v3/cli/cmd/Generate.java

set handlebars as default template engine.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenOperation.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenParameter.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SpringCodegen.java
modules/swagger-codegen/src/main/resources/JavaSpring/libraries/spring-boot/api_test.mustache
modules/swagger-codegen/src/main/resources/JavaSpring/libraries/spring-boot/pom.mustache
modules/swagger-codegen/src/main/resources/JavaSpring/libraries/spring-mvc/api_test.mustache
modules/swagger-codegen/src/main/resources/JavaSpring/libraries/spring-mvc/pom.mustache

with these changes we can verify that endpoints are reached on output code.

added api test files templates for springboot and spring mvc.

---

modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/v3/cli/cmd/Meta.java
samples/meta-codegen/README.md
samples/meta-codegen/pom.xml
samples/meta-codegen/src/main/java/com/my/company/codegen/MyclientcodegenGenerator.java
samples/meta-codegen/src/main/resources/META-INF/services/io.swagger.codegen.v3.CodegenConfig

refs #8784 - fix meta generator

refs #8784 - fix meta generator

---

README.md

- [ X] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ N/A ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ x ] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [ N/A ] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a …

Added Windows Docker Run instruction

---

modules/swagger-generator/Dockerfile
modules/swagger-generator/docker/ROOT.xml
modules/swagger-generator/pom.xml

fix #8820 - add external classpath to docker image jetty webapp

ref #8820 - add external classpath to docker image jetty webapp

---

modules/swagger-codegen/src/main/resources/kotlin-client/api.mustache
modules/swagger-codegen/src/main/resources/kotlin-client/infrastructure/ApiClient.kt.mustache
samples/client/petstore/kotlin/README.md
samples/client/petstore/kotlin/docs/Amount.md
samples/client/petstore/kotlin/docs/Currency.md
samples/client/petstore/kotlin/docs/PetApi.md
samples/client/petstore/kotlin/docs/StoreApi.md
samples/client/petstore/kotlin/docs/UserApi.md
samples/client/petstore/kotlin/settings.gradle
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/apis/PetApi.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/apis/StoreApi.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/apis/UserApi.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/models/Amount.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/models/ApiResponse.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/models/Category.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/models/Currency.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/models/Order.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/models/Pet.kt

Added logic to handle files in FormDataMediaType for Kotlin, so that files are uploaded, not just strings. @HugoMario

Frozenstep kotlin fixing file uploading

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenConfig.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/DefaultGenerator.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/config/CodegenConfigurator.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/utils/URLPathUtil.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/v3/utils/URLPathUtilTest.java

fixed relative url issue.

---

modules/swagger-codegen/src/main/resources/JavaSpring/beanValidationCore.mustache

handled extension for pattern message.

---

README.md

Update company list users

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/DefaultGenerator.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/v3/service/GeneratorServiceTest.java
modules/swagger-codegen/src/test/resources/3_0_0/noModel.yaml

related templates updates in https://github.com/swagger-api/swagger-codegen-generators/pull/352

fixes imports when spec contains no schema

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/DefaultGeneratorTest.java
modules/swagger-codegen/src/test/resources/2_0/issue-9132.yaml

Handling UntypedProperty to avoid UNKNOWN_ERROR at string sanitize, when MapProperty`s Property is not a schema, but a boolean: true. refs issue #9132

ref #9132 - Handle UntypedProperty

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenSecurity.java

added bearer checks to be used in templates.

---

README.md

Adding Jenkins Build Status badges for master branch; default and Java 7.

Add Jenkins Build Status Badges

---

modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/v3/cli/cmd/Generate.java
modules/swagger-codegen-cli/src/main/resources/oas3.yaml
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenConstants.java

added a new option on CLI to disable json/xml examples.

added option to disable examples.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngularClientCodegen.java

fixed incorrect model name prefix and suffix issue

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java

fixed examples over quotes

---

pom.docker.xml
pom.xml
pom.xml.bash
pom.xml.shippable

bump parser to 2.0.15-SNAPSHOT version

bump parser to next snapshot

---

modules/swagger-codegen/pom.xml
pom.docker.xml
pom.xml
pom.xml.bash
pom.xml.shippable

refs #9732 - increase handlebars version

---

modules/swagger-codegen/pom.xml
pom.xml

Increase handlebars version to have conditional helpers (https://gith…ub.com/jknack/handlebars.java/issues/627) They are needs in swagger-codegen-generators
fix #9732

issue-9732

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/utils/URLPathUtil.java

fixed base path exception on URL parsing

---

modules/swagger-codegen/src/main/resources/htmlDocs/index.mustache
modules/swagger-codegen/src/main/resources/htmlDocs2/js_jsonschemaview.mustache

show example on html and html2 generators

---

pom.docker.xml
pom.xml
pom.xml.bash
pom.xml.shippable

updated swagger parser dependency version

updated pom files

---

modules/swagger-codegen-maven-plugin/pom.xml

updated maven plugin to 3.6.0 version

bump up maven plugin version

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Swift4Codegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Swift5Codegen.java
modules/swagger-codegen/src/main/resources/swift4/modelObject.mustache
modules/swagger-codegen/src/main/resources/swift5/modelObject.mustache

added option to use classes as models

---

README.md

3.0.0-Fixed Badges

---

README.md

Updated more badges

---

modules/swagger-codegen/src/main/resources/typescript-angular/index.mustache

import models only when they exist

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/resources/Java/pojo.mustache

skip discriminator property assignment for enums.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenModel.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/ISchemaHandler.java

Composed refactoring

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenSchema.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/DefaultGenerator.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/ISchemaHandler.java

refactored composed schema method generation

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenConfig.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/DefaultGenerator.java

add schema handle method on codegen config interface.

---

modules/swagger-codegen/src/main/resources/go/api.mustache

Ffddorf issue 7311

---

pom.docker.xml
pom.xml
pom.xml.bash
pom.xml.shippable

update swagger parser versions

update swagger parser versions

---

modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/cmd/Generate.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java

avoid creation of classes from primitive types models

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/DefaultGenerator.java

allow skip alias for models in csharp generator

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java

fixed model missmatch issue on models name with special chars

Model missmatch name fix

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/config/CodegenConfigurator.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/service/GenerationRequest.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/service/GeneratorUtil.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/service/Options.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/v3/service/GeneratorServiceTest.java
modules/swagger-codegen/src/test/resources/3_0_0/FlattenComposedInlineSchema.yaml

Flatten inline composed schema

Flatten inline composed schema

---

modules/swagger-codegen/pom.xml
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java
pom.xml
pom.xml.bash
pom.xml.circleci
pom.xml.ios
pom.xml.jenkins
pom.xml.travis

Issue 8148

---

README.md

Added Norwegian Air Shuttle to companies list

---

modules/swagger-codegen/src/test/java/io/swagger/codegen/v3/service/GeneratorServiceTest.java

Tests for notNullJacksonAnnotation in 3.0.0
Refs- #6844
Depends on https://github.com/swagger-api/swagger-codegen-generators/pull/690

Tests for notNullJacksonAnnotation in 3.0.0

---

modules/swagger-codegen/src/test/java/io/swagger/codegen/v3/service/GeneratorServiceTest.java
modules/swagger-codegen/src/test/resources/3_0_0/swos196.yaml

test for invalid model name in html2 genetator
Depends on https://github.com/swagger-api/swagger-codegen-generators/pull/698

test for swos_196

---

README.md

Added Trifork as company using swagger-codegen

---

modules/swagger-codegen-maven-plugin/src/main/java/io/swagger/codegen/v3/maven/plugin/CodeGenMojo.java

applies same fix of #10329 to 3.0.0

refs #6260 - Fix #6260 on 3.0.0 by preventing parallelism

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/AbstractGenerator.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenConfig.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/templates/HandlebarTemplateEngine.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/templates/MustacheTemplateEngine.java

override specific templates

---

modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/api.mustache

Fixes #10351

---

modules/swagger-codegen/src/main/resources/csharp-dotnet2/ApiClient.mustache

fixed calls in templates

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/InlineModelResolver.java

flatten composed property to fix generic type issue

---

modules/swagger-codegen-cli/pom.xml
modules/swagger-codegen-maven-plugin/pom.xml
modules/swagger-codegen/pom.xml
modules/swagger-generator/pom.xml
pom.xml
pom.xml.bash
pom.xml.circleci
pom.xml.circleci.java7
pom.xml.ios
pom.xml.jenkins
pom.xml.jenkins.java7
pom.xml.travis

bump codegen to next version

---

modules/swagger-codegen-cli/pom.xml
modules/swagger-codegen-maven-plugin/pom.xml
modules/swagger-codegen/pom.xml
modules/swagger-generator/pom.xml
modules/swagger-generator/src/main/resources/openapi.yaml
pom.docker.xml
pom.xml
pom.xml.bash
pom.xml.shippable

bumping to 3.0.22-SNAPSHOT version.

bump codegen v3 to 3.0.22-SNAPSHOT version

---

modules/swagger-codegen/src/main/resources/aspnetcore/Solution.mustache

fixed solution template on aspnetcore

---

modules/swagger-codegen/src/main/resources/JavaJaxRS/beanValidation.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf-cdi/beanValidation.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/model.mustache

added @Valid annotation on bean validation template for java jaxs

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java

add info object extensions to additional property map

---

modules/swagger-codegen/src/main/resources/Java/modelInnerEnum.mustache

addded missed changes for #10546

updated model inner enum template for java generator

---

modules/swagger-codegen/src/main/resources/JavaSpring/api.mustache

added missed validated annotation.

---

.github/workflows/test-framework-java.yml

updated java workflow action to use buildCommands

added buildCommand input

---

.github/workflows/test-framework-php.yml
.github/workflows/test-framework-v2-php.yml

updated php workflows to fix errors on build

changed php action step

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenConstants.java

added kebab case on model property  naming type enumeration

---

modules/swagger-codegen/src/main/resources/aspnetcore/model.mustache

added missed data annotation on model properties

---

.github/workflows/test-framework-v2-ts-angular-v10.yml
.github/workflows/test-framework-v2-ts-angular-v11.yml
.github/workflows/test-framework-v2-ts-angular-v12.yml
.github/workflows/test-framework-v2-ts-angular-v4.yml
.github/workflows/test-framework-v2-ts-angular-v4_3.yml
.github/workflows/test-framework-v2-ts-angular-v5.yml
.github/workflows/test-framework-v2-ts-angular-v6.yml
.github/workflows/test-framework-v2-ts-angular-v7.yml
.github/workflows/test-framework-v2-ts-angular-v8.yml
.github/workflows/test-framework-v2-ts-angular-v9.yml
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngularClientCodegen.java
modules/swagger-codegen/src/main/resources/typescript-angular/package.mustache

tweaked typescript angular generator to work with angular greater versions

Issue 10040

---

modules/swagger-codegen/src/main/resources/php/api.mustache
samples/client/petstore-security-test/php/SwaggerClient-php/lib/Api/FakeApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/AnotherFakeApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/DefaultApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/FakeApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/FakeClassnameTags123Api.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/Fake_classname_tags123Api.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/PetApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/StoreApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/UserApi.php

closes https://github.com/swagger-api/swagger-codegen/pull/11086

Comune fi master

---

modules/swagger-codegen/src/test/java/io/swagger/codegen/v3/service/GeneratorServiceTest.java

tests for PR https://github.com/swagger-api/swagger-codegen/pull/11175

tests for PHP generator gitRepoBaseURL Option, in readme

---

modules/swagger-codegen-cli/pom.xml
modules/swagger-codegen-maven-plugin/pom.xml
modules/swagger-codegen/pom.xml
modules/swagger-generator/pom.xml
pom.xml
pom.xml.jenkins

Reverts swagger-api/swagger-codegen#11265

Revert "bump snapshot 2.4.25-SNAPSHOT"

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java
modules/swagger-codegen/src/main/resources/php/README.mustache
modules/swagger-codegen/src/main/resources/php/git_push.sh.mustache
modules/swagger-codegen/src/test/java/io/swagger/codegen/DefaultGeneratorTest.java

related to https://github.com/swagger-api/swagger-codegen/pull/11170

allow full url in option

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/config/CodegenConfigurator.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/v3/service/GeneratorServiceTest.java

allow full url in php option

---

pom.xml
pom.xml.jenkins

As dicussed via security mailing list, here is version bump of slf4j.
@ponelat

bump slf4j version to fix possible vulnerability

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/templates/CodegenTemplateLoader.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/templates/HandlebarTemplateEngine.java

Fixed custom templates issue

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FlaskConnexionCodegen.java
modules/swagger-codegen/src/main/resources/flaskConnexion/__main__.mustache
modules/swagger-codegen/src/main/resources/flaskConnexion/authorization_controller.mustache
modules/swagger-codegen/src/main/resources/flaskConnexion/model.mustache
modules/swagger-codegen/src/main/resources/flaskConnexion/requirements.mustache
modules/swagger-codegen/src/main/resources/flaskConnexion/setup.mustache
modules/swagger-codegen/src/main/resources/flaskConnexion/type_util.mustache
modules/swagger-codegen/src/main/resources/flaskConnexion/util.mustache
pom.xml.jenkins
samples/client/petstore/java/jersey2/src/test/java/io/swagger/client/JSONTest.java
samples/server/petstore/java-pkmst/pom.xml

fixes #10523 issue on codegen v2

run swagger-ui along with flask output code

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java

fixes https://github.com/swagger-api/swagger-codegen/issues/8780

changed pattern to work with acronyms in underscore conversion

---

modules/swagger-generator/Dockerfile
modules/swagger-generator/Dockerfile_root

Install gzip in swagger-generator Dockerfile

---

modules/swagger-codegen-cli/pom.xml
modules/swagger-codegen-maven-plugin/pom.xml
modules/swagger-codegen/pom.xml
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/DefaultGenerator.java
modules/swagger-generator/pom.xml
modules/swagger-generator/src/main/resources/openapi.yaml
pom.docker.xml
pom.java11.xml
pom.java8.xml
pom.xml
samples/meta-codegen/pom.xml

* [bump next snapshot 3.0.50-SNAPSHOT](https://github.com/swagger-api/swagger-codegen/commit/4bf82cbb205078e3cde4ef390bd889748970575a)
* [escape quotes in paths](https://github.com/swagger-api/swagger-codegen/commit/404069995bddab5517873f95bceb25f34b2aa610)
addresses code injections in paths values

escape quotes in paths

---

README.md
modules/swagger-codegen-cli/pom.xml
modules/swagger-codegen-maven-plugin/pom.xml
modules/swagger-codegen/pom.xml
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/BashClientCodegen.java
modules/swagger-generator/pom.xml
modules/swagger-generator/pom.xml.jenkins
pom.xml
pom.xml.jenkins

* [implement escapeQuotationMark in bash generator](https://github.com/swagger-api/swagger-codegen/commit/31ae302314aac3979d9a6da38a7cf6a9efc6dca2)
* [update dependencies](https://github.com/swagger-api/swagger-codegen/commit/d88d3f365c3cb2244d499bc32d084b501315ab53)
* [prepare release 2.4.36](https://github.com/swagger-api/swagger-codegen/commit/6a195442759116a778e76cd8ff7bdac4ed21cce0)

implement escapeQuotationMark in bash generator - update deps

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenModel.java

Osztos a feature/java interface discriminator helper

---

README.md
modules/swagger-codegen-cli/pom.xml
modules/swagger-codegen-maven-plugin/pom.xml
modules/swagger-codegen/pom.xml
modules/swagger-codegen/src/test/resources/integrationtests/csharp/general/enum-support-expected/src/IO.Swagger/Model/MyClassWithOptionalInlineEnum.cs
modules/swagger-codegen/src/test/resources/integrationtests/csharp/general/enum-support-expected/src/IO.Swagger/Model/MyClassWithRequiredInlineEnum.cs
modules/swagger-generator/pom.xml
pom.xml

* [update deps](https://github.com/swagger-api/swagger-codegen/commit/c52c3f8e04086104ffaa83229aba15bc4bc80031)
* [prepare-release-2.4.38](https://github.com/swagger-api/swagger-codegen/commit/3d2049816694e08d4977363b23650111c8ad8f34)

prepare release 2.4.38

---

README.md
modules/swagger-codegen-cli/pom.xml
modules/swagger-codegen-maven-plugin/pom.xml
modules/swagger-codegen/pom.xml
modules/swagger-codegen/src/test/resources/integrationtests/csharp/general/enum-support-expected/src/IO.Swagger/Model/MyClassWithOptionalInlineEnum.cs
modules/swagger-codegen/src/test/resources/integrationtests/csharp/general/enum-support-expected/src/IO.Swagger/Model/MyClassWithRequiredInlineEnum.cs
modules/swagger-generator/pom.xml
pom.xml

downgrade jmustache to 1.15 and prepare release 2.4.39

prepare-release-2.4.39

---

.github/workflows/codeql.yml

Add CodeQl workflow

---

docs/docker.md

chore(docs): typo fix in docker md
