swagger-api/swagger-codegen

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/ApiClient.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/api.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/build.gradle.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/build.sbt.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/pom.mustache
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/JavaClientOptionsProvider.java

Reverts swagger-api/swagger-codegen#4708

Revert "rx2 support"

---

Dockerfile

Signed-off-by: weiyang <weiyang.ones@gmail.com>
Reduse image size from 815M to 374M.

[dockerfile] Replace 'maven:3.3-jdk-7' with 'maven:3-jdk-7-alpine'

---

modules/swagger-codegen/src/main/resources/Java/libraries/feign/ApiClient.mustache
samples/client/petstore/java/feign/src/main/java/io/swagger/client/ApiClient.java

String comparison with equals, to avoid object reference comparison.
Run manually mvn clean package successfully.

[Java-Feign] Fixed String comparison using equals instead of == operator

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java

Before this change if a model had a property of type=string and
format=uuid, it would be generated as a Java String.
Now, it generates the property as java.util.UUID.

[Java][Issue #1806] generate using java.util.UUID for UUIDs

---

modules/swagger-codegen/src/main/resources/typescript-angular2/gitignore

ignore dist folder
Adding the dist folder to .gitignore so that it isn't packed by `npm package`.

Update gitignore to ignore dist folder

---

modules/swagger-codegen/src/main/resources/JavaInflector/pojo.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf-cdi/pojo.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/pojo.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/resteasy/pojo.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/spec/pojo.mustache
modules/swagger-codegen/src/main/resources/undertow/pojo.mustache

This commit fixes the Java problem related by this defect #2064.
If the swagger model contains a class named 'Object' some mustache templates
will generate non compiling **Java** code.

Fix issue when the swagger model contains an 'Object' class

---

modules/swagger-codegen/src/main/resources/Java/libraries/feign/ApiClient.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit/ApiClient.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/ApiClient.mustache
samples/client/petstore/java/feign/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/retrofit/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/ApiClient.java

To clean up trailing whitespace in Java API clients.

[Java] remove trailing whitespaces in Java API client

---

modules/swagger-codegen/src/main/resources/scala/apiInvoker.mustache
samples/client/petstore/scala/src/main/scala/io/swagger/client/ApiInvoker.scala

Add an escape method for handling UUIDs in generated scala client code.

Ensure that `ApiInvoker.scala` can support `UUID` types

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenResponse.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/resources/htmlDocs2/index.mustache
modules/swagger-codegen/src/test/resources/2_0/responseHeaderTest.yaml
samples/html2/index.html

Fixes #1940 . The html2 generator now displays response header. As the petstore example does not use header values in responses, I have added a new test spec responseHeaderTest.yaml under modules/swagger-codegen/src/test/resources/2_0 to test the new feature.

[HTML2] Fix for #1940 - Show response headers

---

modules/swagger-codegen/src/main/resources/php/ApiException.mustache
samples/client/petstore-security-test/php/SwaggerClient-php/lib/ApiException.php
samples/client/petstore/php/SwaggerClient-php/lib/ApiException.php
samples/client/petstore/php/test.php

Hi. This PR fixes minor errors in `test.php` file which where caused by different types returned than expected. Preview:
```
/usr/bin/php /home/bbialek/projects/swagger-codegen/samples/client/petstore/php/test.php
PHP SDK (Swagger\Client) Debug Report:
OS: Linux bbialek-HP-EliteDesk-800-G1-SFF 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64
PHP Version: 7.0.13-0ubuntu0.16.04.1
OpenAPI Spec Version: 1.0.0
Temp Folder Path: /tmp
PHP Notice:  Array to string conversion in /home/bbialek/projects/swagger-codegen/samples/client/petstore/php/test.php on line 58
PHP Stack trace:
PHP   1. {main}() /home/bbialek/projects/swagger-codegen/samples/client/petstore/php/test.php:0
PHP Catchable fatal error:  Object of class stdClass could not be converted to string in …
```

[PHP] fixed ApiException's methods return types

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/BashClientCodegen.java
modules/swagger-codegen/src/main/resources/bash/Dockerfile.mustache
modules/swagger-codegen/src/main/resources/bash/README.md
modules/swagger-codegen/src/main/resources/bash/client.mustache
samples/client/petstore/bash/Dockerfile
samples/client/petstore/bash/_petstore-cli
samples/client/petstore/bash/petstore-cli
samples/client/petstore/bash/petstore-cli.bash-completion
samples/client/petstore/bash/tests/petstore_test.sh

@wing328 
I've added some further minor bugfixes to the Bash generator:
* Fixed passing of default cURL options from config options to generated Bash client
* Fixed generation of JSON body from command line arguments
* Added some more Bats test cases
* Updated README file in the Bash codegen module to use swagger-api default build instructions
* Fixed generated Dockerfile with proper access rights to client Bash script

[Bash] Bugfix default curl options fix

---

modules/swagger-codegen/pom.xml
modules/swagger-codegen/src/main/java/io/swagger/codegen/examples/XmlExampleGenerator.java

Reduce maven dependencies for swagger-codegen artefact, to make it easier to use it outside of a maven-plugin context.
See http://mvnrepository.com/artifact/io.swagger/swagger-codegen/2.2.1
`org.apache.felix:maven-bundle-plugin` and `org.apache.maven:maven-plugin-tools-api` should be obsolete.

Remove maven-api dependencies on swagger-codegen module

---

modules/swagger-codegen/src/main/resources/Javascript/ApiClient.mustache
samples/client/petstore/javascript/src/ApiClient.js

Superagent doesn't encode form parameters properly. For example it doesn't encode objects which contain array. The following is a failed test case:
```
var my_opts = {
'storyId': 65441,
'id': [56, 352]
};
```

Encode form paramerers properly

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SilexServerCodegen.java
modules/swagger-codegen/src/main/resources/silex/index.mustache
samples/server/petstore/silex/SwaggerServer/index.php

Use original path name for path variable naming to resolve https://github.com/swagger-api/swagger-codegen/issues/4257

[PHP][Silex] use original path name for path variable naming

---

modules/swagger-codegen/src/main/resources/JavaJaxRS/libraries/jersey1/pom.mustache
samples/server/petstore/jaxrs/jersey1/pom.xml

Add back dependencies related to jackson.

[JAX-RS][Jersey1] Fix issue in pom dependencies

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/config/CodegenConfigurator.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/config/CodegenConfiguratorTest.java

Makes the `CodegenConfigurator` implement `Serializable`. This is useful because it allows it to be cached with gradle which speeds up build times by allowing tasks that have already run to be skipped.
Closes #4887

Make the CodegenConfigurator serializable

---

modules/swagger-codegen/src/main/resources/ruby/api_client.mustache
samples/client/petstore-security-test/ruby/spec/api_client_spec.rb
samples/client/petstore/ruby/lib/petstore/api/fake_api.rb
samples/client/petstore/ruby/lib/petstore/api/store_api.rb
samples/client/petstore/ruby/lib/petstore/api_client.rb

Fix ruby-client work with modern content types, like application/api.vnd+json

[Ruby] Can only use content-type application/json with ruby-client #4867

---

modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/server/pom.mustache
samples/server/petstore/jaxrs-cxf/pom.xml

fix dependencies for swagger-core 1.5.12 for CXF server see #4924

[Jaxrs-cxf] Fix compile errors after update of swagger-core / add jackson dependencies to pom #4924

---

samples/server/petstore/scalatra/build.sbt
samples/server/petstore/scalatra/src/main/scala/com/wordnik/client/api/PetApi.scala
samples/server/petstore/scalatra/src/main/scala/com/wordnik/client/api/StoreApi.scala
samples/server/petstore/scalatra/src/main/scala/com/wordnik/client/api/UserApi.scala

→ just bin/scalatra-petstore.sh
This just updates the scalatra samples without any functionality changes.
(This is a part of #4901 split out into a separate PR to see if CI likes it better than the whole thing.)

Update samples for Scalatra after 2.2.2.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaCXFClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaCXFServerCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaJAXRSSpecServerCodegen.java

according to the help message setting dateLibrary to 'legacy' should
make the code generator use java.util.Date.
before this change, when setting dateLibrary to 'legacy' made the
generator use javax.xml.datatype.XMLGregorianCalendar.
now, the generator uses java.util.Date such that the documentation and
behavior are consistent.

[JAXRS-CXF] [bug #4422] use java.util.Date when selecting dateLibrary=legacy

---

modules/swagger-codegen/src/main/resources/scala/model.mustache
samples/client/petstore/scala/src/main/scala/io/swagger/client/model/ApiResponse.scala
samples/client/petstore/scala/src/main/scala/io/swagger/client/model/Category.scala
samples/client/petstore/scala/src/main/scala/io/swagger/client/model/Order.scala
samples/client/petstore/scala/src/main/scala/io/swagger/client/model/Pet.scala
samples/client/petstore/scala/src/main/scala/io/swagger/client/model/Tag.scala
samples/client/petstore/scala/src/main/scala/io/swagger/client/model/User.scala
samples/client/petstore/scala/src/test/scala/PetApiTest.scala
samples/client/petstore/scala/src/test/scala/StoreApiTest.scala
samples/client/petstore/scala/src/test/scala/UserApiTest.scala

Port the option and enum logic from the scala-async template into this one. What is considered a breaking change? This will certainly require anyone generating scala templates to update their code should they regenerate with this template, does that count as breaking? If so I'll recreate the PR onto the right branch.
I know that the plans are to merge the scala & async-scala generators, which project will be considered the main project? I initially tried using the async-scala generator and had some small issues, and switched to this generator just because it was easier to get working initially.

Port the optional/enum template logic from async-scala to the regular scala client

---

modules/swagger-codegen/src/main/resources/Javascript/ApiClient.mustache
samples/client/petstore/javascript/src/ApiClient.js

#4932
Fields in models will be finally parsed to its type. But if the field is null or undefined.
Keep it to null or undefined will benefit the caller for further process.

[JavaScript] Do not parse null and undefined as type.

---

modules/swagger-codegen/src/main/resources/qt5cpp/helpers-body.mustache

While creating a static library from the generated files, compilation issues arose due to QDateTime only being forward declared. Adding the include resolves the issue.
This is my proposed fix for #4833

Added include to qt5cpp to fix library compile

---

bin/windows/swift-petstore-all.bat
bin/windows/swift-petstore-promisekit.bat
bin/windows/swift-petstore-rxswift.bat
bin/windows/swift-petstore.bat
bin/windows/swift3-petstore-all.bat
bin/windows/swift3-petstore-promisekit.bat
bin/windows/swift3-petstore-rxswift.bat
bin/windows/swift3-petstore.bat

Add Windows batch files for swift 2,3 API client generator to generate Petstore samples (for CI tests)

[Swift] add batch files for swift 2,3 to generate petstore samples

---

README.md

#4944 
Changed the direct download link for swagger-codegen-cli jar that is hosted in Maven from the previous releases file to the latest one.

Updated readme with latest maven download URL

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java
samples/client/petstore-security-test/python/petstore_api/api_client.py
samples/client/petstore-security-test/python/requirements.txt

When the model contains a string with a default value with new lines in it, simply quoting generates invalid python code. Using triple quotes for string defaults that contain new lines makes sure the generated code will be a valid python string.
Fixes #4862

[python] Triple quote strings with new lines in default values

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FlaskConnexionCodegen.java

- Fix inconsistency between model name and file name
- add "object" as primitive type to avoid import

[Python][Flask] Fix inconsistency between model name and file name

---

modules/swagger-codegen/src/main/resources/swift3/api.mustache
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift

→ bin/swift3-petstore-all.sh (~~once before the change, see #4911, once again~~ after the change.)
~~This includes the changes of #4911 – after merging those, it should be clearer what actually changed. (Or just have a look at the last two commits.)~~
This fixes a wrong name-mapping of path parameters, as part of solving #4898.
It looks like there is no test case in petstore which actually makes a difference here.
It might be that there actually is no problem (i.e. if parameter names are never modified for Swift3, then `baseName` is the same as `paramName`, so it doesn't matter – though then there might be problems when hitting reserved words), or that it just is not happens with our petstore example.
I need someone who knows about the swift clients to review this – cc @jaz-ah @Edubits. …

Fix (partially) #4898 for swift3

---

modules/swagger-codegen/src/main/resources/python/configuration.mustache
modules/swagger-codegen/src/main/resources/python/rest.mustache
samples/client/petstore-security-test/python/petstore_api/api_client.py
samples/client/petstore-security-test/python/petstore_api/configuration.py
samples/client/petstore-security-test/python/petstore_api/rest.py
samples/client/petstore-security-test/python/requirements.txt
samples/client/petstore/python/petstore_api/configuration.py
samples/client/petstore/python/petstore_api/rest.py

Adds support for proxies in the Python client as discussed in #4639. Simply setting the `proxy` property of the configuration object to the proper URL should be picked up and the client will use `ProxyManager` instead of `PoolManager`. Note that this does not support authenticated proxies.

Add proxy support to fix #4639

---

modules/swagger-codegen/src/main/resources/Javascript/ApiClient.mustache
samples/client/petstore/javascript-promise/src/ApiClient.js
samples/client/petstore/javascript/src/ApiClient.js

Fixes #2442
This adds a `enableCookies` boolean flag to ApiClient. If set to true,
the client will save and return cookies to the server.
This is useful for supporting @SessionScoped beans in Java servers.
Works both in Node.js desktop apps, and in the browser.

Add support for saving/returning cookies

---

modules/swagger-codegen/src/main/resources/php/ObjectSerializer.mustache
modules/swagger-codegen/src/main/resources/php/model.mustache
modules/swagger-codegen/src/main/resources/php/model_enum.mustache
samples/client/petstore/php/SwaggerClient-php/lib/Model/EnumClass.php
samples/client/petstore/php/SwaggerClient-php/lib/Model/OuterEnum.php
samples/client/petstore/php/SwaggerClient-php/lib/ObjectSerializer.php
samples/client/petstore/php/SwaggerClient-php/tests/OuterEnumTest.php

Fix for #4032. 
Example given in referenced ticket where Model has multiple properties is not really causing any errors on current version of SwaggerCodegen. 
This PR fixes serialization failure when we're dealing with Model containing only enum, like this one:
```
definitions:
OuterEnum:
type: "string"
enum:
- "placed"
- "approved"
- "delivered"
```
I added new serialization rule for this case and method `getAllowableEnumValues()` to Enum model class. Enum class is used only to validate parameters and store constants, deserialized result is just a string. Is it valid approach?
To differentiate between enum and non-enum model I am checking if model class has method `getAllowableEnumValues()`. That's dirty solution for now just to validate my idea. It would be nicer to have some …

[PHP] error when deserializing enums #4032

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/StaticHtmlGenerator.java
modules/swagger-codegen/src/main/resources/htmlDocs/index.mustache
samples/html/index.html

Render "default" instead of 0 for response code when Swagger uses "default" (#4982)
Add title for models to TOC and each model's section
Render model description only conditionally.
Remove extraneous Up link
Regenerate samples/html/index.html

Improve HTML output for model titles, default responses

---

.gitignore
.travis.yml
samples/client/petstore/ruby/pom.xml

Cache module directories to improve Travis CI performance

Cache module directories to improve Travis CI performance

---

.github/ISSUE_TEMPLATE.md

This template seems to lead to people wrapping their code with indented code markers, which won't work.
Hopefully not indenting it here helps a bit.
Latest example I've seen was #5009, but there was already a different example some days ago (and I don't succeed to look at every issue).

remove indentation of the comment

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java

To fix https://github.com/swagger-api/swagger-codegen/issues/3678

[Java] Do not map UUID as model in java

---

modules/swagger-codegen/src/main/resources/cpprest/api-source.mustache

Update ApiException to use {{operationId}} variable to correct typo

Update exception message to use operationId

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CppRestClientCodegen.java

number to float or double type mapping was missing, added number to double to accommodate both.

Add missing number type mapping

---

.github/PULL_REQUEST_TEMPLATE.md

See where it says "guildelines" above? That should be "guidelines". Yes, it's really really small but might as well fix it and look a bit nicer! :smile_cat: 
This PR changes no code whatsoever so the Petstore sample did not need updating.

Ultra minor spelling fix

---

modules/swagger-codegen/src/main/resources/swift3/APIs.mustache
modules/swagger-codegen/src/main/resources/swift3/AlamofireImplementations.mustache
modules/swagger-codegen/src/main/resources/swift3/Models.mustache
modules/swagger-codegen/src/main/resources/swift3/api.mustache
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs.swift
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/FakeAPI.swift
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/Fake_classname_tags123API.swift
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/AlamofireImplementations.swift
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/Models.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs/FakeAPI.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs/Fake_classname_tags123API.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/AlamofireImplementations.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/Models.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs/FakeAPI.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs/Fake_classname_tags123API.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/AlamofireImplementations.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/Models.swift

As all other the fields can be null, I think an enumeration field can also be null. The users can decide whether that's a problem. This is to be consistent with previous behaviors.
This was introduced in #4547 (@philippelatulippe)
The real change is only [one line](https://github.com/swagger-api/swagger-codegen/pull/4762/files#diff-940535e66d162a893df844fd9b6b45ffR122), but I cannot help but fix format issues.

[Swift3] null enumerations should not cause failure

---

modules/swagger-codegen/src/main/resources/flash/api.mustache
samples/client/petstore/flash/flash/src/io/swagger/client/api/PetApi.as

→ bin/flash-petstore.sh
This fixes (or hopes to fix) part of #4898 for the `flash` generator.
The problem likely occurred when a path, query or header parameter name (as declared in the OpenAPI definition) is of a form which doesn't match the form used in Flash, or is a reserved word there. In this case the parameter gets renamed for use in the code, and the algorithm for creating the actual path tries to replace the renamed parameter in the path (which will do nothing), not the original one (which would be correct). For query or header parameters, the parameter will be sent with the sanitized name instead of the original one.
This commit changes the replacement to using `{{baseName}}` (which is the original name of the parameter definition as parsed from the API definition) instead of …

Fix (partially) #4898 for flash

---

modules/swagger-codegen/src/main/resources/dart/api.mustache

→ ran bin/dart-petstore.sh, with no changes in the produced samples.
This fixes (or hopes to fix) part of #4898 for the `dart` generator.
The problem likely occurred when a path parameter name (as declared in the OpenAPI definition) is of a form which doesn't match the form used in Dart, or is a reserved word there. In this case the parameter gets renamed for use in the code, and the algorithm for creating the actual path tries to replace the renamed parameter in the path (which will do nothing), not the original one (which would be correct).
This commit changes the replacement to using `{{baseName}}` (which is the original name of the parameter definition as parsed from the API definition) instead of `{{paramName}}` (which is the sanitized version of the parameter name).
Our Petstore API …

fix (partially) #4898 for dart.

---

.travis.yml
README.md

Follow-up on the improved Docker stuff in #2945 this pull request adds building and uploading a [Swagger Codegen CLI Docker image](https://hub.docker.com/r/swaggerapi/swagger-codegen-cli/) to Docker Hub on releases.

Build and upload Swagger Codegen CLI Docker image on release

---

modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/api.mustache

Change the build call method visibility for operations.
This allows to access the input stream of the body response to monitor a progress for instance. See #5007

[Java] Change build call visibility

---

shippable.yml

Commented out openjdk8 to avoid issue due to JAVA_HOME missing.

[CI] fix shippable config due to JAVA_HOME issue in openjdk8

---

README.md

The README has an error in the name of the Docker Hub repository.

Fix wrong Docker Hub repo in README

---

samples/client/petstore/clojure/src/swagger_petstore/api/pet.clj
samples/client/petstore/clojure/src/swagger_petstore/api/store.clj
samples/client/petstore/clojure/src/swagger_petstore/api/user.clj
samples/client/petstore/clojure/src/swagger_petstore/core.clj
samples/client/petstore/clojure/test/swagger_petstore/core_test.clj

Removed some additional test cases for authentication in Clojure API client as "petstore.json" is being used at the moment.

[Clojure] update Clojure test cases after restoring to petstore.json

---

modules/swagger-codegen/src/main/resources/Groovy/api.mustache
samples/client/petstore/groovy/src/main/groovy/io/swagger/api/PetApi.groovy
samples/client/petstore/groovy/src/main/groovy/io/swagger/api/StoreApi.groovy
samples/client/petstore/groovy/src/main/groovy/io/swagger/api/UserApi.groovy

→ bin/groovy-petstore.sh
This fixes (or hopes to fix) part of #4898 for the `groovy` generator.
The problem likely occurred when a query or header parameter name (as declared in the OpenAPI definition) is of a form which doesn't match the form used in Groovy, or is a reserved word there. In this case the parameter gets renamed for use in the code, and the parameter will be sent with the sanitized name instead of the original one.
This commit changes the replacement to using `{{baseName}}` (which is the original name of the parameter definition as parsed from the API definition) instead of `{{paramName}}` (which is the sanitized version of the parameter name).
_**Note** that it looks like the Groovy generator has no support at all for path, form or body parameters – those are accepted by …

Fix (partially) #4898 for groovy

---

shippable.yml

Use Oracle JDK 8 instead of OpenJDK 8 in shippable config

[CI] use Oracle JDK instead in shippable config

---

modules/swagger-codegen/src/main/resources/akka-scala/model.mustache
samples/client/petstore/akka-scala/pom.xml
samples/client/petstore/akka-scala/src/main/scala/io/swagger/client/api/PetApi.scala
samples/client/petstore/akka-scala/src/main/scala/io/swagger/client/api/UserApi.scala
samples/client/petstore/akka-scala/src/main/scala/io/swagger/client/model/ApiResponse.scala
samples/client/petstore/akka-scala/src/main/scala/io/swagger/client/model/Category.scala
samples/client/petstore/akka-scala/src/main/scala/io/swagger/client/model/Order.scala
samples/client/petstore/akka-scala/src/main/scala/io/swagger/client/model/Pet.scala
samples/client/petstore/akka-scala/src/main/scala/io/swagger/client/model/Tag.scala
samples/client/petstore/akka-scala/src/main/scala/io/swagger/client/model/User.scala

imported java.util.UUID in the model to allow for UUID types

Allow for UUID types in akka-scala

---

modules/swagger-codegen/src/main/resources/haskell-servant/stack.mustache
samples/server/petstore/haskell-servant/lib/SwaggerPetstore/Types.hs
samples/server/petstore/haskell-servant/stack.yaml

Bumps the `servant` dependencies from `0.6` to `0.9.1.1` and haskell from `lts-5.11` to `lts-8.5`.
Fixes issue #4162.

[Haskell] Bump dependencies

---

pom.xml
samples/client/petstore/akka-scala/pom.xml

Update pom.xml to cover akka-scala petstore client.

[Scala] update Travis CI to cover akka-scala petstore client

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AsyncScalaClientCodegen.java
samples/client/petstore/async-scala/src/main/scala/io/swagger/client/api/PetApi.scala

Override `escapeQuotationMark` in Async Scala generator to prevent code injection

[Scala] Override `escapeQuotationMark` in Async Scala generator to prevent code injection

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Swift3Codegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwiftCodegen.java

Adds file type detection to Swift codegen, which was previously missing. This was causing Swift codegen to never know when a parameter or response type was defined with type file.
This fixes issue #4764.

[Swift] Fix issue #4764

---

modules/swagger-codegen-maven-plugin/README.md
modules/swagger-codegen-maven-plugin/src/main/java/io/swagger/codegen/plugin/CodeGenMojo.java

This adds support to the maven plugin to support the selective generation options.

Add Selective Generation support to the Maven plugin.

---

modules/swagger-codegen/src/main/resources/scala/pom.mustache
samples/client/petstore/scala/pom.xml

→ bin/scala-petstore.sh
I noticed that my merge of master and 2.3.0 had a different version number than both master and 2.3.0.
The reason is that the master sample was not up-to-date (#4881 forgot to update the scala samples).
~~~This updates it – CI will fail here, I'll try to fix this in a follow-up commit. Please do not merge yet.~~~

Update petstore samples for scala client.

---

bin/akka-scala-petstore.sh
bin/windows/akka-scala-petstore.bat
samples/client/petstore/akka-scala/pom.xml
samples/client/petstore/akka-scala/src/main/resources/reference.conf

→ bin/akka-scala-petstore.sh (twice, once before and once after the change).
This was first just meant to update the Akka samples, there are no code changes here.
The first commit (updating samples from the script) undoes part of the change from #5073, which changed the name + artifact ID manually.
This shows that the default artifact ID is not what is used when running CI.
The second commit changes the sample update scripts to set the correct `--artifact-id` parameter.
The third commit updates the samples again, showing that everything is fine now. (There is a change in the generated reference.conf, not sure if it is relevant.)

Fix sample script to set the correct artifact ID in the generated POM

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Swift3Codegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/swift3/Swift3CodegenTest.java

Swift3 generator: added 'number' prefix to enum variable names that start with a number
Same issue as #3934, but for the Swift3 Generator.

Swift3 enum: number variable names fix

---

modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/pom.mustache
samples/client/petstore/jaxrs-cxf/pom.xml

fix dependencies for swagger-core 1.5.12 for CXF client see #4924

[Jaxrs-cxf-client] Add jackson dependencies to pom for cxf-client #4924

---

modules/swagger-codegen/src/main/resources/csharp/api.mustache
samples/client/petstore/csharp/SwaggerClient/IO.Swagger.sln
samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/IO.Swagger.csproj
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/IO.Swagger.sln
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/src/IO.Swagger.Test/IO.Swagger.Test.csproj
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/src/IO.Swagger/IO.Swagger.csproj

To fix https://github.com/swagger-api/swagger-codegen/issues/4977

[C#] fix path with {{{ .. }}} in c# API mustache file

---

modules/swagger-codegen/src/main/resources/elixir/api.mustache
samples/client/petstore/elixir/lib/swagger_petstore/api/fake.ex
samples/client/petstore/elixir/lib/swagger_petstore/api/pet.ex

→ bin/elixir-petstore.sh
This fixes (or hopes to fix) part of #4898 for the `elixir` generator.
The problem likely occurred when a query/form/header parameter name (as declared in the OpenAPI definition) is of a form which doesn't match the form used in Elixir, or is a reserved word there. In this case the parameter gets renamed for use in the code, and the algorithm for including the parameter in the request uses the sanitized name instead of the original one.
This commit changes the replacement to using `{{baseName}}` (which is the original name of the parameter definition as parsed from the API definition) instead of `{{paramName}}` (which is the sanitized version of the parameter name).
There are some places in the Petstore samples where this makes some difference, to me it looks like …

Fix (partially) #4898 for elixir

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FlaskConnexionCodegen.java

Solves #4752 by adding the `import re` when model has any property using the `pattern` constraint.

[python/flask] Fix #4752 by adding missing import when pattern constraing is used

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AkkaScalaClientCodegen.java
samples/client/petstore/akka-scala/src/main/scala/io/swagger/client/api/UserApi.scala

Ensure identifiers get sanitized & model names have the same formatting

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AspNetCoreServerCodegen.java
modules/swagger-codegen/src/main/resources/aspnetcore/Dockerfile.mustache
modules/swagger-codegen/src/main/resources/aspnetcore/README.mustache
samples/server/petstore/aspnetcore/IO.Swagger.sln
samples/server/petstore/aspnetcore/README.md
samples/server/petstore/aspnetcore/global.json
samples/server/petstore/aspnetcore/src/IO.Swagger/Dockerfile
samples/server/petstore/aspnetcore/src/IO.Swagger/IO.Swagger.xproj

* Use lower-case packageName for README.md docker build example
* Use dotnet:1.0.3-sdk instead of just "latest"
* Regenerate Petstore server sample
Fixes #5126.

[C#][aspnetcore] Fix broken Docker build option & documentation

---

modules/swagger-codegen/src/main/resources/typescript-angular2/apis.mustache
samples/client/petstore/typescript-angular2/default/api/api.ts
samples/client/petstore/typescript-angular2/npm/README.md
samples/client/petstore/typescript-angular2/npm/api/api.ts
samples/client/petstore/typescript-angular2/npm/package.json

For https://github.com/swagger-api/swagger-codegen/pull/4539#issuecomment-286544175

[TypeScript][Angular2] Add back missing changes from #4539 due to bad merge

---

modules/swagger-codegen/src/main/resources/htmlDocs2/index.mustache
modules/swagger-codegen/src/main/resources/htmlDocs2/js_jsonformatter.mustache

The JSON view won't be rendered correctly if there is enum type in the module declared in the swagger file when generating html2Doc. I used chrome to find out that there is an undefined exception which is caused by the missing library [json-formatter-js](https://github.com/mohsen1/json-formatter-js.git). After adding the dependency, everything goes well.

[htmlDoc2] add support for enum type.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FlaskConnexionCodegen.java
modules/swagger-codegen/src/main/resources/flaskConnexion/Dockerfile.mustache
modules/swagger-codegen/src/main/resources/flaskConnexion/README.mustache
modules/swagger-codegen/src/main/resources/flaskConnexion/dockerignore.mustache
samples/server/petstore/flaskConnexion/.dockerignore
samples/server/petstore/flaskConnexion/Dockerfile
samples/server/petstore/flaskConnexion/README.md
samples/server/petstore/flaskConnexion/swagger_server/swagger/swagger.yaml

Adds Docker support for the `python-flask` lang.
Generates a Dockerfile for python2 and python3.

Add docker support to python flask

---

README.md

→ none needed, just a README fix.
This just adds a single missing code marker (`` ` ``) in the README, which did break the markup in one paragraph.

fix missing code marker in README.md

---

modules/swagger-codegen-maven-plugin/src/main/java/io/swagger/codegen/plugin/CodeGenMojo.java

See  #5151
Options passed as system properties are now properly reset when disabled in the execution configuration.

Fix selective generation in successive Maven plugin executions

---

pom.xml

Not applicable... simple POM change.
Update maven-bundle-plugin to 3.3.0 to fix CVE-2012-2098, per issue #5148

Update maven-bundle-plugin version in POM

---

modules/swagger-codegen/src/main/resources/Java/libraries/retrofit/auth/OAuth.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/auth/OAuth.mustache
samples/client/petstore/java/retrofit/src/main/java/io/swagger/client/auth/OAuth.java
samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/auth/OAuth.java
samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/auth/OAuth.java

The updateAccessToken method returns `true` when it means `false` and
vice versa. Fixes #5039 .
Fixes an issue in the generated OAuth client for Java retrofit, retrofit2, and retrofit2-rx clients.  The `OAuth.updateAccessToken` method is returning true when it means false, and vice versa. This causes some authentication errors to be mistakenly forwarded to the client, even when an automatic retry is possible, and can also cause an infinite recursion loop when the client receives a 401 or 403 that is not related to the OAuth flow.

Modify Java/retrofit OAuth templates for #5039

---

modules/swagger-codegen/src/main/resources/Java/libraries/feign/api.mustache
samples/client/petstore/java/feign/src/main/java/io/swagger/client/api/FakeApi.java

In the convenience class defined for generating a Map of query parameters, the
parameter name was mistakenly being set to the Java variable name, not the
actual parameter name. These are often the same, but can be different in the
case of multi-word parameters, such as in the sample API's `enum_query_string`
vs `enumQueryString`.
In the convenience class for building up a query parameter map in the Feign API, changed the value of the URL parameter name from the Java variable name to the proper parameter name. You can see how this affects the code in the pet store sample, which has a few cases of multi-word parameters where the parameter name is different from the Java variable name.

Fixes a bug in #5142 for multi-word parameters

---

samples/client/petstore/objc/core-data/SwaggerClient/Api/SWGPetApi.m
samples/client/petstore/objc/core-data/SwaggerClient/Api/SWGStoreApi.m
samples/client/petstore/objc/core-data/SwaggerClient/Api/SWGUserApi.m
samples/client/petstore/objc/core-data/SwaggerClient/Core/SWGApiClient.m

→ bin/objc-petstore-all.sh
No code-changes, just updating the samples so later updates can see what actually changed.
The changes likely come from #4987 (which updated just objc/default, not objc/core-data).

Update samples for ObjC/core-data.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java
modules/swagger-codegen/src/main/resources/Javascript/ApiClient.mustache
modules/swagger-codegen/src/main/resources/Javascript/package.mustache
modules/swagger-codegen/src/test/java/io/swagger/codegen/javascript/JavaScriptModelTest.java
samples/client/petstore/javascript-promise/docs/FakeApi.md
samples/client/petstore/javascript-promise/docs/FormatTest.md
samples/client/petstore/javascript-promise/package.json
samples/client/petstore/javascript-promise/src/ApiClient.js
samples/client/petstore/javascript-promise/src/api/FakeApi.js
samples/client/petstore/javascript-promise/src/model/FormatTest.js
samples/client/petstore/javascript/docs/FakeApi.md
samples/client/petstore/javascript/docs/FormatTest.md
samples/client/petstore/javascript/package.json
samples/client/petstore/javascript/src/ApiClient.js
samples/client/petstore/javascript/src/api/FakeApi.js
samples/client/petstore/javascript/src/model/FormatTest.js

This PR replaces the String type for binary and byte array properties by a blob type which allows superagent to return bytes array instead of a String or a JSON object.

[Javascript] Support for ByteArray and Binary

---

samples/client/petstore/jaxrs-cxf-client/src/gen/java/io/swagger/api/PetApi.java
samples/client/petstore/jaxrs-cxf-client/src/gen/java/io/swagger/api/StoreApi.java
samples/client/petstore/jaxrs-cxf-client/src/gen/java/io/swagger/api/UserApi.java
samples/server/petstore/jaxrs-cxf-annotated-base-path/src/gen/java/io/swagger/api/PetApi.java
samples/server/petstore/jaxrs-cxf-annotated-base-path/src/gen/java/io/swagger/api/StoreApi.java
samples/server/petstore/jaxrs-cxf-annotated-base-path/src/gen/java/io/swagger/api/UserApi.java
samples/server/petstore/jaxrs-cxf-annotated-base-path/src/gen/java/io/swagger/model/Category.java
samples/server/petstore/jaxrs-cxf-annotated-base-path/src/gen/java/io/swagger/model/ModelApiResponse.java
samples/server/petstore/jaxrs-cxf-annotated-base-path/src/gen/java/io/swagger/model/Order.java
samples/server/petstore/jaxrs-cxf-annotated-base-path/src/gen/java/io/swagger/model/Pet.java
samples/server/petstore/jaxrs-cxf-annotated-base-path/src/gen/java/io/swagger/model/Tag.java
samples/server/petstore/jaxrs-cxf-annotated-base-path/src/gen/java/io/swagger/model/User.java
samples/server/petstore/jaxrs-cxf-non-spring-app/src/gen/java/io/swagger/api/PetApi.java
samples/server/petstore/jaxrs-cxf-non-spring-app/src/gen/java/io/swagger/api/StoreApi.java
samples/server/petstore/jaxrs-cxf-non-spring-app/src/gen/java/io/swagger/api/UserApi.java
samples/server/petstore/jaxrs-cxf-non-spring-app/src/gen/java/io/swagger/model/Category.java
samples/server/petstore/jaxrs-cxf-non-spring-app/src/gen/java/io/swagger/model/ModelApiResponse.java
samples/server/petstore/jaxrs-cxf-non-spring-app/src/gen/java/io/swagger/model/Order.java
samples/server/petstore/jaxrs-cxf-non-spring-app/src/gen/java/io/swagger/model/Pet.java
samples/server/petstore/jaxrs-cxf-non-spring-app/src/gen/java/io/swagger/model/Tag.java
samples/server/petstore/jaxrs-cxf-non-spring-app/src/gen/java/io/swagger/model/User.java

→ bin/jaxrs-cxf-petstore-server-non-spring-application.sh, bin/jaxrs-cxf-petstore-server-annotated-base-path.sh, bin/jaxrs-cxf-petstore-server.sh, bin/jaxrs-cxf-client-petstore.sh
No code changes, just updating the samples so later updates can easier say what changed.
The `@Valid` was likely added by #4921. #4920 added some `@ApiResponse`. The `@ApiModelProperty` changes came from #5017. Some XmlGregorianCalendar → Date changes came likely from #4724.

Update samples for JaxRS/CXF.

---

bin/bash-petstore.sh
modules/swagger-codegen/src/main/resources/bash/bash-completion.mustache
modules/swagger-codegen/src/main/resources/bash/client.mustache
modules/swagger-codegen/src/main/resources/bash/zsh-completion.mustache
samples/client/petstore/bash/_petstore-cli
samples/client/petstore/bash/petstore-cli
samples/client/petstore/bash/petstore-cli.bash-completion

→ bin/bash-petstore.sh
This removes the output of the timestamp for the bash petstore samples, as a part of #3084.
This consists of two steps:
* make the templates aware of `hideGenerationTimestamp`
* pass the value `true` in the sample generation script.
This does not try to change the default behavior, if wished this can be done in a separate pull request.

Issue #3084: remove timestamps from bash samples.

---

bin/csharp-petstore.sh
bin/csharp-property-changed-petstore.sh
bin/windows/csharp-petstore-netstandard.bat
bin/windows/csharp-petstore.bat

→ bin/csharp-petstore.sh + bin/csharp-property-changed-petstore.sh.
This changes the C# sample generation scripts to pass a fixed packageGuid parameter.
The effect is that the generated samples don't change randomly with every update, obfuscating the real changes. (This is a part of #5196.)
The functionality for this was already build in #1941, when the project files with GUIDs were added.
I chose the fixed GUIDs as the latest random value from master, with the effect that an update now doesn't change anything anymore. (When merging into 2.3.0 and regenerating, you'll get a change once.)
(I also changed the .bat files, though **I'm not able to test this here**.)

[C#] Issue #5196: make package GUID non-random for the C# samples.

---

bin/nancyfx-petstore-server.sh
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/NancyFXServerCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/NancyFXServerOptionsProvider.java

→ bin/nancyfx-petstore-server.sh
This adds a `packageGuid` parameter to NancyFXServerCodegen, which allows to pass a fixed GUID, instead of a randomly generated one.
The petstore sample generation script then uses this option (with the last random value from master) to generate the samples. This way there are no random changes between sample updates which obscured the real changes.  (This is a part of #5196.)

[nancyfx] Issue #5196: make package GUID nonrandom for nancyfx samples

---

bin/aspnetcore-petstore-server.sh
bin/windows/aspnetcore-petstore-server.bat
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AspNetCoreServerCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/aspnetcore/AspNetCoreServerOptionsTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/AspNetCoreServerOptionsProvider.java

→ bin/aspnetcore-petstore-server.sh
This adds a `packageGuid` parameter to the AspNetCoreServerCodegen generator, which allows passing a fixed GUID as a parameter, analogously to the argument of CSharpClientCodegen. (I actually copied some code from there.)
I also added this parameter to the sample generation script, with the value being the latest randomly generated value from master.
This way, the generated files won't randomly change with every sample-update, and actual changes are better visible. (This is a part of #5196.)
I also changed the windows .bat file, though **I'm not able to test this here.**

[ASP.NET] Issue #5196: add packageGuid parameter to AspNetCoreServerCodegen.

---

samples/client/petstore/ruby/lib/petstore/api/fake_api.rb
samples/server/petstore/rails5/README.md

→ bin/rails5-petstore-server.sh, bin/ruby-petstore.sh
No code changes, just updating the samples (so later updates show what actually changed.)
* The ruby client got some additional code for enum validation – likely related to other enum changes for other languages, but I didn't find out where it comes from.
* The Ruby-on-Rails Server's README got a typo fix (from #4656).
*(I bundled those two updates together because I thought the same people might want to review them.)*

[Ruby][Rails] Update samples for Ruby-Client + Rails server.

---

samples/server/petstore/java-inflector/src/gen/java/io/swagger/model/AdditionalPropertiesClass.java
samples/server/petstore/java-inflector/src/gen/java/io/swagger/model/Animal.java
samples/server/petstore/java-inflector/src/gen/java/io/swagger/model/ArrayOfArrayOfNumberOnly.java
samples/server/petstore/java-inflector/src/gen/java/io/swagger/model/ArrayOfNumberOnly.java
samples/server/petstore/java-inflector/src/gen/java/io/swagger/model/ArrayTest.java
samples/server/petstore/java-inflector/src/gen/java/io/swagger/model/Capitalization.java
samples/server/petstore/java-inflector/src/gen/java/io/swagger/model/Cat.java
samples/server/petstore/java-inflector/src/gen/java/io/swagger/model/Category.java
samples/server/petstore/java-inflector/src/gen/java/io/swagger/model/ClassModel.java
samples/server/petstore/java-inflector/src/gen/java/io/swagger/model/Client.java
samples/server/petstore/java-inflector/src/gen/java/io/swagger/model/Dog.java
samples/server/petstore/java-inflector/src/gen/java/io/swagger/model/EnumArrays.java
samples/server/petstore/java-inflector/src/gen/java/io/swagger/model/EnumTest.java
samples/server/petstore/java-inflector/src/gen/java/io/swagger/model/FormatTest.java
samples/server/petstore/java-inflector/src/gen/java/io/swagger/model/HasOnlyReadOnly.java
samples/server/petstore/java-inflector/src/gen/java/io/swagger/model/MapTest.java
samples/server/petstore/java-inflector/src/gen/java/io/swagger/model/MixedPropertiesAndAdditionalPropertiesClass.java
samples/server/petstore/java-inflector/src/gen/java/io/swagger/model/Model200Response.java
samples/server/petstore/java-inflector/src/gen/java/io/swagger/model/ModelApiResponse.java
samples/server/petstore/java-inflector/src/gen/java/io/swagger/model/ModelReturn.java
samples/server/petstore/java-inflector/src/gen/java/io/swagger/model/Name.java
samples/server/petstore/java-inflector/src/gen/java/io/swagger/model/NumberOnly.java
samples/server/petstore/java-inflector/src/gen/java/io/swagger/model/Order.java
samples/server/petstore/java-inflector/src/gen/java/io/swagger/model/Pet.java
samples/server/petstore/java-inflector/src/gen/java/io/swagger/model/ReadOnlyFirst.java
samples/server/petstore/java-inflector/src/gen/java/io/swagger/model/SpecialModelName.java
samples/server/petstore/java-inflector/src/gen/java/io/swagger/model/Tag.java
samples/server/petstore/java-inflector/src/gen/java/io/swagger/model/User.java
samples/server/petstore/java-inflector/src/main/swagger/swagger.yaml

No code changes, just updating the samples so later updates can see what actually changed.
The many @ApiModelProperty changes came from #5017.
I don't know where the YAML changes came from (neither the source YAML was changed since this was last generated, nor was there any recent PR obviously about it).

[java][inflector] Update samples for Java Inflector.

---

samples/server/petstore/undertow/src/main/java/io/swagger/model/Category.java
samples/server/petstore/undertow/src/main/java/io/swagger/model/ModelApiResponse.java
samples/server/petstore/undertow/src/main/java/io/swagger/model/Order.java
samples/server/petstore/undertow/src/main/java/io/swagger/model/Pet.java
samples/server/petstore/undertow/src/main/java/io/swagger/model/Tag.java
samples/server/petstore/undertow/src/main/java/io/swagger/model/User.java
samples/server/petstore/undertow/src/main/resources/config/swagger.json

→ bin/java-undertow-petstore-server.sh
No code changes, just updating samples so later updates can see the actual changes.
The "null" changes were from #5017, the @Generated changes were from #4366.

[java][undertow] Update samples for Java/Undertow.

---

samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/io/swagger/api/ApiException.java
samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/io/swagger/api/ApiOriginFilter.java
samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/io/swagger/api/ApiResponseMessage.java
samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/io/swagger/api/NotFoundException.java
samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/io/swagger/model/Category.java
samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/io/swagger/model/ModelApiResponse.java
samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/io/swagger/model/Order.java
samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/io/swagger/model/Pet.java
samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/io/swagger/model/Tag.java
samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/io/swagger/model/User.java

→ bin/jaxrs-resteasy-joda-petstore-server.sh
No code changes, just updating the samples so later updates show real changes.
This contains tab→spaces changes from #5174, as well as the "null" fixes from #5017.

[java][JaxRS] Update samples for JaxRS/RestEasy/Joda.

---

modules/swagger-codegen/src/main/resources/MSF4J/pom.mustache
samples/server/petstore/java-msf4j/.swagger-codegen-ignore
samples/server/petstore/java-msf4j/mvn_test_jdk8_only.sh
samples/server/petstore/java-msf4j/pom.xml
samples/server/petstore/java-msf4j/src/gen/java/io/swagger/api/FakeApi.java

For https://github.com/swagger-api/swagger-codegen/issues/5219. Also fixed indentation in pom.xml

[Java][MSF4J] add CI test for MSF4J Petstore server

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ErlangServerCodegen.java
samples/server/petstore/erlang-server/priv/swagger.json
samples/server/petstore/erlang-server/src/swagger_api.erl

→ bin/erlang-petstore-server.sh
I wanted to just update the samples, but noticed there that the generated swagger.json is a single line (of 13593 bytes before the update vs. 14000 bytes afterwards).
There is no way of reviewing the changes therein.
So this PR adds pretty-printing of the swagger.json to the generation process, then updates the samples.
In a first commit I manually pretty-printed the swagger.json, using `jq` – this is not exactly the same format, but with ignoring whitespace changes you can see the actual changes in the later commits. As far as I can see, only added title/description for some of the models, and a `"minimum": 1` removed for the orderId parameter.
Other than this, swagger_api.erl has some minor changes (the same `{min,1.0}` removed, and at one point changed …

[Erlang] pretty print swagger json

---

modules/swagger-codegen/src/main/resources/TypeScript-Fetch/api.mustache

This change enables top level enumeratons to be written out as:
```
export type SortDirection = "Ascending" | "Descending";
```
vs.
```
export class SortDirection {
}
```

export top level enumeration types in typescript-fetch mode

---

modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/ApiClient.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/api.mustache
samples/client/petstore/java/retrofit2-play24/src/main/java/io/swagger/client/api/FakeApi.java
samples/client/petstore/java/retrofit2-play24/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/retrofit2-play24/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/retrofit2-play24/src/main/java/io/swagger/client/api/UserApi.java
samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/api/FakeApi.java
samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/api/UserApi.java
samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/api/FakeApi.java
samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/api/UserApi.java

For https://github.com/swagger-api/swagger-codegen/issues/5175

[Java][Retrofit2] better code indentation

---

modules/swagger-codegen/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml

Add port 80 to Swagger spec so as to ensure the port is shown correctly in the auto-generated code/doc.

Add port 80 to swagger spec

---

bin/java-undertow-petstore-server.sh
modules/swagger-codegen/src/main/resources/undertow/generatedAnnotation.mustache
samples/server/petstore/undertow/src/main/java/io/swagger/model/Category.java
samples/server/petstore/undertow/src/main/java/io/swagger/model/ModelApiResponse.java
samples/server/petstore/undertow/src/main/java/io/swagger/model/Order.java
samples/server/petstore/undertow/src/main/java/io/swagger/model/Pet.java
samples/server/petstore/undertow/src/main/java/io/swagger/model/Tag.java
samples/server/petstore/undertow/src/main/java/io/swagger/model/User.java

→ bin/java-undertow-petstore-server.sh
* implement the `hideGenerationTimestamp` option for the undertow generator
* use the option in the sample generation script
* update the samples

Issue #3084: remove timestamps from undertow samples

---

bin/jaxrs-jersey1-petstore-server.sh
bin/jaxrs-petstore-server.sh
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaJAXRSServerCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/JavaCXFServerOptionsProvider.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/JavaResteasyEapServerOptionsProvider.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/JavaResteasyServerOptionsProvider.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/JaxRSServerOptionsProvider.java
samples/server/petstore/jaxrs/jersey1/src/gen/java/io/swagger/api/FakeApi.java
samples/server/petstore/jaxrs/jersey1/src/gen/java/io/swagger/model/FormatTest.java
samples/server/petstore/jaxrs/jersey1/src/main/webapp/WEB-INF/web.xml
samples/server/petstore/jaxrs/jersey2/src/gen/java/io/swagger/api/FakeApi.java
samples/server/petstore/jaxrs/jersey2/src/main/webapp/WEB-INF/web.xml

→ bin/jaxrs-jersey1-petstore-server.sh, bin/jaxrs-petstore-server.sh
We are introducing a CLI argument `serverPort` to the generators which overrides the port given in the API definition's `host` or the default of `8080`.
This we use from the generating scripts, so the CI tests won't try to use `80` (which is usually reserved to privileged processes).
(Triggered by the change in #5232 and the failing tests in #5243.)

[JaxRS Server][Jersey1/2] Pass server port by cli

---

modules/swagger-codegen/src/main/resources/typescript-angular2/api.service.mustache
modules/swagger-codegen/src/main/resources/typescript-angular2/configuration.mustache
samples/client/petstore/typescript-angular2/default/api/pet.service.ts
samples/client/petstore/typescript-angular2/default/api/store.service.ts
samples/client/petstore/typescript-angular2/default/configuration.ts
samples/client/petstore/typescript-angular2/npm/README.md
samples/client/petstore/typescript-angular2/npm/api/pet.service.ts
samples/client/petstore/typescript-angular2/npm/api/store.service.ts
samples/client/petstore/typescript-angular2/npm/configuration.ts
samples/client/petstore/typescript-angular2/npm/package.json

Please see #5227 for the initial PR (incorrectly set to merge to master)
Fix for #5224
To allow for multiple API Keys, the configuration now expects a dictionary of keys. The key is the name of the header and the value is the API Key itself.
NOTE: I've copied across the relevant Pet Store changes from my previous PR.  However running the scripts to regenerate them made a load of unrelated changes and I'm not sure what to make of them to be honest.  I can submit these as a separate PR if you'd like me to?

[Typescript - Angular2] Add support for multiple API Keys

---

modules/swagger-codegen/src/main/resources/nodejs/index.mustache

See title.
Shell script did not run, see output below. Any hint?
```
Downloaded: https://repo.maven.apache.org/maven2/oro/oro/2.0.8/oro-2.0.8.jar (64 KB at 331.9 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar (562 KB at 2519.7 KB/sec)
[INFO] Reactor Summary:
[INFO] 
[INFO] swagger-codegen-project ........................... FAILURE [51.408s]
[INFO] swagger-codegen (core library) .................... SKIPPED
[INFO] swagger-codegen (executable) ...................... SKIPPED
[INFO] swagger-codegen (maven-plugin) .................... SKIPPED
[INFO] swagger-generator ................................. SKIPPED
[INFO] …
```

Use `__dirname` for paths if server is started from a different directory

---

samples/client/petstore/javascript-promise/src/ApiClient.js
samples/client/petstore/javascript-promise/src/model/FormatTest.js
samples/client/petstore/javascript/src/ApiClient.js
samples/client/petstore/javascript/src/model/FormatTest.js

→ bin/javascript-petstore.sh, bin/javascript-promise-petstore.sh
No code changes, just updating the samples (so later sample updates show what happened).
It looks like #5194 (which added the blob feature) didn't update the samples with the latest version of the code, but an earlier one.

Update samples for javascript + javascript-promise.

---

modules/swagger-codegen/src/main/resources/csharp/compile.mustache

Replace IO.Swagger for {{packageName}} where necessary on compile.mustache.
Found issue #5239 reported and already proposed the fix did not send the pull request.

fix mustache file for csharp client library generation build.bat

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
modules/swagger-codegen/src/main/resources/Java/libraries/feign/EncodingUtils.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/feign/api.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/feign/pom.mustache
samples/client/petstore/java/feign/pom.xml
samples/client/petstore/java/feign/src/main/java/io/swagger/client/EncodingUtils.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/api/FakeApi.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/feign/src/main/java/io/swagger/client/api/UserApi.java
samples/client/petstore/java/feign/src/test/java/io/swagger/client/api/PetApiTest.java

Feign only natively supports the "multi" collectionFormat for encoding lists
of parameter values. This change adds manual encoding of the other formats, such
as "csv" (the default for collections), "tsv", space-separated, and pipes.
Suggested fix for #5265.
Defines a new utility class for encoding query parameters. For QueryMap parameters, uses the convenience class to manually encode the parameters instead of having Feign encode them. Unfortunately, this doesn't help with the API that lists out the query parameters individually, but users can directly call the utility methods as a workaround.
It also adds finer-grained testing of the generated URL with the MockWebServer from okhttp.

Support Swagger collectionFormat encodings in Feign

---

modules/swagger-codegen/src/test/resources/2_0/templates/Java/libraries/jersey2/ApiClient.mustache

The code generated for Jersey2 is unable to dowload file responses.
For an endpoint with the file response type, the API call with the generated client results in a FileAlreadyExistsException.
A sample response:
responses:
200:
description: The template workbook
schema:
type: file
The exception:
xyz.client.ApiException: java.nio.file.FileAlreadyExistsException: e:\temp-dir\download-4619092686092804097
at xyz.client.ApiClient.downloadFileFromResponse(ApiClient.java:576)
at xyz.client.ApiClient.deserialize(ApiClient.java:550)
at xyz.client.ApiClient.invokeAPI(ApiClient.java:693)
at xyz.client.api.DefaultApi.getTemplateFile(DefaultApi.java:79)
In order for Files.copy to not fail, Files.copy needs to have the StandardCopyOption.REPLACE_EXISTING option specified (prepareDownloadFile creates an …

[Java,Jersey2] Files.copy in generated code throws FileAlreadyExistsException

---

modules/swagger-codegen/src/main/resources/typescript-node/api.mustache
samples/client/petstore/typescript-node/default/api.ts
samples/client/petstore/typescript-node/npm/api.ts

This adds a setter for basePath so it can be changed after calling the constructor.

TypeScript client API: Add setter for base path

---

modules/swagger-codegen/src/main/resources/csharp/mono_nunit_test.mustache

Similar to https://github.com/swagger-api/swagger-codegen/pull/5264, this fix applies to the mono test script.

[C#] fix package name in mono test script

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java

For https://github.com/swagger-api/swagger-codegen/issues/5296

[Java] add logic to camelize path variables for Feign client

---

bin/jaxrs-resteasy-eap-joda-petstore-server.json
bin/jaxrs-resteasy-eap-joda-petstore-server.sh
bin/jaxrs-resteasy-eap-petstore-server.sh
modules/swagger-codegen/src/main/resources/JavaJaxRS/resteasy/eap/JacksonConfig.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/resteasy/eap/RestApplication.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/resteasy/eap/web.mustache
pom.xml
samples/server/petstore/jaxrs-resteasy/eap-joda/pom.xml
samples/server/petstore/jaxrs-resteasy/eap-joda/settings.gradle
samples/server/petstore/jaxrs-resteasy/eap-joda/src/gen/java/io/swagger/model/Category.java
samples/server/petstore/jaxrs-resteasy/eap-joda/src/gen/java/io/swagger/model/ModelApiResponse.java
samples/server/petstore/jaxrs-resteasy/eap-joda/src/gen/java/io/swagger/model/Order.java
samples/server/petstore/jaxrs-resteasy/eap-joda/src/gen/java/io/swagger/model/Pet.java
samples/server/petstore/jaxrs-resteasy/eap-joda/src/gen/java/io/swagger/model/Tag.java
samples/server/petstore/jaxrs-resteasy/eap-joda/src/gen/java/io/swagger/model/User.java
samples/server/petstore/jaxrs-resteasy/eap-joda/src/main/java/io/swagger/api/RestApplication.java
samples/server/petstore/jaxrs-resteasy/eap-joda/src/main/webapp/WEB-INF/web.xml
samples/server/petstore/jaxrs-resteasy/eap/pom.xml
samples/server/petstore/jaxrs-resteasy/eap/src/gen/java/io/swagger/model/Category.java
samples/server/petstore/jaxrs-resteasy/eap/src/gen/java/io/swagger/model/ModelApiResponse.java
samples/server/petstore/jaxrs-resteasy/eap/src/gen/java/io/swagger/model/Order.java
samples/server/petstore/jaxrs-resteasy/eap/src/gen/java/io/swagger/model/Pet.java
samples/server/petstore/jaxrs-resteasy/eap/src/gen/java/io/swagger/model/Tag.java
samples/server/petstore/jaxrs-resteasy/eap/src/gen/java/io/swagger/model/User.java
samples/server/petstore/jaxrs-resteasy/eap/src/main/java/io/swagger/api/RestApplication.java
samples/server/petstore/jaxrs-resteasy/eap/src/main/webapp/WEB-INF/web.xml

This fixes #5302
This is for the EAP version specifically.
* The JacksonConfig class always used the io.swagger.api package
* The RestApplication class did not import the service implementations
from the correct package
* Added shell script for generating test applications

[JaxrsResteasy] Fix JacksonConfig package and RestApplication imports

---

bin/security/typescript-fetch.sh
samples/client/petstore-security-test/typescript-fetch/api.ts

→ bin/security/typescript-fetch.sh
No generator changes, just a sample generation script.
The script bin/security/typescript-fetch.sh complained that the template directory `modules/swagger-codegen/src/main/resources/typescript-fetch` does not exist. It actually is named `.../TypeScript-Fetch`, which is a difference e.g. on case-sensitive file systems (e.g. the usual Linux ones), while it is ignored in case-insensitive ones (e.g. usual on Windows) or case-preserving ones (usual on MacOS).
Also updated the samples after the change.

[typescript-fetch][util] Fix template directory used by samples script.

---

samples/client/petstore-security-test/swift/SwaggerClient.podspec
samples/client/petstore-security-test/swift/SwaggerClient/Classes/Swaggers/APIHelper.swift
samples/client/petstore-security-test/swift/SwaggerClient/Classes/Swaggers/APIs.swift
samples/client/petstore-security-test/swift/SwaggerClient/Classes/Swaggers/APIs/FakeAPI.swift
samples/client/petstore-security-test/swift/SwaggerClient/Classes/Swaggers/AlamofireImplementations.swift
samples/client/petstore-security-test/swift/SwaggerClient/Classes/Swaggers/Extensions.swift
samples/client/petstore-security-test/swift/SwaggerClient/Classes/Swaggers/Models.swift
samples/client/petstore-security-test/swift/SwaggerClient/Classes/Swaggers/Models/Return.swift

→ bin/security/sift-petstore.sh
No code changes, just updating some samples so later updates show what actually changed.

Update security samples for swift.

---

modules/swagger-codegen/src/main/resources/python/api.mustache
modules/swagger-codegen/src/main/resources/python/api_client.mustache
samples/client/petstore/python/petstore_api/api_client.py
samples/client/petstore/python/petstore_api/apis/fake_api.py
samples/client/petstore/python/petstore_api/apis/fake_classname_tags_123_api.py
samples/client/petstore/python/petstore_api/apis/pet_api.py
samples/client/petstore/python/petstore_api/apis/store_api.py
samples/client/petstore/python/petstore_api/apis/user_api.py
samples/client/petstore/python/tests/test_pet_api.py

Fixes issue https://github.com/swagger-api/swagger-codegen/issues/4235. Implementation of solution suggested here: https://github.com/swagger-api/swagger-codegen/issues/4235#issuecomment-291086921. See test cases for examples: https://github.com/swagger-api/swagger-codegen/pull/5308/files#diff-c5c849b26d5134175812cdb46ddbe39cR143
In next iteration implementation can be improved by adding separate methods for async stuff like `api.get_pet_by_id_async()` and `api.get_pet_by_id_async_with_http_info()`.

[Python] async error handling fix

---

modules/swagger-codegen/src/main/resources/akka-scala/paramCreation.mustache

To fix https://github.com/swagger-api/swagger-codegen/issues/5333
Also reviewed `scala` and `async-scala` generators, which do not use backticks to escape reserved words.

[Scala] use original value of paramName in Akka Scala templates

---

modules/swagger-codegen-maven-plugin/examples/java-client.xml

This PR addresses issue #5332. I was looking for a way to use swagger-codegen-maven-plugin in order to generate server code (based on Spring Boot). The current example generates client code only. Therefore, I added a hint to the example to make it easier for other people to find out how to generate server code.

swagger-codegen-maven-plugin: hint added how to generate server code

---

modules/swagger-codegen/src/main/resources/JavaSpring/pojo.mustache

Added serialVersionUID to the mustache template for Spring POJO's to resolve a Java compiler warning.
Link to issue: https://github.com/swagger-api/swagger-codegen/issues/5346

[Spring] Adds serialVersionUID to serializable model POJO's

---

modules/swagger-codegen/src/main/resources/perl/ApiClient.mustache
modules/swagger-codegen/src/main/resources/perl/ApiFactory.mustache
modules/swagger-codegen/src/main/resources/perl/Configuration.mustache
modules/swagger-codegen/src/main/resources/perl/README.mustache
modules/swagger-codegen/src/main/resources/perl/Role.mustache
modules/swagger-codegen/src/main/resources/perl/api.mustache
modules/swagger-codegen/src/main/resources/perl/api_doc.mustache
samples/client/petstore/perl/README.md
samples/client/petstore/perl/docs/FakeApi.md
samples/client/petstore/perl/docs/FakeClassnameTags123Api.md
samples/client/petstore/perl/docs/PetApi.md
samples/client/petstore/perl/docs/StoreApi.md
samples/client/petstore/perl/docs/UserApi.md
samples/client/petstore/perl/lib/WWW/SwaggerClient/ApiClient.pm
samples/client/petstore/perl/lib/WWW/SwaggerClient/ApiFactory.pm
samples/client/petstore/perl/lib/WWW/SwaggerClient/Configuration.pm
samples/client/petstore/perl/lib/WWW/SwaggerClient/FakeApi.pm
samples/client/petstore/perl/lib/WWW/SwaggerClient/FakeClassnameTags123Api.pm
samples/client/petstore/perl/lib/WWW/SwaggerClient/PetApi.pm
samples/client/petstore/perl/lib/WWW/SwaggerClient/Role.pm
samples/client/petstore/perl/lib/WWW/SwaggerClient/StoreApi.pm
samples/client/petstore/perl/lib/WWW/SwaggerClient/UserApi.pm
samples/client/petstore/perl/test.pl
samples/client/petstore/perl/tests/01_pet_api.t
samples/client/petstore/perl/tests/02_store_api.t
samples/client/petstore/perl/tests/03_api_factory.t
samples/client/petstore/perl/tests/04_role.t

- removed Singleton from ApiClient
fixes #5336
The perl singleton was removed and the documentation updated ( at least i hope i found all relevant parts )

[Perl] remove singleton

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/php/PhpModelTest.java

Signed-off-by: Vincent Giersch <vincent@giersch.fr>
Similar to #4201 / #4357 but in PHP: escape the enum variables names + use standard escape function.

[PHP] Eescape reserved words in enum variables names

---

modules/swagger-codegen/src/main/resources/php/ObjectSerializer.mustache
samples/client/petstore-security-test/php/SwaggerClient-php/lib/ObjectSerializer.php
samples/client/petstore/php/SwaggerClient-php/lib/ObjectSerializer.php

Since #4886, not specifying an optional enum value throws an error (not sure how we can add tests for this though...)

PHP: should not check enum value if not unspecified and optional

---

modules/swagger-codegen-maven-plugin/src/main/java/io/swagger/codegen/plugin/CodeGenMojo.java

System properties were retained across multiple successive executions,
resulting in unpredictable behavior. Property values are now properly reset
to their original value after plugin execution.
See #5350

Fix environment variable support in successive Maven plugin executions

---

modules/swagger-codegen-maven-plugin/README.md
modules/swagger-codegen-maven-plugin/src/main/java/io/swagger/codegen/plugin/CodeGenMojo.java

The execution is skipped if either the `codegen.skip` property or the `<skip>`
configuration parameter is set. This is consistent with how many other Maven
plugins, such as maven-exec-plugin and maven-clean-plugin, handle this.

Add option to skip Maven plugin execution

---

modules/swagger-codegen/src/main/resources/Javascript/ApiClient.mustache
samples/client/petstore/javascript-promise/src/ApiClient.js
samples/client/petstore/javascript/src/ApiClient.js

[JavaScript] Fix for issue #5358: Regression in 2.3 using `multi` parameters (Cannot read property 'buildCollectionParam' of undefined)

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java
samples/client/petstore/csharp/SwaggerClient.v5/src/IO.Swagger/Api/FakeApi.cs
samples/client/petstore/csharp/SwaggerClient.v5/src/IO.Swagger/Api/PetApi.cs
samples/client/petstore/csharp/SwaggerClient.v5/src/IO.Swagger/Api/StoreApi.cs
samples/client/petstore/csharp/SwaggerClient.v5/src/IO.Swagger/Api/UserApi.cs
samples/client/petstore/csharp/SwaggerClient.v5/src/IO.Swagger/Client/ApiClient.cs
samples/client/petstore/csharp/SwaggerClient.v5/src/IO.Swagger/Client/ApiException.cs

Fixes #5367.
A typo is fixed in modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java to correctly support async and UWP when generating .NET clients for `netstandard` target framework.

Fixes 5367. Async support is enabled for .NET netstandard API clients

---

modules/swagger-codegen/src/main/resources/cpprest/apiclient-header.mustache
modules/swagger-codegen/src/main/resources/cpprest/apiclient-source.mustache
modules/swagger-codegen/src/main/resources/cpprest/modelbase-header.mustache
modules/swagger-codegen/src/main/resources/cpprest/modelbase-source.mustache

I had the float conversion for cpprest client API template.

Add float conversion for cpprest client api template.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenParameter.java

One line fix for bug in CodegenParameter copy method.  This `isPrimitiveType` value was not being copied to the new object.

Fix copy method of CodegenParameter to copy isPrimitiveType

---

modules/swagger-codegen/src/main/resources/typescript-angular/apis.mustache
modules/swagger-codegen/src/main/resources/typescript-angular/models.mustache
modules/swagger-codegen/src/main/resources/typescript-angular2/models.mustache
samples/client/petstore-security-test/typescript-angular/api/api.ts
samples/client/petstore/typescript-angular/api/api.ts
samples/client/petstore/typescript-angular2/npm/README.md
samples/client/petstore/typescript-angular2/npm/package.json

- Fixes #5136 
- Same changes as in #5131 but for ts-angular.
- Additionally: changed models.mustache of ts-angular2
- Recreated ts-angular & ts-angular2 samples

[TypeScript] fix class filename in import/export

---

modules/swagger-codegen/src/main/resources/swift3/AlamofireImplementations.mustache
modules/swagger-codegen/src/main/resources/swift3/Models.mustache
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/FakeAPI.swift
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/AlamofireImplementations.swift
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/Models.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs/FakeAPI.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/AlamofireImplementations.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/Models.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs/FakeAPI.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/AlamofireImplementations.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/Models.swift

I was having problems with classes inheriting from other classes, fields defined in parent classes were `nil`. I fixed it by calling the parent's decoder in the child's decoder and passing the child's instance.

fix(swift3): decoders call parents decoders too

---

modules/swagger-codegen/src/main/resources/swift3/AlamofireImplementations.mustache
modules/swagger-codegen/src/main/resources/swift3/Models.mustache
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/FakeAPI.swift
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/Fake_classname_tags123API.swift
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/AlamofireImplementations.swift
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/Models.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs/FakeAPI.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs/Fake_classname_tags123API.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/AlamofireImplementations.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/Models.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs/FakeAPI.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs/Fake_classname_tags123API.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/AlamofireImplementations.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/Models.swift

This is the same than https://github.com/swagger-api/swagger-codegen/pull/5369 and https://github.com/swagger-api/swagger-codegen/pull/5416, but against branch `2.3.0`.

[2.3.0] fix(swift3): decoders call parents decoders too

---

modules/swagger-codegen/src/main/resources/swift3/Models.mustache
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/Models.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/Models.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/Models.swift

My last commit (https://github.com/swagger-api/swagger-codegen/commit/b1a39ac820fa1e3920b1ff826797f6fd354921fe) had introduced an infinite loop if you were using `discriminator` *and* returning a class that has a parent in one of your routes. By ensuring the instance is `nil` before "going down" in the tree, we ensure that we're not already "going up", thus removing the infinite loop.
In the petstore, add a route `/cats` returning `Cat` elements only. It will first go through the `Cat` decoder, that will call the `Animal` decoder, which has a discriminator on `className` and thus will call the `Cat` decoder again...

fix(swift3): fix infinite loop with inheritance and check if parent decoder exists

---

modules/swagger-codegen/src/main/resources/cpprest/apiclient-source.mustache

My rails server try to parse a json body because content-type was application/json in the header but the cpprest client generate build a formdata body.
I corrected this by adding the generation of a body in json in case the content type is "application / json".

Cpprest json body for application/json content-type

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java
modules/swagger-codegen/src/main/resources/php/model_generic.mustache
samples/client/petstore/php/SwaggerClient-php/lib/Model/EnumArrays.php
samples/client/petstore/php/SwaggerClient-php/lib/Model/EnumTest.php
samples/client/petstore/php/SwaggerClient-php/lib/Model/MapTest.php
samples/client/petstore/php/SwaggerClient-php/lib/Model/Order.php
samples/client/petstore/php/SwaggerClient-php/lib/Model/Pet.php

- Fix a bug for repeating `JUST_SYMBOL_` constants (reuse `getSymbolName()`)
- Reuse `get...AllowableValues()` for enum values
- Remove extra brackets around `array_diff` and `!in_array`

PHP: Reuse allowed Enum values

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngular2ClientCodegen.java
modules/swagger-codegen/src/main/resources/typescript-angular2/api.service.mustache
modules/swagger-codegen/src/test/java/io/swagger/codegen/typescript/typescriptangular2/TypeScriptAngular2ModelTest.java

The current 2.3.0 typescript-angular2 treats both Swagger dates and datetimes as Javascript `Date`s and sends their `toISOString()` over the wire. This is reasonable behavior for datetimes, but for dates, which don't contain times, the generated client will send across meaningless times, in violation of the Swagger spec and breaking APIs that are expecting to receive dates.
Javascript/TypeScript does not have a native way to store dates (the native `Date` object only stores datetimes), so an ISO string (e.g. `"2017-04-19"` is the best way to represent this data.
This PR changes the type to `string` for dates, but leaves datetimes as `Date`s.
Feedback welcome and let me know if there's anything I can do to help.

typescript-angular2: treating dates as strings (datetimes are still Dates)

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java

This PR fix possible null pointer dereference found with static analysis.

Fix Possible null pointer dereference

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java
modules/swagger-codegen/src/main/resources/Java/pojo.mustache

Some valid json expressions within a swagger.json file result in uncompilable Java code.
How to test:
Use [this pom.xml](https://gist.github.com/spr3nk3ls/d7021930cc42941d413ef120b710beb9) and [this swagger.json](https://gist.github.com/spr3nk3ls/f165f0f19656a9e1ef8bf0f900f5067a) to generate an example swagger API client in Java.
Expected: the code generated results in compilable Java.
Result: the resulting Java does not compile, because expressions like `"example": "[\"RABO23124NL\",\"RABO12345NL\"]",` and `"example": "\\\"[A-Z.]{1,10}\\",` are escaped incorrectly.
I was unable to fix my original PR (https://github.com/swagger-api/swagger-codegen/pull/5234), so I created this one instead. Suggestions made on the original PR have been processed in this one.

Fixes in escaping when generating Java from swagger.json (2)

---

modules/swagger-codegen/src/main/resources/typescript-angular2/api.service.mustache
samples/client/petstore/typescript-angular2/default/api/pet.service.ts
samples/client/petstore/typescript-angular2/npm/README.md
samples/client/petstore/typescript-angular2/npm/api/pet.service.ts
samples/client/petstore/typescript-angular2/npm/package.json

toString() seems to be removed when syncing changes from master to 2.3.0. Adding it back via this PR.

[TypeScript][Angular2] Add "toString()" to form parameters

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java

Fix NullPointerException for info.version on Javascript client codegen

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenOperation.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/DefaultGeneratorTest.java

Adds the ability to reference the tag name, description, external docs, and vendor extensions in Mustache templates during codegen for tags.
Filed against the 2.3.0 branch since it is a breaking change.
I did not use the method Swagger#getTag that was introduced as part of #1073 since it requires updating to swagger core version 1.5.13 which causes other regressions. 
Closes #1073
Related #5074

Enable Tag details to be used in templates

---

circle.yml
modules/swagger-codegen/src/test/java/io/swagger/codegen/javaPlayFramework/JavaPlayFrameworkOptionsTest.java
pom.xml
pom.xml.circleci
samples/server/petstore/scalatra/pom.xml

Update pom.xml for CircleCI to test java-related projects only

Update pom.xml for CircleCI to test java-related projects only

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SpringCodegen.java
modules/swagger-codegen/src/main/resources/JavaSpring/api.mustache
modules/swagger-codegen/src/main/resources/JavaSpring/apiController.mustache
pom.xml
pom.xml.circleci
samples/client/petstore/spring-cloud/src/main/java/io/swagger/api/PetApi.java
samples/client/petstore/spring-cloud/src/main/java/io/swagger/api/StoreApi.java
samples/client/petstore/spring-cloud/src/main/java/io/swagger/api/UserApi.java
samples/client/petstore/spring-cloud/src/main/java/io/swagger/model/Category.java
samples/client/petstore/spring-cloud/src/main/java/io/swagger/model/ModelApiResponse.java
samples/client/petstore/spring-cloud/src/main/java/io/swagger/model/Order.java
samples/client/petstore/spring-cloud/src/main/java/io/swagger/model/Pet.java
samples/client/petstore/spring-cloud/src/main/java/io/swagger/model/Tag.java
samples/client/petstore/spring-cloud/src/main/java/io/swagger/model/User.java

To fix https://github.com/swagger-api/swagger-codegen/issues/5432

[Java][Spring] Fix spring cloud client due to enhancement in adding server example responses.

---

modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache
modules/swagger-codegen/src/main/resources/typescript-angular2/configuration.mustache
samples/client/petstore/typescript-angular2/default/api/PetApi.ts
samples/client/petstore/typescript-angular2/default/api/StoreApi.ts
samples/client/petstore/typescript-angular2/default/api/UserApi.ts
samples/client/petstore/typescript-angular2/default/configuration.ts
samples/client/petstore/typescript-angular2/npm/README.md
samples/client/petstore/typescript-angular2/npm/api/PetApi.ts
samples/client/petstore/typescript-angular2/npm/api/StoreApi.ts
samples/client/petstore/typescript-angular2/npm/api/UserApi.ts
samples/client/petstore/typescript-angular2/npm/configuration.ts
samples/client/petstore/typescript-angular2/npm/package.json

#5374 
1. `withCredentials` in Request is `false` default
2. if want to set the `withCredentials` as `true` (for CORS request),
instance `Configuration` object and set the `withCredentials` as `true`.

add withCredentials to the configuration

---

modules/swagger-codegen/src/main/resources/python/api.mustache
samples/client/petstore-security-test/python/petstore_api/apis/fake_api.py
samples/client/petstore/python/petstore_api/apis/fake_api.py
samples/client/petstore/python/petstore_api/apis/pet_api.py
samples/client/petstore/python/petstore_api/apis/store_api.py
samples/client/petstore/python/petstore_api/apis/user_api.py

query_params is a list of tuple, so defined it as a list by
default instead of a dict.
This fix below issue on the client side.
Traceback (most recent call last):
File "test.py", line 13, in <module>
api_response = api_instance.seek("the")
File "python-client/swagger_client/apis/seek_api.py", line 168, in seek
(data) = self.seek_with_http_info(recherche, **kwargs)
File "python-client/swagger_client/apis/seek_api.py", line 245, in seek_with_http_info
collection_formats=collection_formats)
File "python-client/swagger_client/api_client.py", line 323, in call_api
_return_http_data_only, collection_formats, _preload_content, _request_timeout)
File "python-client/swagger_client/api_client.py", line 135, in __call_api
self.update_params_for_auth(header_params, query_params, auth_settings)
File …

[Python]: correct query_params type.

---

modules/swagger-codegen/src/main/resources/JavaJaxRS/jacksonJsonProvider.mustache

This is related, at least in spirit, to this issue: https://github.com/swagger-api/swagger-codegen/issues/2874

For dateLibrary=java8, remove JODA references

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java

The hasMore field of the global authMethods was broken due to sorting after
setting that field. The sort order for per-operation authMethods was not
guaranteed to be consistent across runs because it didn't do sorting. This
change fixes those issues by always sorting and setting the hasMore field
post-sort.
Adopted code from DefaultGenerator and AkkaScalaClientCodegen to consistently sort the authMethods dictionaries and set the hasMore field.
Fix for #5515

Fix hasMore field and order consistency of authMethods

---

modules/swagger-codegen/src/main/resources/Java/typeInfoAnnotation.mustache

This fixes a typo in the mustache file for discriminator types. It is generating a class name, so it should use the {{classname}} field, not the {{name}} field. Most of the time, these two are the same, but in cases where the model name in the spec file is lower cased, they are different. This edge case doesn't show up in the existing testing endpoint, so the samples are unaffected.

Fix class name in discriminator subtypes

---

modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/SwaggerCodegen.java
modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/cmd/Validate.java
modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/cmd/ValidateException.java

- Issue #5466 
- Enhancement to add `validate` option to swagger-codegen-cli
- Using swagger-parser's `SwaggerDeserializationResult` according to @wing328 advice
- If this basic concept is OK, I will add some tests for this enhancement, so please let me know.
```shell
$ java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar validate -i valid.json
Validating spec file (valid.json)
```
```shell
$ java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar validate -i invalid.json
Validating spec file (invalid.json)
attribute infa is unexpected
attribute info is missing
Exception in thread "main" io.swagger.codegen.cmd.ValidateException
at io.swagger.codegen.cmd.Validate.run(Validate.java:60)
at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:43)
``` …

Add validate option to swagger-codegen-cli (Issue #5466)

---

bin/csharp-petstore-net-standard.sh
bin/csharp-petstore-netcore-project.sh
bin/ruby-petstore.sh
bin/typescript-petstore-npm.json

- typo in csharp-petstore-net-standard.sh (Stanard -> Standard)
- non-existent config file name name in csharp-petstore-netcore-project.sh
- non-existing config file name in ruby-petstore.sh
- snapshot versioning in typescript-petstore-npm.json causes
non-deterministic output
In trying to recreate some of the samples, I ran into a few issues with the scripts that produced incorrect output. Mostly these were typos or references to non-existent (probably old) config files.
I'm working on re-generating the samples with new testing endpoints, so these fixes will help make that process go more smoothly.

Minor fixes to sample generation scripts

---

modules/swagger-codegen/src/main/resources/ruby/api.mustache
modules/swagger-codegen/src/main/resources/ruby/configuration.mustache
modules/swagger-codegen/src/main/resources/ruby/gemspec.mustache
samples/client/petstore/ruby/Gemfile.lock
samples/client/petstore/ruby/lib/petstore/api/fake_api.rb
samples/client/petstore/ruby/lib/petstore/api/pet_api.rb
samples/client/petstore/ruby/lib/petstore/api/store_api.rb
samples/client/petstore/ruby/lib/petstore/api/user_api.rb
samples/client/petstore/ruby/lib/petstore/configuration.rb
samples/client/petstore/ruby/petstore.gemspec

- Add an option in configuration object to skip client validation so that the Ruby API client can be used to perform integration tests with the RESTful backend.
- update dependency "autotest-fsevent" to 0.2.12 to resolve an issue in Mac OS

add option to skip client side validation in ruby client

---

modules/swagger-codegen/src/main/resources/JavaSpring/pojo.mustache

Applies the same fix as #5247 to avoid invalid escaping of the attribute
example within `ApiModelProperty`.
Resolves #5534
Resolves issue described within #5534  for JavaSpring

Bugfix: JavaSpring pojo example escape

---

modules/swagger-codegen/src/main/resources/CsharpDotNet2/README.mustache
modules/swagger-codegen/src/main/resources/CsharpDotNet2/api_doc.mustache
modules/swagger-codegen/src/main/resources/JavaInflector/pojo.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf-cdi/pojo.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/pojo.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/pojo.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/resteasy/eap/pojo.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/resteasy/pojo.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/spec/pojo.mustache
modules/swagger-codegen/src/main/resources/JavaSpring/pojo.mustache
modules/swagger-codegen/src/main/resources/MSF4J/pojo.mustache
modules/swagger-codegen/src/main/resources/csharp/README.mustache
modules/swagger-codegen/src/main/resources/csharp/api_doc.mustache
modules/swagger-codegen/src/main/resources/htmlDocs2/sample_csharp.mustache
modules/swagger-codegen/src/main/resources/undertow/pojo.mustache

Similar to https://github.com/swagger-api/swagger-codegen/pull/5536, this PR aims to clean up the remaining incorrect use of {{example}} with {{{example}}} instead.

Use original (unescaped) value of "example"

---

modules/swagger-codegen/src/main/resources/Java/libraries/feign/build.gradle.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/build.gradle.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit/build.gradle.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit/pom.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/build.gradle.mustache
modules/swagger-codegen/src/main/resources/android/build.mustache
modules/swagger-codegen/src/main/resources/android/libraries/volley/build.mustache
modules/swagger-codegen/src/main/resources/android/libraries/volley/pom.mustache
modules/swagger-codegen/src/main/resources/android/pom.mustache
samples/client/petstore/android/volley/pom.xml

Use `java8` mustache tag to determine Java version in the output.

Add switch in mustache templates to determine Java8 or Java7

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java
modules/swagger-codegen/src/main/resources/csharp/api.mustache
modules/swagger-codegen/src/main/resources/csharp/modelGeneric.mustache
samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/Api/FakeApi.cs
samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/Api/PetApi.cs
samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/Api/StoreApi.cs
samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/Api/UserApi.cs
samples/client/petstore/csharp/SwaggerClientNetStandard/IO.Swagger.sln
samples/client/petstore/csharp/SwaggerClientNetStandard/README.md
samples/client/petstore/csharp/SwaggerClientNetStandard/docs/FakeApi.md
samples/client/petstore/csharp/SwaggerClientNetStandard/docs/PetApi.md
samples/client/petstore/csharp/SwaggerClientNetStandard/docs/StoreApi.md
samples/client/petstore/csharp/SwaggerClientNetStandard/docs/UserApi.md
samples/client/petstore/csharp/SwaggerClientNetStandard/src/IO.Swagger/Api/FakeApi.cs
samples/client/petstore/csharp/SwaggerClientNetStandard/src/IO.Swagger/Api/PetApi.cs
samples/client/petstore/csharp/SwaggerClientNetStandard/src/IO.Swagger/Api/StoreApi.cs
samples/client/petstore/csharp/SwaggerClientNetStandard/src/IO.Swagger/Api/UserApi.cs
samples/client/petstore/csharp/SwaggerClientNetStandard/src/IO.Swagger/Client/ApiClient.cs
samples/client/petstore/csharp/SwaggerClientNetStandard/src/IO.Swagger/Client/ApiException.cs
samples/client/petstore/csharp/SwaggerClientNetStandard/src/IO.Swagger/IO.Swagger.csproj
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/src/IO.Swagger/Api/FakeApi.cs
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/src/IO.Swagger/Api/PetApi.cs
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/src/IO.Swagger/Api/StoreApi.cs
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/src/IO.Swagger/Api/UserApi.cs

For https://github.com/swagger-api/swagger-codegen/issues/5122
This PR also removes some trailing spaces in the api.mustache (C#)

[C#] Add 'validatable' flag for .net 3.5 framework

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java

see #4020
There was confusion about the usage of `invokerPackage` vs `packageName`. It appears only Java and Flash generators use `invokerPackage` while all others use `packageName`.
This PR warns on usage of `invokerPackage` and offers the correct property as `packageName`.

[csharp] warn on use of invokerPackage

---

modules/swagger-codegen/src/main/resources/Java/beanValidation.mustache
modules/swagger-codegen/src/main/resources/Java/model.mustache

#5393:
https://github.com/cakemail/swagger-codegen/blob/07f066a20350302429c133f2febfcb58632aa56a/modules/swagger-codegen/src/main/resources/JavaSpring/beanValidation.mustache
`the change below was added into JavaSpring language but it was not added into Java language.`
`so I  have created the PR  to support @Valid for java language to implement` #5498
`[JAVA] enhance beanvalidation with adding @Valid`

add @Valid annotion for bean-validation

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CsharpDotNet2ClientCodegen.java
samples/client/petstore/csharp-dotnet2/SwaggerClientTest/Lib/SwaggerClient/docs/ApiResponse.md
samples/client/petstore/csharp-dotnet2/SwaggerClientTest/Lib/SwaggerClient/docs/Category.md
samples/client/petstore/csharp-dotnet2/SwaggerClientTest/Lib/SwaggerClient/docs/Order.md
samples/client/petstore/csharp-dotnet2/SwaggerClientTest/Lib/SwaggerClient/docs/Pet.md
samples/client/petstore/csharp-dotnet2/SwaggerClientTest/Lib/SwaggerClient/docs/StoreApi.md
samples/client/petstore/csharp-dotnet2/SwaggerClientTest/Lib/SwaggerClient/docs/Tag.md
samples/client/petstore/csharp-dotnet2/SwaggerClientTest/Lib/SwaggerClient/docs/User.md
samples/client/petstore/csharp-dotnet2/SwaggerClientTest/Lib/SwaggerClient/src/main/CsharpDotNet2/IO/Swagger/Api/StoreApi.cs

see #5138
This is the start of consolidation efforts of C# 2.0 to the greater C# client generator code.
There is further discussion in the issue related to maintainability of combining C# 2.0 code into the newer code. For example, current users of both generators have the option to extend built-in templates to enhance the generator for their use case. This means users of `CsharpDotNet2` as well as `csharp` may have a file called `api.mustache`. The `CsharpDotNet2` version of the file is extremely basic because C# 2.0 doesn't support many of the advanced features that C# 3.0 and higher support. One option is to introduce extensive conditions into the logicless mustache template, which I think would reduce maintainability. Another option is to rename the file from `api.mustache` to …

[csharp2] Extend generator from AbstractCSharpCodegen

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/java/JavaModelTest.java

The Swagger/OpenAPI spec (2.0 at least) does not have a way to give a "name" to an element in an array property.  Currently, the generator confers the name of the array property onto the property for an array item.  This can lead to awkward/unnatural method names for adding or removing an item from an array property.
Consider:
```
properties:
children:
type: array
items:
$ref: "#/definitions/Child"
```
Currently, the CodegenProperty describing an item in the `children` array will also have the name `children`.  For some languages it is common to provide methods to access individual elements of an array property, like add<element>.  For the `children` property above, the natural signature (in Java) for such a method would be:
```
public void addChild(Child child) {
```
But since the item …

Set name for item property from 'x-item-name' annotation if present.

---

modules/swagger-codegen/src/main/resources/php/api.mustache
samples/client/petstore/php/SwaggerClient-php/lib/Api/FakeApi.php

Currently the default value from the spec is ignored in the generated code. This change makes sure that if there is existing default value for non-required arguments it's added to the signature of the method.

[PHP] Add default value to method signature if present in Swagger spec

---

modules/swagger-codegen/src/main/resources/php/ApiClient.mustache
modules/swagger-codegen/src/main/resources/php/configuration.mustache
samples/client/petstore/php/SwaggerClient-php/lib/ApiClient.php
samples/client/petstore/php/SwaggerClient-php/lib/Configuration.php

This change is to implement PHP client for allowing encoding headers.
https://github.com/swagger-api/swagger-codegen/issues/3365

issue #3365 adding accept encoding for PHP

---

.travis.yml
modules/swagger-codegen/src/main/resources/erlang-server/rebar.config.mustache
pom.xml
samples/server/petstore/erlang-server/pom.xml
samples/server/petstore/erlang-server/priv/swagger.json
samples/server/petstore/erlang-server/rebar.config

This PR is not ready to be merged yet, and opened for receiving comments (RFC).
- (There is no erlang-server related script in `./bin/security/`)
This PR plants CI for erlang-server. A related issue seems to be #3762
This PR tests that the sample compiles, that can be considered a very basic test.
I see the current version of the code generation leaves functions syntactically invalid - i.e. no body at all rather than e.g. raising a runtime error - hence the code will not compile. I suggest - and I plan to implement if I find time - the way forward is populating the (generated) body with `error(unimplemented)` and the "correct" separator/terminator i.e. `;` or `.`. Any comments?

[Erlang] Plant CI for server

---

modules/swagger-codegen/src/main/resources/go/api_client.mustache
samples/client/petstore-security-test/go/api_client.go
samples/client/petstore/go/go-petstore/api_client.go
samples/client/petstore/go/pom.xml

Fixes #5578
Users will have to run `go get ./...` again after generating the golang client, as the dependency now tracks the `resty` stable release instead of the HEAD of resty's repository master.

Modifying resty dependency to use stable release instead of HEAD

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngular2ClientCodegen.java
modules/swagger-codegen/src/main/resources/typescript-angular2/variables.mustache
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/TypeScriptAngular2ClientOptionsProvider.java
samples/client/petstore-security-test/typescript-angular2/api/FakeApi.ts
samples/client/petstore-security-test/typescript-angular2/configuration.ts
samples/client/petstore-security-test/typescript-angular2/variables.ts
samples/client/petstore/typescript-angular2/default/api/PetApi.ts
samples/client/petstore/typescript-angular2/default/variables.ts
samples/client/petstore/typescript-angular2/npm/README.md
samples/client/petstore/typescript-angular2/npm/api/PetApi.ts
samples/client/petstore/typescript-angular2/npm/package.json
samples/client/petstore/typescript-angular2/npm/variables.ts

- Issue #5565
- Change `OpaqueToken` to `InjectionToken<string>`
- Provide `useOpaqueToken` option for backward compatibility

[typescript-angular2] change OpaqueToken to InjectionToken<string> (Issue #5565)

---

docker-entrypoint.sh

Hi,
Thanks for developing and maintaining Swagger!
Yesterday I found that I could not run "validate" in Docker, so I made a trivial change to allow the "validate" and "version" commands in the docker-environment shell script.  Then it occured to me that it would not be so hard to check if the CLI can handle an arbitrary command, and then a couple of unquoted shell variables caught my eye.
Thanks in advance, and keep up the great work!
G'luck,
Peter

Run all the CLI commands in the Docker environment

---

modules/swagger-codegen/src/main/resources/swift3/AlamofireImplementations.mustache
modules/swagger-codegen/src/main/resources/swift3/Extensions.mustache
modules/swagger-codegen/src/main/resources/swift3/Models.mustache
modules/swagger-codegen/src/main/resources/swift3/api.mustache
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/FakeAPI.swift
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/AlamofireImplementations.swift
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/Extensions.swift
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/Models.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs/FakeAPI.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/AlamofireImplementations.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/Extensions.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/Models.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs/FakeAPI.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs/PetAPI.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs/StoreAPI.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/AlamofireImplementations.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/Extensions.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/Models.swift

Added code to templates to ensure correct generation of code for Swift3 so that it builds on both Apple platforms and Linux. Fixed a bug in the Model decoders that prevented code from building for Linux.
Currently the templates for AlamofireImplementations.swift, Extensions.swift and DefaultAPI.swift assume that the files are being compiled in the context of an iOS, macOS, watchOS or tvOS application, and consequently that Foundation has already been imported. This is not true in the case of applications being developed for Swift on Linux. Adding 
~~~~
import Foundation
~~~~
to the top of these files has no effect on Apple platforms, but enables the files to compile without errors in applications targeted for Linux. Additionally when files are compiled for Linux there is a limitation in …

Added code to templates to ensure correct generation of code for Swift3

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/utils/ImplementationVersion.java

see #2183
This adds a new file at `.swagger/VERSION` which holds the swagger-codegen.jar's implementation version.

[generator] Adds a .swagger/VERSION file for all generators

---

modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache
modules/swagger-codegen/src/main/resources/csharp/Project.mustache
samples/client/petstore-security-test/csharp/SwaggerClient/src/IO.Swagger/Api/FakeApi.cs
samples/client/petstore-security-test/csharp/SwaggerClient/src/IO.Swagger/IO.Swagger.csproj
samples/client/petstore-security-test/csharp/SwaggerClient/src/IO.Swagger/Model/ModelReturn.cs
samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/IO.Swagger.csproj
samples/client/petstore/csharp/SwaggerClientNetStandard/src/IO.Swagger/Client/ApiClient.cs
samples/client/petstore/csharp/SwaggerClientNetStandard/src/IO.Swagger/IO.Swagger.csproj
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/src/IO.Swagger/IO.Swagger.csproj

This is a non-breaking change.
see #5589 
As a side node: due to including `**/*.cs` as files to compile, there have always been some files of the `obj\` directory which where included.
This is fixed due to only include all files of the generated root directories, thus excluding the `obj\` directory.

[csharp] fixes for netstandard (json serializing and project files)

---

modules/swagger-codegen/src/main/resources/csharp/Project.mustache
modules/swagger-codegen/src/main/resources/csharp/TestProject.mustache

This fixes the glob pattern to remove hard-coded namespaces, and exclude the obj folder.
Introduced in #5590, the following change to the project file was made:
```diff
-     <Compile Include="**\*.cs"/>
+     <Compile Include="Api\**\*.cs"/>
+     <Compile Include="Client\**\*.cs"/>
+     <Compile Include="Model\**\*.cs"/>
+     <Compile Include="Properties\**\*.cs"/>
```
This change was made to account for Xamarin also including `obj\*.cs`. See #5590 for more discussion.
The change causes apiPackage and modelPackage additional properties to generated code, but be excluded when code is loaded in an IDE.
To compare with master:
* run `\rm -rf samples/client/petstore/csharp/SwaggerClient/`. This is necessary, otherwise Api and Model folders from previous sample generation will remain.
* …

[csharp] Fix project glob pattern

---

modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
samples/client/petstore-security-test/java/okhttp-gson/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/ApiClient.java

Make `keyManagers` a configurable parameter for generated clients.
This enables client-side certificate based authentication.
`keyManagers` was basically unused in the current template.

[Java] Add custom SSL KeyManagers for okhttp-gson Java clients

---

modules/swagger-codegen/src/main/resources/typescript-angular2/api.module.mustache
samples/client/petstore/typescript-angular2/default/api.module.ts
samples/client/petstore/typescript-angular2/npm/api.module.ts

With this change, users providing custom configuration must provide an exported Configuration factory, rather than just an object. This is needed to be Angular AoT compatible.
Example use:
```
import * as api from '../api';
/** Configuration settings for the backend API */
export function backendConfigurationFactory(): api.Configuration {
return new api.Configuration({basePath: '/api'});
}
@NgModule({
imports: [api.ApiModule.forConfig(backendConfigurationFactory)],
```

Fix for issue #5349.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java

Fixes issue #5615 
Java client code generation
Property with name 'null' does not lead to corrupt java code any more

#5615 [Java] recognize 'null' as a reserved keyword

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/java/AbstractJavaCodegenTest.java

Fixing the issue that the Java generator was using the auto-generated model classes when generating the client API stub, ignoring the `--import-mappings` parameters. Added two unit tests to ensure it is fixed and it won't regress.
Seems related to #2502, despite being related to the client generation.

Fixing import-mappings and using it when generating API stub. #2248

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/GoClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/GoServerCodegen.java
modules/swagger-codegen/src/main/resources/go/model.mustache
samples/client/petstore/go/go-petstore/enum_class.go
samples/client/petstore/go/go-petstore/outer_enum.go

Fixes #4459
Adding enum generation support for golang. After some investigation, it turns out the missing key to actually getting the enum value support for the mustache fields was to call `postProcessModelsEnum()` before returning the `objs` result in the client-generator's `postProcessModels()` function.
Derived from #5631.
@wing328 
@antihax

Adding enum generation support for golang client

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AndroidClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FlaskConnexionCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/GoClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/GoServerCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java

Similar to https://github.com/swagger-api/swagger-codegen/pull/5617, we will add null/nil/none as reserved keyword to a few generators.

Add null/nil as reserved keyword in some generators

---

modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
samples/client/petstore-security-test/java/okhttp-gson/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/ApiClient.java

Extract out a method that will give you a `Request` object from existing `buildCall` call, useful for generating WebSockets requests.

[Java] Extract out a new helper method from okhttp clients

---

modules/swagger-codegen/src/main/resources/Java/ApiClient.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/feign/ApiClient.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/JSON.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/resteasy/JSON.mustache
samples/client/petstore/java/feign/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/jersey1/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/jersey2-java6/src/main/java/io/swagger/client/JSON.java
samples/client/petstore/java/jersey2-java8/src/main/java/io/swagger/client/JSON.java
samples/client/petstore/java/jersey2-java8/src/test/java/io/swagger/client/ConfigurationTest.java
samples/client/petstore/java/jersey2-java8/src/test/java/io/swagger/client/api/PetApiTest.java
samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/JSON.java
samples/client/petstore/java/resteasy/src/main/java/io/swagger/client/JSON.java

With this change, Jackson does not fail even if it doesn't recognize a
discriminator type name. This is helpful when upgrading a microservice with
a new subtype while keeping compatibility with its old clients. The instance
is returned as null instead of throwing an exception deep in the feign
framework, allowing clients to gracefully degrade.
This is a fix for #5596. It disables the Jackson FAIL_ON_INVALID_SUBTYPE deserialization feature so that unknown discriminator subtypes return null instead of throwing an exception.

Disable Jackson FAIL_ON_INVALID_SUBTYPE in feign

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java

When generating typescript, the typescript classes must be in the right order, classes must be defined before used, especially subclasses must be defined after there superclasses. If not done correctly the typescript file will compile without errors but a runtime error will occure.
This pull requests corrects the order of classes when using inheritance in the style of swagger 2.0 (see https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#composition-and-inheritance-polymorphism) and makes sure that superclasses are defined before subclasses in the generate typescript
[simple-api.yaml.txt](https://github.com/swagger-api/swagger-codegen/files/469359/simple-api.yaml.txt)
Example: 
definitions:
SuperClass:
type: object
discriminator: ctype
properties:
field1:
type: string …

[Typescript] Fix order of generated classes for typescript-node

---

modules/swagger-codegen-maven-plugin/src/main/java/io/swagger/codegen/plugin/CodeGenMojo.java

Converting import-mappings to a list and moving it outside of `configOptions`, but still keeping it backwards compatible (and still as a comma-separated string). Fixes #5383 
This adds support to having configuration like this:
```xml
<configuration>
<importMappings>
<param>json_mymodel=com.mypackage.MyModel</param>
<param>json_anothermodel=com.mypackage.AnotherModel</param>
</importMappings>
</configuration>
```

Moving import-mappings out of configOptions and converting it into a list, rather than being a comma-separated string.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenResponse.java

In PHP templates (and certainly others), an isWildcard method exists to render a default proposition in switch list.
But the corresponding method was removed inconsistently from the CodegenResponse class.
So I make this PR.

Fixed missing isWildcard method used in templates

---

docker-entrypoint.sh
run-in-docker.sh

This change uses the [official maven docker image's method](https://github.com/carlossg/docker-maven#running-as-non-root) to set the user in the docker container to the same user who invokes the `run-in-docker.sh` script. The outcome of this is that all the artefacts generated by the container (m2 cache in home dir, target directories, output client and server code, etc) are owned by the expected user instead of root.
Apologies: this is a re-roll of #5700 now based on master instead of 2.3.0.

[docker] Run as non-root user, fixes ownership of generated artefacts

---

modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache
samples/client/petstore/typescript-angular2/default/api/PetApi.ts
samples/client/petstore/typescript-angular2/default/api/StoreApi.ts
samples/client/petstore/typescript-angular2/default/api/UserApi.ts
samples/client/petstore/typescript-angular2/npm/api/PetApi.ts
samples/client/petstore/typescript-angular2/npm/api/StoreApi.ts
samples/client/petstore/typescript-angular2/npm/api/UserApi.ts

Move the tslint comment that disables `no-unused-variable` to before the
import statements, to avoid "Unused import" warnings

[typescript-angular2] Avoid tslint "Unused import" warnings

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractTypeScriptClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngular2ClientCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/typescript/fetch/TypeScriptFetchModelTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/typescript/typescriptangular/TypeScriptAngularModelTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/typescript/typescriptnode/TypeScriptNodeModelTest.java

The 2.3.0 typescript clients all treat Swagger dates as Javascript Date types. This would be appropriate for date-times, but for dates, which lack times, this leads to meaningless times being passed to an API which expects only dates, in violation of the Swagger spec.
A better datetype for Swagger dates, since Javascript does not have a native concept of dates, is simply ISO strings (e.g `2017-04-30`). The generated clients should therefore use strings for dates, while continuing to use Dates for datetimes.
In #5417 I submitted a change that fixed this issue for the typescript-angular2 client. @wing328 merged it but suggested that we fix this for the other Typescript clients as well, to ensure consistency. Therefore, I'm submitting this PR, which moves the typing to the …

ensuring that swagger dates are treated as strings for all typescript clients

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SpringCodegen.java
modules/swagger-codegen/src/main/resources/JavaSpring/api.mustache
samples/client/petstore/spring-cloud/src/main/java/io/swagger/api/PetApi.java
samples/client/petstore/spring-cloud/src/main/java/io/swagger/api/StoreApi.java
samples/client/petstore/spring-cloud/src/main/java/io/swagger/api/UserApi.java
samples/client/petstore/spring-stubs/src/main/java/io/swagger/api/PetApi.java
samples/client/petstore/spring-stubs/src/main/java/io/swagger/api/StoreApi.java
samples/client/petstore/spring-stubs/src/main/java/io/swagger/api/UserApi.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/api/PetApi.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/api/StoreApi.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/api/UserApi.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/PetApi.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/StoreApi.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/UserApi.java
samples/server/petstore/springboot-beanvalidation/pom.xml
samples/server/petstore/springboot-beanvalidation/src/main/java/io/swagger/api/PetApi.java
samples/server/petstore/springboot-beanvalidation/src/main/java/io/swagger/api/StoreApi.java
samples/server/petstore/springboot-beanvalidation/src/main/java/io/swagger/api/UserApi.java
samples/server/petstore/springboot-delegate-j8/src/main/java/io/swagger/api/PetApi.java
samples/server/petstore/springboot-delegate-j8/src/main/java/io/swagger/api/StoreApi.java
samples/server/petstore/springboot-delegate-j8/src/main/java/io/swagger/api/UserApi.java
samples/server/petstore/springboot-delegate/src/main/java/io/swagger/api/PetApi.java
samples/server/petstore/springboot-delegate/src/main/java/io/swagger/api/StoreApi.java
samples/server/petstore/springboot-delegate/src/main/java/io/swagger/api/UserApi.java
samples/server/petstore/springboot/src/main/java/io/swagger/api/PetApi.java
samples/server/petstore/springboot/src/main/java/io/swagger/api/StoreApi.java
samples/server/petstore/springboot/src/main/java/io/swagger/api/UserApi.java

Fixes the spring java code generator so that the ApiResponse fields are populated correctly
on the controller.
Related to #4693
This yaml:
```yaml
responses:
'200':
description: pet response
schema:
type: array
items:
$ref: '#/definitions/pet'
'400':
description: unexpected error
schema:
$ref: '#/definitions/errorModel'
```
Will now generate this java:
```java
@ApiOperation(value = "", notes = "Returns all pets from the system that the user has access to", response = Pet.class, responseContainer = "List", tags={  })
@ApiResponses(value = { 
@ApiResponse(code = 200, message = "pet response", response = Pet.class),
@ApiResponse(code = 400, message = "unexpected error", response = …
```

Fix spring generated annotations only generating first return type

---

modules/swagger-codegen/src/main/resources/cpprest/model-source.mustache

which was generating code that doesn't compile because of a wrong variable name
I have run the `cpprest-petstore.sh` and everything seems fine. I did not get changes in the generated files which I suspect is the reason this was overlooked in the first place (the relevant part of the template is not used for any generation in the petstore example).

[cpprest] fix cpprest model source mustache template

---

modules/swagger-codegen/src/main/resources/kotlin-client/data_class.mustache
modules/swagger-codegen/src/main/resources/kotlin-client/data_class_opt_var.mustache
modules/swagger-codegen/src/main/resources/kotlin-client/data_class_req_var.mustache
modules/swagger-codegen/src/main/resources/kotlin-client/enum_class.mustache
modules/swagger-codegen/src/main/resources/kotlin-client/model.mustache
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/models/ApiResponse.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/models/Category.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/models/Order.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/models/Pet.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/models/Tag.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/models/User.kt
samples/client/petstore/kotlin/src/test/kotlin/io/swagger/client/functional/EvaluateTest.kt

This updates model generation to support nested enums. Verified that top-level enums were handled correctly by default behavior in DefaultCodegen.
This checks off a couple of todos in #5730, although enum-related tests aren't included in this PR. I'll update the tracking issue to include testing of top-level and nested enums.

[kotlin] Support nested enums in models

---

modules/swagger-codegen/src/main/resources/Javascript/ApiClient.mustache
samples/client/petstore/javascript-es6/src/ApiClient.js
samples/client/petstore/javascript-promise-es6/src/ApiClient.js
samples/client/petstore/javascript-promise/src/ApiClient.js
samples/client/petstore/javascript/src/ApiClient.js

- [v] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [v] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [v] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.
This fixes the bug with empty response body when response schema type is a string.
Here's an example spec snippet:
```
responses:
200:
schema:
type: string
```
I've checked its ruby equivalent to confirm that string …

[javascript] Fix empty response body when schema type is string

---

modules/swagger-codegen/src/main/resources/Javascript-es6/ApiClient.mustache
modules/swagger-codegen/src/main/resources/Javascript/ApiClient.mustache
samples/client/petstore/javascript-es6/src/ApiClient.js
samples/client/petstore/javascript-promise-es6/src/ApiClient.js
samples/client/petstore/javascript-promise/src/ApiClient.js
samples/client/petstore/javascript/src/ApiClient.js

[Electron](https://electron.atom.io/) has `fs` module with correctly working `ReadStream`, but the check `typeof window === 'undefined'` forced it to skip the `ReadStream` check in Electron, while it is completely valid.
P.S. Other than this, the generated client works perfectly in Electron! (Well, I had to workaround an issue in formidable (https://github.com/felixge/node-formidable/issues/337#issuecomment-153408479), which is a dependency of superagent)

[javascript] Fixed `fs` files support for Electron

---

modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/ProgressRequestBody.mustache
samples/client/petstore-security-test/java/okhttp-gson/src/main/java/io/swagger/client/ProgressRequestBody.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/ProgressRequestBody.java

Fixes unexpected end of stream exceptions when using the okhttp-gson library
and making asynchronous calls.
Fixes unexpected end of stream exceptions when using the `okhttp-gson` library
and making asynchronous calls. Fix implemented as proposed by @Megamzero. 
See #4095

Fix issue with buffered sink handling in OkHttp

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Swift3Codegen.java
modules/swagger-codegen/src/main/resources/swift3/Models.mustache
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/Swift3OptionsProvider.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/swift3/Swift3OptionsTest.java
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/Models.swift

This adds a Swift3 option (`lenientTypeCast`) that, when set to true, generates a client JSON decoder that will accept and cast mistyped (by the server) values to their correct (expected by the client, per specification) type, as here:
- String => Bool ("true" instead of true),
- String => Int ("123" instead of 123),
- NSNumber => String (123 instead of "123").
The point is to allow the same client code to handle several server implementations that may (sadly) not be up to spec, or still be "evolving".
Not a perfect/complete solution, not sure if it should be activated along other casts (I think each language/implementation handles this differently), so kept behind an option for Swift3 at this point.
See: #5746.

[Swift3] Set more liberal Swift3 decoder, behind lenientTypeCast option

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/KotlinClientCodegen.java
modules/swagger-codegen/src/main/resources/kotlin-client/api.mustache
modules/swagger-codegen/src/main/resources/kotlin-client/infrastructure/ApiAbstractions.kt.mustache
modules/swagger-codegen/src/main/resources/kotlin-client/infrastructure/ApiClient.kt.mustache
modules/swagger-codegen/src/main/resources/kotlin-client/infrastructure/RequestConfig.kt.mustache
modules/swagger-codegen/src/test/java/io/swagger/codegen/kotlin/KotlinClientCodegenModelTest.java
samples/client/petstore/kotlin/docs/Pet.md
samples/client/petstore/kotlin/docs/PetApi.md
samples/client/petstore/kotlin/docs/UserApi.md
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/apis/PetApi.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/apis/StoreApi.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/apis/UserApi.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/infrastructure/ApiAbstractions.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/infrastructure/RequestConfig.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/models/Pet.kt
samples/client/petstore/kotlin/src/test/kotlin/io/swagger/client/functional/EvaluateTest.kt

Adds "multi" support to collections.
Also changes generic lists (`List<T>`) to arrays. Generic lists and nested
lists can be problematic and require customized json factories. The
previous implement appeared to work because the results in the test were
`LinkedHashMap` with count greater than 0. The functional test has been
updated to force serialization and verify the results.
I've verified multi and csv collection formats against a simplified fake local api (https://github.com/jimschubert/simple-petstore). If you'd like go generate against that project, you can start it locally (`yarn run simple`), then generate against the swagger doc (`http://localhost:3000/swagger.json`) and add the following test:
```
package io.swagger.client.apis
import io.kotlintest.matchers.should
import …
```

[kotlin] support collection format multi

---

modules/swagger-codegen/src/main/resources/JavaJaxRS/api.mustache
samples/server/petstore/jaxrs/jersey2/src/gen/java/io/swagger/api/FakeApi.java
samples/server/petstore/jaxrs/jersey2/src/gen/java/io/swagger/api/PetApi.java
samples/server/petstore/jaxrs/jersey2/src/gen/java/io/swagger/api/StoreApi.java
samples/server/petstore/jaxrs/jersey2/src/gen/java/io/swagger/api/UserApi.java

With this update it is now possible to choose an implementation class for the service delegate. By default the generated service will behave as normal, generating a stub implementation. But now it is also possible to add an init parameter to the the Jersey servlet in web.xml with a class name, eg.:
```
<servlet>
<servlet-name>Swagger Servlet</servlet-name>
<servlet-class>org.glassfish.jersey.servlet.ServletContainer</servlet-class>
... snip ...
<init-param>
<param-name>PetApi.implementation</param-name>
<param-value>org.example.petshop.CustomPetApiService</param-value>
</init-param>
<load-on-startup>1</load-on-startup>
</servlet>
```
The generated PetApi class will now use the ``org.example.petshop.CustomPetApiService`` instead of using ``PetApiServiceFactory`` to make an instance of …

Allow overriding the service delegate

---

modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
samples/client/petstore-security-test/java/okhttp-gson/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/okhttp-gson/src/test/java/io/swagger/client/ApiClientTest.java

Add support for marshalling JSON-Patch based objects (https://tools.ietf.org/html/rfc6902)

Add JSON-patch as a JSON mime-type

---

modules/swagger-codegen/src/main/resources/Java/ApiClient.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
samples/client/petstore/java/jersey1/pom.xml
samples/client/petstore/java/jersey1/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/jersey2-java6/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/jersey2-java8/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/retrofit/pom.xml
samples/client/petstore/java/retrofit2-play24/pom.xml
samples/client/petstore/java/retrofit2/pom.xml
samples/client/petstore/java/retrofit2rx/pom.xml
samples/client/petstore/java/retrofit2rx2/pom.xml

Similar to https://github.com/swagger-api/swagger-codegen/pull/5764, we're adding JSON-patch support to other Java API clients (e.g. jersey2)

[Java] Add JSON-patch support to other Java API clients

---

modules/swagger-codegen/src/main/resources/swift3/APIHelper.mustache
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIHelper.swift
samples/client/petstore/swift3/promisekit/PetstoreClient/Classes/Swaggers/APIHelper.swift
samples/client/petstore/swift3/rxswift/PetstoreClient/Classes/Swaggers/APIHelper.swift

Query items with array values should be returned as a multiple query items, each with a single value, as per the URI specification.

[Swift3] Fix handling of query item with array value

---

modules/swagger-codegen/src/main/resources/Java/typeInfoAnnotation.mustache
modules/swagger-codegen/src/main/resources/JavaInflector/typeInfoAnnotation.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/typeInfoAnnotation.mustache
modules/swagger-codegen/src/main/resources/JavaPlayFramework/typeInfoAnnotation.mustache
modules/swagger-codegen/src/main/resources/JavaSpring/typeInfoAnnotation.mustache

Only ``.mustache`` file changed, I did know where I could add some tests so right now this PR doesn't include any new.
See #5735

[Java] fix Bad class name for JsonSubTypes

---

modules/swagger-codegen/src/main/resources/JavaSpring/api.mustache
modules/swagger-codegen/src/main/resources/JavaSpring/apiController.mustache
samples/client/petstore/spring-cloud/src/main/java/io/swagger/api/PetApi.java
samples/client/petstore/spring-cloud/src/main/java/io/swagger/api/StoreApi.java
samples/client/petstore/spring-cloud/src/main/java/io/swagger/api/UserApi.java
samples/client/petstore/spring-stubs/src/main/java/io/swagger/api/PetApi.java
samples/client/petstore/spring-stubs/src/main/java/io/swagger/api/StoreApi.java
samples/client/petstore/spring-stubs/src/main/java/io/swagger/api/UserApi.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/model/ClassModel.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/model/OuterEnum.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/FakeApi.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/FakeApiController.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/FakeClassnameTestApi.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/FakeClassnameTestApiController.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/PetApi.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/PetApiController.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/StoreApi.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/StoreApiController.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/UserApi.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/UserApiController.java
samples/server/petstore/springboot/src/main/java/io/swagger/api/FakeApi.java
samples/server/petstore/springboot/src/main/java/io/swagger/api/FakeApiController.java
samples/server/petstore/springboot/src/main/java/io/swagger/api/FakeClassnameTestApi.java
samples/server/petstore/springboot/src/main/java/io/swagger/api/FakeClassnameTestApiController.java
samples/server/petstore/springboot/src/main/java/io/swagger/api/PetApi.java
samples/server/petstore/springboot/src/main/java/io/swagger/api/PetApiController.java
samples/server/petstore/springboot/src/main/java/io/swagger/api/StoreApi.java
samples/server/petstore/springboot/src/main/java/io/swagger/api/StoreApiController.java
samples/server/petstore/springboot/src/main/java/io/swagger/api/UserApi.java
samples/server/petstore/springboot/src/main/java/io/swagger/api/UserApiController.java

Adds 'throws Exception' to all controller methods. This allows servers to implement global exception handling in Spring, where controller methods can throw exceptions and have them handled globally.
Breaking change, hence filed against 2.3.0
See Issue #5686

Java spring throw exceptions (#5686)

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/HaskellServantCodegen.java

Fix a bug that leads to generated field names not escaping special characters. (#5793)

Fix issue 5793

---

modules/swagger-codegen/src/main/resources/typescript-angular2/modelGeneric.mustache

- [done ] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [done ] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [done ] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.
This change removes the `models.` namespace usage for interfaces that extend a parent.  This was originally modified by commit `7ea419dc5d1aab6c275986ac5322f46e994973bd` which removed the hard-coded inclusion …

[Typescript-Angular2] Removed models namespace from inheritance template

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FlaskConnexionCodegen.java

in order to change the serverPort from the codegen cli

serverPort add from cli

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/StaticHtml2Generator.java
modules/swagger-codegen/src/main/resources/htmlDocs2/index.mustache
modules/swagger-codegen/src/main/resources/htmlDocs2/js_jsonschemaview.mustache
modules/swagger-codegen/src/main/resources/htmlDocs2/param.mustache
modules/swagger-codegen/src/main/resources/htmlDocs2/styles.mustache

Some code to speed up the render of HTML2 documentation. 
- Parse Html markdown with Java's parser instead of JS. 
- Kill some JS that slow down the page loading ( and causes Flash of Unstyled Text (FOUT) )
- Use mustache variable to build html instead of javascript

Html2 speed Up | Raw html using java parser instead of JS parser

---

modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/ApiClient.java

Fix for issue #5777
Fix for: java/jersey2 ApiClient.invokeAPI doesn´t close the Response object

Fix for issue #5777 - java/jersey2 ApiClient.invokeAPI doesn´t close the Response object

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RestbedCodegen.java

Use file.separator instead of "/" for file path in different platforms (Windows, Linux, Mac)

[C++][Restbed] use file.separator instead of "/" for file path

---

bin/flaskConnexion-python2.sh
bin/flaskConnexion.sh
bin/go-petstore-server.sh
bin/javascript-petstore.sh
bin/javascript-promise-petstore.sh
bin/nodejs-petstore-google-cloud-functions.sh
bin/nodejs-petstore-server.sh
bin/objc-petstore-coredata.sh
bin/objc-petstore.sh
bin/security/javascript-petstore.sh
bin/windows/javascript-petstore.bat
bin/windows/javascript-promise-petstore.bat
bin/windows/objc-petstore.bat
modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/cmd/Generate.java
modules/swagger-codegen-cli/src/test/java/io/swagger/codegen/cmd/GenerateTest.java
modules/swagger-codegen-cli/src/test/java/io/swagger/codegen/cmd/utils/OptionUtilsTest.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/config/CodegenConfiguratorUtils.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/utils/OptionUtils.java

- bin/run-all-petstore – no changes after latest rebase (2017-04-04, based on 22c80588f63629a17ae0113da11e2d9b437bd4cf).
- bin/security/run-all-petstore-security-test → same changes as in #5325 + #5324. Not committed here, I will rebase and redo it when those are merged.
As detailed in #5147, this implements two changes (in separate commits, so it should be easy to separate those if needed).
* When parsing comma-separated key-value pairs we know accept empty values (and keys without value are also handled as empty values). This applies to the `-D` option as well as to `--instantiation-type`, `--type-mappings`, `--additional-properties`, `--import-mappings`.
(Previously those keys were simply ignored, which made it impossible to pass just `-D models` (or `-D models=`) as an argument after …

[CLI] #5147: make -D work like system properties

---

modules/swagger-codegen/src/main/resources/Javascript-es6/ApiClient.mustache
samples/client/petstore-security-test/javascript/src/ApiClient.js

Without this change, consuming the API results in `cannot read property 'deserialize' of undefined` from `ApiClient`.  Using a plain anonymous function instead of an arrow function drops the `this` context for `ApiClient` in the superagent callback.

[javascript] Use arrow function with usePromises in ES6 ApiClient.js for superagent callback to preserve `this` context

---

modules/swagger-codegen/src/main/resources/Javascript-es6/ApiClient.mustache
modules/swagger-codegen/src/main/resources/Javascript-es6/partial_model_generic.mustache
samples/client/petstore-security-test/javascript/src/ApiClient.js

`exports` is not a valid global identifier in ES6 modules.

[javascript] Fix usages of `exports` in generated ES6 code

---

modules/swagger-codegen/src/main/resources/qt5cpp/HttpRequest.cpp.mustache
samples/client/petstore-security-test/qt5cpp/client/SWGHttpRequest.cpp
samples/client/petstore/qt5cpp/client/SWGHttpRequest.cpp

Add support for PATCH verb. This was a lifecycle bug. 
Correction use newer QT5 api when available, falls back on old api (with corrected calling code) for backward compatibility.

Fix#5856 - Add support for PATCH

---

modules/swagger-codegen/src/main/resources/Javascript/README.mustache
modules/swagger-codegen/src/main/resources/Javascript/es6/README.mustache
samples/client/petstore/javascript-es6/README.md
samples/client/petstore/javascript-promise-es6/README.md
samples/client/petstore/javascript-promise/README.md
samples/client/petstore/javascript/README.md

This is another try to document the Webpack configuration for the JS clients (#3466). The previous PR #5767 was too hacky.

[JavaScript] Added README section for Webpack configuration

---

modules/swagger-codegen/src/main/resources/Javascript/ApiClient.mustache
samples/client/petstore/javascript-promise/src/ApiClient.js

This is a bug-fix PR for the change introduced in #4902. The syntax was not ES5 compatible, thus this change should be applied to the ES5 JS generator.

[JavaScript] Fixed *WithHttpInfo methods in 'usePromises' mode to be ES5 compatible

---

modules/swagger-codegen/src/main/resources/python/rest.mustache
samples/client/petstore/python/petstore_api/rest.py

swagger-client shouldn't throw ApiException if status code in range 200-299
closes #5105

[Python] Increase range of valid status codes

---

bin/javascript-petstore.sh
bin/javascript-promise-petstore.sh
bin/windows/javascript-petstore.bat
bin/windows/javascript-promise-petstore.bat
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java

Closes https://github.com/swagger-api/swagger-codegen/issues/5909

[JavaScript] set ES6 as the default for JS generator in the 2.3.0 branch

---

modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/pom.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/server/pom.mustache
samples/client/petstore/jaxrs-cxf-client/pom.xml
samples/client/petstore/jaxrs-cxf/pom.xml
samples/server/petstore/jaxrs-cxf-annotated-base-path/pom.xml
samples/server/petstore/jaxrs-cxf-non-spring-app/pom.xml
samples/server/petstore/jaxrs-cxf/pom.xml

Please update the CXF version to include the latest fixes. It's only a backward compatible minor version change.

update to latest CXF release

---

run-in-docker.sh

Fix wrong group id lookup in run-in-docker.sh
Tiny change, the run-in-docker.sh uses id -u for determining the group id, change that to id -g and everything is fine if the user has a gid != uid.
Tested on my local machine.

Use id -g for determining the gid instead of -u

---

modules/swagger-codegen/src/main/resources/typescript-node/api.mustache
samples/client/petstore-security-test/typescript-node/api.ts
samples/client/petstore/typescript-node/default/api.ts
samples/client/petstore/typescript-node/npm/api.ts

For some APIs the authentication logic can be more sophisticated than is in the client (e.g. client certificates, custom root certificates, etc)
Rather than implement all of this in the client, just enable the user to inject their own `Authentication` implementation that will do the right thing.

Add a function for injecting your own Authentication into the Typescript-node client.

---

modules/swagger-codegen-maven-plugin/README.md
modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/pom.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/server/pom.mustache
samples/client/petstore/jaxrs-cxf-client/pom.xml
samples/client/petstore/jaxrs-cxf/pom.xml
samples/server/petstore/jaxrs-cxf-annotated-base-path/pom.xml
samples/server/petstore/jaxrs-cxf-non-spring-app/pom.xml
samples/server/petstore/jaxrs-cxf/pom.xml

jersey2-version in CXF projects is confusing, it doesn't make sense to mix up two JAX-RS implementations and the property is not in use.
I also updated the README.md file for swagger-codegen-maven-plugin as the version 2.2.2 is already released and available on central.

removed obsolete jersey2-version

---

README.md
bin/csharp-property-changed-petstore.sh
modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/cmd/Generate.java
modules/swagger-codegen-cli/src/test/java/io/swagger/codegen/cmd/GenerateTest.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/config/CodegenConfiguratorUtils.java

→ bin/run-all-petstore, with no changes (apart from those who already happen in master, see #5859 + #5861).
As discussed in #5147, all the options which previously had comma separated lists of values now also allow multiple values (or multiple key-value-pairs), as was previously (in #5191) already done for `-D`.
This affects those with key-value-pairs:
--additional-properties
--import-mappings
--instantiation-types
--reserved-word-mappings
--type-mappings
and this option with a simple list of values:
--language-specific-primitives
I also regenerated the output of `help generate` in README.md, which was already out-of-date before.

#5147: allow multiple for other plural options, too

---

modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf-cdi/pom.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/server/pom.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/libraries/jersey1/pom.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/pom.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/resteasy/eap/pom.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/resteasy/pom.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/spec/pom.mustache
modules/swagger-codegen/src/main/resources/JavaSpring/libraries/spring-mvc/pom.mustache
modules/swagger-generator/pom.xml
samples/client/petstore/jaxrs-cxf-client/pom.xml
samples/server/petstore/jaxrs-cxf-annotated-base-path/pom.xml
samples/server/petstore/jaxrs-cxf-cdi/pom.xml
samples/server/petstore/jaxrs-cxf-non-spring-app/pom.xml
samples/server/petstore/jaxrs-cxf/pom.xml
samples/server/petstore/jaxrs-resteasy/default/pom.xml
samples/server/petstore/jaxrs-resteasy/eap-joda/pom.xml
samples/server/petstore/jaxrs-resteasy/eap/pom.xml
samples/server/petstore/jaxrs-resteasy/joda/pom.xml
samples/server/petstore/jaxrs-spec/pom.xml
samples/server/petstore/jaxrs/jersey1/pom.xml
samples/server/petstore/jaxrs/jersey2/pom.xml
samples/server/petstore/spring-mvc-j8-async/pom.xml
samples/server/petstore/spring-mvc/pom.xml

Updated maven-war-plugin to latest version.
The default for failOnMissingWebXml changed from true to false which may simplify several poms but for now I've not touched the existing configuration.

updated maven-war-plugin

---

modules/swagger-codegen-maven-plugin/pom.xml
pom.xml

This PR fixes a warning message when building with Maven 3.5.0:
[WARNING] The project io.swagger:swagger-codegen-project:pom:2.2.3-SNAPSHOT uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
I've increased the required Maven version to 3.2.5 as the 3.2.5 API version is in use in swagger-codegen-maven-plugin.

use enforcer-plugin to fix Maven warning

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java

The change made by PRhttps://github.com/swagger-api/swagger-codegen/pull/5715 introduced an error in the name of models (both files and docs) where names such as `V1TestModel` would be document as `v1TestModel`. 
**Note:** several of the changes seen on the generated `petstore` files are not introduced by this change. Running the script before applying the changes on the PR generate the same changes.

Docs and examples need model name to be passed as baseType

---

.travis.yml

This PR will update .travis.yml to only do a `mvn clean deploy` if the changes are made to "master"

Enable snapshot push for master only  

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
samples/client/petstore/ruby/docs/FakeApi.md
samples/client/petstore/ruby/lib/petstore/models/format_test.rb

"/" (forward slash) is not escaped when adding delimiters "/" to regular expressions. This PR aims to fix that as byte array (base64 string) now has a `pattern` after upgrading to newer version of Swagger Core.

Fix regular expression to escape forward slash 

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CppRestClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PistacheServerCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RestbedCodegen.java
samples/client/petstore/cpprest/model/Category.cpp
samples/client/petstore/cpprest/model/Order.cpp
samples/client/petstore/cpprest/model/Pet.cpp
samples/client/petstore/cpprest/model/Tag.cpp
samples/client/petstore/cpprest/model/User.cpp
samples/server/petstore/pistache-server/model/Category.cpp
samples/server/petstore/pistache-server/model/Order.cpp
samples/server/petstore/pistache-server/model/Pet.cpp
samples/server/petstore/pistache-server/model/Tag.cpp
samples/server/petstore/pistache-server/model/User.cpp
samples/server/petstore/restbed/model/Category.cpp
samples/server/petstore/restbed/model/Order.cpp
samples/server/petstore/restbed/model/Pet.cpp
samples/server/petstore/restbed/model/Tag.cpp
samples/server/petstore/restbed/model/User.cpp

- [ x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
This issue is similar to 8237e49, in which some type checking has in the wrong order. It was picked up by
https://lgtm.com/projects/g/swagger-api/swagger-codegen/alerts/
as 'Contradictory Type checks' (at the very …

[CPP] Fixing some more ordering of checks

---

modules/swagger-codegen/src/main/resources/JavaSpring/libraries/spring-cloud/pom.mustache
samples/client/petstore/spring-cloud/pom.xml
samples/client/petstore/spring-cloud/src/test/resources/application.yml

update Spring cloud dependency again (#5947 missed the application.yml change)

update Spring cloud dependency (#5947 missed the application.yml change)

---

modules/swagger-codegen/src/main/resources/typescript-angular2/configuration.mustache

fix problem with configuration.ts in typescript-angular2 
fix signature for class Configuration to correctly implement  interface ConfigurationParameters
fix compiler error error TS2322: Type 'string | undefined' is not assignable to type 'string | (() => string)'.

[TypeScript][Angular2] fix issues with configuration.ts

---

modules/swagger-codegen/src/main/resources/typescript-angular2/configuration.mustache

fix for typescript-angular2's configuration.mustache -- PR #4361 had opened this up to be able to be specified by string or function; one of the recent changes seems to have stepped on this in that the interface passed to the constructor only allows for string, hence static initialization is problematic.

allow accessToken to be specified by string or function; restores PR #4361

---

modules/swagger-codegen/src/main/resources/erlang-server/handler.mustache
samples/server/petstore/erlang-server/src/swagger_store_handler.erl
samples/server/petstore/erlang-server/src/swagger_user_handler.erl

Broken code is generated when no authentication methods are supplied
in the API schema. Fix this by providing code to fall back to.

Fix Erlang auth method code generation

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ObjcClientCodegen.java

This will prevent submitting integer numbers instead of booleans
when posting objects to the REST API.
Default values for Bool convert into numbers.
Bool are stored as NSNumber, setting a default value to 'false' or 'true' on specification file generates the following lines:
```
property = @0 //false
property = @1 //true
```
this converts into a __NSCFNumber instead of __NSCFBoolean
When posting to the backend this will post an integer instead of a boolean and the REST API will complain.
Generating instead the following code:
```
property = @(NO) //false
property = @(YES) //true
```
it would create an __NSCFBoolean and would not fail when posting the object to the server wrapped into a JSONDictionary

[objc] Initialize default BOOL with @(YES)/@(NO). (#5982)

---

modules/swagger-codegen/src/main/resources/lumen/api.mustache
samples/server/petstore/lumen/lib/app/Http/Controllers/FakeApi.php
samples/server/petstore/lumen/lib/app/Http/Controllers/StoreApi.php

Fixes issue #6012
I've removed all superfluous closing brackets, that would produce syntactical errors, from mustache template. I also regenerated the lumen samples to ensure that the fix will produce correct code.

#6012 - fixed mustache template for lumen server

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCppCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CppRestClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PistacheServerCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RestbedCodegen.java
modules/swagger-codegen/src/main/resources/cpprest/model-header.mustache
modules/swagger-codegen/src/main/resources/cpprest/model-source.mustache
modules/swagger-codegen/src/main/resources/pistache-server/model-header.mustache
modules/swagger-codegen/src/main/resources/pistache-server/model-source.mustache

- [ x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
This change escapes special characters in the property names in the three c++ generators, while preserving the petstore samples. Part of #5949

[CPP] Fix cpp escape issue part of #5949

---

modules/swagger-codegen/src/main/resources/typescript-angular2/api.service.mustache

Code generated for typescript-angular2 client in case when return blob 
could also return undefined
typescript compiler error is :
error TS2322: Type 'Observable<Blob | undefined>' is not assignable to type 'Observable<Blob>'.

[TypeScript][Angular2] Add support for "blob" response type

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java
modules/swagger-codegen/src/main/resources/Java/libraries/resttemplate/build.gradle.mustache
samples/client/petstore/java/resttemplate-withXml/build.gradle
samples/client/petstore/java/resttemplate/pom.xml

- fixed build.gradle
- minor wording change for `withXML` option

[Java][resttemplate] fixed build.gradle

---

modules/swagger-codegen/src/main/resources/Javascript/README.mustache

- Add instructions for installing the generated Javascript library locally without publishing to a remote npm registry.
- Clarify what `main.js` is.
Clarify how to use generated javascript clients locally. Resolves #5986.

Clarify the Javascript README for local use

---

bin/typescript-angular-petstore.sh
bin/typescript-angular2-petstore-all.sh
bin/typescript-angular2-petstore-interfaces.sh
bin/typescript-angular2-petstore-with-npm.sh
bin/typescript-angular2-petstore.sh
bin/typescript-angular4-petstore-with-npm.sh
bin/windows/typescript-angular.bat
bin/windows/typescript-angular2-interfaces.bat
bin/windows/typescript-angular2-petstore-all.bat
bin/windows/typescript-angular2-with-npm.bat
bin/windows/typescript-angular2.bat
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngular2ClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngularClientCodegen.java
samples/client/petstore/typescript-angular2/npm/package.json

- renamed typescript-angular to typescript-angularjs in 2.3.0
- renamed typescript-angular2 to typescript-angular in 2.3.0
- updated shell scripts, batch files
Closes https://github.com/swagger-api/swagger-codegen/issues/5570

[TypeScript] rename Angular, Angular2 generators

---

modules/swagger-codegen/src/main/resources/csharp/modelGeneric.mustache
samples/client/petstore/csharp/SwaggerClient/docs/FakeApi.md
samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/Model/FormatTest.cs
samples/client/petstore/csharp/SwaggerClientNetStandard/docs/FakeApi.md
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/docs/FakeApi.md
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/src/IO.Swagger/Model/FormatTest.cs

Skip the regular expression validation for byte array, which causes compilation errors.

[C#] skip pattern check for byte array in C# API client

---

bin/windows/typescript-angular2-all.bat
modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache
samples/client/petstore/typescript-angular2/default/api/PetApi.ts
samples/client/petstore/typescript-angular2/default/api/StoreApi.ts
samples/client/petstore/typescript-angular2/default/api/UserApi.ts
samples/client/petstore/typescript-angular2/npm/api/PetApi.ts
samples/client/petstore/typescript-angular2/npm/api/StoreApi.ts
samples/client/petstore/typescript-angular2/npm/api/UserApi.ts
samples/client/petstore/typescript-angular2/with-interfaces/api/PetApi.ts
samples/client/petstore/typescript-angular2/with-interfaces/api/StoreApi.ts
samples/client/petstore/typescript-angular2/with-interfaces/api/UserApi.ts

add `@summary` JSDoc tag for api method

[Typescript-Angular2] add @summary JSDoc tag

---

modules/swagger-generator/pom.xml

Fix this issue #4644
`8080` is jetty default port
Removing this value allow using config `-Djetty.port=8181` to fix possible conflicts

[swagger-generator] Configurable jetty server port

---

modules/swagger-codegen/src/main/resources/Java/modelEnum.mustache
modules/swagger-codegen/src/main/resources/Java/pojo.mustache
samples/client/petstore-security-test/java/okhttp-gson/src/main/java/io/swagger/client/model/ModelReturn.java

The [java8 doclint](http://openjdk.java.net/jeps/172) rejects unescaped
HTML chars such as `<`, making some generated clients unbuildable with
java8. Seems a few property descriptions were using the `{{{` instead
of `{{` preventing those HTML chars from being escaped properly.

[Java] Escape descriptions in javadocs

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java

When generating client libs for the EVE Online ESI API a null pointer exception occured preventing the libs from being build.
git clone https://github.com/swagger-api/swagger-codegen
cd swagger-codegen
mvn clean package
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
-i https://esi.tech.ccp.is/latest/swagger.json \
-l java \
-o samples/client/eve-online-esi-api/java
I traced the root cause of the null pointer exception and prevented it by a not-null-check when adding the object in question.
**Caution: I have absolutely no idea what the code were I implemented the fix does!!!**
Please check the fix for any side effects. I only tested the fix with the petstore and eve specs and both can build their client libs.

Added not null check in code generator.

---

modules/swagger-codegen/src/main/resources/JavaJaxRS/resteasy/eap/JacksonConfig.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/resteasy/eap/gradle.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/resteasy/eap/pom.mustache
samples/server/petstore/jaxrs-resteasy/eap-joda/build.gradle
samples/server/petstore/jaxrs-resteasy/eap-joda/pom.xml
samples/server/petstore/jaxrs-resteasy/eap/build.gradle
samples/server/petstore/jaxrs-resteasy/eap/pom.xml
samples/server/petstore/jaxrs-resteasy/eap/src/main/java/io/swagger/api/JacksonConfig.java

* Depend on Joda by default, like the default JAX-RS server.
* If Java 8 is specified add Jackson JSR-310 dependency and import
in the JacksonConfig.

[JaxrsResteasy] Fix EAP dependencies for Java 8

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaPlayFrameworkCodegen.java

Fix Java Play server generator when path variables aren't camelCase

---

modules/swagger-codegen/src/main/resources/rust/api.mustache
modules/swagger-codegen/src/main/resources/rust/api_mod.mustache
modules/swagger-codegen/src/main/resources/rust/model.mustache

Template fixes for rust generator WIP in https://github.com/swagger-api/swagger-codegen/pull/6105
/cc @wing328

Rust generator

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FlaskConnexionCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java

* setReservedWordsLowerCase was called twice, the second time without self and None
* True, False and nonlocal are python3 reserved words
issue reference #6111
* setReservedWordsLowerCase was called twice, the second time without self and None
* True, False and nonlocal are python3 reserved words

[Flask] self and None are reserved words (#6111)

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RustClientCodegen.java
modules/swagger-codegen/src/main/resources/rust/api.mustache
modules/swagger-codegen/src/main/resources/rust/api_mod.mustache
modules/swagger-codegen/src/main/resources/rust/client.mustache
modules/swagger-codegen/src/main/resources/rust/model.mustache
modules/swagger-codegen/src/main/resources/rust/model_mod.mustache

Final portion of changes to #6105 so it compiles.
/cc @wing328

Fixed the remaining templates inconsistencies for rust generator

---

samples/client/petstore/rust/.gitignore
samples/client/petstore/rust/Cargo.toml
samples/client/petstore/rust/examples/client.rs
samples/client/petstore/rust/src/apis/add_pet_api.rs
samples/client/petstore/rust/src/apis/client.rs
samples/client/petstore/rust/src/apis/configuration.rs
samples/client/petstore/rust/src/apis/get_pet_by_id_api.rs
samples/client/petstore/rust/src/apis/mod.rs
samples/client/petstore/rust/src/apis/pet_api.rs
samples/client/petstore/rust/src/apis/update_pet_with_form_api.rs
samples/client/petstore/rust/src/lib.rs
samples/client/petstore/rust/src/models/category.rs
samples/client/petstore/rust/src/models/mod.rs
samples/client/petstore/rust/src/models/pet.rs
samples/client/petstore/rust/src/models/tag.rs

Tracking PR for Rust client implementation.
The first commit adds a subset of apis requested in #5905.

[New Generator] Rust API client generator

---

modules/swagger-codegen/src/main/resources/ruby/partial_model_enum_class.mustache

- [x ] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes.
Fixes issue with ENUM generation for ruby issue #4848

Ruby Enums: Fix for issue #4848

---

modules/swagger-codegen/src/main/resources/objc/api-body.mustache

Change booleans in query parameters from 0/1 to true/false to
match Swagger UI behaviour
- [x ] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes.
https://github.com/swagger-api/swagger-codegen/issues/6139
Boolean properties …

[objc] Convert boolean query params to true/false (#6139)

---

CONTRIBUTING.md
bin/eiffel-petstore.sh
bin/windows/eiffel-petstore.bat
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractEiffelCogegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/EiffelClientCodegen.java
modules/swagger-codegen/src/main/resources/Eiffel/README.mustache
modules/swagger-codegen/src/main/resources/Eiffel/api_client.mustache
modules/swagger-codegen/src/main/resources/Eiffel/framework/auth/authentication.mustache
modules/swagger-codegen/src/main/resources/Eiffel/travis.mustache

Added shell scripts, batch files to generate Eiffel Petstore samples.
Added Setup CI (travis, shippable, etc) to cover the Eiffel Petstore samples.
Refactored part of the code into an Abstract Eiffel base class,
which can be later used in Eiffel server stub generators.
Added Eiffel Style guide to the contribution guidelines so that Eiffel contributors know what to follow in terms of code style
Fixed code generator issues.
Updated mustaches templates.
**Related issues/PRs**
[#6057](https://github.com/swagger-api/swagger-codegen/issues/6057)

Enhancements to the Eiffel generator #6057

---

modules/swagger-codegen/src/main/resources/TypeScript-Fetch/api.mustache
samples/client/petstore-security-test/typescript-fetch/api.ts
samples/client/petstore/typescript-fetch/builds/default/api.ts

This prevents empty URL parameters from being sent, e.g. `http://some-api/endpoint?param=SOMETHING?v=` will now be `http://some-api/endpoint?param=SOMETHING`.
Solution suggested by @TiFu. Fixes #6003.
Can somebody please verify whether this is still working as intended: https://github.com/swagger-api/swagger-codegen/compare/master...roberterdin:master#diff-89eaac82e75bf2e3698813ad62b26691L70
I don't know if it is covered by the tests and if the browser tests are being executed with maven.

[TypeScript Fetch] Optional URL query parameters not sent anymore

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/KotlinClientCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/kotlin/KotlinClientCodegenOptionsTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/KotlinClientCodegenOptionsProvider.java

#6133 : Fixed support of sourceFolder property for kotlin code generation

[kotlin] fixed support of source folder (#6133)

---

modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/ApiClient.mustache

Jersey LoggingFilter is deprecated, replaced with LoggingFeature

---

modules/swagger-codegen/src/main/resources/objc/api-header.mustache

Allow documentation to specify void when no
return type is available
Remove Xcode warnings:
```
Documentation Issue
Empty paragraph passed to '@return' command
```
- [ x] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes. …

Fix Xcode Documentation Issue

---

modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
samples/client/petstore/java/jersey2-java6/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/ApiClient.java

I found myself in a situation where I needed to change the configured `Feature`s, but
because of all the private variables I was not able to do so. Perhaps this is a bit too
broad of a stroke, but I changed all fields and methods to `protected` instead of `private`.
In this way, future extensibility should be improved.
Also, to solve my particular problem, I added a new empty method called
`performAdditionalClientConfiguration` which will allow subclasses to add specific features,
or do anything else possible with a `ClientConfig`.

More flexible subclassing of ApiClient possible by s/private/protected/g

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenOperation.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/resources/Java/api.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/api.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/resteasy/api.mustache
modules/swagger-codegen/src/test/java/io/swagger/codegen/CodegenTest.java
modules/swagger-codegen/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
modules/swagger-codegen/src/test/resources/2_0/petstore.json
modules/swagger-codegen/src/test/resources/2_0/petstore.yaml
samples/client/petstore/java/jersey1/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/jersey2-java6/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/resteasy/src/main/java/io/swagger/client/api/PetApi.java

Add `@Deprecated` annotations to generated Java clients.

[Java][Client] Add Deprecated annotation

---

modules/swagger-codegen/src/main/resources/php/api.mustache

Allow to customize file param name.

Fix PHP file param name

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConfig.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/java/JavaModelTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/staticDocs/StaticOperationTest.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/model/Cat.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/model/Order.java

Add several functions to better control the setter and getter (boolean, non-boolean)
Enhancements to https://github.com/swagger-api/swagger-codegen/pull/6169

Better control on setter, getter (for boolean, non-boolean)

---

modules/swagger-codegen/src/main/resources/Java/ApiClient.mustache

I'm having trouble with the `./bin/java-petstore-all.sh` script since it's introducing a lot of changes unrelated to this change, even when I run against `upstream/master` with no changes staged. It seems like at some point changes to the templates were not checked in alongside their changes to the petstore examples.
Servers can describe their desired (consumed) content type for an operation as "*/*", which the current swagger API sends as the content type for any request against that operation. This is troublesome because "*/*" provides no info to the server as to what is being sent. Given that swagger already defaults to "application/json", this seems appropriate.

[Java] Interpret consumes '*/*' as 'application/json'

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/KotlinClientCodegen.java

#6135 removed warnings for "apiPackage" and "modelPackage" indicating that the properties are not used even though they are
properties are actually taken into account in `super.processOpts();` call

[kotlin] removed unaccurate warning (#6135)

---

modules/swagger-codegen/src/main/resources/csharp/api.mustache
modules/swagger-codegen/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
samples/client/petstore/csharp/SwaggerClient/README.md
samples/client/petstore/csharp/SwaggerClient/docs/Fake_classname_tags123Api.md
samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/Api/FakeApi.cs
samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/Api/Fake_classname_tags123Api.cs
samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/Api/PetApi.cs
samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/Api/StoreApi.cs
samples/client/petstore/csharp/SwaggerClientNetStandard/README.md
samples/client/petstore/csharp/SwaggerClientNetStandard/docs/Fake_classname_tags123Api.md
samples/client/petstore/csharp/SwaggerClientNetStandard/src/IO.Swagger/Api/FakeApi.cs
samples/client/petstore/csharp/SwaggerClientNetStandard/src/IO.Swagger/Api/Fake_classname_tags123Api.cs
samples/client/petstore/csharp/SwaggerClientNetStandard/src/IO.Swagger/Api/PetApi.cs
samples/client/petstore/csharp/SwaggerClientNetStandard/src/IO.Swagger/Api/StoreApi.cs
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/README.md
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/docs/Fake_classname_tags123Api.md
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/src/IO.Swagger/Api/FakeApi.cs
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/src/IO.Swagger/Api/Fake_classname_tags123Api.cs
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/src/IO.Swagger/Api/PetApi.cs
samples/client/petstore/csharp/SwaggerClientWithPropertyChanged/src/IO.Swagger/Api/StoreApi.cs

- Fixed the issue with `ParameterToKeyValuePairs` for query parameters
- Updated petstore-with-fake-endpoints-models-for-testing.yaml with additional test cases to cover the issue moving forward

[C#] fix issue with API key (query)

---

modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/pom.mustache
samples/client/petstore/java/jersey2-java6/pom.xml

To fix https://github.com/swagger-api/swagger-codegen/issues/6154

[Java][Jersey2] Use jersey 2.6 for JDK6

---

modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/pom.mustache

Add `javax.validation.validation-api` dependency for Bean Validation API support to `pom.mustache` under jersey2

[Java][Client] Add javax.validation.validation-api dependency for Bean Validation API support to Jersey 2

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java

Made the x-examples to have the same formatting as other examples in swagger

Fixed x-example

---

bin/swift3-petstore-objcCompatible.json
bin/swift3-petstore-objcCompatible.sh
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Swift3Codegen.java
modules/swagger-codegen/src/main/resources/swift3/model.mustache
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/Swift3OptionsProvider.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/swift3/Swift3OptionsTest.java

Currently, in the swift3 language, if you have an optional integer, number, or boolean property in a model, then the generated swift3 model class might look like:
```
class SomeModel {
var someInt: Int?
var someFloat: Float?
var someDouble: Double?
var someBool: Bool?
}
```
This works fine if you are accessing this model only from Swift code. However, it is very common for iOS codebases to contain both Swift AND Objective-C. If you need to access this model from Objective-C, then those 4 properties are not accessible, since Optional scalars do not translate to Objective-C.
Therefore, in the swift3 language, we want to add some code for Objective-C compatibility:
1. We add a "objcCompatible" boolean command-line option. If objcCompatible=true, then this enables some additional code …

Add additional cli option and properties to swift3 for Objective-C compatibility

---

bin/swift4-petstore-objcCompatible.json
bin/swift4-petstore-objcCompatible.sh
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Swift4Codegen.java
modules/swagger-codegen/src/main/resources/swift4/model.mustache
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/Swift4OptionsProvider.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/swift4/Swift4CodegenTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/swift4/Swift4ModelTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/swift4/Swift4OptionsTest.java

This change adds Objective-C compatibility for Swift Optional scalars in the swift4 language just like we added in swift3 here:
https://github.com/swagger-api/swagger-codegen/pull/6129
It also adds unit tests for the swift4 language. Currently those unit tests are the same as the swift3 unit tests, but will change soon as we iterate on the swift4 language generator.
- [x ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). …

Add Objective-C compatibility for Optional scalars in swift4 just like swift3

---

bin/eiffel-petstore.sh
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractEiffelCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/EiffelClientCodegen.java
modules/swagger-codegen/src/main/resources/Eiffel/api.mustache
modules/swagger-codegen/src/main/resources/Eiffel/api_client.mustache
modules/swagger-codegen/src/main/resources/Eiffel/ecf.mustache
modules/swagger-codegen/src/main/resources/Eiffel/model.mustache
modules/swagger-codegen/src/main/resources/Eiffel/model_enum.mustache
modules/swagger-codegen/src/main/resources/Eiffel/model_generic.mustache
modules/swagger-codegen/src/main/resources/Eiffel/test/ecf_test.mustache
samples/client/petstore/eiffel/api_client.ecf
samples/client/petstore/eiffel/test/api_test.ecf

This PR added Enum support and fixes
Fixed typo in the Abstract Eiffel class.
Fixed typo in shell script
Added support for Outer Enums, inner enums not supported.
Added missing UUID library in ecf configuration template.
Improved Model inheritance.

Fixed typo in the Abstract Eiffel class.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/InlineModelResolver.java

Fix returnBaseType in Map response  (which was not handled before)

Fix returnBaseType in Map response

---

modules/swagger-codegen/src/main/resources/rust/model.mustache

This can be improved further by turning ref Options into Options with refs and passing trivial types by copy.

Added trivial getter implementation

---

modules/swagger-codegen/src/main/resources/JavaSpring/api.mustache
samples/client/petstore/spring-cloud/src/main/java/io/swagger/api/PetApi.java
samples/client/petstore/spring-cloud/src/main/java/io/swagger/api/StoreApi.java
samples/client/petstore/spring-cloud/src/main/java/io/swagger/api/UserApi.java
samples/client/petstore/spring-stubs/src/main/java/io/swagger/api/PetApi.java
samples/client/petstore/spring-stubs/src/main/java/io/swagger/api/StoreApi.java
samples/client/petstore/spring-stubs/src/main/java/io/swagger/api/UserApi.java
samples/server/petstore/spring-mvc-j8-async/pom.xml
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/api/FakeApi.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/api/PetApi.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/api/StoreApi.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/api/UserApi.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/model/ClassModel.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/model/OuterEnum.java
samples/server/petstore/spring-mvc/pom.xml
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/FakeApi.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/PetApi.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/StoreApi.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/UserApi.java
samples/server/petstore/springboot/src/main/java/io/swagger/api/FakeApi.java
samples/server/petstore/springboot/src/main/java/io/swagger/api/PetApi.java
samples/server/petstore/springboot/src/main/java/io/swagger/api/StoreApi.java
samples/server/petstore/springboot/src/main/java/io/swagger/api/UserApi.java

@ApiResponse's 'response' property now refers to its relative 'baseType', if defined.
Fix of #3371, to have a correct @ApiResponse's response type.
@ApiResponse's 'response' property now refers to its relative 'baseType', if defined.

Fix of #3371, to have a correct @ApiResponse's response type.

---

modules/swagger-codegen/src/test/resources/2_0/petstore.json

Deprecated should be a boolean otherwise the parser does not validate

string used instead of Boolean for "deprecated"

---

modules/swagger-codegen/src/main/resources/Java/api.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/feign/api.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/api.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/api.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/resteasy/api.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/resttemplate/api.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit/api.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/api.mustache
samples/client/petstore/java/jersey1/docs/StoreApi.md
samples/client/petstore/java/jersey2-java6/docs/StoreApi.md
samples/client/petstore/java/jersey2-java8/docs/StoreApi.md
samples/client/petstore/java/jersey2/docs/StoreApi.md
samples/client/petstore/java/okhttp-gson-parcelableModel/docs/StoreApi.md
samples/client/petstore/java/okhttp-gson/docs/StoreApi.md
samples/client/petstore/java/resteasy/docs/StoreApi.md
samples/client/petstore/java/resttemplate-withXml/docs/StoreApi.md
samples/client/petstore/java/resttemplate/docs/StoreApi.md
samples/client/petstore/java/retrofit2-play24/docs/StoreApi.md
samples/client/petstore/java/retrofit2/docs/StoreApi.md
samples/client/petstore/java/retrofit2rx/docs/StoreApi.md
samples/client/petstore/java/retrofit2rx2/docs/StoreApi.md

Fix unexpected text error in javadoc by replacing url with html tag

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaJerseyServerCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/jaxrs/JaxRSServerOptionsTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/JaxRSServerOptionsProvider.java

Adds a useTags additional property to the Java Jersey JaxRS server codegen. Allows for generation to create sevice/factories according to specified tags rather than root of URL stem.
#6218

Add useTags option to JavaJersey server codegen

---

modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/JSON.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/JSON.mustache

This commit https://github.com/swagger-api/swagger-codegen/commit/f1e237f76fc7ee8c731e77569c5628da5dff85d8 seemed to have introduce unprompted new properties to the `DateTimeTypeAdaptor`. While this technically changes the intended behavior of having two separate date time formatters for parsing and printing, I can't see reverting this breaking anything since the generated code in its current state cannot compile.

[Java] Fix okhttp-gson datetime converter compilation

---

modules/swagger-codegen/pom.xml
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractScalaCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AkkaScalaClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ScalaClientCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/languages/AbstractScalaCodegenTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/languages/ScalaCodegenTest.java

This goal of this PR is to fix this [issue](https://github.com/swagger-api/swagger-codegen/issues/6234).
In fact, When generating a client using scala module, the class name of the generated models contains the package like this "models.WebsiteBodyModel" which causes compilation errors.
This PR replaces this old one: https://github.com/swagger-api/swagger-codegen/pull/6235

[Scala] Strip package name from the class name

---

modules/swagger-codegen/src/main/resources/swift3/AlamofireImplementations.mustache
samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/AlamofireImplementations.swift

Fix for issue #6236 
The `schema: file` was unsupported.  The code now downloads a file to the file system and returns a file `URL`.
cc @wuf810

[Swift3] Download file fix

---

modules/swagger-codegen/src/main/resources/Java/libraries/retrofit/auth/OAuth.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/auth/OAuth.mustache
samples/client/petstore/java/retrofit/src/main/java/io/swagger/client/auth/OAuth.java
samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/auth/OAuth.java
samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/auth/OAuth.java
samples/client/petstore/java/retrofit2rx2/src/main/java/io/swagger/client/auth/OAuth.java

When the response is 401 or 403, the interceptor assumes that it is because of token so it keeps retrying the request with new token. However if the response status is due to the fact that authorization to the api endpoint failed, and not due to invalid token, then a recursive operation of updating token and re-requesting the failed request happens.
For second point, I committed the files affected by my change. There were many generated files by the shell scripts which I ignored. Ran maven integration tests and they pass.
This PR fixes the bug described in https://github.com/swagger-api/swagger-codegen/issues/6288 (and above too)
The fix is to not retry making the api request when receiving 401 (or 403) for a second time, and just return the 401 (or 403) response.

[Java] fix a bug whereby OAuth intercept method calls itself forever

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/csharp/CSharpClientOptionsTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/CSharpClientOptionsProvider.java

#6281 
Almost 100% identical with the implementation of the option in the Scala generator

[C#] Added modelPropertyNaming option to the csharp generator

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenOperation.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/examples/ExampleGenerator.java

Added examples for Body parameter - the reason for this it to be able to auto generate test cases with valid request content. The other option is to manually add x-examples in the specification and use those as input.

Added examples for body parameter

---

modules/swagger-codegen/src/main/resources/python/asyncio/rest.mustache
modules/swagger-codegen/src/main/resources/python/rest.mustache

Checking for "trueness" here is not sufficient.  An empty list has a truth
value of false so it will not be encoded as json and sent as the request
body as it should.  Instead we need to check explicitly if body is None.

[python] Fix body check in rest.py

---

modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf-cdi/pom.mustache
samples/server/petstore/jaxrs-cxf-cdi/pom.xml

Update JAXRS-CXF-CDI pom.xml to avoid downloading the latest pre-release of io.swagger annotation lib.

[Java][JAX-RS] Fix pom in jaxrs-cxf-cdi

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java

Partial fix for #2936; will fix the ArrayList/HashMap import issue.
All this does is avoid trying to import "ArrayList" and "HashMap" when using full java util classes.  Doing so should be save because java.util.* will be referenced via full classnames in that case, and if alternate mappings are provided for these, absolute classes can be used.

[Java] Valid generated classes with `fullJavaUtil`

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/KotlinClientCodegen.java

Use the optional packageName parameter for model and api classes,
additionally to the infrastructure classes.
Fixes #6364
This PR fixes #6364 by using the packageName option to build the package name for the api and model classes unless these are not explicitly set.

Kotlin: Use packageName option for all classes

---

modules/swagger-codegen/src/main/resources/nodejs/writer.mustache

Don't send code with response.end because it's already set in writeHead.
Fixes #6292

fix(codegen, nodejs-server): correct reponse.end

---

modules/swagger-codegen/src/main/resources/JavaPlayFramework/newApiController.mustache
samples/server/petstore/java-play-framework-fake-endpoints/app/controllers/FakeApiController.java

Small bug of using the wrong mustache param when getting query parameters.

[Java Play Framework] Fix a small error of using paramName instead of baseName

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/HaskellServantCodegen.java
samples/server/petstore/haskell-servant/lib/SwaggerPetstore/Types.hs

Map ByteArray to the Haskell type Text. Fixes #6401.

Map ByteArray to Text for haskell codegen

---

modules/swagger-codegen/src/main/resources/ruby/api_client.mustache

File here will be overriden by generated class File if swagger.yml contains the definition named File. Using global namespace can fix it

Global namespaces for ruby basic types

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/KotlinClientCodegen.java
modules/swagger-codegen/src/main/resources/kotlin-client/enum_class.mustache

Run postProcessModelsEnum on model enums, so that enumVars get populated,
and fix the model enum template.
see above

[Kotlin] Fix model enum generation

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngularClientCodegen.java
modules/swagger-codegen/src/main/resources/typescript-angular/api.service.mustache
modules/swagger-codegen/src/main/resources/typescript-angular/encoder.mustache
samples/client/petstore/typescript-angular-v2/default/api/pet.service.ts
samples/client/petstore/typescript-angular-v2/default/api/store.service.ts
samples/client/petstore/typescript-angular-v2/default/api/user.service.ts
samples/client/petstore/typescript-angular-v2/default/encoder.ts
samples/client/petstore/typescript-angular-v2/npm/api/pet.service.ts
samples/client/petstore/typescript-angular-v2/npm/api/store.service.ts
samples/client/petstore/typescript-angular-v2/npm/api/user.service.ts
samples/client/petstore/typescript-angular-v2/npm/encoder.ts
samples/client/petstore/typescript-angular-v2/with-interfaces/api/pet.service.ts
samples/client/petstore/typescript-angular-v2/with-interfaces/api/store.service.ts
samples/client/petstore/typescript-angular-v2/with-interfaces/api/user.service.ts
samples/client/petstore/typescript-angular-v2/with-interfaces/encoder.ts
samples/client/petstore/typescript-angular-v4/npm/api/pet.service.ts
samples/client/petstore/typescript-angular-v4/npm/api/store.service.ts
samples/client/petstore/typescript-angular-v4/npm/api/user.service.ts
samples/client/petstore/typescript-angular-v4/npm/configuration.ts
samples/client/petstore/typescript-angular-v4/npm/encoder.ts
samples/client/petstore/typescript-angular-v4/npm/package.json

- Issue #6306 
- Add customized query encoder to use '+' character in query parameter

[typescript-angular] add customized encoder to use '+' char in query parameter #6306

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java
samples/client/petstore/java/retrofit2-play24/src/main/java/io/swagger/client/model/FormatTest.java

When used as an enum value, long values (those marked with format: int64 in an OAS spec) were not being suffixed with l. This means autoboxing (as Long is used in place of long) fails, preventing the code from compiling.
Sample broken before this change (build with  `-l java -Dmodels` or you'll get an NPE as there are no paths) and fixed after the change.
```
swagger: 2.0
definitions:
BrokenEnum:
type: object
properties:
long_value:
enum:
- 1
- 2
type: integer
format: int64
```
Resolves #6338 
Note: I ran java-petstore-all.sh to update the samples - I'm unsure which one exactly the plain `java` language maps to, nor whether to just test everything since model changes can in theory affect them all.

[Java] Handle Long in enum correctly

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/CodegenTest.java

I discovered that the `camelize` function doesn't support `hyphen-case` to `camelCase`. So I added the needed code. Tested by running all the samples from Java Play Framework and it doesn't change anything since all petstore examples are already camelCase or underscore_case. Maybe we should add an example of this. The "instagram" example from swagger.io is all hyphen-case.

[All generators] Supports of hyphen-case to camelCase

---

modules/swagger-codegen/src/main/resources/android/libraries/volley/apiInvoker.mustache
samples/client/petstore/android/volley/docs/StoreApi.md
samples/client/petstore/android/volley/src/main/java/io/swagger/client/ApiInvoker.java
samples/client/petstore/android/volley/src/main/java/io/swagger/client/api/StoreApi.java

PR for Issue #6432 
The constructor of StringEntity can throw UnsupportedEncodingException, which is not catch nor thrown by createRequest method.
Therefore the build of android client fails with:
ApiInvoker.java:448: error: unreported exception UnsupportedEncodingException; must be caught or declared to be thrown
This commit adds a try ... catch on UnsupportedEncodingException in invokeAPI methods and declare this exception to be thrown in createRequest

[ANDROID][volley] Handle UnsupportedEncodingException in invokeAPI

---

modules/swagger-codegen/src/main/resources/flaskConnexion/requirements.mustache
samples/client/petstore/python/petstore_api/rest.py
samples/server/petstore/flaskConnexion/requirements.txt

Updating the version of connexion from 1.1.9 to 1.1.15, to support arrays with the multi collection format.

[Python][Flask] Upgraded connxion to 1.1.15 (now supports multi collection format arrays)

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ObjcClientCodegen.java
samples/client/petstore/objc/core-data/SwaggerClient/Api/SWGPetApi.h
samples/client/petstore/objc/core-data/SwaggerClient/Api/SWGStoreApi.h
samples/client/petstore/objc/core-data/SwaggerClient/Api/SWGUserApi.h
samples/client/petstore/objc/default/SwaggerClient/Api/SWGPetApi.h
samples/client/petstore/objc/default/SwaggerClient/Api/SWGStoreApi.h
samples/client/petstore/objc/default/SwaggerClient/Api/SWGUserApi.h
samples/client/petstore/objc/default/docs/SWGStoreApi.md

Similar to https://github.com/swagger-api/swagger-codegen/pull/6462 but for ObjC

[ObjC] fix NPE when getting swagger type

---

modules/swagger-codegen/src/main/resources/swift4/AlamofireImplementations.mustache
samples/client/petstore/swift4/default/PetstoreClient/Classes/Swaggers/AlamofireImplementations.swift
samples/client/petstore/swift4/default/PetstoreClient/Classes/Swaggers/CodableHelper.swift
samples/client/petstore/swift4/promisekit/PetstoreClient/Classes/Swaggers/AlamofireImplementations.swift
samples/client/petstore/swift4/promisekit/PetstoreClient/Classes/Swaggers/CodableHelper.swift
samples/client/petstore/swift4/rxswift/PetstoreClient/Classes/Swaggers/AlamofireImplementations.swift
samples/client/petstore/swift4/rxswift/PetstoreClient/Classes/Swaggers/CodableHelper.swift

This is the equivalent change in the swift4 module to the change which was made in the swift3 module in this PR:
https://github.com/swagger-api/swagger-codegen/pull/6274
This updates AlamofireImplementations.mustache to handle when the response is an URL. It also makes changes in the generated sample code for:
* default configuration (no promisekit or rxswift)
* promisekit
* rxswift
Also, in order to build, the generated code needed to be updated with the change in CodableHelper which changes dataDecodingStrategy to ".base64" from its previous definition in earlier Xcode 9 betas.
- [x ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify …

Swift4: Handle when response is a file URL.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCppCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CppRestClientCodegen.java

* Also handles automatic escaping for reserved words, i.e.
by default, no need to provide a mapping.
Fix #6498

Add support for reserved-words-mappings to cpprest

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Swift4Codegen.java

This change eliminates all Java compilation warnings in the swift4 codegen module. The compilation warnings included:
- Avoiding importing modules via wildcard
- Lines longer than 100 characters
- Lines which ended in an operator like "+" or "||"
- Lack of space as in these cases:
- "if("
- "while("
- Single-letter variable names like "p"
- "if" or "else" clauses which were not enclosed in braces
- Incorrect indentation

Eliminate all Java compilation warnings for swift4 codegen module

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/php/PhpModelTest.java
samples/client/petstore/php/SwaggerClient-php/docs/Model/FormatTest.md

[PHP] Fix #6474: Bug with 'format: date' when using --model-name-prefix

---

modules/swagger-codegen/src/main/resources/JavaJaxRS/resteasy/eap/enumOuterClass.mustache

- fixed the mustache enum-template for java jaxrs-resteasy-eap code generation to produce valid java (see issue #4123)

produce correct enum for jaxrs resteasy eap

---

modules/swagger-codegen/src/main/resources/typescript-angular/api.service.mustache
samples/client/petstore/typescript-angular-v2/default/api/pet.service.ts
samples/client/petstore/typescript-angular-v2/default/api/store.service.ts
samples/client/petstore/typescript-angular-v2/default/api/user.service.ts
samples/client/petstore/typescript-angular-v2/npm/api/pet.service.ts
samples/client/petstore/typescript-angular-v2/npm/api/store.service.ts
samples/client/petstore/typescript-angular-v2/npm/api/user.service.ts
samples/client/petstore/typescript-angular-v2/with-interfaces/api/pet.service.ts
samples/client/petstore/typescript-angular-v2/with-interfaces/api/store.service.ts
samples/client/petstore/typescript-angular-v2/with-interfaces/api/user.service.ts

fix for issue https://github.com/swagger-api/swagger-codegen/issues/6006
checks if the produces or consumes list is null or empty and adds the corresponding headers (Accept, Content-Type), with the value being a list seperated by semicolon, according to http-spec.

[TypeScript][Angular] Better support for "Accept", "Content-Type"

---

modules/swagger-codegen/src/main/resources/typescript-angular/api.service.mustache
modules/swagger-codegen/src/main/resources/typescript-angularjs/api.mustache
samples/client/petstore/typescript-angular-v2/default/api/pet.service.ts
samples/client/petstore/typescript-angular-v2/default/api/store.service.ts
samples/client/petstore/typescript-angular-v2/default/api/user.service.ts
samples/client/petstore/typescript-angular-v2/npm/api/pet.service.ts
samples/client/petstore/typescript-angular-v2/npm/api/store.service.ts
samples/client/petstore/typescript-angular-v2/npm/api/user.service.ts
samples/client/petstore/typescript-angular-v2/with-interfaces/api/pet.service.ts
samples/client/petstore/typescript-angular-v2/with-interfaces/api/store.service.ts
samples/client/petstore/typescript-angular-v2/with-interfaces/api/user.service.ts
samples/client/petstore/typescript-angularjs/api/PetApi.ts
samples/client/petstore/typescript-angularjs/api/StoreApi.ts
samples/client/petstore/typescript-angularjs/api/UserApi.ts

[typescript-angular2], [typescript-angularjs]: use encodeURIComponent for path parameters
resolve #6524

[typescript-angular] apply encodeURIComponent to path-parameter

---

modules/swagger-codegen/src/main/resources/php/ObjectSerializer.mustache
samples/client/petstore/php/SwaggerClient-php/lib/ObjectSerializer.php

[PHP] Fix #6353: Yii autoloader conflict

---

modules/swagger-codegen/src/main/resources/bash/client.mustache
samples/client/petstore/bash/Dockerfile
samples/client/petstore/bash/_petstore-cli
samples/client/petstore/bash/petstore-cli
samples/client/petstore/bash/petstore-cli.bash-completion

The only special handling was for security definition type `apiKey`
in `query`. All the other security configurations should result in the
same generated code.
Moves the handling of the special query parameters outside of the
`parameters without specific cardinality` section.
To cover the scenario where `elif` was being used, simply leverage the
builtin `continue` statement to stop processing the specific query
parameter and continue to the next available query parameter, if any.
Manually test with multiple different combinations.
Resolves: #6526

[bash] Bugfix: Handle all different types of security

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/CodegenTest.java

To fix https://github.com/swagger-api/swagger-codegen/issues/6482
- add class prefix to tag with numbers
- update Java generator to use default tag naming

Add class prefix to tag with numbers

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/play25/Play25CallAdapterFactory.mustache
modules/swagger-codegen/src/test/java/io/swagger/codegen/CodegenTest.java
samples/client/petstore/java/retrofit2-play24/docs/AnotherFakeApi.md
samples/client/petstore/java/retrofit2-play24/src/main/java/io/swagger/client/api/AnotherFakeApi.java
samples/client/petstore/java/retrofit2-play24/src/test/java/io/swagger/client/api/AnotherFakeApiTest.java
samples/client/petstore/java/retrofit2-play25/docs/AnotherFakeApi.md
samples/client/petstore/java/retrofit2-play25/src/main/java/io/swagger/client/Play25CallAdapterFactory.java
samples/client/petstore/java/retrofit2-play25/src/main/java/io/swagger/client/api/AnotherFakeApi.java
samples/client/petstore/java/retrofit2-play25/src/test/java/io/swagger/client/api/AnotherFakeApiTest.java
samples/client/petstore/java/retrofit2/docs/AnotherFakeApi.md
samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/api/AnotherFakeApi.java
samples/client/petstore/java/retrofit2/src/test/java/io/swagger/client/api/AnotherFakeApiTest.java
samples/client/petstore/java/retrofit2rx/docs/AnotherFakeApi.md
samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/api/AnotherFakeApi.java
samples/client/petstore/java/retrofit2rx/src/test/java/io/swagger/client/api/AnotherFakeApiTest.java
samples/client/petstore/java/retrofit2rx2/docs/AnotherFakeApi.md
samples/client/petstore/java/retrofit2rx2/src/main/java/io/swagger/client/api/AnotherFakeApi.java
samples/client/petstore/java/retrofit2rx2/src/test/java/io/swagger/client/api/AnotherFakeApiTest.java

- added exception converter that can be used to convert from retrofit2.HttpException to custom API exception
- fixed underscore removal code bug (didnt work correctly when the dollar symbol ($) was present)

[Java] Play! framework + retrofit2 client exception converter, bug fixes

---

modules/swagger-codegen/src/main/resources/bash/client.mustache
samples/client/petstore/bash/petstore-cli

Updates the bash client template to allow the generated client code
to be free of lint errors.
Resolves: #6562

[Bash] Bugfix: Resolve lint errors for generated client

---

modules/swagger-codegen/src/main/resources/typescript-angular/api.service.mustache
samples/client/petstore/typescript-angular-v2/default/api/pet.service.ts
samples/client/petstore/typescript-angular-v2/default/api/store.service.ts
samples/client/petstore/typescript-angular-v2/default/api/user.service.ts
samples/client/petstore/typescript-angular-v2/npm/api/pet.service.ts
samples/client/petstore/typescript-angular-v2/npm/api/store.service.ts
samples/client/petstore/typescript-angular-v2/npm/api/user.service.ts
samples/client/petstore/typescript-angular-v2/with-interfaces/api/pet.service.ts
samples/client/petstore/typescript-angular-v2/with-interfaces/api/store.service.ts
samples/client/petstore/typescript-angular-v2/with-interfaces/api/user.service.ts
samples/client/petstore/typescript-angular-v4/npm/api/pet.service.ts
samples/client/petstore/typescript-angular-v4/npm/api/store.service.ts
samples/client/petstore/typescript-angular-v4/npm/api/user.service.ts
samples/client/petstore/typescript-angular-v4/npm/package.json

Use valid JS RegEx

---

modules/swagger-codegen/src/main/resources/bash/client.mustache
samples/client/petstore/bash/petstore-cli

A previous change to make the regex a variable to allow proper linting
resulted in the regexp not having access to the value associated with
the variable and the path variable not being replaced.
Moves the regexp variable inside the for loop to allow the value to be
used and the path variable to be replaced with the provided value.

[Bash ] Bugfix: Path replacement regex not working

---

modules/swagger-codegen/src/main/resources/cpprest/api-source.mustache
modules/swagger-codegen/src/main/resources/cpprest/apiclient-source.mustache
samples/client/petstore/cpprest/ApiClient.cpp
samples/client/petstore/cpprest/api/PetApi.cpp
samples/client/petstore/cpprest/api/StoreApi.cpp
samples/client/petstore/cpprest/api/UserApi.cpp
samples/client/petstore/cpprest/model/Pet.h

Before this PR, file upload functionality was completely broken. I have fixed the segmentation fault due to the use of null `postBody` instead of `uploadData` (I believe, it was just a typo) and `Content-Type` didn't include the `boundary` marker.

[CPPREST] Fixed multipart files upload implementation

---

pom.xml.shippable
shippable.yml

Add haskell-http-client to Shippable CI

[Haskell] Add haskell-http-client to Shippable CI

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java
modules/swagger-codegen/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml

A type alias in this context is where a model is simply another name for a
primitive type, such as `MyString` in the following model definitions:
MyList:
type: array
items:
$ref: '#/definitions/MyString'
MyString:
type: string
It is valid to use a type alias as a property in another object or array model,
even if the object/array is defined before the alias is, as in the example
above. However, the current alias logic only looks "back" in list of previously
defined models, meaning that `MyList` would not know that `MyString` is an
alias. This change fixes the incorrect behavior by pre-calculating the list of
aliases before any models are processed. It also changes the test endpoint to
verify the correct behavior even when an object is defined before an alias it
uses.
- [x ] Read the …

Pre-calculate type aliases before processing models

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngularClientCodegen.java

Naive fix for Issue #6201 . Does not address any other languages.

Fix #6201: Typescript-Angular2 produces invalid import for self-referencing model

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ElixirClientCodegen.java
samples/client/petstore/elixir/lib/swagger_petstore/api/fake.ex
samples/client/petstore/elixir/lib/swagger_petstore/api/pet.ex
samples/client/petstore/elixir/lib/swagger_petstore/api/store.ex

Fix following dialyzer warnings in the sample:
```
:0: Unknown type 'Elixir.Float':t/0
:0: Unknown type 'Elixir.Integer':t/0
```
You can check dialyzer warnings following like:
```
% git clone https://github.com/jeremyjh/dialyxir
% cd dialyxir
% MIX_ENV=prod mix do compile, archive.build, archive.install
% cd ../swagger-codegen/samples/client/petstore/elixir
% mix do deps.get, dialyzer
```

[Elixir] Improve Elixir Client about primitive type spec

---

modules/swagger-codegen/src/main/resources/typescript-angular/modelEnum.mustache
modules/swagger-codegen/src/main/resources/typescript-angular/modelGeneric.mustache
samples/client/petstore/typescript-angular-v2/default/model/order.ts
samples/client/petstore/typescript-angular-v2/default/model/pet.ts
samples/client/petstore/typescript-angular-v2/npm/model/order.ts
samples/client/petstore/typescript-angular-v2/npm/model/pet.ts
samples/client/petstore/typescript-angular-v2/with-interfaces/model/Order.ts
samples/client/petstore/typescript-angular-v2/with-interfaces/model/Pet.ts
samples/client/petstore/typescript-angular-v4/npm/model/order.ts
samples/client/petstore/typescript-angular-v4/npm/model/pet.ts

This PR changes the angular-typescript generator to emit a union of literals for swagger enums, e.g.:
export type StatusEnum = 'open' | 'inProgress' | 'resolved' | 'closed';
or
export type ResponseCode = 200 | 404;
enabling their easy use in angular templates, structural subtyping
among enums (in particular, different instances of the same enum
are now mutually assignable), improving type safety by preventing
incorrect widening, and permitting numeric enum values
(albeit without descriptive names)
Fixes #6206, #5146, #3500

represent swagger enums as union of literal types

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java

Fix NPE in isDataTypeBinary

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/CodegenTest.java

Fix underscore to handle spaces
To close https://github.com/swagger-api/swagger-codegen/issues/6627

Fix underscore to handle spaces

---

modules/swagger-codegen/src/main/resources/Java/libraries/feign/build.gradle.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/feign/build.sbt.mustache
samples/client/petstore/java/feign/build.gradle
samples/client/petstore/java/feign/build.sbt

Changed groupId from “com.netflix.feign” to “io.github.openfeign” from
gradle and sbt mustache templates.
Fixes #6397 by changing groupId in gradle and sbt mustache templates.

Updated feign library dependency to io.github.openfeign

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SymfonyServerCodegen.java
modules/swagger-codegen/src/main/resources/php-symfony/api.mustache
modules/swagger-codegen/src/main/resources/php-symfony/api_controller.mustache
modules/swagger-codegen/src/main/resources/php-symfony/model.mustache
modules/swagger-codegen/src/main/resources/php-symfony/model_generic.mustache
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/SymfonyServerOptionsProvider.java

We were experiencing syntax issues when generating the Petstore example. See some of the examples below:
namespace Swagger\Server\Api;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Swagger\Server\Model\Order;
**use maparray&lt;string,int&gt;;**
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
public function createUsersWithArrayInput(**User[]** $body);
public function createUsersWithListInput(**User[]** $body);
namespace Swagger\Server\Api;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Swagger\Server\Model\Pet;
use Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException;
use Swagger\Server\Model\ApiResponse;
**use string[];**
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
public function …

[PHP][Symfony] Generate valid PHP code

---

modules/swagger-codegen/src/main/resources/go/partial_header.mustache

Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>
The generated comments have a trailing whitespace, which several format related tools check for.

golang: trailing whitespace fails gofmt

---

modules/swagger-codegen/src/main/resources/kotlin-client/infrastructure/ApiClient.kt.mustache
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/infrastructure/ApiClient.kt

I faced with the following exception at runtime on Android Device(API 19) by using generated api client.
```
E/AndroidRuntime(32762): java.lang.NoClassDefFoundError: io.swagger.client.infrastructure.ApiClient$request$1
E/AndroidRuntime(32762): 	at io.swagger.client.apis.InventoryApi.deleteInventory(InventoryApi.kt:294)
```
Finally I was approached an incompatible forEach syntax on ApiClient. Please review this whether is appropriate or not.

[kotlin] Fix causing NoClassDefFoundError at runtime on Android device

---

modules/swagger-codegen/src/main/resources/php/api.mustache
modules/swagger-codegen/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
samples/client/petstore-security-test/php/SwaggerClient-php/lib/Api/FakeApi.php
samples/client/petstore/php/SwaggerClient-php/README.md
samples/client/petstore/php/SwaggerClient-php/docs/Api/FakeApi.md
samples/client/petstore/php/SwaggerClient-php/lib/Api/AnotherFakeApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/FakeApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/FakeClassnameTags123Api.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/PetApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/StoreApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/UserApi.php
samples/client/petstore/php/SwaggerClient-php/tests/ParametersTest.php

This PR fixes the bug reported in https://github.com/swagger-api/swagger-codegen/issues/5338#issuecomment-292502895 .
Currently, the conditions which produces the bug, and error message by the bug differs from https://github.com/swagger-api/swagger-codegen/issues/5338#issuecomment-292502895.
Following reproduces the bug on latest master.
- spec.json
```json
{
"swagger": "2.0",
"paths": {
"/": {
"post": {
"operationId": "postIt",
"consumes": ["application/json"],
"parameters": [{
"name": "body",
"in": "body",
"required": true,
"schema": {
"type": "object",
"additionalProperties": {
"type": "string"
}
}
}]
}
}
}
}
```
- server.php
```php
<?php
file_put_contents(__DIR__ . '/log.txt', file_get_contents('php://input') . "\n");
```
- client.php
```php
<?php
require …
```

[PHP] Fix #5338: InvalidArgumentException

---

modules/swagger-codegen/src/main/resources/typescript-fetch/api.mustache
samples/client/petstore/typescript-fetch/builds/es6-target/api.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/api.ts

Fixes #6698
Prefix all local variables inserted by the template so they won't conflict with function parameters generated from API routes.
@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx

Prefix local vars to prevent conflict with params

---

modules/swagger-codegen/src/main/resources/r/api.mustache
modules/swagger-codegen/src/main/resources/r/model.mustache

Fixing body json string in R client generator
Fixing model string replacement for list of strings

Fixing body json string in R client generator

---

README.md
modules/swagger-codegen/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml

* the yaml currently includes invalid definitions that do not exist: `#/definitions/xmlObject`. 
introduced in 1d89ab6e0 
Revert to previous known good yaml state.
* update template creators

revert changes to fakes yaml

---

README.md

I noticed that the link to the search for open issues that need contributions was always showing up 0 results.
This PR changes the searched label from "Need community contribution" (I guess it was on old label) to "help wanted".

Fixed link to open issues (correct label is 'help wanted')

---

modules/swagger-codegen/src/main/resources/python/api_client.mustache
modules/swagger-codegen/src/main/resources/python/configuration.mustache
samples/client/petstore/python/README.md
samples/client/petstore/python/docs/FakeApi.md
samples/client/petstore/python/petstore_api/api_client.py
samples/client/petstore/python/petstore_api/apis/fake_api.py
samples/client/petstore/python/petstore_api/configuration.py

`ApiClient` docstrings were out of date- `host` isn't a parameter anymore, so I've replaced it with `configuration` and added one for `cookies`
`Configuration` had docstrings on properties and their setters, however only docstrings for the `@property` decorated functions are used. I copied the more descriptive docstrings from the setters to the properties.
No functional changes, docstrings only.
@taxpon @frol @mbohlool @cbornet

Fixed Python client docstrings

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngularClientCodegen.java
samples/client/petstore/typescript-angular-v4.3/npm/model/apiResponse.ts
samples/client/petstore/typescript-angular-v4.3/npm/model/category.ts
samples/client/petstore/typescript-angular-v4.3/npm/model/order.ts
samples/client/petstore/typescript-angular-v4.3/npm/model/pet.ts
samples/client/petstore/typescript-angular-v4.3/npm/model/tag.ts
samples/client/petstore/typescript-angular-v4.3/npm/model/user.ts

This update replaces the code for updating paths for URI encoding. Previously, this code was not converting from snake_case to camelCase, causing the variables embedded in the path to not match the parameter names they were passed to the function as.
The new method involves finding matches of items in curly-braces and iterating through them. Each match is then searched through for underscores. If one is found, it is removed and the following letter is capitalized.
The more complicated replacement is necessary to guarantee we only change the format of the variables inside the template braces. Otherwise, it might replace parts of the url/path itself, rather than just the variable names.
This should fix #6762.
@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx

[TypeScript-Angular] Path URI Encoding Update

---

docker-entrypoint.sh

See #6703. docker-entrypoint.sh doesn't find the "help" command with fgrep. This is a simple workaround--there may be a better approach.

Allow using help command with run-in-docker.sh

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/InlineModelResolver.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/InlineModelResolverTest.java

flatten methods replaces original ObjectProperty objects with new
RefProperty objects which required variables are false as default.
Newly created objects' required variables are set as the original
property.

Fix required bug

---

modules/swagger-codegen/src/main/resources/Javascript/es6/.babelrc.mustache
modules/swagger-codegen/src/main/resources/Javascript/es6/package.mustache
samples/client/petstore/javascript-es6/.babelrc
samples/client/petstore/javascript-es6/package.json
samples/client/petstore/javascript-promise-es6/.babelrc
samples/client/petstore/javascript-promise-es6/package.json

Related issue #6719
* Use babel-preset-env instead of es2015 
* Upgrade babel-cli and babel-core
@CodeNinjai @frol @cliffano

[JavaScript] Use babel-preset-env instead of es2015

---

modules/swagger-codegen/src/main/resources/typescript-fetch/api.mustache
samples/client/petstore/typescript-fetch/builds/default/api.ts
samples/client/petstore/typescript-fetch/builds/es6-target/api.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/api.ts

Fixes #6772
Change the return type of API methods for which a response schema is not available to reflect that they return a `Promise<Response>` (instead of `Promise<any>`).
@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx

Change return type from any -> Response

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/InlineModelResolver.java

Fix RefProperty bug for flattening MapProperty's inner properties.

---

modules/swagger-codegen/src/main/resources/elixir/request_builder.ex.mustache
samples/client/petstore/elixir/lib/swagger_petstore/api/fake.ex
samples/client/petstore/elixir/lib/swagger_petstore/request_builder.ex

Fix following dialyzer warnings in the sample:
<details>
```
lib/swagger_petstore/api/another_fake.ex:30: Function test_special_tags/2 has no local return
lib/swagger_petstore/api/another_fake.ex:30: Function test_special_tags/3 has no local return
lib/swagger_petstore/api/another_fake.ex:32: The call 'Elixir.SwaggerPetstore.RequestBuilder':method(#{},'patch') breaks the contract (map(),'Elixir.String':t()) -> map()
lib/swagger_petstore/api/fake.ex:29: Function fake_outer_boolean_serialize/1 has no local return
lib/swagger_petstore/api/fake.ex:29: Function fake_outer_boolean_serialize/2 has no local return
lib/swagger_petstore/api/fake.ex:34: The call 'Elixir.SwaggerPetstore.RequestBuilder':method(#{},'post') breaks the contract (map(),'Elixir.String':t()) -> map() …
```

[Elixir Client]Improve elixir client typings

---

modules/swagger-codegen/src/main/resources/ruby/partial_model_enum_class.mustache
samples/client/petstore/ruby/lib/petstore/models/enum_class.rb
samples/client/petstore/ruby/lib/petstore/models/outer_enum.rb

Modify build_from_hash to compare the given value against the enum's value rather than the enum's constant name.
Unless I'm missing something, it seems to me that this should be the desired behavior for build_from_hash.
For instance, consider the following Ruby enum class:
```
class Enum
ENUM1 = "enum 1"
ENUM2 = "enum 2"
ENUM3 = "enum 3"
def build_from_hash(value)
...
end
end
```
If we run the following:
```
Enum.new.build_from_hash("enum 2")
```
It'll return "enum 2".
Before this fix, it would return an error since we were comparing "enum 2" against the constant names "ENUM1", "ENUM2" and "ENUM3".
Hope this makes sense!

[Ruby] Fix "build_from_hash" function for Ruby enums

---

README.md

Updated information for .swagger-codegen-ignore support via IntelliJ plugin, and path override.
I noticed the `--ignore-file-override` wasn't mentioned in the README, nor was the plugin support for IntelliJ.

[.swagger-codegen-ignore] Update README.md

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RustClientCodegen.java
modules/swagger-codegen/src/main/resources/rust/Cargo.mustache
modules/swagger-codegen/src/main/resources/rust/model.mustache
samples/client/petstore/rust/Cargo.toml
samples/client/petstore/rust/src/models/api_response.rs
samples/client/petstore/rust/src/models/category.rs
samples/client/petstore/rust/src/models/order.rs
samples/client/petstore/rust/src/models/pet.rs
samples/client/petstore/rust/src/models/tag.rs
samples/client/petstore/rust/src/models/user.rs
samples/server/petstore/rust-server/README.md
samples/server/petstore/rust-server/api/swagger.yaml
samples/server/petstore/rust-server/examples/client.rs
samples/server/petstore/rust-server/examples/server_lib/mod.rs
samples/server/petstore/rust-server/src/client.rs
samples/server/petstore/rust-server/src/lib.rs
samples/server/petstore/rust-server/src/mimetypes.rs
samples/server/petstore/rust-server/src/server.rs

This contains 2 fixes for the rust codegen.
First, the TODO for "Object" was replaced with the `serde_json::Value` type.
This at least makes it compile; I haven't ensured runtime functionality is correct, but it's certainly no worse than before.
Second, I've updated the provided `Cargo.toml` to include rough version selectors. They correspond to what it's picking now, but will future-proof it a bit more against external crate changes.
cc @frol @farcaller

[Rust] Implement 'object' type conversion

---

modules/swagger-codegen/src/main/resources/php/api.mustache
samples/client/petstore-security-test/php/SwaggerClient-php/lib/Api/FakeApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/AnotherFakeApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/FakeApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/FakeClassnameTags123Api.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/PetApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/StoreApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/UserApi.php
samples/client/petstore/php/SwaggerClient-php/tests/DebugTest.php

[PHP] Fix #6770: Debug flag is not passed

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractTypeScriptClientCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/typescript/fetch/TypeScriptFetchModelTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/typescript/typescriptangular/TypeScriptAngularModelTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/typescript/typescriptangularjs/TypeScriptAngularJsModelTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/typescript/typescriptnode/TypeScriptNodeModelTest.java

Fixes #6765.
Added a method to set the default values for TypeScript conversions.

Add TypeScript default value mappers

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConstants.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/KotlinClientCodegen.java
modules/swagger-codegen/src/main/resources/kotlin-client/data_class.mustache
modules/swagger-codegen/src/main/resources/kotlin-client/enum_class.mustache
modules/swagger-codegen/src/test/java/io/swagger/codegen/kotlin/KotlinClientCodegenOptionsTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/KotlinClientCodegenOptionsProvider.java

See #6830 This should resolve issues with nested enums, as well as providing a CLI option to allow for customization of enums. For example:
```
--additional-properties=enumPropertyNaming=PascalCase
```
Default is camelCase, which removes hyphens and underscores. I'd be happy to change the default if there's enough concern.

[kotlin] Nested enum naming fix, and naming options via CLI

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java

New error message when an unsupported library is specified:
For example, passing `--library asdfasdfasdf` to the java client generator:
```
Removing files and folders under samples/client/petstore/java/feign/src/main
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
Exception in thread "main" java.lang.RuntimeException: Unknown library: asdfasdfasdf
Available libraries:
jersey1
feign
jersey2
okhttp-gson
retrofit
retrofit2
resttemplate
resteasy
vertx
at io.swagger.codegen.DefaultCodegen.setLibrary(DefaultCodegen.java:3394)
at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:421)
at io.swagger.codegen.cmd.Generate.run(Generate.java:283)
at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35 …
```

[all] Better error message for missing libraries

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCppCodegen.java
samples/client/petstore/cpprest/model/Order.cpp
samples/client/petstore/cpprest/model/Order.h
samples/client/petstore/cpprest/model/Pet.h
samples/client/petstore/qt5cpp/client/SWGOrder.cpp
samples/client/petstore/qt5cpp/client/SWGOrder.h
samples/server/petstore/restbed/model/Order.cpp
samples/server/petstore/restbed/model/Order.h

[C++] Updated C++ generators to name boolean getters correctly

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/KotlinClientCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/kotlin/KotlinClientCodegenModelTest.java
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/models/ApiResponse.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/models/Category.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/models/Order.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/models/Pet.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/models/Tag.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/models/User.kt

Kotlin names weren't being cleanly sanitized. This adds some additional constraints related to kotlin.
See #6864.

Kotlin sanitize model names 6864

---

modules/swagger-codegen/src/main/resources/flaskConnexion/util.mustache
modules/swagger-codegen/src/main/resources/python/api_client.mustache
samples/client/petstore/python-asyncio/docs/FakeApi.md
samples/client/petstore/python-asyncio/petstore_api/api_client.py
samples/client/petstore/python-tornado/docs/FakeApi.md
samples/client/petstore/python-tornado/petstore_api/api_client.py
samples/client/petstore/python/docs/FakeApi.md
samples/client/petstore/python/petstore_api/api_client.py
samples/server/petstore/flaskConnexion-python2/swagger_server/util.py
samples/server/petstore/flaskConnexion/swagger_server/util.py

`unicode` does not exist in py3, therefore since six is already imported
switch to using `six.u` so that `unicode` is used on py2 and `str` is used
on py3.
@taxpon  @frol  @mbohlool  @cbornet
CC @wing328

[python] Convert unicode to six.u

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java

Body parameter can be optional so we can't always add it to the required parameter list.

Minor fix to body parameter in required parameter list

---

modules/swagger-codegen/src/main/resources/php-symfony/Controller.mustache

[PHP][Symfony] Update Controller.mustache

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CppRestClientCodegen.java
modules/swagger-codegen/src/main/resources/cpprest/api-source.mustache
modules/swagger-codegen/src/main/resources/cpprest/apiclient-header.mustache
modules/swagger-codegen/src/main/resources/cpprest/apiclient-source.mustache
modules/swagger-codegen/src/main/resources/cpprest/apiconfiguration-source.mustache
modules/swagger-codegen/src/main/resources/cpprest/model-source.mustache
modules/swagger-codegen/src/main/resources/cpprest/modelbase-header.mustache
modules/swagger-codegen/src/main/resources/cpprest/modelbase-source.mustache
samples/client/petstore/cpprest/ApiClient.cpp
samples/client/petstore/cpprest/ApiClient.h
samples/client/petstore/cpprest/ApiConfiguration.cpp
samples/client/petstore/cpprest/ModelBase.cpp
samples/client/petstore/cpprest/ModelBase.h
samples/client/petstore/cpprest/api/PetApi.cpp
samples/client/petstore/cpprest/api/StoreApi.cpp
samples/client/petstore/cpprest/api/UserApi.cpp
samples/client/petstore/cpprest/model/ApiResponse.cpp
samples/client/petstore/cpprest/model/Category.cpp
samples/client/petstore/cpprest/model/Order.cpp
samples/client/petstore/cpprest/model/Pet.cpp
samples/client/petstore/cpprest/model/Tag.cpp
samples/client/petstore/cpprest/model/User.cpp

This PR removes all usages of the infamous casablanca `U(x)` macro, and replaces them with a safer conversion function (also provided by casablanca).
The rationale for this change is that users of the generator might need to disable that macro entirely in casablanca, as it can easily cause conflicts (see [the Casablanca FAQ](https://github.com/Microsoft/cpprestsdk/wiki/FAQ#what-is-utilitystring_t-and-the-u-macro) for more info). The generated code should therefore not rely on it.
I've updated the sample code accordingly and managed to compile it without any problems.
This change has also been tested on code generated for actual (non-public) APIs successfully.

[CppRest] Remove U macro

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CppRestClientCodegen.java
modules/swagger-codegen/src/main/resources/cpprest/api-header.mustache
modules/swagger-codegen/src/main/resources/cpprest/apiclient-header.mustache
modules/swagger-codegen/src/main/resources/cpprest/apiconfiguration-header.mustache
modules/swagger-codegen/src/main/resources/cpprest/apiexception-header.mustache
modules/swagger-codegen/src/main/resources/cpprest/httpcontent-header.mustache
modules/swagger-codegen/src/main/resources/cpprest/ihttpbody-header.mustache
modules/swagger-codegen/src/main/resources/cpprest/jsonbody-header.mustache
modules/swagger-codegen/src/main/resources/cpprest/model-header.mustache
modules/swagger-codegen/src/main/resources/cpprest/modelbase-header.mustache
modules/swagger-codegen/src/main/resources/cpprest/multipart-header.mustache
samples/client/petstore/cpprest/ApiClient.h
samples/client/petstore/cpprest/ApiConfiguration.h
samples/client/petstore/cpprest/ApiException.h
samples/client/petstore/cpprest/HttpContent.h
samples/client/petstore/cpprest/IHttpBody.h
samples/client/petstore/cpprest/JsonBody.h
samples/client/petstore/cpprest/ModelBase.h
samples/client/petstore/cpprest/MultipartFormData.h
samples/client/petstore/cpprest/api/PetApi.h
samples/client/petstore/cpprest/api/StoreApi.h
samples/client/petstore/cpprest/api/UserApi.h
samples/client/petstore/cpprest/model/ApiResponse.h
samples/client/petstore/cpprest/model/Category.h
samples/client/petstore/cpprest/model/Order.h
samples/client/petstore/cpprest/model/Pet.h
samples/client/petstore/cpprest/model/Tag.h
samples/client/petstore/cpprest/model/User.h

This PR adds package names in the generated header guards, in order to avoid clashes when generating code from two or more different API spec files.
I've updated the sample code accordingly and managed to compile it without any problems.
This change has also been tested successfully on a codebase where two separate APIs coexist (which wasn't possible at all before).

[CppRest] Unique header guards

---

modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
samples/client/petstore-security-test/java/okhttp-gson/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore-security-test/java/okhttp-gson/src/main/java/io/swagger/client/api/FakeApi.java
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/okhttp-gson/src/test/java/io/swagger/client/ApiClientTest.java

based ApiClients
adding "Write Timeout" getters and setters for the OkHttp based
ApiClient
adding tests for the OkHttpClient covering the new getters and setters
- [X ] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
added getters and setters in the ApiClient mustache file for the OkHttp's read and write timeout settings
added getters and setters for the Jersey ApiClient mustache file for the Jersey read timeout property
added tests for the ApiClient settings

adding "Read Timeout" getters and setters for the Jersey and OkHttp

---

modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/pojo.mustache
samples/client/petstore/jaxrs-cxf-client/src/gen/java/io/swagger/model/Order.java
samples/client/petstore/jaxrs-cxf-client/src/gen/java/io/swagger/model/Pet.java
samples/server/petstore/jaxrs-cxf-annotated-base-path/src/gen/java/io/swagger/model/Order.java
samples/server/petstore/jaxrs-cxf-annotated-base-path/src/gen/java/io/swagger/model/Pet.java
samples/server/petstore/jaxrs-cxf-non-spring-app/src/gen/java/io/swagger/model/Order.java
samples/server/petstore/jaxrs-cxf-non-spring-app/src/gen/java/io/swagger/model/Pet.java
samples/server/petstore/jaxrs-cxf/src/gen/java/io/swagger/api/FakeApi.java
samples/server/petstore/jaxrs-cxf/src/gen/java/io/swagger/model/EnumArrays.java
samples/server/petstore/jaxrs-cxf/src/gen/java/io/swagger/model/EnumTest.java
samples/server/petstore/jaxrs-cxf/src/gen/java/io/swagger/model/Order.java
samples/server/petstore/jaxrs-cxf/src/gen/java/io/swagger/model/Pet.java
samples/server/petstore/jaxrs-cxf/src/main/java/io/swagger/api/impl/FakeApiServiceImpl.java

I respect the values of the enumerations when transforming JSON/XML to Java Objects in the CXF Server stub and Client generation. 
fix #6694
@bbdouglas, @JFCote, @sreeshas, @jfiala, @lukoyanov, @cbornet, @wing328

Issue 6694 2.3.0

---

.travis.yml
pom.xml

The MacOS image does not seem very stable and timeout occurs more and more often. We'll switch back to Linux.

Switch Travis image from MacOS to Linux

---

modules/swagger-codegen/src/main/resources/qt5cpp/model-body.mustache

The issue #6884 is still present and requires fixing outside of mustache file as well.
Petstore is not impacted by this change. No changes in Petstore examples.
Verified the changes with modified docker swagger yaml.
Docker swagger yaml does not compile fully due to other issues.

[qt5cpp] Fixes Issue #6841, Map for accessing additionalProperties is generated.

---

modules/swagger-codegen/src/main/resources/php/api.mustache
samples/client/petstore/php/SwaggerClient-php/docs/Api/FakeApi.md
samples/client/petstore/php/SwaggerClient-php/lib/Api/AnotherFakeApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/FakeApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/FakeClassnameTags123Api.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/PetApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/StoreApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/UserApi.php

Add a missing parameter when create an ApiException: body response.
With this patch, we will be able to get the full error, not the trucated one, when we catch the ApiException.
This should not break anythink since it's an optionnal parameter which was not set before and set from this patch.
-------
@jebentier (2017/07) @dkarlovi (2017/07) @mandrean (2017/08) @jfastnacht (2017/09) @ackintosh (2017/09)

Fix PHP passes response body to ApiException

---

modules/swagger-codegen/src/main/resources/swift4/CodableHelper.mustache
samples/client/petstore/swift4/default/PetstoreClient/Classes/Swaggers/CodableHelper.swift
samples/client/petstore/swift4/promisekit/PetstoreClient/Classes/Swaggers/CodableHelper.swift
samples/client/petstore/swift4/rxswift/PetstoreClient/Classes/Swaggers/CodableHelper.swift

Setting a custom date format to be used on decoding. 
My server response date uses the format `YYYY-MM-DD'T'HH:mm:ss.sssZ`, I needed a way to set DateFormatter on the decoding of the data models. Suggest allowing for a custom DateFormat to be used in `CodableHelper`. 
Usage:
```
// Custom Date
let dateFormat = DateFormatter()
dateFormat.dateFormat = "YYYY-MM-DD'T'HH:mm:ss.sssZ" // "2017-10-12T17:03:21.000Z"
CodableHelper.dateformatter = dateFormat
```
Suggested code change in `CodableHelper`
```
// Allow for custom date formatter to be used
open static var dateformatter: DateFormatter?
// Check if formatter is set, else fallback to default values
let decoder = JSONDecoder()
if let df = self.dateformatter {
decoder.dateDecodingStrategy = .formatted(df)
} else {
decoder.dateDecodingStrategy …
```

[Swift4] Allow for custom dateformatter to be used

---

modules/swagger-generator/pom.xml

Had problems getting the swagger-api download set in pom.xml on http.  I assume this is to networking issues that other people could have as well so I updated this.
@wing328

Updated swagger-ui wget url to https

---

circle.yml

Added a docker build tag to the circle.yml file so that when the images are pushed, a version tag is pushed as well at latest.
fix #6728

Docker image tags

---

modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/ApiClient.mustache

https://github.com/swagger-api/swagger-codegen/pull/6853 added a getter and setter for `readTimeout` in the ApiClient.mustache template for the jersey2 "sub-template". However, the `readTimeout` field does not exist in `ApiClient.java`, so the generated client cannot be compiled. This is a one-line change to add `readTimeout` to the template.
~The second commit (b04a360c5) is the result of `./bin/java-petstore-all.sh`, and contains many changes unrelated to the first commit.~ I backed out this change -- I'm pretty sure it's unrelated to the fix I'm trying to make, and deleting the google-api-client sample causes the CI tests to fail.
cc @bbdouglas @JFCote @sreeshas @jfiala @lukoyanov @cbornet @normana400

[Java/jersey2] Add readTimeout field

---

modules/swagger-codegen/src/main/resources/python/tornado/rest.mustache
samples/client/petstore/python-tornado/Makefile
samples/client/petstore/python-tornado/docs/FakeApi.md
samples/client/petstore/python-tornado/git_push.sh
samples/client/petstore/python-tornado/petstore_api/rest.py
samples/client/petstore/python-tornado/test_python2_and_3.sh
samples/client/petstore/python-tornado/tests/test_pet_api.py
samples/client/petstore/python/docs/FakeApi.md
samples/client/petstore/python/git_push.sh
samples/client/petstore/python/test_python2.sh
samples/client/petstore/python/test_python2_and_3.sh
samples/client/petstore/python/tests/test_pet_api.py

Fixes related to:
1. Travis doesn't know that tests fail because an exit codes from bash scripts are always zero - fixed
2. Tornado client doesn't work in python < 2.7.9 - fixed
3. Some tests are skipped because public PetStore endpoint has incorrect data. Travis use local instance of PetStore server and all test can run. I removed `@skip` and also force endpoint name to `localhost`. IMO it'll remind developers about starting a local instance. #6907 
Please take a look: @wing328 @taxpon @frol @mbohlool @cbornet @kenjones-cisco

[python] fix tests, tornado ssl fix

---

modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/ApiClient.mustache

Removal of content-type check in Jersey2

---

modules/swagger-codegen/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache

@cbornet bugfix suggestion for  #6976 Change for Java(resttemplate)

- fix duplicate problem

---

modules/swagger-codegen/src/main/resources/typescript-angular/api.service.mustache
modules/swagger-codegen/src/main/resources/typescript-angular/configuration.mustache
samples/client/petstore/typescript-angular-v2/default/api/pet.service.ts
samples/client/petstore/typescript-angular-v2/default/api/store.service.ts
samples/client/petstore/typescript-angular-v2/default/api/user.service.ts
samples/client/petstore/typescript-angular-v2/default/configuration.ts
samples/client/petstore/typescript-angular-v2/default/git_push.sh
samples/client/petstore/typescript-angular-v2/npm/api/pet.service.ts
samples/client/petstore/typescript-angular-v2/npm/api/store.service.ts
samples/client/petstore/typescript-angular-v2/npm/api/user.service.ts
samples/client/petstore/typescript-angular-v2/npm/configuration.ts
samples/client/petstore/typescript-angular-v2/npm/git_push.sh
samples/client/petstore/typescript-angular-v2/with-interfaces/api/pet.service.ts
samples/client/petstore/typescript-angular-v2/with-interfaces/api/store.service.ts
samples/client/petstore/typescript-angular-v2/with-interfaces/api/user.service.ts
samples/client/petstore/typescript-angular-v2/with-interfaces/configuration.ts
samples/client/petstore/typescript-angular-v2/with-interfaces/git_push.sh
samples/client/petstore/typescript-angular-v2/with-interfaces/package.json
samples/client/petstore/typescript-angular-v4.3/npm/api/pet.service.ts
samples/client/petstore/typescript-angular-v4.3/npm/api/store.service.ts
samples/client/petstore/typescript-angular-v4.3/npm/api/user.service.ts
samples/client/petstore/typescript-angular-v4.3/npm/configuration.ts
samples/client/petstore/typescript-angular-v4.3/npm/git_push.sh
samples/client/petstore/typescript-angular-v4/npm/api/pet.service.ts
samples/client/petstore/typescript-angular-v4/npm/api/store.service.ts
samples/client/petstore/typescript-angular-v4/npm/api/user.service.ts
samples/client/petstore/typescript-angular-v4/npm/configuration.ts
samples/client/petstore/typescript-angular-v4/npm/git_push.sh

- [x ] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.
@sebastianhaas @TiFu @taxpon @kenisteward @Vrolijkx 
if  in  tsconfig.json file "strict": true,  current master does not compiled
fix it  so it compiles 
compilation errors 
36             return undefined;
~~~~~~~~~~~~~~~~~
src/app/core/generated/configuration.ts(36,13): error TS2322: Type 'undefined' is not assignable to type 'string'.
55 …

[TypeScript][Angular] fix problem with strict compilation

---

Dockerfile

Based on discussions in #6836, this is a modification to the root Dockerfile which is intended to allow developers a clean sandbox to evaluate local changes.
NOTES:
1. This image is not the image published to [swaggerapi/swagger-codegen-cli](https://hub.docker.com/r/swaggerapi/swagger-codegen-cli/) or [swaggerapi/swagger-generator](https://hub.docker.com/r/swaggerapi/swagger-generator/).  Those images are containers encapsulating the compiled .jars and a java runtime for each.
2. I've removed swagger-generator from being cached within this image. The assumption here is that anyone working on local swagger-generator modifications will likely be running that locally. Since this root Dockerfile is specifically setup to run as the locally modified CLI code, it doesn't make a lot of sense to …

[docker] Update root Dockerfile

---

modules/swagger-codegen/src/main/resources/cpprest/api-header.mustache
modules/swagger-codegen/src/main/resources/cpprest/api-source.mustache
samples/client/petstore/cpprest/api/PetApi.cpp
samples/client/petstore/cpprest/api/PetApi.h
samples/client/petstore/cpprest/api/StoreApi.h
samples/client/petstore/cpprest/api/UserApi.cpp
samples/client/petstore/cpprest/api/UserApi.h

This PR adds support for optional parameters (those marked as `required: false` in a swagger spec) using `boost::optional`.
Users of the client code can now pass `boost::none` to API calls for any optional parameters they are not interested in using.
Notes:
- `in: path` params are not covered because they cannot be optional (see [OpenAPI spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterObject)).
- `in: body` params are also not covered, as the implementation would be less trivial. The current behaviour for those params doesn't change, i.e. they are always required to make a call.
- This doesn't add any new linking dependencies as `boost::optional` is header-only, and `boost` itself is already required to compile the generated client code.

[CppRest] Support optional parameters

---

modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/JSON.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/build.gradle.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/build.sbt.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/pom.mustache
samples/client/petstore/java/okhttp-gson/build.gradle
samples/client/petstore/java/okhttp-gson/build.sbt
samples/client/petstore/java/okhttp-gson/pom.xml
samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/JSON.java

Inheritance support for okhttp with gson parser.
@cbornet  Can you please take a look?

Inheritance support java client okhttp gson

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FlaskConnexionCodegen.java
samples/server/petstore/flaskConnexion-python2/git_push.sh
samples/server/petstore/flaskConnexion-python2/swagger_server/swagger/swagger.yaml
samples/server/petstore/flaskConnexion/git_push.sh
samples/server/petstore/flaskConnexion/swagger_server/swagger/swagger.yaml

Removed the "special" logic to use the last part of the operationId (separated by dot)
Reused the same logic in python client's "toOperationId"
(this will help us more easily create a common abstract class "AbstractPythonCodegen" later. 
To close https://github.com/swagger-api/swagger-codegen/issues/7015

[Python][Flask] use python client's "toOperationId"

---

modules/swagger-codegen/src/main/resources/typescript-angular/api.service.mustache
modules/swagger-generator/pom.xml
samples/client/petstore/typescript-angular-v2/default/api/pet.service.ts
samples/client/petstore/typescript-angular-v2/default/api/store.service.ts
samples/client/petstore/typescript-angular-v2/default/api/user.service.ts
samples/client/petstore/typescript-angular-v2/default/git_push.sh
samples/client/petstore/typescript-angular-v2/npm/api/pet.service.ts
samples/client/petstore/typescript-angular-v2/npm/api/store.service.ts
samples/client/petstore/typescript-angular-v2/npm/api/user.service.ts
samples/client/petstore/typescript-angular-v2/npm/git_push.sh
samples/client/petstore/typescript-angular-v2/with-interfaces/api/pet.service.ts
samples/client/petstore/typescript-angular-v2/with-interfaces/api/store.service.ts
samples/client/petstore/typescript-angular-v2/with-interfaces/api/user.service.ts
samples/client/petstore/typescript-angular-v2/with-interfaces/git_push.sh
samples/client/petstore/typescript-angular-v2/with-interfaces/package.json
samples/client/petstore/typescript-angular-v4.3/npm/api/pet.service.ts
samples/client/petstore/typescript-angular-v4.3/npm/api/store.service.ts
samples/client/petstore/typescript-angular-v4.3/npm/api/user.service.ts
samples/client/petstore/typescript-angular-v4.3/npm/git_push.sh
samples/client/petstore/typescript-angular-v4/npm/api/pet.service.ts
samples/client/petstore/typescript-angular-v4/npm/api/store.service.ts
samples/client/petstore/typescript-angular-v4/npm/api/user.service.ts
samples/client/petstore/typescript-angular-v4/npm/git_push.sh

Fixes #6902 with some added bonuses
@bedag-moo @HermenOtter Gonna need you 2 to test this as i'm not currently running angular ^4.3 Will be upgrading to 5 very soon though.
Note: For overloads to work with proper intellisense the first overload must always be for 'body'.  if any changes are made to the overload that rearranges them intellisense will break and confuse consumers
@TiFu @taxpon  @sebastianhaas  @Vrolijkx

[Typescript][Angular]Issue #6902 Return Client Response for Angular 4.3 and above with Observe string

---

modules/swagger-codegen/src/main/resources/typescript-angular/api.service.mustache
modules/swagger-codegen/src/main/resources/typescript-angular/rxjs-operators.mustache
samples/client/petstore/typescript-angular-v2/default/git_push.sh
samples/client/petstore/typescript-angular-v2/default/rxjs-operators.ts
samples/client/petstore/typescript-angular-v2/npm/git_push.sh
samples/client/petstore/typescript-angular-v2/npm/rxjs-operators.ts
samples/client/petstore/typescript-angular-v2/with-interfaces/git_push.sh
samples/client/petstore/typescript-angular-v2/with-interfaces/package.json
samples/client/petstore/typescript-angular-v2/with-interfaces/rxjs-operators.ts
samples/client/petstore/typescript-angular-v4.3/npm/api/pet.service.ts
samples/client/petstore/typescript-angular-v4.3/npm/api/store.service.ts
samples/client/petstore/typescript-angular-v4.3/npm/api/user.service.ts
samples/client/petstore/typescript-angular-v4.3/npm/git_push.sh
samples/client/petstore/typescript-angular-v4.3/npm/rxjs-operators.ts
samples/client/petstore/typescript-angular-v4/npm/git_push.sh
samples/client/petstore/typescript-angular-v4/npm/rxjs-operators.ts

Remove rxjs operators

---

modules/swagger-codegen/src/main/resources/php-symfony/serialization/JmsSerializer.mustache
samples/server/petstore/php-symfony/SymfonyBundle-php/README.md
samples/server/petstore/php-symfony/SymfonyBundle-php/Service/JmsSerializer.php
samples/server/petstore/php-symfony/SymfonyBundle-php/git_push.sh
samples/server/petstore/php-symfony/SymfonyBundle-php/phpunit.xml.dist

For the PHP Symfony generation this import
```php
use` Swagger\Server\Service\StrictJsonDeserializationVisitor;
```  
is wrong as the class is sitting in the same package as the JMSSerializer class.
This results in exception when the serializer is used
@jebentier  @dkarlovi  @mandrean  @jfastnacht  @ackintosh @naelrashdeen

Removed wrong import of StrictJsonDeserializationVisitor

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SymfonyServerCodegen.java
modules/swagger-codegen/src/main/resources/php-symfony/api.mustache
modules/swagger-codegen/src/main/resources/php-symfony/api_controller.mustache
modules/swagger-codegen/src/main/resources/php-symfony/api_input_validation.mustache
modules/swagger-codegen/src/main/resources/php-symfony/model_generic.mustache
modules/swagger-codegen/src/main/resources/php-symfony/model_variables.mustache
modules/swagger-codegen/src/main/resources/php-symfony/serialization/JmsSerializer.mustache
samples/server/petstore/php-symfony/SymfonyBundle-php/Api/PetApiInterface.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Api/StoreApiInterface.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Api/UserApiInterface.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Controller/PetController.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Controller/StoreController.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Controller/UserController.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Model/Pet.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Resources/docs/Api/PetApiInterface.md
samples/server/petstore/php-symfony/SymfonyBundle-php/Resources/docs/Api/StoreApiInterface.md
samples/server/petstore/php-symfony/SymfonyBundle-php/Resources/docs/Api/UserApiInterface.md
samples/server/petstore/php-symfony/SymfonyBundle-php/Resources/docs/Model/Pet.md
samples/server/petstore/php-symfony/SymfonyBundle-php/Service/JmsSerializer.php

The current PHP Symfony needs some further changes, which are described below: 
* Headers are not being fetched properly in the request
* Objects should be mapped to arrays instead, in the model classes to be compatible with Symfony type validation
* Deserialising arrays as collection formats are not working properly
* Correct data type is not set in the comments for the Api interfaces
Closes #6999

[PHP][Symfony] Further enhancements

---

modules/swagger-codegen/src/main/resources/scala/api.mustache
samples/client/petstore-security-test/scala/git_push.sh
samples/client/petstore-security-test/scala/pom.xml
samples/client/petstore-security-test/scala/src/main/scala/io/swagger/client/api/FakeApi.scala
samples/client/petstore/scala/git_push.sh

Defaults `Option` parameters to `None` which makes method calls and models less verbose.

[Scala] Default Option parameters to None

---

modules/swagger-codegen/src/main/resources/python/tornado/rest.mustache
samples/client/petstore/python-tornado/petstore_api/rest.py

In my last PR (https://github.com/swagger-api/swagger-codegen/pull/6968) I had to add some hack to disable SSL in older versions of Python. I looked into the implementation and I found that Tornado also didn't support older version of SSL in Python for security reasons (https://github.com/tornadoweb/tornado/pull/2177). Moreover it implements everything we need and also there is a notice about pycurl which doesn't work with SSLContext. Finally I switched to their implementation and it's simple and works correctly with SimpleAsyncHTTPClient and CurlAsyncHTTPClient.
Question: Do we have something to test SSL in CI pipeline ?
Please take a look: @wing328 @taxpon @frol @mbohlool @cbornet @kenjones-cisco @toumorokoshi

[python/tornado] ssl improvements

---

modules/swagger-codegen/src/main/resources/JavaSpring/libraries/spring-cloud/clientConfiguration.mustache

remove leading space
PR checklist
Read the contribution guidelines.
[no need] Ran the shell script under ./bin/ to update Petstore sample so that CIs can verify the change. (For instance, only need to run ./bin/{LANG}-petstore.sh and ./bin/security/{LANG}-petstore.sh if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in .\bin\windows\.
[Master] Filed the PR against the correct branch: 3.0.0 branch for changes related to OpenAPI spec 3.0. Default: master.
Copied the technical committee to review the pull request if your PR is targeting a particular programming language.
Description of …

fix spring cloud config variable names

---

modules/swagger-codegen/src/main/resources/Java/libraries/resttemplate/api.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/api.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/play24/api.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/play25/api.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf-cdi/api.mustache
modules/swagger-codegen/src/main/resources/apex/api.mustache
modules/swagger-codegen/src/main/resources/bash/client.mustache
modules/swagger-codegen/src/main/resources/cpprest/api-source.mustache
modules/swagger-codegen/src/main/resources/php-symfony/api_controller.mustache
modules/swagger-codegen/src/main/resources/tizen/api-body.mustache
modules/swagger-codegen/src/main/resources/ze-ph/api.mustache

To avoid issue with HTML-escaped characters in the `consumes`, `produces`

Use {{{mediaType}} instead of {{mediaType}}

---

modules/swagger-codegen/src/main/resources/MSF4J/api.mustache
samples/server/petstore/java-msf4j/pom.xml
samples/server/petstore/java-msf4j/src/gen/java/io/swagger/api/AnotherFakeApi.java
samples/server/petstore/java-msf4j/src/gen/java/io/swagger/api/AnotherFakeApiService.java
samples/server/petstore/java-msf4j/src/gen/java/io/swagger/api/FakeApi.java
samples/server/petstore/java-msf4j/src/gen/java/io/swagger/api/FakeApiService.java
samples/server/petstore/java-msf4j/src/gen/java/io/swagger/api/FakeClassnameTestApi.java
samples/server/petstore/java-msf4j/src/gen/java/io/swagger/api/PetApi.java
samples/server/petstore/java-msf4j/src/gen/java/io/swagger/api/StoreApi.java
samples/server/petstore/java-msf4j/src/gen/java/io/swagger/api/UserApi.java
samples/server/petstore/java-msf4j/src/gen/java/io/swagger/model/Cat.java
samples/server/petstore/java-msf4j/src/gen/java/io/swagger/model/Order.java
samples/server/petstore/java-msf4j/src/main/java/io/swagger/api/factories/AnotherFakeApiServiceFactory.java
samples/server/petstore/java-msf4j/src/main/java/io/swagger/api/impl/AnotherFakeApiServiceImpl.java
samples/server/petstore/java-msf4j/src/main/java/io/swagger/api/impl/FakeApiServiceImpl.java

Use {{returnBaseType}} to fix the annotation

[Java][MSF4J] fix return type annotation

---

modules/swagger-codegen/src/main/resources/aspnetcore/controller.mustache
samples/server/petstore/aspnetcore/src/IO.Swagger/Controllers/PetApi.cs
samples/server/petstore/aspnetcore/src/IO.Swagger/Controllers/StoreApi.cs
samples/server/petstore/aspnetcore/src/IO.Swagger/Controllers/UserApi.cs
samples/server/petstore/aspnetcore/src/IO.Swagger/Models/Order.cs
samples/server/petstore/aspnetcore/src/IO.Swagger/Models/Pet.cs
samples/server/petstore/aspnetcore/src/IO.Swagger/project.json

@mandrean @jimschubert
#7097 
This uses this.StatusCode(..) to render more verbose STUBS for the Controllers.
So people that are less familiar with ASP.NET Core can understand how it works..

Operation now returns StatusCode Stubs as well

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptJqueryClientCodegen.java
modules/swagger-codegen/src/main/resources/typescript-fetch/README.mustache
modules/swagger-codegen/src/main/resources/typescript-jquery/README.mustache
samples/client/petstore/typescript-fetch/builds/default/api.ts
samples/client/petstore/typescript-fetch/builds/default/git_push.sh
samples/client/petstore/typescript-fetch/builds/es6-target/README.md
samples/client/petstore/typescript-fetch/builds/es6-target/api.ts
samples/client/petstore/typescript-fetch/builds/es6-target/git_push.sh
samples/client/petstore/typescript-fetch/builds/with-npm-version/README.md
samples/client/petstore/typescript-fetch/builds/with-npm-version/api.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/git_push.sh
samples/client/petstore/typescript-jquery/default/git_push.sh
samples/client/petstore/typescript-jquery/npm/README.md
samples/client/petstore/typescript-jquery/npm/git_push.sh

Add the readme.md that I think was removed when I've done the refactoring a couple of months ago.

[Typescript jQuery] Add README.md

---

modules/swagger-codegen/src/main/resources/ruby/partial_model_generic.mustache

Changes a typo, that's all.
@cliffano @zlx
After running the `./bin/ruby-petshore.sh` and `./bin/security/ruby-petstore.sh` it generated diff in the samples which I'm not sure is correct/incorrect, therefore I didn't add it in the commit.
The diff is
```
diff --git a/samples/client/petstore-security-test/ruby/git_push.sh b/samples/client/petstore-security-test/ruby/git_push.sh
index 7cb1edb..89eb49e 100644
--- a/samples/client/petstore-security-test/ruby/git_push.sh
+++ b/samples/client/petstore-security-test/ruby/git_push.sh
@@ -39,7 +39,7 @@ git_remote=`git remote`
if [ "$git_remote" = "" ]; then # git remote not defined
if [ "$GIT_TOKEN" = "" ]; then
-        echo "[INFO] \$GIT_TOKEN (environment variable) is not set. Using the git crediential in your environment."
+        echo …
```

[Ruby] Fix typo

---

modules/swagger-codegen/src/main/resources/finch/build.sbt
modules/swagger-codegen/src/main/resources/scala/api.mustache
modules/swagger-codegen/src/main/resources/scala/apiInvoker.mustache
modules/swagger-codegen/src/main/resources/scala/build.sbt.mustache
modules/swagger-codegen/src/main/resources/scala/client.mustache
modules/swagger-codegen/src/main/resources/scala/model.mustache
modules/swagger-codegen/src/main/resources/scala/pom.mustache
samples/client/petstore-security-test/scala/pom.xml
samples/client/petstore/scala/pom.xml
samples/server/petstore/finch/build.sbt

[Scala] [ISSUE-7085] Scala template code format refactor

---

modules/swagger-codegen/src/main/resources/Java/libraries/resteasy/ApiClient.mustache
samples/client/petstore/java/resteasy/src/main/java/io/swagger/client/ApiClient.java

@bbdouglas 
@JFCote 
@sreeshas 
@jfiala 
@lukoyanov 
@cbornet
The original method accesses the value of a Map entry, using a key that was retrieved from a keySet iterator. It is more efficient to use an iterator on the entrySet of the map, to avoid the Map.get(key) lookup.
http://findbugs.sourceforge.net/bugDescriptions.html#WMI_WRONG_MAP_ITERATOR

Make efficient use of entrySet iterator.

---

samples/client/petstore/php/SwaggerClient-php/tests/PetApiTest.php
samples/client/petstore/php/SwaggerClient-php/tests/StoreApiTest.php

This PR improves the disabled test code in StoreApiTest.

[PHP] Improve StoreApiTest

---

modules/swagger-codegen/src/main/resources/php/api.mustache

@jebentier (2017/07) @dkarlovi (2017/07) @mandrean (2017/08) @jfastnacht (2017/09) @ackintosh (2017/09)
Fixed issue #7137 by checking Response before calling getBody() when catching ApiException

Fixed #7137 by checking for Response before calling getBody() on it

---

modules/swagger-codegen/src/main/resources/typescript-angularjs/api.mustache
samples/client/petstore/typescript-angularjs/git_push.sh

Fixes issue #7134 Wrong "params" indentation

Fix issue 7134 Wrong "params" indentation

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RustServerCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/languages/RustServerCodegenTest.java
samples/client/petstore/rust/git_push.sh

@frol @farcaller 
In rust-server, use rust integer types best matching the `format`, `minimum` and `maximum` schema constraints.
Matching rules cover all rust standard int size, from 8 to 64bits, signed and unsigned, including `size` types.
- `minimum` is used to determine if the int type should be signed. Default is signed.
- `maximum` is used to determine the int size. Default is `isize` or `usize`.
- Standard `formats` `int32` and `int64` can be used to force int size.
- Existing custom formats `uint32` and `uint64` have been preserved, even though they are superseded by new code.
- `minimum` and `maximum` constraints also respects their `exclusive` flags if specified.

Match rust integer type to minimum and maximum constraints

---

bin/windows/go-petstore-server.bat

@antihax
Add missing go-server petstore Windows batch script to address issue #7144

Add missing go-server petstore batch script

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java
modules/swagger-codegen/src/main/resources/aspnetcore/controller.mustache
samples/server/petstore/aspnetcore/src/IO.Swagger/Controllers/PetApi.cs
samples/server/petstore/aspnetcore/src/IO.Swagger/Controllers/StoreApi.cs
samples/server/petstore/aspnetcore/src/IO.Swagger/Controllers/UserApi.cs

RE: Issue #7092, #5423
@mandrean @jimschubert 
Added support for Operation EXAMPLE value in ASP.NET Core Generator.
Now exampleJson is currectly generated.

Added support for Operation EXAMPLE value in ASP.NET Core Generator.

---

modules/swagger-codegen/src/main/resources/bash/client.mustache
samples/client/petstore/bash/README.md
samples/client/petstore/bash/_petstore-cli
samples/client/petstore/bash/docs/FakeApi.md
samples/client/petstore/bash/petstore-cli
samples/client/petstore/bash/petstore-cli.bash-completion
samples/client/petstore/bash/tests/petstore_test.sh

Fixes #7047
Also added an automated test for checking syntax of generated Bash clients.
@MikeRalphson @wing328

#7047 - Added Bash syntax check to tests

---

modules/swagger-codegen/src/main/resources/rust-server/client.mustache
modules/swagger-codegen/src/main/resources/rust-server/example-server.mustache
samples/server/petstore/rust-server/examples/server.rs
samples/server/petstore/rust-server/src/client.rs

The latest version of openssl deprecates some methods, leading to a bunch of warnings appearing. This PR performs the simple fix to use the new API.
Fixes #7133

[rust-server] End use of deprecated openssl method

---

modules/swagger-codegen/src/main/resources/aspnetcore/controller.mustache
samples/server/petstore/aspnetcore/src/IO.Swagger/Controllers/PetApi.cs
samples/server/petstore/aspnetcore/src/IO.Swagger/Controllers/StoreApi.cs
samples/server/petstore/aspnetcore/src/IO.Swagger/Controllers/UserApi.cs

RE: Issue #7094
@mandrean @jimschubert
I've modified the server generator, so that responses with no data are excluded, but multiple responses with their dataType are honored..
```
[Route("/api/parcel/{trackingId}")]
[ValidateModelState]
[SwaggerOperation("TrackParcel")]
[SwaggerResponse(statusCode: 200, type: typeof(TrackingInformation), description: "Parcel exists.")]
[SwaggerResponse(statusCode: 500, type: typeof(Error), description: "The operation failed due to an error.")]
public virtual IActionResult TrackParcel([FromRoute]string trackingId)
```

Updated SwaggerResponse Attributes so they use the actual dataType instead of the common returnType

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractTypeScriptClientCodegen.java
samples/client/petstore/typescript-angularjs/git_push.sh
samples/client/petstore/typescript-aurelia/default/git_push.sh
samples/client/petstore/typescript-fetch/builds/default/api.ts
samples/client/petstore/typescript-fetch/builds/default/git_push.sh
samples/client/petstore/typescript-fetch/builds/es6-target/api.ts
samples/client/petstore/typescript-fetch/builds/es6-target/git_push.sh
samples/client/petstore/typescript-fetch/builds/with-npm-version/api.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/git_push.sh
samples/client/petstore/typescript-jquery/default/git_push.sh
samples/client/petstore/typescript-jquery/npm/git_push.sh
samples/client/petstore/typescript-node/npm/package.json

Reserved keywords were escaped everywhere but for this. I just add it in the `AbstractTypescriptClientCodegen`. I run all the typescript sample I could find. All the changes are not related to my change because the petstore doesn't contain any reserved keyword.

[Typescript All] Prevent usage of reserved keyword for model fields

---

modules/swagger-codegen/src/main/resources/JavaSpring/pojo.mustache

[Java][Spring] One space too many before JavaDoc first line in model methods

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Qt5CPPGenerator.java
modules/swagger-codegen/src/main/resources/qt5cpp/helpers-body.mustache

(cherry picked from commit bfaf253caebe0a8367275aa477d9bc0dcd030adc)
Fixes for #6984

[C++][Qt5] Fixes segmentation faults for arrays of primitive types

---

modules/swagger-codegen/src/test/resources/2_0/petstore.yaml
samples/client/petstore/ada/src/client/samples-petstore-models.ads
samples/html/index.html
samples/html2/index.html
samples/server/petstore/aspnetcore/src/IO.Swagger/wwwroot/swagger-original.json
samples/server/petstore/erlang-server/priv/swagger.json
samples/server/petstore/flaskConnexion-python2/swagger_server/swagger/swagger.yaml
samples/server/petstore/flaskConnexion/swagger_server/swagger/swagger.yaml
samples/server/petstore/go-api-server/api/swagger.yaml
samples/server/petstore/java-play-framework-controller-only/public/swagger.json
samples/server/petstore/java-play-framework-no-bean-validation/public/swagger.json
samples/server/petstore/java-play-framework-no-exception-handling/public/swagger.json
samples/server/petstore/java-play-framework-no-interface/public/swagger.json
samples/server/petstore/java-play-framework-no-wrap-calls/public/swagger.json
samples/server/petstore/java-play-framework/public/swagger.json
samples/server/petstore/java-vertx/async/src/main/resources/swagger.json
samples/server/petstore/java-vertx/rx/src/main/resources/swagger.json
samples/server/petstore/jaxrs-cxf-cdi/swagger.json
samples/server/petstore/nodejs-google-cloud-functions/api/swagger.yaml
samples/server/petstore/nodejs/api/swagger.yaml
samples/server/petstore/sinatra/swagger.yaml
samples/server/petstore/undertow/src/main/resources/config/swagger.json

Fix typo in Petstore.yaml file to address #7190. Also correct in all generated client/server samples.

Fix typo in Petstore yaml #7190

---

modules/swagger-codegen/src/main/resources/typescript-fetch/api.mustache
samples/client/petstore/typescript-fetch/builds/default/api.ts
samples/client/petstore/typescript-fetch/builds/default/git_push.sh
samples/client/petstore/typescript-fetch/builds/es6-target/api.ts
samples/client/petstore/typescript-fetch/builds/es6-target/git_push.sh
samples/client/petstore/typescript-fetch/builds/with-npm-version/api.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/git_push.sh

This change adds support for non-"application/json" MIME types in a body parameter. The logic has some hairy bits I'm not entirely happy with, but I'm trying to follow what the other language generators do:
- Instead of always emitting a default `"Content-Type"` of `"application/json"`, emit the first MIME-type from the operation's `consumes` array if available, and fall back to `"application/json"` if this is not present.
This is a little ugly; if the user needs to use a MIME-type from the `consumes` array that isn't the first one, they need to know to pass it in `options.headers["Content-Type"]`, which isn't very visible. I'd like to make the content type an explicit, required parameter on operations where there's more than one  entry in the `consumes` array, but for now I've just …

[TypeScript-Fetch] Support for non-JSON body params

---

modules/swagger-codegen/src/main/resources/typescript-fetch/api.mustache
pom.xml.circleci

For https://github.com/swagger-api/swagger-codegen/pull/6994#discussion_r153138319 
cc @TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx

[TS][Fetch] Use unescaped media type value

---

bin/windows/go-petstore.bat
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractGoCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/GoClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/GoServerCodegen.java
samples/server/petstore/go-api-server/go/README.md

@antihax
Introduce an abstract codegen base class for Go to address part of issue #6059. Should be no functional changes to Go client and server generators.

Create abstract go codegen base class #6059

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractTypeScriptClientCodegen.java

Fix for #7201: Take the modelPropertyNaming property into account again

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java
samples/client/petstore/javascript-es6/docs/FakeApi.md
samples/client/petstore/javascript-promise-es6/docs/FakeApi.md
samples/client/petstore/javascript-promise/docs/FakeApi.md
samples/client/petstore/javascript/docs/FakeApi.md

Given that JS (ES6) API client is still in beta, we'll set ES5 as the default.

[Javascript] Set ES5 as default

---

README.md

We use swagger-codegen `akka-scala` to generate sdk, [here](https://github.com/huaweicloudsdk/huaweicloud-cs-sdk)
Add huawei cloud and CS service to the company lists.

[Doc] add huawei cloud to companies list #7308

---

modules/swagger-codegen/src/main/resources/JavaPlayFramework/routes.mustache
samples/server/petstore/java-play-framework-controller-only/app/apimodels/Pet.java
samples/server/petstore/java-play-framework-controller-only/conf/routes
samples/server/petstore/java-play-framework-controller-only/public/swagger.json
samples/server/petstore/java-play-framework-fake-endpoints/app/apimodels/AdditionalPropertiesClass.java
samples/server/petstore/java-play-framework-fake-endpoints/app/apimodels/ArrayOfArrayOfNumberOnly.java
samples/server/petstore/java-play-framework-fake-endpoints/app/apimodels/ArrayOfNumberOnly.java
samples/server/petstore/java-play-framework-fake-endpoints/app/apimodels/ArrayTest.java
samples/server/petstore/java-play-framework-fake-endpoints/app/apimodels/EnumArrays.java
samples/server/petstore/java-play-framework-fake-endpoints/app/apimodels/MapTest.java
samples/server/petstore/java-play-framework-fake-endpoints/app/apimodels/MixedPropertiesAndAdditionalPropertiesClass.java
samples/server/petstore/java-play-framework-fake-endpoints/app/apimodels/Pet.java
samples/server/petstore/java-play-framework-fake-endpoints/public/swagger.json
samples/server/petstore/java-play-framework-no-bean-validation/app/apimodels/Pet.java
samples/server/petstore/java-play-framework-no-bean-validation/conf/routes
samples/server/petstore/java-play-framework-no-bean-validation/public/swagger.json
samples/server/petstore/java-play-framework-no-exception-handling/app/apimodels/Pet.java
samples/server/petstore/java-play-framework-no-exception-handling/conf/routes
samples/server/petstore/java-play-framework-no-exception-handling/public/swagger.json
samples/server/petstore/java-play-framework-no-interface/app/apimodels/Pet.java
samples/server/petstore/java-play-framework-no-interface/conf/routes
samples/server/petstore/java-play-framework-no-interface/public/swagger.json
samples/server/petstore/java-play-framework-no-swagger-ui/app/apimodels/Pet.java
samples/server/petstore/java-play-framework-no-swagger-ui/conf/routes
samples/server/petstore/java-play-framework-no-wrap-calls/app/apimodels/Pet.java
samples/server/petstore/java-play-framework-no-wrap-calls/conf/routes
samples/server/petstore/java-play-framework-no-wrap-calls/public/swagger.json
samples/server/petstore/java-play-framework/app/apimodels/Pet.java
samples/server/petstore/java-play-framework/conf/routes
samples/server/petstore/java-play-framework/public/swagger.json

Indentations were added in the route files which prevent Play Framework compilation
Rollback the template file for routes which prevented the Play Framework from compiling.

[Java Play Framework] Fix a regression bug that was introduced in a recent commit in routes

---

README.md

Link in table of contacts still links to https://github.com/swagger-api/swagger-codegen/wiki/Guidelines-for-Contribution but that page says 
>This page has been moved to https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md
This PR just links to `CONTRIBUTING.md` directly.

Update contributing guide link in README

---

modules/swagger-codegen/src/main/resources/php/model_test.mustache

This PR tweaks test doc comment.
---
> PR checklist
> Ran the shell script under `./bin/` to update Petstore sample
I could't regenerate sample test codes because ["test"](https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/php/SwaggerClient-php/test) contains real test code.
(refs: [[PHP] "test" should not contain real codes. · Issue #7200 · swagger-api/swagger-codegen](https://github.com/swagger-api/swagger-codegen/issues/7200))

[PHP] Tweak doc comment

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractGoCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/GoClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/GoServerCodegen.java
modules/swagger-codegen/src/main/resources/go/swagger.mustache
samples/client/petstore/go/go-petstore/api/swagger.yaml
samples/server/petstore/go-api-server/go/README.md

@antihax 
Output swagger yaml file when generating go client to address issue #7232.

[Go] Generate swagger yaml for go client

---

modules/swagger-codegen/src/main/resources/ruby/gemspec.mustache
samples/client/petstore-security-test/ruby/petstore.gemspec
samples/client/petstore/ruby/petstore.gemspec

- [n/a] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.
Fixes typo in Ruby gemspec. Replaces `uncommnet` to `uncomment` and removes a trailing space.

[Ruby] Correct minor typo in Ruby gemspec files

---

modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/pom.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/server/pom.mustache
samples/client/petstore/jaxrs-cxf-client/pom.xml
samples/client/petstore/jaxrs-cxf/pom.xml
samples/server/petstore/jaxrs-cxf-annotated-base-path/pom.xml
samples/server/petstore/jaxrs-cxf-non-spring-app/pom.xml
samples/server/petstore/jaxrs-cxf/pom.xml

I've updated the CXF version to the latest release and adapted transitive dependencies accordingly. Already did a similar update in #5923 half a year ago...

[Java] update CXF to latest release (3.2.1)

---

modules/swagger-codegen/src/main/resources/qt5cpp/model-body.mustache

Generated code for Docker API version 1.32. Client code communicates with dockerd with the parameters successfully interpreted by dockerd.
cc @stkrwork @ravinikam @fvarose

[C++][Qt5] use QJsonObject instead of QJsonArray for maps

---

modules/swagger-codegen/src/main/resources/swift4/model.mustache
modules/swagger-codegen/src/main/resources/swift4/modelArray.mustache
modules/swagger-codegen/src/main/resources/swift4/modelEnum.mustache
modules/swagger-codegen/src/main/resources/swift4/modelInlineEnumDeclaration.mustache
modules/swagger-codegen/src/main/resources/swift4/modelObject.mustache

The Swift4 model.mustache was getting unwieldy and difficult to read. This change simply splits model.mustache up into partials. I took care so that the changes did not result in any change to the generated code.
The model.mustache template hierarchy is now:
* model.mustache
* modelArray.mustache - for models which are arrays
* modelEnum.mustache - for models which are enums
* modelObject.mustache - for models which are normal type=object models
* modelInlineEnumDeclaration.mustache - declares Swift enums for properties which are inline enum definitions

Swift4: Split up model template into partials

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConstants.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractScalaCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ScalaClientCodegen.java

See https://github.com/swagger-api/swagger-codegen/issues/7225
Needed because some APIs (e.g. Kubernetes) include version information in packages. Stripping causes many generated API and model classes to be named the same, causing a last-one-wins situation which is unacceptable.
@clasnake  @jimschubert

[scala] make stripPackage name configurable via property

---

modules/swagger-codegen/src/main/resources/typescript-jquery/api.mustache
samples/client/petstore/typescript-jquery/default/api/PetApi.ts
samples/client/petstore/typescript-jquery/default/api/StoreApi.ts
samples/client/petstore/typescript-jquery/default/api/UserApi.ts
samples/client/petstore/typescript-jquery/npm/api/PetApi.ts
samples/client/petstore/typescript-jquery/npm/api/StoreApi.ts
samples/client/petstore/typescript-jquery/npm/api/UserApi.ts

The jQuery generator was missing the possibility to specify options for the request. I added this feature like the other generators + the possibility to specify it at the class level which I think is a must (for example, if you want to use `withCredentials` everywhere.

[Typescript jQuery] Added optional extra JQueryAjaxSettings at the class and function level

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Swift4Codegen.java

Re-organize the reserved words for Swift4

---

modules/swagger-codegen/src/main/resources/Java/beanValidationCore.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/beanValidationCore.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf-cdi/beanValidationCore.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/beanValidationCore.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/resteasy/beanValidationCore.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/spec/beanValidationCore.mustache
modules/swagger-codegen/src/main/resources/JavaSpring/beanValidationCore.mustache
samples/client/petstore/spring-cloud/src/main/java/io/swagger/api/StoreApi.java
samples/client/petstore/spring-stubs/src/main/java/io/swagger/api/StoreApi.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/api/StoreApi.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/StoreApi.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/StoreApiController.java
samples/server/petstore/springboot-beanvalidation/src/main/java/io/swagger/api/StoreApi.java
samples/server/petstore/springboot-beanvalidation/src/main/java/io/swagger/api/StoreApiController.java
samples/server/petstore/springboot-delegate-j8/src/main/java/io/swagger/api/StoreApi.java
samples/server/petstore/springboot-delegate/src/main/java/io/swagger/api/StoreApi.java
samples/server/petstore/springboot-delegate/src/main/java/io/swagger/api/StoreApiController.java
samples/server/petstore/springboot-implicitHeaders/src/main/java/io/swagger/api/StoreApi.java
samples/server/petstore/springboot-implicitHeaders/src/main/java/io/swagger/api/StoreApiController.java
samples/server/petstore/springboot-useoptional/src/main/java/io/swagger/api/StoreApi.java
samples/server/petstore/springboot-useoptional/src/main/java/io/swagger/api/StoreApiController.java
samples/server/petstore/springboot/src/main/java/io/swagger/api/StoreApi.java
samples/server/petstore/springboot/src/main/java/io/swagger/api/StoreApiController.java

Hello,
I have a json model that contains the following attribute:
```
...
"aLongNumber": {
"type": "integer",
"format": "int64",
"default": 0,
"minimum": 0,
"maximum": 9999999999
},
...
```
And the generated server code for spring does not compile as the maximum value in the `@Max` annotation is bigger than a java integer: 
```
@Min(0) @Max(9999999999) 
public Long getALongNumber() {
return aLongNumber;
}
```
I modified java/spring mustache files to add a "L" at the end of the minimum & maximum attributes. the resulting java code now compiles correctly:
```
@Min(0L) @Max(9999999999L) 
public Long getALongNumber() {
return aLongNumber;
}
```
I Hope that you will accept my contribution @bbdouglas, @JFCote, @sreeshas, @jfiala, @lukoyanov, @cbornet

[Spring][Java] fix support of long values for @Max and @Min annotations

---

CONTRIBUTING.md

Rustfmt is widely accepted in the rust community. The actual style it
enforces is not completely stable, but running a reasonably recent
rustfmt and reading the short rfc-based style guide seems better than
nothing by a long shot.
- [N/A] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
cc @frol @farcaller @bjgill

[Rust] Recommend style based on 'rustfmt' defaults

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenOperation.java
modules/swagger-codegen/src/main/resources/scala/api.mustache

Change 'equals' method to 'equalsIgnoreCase' for isRestfulIndex method in Operations.  This matches isRestfulCreate, isRestfulShow, isRestfulDestroy

Standardize all isRestfulxxx methods.

---

README.md

add swagger example to README.md

add swagger example to README.md

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractScalaCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ScalaClientCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/languages/AbstractScalaCodegenTest.java
modules/swagger-codegen/src/test/resources/integrationtests/scala/client/required-attributes-expected/src/main/scala/io/swagger/client/api/HobbiesApi.scala
modules/swagger-codegen/src/test/resources/integrationtests/scala/client/required-attributes-expected/src/main/scala/io/swagger/client/model/Hobby.scala
modules/swagger-codegen/src/test/resources/integrationtests/scala/client/required-attributes-spec.json
samples/client/petstore/scala/src/main/scala/io/swagger/client/model/ApiResponse.scala

[scala] Escape reserved words, support Array[Byte]
Previously, Array[Byte] was compiling to ArrayByte. This provides a type
mapping to output the correct type.
This also escapes reserved words with grave accents, as is most common
in Scala. Escaping with an underscore prefix breaks serialization (in
Jackson, for example) unless templates are modified manually. Escaping
using grave accent should unblock most serializers from requiring
template modifications.
This should resolve #7371.
I'll have to verify, but it may also resolve #6393.

[scala] Escape reserved words, support Array[Byte]

---

modules/swagger-codegen/src/main/resources/Javascript/model_test.mustache

Fixes a variable name typo in two commented pieces of code.

[javascript] Fixing variable name typo (instane -> instance)

---

samples/client/petstore/rust/examples/client.rs

This was handled via 'cargo fmt' on the current nightly rust. I also
moved a few lines around and deleted an old comment.
Since #7335 merged, this updates the example to match that style in the sample example.
I'll go through and update the style in more places once I don't have other PRs which would merge-conflict in flight.
cc @frol @farcaller @bjgill

[Rust] Format example with rustfmt

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ScalatraServerCodegen.java
modules/swagger-codegen/src/main/resources/scalatra/gitignore.mustache
samples/server/petstore/scalatra/.gitignore

Copy gitignore template from client
please review
@clasnake  @jimschubert  @shijinkui 
Copy gitignore template from client

[Scalatra]Added gitignore generation function

---

modules/swagger-codegen/src/main/resources/qt5cpp/helpers-header.mustache
modules/swagger-codegen/src/main/resources/qt5cpp/model-body.mustache
samples/client/petstore/qt5cpp/client/SWGHelpers.h
samples/client/petstore/qt5cpp/client/SWGPet.cpp

- Small Changes to check object against nullptr to prevent crash whe empty json body is provided
- Add QMap and QList to Helper includes.
cc @stkrwork @ravinikam @fvarose

[qt5cpp] Add nullptr guard to prevent crash when empty model is being serialized

---

samples/client/petstore/scala/src/main/scala/io/swagger/client/api/PetApi.scala
samples/server/petstore/scalatra/src/main/resources/logback.xml
samples/server/petstore/scalatra/src/main/scala/io/swagger/server/model/ApiResponse.scala

When creating the following PR, sample was generated without reflecting the last change.
https://github.com/swagger-api/swagger-codegen/pull/7393
With this commit, it will be synchronized
please review
@clasnake  @jimschubert   @shijinkui 
--

[scalatra]Rebuild Scalatra sample

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenSecurity.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java

ref: https://github.com/swagger-api/swagger-codegen/issues/7236
add vendorExtensions field in CodegenSecurity class

add vendorExtensions field in CodegenSecurity class (ref: #7236)

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaJAXRSSpecServerCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/languages/JavaJAXRSSpecServerCodegenTest.java

Fixing jaxrs-spec to handle interfaceOnly=false as intended. Added to unit tests exposing the behaviour.
To fix #7438

Fix that prevents generating interfaces when interfaceOnly is false.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SpringCodegen.java

Removed 4 lines of code.
Fixes issue #7177.

SpringCodeGen dateLibrary "java8-localdatetime" option is ignored

---

modules/swagger-codegen/src/main/resources/JavaVertXServer/MainApiVerticle.mustache

Fix for #7478 
Added getter/setter for serverPort to allow override of port for testing. Default behavior maintains port assignment from `host` value defined in spec.
@wing328 @bbdouglas (2017/07) @JFCote (2017/08) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09)

[Java][library: vertx] Expose getter/setter for serverPort to facilitate testing. Fixes #7478

---

modules/swagger-codegen/src/main/resources/rust/api.mustache

@frol @farcaller @bjgill
If `format` of the parameter is set as `UUID`, generated code can not be compiled since type of the parameter is produced as `::models::String`. As a solution, special check is added to generate `&str` type.
Code tested with:
```yaml
/pet/{petId}/uploadImage:
post:
tags:
- pets
summary: Uploads an image
operationId: uploadFile
parameters:
- name: petId
in: path
description: The id of pet to update
required: true
format: uuid
type: string
```

Fixes #7107 - [Rust] Handles UUID as string

---

modules/swagger-codegen/src/main/resources/php/api.mustache
samples/client/petstore-security-test/php/SwaggerClient-php/lib/Api/FakeApi.php
samples/client/petstore/php/SwaggerClient-php/docs/Api/FakeApi.md
samples/client/petstore/php/SwaggerClient-php/docs/Api/PetApi.md
samples/client/petstore/php/SwaggerClient-php/lib/Api/AnotherFakeApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/FakeApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/FakeClassnameTags123Api.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/PetApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/StoreApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/UserApi.php

The property `headerSelector` was created dynamically, it's a more clean approach to declare it as a member of the class.

fix: declare property headerSelector

---

modules/swagger-codegen/src/main/resources/Ada/server-skeleton-body.mustache

Fix the extraction of form parameters to use the Context to get the parameters
This pull request fixes #7513 . This fixes the Ada skeleton template:
- The Shared_Instance now handles the authsMethods to authenticate the request
- The extraction of form parameters now uses the Context object

[Ada] fix PUT request and authentication checks for the server skeleton

---

modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/pom.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/server/pom.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/pom.mustache

fix for #7123, differentiation is already in use for Jersey

#7123 use correct jackson date library when using Java 8

---

modules/swagger-codegen/src/main/resources/dart/api_client.mustache
modules/swagger-codegen/src/main/resources/dart/auth/oauth.mustache

The dart client generator was lacking oauth support completely. I took the Java implementation as a blueprint. This allows to set an `accessToken` from outside.
Hello again @ircecho  😄

[Dart] Allow setting an accessToken for OAuth

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenOperation.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java

Add operationIdOriginal to store the original operationId

Add operationIdOriginal to store the original operationId

---

modules/swagger-codegen-maven-plugin/README.md

Please use the latest version in the snippet as the older ones may contain nasty bugs (like this one https://github.com/swagger-api/swagger-codegen/issues/6122). Thanks.

Use latest version in dependencies snippet

---

modules/swagger-codegen-maven-plugin/pom.xml
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java

fixed NPE on `getComponent` call from `openAPI` object.

---

modules/swagger-codegen/src/main/resources/python/api_client.mustache
modules/swagger-codegen/src/main/resources/python/tornado/rest.mustache
samples/client/petstore-security-test/python/petstore_api/api_client.py
samples/client/petstore/python-asyncio/petstore_api/api_client.py
samples/client/petstore/python-tornado/petstore_api/api_client.py
samples/client/petstore/python/petstore_api/api_client.py

This PR will fix https://github.com/swagger-api/swagger-codegen/issues/7559 and https://github.com/swagger-api/swagger-codegen/issues/7109
1) Setting  _allow_nonstandard_methods_ flag by default to TRUE to make sure that tornado client can be used for DELETE and other methods with body.
2) six.u does not support Unicode as an input and end up throwing exception in python2 for unicode inputs. Now, using six.text_type to for reliable conversion.

Fixed unicode error and supported allow_nonstandard_methods in tornado based python client

---

modules/swagger-codegen/src/main/resources/flaskConnexion/controller.mustache

@taxpon @frol @mbohlool @cbornet @kenjones-cisco
If format of the parameter is set as UUID, generated code is broken. As a solution, special check is added similar to primitive types.
Code tested with:
```yaml
/pet/{petId}/testUuid:
post:
tags:
- pets
summary: My test with Uuid
operationId: testUuid
parameters:
- name: petId
in: path
description: The id of pet to update
required: true
format: uuid
type: string
/pet/{petId}/testString:
post:
tags:
- pets
summary: My test with String
operationId: testString
parameters:
- name: petId
in: path
description: The id of pet to update
required: true
type: string
```
Fixes #7469

[Python][Flask] Handles UUID format - Fixes #7469

---

modules/swagger-codegen-maven-plugin/src/main/java/io/swagger/codegen/plugin/CodeGenMojo.java

Issue  #7612
Checks if configOptions is null before checking if it has a property

[MAVEN PLUGIN] Checking for null configOptions before looking for property

---

modules/swagger-codegen/src/main/resources/rust/api.mustache

Changed to `{{paramName}}` instead of `body`. Otherwise generated code cannot be compiled since method parameter is named with `{{paramName}}` and there is no variable named `body`.
Test has been done with suggested yaml:
```yaml
paths:
'/ExampleResource':
post:
summary: Example
parameters:
- in: body
name: body_param_name
schema:
$ref: '#/definitions/Example'
responses:
'200':
description: Successful operation.
definitions:
Example:
description: "example"
type: string
```

[Rust] Changes hard coded body to dynamic parameter name - Fixes #6569

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ScalaGatlingCodegen.java
modules/swagger-codegen/src/main/resources/scala-gatling/build.gradle

@clasnake @jimschubert @shijinkui 
The `-BodyParams.csv` file must be named `-bodyParams.csv` as that file is used in the gatling test defnition. Futhermore all other files are also using lowercase names (e.g. `-headerParams.csv`).
close #7616

7616 correct body params filename

---

modules/swagger-codegen/src/main/resources/kotlin-client/data_class.mustache
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/models/Order.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/models/Pet.kt

The name of the property is "datatype" lowercase, as can be seen in https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenProperty.java#L10
While the name of the property is "dataType" camelCase in the https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenParameter.java#L12 file.
Using "dataType" does not work, and the type of the inner enum is null.
The confusion comes from some casing issue between 
fixes #7596
cc @jimschubert

Kotlin: Correct data_class.mustache to use proper property for inner enum data type

---

modules/swagger-codegen/src/main/resources/objc/ApiClient-body.mustache
samples/client/petstore-security-test/objc/SwaggerClient/Core/SWGApiClient.h
samples/client/petstore-security-test/objc/SwaggerClient/Core/SWGApiClient.m
samples/client/petstore-security-test/objc/git_push.sh
samples/client/petstore/objc/default/SwaggerClient/Core/SWGApiClient.m
samples/client/petstore/objc/default/git_push.sh

NOTE: There is no ObjC technical committee. Copying the Swift committee: @jgavris @ehyche @Edubits @jaz-ah
In the ObjC generator, replaced calls to the deprecated AFNetworking function `dataTaskWithRequest:completionHandler:` with the replacement function `dataTaskWithRequest:uploadProgress:downloadProgress:completionHandler:`.
The generator now incorporates the recommended migration path from AFNetworking, which is to simply call the replacement function, setting the two new parameters in the replacement function to `nil`.
The generated ObjC client no longer causes deprecation warnings in Xcode.
Fixes #7644

7644 objc deprecated afnetworking datataskwithrequest

---

modules/swagger-codegen/src/main/resources/kotlin-client/infrastructure/ApiClient.kt.mustache
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/infrastructure/ApiClient.kt

…agger-codegen generates clients from Api models without bodies for these methods.
- [X Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.
This change prevents an NPE in the case that a POST/PUT/PATCH request did not specify a model.  The Java client allows empty models, so I believe this is a valid change.
See also: https://github.com/square/okhttp/issues/751
This is a resubmission of https://github.com/swagger-api/swagger-codegen/pull/7626 due to an issue w/ email address associated with commit.
Testing:
I've consumed my forked repo branch via jitpack on an internal project and have used the feature successfully.
Unit tests pass.
CC …

[kotlin] Fix NPE for POST/PUT/PATCH with empty request models.

---

modules/swagger-codegen/src/main/resources/go/model.mustache

Previously if the type was "myEnum" it would be written as
```
type myEnum string
const (
DEMO MyEnum = "DEMO"
)
```
which would fail because of the capitalization difference. This fixes that.

Properly capitalize exported go types

---

modules/swagger-codegen/src/main/resources/php/api.mustache
samples/client/petstore/php/SwaggerClient-php/docs/Api/FakeClassnameTags123Api.md
samples/client/petstore/php/SwaggerClient-php/lib/Api/AnotherFakeApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/FakeApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/FakeClassnameTags123Api.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/PetApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/StoreApi.php
samples/client/petstore/php/SwaggerClient-php/lib/Api/UserApi.php
samples/client/petstore/php/SwaggerClient-php/tests/PetApiTest.php

refs https://github.com/swagger-api/swagger-codegen/pull/7675#issuecomment-366658641
> PetApi::findPetsByStatus() should throw an exception if an empty array is passed.

[PHP] Improve validation on empty arrays

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java

Fixes issue #7357 using the same fix as #4958
Fixes modules filename generation for the python client. Issue reported in #7357 and #4684.
The fix applied to python client generator is the same as the one applied to the Flask server in #4958.

Fix inconsistency between model name and file name in python client

---

modules/swagger-codegen/src/main/resources/JavaSpring/libraries/spring-boot/swagger2SpringBoot.mustache
modules/swagger-codegen/src/main/resources/JavaSpring/swaggerDocumentationConfig.mustache
samples/server/petstore/springboot-beanvalidation/src/main/java/io/swagger/Swagger2SpringBoot.java
samples/server/petstore/springboot-delegate-j8/src/main/java/io/swagger/Swagger2SpringBoot.java
samples/server/petstore/springboot-delegate/src/main/java/io/swagger/Swagger2SpringBoot.java
samples/server/petstore/springboot-implicitHeaders/src/main/java/io/swagger/Swagger2SpringBoot.java
samples/server/petstore/springboot-useoptional/src/main/java/io/swagger/Swagger2SpringBoot.java
samples/server/petstore/springboot-useoptional/src/main/java/io/swagger/configuration/SwaggerDocumentationConfig.java
samples/server/petstore/springboot/src/main/java/io/swagger/Swagger2SpringBoot.java

@bbdouglas @JFCote @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger
When a spring boot server stub is generated from a swagger spec which includes optional parameters and `useOptional` is true then the swagger generated from the resulting code omitted the optional parameters.  Fixed by adding `genericModelSubstitutes` to Docket generator, so `Optional<T>` is treated as the parametrised type `T` for documentation generation.
Additionally, if basePackage and apiPackage but not configPackage are specified when generating then the default io.swagger.configuration package is not scanned and so the Docket config is ignored.  Fixed by adding `configPackage` to the `ComponentScans` in Swagger2SprintBoot
Fixes #7601

[Java][Spring] fix optional query params missing in generated swagger

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaInflectorServerCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/utils/Markdown.java
modules/swagger-codegen/src/main/resources/META-INF/services/io.swagger.codegen.CodegenConfig

I do not think that I need to run something in the `./bin/` script folder. I did not change anything to the generators.
cc: @HugoMario 
cc technical-committee: @bbdouglas (2017/07) @JFCote (2017/08) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01)
On the `3.0.0` the generators for `java` and `inflector` were moved to an other repository : http://github.com/swagger-api/swagger-codegen-generators/
The Service registry was updated, but now references classes that are not present in this jar. 
```
io.swagger.codegen.languages.java.JavaClientCodegen
io.swagger.codegen.languages.java.JavaInflectorServerCodegen
```
They needs to be removed from this list and added in the other jar (I will file an other pull request for that).
=> see commit …

[3.0.0] fix in META-INF/services/io.swagger.codegen.CodegenConfig 

---

bin/jaxrs-jersey1-petstore-server.sh
bin/jaxrs-petstore-server.sh
bin/jaxrs-usetags-petstore-server.sh
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaJerseyServerCodegen.java

In the `JavaJerseyServerCodegen` class there is a `TODO` indicating that `jaxrs` should be renamed to `jaxrs-jersey`.
With the switch from version 2 to version 3, such a change can be made.
Of course on the long term, JaxRS generators will be moved to `swagger-codegen-generator`. See #7622
cc: @HugoMario

[3.0.0] Rename "jaxrs" to "jaxrs-jersey"

---

modules/swagger-codegen/src/main/resources/python/tornado/rest.mustache
samples/client/petstore/python-tornado/petstore_api/rest.py

Fixes #7737 
A response from tornado may contain a body of `None`, most usually in the case of a timeout. This needs to be handled when attempting to decode the response body.
@taxpon 
@frol 
@mbohlool 
@cbornet 
@kenjones-cisco

Fix python / tornado body handling

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConfig.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/config/CodegenConfigurator.java

With commit ab1c5f3e38d9736d34711d74ff652bc7c9d3fe15, @HugoMario has introduced a new method. With this pull request the name is fixed: `processArgumentsValues` instead of `processArgumentsValiues`

[3.0.0] Fix typo: 'Values' instead of 'Valiues'

---

modules/swagger-codegen/src/main/resources/php/ObjectSerializer.mustache
samples/client/petstore/php/SwaggerClient-php/lib/ObjectSerializer.php
samples/client/petstore/php/SwaggerClient-php/phpunit.xml.dist

Add the separator between the tempFolderPath and the sanitized filename so that the path to the file is correct.
(Fixes #7670)
Add the separator (/) between the folder path and the file path so that the returned path is correct.

[PHP] Add path & file separator (/) to return the correct path when deserializing a file

---

modules/swagger-codegen/src/main/resources/Java/ApiClient.mustache

I just fixed a little map performance Problem, because our linter keeps finding this and we'd like to use upstream template and not custom ones.

Fix performance linting problem with maps in java ApiClient template

---

modules/swagger-codegen/src/main/java/config/Config.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/ignore/CodegenIgnoreProcessor.java

With https://github.com/swagger-api/swagger-codegen-generators/issues/5 we have started to remove guava from `swagger-codegen-generators`.
This is useless if the code used by `swagger-codegen-generators` in `swagger-codegen` is still using Guava.
This pull request removes the guava imports from the code, except in the `io.swagger.codegen.languages` package (that contains already dead code => code that is no longer used and present for legacy reason until the migration is over).
The goal is to be able to use `swagger-codegen-generators` in a project configured as follow:
<dependency>
<groupId>io.swagger</groupId>
<artifactId>swagger-codegen-generators</artifactId>
<version>1.0.0-SNAPSHOT</version>
<exclusions>
<exclusion>
<groupId>com.google.guava</groupId>
<artifactId>guava</artifactId> …

[3.0.0] Migrate guava logic to java 8

---

modules/swagger-codegen/pom.xml
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java

The `3.0.0` branch uses Java 8. `java.time.*` can be used instead of `org.joda.time.*`.
Migration guide: http://blog.joda.org/2014/11/converting-from-joda-time-to-javatime.html

[3.0.0] Remove "joda-time" dependency

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaJAXRSServerCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaCXFServerCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaJAXRSCXFCDIServerCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaJAXRSSpecServerCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaJerseyServerCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaResteasyEapServerCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaResteasyServerCodegen.java

Now that JaxRS Codegen classes were migrated to `swagger-codegen-generators` (see https://github.com/swagger-api/swagger-codegen-generators/pull/29), some [cleanup tasks](https://github.com/swagger-api/swagger-codegen/wiki/Swagger-Codegen-migration-(swagger-codegen-generators-repository)#cleanup-work-in-the-swagger-codegen-repository) are requested in this repository:
* Add `@deprecated` on the old classes (incl. Javadoc comment)
---
Additional steps are requested, but I propose to delay them in order to keep the CI Build running.
* Update the `bin/*.sh` and `bin/windows/*.bat` scripts
* Run all the `bin/jaxrs-*.sh` to update the examples.
When I have updated the examples, I have noticed some errors (`HandlebarsException` ...). I will raise issues and propose fixes in the …

[3.0.0] Cleanup work after migration of JaxRS Codegen classes

---

modules/swagger-codegen/src/main/resources/php/model_generic.mustache
modules/swagger-codegen/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
samples/client/petstore/php/SwaggerClient-php/docs/Model/EnumTest.md
samples/client/petstore/php/SwaggerClient-php/lib/Model/EnumArrays.php
samples/client/petstore/php/SwaggerClient-php/lib/Model/EnumTest.php
samples/client/petstore/php/SwaggerClient-php/lib/Model/Order.php
samples/client/petstore/php/SwaggerClient-php/lib/Model/Pet.php
samples/client/petstore/php/SwaggerClient-php/tests/EnumTestTest.php

refs https://github.com/swagger-api/swagger-codegen/pull/7686#issuecomment-368200011
> 2. Non-required enum property is listed as invalid when omitted
This PR fixes the above problem.

[PHP] Non required enum property

---

modules/swagger-codegen/src/main/resources/Java/libraries/retrofit/auth/OAuth.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/auth/OAuth.mustache
samples/client/petstore/java/retrofit/src/main/java/io/swagger/client/auth/OAuth.java
samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/auth/OAuth.java
samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/auth/OAuth.java
samples/client/petstore/java/retrofit2rx2/src/main/java/io/swagger/client/auth/OAuth.java

OAuth interceptors of retrofit 1 and 2 are causing a connection leak on token refresh.
When the initial request returns 401 or 403, the token is refreshed and - if successful - a new attempt to execute the initial request is made.
But the first response is never closed in that case and causes a connection leak that okhttp3 is even logging
```
2017-12-13 23:28:03.228 [WARN ] [com.squareup.okhttp.OkHttpClient    ] - A connection to https://api.whatever.com/ was leaked. Did you forget to close a response body?
```
I discovered that problem during the development of a tado-binding for OpenHAB. The related discussion is [in the OpenHAB forum](https://community.openhab.org/t/tado-binding/37000).
To prevent the connection leak, the OAuth interceptor is now manually closing the initial response …

[Java] fix connection leak on retrofit OAuth token renewal

---

modules/swagger-codegen/src/main/resources/php/README.mustache

Fix code example from README. Variable name was missing when using Basic auth.
@jebentier (2017/07) @dkarlovi (2017/07) @mandrean (2017/08) @jfastnacht (2017/09) @ackintosh (2017/09)
In the previous change (link in the description) $config variable was accidentally removed. So the generated README file had incorrect code example when using basic auth.
https://github.com/swagger-api/swagger-codegen/commit/9ca9887de471fb82488592298e5e3e544f278aa7#diff-48c9b5ad08e2cc9e563b3ac9da839117
I have restored variable name and checked the code example after generation.

[PHP] Fix code example from README. Variable name was missing when using Basic auth.

---

modules/swagger-codegen/src/main/resources/Java/libraries/google-api-client/api.mustache
samples/client/petstore/java/google-api-client/src/main/java/io/swagger/client/api/AnotherFakeApi.java
samples/client/petstore/java/google-api-client/src/main/java/io/swagger/client/api/FakeApi.java
samples/client/petstore/java/google-api-client/src/main/java/io/swagger/client/api/FakeClassnameTags123Api.java
samples/client/petstore/java/google-api-client/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/google-api-client/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/google-api-client/src/main/java/io/swagger/client/api/UserApi.java

Java technical committee - @bbdouglas (2017/07) @JFCote (2017/08) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01)
Fixes https://github.com/swagger-api/swagger-codegen/issues/7786
This PR basically fixes a few issues with the `google-api-client` templates. 
The biggest issue is POST requests for endpoints that send empty request bodies are failing with a 415 status code (Unsupported Media Type) because the `Content-Type: application/json` isn't being sent in this case. 
A good example would be -- in our APIs we have lifecycle operations such as `POST /foo/{id}/publish` or `POST /foo/{id}/pause` which transition some entity to a different state, but no request body is required since we are simply indicating that a `publish` is taking …

[Java][google-api-client] Fix bug with empty POST request not sending content-type

---

modules/swagger-codegen/src/main/resources/JavaSpring/api.mustache
samples/client/petstore/spring-cloud/src/main/java/io/swagger/api/PetApi.java
samples/client/petstore/spring-cloud/src/main/java/io/swagger/api/StoreApi.java
samples/client/petstore/spring-cloud/src/main/java/io/swagger/api/UserApi.java
samples/client/petstore/spring-stubs/src/main/java/io/swagger/api/PetApi.java
samples/client/petstore/spring-stubs/src/main/java/io/swagger/api/StoreApi.java
samples/client/petstore/spring-stubs/src/main/java/io/swagger/api/UserApi.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/api/FakeClassnameTestApi.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/api/UserApi.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/FakeClassnameTestApi.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/UserApi.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/UserApiController.java
samples/server/petstore/springboot-beanvalidation/src/main/java/io/swagger/api/FakeClassnameTestApi.java
samples/server/petstore/springboot-beanvalidation/src/main/java/io/swagger/api/UserApi.java
samples/server/petstore/springboot-beanvalidation/src/main/java/io/swagger/api/UserApiController.java
samples/server/petstore/springboot-delegate-j8/src/main/java/io/swagger/api/FakeClassnameTestApi.java
samples/server/petstore/springboot-delegate-j8/src/main/java/io/swagger/api/UserApi.java
samples/server/petstore/springboot-delegate/src/main/java/io/swagger/api/FakeClassnameTestApi.java
samples/server/petstore/springboot-delegate/src/main/java/io/swagger/api/UserApi.java
samples/server/petstore/springboot-delegate/src/main/java/io/swagger/api/UserApiController.java
samples/server/petstore/springboot-implicitHeaders/src/main/java/io/swagger/api/FakeClassnameTestApi.java
samples/server/petstore/springboot-implicitHeaders/src/main/java/io/swagger/api/UserApi.java
samples/server/petstore/springboot-implicitHeaders/src/main/java/io/swagger/api/UserApiController.java
samples/server/petstore/springboot-useoptional/src/main/java/io/swagger/api/FakeClassnameTestApi.java
samples/server/petstore/springboot-useoptional/src/main/java/io/swagger/api/UserApi.java
samples/server/petstore/springboot-useoptional/src/main/java/io/swagger/api/UserApiController.java
samples/server/petstore/springboot/src/main/java/io/swagger/api/FakeClassnameTestApi.java
samples/server/petstore/springboot/src/main/java/io/swagger/api/UserApi.java
samples/server/petstore/springboot/src/main/java/io/swagger/api/UserApiController.java

Fixes issue #7734. Basically, the `produces` and `consumes` attributes from Springs `@RequestMapping` are omitted if they are not defined in the YAML. Before this fix they were filled with `application/json` or `""` for GET requests, where the latter leads to startup errors in the Spring Application Context. 
@bbdouglas @JFCote @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger can you review the change?

[JAVA] Fix #7734: Correct consumes/produces attributes for Spring Controllers

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java

fix for stripping prefix on single enums. See #7725

---

docker-entrypoint.sh
run-in-docker.sh

- Update run-in-docker.sh to use jdk-8
- Update docker-entrypoint.sh for 3.0 style commands
https://github.com/swagger-api/swagger-codegen/issues/7678

Bring run-in-docker.sh to date for 3.0

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Qt5CPPGenerator.java
modules/swagger-codegen/src/main/resources/qt5cpp/Project.mustache
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/Qt5CPPOptionsProvider.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/qtfivecpp/Qt5CPPOptionsTest.java
samples/client/petstore/qt5cpp/PetStore/PetStore.pro
samples/client/petstore/qt5cpp/client/SWGHelpers.h
samples/client/petstore/qt5cpp/client/SWGModelFactory.h
samples/client/petstore/qt5cpp/client/SWGObject.h
samples/client/petstore/qt5cpp/client/client.pri

I would like to fix #7784 by adding `client.pri` generation. This is a work in progress but I open this PR to address some problem I have with its implementation.
For the Pet Store example, the resulting file should look like this:
```
QT += network
HEADERS += \
$${PWD}/SWGApiResponse.h \
$${PWD}/SWGCategory.h \
$${PWD}/SWGHelpers.h \
$${PWD}/SWGHttpRequest.h \
$${PWD}/SWGModelFactory.h \
$${PWD}/SWGObject.h \
$${PWD}/SWGOrder.h \
$${PWD}/SWGPet.h \
$${PWD}/SWGPetApi.h \
$${PWD}/SWGStoreApi.h \
$${PWD}/SWGTag.h \
$${PWD}/SWGUser.h \
$${PWD}/SWGUserApi.h
SOURCES += \
$${PWD}/SWGApiResponse.cpp \
$${PWD}/SWGCategory.cpp \
$${PWD}/SWGHelpers.cpp \
$${PWD}/SWGHttpRequest.cpp \
$${PWD}/SWGOrder.cpp \
$${PWD}/SWGPet.cpp \
$${PWD}/SWGPetApi.cpp \
$${PWD}/SWGStoreApi.cpp \
$${PWD}/SWGTag.cpp \ …
```

Adding qt project generation fix #7784

---

modules/swagger-codegen/src/main/resources/elixir/deserializer.ex.mustache

When deserializing a date value the value has to be a string when calling to_iso8601. Otherwise it fails with a match error due to a is_binary() guard.

Check date value before calling to_iso8601

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwaggerYamlGenerator.java

removed null fields

---

modules/swagger-codegen/src/main/resources/JMeter/api.mustache
samples/client/petstore/jmeter/PetApi.jmx
samples/client/petstore/jmeter/StoreApi.jmx
samples/client/petstore/jmeter/UserApi.jmx

Hello @davidkiss,
In CSV DataSet ignore first line as it contains headers
Share CSV for Thread-Group instead of doing it across all threads
Use scheduler
Add variables definable through properties for:
- Rampup
- Duration
- Threads
Drop HttpClient 3.1 customization
Remove in Test Plan Element host and port as they are defined in User Variables
This fixes:
https://github.com/swagger-api/swagger-codegen/issues/7773

Improve JMeter Template : Fix Issue 7773

---

modules/swagger-generator/openapi.yaml
modules/swagger-generator/pom.xml
modules/swagger-generator/src/main/java/io/swagger/generator/online/PetstoreServlet.java
modules/swagger-generator/src/main/resources/petstore.json
modules/swagger-generator/src/main/webapp/WEB-INF/web.xml

included swagger ui content inside swagger generator service.

allow swagger-ui content in generator service.

---

modules/swagger-codegen/pom.xml

I got this error when I have opened this spec: [api.yaml](https://gist.github.com/vidyas78/737441244829907cd961ce2a986ec94c)
```
Exception in thread "main" java.lang.NoSuchMethodError: io.swagger.models.Response.responseSchema(Lio/swagger/models/Model;)Lio/swagger/models/Response;
at io.swagger.parser.util.SwaggerDeserializer.response(SwaggerDeserializer.java:1113)
at io.swagger.parser.util.SwaggerDeserializer.responses(SwaggerDeserializer.java:1067)
at io.swagger.parser.util.SwaggerDeserializer.operation(SwaggerDeserializer.java:341)
at io.swagger.parser.util.SwaggerDeserializer.path(SwaggerDeserializer.java:223)
at io.swagger.parser.util.SwaggerDeserializer.paths(SwaggerDeserializer.java:188)
at io.swagger.parser.util.SwaggerDeserializer.parseRoot(SwaggerDeserializer.java:109)
at …
```

[3.0.0] fix java.lang.NoSuchMethodError

---

modules/swagger-codegen-maven-plugin/README.md

Prefix path to `inputSpec` with maven's `${project.basedir}`. The codegen-maven-plugin will look inside the current working directory so whether a relative path works or not is depending on where the maven build is invoked from. Using `${project.basedir}` makes the path absolute.

Fix inputSpec for multi module builds

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/NodeJSServerCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/NodeJSServerOptionsProvider.java

This PR make serverPort configurable via CLI option.
Similar PR in Python: [[Python][Flask] make serverPort configurable via CLI option](https://github.com/swagger-api/swagger-codegen/pull/5821)

[NodeJS] make serverPort configurable via CLI option

---

modules/swagger-codegen/src/main/resources/typescript-node/api.mustache

@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny
Fix for generating models of type array. If the model is of type array do not generate getAttributeTypeMap function and attributeTypeMap. Should address issue #7827.

Fix typescript-node generation of array type models

---

modules/swagger-codegen/src/main/resources/typescript-node/api.mustache
samples/client/petstore/typescript-node/default/api.ts
samples/client/petstore/typescript-node/npm/.swagger-codegen-ignore
samples/client/petstore/typescript-node/npm/api.d.ts
samples/client/petstore/typescript-node/npm/api.ts

@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny
Make optional properties in models optional parameters in generated typescript-node client. Addresses issue #7791.

Make optional properties in models optional parameters

---

modules/swagger-codegen/src/main/resources/rust/api.mustache
modules/swagger-codegen/src/main/resources/rust/configuration.mustache
samples/client/petstore/rust/docs/UserApi.md
samples/client/petstore/rust/src/apis/configuration.rs
samples/client/petstore/rust/src/apis/pet_api.rs
samples/client/petstore/rust/src/apis/store_api.rs
samples/client/petstore/rust/src/apis/user_api.rs

This PR implements the minimum required to implement oauth or basic auth on the client side

[Rust] Implement minimal auth support

---

modules/swagger-codegen/src/main/resources/qt5cpp/api-body.mustache
samples/client/petstore/qt5cpp/client/SWGStoreApi.cpp

The client was crashing during the callback with a map container. This was due to an initialized pointer passed to the *setValue* method.
@ravinikam @stkrwork @fvarose @etherealjoy

[qt5cpp] Fix crash when API return a map container

---

modules/swagger-codegen/src/main/resources/cpprest/apiclient-header.mustache
modules/swagger-codegen/src/main/resources/cpprest/apiclient-source.mustache
samples/client/petstore/cpprest/ApiClient.cpp
samples/client/petstore/cpprest/ApiClient.h

Type `number` with unspecified format is generated to type `double` in C++ code. 
```
- name: some_number
in: query
type: number
required: true
```
It doesnt have corresponding ApiClient::parameterToString method.
no test were updated
@ravinikam, @stkrwork, @fvarose, @etherealjoy, @martindelille could you please review my PR?
cpprest related scripts under `./bin/` were failed by some unknown reason before i have modified source code, sorry have no enougt time to fix them

fix #7906 [cpprest] add parameterToString for number type with unspecified format

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FlaskConnexionCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java

@taxpon @frol @mbohlool @cbornet @kenjones-cisco

Additional reserved python keywords

---

modules/swagger-codegen/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml

The definition of `/fake/body-with-query-params` added in  https://github.com/swagger-api/swagger-codegen/pull/7896/commits/afb095bf5e6088a12b8a6b456975017a076d564c , should have a `fake` tag.
With this fix, operation `testBodyWithQueryParams` will be added to the FakeApi.

Fix the missing tag on FakeApi

---

modules/swagger-codegen/src/main/resources/kotlin-client/infrastructure/ApiClient.kt.mustache
samples/client/petstore/kotlin-string/docs/UserApi.md
samples/client/petstore/kotlin-string/src/main/kotlin/io/swagger/client/apis/UserApi.kt
samples/client/petstore/kotlin-string/src/main/kotlin/io/swagger/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-string/src/main/kotlin/io/swagger/client/models/Order.kt
samples/client/petstore/kotlin-string/src/main/kotlin/io/swagger/client/models/Pet.kt
samples/client/petstore/kotlin-threetenbp/docs/UserApi.md
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/io/swagger/client/apis/UserApi.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/io/swagger/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/io/swagger/client/models/Order.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/io/swagger/client/models/Pet.kt
samples/client/petstore/kotlin/docs/UserApi.md
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/apis/UserApi.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/infrastructure/ApiClient.kt

https://github.com/swagger-api/swagger-codegen/issues/7872
Default constructor of OkHttpClient generates a Builder instance implicitly, but I need to customize it. For instance, set some interceptors by calling addInterceptor()
So I add an explicit Builder to ApiClient.

[kotlin] Add OkHttpClient.Builder to ApiClient.

---

modules/swagger-codegen/src/main/resources/META-INF/services/io.swagger.codegen.CodegenConfig

Removed a duplicated entry in the config file

---

modules/swagger-codegen/src/main/resources/Java/build.gradle.mustache

The commas are invalid syntax and create the error:
```
A problem occurred evaluating project ':client'.
> Could not get unknown property 'testCompile' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

Fixing invalid syntax of commas in build.gradle of generated Java lang client (critical error)

---

modules/swagger-codegen/src/main/resources/aspnetcore/Dockerfile.mustache
samples/server/petstore/aspnetcore/.swagger-codegen/VERSION
samples/server/petstore/aspnetcore/src/IO.Swagger/Controllers/PetApi.cs
samples/server/petstore/aspnetcore/src/IO.Swagger/Controllers/StoreApi.cs
samples/server/petstore/aspnetcore/src/IO.Swagger/Controllers/UserApi.cs
samples/server/petstore/aspnetcore/src/IO.Swagger/Dockerfile
samples/server/petstore/aspnetcore/src/IO.Swagger/wwwroot/swagger-original.json

Updated the aspnetcore dockerfile to use the correct version of framework

[aspnetcore] Update Dockerfile

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwaggerYamlGenerator.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/swaggeryaml/SwaggerYamlGeneratorTest.java
modules/swagger-codegen/src/test/resources/2_0/petstore_issue_7999.json

show number as strings

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConfig.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java

In #7998 I forgot to add the new getter (`isHideGenerationTimestamp()`) and setter (`setHideGenerationTimestamp(boolean)`) method in the `CodegenConfig` interface.
Original Issue: #7997

Add HideGenerationTimestamp getter and setter in CodegenConfig

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractPhpCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AndroidClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/android/AndroidClientCodegenTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/java/AbstractJavaCodegenTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/java/jaxrs/AbstractJavaJAXRSServerCodegenTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/javascript/JavascriptClientCodegenTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/languages/JavaClientCodegenTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/php/AbstractPhpCodegenTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/php/PhpClientCodegenTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/ruby/RubyClientCodegenTest.java

See issue description in #8004.
* New getter `getInvokerPackage()` added (to be consistent with other genertors already having this method with c10099536e9e5dc9b9f49c4dbcd750f0841c4c8c
* Test cases added for any logic change with 68cc55cd5676310958f4bce72e1a8ce4289d2d27 => This demonstrates that there is no regression introduced with the main change.
* **Main change:** aff61bad8fdaeea4e54a8ec468ea14b5d346326b: values set with `setApiPackage(..)` and `setModelPackage(..)` are now taken in account [1]
[1] As I wrote it in #8004, my change is limited to all `java` generators (including `android-client`). I now have there the same behavior as for the PHP generators. See [AbstractPhpCodegenTest.java](https://github.com/swagger-api/swagger-codegen/blob/68cc55cd5676310958f4bce72e1a8ce4289d2d27/mo …

Allow to set values with setApiPackage(..) and setModelPackage(..)

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java
modules/swagger-codegen/src/main/resources/Javascript/partial_model_generic.mustache

Switch template for constructFromObject.
When `$ref` is used to reference primitive types, The value is always empty object.
This forces users to modify the Swagger file even if the API definition is valid.
Reported in #4973

Added vendorExtensions.x-isPrimitive.

---

modules/swagger-codegen/src/main/resources/typescript-angular/api.service.mustache
samples/client/petstore/typescript-angular-v2/default/api/user.service.ts
samples/client/petstore/typescript-angular-v2/npm/api/user.service.ts
samples/client/petstore/typescript-angular-v2/with-interfaces/README.md
samples/client/petstore/typescript-angular-v2/with-interfaces/api/user.service.ts
samples/client/petstore/typescript-angular-v2/with-interfaces/package.json
samples/client/petstore/typescript-angular-v2/with-interfaces/tsconfig.json
samples/client/petstore/typescript-angular-v2/with-interfaces/typings.json
samples/client/petstore/typescript-angular-v4.3/npm/api/user.service.ts
samples/client/petstore/typescript-angular-v4/npm/api/user.service.ts
samples/client/petstore/typescript-angular-v5/npm/api.module.ts
samples/client/petstore/typescript-angular-v5/npm/api/pet.service.ts
samples/client/petstore/typescript-angular-v5/npm/api/store.service.ts
samples/client/petstore/typescript-angular-v5/npm/api/user.service.ts
samples/client/petstore/typescript-angular-v5/npm/model/order.ts
samples/client/petstore/typescript-angular-v5/npm/model/pet.ts

fixes #7893
A query parameter should not be set if the value is `null`, as this would be interpreted as a string with value `"null"`

[typescript][angular] query parameter with null value should not be set

---

README.md
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
modules/swagger-codegen/src/main/resources/Java/libraries/rest-assured/api.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/rest-assured/build.gradle.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/rest-assured/build.sbt.mustache
modules/swagger-codegen/src/main/resources/Java/libraries/rest-assured/pom.mustache
samples/client/petstore/java/rest-assured/build.gradle
samples/client/petstore/java/rest-assured/build.sbt
samples/client/petstore/java/rest-assured/docs/EnumTest.md
samples/client/petstore/java/rest-assured/docs/FakeApi.md
samples/client/petstore/java/rest-assured/pom.xml
samples/client/petstore/java/rest-assured/src/main/java/io/swagger/client/api/AnotherFakeApi.java
samples/client/petstore/java/rest-assured/src/main/java/io/swagger/client/api/FakeApi.java
samples/client/petstore/java/rest-assured/src/main/java/io/swagger/client/api/FakeClassnameTags123Api.java
samples/client/petstore/java/rest-assured/src/main/java/io/swagger/client/api/PetApi.java
samples/client/petstore/java/rest-assured/src/main/java/io/swagger/client/api/StoreApi.java
samples/client/petstore/java/rest-assured/src/main/java/io/swagger/client/api/UserApi.java
samples/client/petstore/java/rest-assured/src/main/java/io/swagger/client/model/EnumTest.java

Hello, guys
As you know new rest-assured just has been released. New feature "Type instead of Class for mapping" was added in version 3.1.0. Here is the link: https://github.com/rest-assured/rest-assured/pull/980.  My aim is to use the feature in Rest-assured client. 
So, the PR: updated  rest-assured from 3.0.6  up to 3.1.0. Additional mapper was deleted for ApiClient& Now you are able to customise mapper via Rest-assured config easier than it was before.
Just want to notice that your test server (Petstore) is now returning 500 for some requests. For instance: curl -X GET "http://petstore.swagger.io/v2/store/inventory" -H  "accept: application/json"

[JAVA][Rest-assured] Version rest-assured has been updated to 3.1.0

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractKotlinCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/kotlin/KotlinClientCodegenModelTest.java

Previously the case of the names could be inconsistent if there were nested object properties. Eg. 'MyNewPet_barking_type' now becomes 'MyNewPetBarkingType'.
Ideally, we should use nested classes to take advantage of the namespace of the parent class, but this is much more work.
Previously the case of the names could be inconsistent if there were nested object properties. Eg. 'MyNewPet_barking_type' now becomes 'MyNewPetBarkingType'.
Ideally, we should use nested classes to take advantage of the namespace of the parent class, but this is much more work.
Technical committee member: @jimschubert

Camelize Kotlin model names and filenames

---

modules/swagger-codegen/src/main/resources/clojure/core.mustache
samples/client/petstore/clojure/git_push.sh
samples/client/petstore/clojure/project.clj
samples/client/petstore/clojure/src/swagger_petstore/api/pet.clj
samples/client/petstore/clojure/src/swagger_petstore/api/store.clj
samples/client/petstore/clojure/src/swagger_petstore/api/user.clj
samples/client/petstore/clojure/src/swagger_petstore/core.clj

This PR defaults content-type wildcard `*/*` into `application/json` for Clojure client. Without this change it's impossible to call some of the generated API calls (see https://github.com/swagger-api/swagger-codegen/issues/8095)

[Clojure] Default */* MIME to application/json

---

modules/swagger-codegen/src/main/resources/go/api.mustache
modules/swagger-codegen/src/main/resources/go/client.mustache
samples/client/petstore/go/go-petstore-withXml/README.md
samples/client/petstore/go/go-petstore-withXml/api/swagger.yaml
samples/client/petstore/go/go-petstore-withXml/api_another_fake.go
samples/client/petstore/go/go-petstore-withXml/api_fake.go
samples/client/petstore/go/go-petstore-withXml/api_fake_classname_tags123.go
samples/client/petstore/go/go-petstore-withXml/api_pet.go
samples/client/petstore/go/go-petstore-withXml/api_store.go
samples/client/petstore/go/go-petstore-withXml/api_user.go
samples/client/petstore/go/go-petstore-withXml/client.go
samples/client/petstore/go/go-petstore-withXml/docs/AnotherFakeApi.md
samples/client/petstore/go/go-petstore-withXml/docs/FakeApi.md
samples/client/petstore/go/go-petstore-withXml/docs/FakeClassnameTags123Api.md
samples/client/petstore/go/go-petstore-withXml/docs/PetApi.md
samples/client/petstore/go/go-petstore-withXml/docs/StoreApi.md
samples/client/petstore/go/go-petstore-withXml/docs/UserApi.md
samples/client/petstore/go/go-petstore/README.md
samples/client/petstore/go/go-petstore/api/swagger.yaml
samples/client/petstore/go/go-petstore/api_another_fake.go
samples/client/petstore/go/go-petstore/api_fake.go
samples/client/petstore/go/go-petstore/api_fake_classname_tags123.go
samples/client/petstore/go/go-petstore/api_pet.go
samples/client/petstore/go/go-petstore/api_store.go
samples/client/petstore/go/go-petstore/api_user.go
samples/client/petstore/go/go-petstore/client.go
samples/client/petstore/go/go-petstore/docs/FakeApi.md

@antihax 
Fix ordering of package context in imports after change to use "context" package rather than "golang.org/x/net/context".

Fix context import order

---

modules/swagger-codegen/src/main/resources/python/README.mustache

Sample output:
```
configuration = swagger_client.Configuration()
configuration.api_key['key'] = 'YOUR_API_KEY'
api_instance = swagger_client.GeocodingApi(swagger_client.ApiClient(configuration))
````
Note: I am not including the result of re-generating the pet shop, because that produced a few changes unrelated to mine, and I was worried. :-)

Adapt Python README template, fixes #7269

---

run-in-docker.sh

- [n/a] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [n/a] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [n/a] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.
Could not run the `run-in-docker.sh` script because the line-continuation was broken by spaces …

Remove extra spaces breaking line-continuation

---

modules/swagger-codegen/src/main/resources/Java/build.gradle.mustache

#8055 creates sources.jar and javadoc jar from gradlebuild for deploying to jfrog public snapshot repository

[codegen][java]Issue 8055: create javadoc and source jar from gradle build

---

modules/swagger-codegen/src/main/resources/typescript-node/api.mustache
samples/client/petstore/typescript-node/default/api.ts

Motivation
----
The current release of swagger-codegen does not output valid strict typescript for discriminators
Modifications
----
Updating the discriminator output to be valid strict typescript

Strict Typescript output of discriminator (PHNX-805) (#1)

---

samples/client/petstore/typescript-node/npm/package-lock.json

This PR updates typescript-node's `package-lock.json`, with the goal of avoiding an [insecure version of `hoek`](https://hackerone.com/reports/310439).

update typescript-node `package-lock.json`

---

pom.xml.circleci
pom.xml.circleci.java7

Comment out scalaz test due to sbt error

---

.travis.yml
README.md
modules/swagger-codegen-cli/pom.xml
modules/swagger-codegen-maven-plugin/pom.xml
modules/swagger-codegen/pom.xml
modules/swagger-generator/pom.xml
pom.xml
pom.xml.bash
pom.xml.circleci
pom.xml.shippable

prepare release 3.0.0-rc1

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/InlineModelResolver.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/InlineModelResolverTest.java

fixed index out of bound exception for inline empty example field.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/javascript/JavaScriptClientOptionsTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/JavaScriptOptionsProvider.java

Fixes 6530.
Add option `modelPropertyNaming` to `JavascriptClientCodegen` to support different naming conventions for properties. See issue #6530
@CodeNinjai @frol @cliffano

Add option modelPropertyNaming to javascript generator

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java

(in Windows) path delimiters `\` would be interpreted as escape sequences for a regex parameter.
Replaced `replaceFirst()` with `StringUtils.replaceOnce()`
This fixes #8218

Fixed DefaultGenerator.getHandleBars to not use a regex string for the templateDir 

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenOperation.java

getHasQueryParams only checks if queryParams is not empty, but
query params could also be defined by authMethods.
Fixes #7303
I'm not sure about the petstore script, do I have to run all of them and commit the changes?

Fix getHasQueryParams to take authMethods into account

---

modules/swagger-codegen/src/main/resources/Java/pojo.mustache

When a model class is configured with additionalProperties, getters for non-dynamic properties always return null because values have been set as properties of the map instead of the class. As a workaround, this commit ensures that we these values are retrieved from the underlying map.
This (partially) fixes #4970, fixes #5259, and fixes #5187
The issue of `additionalProperties` is not completely solved by this PR, however, we support the situation where `additionalProperties` is of type `object`, or all fields are of the same type as `additionalProperties`. I.e. it will not work if we have properties of type `integer` and `additionalProperties` of type `array` due to incorrect type casting.

Fix getter methods for Java model with additionalProperties

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java

refactor `getHandlebars` method to handle properly files paths.

---

Dockerfile

Follow up work after investigation on #8368. This does not fix any issue, just gets rid of a dependency on an unmaintained docker image.

dock3r: use an official docker base image

---

modules/swagger-codegen/src/main/resources/JavaSpring/libraries/spring-mvc/pom.mustache
samples/server/petstore/spring-mvc-j8-async/pom.xml
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/api/FakeApi.java
samples/server/petstore/spring-mvc-j8-async/src/main/java/io/swagger/model/EnumTest.java
samples/server/petstore/spring-mvc-j8-localdatetime/pom.xml
samples/server/petstore/spring-mvc-j8-localdatetime/src/main/java/io/swagger/api/FakeApi.java
samples/server/petstore/spring-mvc-j8-localdatetime/src/main/java/io/swagger/api/FakeClassnameTestApi.java
samples/server/petstore/spring-mvc-j8-localdatetime/src/main/java/io/swagger/api/UserApi.java
samples/server/petstore/spring-mvc-j8-localdatetime/src/main/java/io/swagger/model/EnumTest.java
samples/server/petstore/spring-mvc/pom.xml
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/FakeApi.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/FakeApiController.java
samples/server/petstore/spring-mvc/src/main/java/io/swagger/model/EnumTest.java

Make spring-mvc jersey tests wait that jetty is closed before terminating

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngularClientCodegen.java
modules/swagger-codegen/src/main/resources/typescript-angular/api.service.mustache
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/TypeScriptAngularClientOptionsProvider.java

@@### PR checklist
add support for Tree Shakable Providers as described in  the blog
[angular blog ](https://blog.angular.io/version-6-of-angular-now-available-cc56b0efa7a4)
add more people to review  
@sebastianhaas @TiFu @taxpon @kenisteward @Vrolijkx @roni-frantchi 
@wing328

[typescript-angular] add providedIn support

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwaggerYamlGenerator.java

added mixIn configuration on mapper to fix extra schema on swagger-yaml

---

samples/client/petstore/python/tests/test_deserialization.py

updating sample tests related to changes on #8414 

added value to required property on test data.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java

Found out that when Maven plugin is being used, the options may come already set from `additionalProperties` but the `DefaultGenerator` will override it with the default settings nonetheless. This small PR fixes that (followup for https://github.com/swagger-api/swagger-codegen/pull/8397)

OAS 3.0 - Fixing the 'useOas2' option override in case of Codegen Maven plugin usage

---

modules/swagger-codegen/src/main/resources/Java/libraries/resteasy/ApiClient.mustache
samples/client/petstore/java/resteasy/docs/EnumTest.md
samples/client/petstore/java/resteasy/docs/FakeApi.md
samples/client/petstore/java/resteasy/src/main/java/io/swagger/client/ApiClient.java
samples/client/petstore/java/resteasy/src/main/java/io/swagger/client/api/FakeApi.java
samples/client/petstore/java/resteasy/src/main/java/io/swagger/client/model/EnumTest.java

Includes and replaces #8360 
Set request headers as key:value. Was key:key
See issue: #8359

refs #8359 - Fixed setting of custom header

---

README.md

#8270 
Minor README improvement: make the usage of `-D` option more explicit so it is not confused with `java` binary -D options.

Make usage of -D more explicit in example

---

docker-entrypoint.sh

the variable wasn't used correctly. i always fell back to use `.` as homedir and never used the given ENV setting.

Docker: use correct MAVEN_CONFIG

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwaggerGenerator.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwaggerYamlGenerator.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/SwaggerOptionsProvider.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/SwaggerYamlOptionsProvider.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/swagger/SwaggerOptionsTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/swaggeryaml/SwaggerYamlOptionsTest.java

Add option to specify output filename for json/yaml targets (using `swagger.json`/`swagger.yaml` as defaults).

add output file options for swagger codegen

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java

Addendum to [PR-8463](https://github.com/swagger-api/swagger-codegen/pull/8463) to support newlines in the following sections:
- model descriptions
- model property descriptions
- operation summary
- operation description
- parameter description
- response description

[C#] Support newlines in comments in various sections

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java

Fixes issue [8475](https://github.com/swagger-api/swagger-codegen/issues/8475).

Fix for $ref as last element in allOf error

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/service/GenerationRequest.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/service/GeneratorService.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/v3/service/GeneratorServiceTest.java

Enum name needs to be in uppercase for CodegenVersion.

Use uppercase enum name for CodegenVersion in GenerationRequest

---

modules/swagger-codegen/src/main/resources/Javascript/es6/package.mustache
modules/swagger-codegen/src/main/resources/Javascript/package.mustache
samples/client/petstore-security-test/javascript/package.json
samples/client/petstore/javascript-es6/package.json
samples/client/petstore/javascript-promise-es6/package.json
samples/client/petstore/javascript-promise/package.json
samples/client/petstore/javascript/package.json

This PR bumps the pinned version for superagent to avoid [`CVE-2017-16129`](https://nvd.nist.gov/vuln/detail/CVE-2017-16129):
> ...superagent is vulnerable to ZIP bomb attacks. In a ZIP bomb attack, the HTTP server replies with a compressed response that becomes several magnitudes larger once uncompressed. If a client does not take special care when processing such responses, it may result in excessive CPU and/or memory consumption.

fix(security): bump superagent dependency 3.5.2 -> 3.7.0

---

.travis.yml
.travis.yml.bash
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenConfig.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/DefaultGenerator.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/v3/service/GeneratorServiceTest.java
modules/swagger-generator/src/test/java/io/swagger/v3/generator/online/GeneratorControllerIT.java

added method on codegen config interface to get template engine object.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenParameter.java

Codegen param tweak

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenParameter.java

refactored codegen param pojo

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwaggerGenerator.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwaggerYamlGenerator.java

fixed example fields addition

---

modules/swagger-codegen/src/main/resources/dart-jaguar/enum.mustache
modules/swagger-codegen/src/main/resources/dart/api_client.mustache
modules/swagger-codegen/src/main/resources/dart/api_helper.mustache
modules/swagger-codegen/src/main/resources/dart/auth/http_basic_auth.mustache
modules/swagger-codegen/src/main/resources/dart/enum.mustache
modules/swagger-codegen/src/test/java/io/swagger/codegen/dart/DartModelEnumTest.java
samples/client/petstore/dart/flutter_petstore/swagger/README.md
samples/client/petstore/dart/flutter_petstore/swagger/docs/Amount.md
samples/client/petstore/dart/flutter_petstore/swagger/docs/Currency.md
samples/client/petstore/dart/flutter_petstore/swagger/lib/api.dart
samples/client/petstore/dart/flutter_petstore/swagger/lib/api_client.dart
samples/client/petstore/dart/flutter_petstore/swagger/lib/model/amount.dart
samples/client/petstore/dart/flutter_petstore/swagger/lib/model/currency.dart
samples/client/petstore/dart/flutter_petstore/swagger/pubspec.yaml
samples/client/petstore/dart/swagger-browser-client/README.md
samples/client/petstore/dart/swagger-browser-client/docs/Amount.md
samples/client/petstore/dart/swagger-browser-client/docs/Currency.md
samples/client/petstore/dart/swagger-browser-client/lib/api.dart
samples/client/petstore/dart/swagger-browser-client/lib/api_client.dart
samples/client/petstore/dart/swagger-browser-client/lib/auth/http_basic_auth.dart
samples/client/petstore/dart/swagger-browser-client/lib/model/amount.dart
samples/client/petstore/dart/swagger-browser-client/lib/model/currency.dart
samples/client/petstore/dart/swagger/README.md
samples/client/petstore/dart/swagger/docs/Amount.md
samples/client/petstore/dart/swagger/docs/Currency.md
samples/client/petstore/dart/swagger/lib/api.dart
samples/client/petstore/dart/swagger/lib/api_client.dart
samples/client/petstore/dart/swagger/lib/auth/http_basic_auth.dart
samples/client/petstore/dart/swagger/lib/model/amount.dart
samples/client/petstore/dart/swagger/lib/model/currency.dart

- @ircecho 
#8426, #7498, #5454, #8353
Enum support in Dart & Flutter lacked testing of String enums. The Dart generator also had lingering `dson` refs that were removed.

[Dart] Fix Dart enums (#8426)

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenOperation.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenParameter.java

added fields, for test generated files, on codegen objects.

---

modules/swagger-codegen/src/main/resources/php-symfony/api.mustache

for php-symfony server codegen.
@dkarlovi
@mandrean
also see 
https://github.com/swagger-api/swagger-codegen/pull/8730
https://github.com/swagger-api/swagger-codegen/pull/8535

[PHP] add support deprecated phpdoc tag

---

modules/swagger-codegen/src/main/resources/kotlin-client/api.mustache
modules/swagger-codegen/src/main/resources/kotlin-client/infrastructure/ApiClient.kt.mustache
samples/client/petstore/kotlin/README.md
samples/client/petstore/kotlin/docs/Amount.md
samples/client/petstore/kotlin/docs/Currency.md
samples/client/petstore/kotlin/docs/PetApi.md
samples/client/petstore/kotlin/docs/StoreApi.md
samples/client/petstore/kotlin/docs/UserApi.md
samples/client/petstore/kotlin/settings.gradle
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/apis/PetApi.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/apis/StoreApi.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/apis/UserApi.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/models/Amount.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/models/ApiResponse.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/models/Category.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/models/Currency.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/models/Order.kt
samples/client/petstore/kotlin/src/main/kotlin/io/swagger/client/models/Pet.kt

When our server responded with a 204 message, but the body had no json content, an EOF exception would be thrown because it tried to deserialize json that did not exist. 
Our solution was to follow a similar practice as some other languages, when the the expected response type of an API call is void (for kotlin, it's Unit), then simply return void from the response deserializer. 
@HugoMario Here's a similar PR

Frozenstep kotlin void response type

---

modules/swagger-codegen/src/main/resources/php-symfony/model_variables.mustache

fix LessThan & LessThanOrEqual conditions
@dkarlovi @mandrean

[BUG] [CRITICAL] [PHP] Symfony server incorrect validation: min contstraint in max condition

---

modules/swagger-codegen/src/main/resources/php-symfony/services.mustache

fix 2 deprecated messages:
"User Deprecated: Not quoting the scalar "%swagger_server.validator%" starting with the "%" indicator character is deprecated since Symfony 3.1 and will throw a ParseException in 4.0 on line 20."
"User Deprecated: Not quoting the scalar "%swagger_server.serializer%" starting with the "%" indicator character is deprecated since Symfony 3.1 and will throw a ParseException in 4.0 in "swagger/server-bundle/Resources/config/services.yml" on line 17."
@dkarlovi 
@mandrean

[PHP] update php-symfony/services.mustache

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenOperation.java

The method getIsRestfulDestroy would return if it's a REST update instead of a REST delete because the wrong constant was used, probably a copy/paste error.
Simple fix to change the wrong constant being used in CodegenOperation.getIsRestfulDestroy()

Fixed wrong constant being used

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenParameter.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenProperty.java

Add nullable to CodegenProperty to allow code generators to support the [nullable](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schemaNullable) property in the 3.0.0, 3.0.1, and 3.0.2 specs.
Possibly Related: #2885, #4262, #6872, #7013, #7600, #8161, #8710

Add nullable property support from OAS 3.0 spec

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java

fixed NPE on composed models datatype.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/KotlinServerCodegen.java

set default library in order to fix issue.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenResponse.java

codegen response object update

---

modules/swagger-codegen/src/main/resources/python/setup.mustache

Set `certifi` to be not older than `2017.4.17` (it's the minimum version required by popular `requests` package)
Set `python-dateutil` minimum version to `2.1` (it's also minimum version required by `botocore` package)
Bump `urllib3` minimum required version to `1.23` as there were known vulnerabilities in lesser versions
PyUp Safety DB https://pyupio.github.io/safety-db/ (look for urllib3)
Snyk Vulnerability DB https://snyk.io/vuln/search?q=urllib3&type=pip
Resolves #9201

[Python] Update Minimum Required Versions in setup.mustache

---

modules/swagger-codegen/src/main/resources/python/api_client.mustache
samples/client/petstore/python-asyncio/petstore_api/api_client.py
samples/client/petstore/python-tornado/petstore_api/api_client.py
samples/client/petstore/python/petstore_api/api_client.py

We are using the swagger python client in parametrized tests with pytest to check the same operation on our API with all permission combinations. This results in thousands of tests, each with their own swagger client instance. We hit a wall after a certain number of tests, we get an error saying no more threads can be created.
The problem is in the creation of the swagger ApiClient object, which unconditionally starts a ThreadPool that is used for async calls. We do not use async calls.
I have tried to cleanup the ThreadPool but have achieved no success in reducing the number of threads the pytest process has opened.
However, the lazy initialization of the ThreadPool did work. Sync call only scenarios get zero penalty for the creation of threads and in the case of the use of async calls, …

[Python client] Lazily initialize thread pool in API client

---

modules/swagger-codegen/src/test/java/io/swagger/codegen/v3/service/GeneratorServiceTest.java

removed `enabled` flag from tests annotations.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenModel.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/resources/Java/pojo.mustache

Doesn't seem to be a name on the technical committee for Java.
The original change was made by @SergeyLyakhov and the person who authorized it @wing328  
This fixes a bug with discriminators that are specified with underscores.
In v2.4.0 a change was made which automatically populated the discriminator variable
with the class name. However whilst the variable name was converted from the model to
a java friendly variable, for example object_type to objectType in the parent class
the set variable didn't translate accordingly and so leaves uncompilable code.
As a result the generated code produced was...
```
public ParentObject() {
this.object_type = this.getClass().getSimpleName();
}
public ParentObject objectType(String objectType) {
this.objectType = objectType;
return this;
}
```
and not …

[JAVA] Generate and use variable name for setting discriminator and fix #9205

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SpringCodegen.java
modules/swagger-codegen/src/main/resources/JavaSpring/libraries/spring-cloud/apiClient.mustache
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/SpringOptionsProvider.java

@davidkiss
#9118 **[JAVA] Enable code generation for OpenFeign with Spring-Boot 2**
When using generation library spring-cloud, code will be generated with import:
`import org.springframework.cloud.netflix.feign.FeignClient;`
But when one wants to use open feign with spring boot 2, we need the following:
`import org.springframework.cloud.openfeign.FeignClient;`
Solution: Setup property to switch between both import statements (JavaSpring library `spring-cloud`) -> `apiClient.mustache`.

Enable code generation for OpenFeign with Spring-Boot 2 (#9118)

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FlaskConnexionCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java

convert pattern to perl convention instead throwing an error.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FlaskConnexionCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java

fixes an error that was canceling the code generation for python and flask

fixed out of bound exception for pattern string.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/DefaultGenerator.java

https://github.com/swagger-api/swagger-codegen/pull/9337 added `hasModel` to operations properties in `generateApis()`. This pull request adds the `hasModel` property to the support file bundle.

Add hasModel property to support file bundle

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/utils/ModelUtils.java

Filtering out missing operations from the returned array (see issue #7007 )

Fix for #7007: remove null operations

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/service/GeneratorUtil.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/service/Options.java

added capability to work with language argument options on service

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java

fixed wrong import for definition named `File`

added file as reserved words for dotnet generators

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/CodegenTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/javascript/JavaScriptInheritanceTest.java
modules/swagger-codegen/src/test/resources/2_0/allOfProperties.yaml
pom.xml
pom.xml.bash
pom.xml.circleci
pom.xml.circleci.java7
pom.xml.ios
pom.xml.jenkins
pom.xml.jenkins.java7
pom.xml.travis

Branch: Master
refs - swagger-api/swagger-parser/issues/1143 - Adding support for properties in ComposedModel
depends on https://github.com/swagger-api/swagger-parser/pull/1241

Adding support for properties in ComposedModel

---

modules/swagger-codegen/src/main/resources/php/api.mustache

Bearer token is now set in header if swagger declaration file contains bearer authentication.
For example:
```yml
components:
securitySchemes:
bearerAuth:
type: http
scheme: bearer
bearerFormat: JWT
```
closes #9495, closes #9879 
cc @dkarlovi, @mandrean

[PHP] Token Authentication headers missing for Bearer token

---

modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/cmd/Generate.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConfig.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/config/CodegenConfigurator.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java

- [xx] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
fixes #9957

allow skip model alias for generators.

---

modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/v3/cli/cmd/Generate.java
modules/swagger-codegen-cli/src/main/resources/oas3.yaml
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenConstants.java

added option to ignore import mappings.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenConfig.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/DefaultGenerator.java

add method to ignore import mapping on model generation

---

modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/cmd/Generate.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConfig.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConstants.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java

added option to ignore import mappings in model generation.

---

bin/go-petstore-server.sh
bin/go-petstore.sh
docker-entrypoint.sh

fix #10015 
Fixes the issues with `./run-in-docker.sh`, ./bin/go-petstore.sh` and `./bin/go-petstore-server.sh` scriptss

Fix the go generation scripts and docker runner script

---

README.md

Download url for current stable of the 3.x.x branch was missing in the prerequisites section of the README.
Without this specification the user may not realize their is a newer version available, specially those who don't want to clone the project and build it.
Resolves: #9475
See also: #9588
Download url for current stable of the 3.x.x branch was missing in the prerequisites section of the README.
Added download link for 3.0.16 current stable of maven repo
Without this specification the user may not realize their is a newer version available, specially those who don't want to clone the project and build it.

[docs] Maven repo missing 3.x.x versions

---

modules/swagger-codegen/src/main/resources/go/api.mustache

Co-authored-by: Mic Szillat <mic@nomaster.cc>
Fixes #7311
Whenever a parameter of type `file` was not required, the variable `localVarFile` would not be defined. This PR fixes this.
We discovered this while generating a go API and found this easy fix. Please feel free to suggest improvements.

WIP: [go] Fix undefined variable exception

---

modules/swagger-generator/pom.xml

fixes jetty-runner startup issue update jetty version to address https://github.com/eclipse/jetty.project/issues/3241 in docker minimal image

update jetty version to address https://github.com/eclipse/jetty.project/issues/3241

---

modules/swagger-codegen/src/main/resources/aspnetcore/3.0/Startup.mustache
modules/swagger-codegen/src/main/resources/aspnetcore/Startup.mustache

This PR resolves issue #10215 and has been tested per the issue's description and supposed resolution. Thanks for the opportunity to serve the ASP.NET Core community by making this and out-of-the-box working experience with the most minimal set of arguments. 
Copying @mandrean, as @mandrean is mentioned as the maintainer of the C# generators. The ASP.NET Core generator's owner isn't specifically mentioned, so if you're looking for one, I'd be willing to own it.

fixed issued with TermsOfService

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SpringCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/features/NotNullAnnotationFeatures.java
modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/pom.mustache
modules/swagger-codegen/src/main/resources/Java/pojo.mustache
modules/swagger-codegen/src/main/resources/JavaSpring/libraries/spring-boot/pom.mustache
modules/swagger-codegen/src/main/resources/JavaSpring/libraries/spring-cloud/pom.mustache
modules/swagger-codegen/src/main/resources/JavaSpring/libraries/spring-mvc/pom.mustache
modules/swagger-codegen/src/main/resources/JavaSpring/pojo.mustache
modules/swagger-codegen/src/test/java/io/swagger/codegen/DefaultGeneratorTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/JavaClientOptionsProvider.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/SpringOptionsProvider.java

Adding option NotNullJacksonAnnotation
Refs issue#6488

Adding option NotNullJacksonAnnotation

---

modules/swagger-codegen/src/main/resources/ue4cpp/api-operations-source.mustache
samples/client/petstore/ue4cpp/Private/SwaggerPetApiOperations.cpp
samples/client/petstore/ue4cpp/Private/SwaggerStoreApiOperations.cpp
samples/client/petstore/ue4cpp/Private/SwaggerUserApiOperations.cpp

Fixed handling of body parameter, now correctly outputs json without creating an additional enclosing "body" object.
Fixed cases where a file parameter is also marked isBinary.
@HugoMario Here is a fix to the PR you recently approved https://github.com/swagger-api/swagger-codegen/pull/10260

Ue4cpp fix

---

modules/swagger-codegen/src/test/java/io/swagger/codegen/v3/service/GeneratorServiceTest.java
modules/swagger-codegen/src/test/resources/3_0_0/html2BearerAuthIssue.yaml

The HTML2 documentation does not include the header `Authorization: Bearer` (Bearer Authentication) in the curl requests like it does for Basic Authentication or API Keys, for example.
Depends on: 
https://github.com/swagger-api/swagger-codegen-generators/pull/702

fix for security header html2 generator

---

README.md

The previous template engine `mustache` and file location don't apply for version 3.

Fix details about template engine and location

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java
modules/swagger-codegen/src/main/resources/Java/modelEnum.mustache
modules/swagger-codegen/src/main/resources/Java/modelInnerEnum.mustache
modules/swagger-codegen/src/main/resources/JavaInflector/enumClass.mustache
modules/swagger-codegen/src/main/resources/JavaInflector/enumOuterClass.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf-cdi/enumClass.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/enumClass.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/enumOuterClass.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/enumClass.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/enumOuterClass.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/spec/enumClass.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/spec/enumOuterClass.mustache
modules/swagger-codegen/src/main/resources/JavaPlayFramework/enumClass.mustache
modules/swagger-codegen/src/main/resources/JavaPlayFramework/enumOuterClass.mustache
modules/swagger-codegen/src/main/resources/JavaSpring/enumClass.mustache
modules/swagger-codegen/src/main/resources/JavaSpring/enumOuterClass.mustache
modules/swagger-codegen/src/main/resources/JavaVertXServer/enumOuterClass.mustache
modules/swagger-codegen/src/main/resources/java-pkmst/enumClass.mustache
modules/swagger-codegen/src/main/resources/java-pkmst/enumOuterClass.mustache

added option to write a throwing exception for unknown enums values.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/CodegenTest.java

added parent if it was not assigned by parser on allOf composed model

---

README.md

The URLs for the petstore in the `README.md` were using HTTP instead of HTTPS. Currently, if we try to access [http://petstore.swagger.io/v2/swagger.json](https://petstore.swagger.io/v2/swagger.json) we got a 302 to be redirected to the HTTPS version.
This may cause some issue, for example:
```
docker run --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli generate \
-i http://petstore.swagger.io/v2/swagger.json \
-l go \
-o /local/out/go
```
Will return:
```
[main] INFO io.swagger.parser.Swagger20Parser - reading from http://petstore.swagger.io/v2/swagger.json
[main] INFO io.swagger.parser.Swagger20Parser - reading from http://petstore.swagger.io/v2/swagger.json
[main] ERROR io.swagger.parser.SwaggerCompatConverter - failed to read resource listing …
```

[Documentation] Use HTTPS for petstore urls

---

README.md

_Swagger Codegen **3.X** supports OpenAPI version 3_
not:
_Swagger Codegen **2.X** supports OpenAPI version 3_

Update README.md: typo fixed, version 3.X vs 2.X

---

README.md

I recently had a consumer of my API reach out and ask, "The Swagger docs indicate that we’ll need a swagger.json file to build the library. I haven’t been able to find a  specific one for your api, just the example on the Swagger repo. So unless that’s forthcoming with the API creds, I might need to be pointed in the right direction." My team uses YAML for our specification file. This question ended up taking a bit of back and forth to discover what the consumer meant because we don't have a 'swagger.json' file we have a YAML file.
My proposal is to add some comments to the generate command for the pet store example to describe the different options that are being passed. The goal being to call out that the http://petstore.swagger.io/v2/swagger.json file is the specification file so that …

Add additional option descriptions to README.md

---

README.md

Added some spaces to JSON snippets in the readme for consistency between all examples.

Use same spaces style for json snippets in readme

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/JavaOptionsProvider.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/JaxRSServerOptionsProvider.java

added option to check duplicated model names.

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
pom.xml

updated parser version and required porperty from composed model

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java
modules/swagger-codegen/src/main/resources/Javascript/partial_model_generic.mustache

Issue 10516

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/GoServerCodegen.java
modules/swagger-codegen/src/main/resources/go-server/Dockerfile

added docker file for go-server generator

---

.github/actions/dotnetbuild/action.yml
.github/actions/generate/action.yml
.github/actions/generate/generate.sh
.github/actions/generate/logback.xml
.github/actions/javabuild/action.yml
.github/actions/jsbuild/action.yml
.github/actions/pythonbuild/action.yml
.github/workflows/test-framework-dotnet.yml
.github/workflows/test-framework-dynamic.yml
.github/workflows/test-framework-java.yml
.github/workflows/test-framework-js.yml
.github/workflows/test-framework-matrix.yml
.github/workflows/test-framework-python.yml
.github/workflows/test-framework-single.yml
.github/workflows/test-framework.yml

added actions for dotnet, java and js generators

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenProperty.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java

This fix helps DefaultCodegen handle uniqueitems flag for query parameters. For body parameters the issue is fixed by PR#10490

#10125 fix DefaultCodegen parsing to handle 'uniqueItems' flag

---

.github/workflows/test-framework-php.yml
.github/workflows/test-framework-v2-php.yml

fixed build path on php workflows

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngularClientCodegen.java

added option to allow use kebab file naming for typescript-angular

---

modules/swagger-generator/src/main/java/io/swagger/v3/generator/online/GeneratorController.java

https://github.com/swagger-api/swagger-codegen/pull/10525 added a `SecurityManager` to the application. When a `SecurityManager` is enabled it causes DNS queries to be cached indefinitely (ref: https://docs.oracle.com/javase/7/docs/technotes/guides/net/properties.html). This causes issues with long-running instances of swagger-generator as the IPs of DNS records change.
This PR re-enables the DNS cache invalidation with a default TTL of 60 seconds.

DNS cache timeout

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SpringCodegen.java
modules/swagger-codegen/src/main/resources/JavaSpring/LocalDateConverter.mustache
modules/swagger-codegen/src/main/resources/JavaSpring/LocalDateTimeConverter.mustache
modules/swagger-codegen/src/main/resources/JavaSpring/libraries/spring-boot/swagger2SpringBoot.mustache
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/SpringOptionsProvider.java

added custom date converter in order to fix issue.

---

pom.xml
pom.xml.jenkins

Version bump of snakeyaml to recent version in order to fix a security vulnerability in snakeyaml < 1.26.
Background: One of my clients uses Blackduck to scan security of their products.
Blackduck reported swagger-codegen-cli-2.4.21.jar to have transitive dependency to snakeyaml-1.24.
"SnakeYAML is vulnerable to a billion laughs attack. An attacker able to supply specially crafted input to the application could cause excessive memory consumption, resulting in a denial-of-service (DoS)."
SnakeYaml Issue: https://bitbucket.org/asomov/snakeyaml/issues/377/allow-configuration-for-preventing-billion
Fixed in https://bitbucket.org/asomov/snakeyaml/src/snakeyaml-1.26/
Fix Commit ID: : https://bitbucket.org/asomov/snakeyaml/commits/da11ddbd91c1f8392ea932b37fa48110fa54ed8c"

bumb version of snakeyaml to fix security issue in snakeyaml < 1.26

---

modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/cmd/Generate.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConfig.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConstants.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/config/CodegenConfigurator.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java
modules/swagger-codegen/src/main/resources/php/README.mustache
modules/swagger-codegen/src/main/resources/php/git_push.sh.mustache
modules/swagger-codegen/src/test/java/io/swagger/codegen/DefaultGeneratorTest.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/PhpClientOptionsProvider.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/php/PhpClientOptionsTest.java
modules/swagger-codegen/src/test/resources/2_0/readmePHP_149.yaml

This pr creates an option to allow the configuration of the repo base url in the readme  and git_push.sh files in php generator.
Option name: gitRepoBaseURL("string of repo url");

feat. option gitRepoBaseURL for PHP generator

---

modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/v3/cli/cmd/Generate.java
modules/swagger-codegen/pom.xml
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenConfig.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenConstants.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/config/CodegenConfigurator.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/service/GeneratorUtil.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/service/Options.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/v3/service/GeneratorServiceTest.java
modules/swagger-codegen/src/test/resources/2_0/readme149.yaml
modules/swagger-codegen/src/test/resources/3_0_0/readme149_v3.yaml

This pr creates an option to allow the configuration of the repo base url in the readme and git_push.sh files in php generator.
Option name: gitRepoBaseURL("string of repo url");
depends on (master): https://github.com/swagger-api/swagger-codegen/pull/11170
relates to:  https://github.com/swagger-api/swagger-codegen-generators/pull/962

git repository BaseUrl config option PHP

---

pom.xml
pom.xml.jenkins

As discussed with @ponelat via security email before here is the PR fixing the issue.
Bump Apache Commons IO from 2.4 to 2.11 in order to fix vulnerability in < 2.7
See related CVE: https://nvd.nist.gov/vuln/detail/CVE-2021-29425
EDIT: bumped to most lastest 2.11 version
Testing:
I run "mvn clean package" locally and all tests passed.

bump Apache Commons IO version in order to fix vulnerability 

---

pom.docker.xml
pom.xml

As discussed with @ponelat via security email before here is the PR fixing the issue.
Bump Apache Commons IO from 2.4 to 2.11 in order to fix vulnerability in < 2.7
See related CVE: https://nvd.nist.gov/vuln/detail/CVE-2021-29425
EDIT: bumped to most lastest 2.11 version
Testing:
I run "mvn clean package" locally and all tests passed.

bump Apache Commons IO version in order to fix vulnerability

---

pom.docker.xml
pom.xml

As dicussed via security mailing list, here is version bump of slf4j.
@ponelat

bump slf4j version to fix possible vulnerability

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/DefaultGenerator.java

don't overwrite already existing property useOas2
This change fixes bug described in #10879 .

don't overwrite already existing property useOas2

---

modules/swagger-codegen/src/main/resources/dart/api_client.mustache

@ircecho
Closes https://github.com/swagger-api/swagger-codegen/issues/11638
Please see that issue for a long description

[security problem] no escape for query parameters for Dart/Flutter language, so any query parameter with char like ?,&,= etc will have problems

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/templates/HandlebarTemplateEngine.java

fixed #11621 
I found out that the problem was from the wrong prefix. 
The program used to add a relative path to the absolute path !.
So I add an option to avoid adding that relative path when the client want to use its own template files.

problem of using custom template Fixed 

---

modules/swagger-generator/src/main/java/io/swagger/generator/resource/SwaggerResource.java
modules/swagger-generator/src/main/webapp/index.html

The changes in #3373 only made the variable work for client code generation. This PR adds the same logic to the server generation.
🛠 with ❤ at [Siemens](https://opensource.siemens.com/)

fix: use GENERATOR_HOST variable in server generation

---

modules/swagger-generator/src/main/java/io/swagger/generator/Bootstrap.java

During the work for #11711 I recognized that the generated OpenAPI spec does not reflect the `GENERATOR_HOST` which causes wrong generated code and non-functional snippets in the UI.
This PR improves that by passing on the relevant parts to the swagger config.
🛠 with ❤ at [Siemens](https://opensource.siemens.com/)

fix: respect configured generator URL in swagger config

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConfig.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/InlineModelResolver.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/config/CodegenConfigurator.java
modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwaggerYamlGenerator.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/options/SwaggerYamlOptionsProvider.java
modules/swagger-generator/src/main/java/io/swagger/generator/model/GeneratorInput.java
modules/swagger-generator/src/main/java/io/swagger/generator/online/Generator.java
pom.xml

This PR fixes difference in behavior introduced in , where `flatten` option while parsing the specification has been removed, if invoked from generator web service. This PR re-introduce it by default, also allowing to provide a new option `usingFlattenSpec` to turn off behavior (`usingFlattenSpec=false` results in specification not being flatten)

fix flatten option and minimize quotes

---

modules/swagger-generator/src/main/java/io/swagger/generator/Bootstrap.java
modules/swagger-generator/src/main/java/io/swagger/generator/DynamicSwaggerConfig.java

I missed that the current implementation does not consider base path and schemes in the `GENERATOR_HOST` variable correctly, making the generate spec incorrect for some scenarions.
🛠 with ❤ at [Siemens](https://opensource.siemens.com/)

fix: use information in generator host for generating spec

---

modules/swagger-codegen/src/main/resources/php/model_generic.mustache

Add `#[\ReturnTypeWillChange]` (https://php.watch/versions/8.1/ReturnTypeWillChange) to avoid deprecation notices.
Fixes https://github.com/swagger-api/swagger-codegen/issues/11820
cc. @dkarlovi and @mandrean

Make generic model compatible with PHP 8.1

---

modules/swagger-generator/Dockerfile
modules/swagger-generator/Dockerfile_root

Since #12036, the tar command is no longer available in the swagger-generator container. This PR installs the tar package to enable the custom codegen templates work for SwaggerHub On-Premise 2.x

Update swagger-generator Dockerfile to install tar

---

modules/swagger-generator/Dockerfile
modules/swagger-generator/Dockerfile_root

Changes needed to allow directory to be useable on OpenShift. OpenShift runs with a random user ID. So any directory in the container that needs to be writeable needs to be owned and writeable by the root group. See OpenShift docs here: https://docs.openshift.com/container-platform/4.11/openshift_images/create-images.html#use-uid_create-images

Create directory for custom codegen

---

pom.xml

- [ Yes ] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ N/A ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ Yes ] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [ N/A ] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a …

Fix #12135 - Upgrading slf4j to latest

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java

set default 'ignore mapping' option for java generators with 'false'

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/utils/URLPathUtil.java
modules/swagger-codegen/src/test/java/io/swagger/codegen/v3/utils/URLPathUtilTest.java

Fixes problem addressed in https://github.com/swagger-api/swagger-codegen/issues/8412. See that issue for full details.

Issue 8412: Replace vars with defaults in server evaluation.

---

README.md
modules/swagger-codegen-cli/pom.xml
modules/swagger-codegen-maven-plugin/pom.xml
modules/swagger-codegen/pom.xml
modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java
modules/swagger-generator/pom.xml
modules/swagger-generator/pom.xml.jenkins
pom.xml
pom.xml.jenkins

* [escape quotes in paths](https://github.com/swagger-api/swagger-codegen/commit/25a0296f4e9ac88f38a6ce5266f1e3980c311625)
* [prepare release 2.4.35](https://github.com/swagger-api/swagger-codegen/commit/b1f700bd63fd369f25ade39b3a704cced279dbc6)

escape quotes in paths - release 2.4.35

---

modules/swagger-codegen-cli/Dockerfile

N/A - not targeting a specific generator here and it doesn't appear any of these scripts use the docker image.
N/A - not targeting particular programming language
This addresses the `UnsupportedClassVersionError` exceptions reported in issues #12240 and #12242 for the 3.0.0 branch.
The error can be reproduced simply by running the docker image with `generate --help`:
``` 
$ docker run --rm --volume "$(pwd)":/local swaggerapi/swagger-codegen-cli-v3:3.0.50 generate --help 
Exception in thread "main" java.lang.UnsupportedClassVersionError: ch/qos/logback/classic/spi/LogbackServiceProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
at …
```

Update cli docker base to eclipse-temurin:17-jre-alpine

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenModel.java

Fix for [JAVA discriminator mapping #804 in CodegenGenerators](https://github.com/swagger-api/swagger-codegen-generators/issues/804)
JAVA discriminator mapping support added in "codegen-generators". In order to access the defined discriminator mapping in the template, a new getter added to the CodegenModel.

fix for #804 subtypeName for discriminator mapping

---

modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java

- [ x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bi/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code gen\erator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. …

Use Object instead ERROR_UNKNOWN as default value for empty  names

---

modules/swagger-codegen/src/main/resources/typescript-fetch/api.mustache

use URLSearchParams instead of url.URLSeachParams

---

modules/swagger-codegen-maven-plugin/README.md

Added info about `localVariablePrefix` which is no where else in the docs.
Added some documentation that I only found via stack overflow to fix a variable naming conflict. 
https://stackoverflow.com/questions/60506131/swagger-codegen-generates-duplicated-variables
https://github.com/swagger-api/swagger-codegen/issues/12328

Add `localVariablePrefix` to the maven plugin README.md

---

.github/workflows/docker-release-3.0.yml

closes #12321
- [ X] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ NA] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ X] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [ NA] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting …

Build swagger-codegen-cli-v3 with correct Dockerfile

---

README.md
docs/generators-configuration.md
docs/generators.md
docs/versioning.md
docs/workflow-integration.md

chore(repo): fix documentation typos 2.X

---

modules/swagger-generator/pom.xml

updated the jetty dependency to fence off few security vulnerabilities.

Vulnerability in jetty: lib upgrade
